### ISSUE TITLE
uzlib cannot compress, cannot crc32

### ISSUE THREAD

**Issue by n1kdo** [micropython/micropython#10098]
the uzlib library is missing some parts that are useful.

In particular, the methods compressobj() , compress(), flush() and crc32().

My use-case is creating PNG images from acquired data.

I could hack C code if I had to.  I used to earn my living doing that in an earlier millennium.

**Comment by n1kdo** [comment]
Sorry, this is apparently a dup of #5590.

**Comment by dpgeorge** [comment]
Closing as duplicate.
