### ISSUE TITLE
micropython firmata

### ISSUE THREAD

**Issue by crousekimo** [micropython/micropython#10105]
I try to compile micropython firmata for pico 2040 w.
I follow the steps of Appendix A.
https://datasheets.raspberrypi.com/picow/connecting-to-the-internet-with-pico-w.pdf
However, the generated firmata.uf2 cannot be connected by using putty.
May I know what happened?

**Comment by robert-hh** [comment]
So 
- building firmware.uf2 succeeded and 
- you could upload the firmware

Then you tried to connect with Putty. Does Putty complain about the wrong com port? Do you use the right COM port? Did you disable flow control with Putty?

**Comment by crousekimo** [comment]
I also compile pico 2040 firmata.
pico 2040 firmata can be connected.
I think that I connect the right com port.
You can watch the following video.
https://youtu.be/JTmaR_DVhJU
The generated uf2 can be downloaded as follows.
https://drive.google.com/file/d/10-pn1HLAkeQuAvg5AOkFi0KchrHPM-Ab/view?usp=sharing

**Comment by robert-hh** [comment]
With your firmware image I get a REPL prompt at my Pico W device.

**Comment by robert-hh** [comment]
The created image is fine. Build worked.

**Comment by AstroHuster** [comment]
@crousekimo ,
The google drive file is gone. Can you please post it again?

**Comment by jimmo** [comment]
@AstroHuster Official firmware builds are available at https://micropython.org/download/rp2-pico-w/
