### ISSUE TITLE
RP2: 1us glitch on SCK pin when switching from SPI function to Pin.OUT

### ISSUE THREAD

**Issue by pdg137** [micropython/micropython#10226]
On the RP2040, several sets of pins can be selected for each of the two SPI modules.  Sometimes we need to disable the SPI function of a pin, while leaving it in the state it was in.  For example the following code should leave pin 14 (SCK) low between `write()` and `sck(1)`:

```python
from machine import SPI, Pin

sck = Pin(14)
mosi = Pin(15)
spi = SPI(id=1, baudrate=100000, polarity=0, phase=0, sck=sck, mosi=mosi)
spi.write(bytearray([0xAA]))
sck.init(mode=Pin.OUT, value=0)
sck(1)
```

However, the *first* time it runs after reset, there's a ~1 microsecond glitch during which pin 14 floats upward. The glitch causes unreliable behavior with SPI devices if you don't take measures to avoid it (the workaround is to run `sck.init(mode=Pin.OUT, value=0)` at least once *before* using SPI.)

I tested this on the latest master branch, MicroPython v1.19.1-716-g227ea47f4, with a Raspberry Pi Pico having a 1k pull-up on pin 14.  Here is a trace of the output:

<img src="https://user-images.githubusercontent.com/466760/207778158-b1f8e8e6-0f4a-4a2b-8287-acf0e205ab19.png" width=500>

We can zoom in on it:
<img src="https://user-images.githubusercontent.com/466760/207778540-79950859-ed3a-4106-ad30-06a1f04f2e57.png" width=500>

I believe the source of the problem is here:

https://github.com/micropython/micropython/blob/master/ports/rp2/mphalport.h#L99-L103

```c
static inline void mp_hal_pin_output(mp_hal_pin_obj_t pin) {
    gpio_set_function(pin, GPIO_FUNC_SIO);
    gpio_set_dir(pin, GPIO_OUT);
    machine_pin_open_drain_mask &= ~(1 << pin);
}
```

The SPI alternate function is *disabled* before the pin is set to an output.

I don't quite understand what's going on here, but I believe that switching the order of these operations would let it work as intended.  Is there a reason to do them in this order?  Or is there some other problem?

**Comment by dpgeorge** [comment]
I think that would be fine to switch the order of those operations in `mp_hal_pin_output()`.  That would configure the GPIO to be output before switching the mux from SPI to GPIO.

**Comment by pdg137** [comment]
I can trigger the glitch every time by pre-initializing the pin as an input:

```python
from machine import SPI, Pin

sck = Pin(14)
mosi = Pin(15)

sck.init(mode=Pin.IN)
spi = SPI(id=1, baudrate=100000, polarity=0, phase=0, sck=sck, mosi=mosi)
spi.write(bytearray([0xAA]))
sck.init(mode=Pin.OUT, value=0)
sck(1)
```
(with 1k pull-up; I think my last one must have really been 10k)
![image](https://user-images.githubusercontent.com/466760/209589086-019bb45d-1d10-4c02-859e-bbf6a17e1e92.png)

Here are similar glitches in the other functions:

```python
from machine import SPI, Pin

sck = Pin(14)
mosi = Pin(15)

sck.init(mode=Pin.OUT, value=1)
spi = SPI(id=1, baudrate=100000, polarity=0, phase=0, sck=sck, mosi=mosi)
spi.write(bytearray([0xAA]))

sck.init(mode=Pin.IN, pull=Pin.PULL_DOWN)
sck.init(mode=Pin.OUT, value=1)
```
(with no pull-up)
![image](https://user-images.githubusercontent.com/466760/209589101-1522bf7f-385a-4cfb-b090-d43c8d8b4a88.png)

```python
from machine import SPI, Pin

sck = Pin(14)
mosi = Pin(15)

sck.init(mode=Pin.OUT, value=0)
spi = SPI(id=1, baudrate=100000, polarity=1, phase=0, sck=sck, mosi=mosi)
spi.write(bytearray([0xAA]))

sck.init(mode=Pin.OPEN_DRAIN, value=0)
```
(with 10k pull-up)
![image](https://user-images.githubusercontent.com/466760/209588753-07d4e101-752b-41cc-9318-7fe0a3017221.png)

That last one is weird though. It looks like `mp_hal_pin_open_drain` overwrites the value argument and always puts a zero to the output:

https://github.com/micropython/micropython/blob/master/ports/rp2/mphalport.h#L108

Is that intentional?

**Comment by dpgeorge** [comment]
> Is that intentional?

No, that's a bug.
