### ISSUE TITLE
Finish Support for Olimex ESP32-POE

### ISSUE THREAD

**Issue by ab-tools** [micropython/micropython#10220]
There has been some work in the past to support Olimex ESP32-POE
https://www.olimex.com/Products/IoT/ESP32/ESP32-POE-ISO/
which is, as far as we know, the only available PoE-enabled ESP32 board. The corresponding page on PlatformIO can be found here:
https://docs.platformio.org/en/latest/boards/espressif32/esp32-poe-iso.html

There is even already a manual, older build by @Benoit3 that supports this board available for download here:
https://github.com/micropython/micropython/issues/4502#issuecomment-1103085106

Unfortunately, however, this board did not yet make it to the official download page of MicroPython
https://micropython.org/download/?vendor=OLIMEX
and as I understand the GitHub issue linked above (although closed somehow which is the reason I create this new one here), there is only a patch that needs to be applied to make it work (ETH CLOCK on different GPIO PIN).

I just had contact also with Olimex support (Tsvetan) and they would be happy to help e. g. with providing a board for testing, if necessary. Obviously, I'm myself also more than happy to help with any testing needed, but I'm afraid I'm not capable of doing the required change myself.

I would therefore highly appreciate if someone of the more experience ESP32 maintainers here would help bringing this great PoE-enabled ESP32 board fully supported to MicroPython! :-)

Thanks a lot
Andreas

**Comment by TsvetanUsunov** [comment]
I confirm, that boards are available for who wants to verify test the above changes.

**Comment by mattytrentini** [comment]
Just FYI...

> as far as we know, the only available PoE-enabled ESP32 board

There are others, including the [wESP32](https://wesp32.com/) that does [have a board definition](https://github.com/micropython/micropython/tree/master/ports/esp32/boards/SIL_WESP32).

I also know of the [M5Stack PoE unit](https://shop.m5stack.com/products/esp32-ethernet-unit-with-poe) and [Espressif's Ethernet Kit](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/hw-reference/esp32/get-started-ethernet-kit.html). There are probably others!

But it would be great to add support for the Olimex ESP32-PoE...

**Comment by robert-hh** [comment]
There are two PRs now for these boards, #10329 and #10330. #10329 requires esp-idf v4.4, but uses the GENERIC firmware otherwise. #10330 includes board files for the device, but is based on the actual standard esp-idf v4.2.2.

**Comment by robert-hh** [comment]
It depends on which PR you choose. If you use #10229, you have to
- build with esp-idf v4.4 or later.
- add two additional arguments to the constructor specifying ref_clk_mode and ref_clk_pin. See the doc extension in the sam PR.
- and you can use the GENERIC board definitions.

If you use PR #10330, you can use the actual default esp-idf version v4.2.2, but you have to build for the board OLIMEX_ESP32_POE.

**Comment by robert-hh** [comment]
The wESP32 board uses GPIO0 for the ref_clk signal, which is the default. The Olimex ESP32 PoE boards use GPIO17. That‘s why a specific setting or configuration is needed.

**Comment by robert-hh** [comment]
Strange. I built the firmware again, loaded it to my ESP32 POE board and it works. To be sure, I updated the image on the web site. The script snipped I use is:
```
import machine, network
lan=network.LAN(mdc=machine.Pin(23), mdio=machine.Pin(18), power=machine.Pin(12),
    phy_type=network.PHY_LAN8720, phy_addr=0)
lan.active(True)
```
The difference is the power Pin.

**Comment by robert-hh** [comment]
This issue can be closed. It was anyhow more a discussion item.
