### ISSUE TITLE
Add I2S dedicated PLL clock configuration on STM32F4 platforms

### ISSUE THREAD

**Issue by jgpeiro** [micropython/micropython#10280]
On STM32F4 platforms, the I2S peripherial has a dedicated PLL with the default values in the current machine_i2s implementation. Configuring it allows to match better the user desired frequency. Also can be useful if the i2s print method shows the final configured value

The "issue" was mentioned here.

https://github.com/micropython/micropython/discussions/10266#discussion-4675699

**Comment by miketeachman** [comment]
Thanks for reporting this problem.  I'll volunteer to fix this issue.  It's the busy holiday season right now, so I can't get at this right away.  I'm thinking a 2 time horizon to submit a PR.
