### ISSUE TITLE
Stale content on value stack is source of uncollectible garbage?

### ISSUE THREAD

**Issue by pfalcon** [micropython/micropython#1029]
We don't seem to take care of clearing value stack when popping values off it. Can this cause garbage to not be released?

**Comment by dpgeorge** [comment]
Probably.  But only for slots that are still in the current stack frame (of the current bytecode function).  For deeper functions that already returned, that part of the stack is not scanned for root pointers by the GC.

**Comment by dpgeorge** [comment]
This has not really proven to be a problem in real code.  So closing.
