### ISSUE TITLE
Pin irq function doesn't work

### ISSUE THREAD

**Issue by jd3096-mpy** [micropython/micropython#10301]
On this commit 5b2929a0e69a4f3667ae9f0dbbfe3677ebc840ad
changed machin_pin.c 
but pin.irq doesn't work on esp32s3

**Comment by robert-hh** [comment]
Can you show your script which attempts to use pin.irq()?

**Comment by jd3096-mpy** [comment]
I'll test it more

**Comment by lbuque** [comment]
@jd3096-mpy I also encountered the same bug, can you tell me how to solve it?
