### ISSUE TITLE
windows version VS 2013 community edition

### ISSUE THREAD

**Issue by denfromufa** [micropython/micropython#1037]
Error	1	error LNK2019: unresolved external symbol ___builtin_expect referenced in function _mp_obj_str_format	C:\Python\micropython\windows\objstr.obj	micropython
Error	2	error LNK1120: 1 unresolved externals	C:\Python\micropython\windows\micropython.exe	1	1	micropython

**Comment by stinos** [comment]
Add these lines to windows/mpconfigport.h:
```
#define MP_LIKELY(x)                (x)
#define MP_UNLIKELY(x)              (x)
```

I'll create a PR for it.

**Comment by pfalcon** [comment]
Should be fixed via https://github.com/micropython/micropython/pull/1039
