### ISSUE TITLE
docs: Document ability to pass array to StateMachine.put 

### ISSUE THREAD

**Issue by pdw-mb** [micropython/micropython#10465]
The documentation for [StateMachine.put()](https://github.com/micropython/micropython/blame/master/docs/library/rp2.StateMachine.rst#L102) says

> Push a word onto the state machine's TX FIFO.

[The code](https://github.com/micropython/micropython/blob/master/ports/rp2/rp2_pio.c#L695) actually supports passing an `array` or `bytearray`, but this is not mentioned in the documentation, although it is used in [this example](https://github.com/micropython/micropython/blob/master/examples/rp2/pio_ws2812.py).

This is feature is quite important, as without it it's hard to reliably keep the PIO FIFO topped up.

**Comment by dpgeorge** [comment]
Fixed by a322ebafc0427f03e1423cf7642b1e6ded5a90a8
