### ISSUE TITLE
Using requests via interrupt breaks things - OSError: [Errno 103] ECONNABORTED

### ISSUE THREAD

**Issue by GM-Script-Writer-62850** [micropython/micropython#10482]
No GPIO attached hardware required

Boards: PICO W / Wiznet W5500-EVB-Pico

Firmware:
* https://micropython.org/download/W5500_EVB_PICO/
  * [v1.19.1-789-ga322ebafc (2023-01-12) .uf2](https://micropython.org/resources/firmware/W5500_EVB_PICO-20230112-unstable-v1.19.1-789-ga322ebafc.uf2)
* https://micropython.org/download/rp2-pico-w/
  * MicroPython v1.19.1 on 2022-10-11; Raspberry Pi Pico W with RP2040

Issues:
 * PICO W gives errors on failure and keep running
 * Wiznet W5500-EVB-Pico hard locks without any error shown

Core 2 runs a loops that toggles a pin that is being listened to triggering core 0's interrupt, this will generate a network request that  will  fail  in less than 12 connections

1/2 this code is just connection to the network, set board on line 8

```
from time import sleep_ms
from machine import Pin
from _thread import start_new_thread as newThread
import urequests # https://github.com/micropython/micropython-lib/blob/master/python-ecosys/urequests/urequests.py
import network

# 1 = Wiznet W5500-EVB-Pico; 0 = PICO W
board=0

if board:
	# Wiznet W5500-EVB-Pico - https://micropython.org/download/W5500_EVB_PICO/
	nic=network.WIZNET5K()
	nic.active(True)
	nic.ifconfig("dhcp")
else:
	# PICO W - https://micropython.org/download/rp2-pico-w/
	from wifi_auth import ssid, password # be sure to set your wifi login...

	wlan = network.WLAN(network.STA_IF)
	wlan.active(True)
	wlan.config(pm = 0xa11140)# Power management is very very bad, ping time is around 1000x worse and packet loss insane
	wlan.connect(ssid, password)

	while True:
		wstat=wlan.status()
		if wstat < 0 or wstat >= 3:
			break
		print('Waiting for WiFi connection...')
		sleep_ms(1000)

	if wlan.status() != 3:
		raise RuntimeError('Network connection failed!')
	else:
		print('Connected')

def http(pin):
	#print("print works...")#this will NOT crash
	print("sending request...")
	r=urequests.get("http://10.0.0.69:8080/die.php")#<?php die("OK"); ?>
	print("urequest -",r.status_code,":",r.content)
	r.close()# should not be necessary
	r=None# should not be necessary

def core1_job():
	while True:
		sleep_ms(5000)
		print('tripping interupt...')
		http_pin.toggle()

http_pin=Pin(0,Pin.OUT,value=0)
http_pin.irq(handler=http, trigger=Pin.IRQ_RISING | Pin.IRQ_FALLING) # this will crash maybe 25% of hte time

newThread(core1_job,())

while True:
	sleep_ms(1000)
	#http(0)# this will work without crashing

```

![Screenshot_20230112_110235](https://user-images.githubusercontent.com/564653/212117755-bb11d41c-7541-490a-aa98-edc37d46d80d.png)

**Comment by jonnor** [comment]
One cannot expect to make a HTTP request from an interrupt handler. The limitation and best practices are documented at: https://docs.micropython.org/en/latest/reference/isr_rules.html

In particular, note these two points:

* Avoid memory allocation: no appending to lists or insertion into dictionaries, no floating point.
* Consider using micropython.schedule to work around the above constraint.
