### ISSUE TITLE
ESP32S3 ADC Pins not working 

### ISSUE THREAD

**Issue by TGiles1998** [micropython/micropython#10585]
Hi,

When trying to read an adc value from the adc pins on the esp32s3 I get the following output:

>>> from machine import ADC
>>> adc = ADC(machine.Pin(7, machine.Pin.IN))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: invalid bits

same error for 

adc = ADC(Pin(7))

and 

pin = machine.Pin(7)
adc = ADC(pin)

Looking at the C code I notice that there is a CONFIG_IDF_TARGET_ESP32S3

https://github.com/micropython/micropython/blob/master/ports/esp32/machine_adc.c

Is there a reason this shouldnt work?

Thanks,

Thomas

**Comment by robert-hh** [comment]
There is a CONFIG_IDF_TARGET_ESP32S3 in line 70:
https://github.com/micropython/micropython/blob/67fac4ebc53db6337008ba06df7932faec80f57c/ports/esp32/machine_adc.c#L70

**Comment by TGiles1998** [comment]
@robert-hh 

Thank you for your reply. Yes thank you I found it too. have you got ADC to work on ESP32S3?

**Comment by robert-hh** [comment]
I never tried it.

**Comment by robert-hh** [comment]
I just tried it. I can run your code snippet w/o problems, and it returns values vaguely correlated to the input voltage.
`MicroPython v1.19.1-669-gd4b9df176e on 2022-11-05; LOLIN S3 with ESP32S`

**Comment by mattytrentini** [comment]
I believe this has been resolved, closing.
