### ISSUE TITLE
There is mistake in BLE simple central when disconnect is called

### ISSUE THREAD

**Issue by cz8pru** [micropython/micropython#10755]
There is code in git:
https://github.com/micropython/micropython/blob/41ed01f1394ea608bf9d055120d671e2765cd9b7/examples/bluetooth/ble_simple_central.py#L181-L185

I used that code and my device never disconnected, I found problem in "if" condition and change it to following code, which works for me:

```
def disconnect(self):
        if self._conn_handle is None:
            return
        self._ble.gap_disconnect(self._conn_handle)):
        self._reset()
```

**Comment by dpgeorge** [comment]
Thanks for the report.  Fixed by e1f211c6b503a0ad8246b289447e9985e629601c
