### ISSUE TITLE
bytes.fromhex() not available since v1.19 for rp2

### ISSUE THREAD

**Issue by pchala** [micropython/micropython#10770]
AttributeError: type object 'bytes' has no attribute 'fromhex'

Seems MICROPY_PY_BUILTINS_BYTES_HEX not defined. 

Will be nice to have it back.

**Comment by robert-hh** [comment]
It is available in the nightly builds.
```
MicroPython v1.19.1-869-gde1f1dd16 on 2023-02-16; Raspberry Pi Pico with RP2040
Type "help()" for more information.
>>> dir(bytes)
['__class__', '__name__', 'count', 'endswith', 'find', 'format', 'index', 'isalpha', 'isdigit', 'islower', 'isspace', 'isupper', 'join', 'lower', 'lstrip', 'replace', 'rfind', 'rindex', 'rsplit', 'rstrip', 'split', 'startswith', 'strip', 'upper', '__bases__', '__dict__', 'center', 'decode', 'fromhex', 'hex', 'partition', 'rpartition', 'splitlines']
```

**Comment by pchala** [comment]
`MicroPython v1.19.1 on 2022-06-18; Raspberry Pi Pico with RP2040

Type "help()" for more information.

>>> dir(bytes)
['__class__', '__name__', 'count', 'endswith', 'find', 'format', 'index', 'isalpha', 'isdigit', 'islower', 'isspace', 'isupper', 'join', 'lower', 'lstrip', 'replace', 'rfind', 'rindex', 'rsplit', 'rstrip', 'split', 'startswith', 'strip', 'upper', '__bases__', '__dict__', 'center', 'decode', 'partition', 'rpartition', 'splitlines']`

**Comment by robert-hh** [comment]
Sure. What I Meant to say : it is available in the nightly build and should be in the next release. If you need it now, install the nightly build. You asked for getting it back: it is already back.
