### ISSUE TITLE
Problems with math.frexp() and math.modf() ?

### ISSUE THREAD

**Issue by ul5255** [micropython/micropython#1081]
Both functions return strange results:

uPy:
Micro Python v1.3.8-124-g438b3d2 on 2015-01-20; PYBv1.0 with STM32F405RG
Type "help()" for more information.
```python
>>> math.frexp(10.1)
(0.0, 0)
>>> math.modf(10.1)
(0.0, 0.0)
```
cPython:
```python
Python 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)] on win32
>>> import math
>>> math.frexp(10.1)
(0.63125, 4)
>>> math.modf(10.1)
(0.09999999999999964, 10.0)
```

**Comment by dpgeorge** [comment]
The math functions themselves are simply not implemented on pyboard; they return 0.

**Comment by dpgeorge** [comment]
Now implemented.
