### ISSUE TITLE
'bytes()' function inconsistent with CPython for values > 255 

### ISSUE THREAD

**Issue by blmorris** [micropython/micropython#1093]
Uncovered this issue while researching #1092
In uPy, when a value > 255 is passed to ```bytes()``` it is treated as though it were val % 256:
```
Micro Python v1.3.9-17-g57aebe1 on 2015-01-28; linux version
>>> bytes([255])
b'\xff'
>>> bytes([256])
b'\x00'
>>> bytes([257])
b'\x01'
>>> 
```
In CPython, an exception is raised for values > 255:
```
>>> bytes([255])
b'\xff'
>>> bytes([256])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: bytes must be in range(0, 256)
>>> 
```
Posting the issue for reference, but low importance until shown otherwise.

**Comment by dpgeorge** [comment]
Check for this now added.  Only compiled in if CPYTHON_COMPAT is set.
