### ISSUE TITLE
super() doesn't work with @classmethod

### ISSUE THREAD

**Issue by North101** [micropython/micropython#10938]
This doesn't work on micropython (`rp2-pico-w-20230302-unstable-v1.19.1-915-g2bcd88d55.uf2`) but does work on python3
```
class Foo:
  value = 'test'
  @classmethod
  def foo(cls):
    return cls.value

class Bar(Foo):
  @classmethod
  def foo(cls):
    return super().foo() # also tried super(Bar, cls).foo()
```

I get the following error:
`AttributeError: type object 'type' has no attribute 'value'`

**Comment by vshymanskyy** [comment]
@dpgeorge is this expected?

**Comment by dpgeorge** [comment]
Both of the above tests should be fixed by 233f5ce661d31c8e606ff727ac0c6de27d32a715

@vshymanskyy can you please test your case with latest MicroPython?

**Comment by vshymanskyy** [comment]
Thanks! I can confirm the fix.

**Comment by dpgeorge** [comment]
Great, thanks for confirming.
