### ISSUE TITLE
Pico, Uart0 Transmit even parity problem when running in main.py without thonny

### ISSUE THREAD

**Issue by jorgen-vc** [micropython/micropython#10976]
Wrote a script:
MicroPython v1.19.1-879-g294098d28 on 2023-02-20; Raspberry Pi Pico with RP2040

main.py

from machine import UART, Pin
uart0 = UART(0,baudrate=57600, bits=8, parity = 0, stop=1, rx=Pin(1),tx=Pin(0))  # parity = 0 for EVEN parity
uart0.write("AAA")

when running in Thonny i receive the correct chars on my windows Docklight terminal program.  57600, Even, 8, 1
01000001 01000001 01000001

when disconnecting usb and the reconnect, so that it runs without thonny, i get garbage..
00000000 00111111 00111111 00111111 00111111 01000001 01000001 11010000 

..Seems that two chars is there but the rest is garbage.. 
Need the Even parity for Modbus protocol.

Best Regards
Jørgen Johannessen
Val Controls A/S2
jj@valcontrols.com

**Comment by robert-hh** [comment]
Are you sure that main.py with the UART setting is stored at the board? What is the result of:

mpremote cat main.py

Does it show the expected content?

**Comment by jorgen-vc** [comment]
Yes when dis/reconnect the power, it is sending the two first chars correctly on the uart to my pc and then garbage for the third.
I have a FTDI chip connected to UART 0 on pico, and then via USB from it to my PC.  

Dont know mpremote, should it be installed on my pc ? or is it a part of thonny ?

**Comment by robert-hh** [comment]
Yes, mpremote must be installed on the PC. You can use pip to install it. it is a very convenient command line tool for dealing with micropython devices, and it does not have  unexpected "features" like Thonny. Call `mpremote --help` for a list of commands.

**Comment by jorgen-vc** [comment]
This will take some time: Windows cant find mpremote when installed..  I can go into python and then import mpremote but then mpremote --help is not working...      But im 100% sure main.py is down in the pico.

**Comment by robert-hh** [comment]
Don't worry about mpremote. I tested it with a logic analyzer, and indeed the parity setting cannot be changed. it is always `None`. Same for stop bits. Checking with the SDK documentation, the setup call is fine. Funny that no one until now complained. I'm almost sure that I had tested that some time ago.

**Comment by robert-hh** [comment]
So the values are handed over to the RPi SDK properly. Let's dig into the SDK then,

**Comment by jorgen-vc** [comment]
Ok thanks, the i will wait for a fix in the future :) Thanks for your help.

**Comment by jorgen-vc** [comment]
Seems that Even parity is working, but the last byte is garbage to me.

**Comment by robert-hh** [comment]
For me no setting worked, no parity, not stop bits, no word length. I have a slightly updated firmware which works for me. Link: https://github.com/robert-hh/Shared-Stuff/blob/master/firmware_rp2_uartfix.uf2
You could try it.

**Comment by robert-hh** [comment]
Better leave it open, if it only works with the image I had provided for you. It's then still not in mainline.

**Comment by jorgen-vc** [comment]
Ok, great :) Then i will get a notice when it later will be released in github.

**Comment by ZacharyInDallas** [comment]
I have a project that interfaces to a device that only uses a UART with even parity.  Is there any time estimate on getting this fix done?  Is there a way to sign up to receive a notice when it is fixed?

**Comment by dpgeorge** [comment]
> Is there a way to sign up to receive a notice when it is fixed?

The fact you commented on this issue means you'll now get email notifications for this issue.  That will include a message when it's fixed (which should be today).

**Comment by dpgeorge** [comment]
Fixed by b7ea90d4cbcc3c718d2bc7d68015cb220cf50897
