### ISSUE TITLE
stm port - gcc promotes floats to doubles with printf ... type vargs

### ISSUE THREAD

**Issue by hagenkaye** [micropython/micropython#110]
So, I'm implementing printf for the stm port to do printing of floats.  It seems gcc will automatically promote floats to doubles when you use a function like printf with ... args

Interesting.  and this isn't necessarily bad.

inside the guts of the printf function there has to be a function that takes a double and converts it to a string.  It seems in my digging about for different sources that do this (it's not as easy as one might think to convert a double to the string) that modern versions of this (including musl) further take the double and convert it to a long double.  I found no variations of source code that takes a float and converts it.

So, it seems that a printf with a floating point value is going to come at some cost of converting a float to something else before it can be processed anyways.

the auto promotion of gcc from floats to doubles with ... type functions saves a lot of tweaking of existing code.  In fact I was able to use the standard printf function in the musl C library without modification.

**Comment by dpgeorge** [comment]
This can be closed because:
- stmhal never passes floats as varargs
- stmhal uses -Wdouble-promotion (and -Werror) to ensure there's no inadvertent promotion
- the core provides float and double formatting (ie conversion to string)
- a custom printf is provided by lib/utils/printf.c (and it handles all the float/double fmt codes)

**Comment by erhan9398** [comment]
if you need to print float value, you can use this  
" **printf(" float value: %.3f", static_cast<double>(float_number));** "
also you can arrange digit number after dot, for this example it is 3.
