### ISSUE TITLE
Docker image is missing `mip`

### ISSUE THREAD

**Issue by BenjaminEHowe** [micropython/micropython#11010]
[The official docker image](https://hub.docker.com/r/micropython/unix) (1.19.1) appears to be missing the `mip`  module:
```
$ micropython-dev -m mip install urequests
ImportError: no module named 'mip'
```

See [an example run via GitHub Actions](https://github.com/BenjaminEHowe/micropython-docker-mip/actions/runs/4394173624/jobs/7695064229#step:3:5).

**Comment by peterhinch** [comment]
AIUI `mip` was released after 1.19.1 and hence is available only in nightly builds. Roll on 1.20!

**Comment by mattytrentini** [comment]
Yes, I've only (manually) published docker images for releases; the intent is to publish with every commit to master. It's on my list for post-1.20...

**Comment by jonnor** [comment]
I see both 1.22 and 1.23 on https://hub.docker.com/r/micropython/unix/tags - so this should be fixed now?

**Comment by BenjaminEHowe** [comment]
Confirming that this works for v1.23.0...

```
sudo docker run -ti --rm micropython/unix:v1.23.0 sh
# micropython -m mip install urequests
Installing urequests (latest) from https://micropython.org/pi/v2 to /root/.micropython/lib
```

Thanks folks!
