### ISSUE TITLE
Can't build rp2 Port when MICROPY_HW_ENABLE_USBDEV is disabled

### ISSUE THREAD

**Issue by Sebi43217** [micropython/micropython#11056]
I’m building a project for the rp2 with no USB functionality.
* I’m unable to Build the port once i disable  MICROPY_HW_ENABLE_USBDEV in the mpconfigport.h

Is micropython without USB not supported?

<img width="978" alt="image" src="https://user-images.githubusercontent.com/43995448/225933873-bf4d7a23-0f87-4674-b741-27b8b9dea695.png">

**Comment by robert-hh** [comment]
It looks as if tinyusb must not be included in that case. Something to change in the make files. Why do you want to disable USB that way? Would it be sufficient to set `MICROPY_HW_USB_CDC (0)`?

**Comment by robert-hh** [comment]
So I have a branch now which allows to unset MICROPY_HW_ENABLE_USBDEV https://github.com/robert-hh/micropython/tree/rp2_usb_deinit
Three files are changed, and the setting for MICROPY_HW_ENABLE_USBDEV must be done in CMakeFiles.txt.

**Comment by robert-hh** [comment]
I changed that branch to have all modifications in .h and .c files. That's style-wise more consistent. No change in the Make files.

**Comment by dpgeorge** [comment]
Fixed by be686e634eede19f33612122d7254007a3d72bd0

**Comment by Sebi43217** [comment]
Thanks for the quick fix it works perfectly now.
