### ISSUE TITLE
Porting to ARM Cortex M0?

### ISSUE THREAD

**Issue by joseangeljimenez** [micropython/micropython#1106]
Hi all,

I am trying to make a rough estimation about the effort it may take me to port Micropython to a more limited platform than the current one: ARM Cortex M0, 256KB Flash, 32KB RAM.

Thanks for your comments and suggestions,
Jose Angel

P.S.: I am quite experienced with several MCU and DSP architectures. Also with Python (desktop). I have very little experience with ARM Cortex.

**Comment by dpgeorge** [comment]
It should work "out of the box"; try the directory minimal/ as a starting point.  You'll have a basic REPL, but will need to implement board-support functions yourself (or copy from stmhal/).

**Comment by dpgeorge** [comment]
If you need further help, please ask/discuss on the forum: http://forum.micropython.org

**Comment by joseangeljimenez** [comment]
Thanks a lot for your nice help!

**Comment by jjtara** [comment]
@joseangeljimenez , did you started the migration? I'm interested as well

**Comment by joseangeljimenez** [comment]
@jjtara Hi Juanjo, I am not there yet, I am currently involved in another project!
