### ISSUE TITLE
Inline assembler function causes crash

### ISSUE THREAD

**Issue by peterhinch** [micropython/micropython#1111]
Use of registers beyond r7 seems problematic. The following causes a crash
```
@micropython.asm_thumb
def foo(r0):
    mov(r9, r0)

foo(0)
```

**Comment by dpgeorge** [comment]
r9 is a callee save register, so you must somehow save/restore it in your asm function.

The lower registers are already saved for you for convenience.

So, this needs documenting :)

**Comment by peterhinch** [comment]
I also had a repeatable crash with the same code and R8. R10 seems to work. It would indeed be good to know which we can safely use - I'm using r0-r7 and need another :)

Alternatively, if registers beyond r7 are out of bounds it would be good to know how to push and pop regsters onto the stack. (I'm a noob regarding ARM assembler). Perhaps I should pursue this in the forum.

**Comment by dpgeorge** [comment]
Thumb2 calling conventions are: callee save regs r4-r11 and r13=sp.  r4-r7 are saved for you.  push/pop are not yet implemented.  Note that you can always use the "data" directive to create unsupported instructions: `data(bytesize, data, ...)`; eg `data(2, 0x1234, 0x4567)`.

**Comment by peterhinch** [comment]
TFT. I've raised a query on the forum as I guess that's a more appropriate place for coding advice.

**Comment by peterhinch** [comment]
I've documented this in the Wiki so I guess this can be closed.

**Comment by dpgeorge** [comment]
push and pop are now implemented.  Use as:
```python
push({r8, r9})
pop({r8, r9})
```

**Comment by pfalcon** [comment]
A set? Looks funky.

**Comment by dpgeorge** [comment]
I wanted it to be as close to ARM assembly as possible.  This syntax then allows for the more general instructions:
```python
ldmia(r0, {r1, r2})
stmdb(r0, {r1, r2)}
```

**Comment by pfalcon** [comment]
Yeah, I see. Though might be interesting to think how to be ready to support other archs, and then having simpler single-reg push/pops might be useful. But yes, it's arch-dependent anyway, so other asms would probably need their own syntax.

**Comment by EmmBee** [comment]
Does "push({r8, r9})" mean push r8, followed by r9 ?
If so then R9 is tos so shouldnt it be "pop({r9, r8})" ? that way you know that R9 came off the stack first...
Just an old lurker testing how sharp his razor is at splitting hairs;)

**Comment by dpgeorge** [comment]
The register list is encoded as a bit pattern: 16 bits, each one set if that register should be pushed/popped.  So the order is fixed and it doesn't matter which way you write it.  When the CPU executes them, push/stm do the opposite order to pop/ldm.  I think the higher numbered registers are pushed first, ie take the higher memory address.
