### ISSUE TITLE
Wrong float numbers in print()

### ISSUE THREAD

**Issue by ondrejkarpis** [micropython/micropython#11141]
MicroPython v1.19.1 on 2022-06-18, ESP32 module
(esp32-20220618-v1.19.1.bin)

Tested code:
for i in range(0,1000):
    print(1.0*i)

The above code should produce output in form 
1.0
2.0
...
999.0

but, for some "i" it produces:
84.00001
89.00001
94.00001
99.00001
805.9999
809.9999
813.9999
817.9999
...

**Comment by robert-hh** [comment]
This has been discussed dozen of times, and there have been changes since v19.1. Please try again with the actual nightly build.

**Comment by ondrejkarpis** [comment]
OK, the nightly build works correctly. Sorry for spamming.
