### ISSUE TITLE
Raspberry Pi Pico W problem with ntptime module

### ISSUE THREAD

**Issue by macraj** [micropython/micropython#11160]
If I'm trying to use settime function in ntptime module I get this error: Cannot find reference 'ntptime' in 'micropython.pyi'. However module seems work if I ignore error and run program. 
My import look's that: from micropython import ntptime
I tried form ntptime import settime but error was : Unresolved reference 'settime' 

I checked MicroPython modules and looks like this:

MicroPython v1.19.1-782-g699477d12 on 2022-12-20; Raspberry Pi Pico W with RP2040
Type "help()" for more information.
>>> import micropython
>>> help('modules')
__main__          gc                uasyncio/event    umachine
_boot             lwip              uasyncio/funcs    uos
_boot_fat         math              uasyncio/lock     urandom
_onewire          micropython       uasyncio/stream   ure
_rp2              mip/__init__      ubinascii         urequests
_thread           neopixel          ucollections      uselect
_uasyncio         network           ucryptolib        usocket
_webrepl          ntptime           uctypes           ussl
builtins          onewire           uerrno            ustruct
cmath             rp2               uhashlib          usys
dht               uarray            uheapq            utime
ds18x20           uasyncio/__init__ uio               uwebsocket
framebuf          uasyncio/core     ujson             uzlib
Plus any modules on the filesystem
>>>

**Comment by dpgeorge** [comment]
Please try a more recent version of the Pico W firmware.  Since commit 6250337c9cf725238df19104f7bf801e91b56e1a the Pico W includes `ntptime` by default.

**Comment by jonnor** [comment]
As mentioned, this should be fixed in releases from mid 2023 forward.
