### ISSUE TITLE
Additonal alternative mpremote disconnect keyboard shortcut

### ISSUE THREAD

**Issue by brainelectronics** [micropython/micropython#11197]
On a german MacBook keyboard, maybe on others as well, I can't use `ctrl-]` to close the `mpremote` session, see https://github.com/micropython/micropython/blob/f34af3e42e6e823f5fbff1f8e729fe14460ea4ca/tools/mpremote/mpremote/repl.py#L11

I would suggest to additionally support `ctrl-x` as done in [rshell](https://github.com/dhylands/rshell)

```python
if c in [b"\x1d", b"\x18"]:  # ctrl-] or ctrl-x, quit
    break
```

I'm of course willing to implement this complex change. I just wanted to make sure we are on the same page and I haven't missed anything else.

**Comment by dpgeorge** [comment]
I'm happy to support ctrl-x to stop mpremote's REPL.

Eventually it could also be configurable via the user's config.py file, but probably we don't need to do that just yet.
