### ISSUE TITLE
Raspberry Pi Pico core1 needs core0 being active to hit maximum performance.

### ISSUE THREAD

**Issue by nspsck** [micropython/micropython#11231]
Greetings,

As this topic describes,
[https://forums.raspberrypi.com/viewtopic.php?p=2097994#p2097994](url)
if there are tasks on both core, both of them will perform their best. However, if the task is only singed to core1, if core0 was not working at the time, the performance on core1 will be significant lower than if core0 were doing some task. **Note that this have less effect on addition.**

```python
import _thread
import time
import random

elapsed0 = 0
elapsed1 = 0

def Stress():
  start = time.ticks_us()
  count = 1
  for loops in range(100_000):
    count *= 1.1 #replace *= to += and the difference is also reduced
    r = random.randint(0, 100)
  end = time.ticks_us()
  return end - start

def Core0():
  global elapsed0; elapsed0 = Stress()

def Core1():
  global elapsed1; elapsed1 = Stress()

# Start Core 1 test
_thread.start_new_thread(Core1,())

# Start Core 0 test
# Uncomment to verify that using both core will make core1 significantly faster
# Core0()

# Uncomment section below to boost performance on core1
# while elapsed1 == 0:
#   pass

# Uncomment section below to boost performance futher on core1
# Can not be used combined with code above
# while elapsed1 == 0:
#   x = 1
  
# Wait and rint results
time.sleep(3)
print("%d us on core0, %d us on core1." % (elapsed0, elapsed1))

```

**Comment by Gadgetoid** [comment]
Looks like “sleep” calls “mp_handle_pending“ in a hot loop via “ MICROPY_EVENT_POLL_HOOK_FAST” 

https://github.com/micropython/micropython/blob/b525f1c9ec8ffa9009754578932f3fad5f63026b/extmod/utime_mphal.c#L49

https://github.com/micropython/micropython/blob/b525f1c9ec8ffa9009754578932f3fad5f63026b/ports/rp2/mphalport.c#L171

https://github.com/micropython/micropython/blob/b525f1c9ec8ffa9009754578932f3fad5f63026b/py/scheduler.c#L211

The schedular function is defined as being “called periodically”, but it strikes me that this hot loop could be enough to starve core1- somehow?

If I were to make an experimental change, it would be adding a fixed periodicity to the “ MICROPY_EVENT_POLL_HOOK_FAST” hook call in the  to more closely match what the VM does in its normal course of operations.
