### ISSUE TITLE
An error occurred when the upip package was imported after compiling and writing

### ISSUE THREAD

**Issue by Ming-XF** [micropython/micropython#11250]
I tried to integrate ESP32's ADF into micropython's idf and everything compiled fine. After writing and running, I tried to import the upip packet but could not find the upip module.

**Comment by xITmasterx** [comment]
Same here, upip does not exist for some reason.

**Comment by jimmo** [comment]
upip has been unsupported for a long time. In v1.20 it was replaced by `mip`. See release notes https://github.com/micropython/micropython/releases/tag/v1.20.0 and documentation https://docs.micropython.org/en/latest/reference/packages.html#installing-packages-with-mip
