### ISSUE TITLE
mpy-cross killed

### ISSUE THREAD

**Issue by ruihua-code** [micropython/micropython#11258]
### description
mpy-cross build mpy not work!

<img width="395" alt="image" src="https://user-images.githubusercontent.com/15189454/232023382-acce5923-10b7-41bc-9891-e496805c0bb7.png">

### platform
- Mac book Pro(M1)

### code
```bash
cd mpy-cross
make
./build/mpy-cross -V
# output:
# zsh: killed     ./build/mpy-cross -V
```

Has anyone seen this before? Please take a look

thanks

**Comment by dlech** [comment]
Can you make a debug build and get a stack track of the crash?

**Comment by ruihua-code** [comment]
A reinstallation of the mac OS fixed the problem, which was suspected to be the python version
