### ISSUE TITLE
docs: Porting MicroPython instructions lack two lines of code

### ISSUE THREAD

**Issue by cyber-murmel** [micropython/micropython#11261]
I tried following the porting tutorial and encountered two hiccups.
Apparently this can be fixed by adding the following to the `main.c`

```c
#include "py/builtin.h"
```

and this to the `Makefile`

```make
SRC_QSTR += shared/readline/readline.c shared/runtime/pyexec.c
```

**Comment by dlech** [comment]
Would you like to make a pull request to fix this?

**Comment by cyber-murmel** [comment]
https://github.com/micropython/micropython/pull/11262
