### ISSUE TITLE
docs: <gsbjdusb></hdidj>>

### ISSUE THREAD

**Issue by Bitsuebig** [micropython/micropython#11321]
* Please search existing issues before raising a new issue. For questions about MicroPython or for help using MicroPython, or any sort of "how do I?" requests, please use the Discussions tab instead.

* Describe what was missing from the documentation and/or what was incorrect/incomplete.

* If possible, please link to the relevant page on https://docs.micropython.org/

* Remove all placeholder text above before submitting.

**Comment by robert-hh** [comment]
Looks like a submission error.
