### ISSUE TITLE
Micropython reset loop after flashing

### ISSUE THREAD

**Issue by boredcoder411** [micropython/micropython#11378]
I recently bought a nodemcu amica, which uses the ESP8266 microcontroller. The problem I'm having is that when I start the chip up, and open puTTY, the chip just sends this message:
![Screenshot (64)](https://user-images.githubusercontent.com/105937655/235344089-31d20156-cd5c-4c7f-a608-1331f781dfb3.png)
And then while restarting prints this for about half a second:
![Screenshot (65)](https://user-images.githubusercontent.com/105937655/235344147-d3c88ec6-483f-47c0-aa7c-d8977cdfd97a.png)

All this happens when flashing this binary:
esp8266-20230426-v1.20.0.bin
Does anyone know why this is?

**Comment by robert-hh** [comment]
Try different flash modes when flashing the firmware. The default is DIO, but in many case it has to be DOUT
P.S.: This behavior has been reported gazillion times in the Forum and Discussions. So you may find more answers there.

**Comment by boredcoder411** [comment]
On second thought, I will just use the nodemcu firmware. Thankyou for you time though!
