### ISSUE TITLE
Busy `try: except:` loop prevents `KeyboardInterrupt` to break the loop

### ISSUE THREAD

**Issue by josuah** [micropython/micropython#11682]
When inserting this in paste mode:

```python
while True:
    try:
        for i in range(1000):
            pass
        raise(TypeError("Any error you actually want to catch"))
    except:
        pass
```

Hitting Ctrl-C (KeyboardInterrupt) does not trigger a KeyboardInterrupt anymore.
We stay in the end of paste mode, the loop being executed continuously.

On the other hand, when reducing 1000 to 100, we end-up seeing a KeyboardInterrupt:

```python
MicroPython v1.20.0-117-ged7a3b11d on 2023-06-01; Monocle on nRF52832
Type "help()" for more information.
>>> 
paste mode; Ctrl-C to cancel, Ctrl-D to finish
=== while True:
===     try:
===         for i in range(100):
===             pass
===         raise(TypeError("Any error you actually want to catch"))
===     except:
===         pass
=== 
Traceback (most recent call last):
  File "<stdin>", in <module>
KeyboardInterrupt: 
```

The bug was reproduced with https://github.com/brilliantlabsAR/monocle-micropython/ but we do not really have anything changed in the `micropython` (git submodule) dir.

In fact, it can even be reproduced in cPython!

```python
lap1:$ python
Python 3.11.3 (main, May 10 2023, 12:13:23) [GCC 12.2.1 20220924] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> while True:
...     try:
...         for i in range(1000):
...             pass
...         raise(TypeError("Any error you actually want to catch"))
...     except:
...         pass
...
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyboardInterrupt
>>>
KeyboardInterrupt
>>>
KeyboardInterrupt
>>>
KeyboardInterrupt
>>>
```

Is this something we want to address? On cPython, it is possible to kill python externally, but in MicroPython, is it desired to have any higher priority in MicroPython nlr_raise() calls?

By adding [logging into `nlr_raise()`](https://github.com/micropython/micropython/blob/master/py/nlr.h#L177) we could observe that both Ctrl-C and the python code's error call `nlr_raise()`.

Is there an opportunity to inject a check for scheduled keyboard exception [`[1]`][1] [`[2]`][2] before nlr_raise() is called [`[3]`][3]?

[1]: https://github.com/micropython/micropython/blob/master/py/scheduler.c#L50
[2]: https://github.com/micropython/micropython/blob/master/py/scheduler.c#L34
[3]: https://github.com/micropython/micropython/blob/master/py/runtime.c#L1635

I am not entirely sure what is going on here, as once the `KeyboardInterrupt` is scheduled, it should be caught upon the next check while running the busy `try:` loop's code (the `for i in range()`)?

Congrats on being bug-to-bug compatible with cPython with a different implementation!

**Comment by robert-hh** [comment]
To cite and old joke: "This is not a bug, it is a feature".
KeyboardInterrupt is the exception which is raised when Ctrl-C is pushed. Your open except: in the test code absorbs that one as well. To catch ctrl-c again, you have to add another exept clause, like:


except KeyboardInterrupt:
    raise
except:
    pass

**Comment by robert-hh** [comment]
All kudos go to Damien, who created MicroPython.

**Comment by thyrrestrup** [comment]
You could look into the mp_sched_vm_abort mechanism if you want the abort to be uncatchable. This is only useful if you implement a custom handler on the C side.

**Comment by pykhaz** [comment]
I've been chatting about that with _GPT_ and, as I understood, <Ctrl-C> reaches micropython and might be not passed to the script; unless the script is run with
`exec(file.read())`
A simple function makes it a bit easier to run a script being _already_ in µpy repl:

    # /home/pi/uc/code/lib/m_system/system.py

    def run(filepath, args=None):
        """Running a py file on esp board"""

        if args is None:
            args = []

        if isinstance(args, str):
            args = args.split(" ")

        global argv_
        argv_ = args

        with open(filepath, "r") as fin:
            argv_ = args
            exec(fin.read(), globals())

It is even possible to simulate passing cli args.
