### ISSUE TITLE
Add Chinese characters input in REPL or terminal

### ISSUE THREAD

**Issue by wuhao19920619** [micropython/micropython#11697]
It's clear that micropython support unicode. `print("\u0031")`  can display chinese characters in REPL. However If I try to input some chinese characters directly, the terminal just remove it and nothing is input

**Comment by mattytrentini** [comment]
Please see #2789 - the MicroPython _interpreter_ supports unicode but the _REPL_ is parsed character-by-character. Note that you can use paste mode (Ctrl+E) to paste a block of code where unicode will be correctly interpreted.

I'll close this ticket but please follow #2789 for updates.
