### ISSUE TITLE
Implement Defragmenting Memory Manger

### ISSUE THREAD

**Issue by vitiral** [micropython/micropython#1169]
This is one of the main issues in @dpgeorge [development wishlist](http://forum.micropython.org/viewtopic.php?f=3&t=455) on the forum, yet it doesn't have an issue associated with it.

The goal is to create a defragmenting memory manager that is reasonably fast with a reasonably small memory footprint. I am currently implementing this and am in the pre-alpha stages with my [tinymem memory manager](https://github.com/cloudformdesign/tinymem). There is a [forum thread](http://forum.micropython.org/viewtopic.php?f=3&t=591) detailing my development on that, so I won't use this issue to update anything but that which is directly related to work on uPython.

Task List:
- Complete #1168
- Integrate tinymem into uPython
- Validate tests
- Tweak parameters / optimize
- determine release schedule

**Comment by pfalcon** [comment]
There was no progress on this issue for a long time, suppose of #1168 and #1169, it's enough to have just one.
