### ISSUE TITLE
The new micropython runs slower.

### ISSUE THREAD

**Issue by Zhengqinze05** [micropython/micropython#11774]
I am using the board of ESP32S3. When I ran the test code using an old version of micropython, it took 55ms. when I use a new version of micropython, it takes 79ms. May I ask what may be the reason for this?
The commit id of my new micropython is fd277704c458784a0e25ae87cf7190833661185d.
The commit id of my old micropython is 2b3667910dfd316b9041cd45c9ca759773b2732e.
My testing program below：
![2299cf7268764004efb6d9b2064c47c](https://github.com/micropython/micropython/assets/92145359/22a99f67-fd3f-4fb5-9466-a740773b6b57)

This is the result of running an old version of micropython:

![f1a21afb9c89d63fc1334e7a2b4f177](https://github.com/micropython/micropython/assets/92145359/3ac97a5e-88e8-42f3-93a7-6953c474e4ae)

This is the result of running an new version of micropython:

![5ca5db3ee3b08879f51d13ca0bc22ba](https://github.com/micropython/micropython/assets/92145359/c3da3633-7646-44d6-bb5f-8ec58055cd74)

**Comment by dpgeorge** [comment]
Were you able to solve this issue?
