### ISSUE TITLE
Strange floating point addition on Pyboard

### ISSUE THREAD

**Issue by peterhinch** [micropython/micropython#1178]
File rats.py:
```python
from math import pi, sin, cos
from array import array
length = 128
x = array('f', (cos(2*pi*x/length) for x in range(length)))
y = array('f', (sin(2*pi*x/length) for x in range(length)))
print(x[1], y[1]) # OK
print(x[1]*x[1], y[1]*y[1]) # OK
print(x[1]*x[1] + y[1]*y[1]) # ????
```
This produces the following output at the REPL
```
>>> import rats
0.9987954 0.04906768
0.9975924 0.002407637
0.0
>>> 
```
This behaviour only occurs when the expected result is precisely 1.0. It's not easy to replicate by simply typing in the values, presumably because of floating point conversion imprecision. I should add that I encountered the error performing the multiply and add using the FPU in assembler and subsequently replicated it in Python so the fault may be subtle.

**Comment by dpgeorge** [comment]
The problem is most likely with printf. The number is probably 0.999999999
and not exactly 1.0.

**Comment by dpgeorge** [comment]
Here is a very concise test for this bug:
```python
print(0.9999999)
```

**Comment by dpgeorge** [comment]
@dhylands @doogle do either of you mind looking into this?  The problem is with single precision floating point, related to this line here https://github.com/micropython/micropython/blob/master/py/formatfloat.c#L146.  To test, change unix build to use single precision instead of double and try the above print test.  Thanks!

**Comment by dhylands** [comment]
I'll take a look t it. It fails in my original code as well.

**Comment by dpgeorge** [comment]
Fixed.
