### ISSUE TITLE
rp2 machine.Timer: representation reports wrong values

### ISSUE THREAD

**Issue by rkompass** [micropython/micropython#11802]
With
```
from machine import Timer

tim = Timer(-1)                 # Software timer
tim.init(period=1000, mode=Timer.PERIODIC, callback=lambda t: print('hello'))
print('Timer object:', tim)

tim.deinit()
```
a timer with period of 1 second is generated.
The timer representation printed gives:
`Timer(mode=PERIODIC, period=268696348, tick_hz=1000000)`
which is obviously wrong.

**Comment by robert-hh** [comment]
It's the wrong format in the print statement. That one works:
`    mp_printf(print, "Timer(mode=%q, period=%lu, tick_hz=1000000)", mode, self->delta_us);`
