### ISSUE TITLE
Port to Espruino Pico

### ISSUE THREAD

**Issue by dpgeorge** [micropython/micropython#1183]
I just got my Espruino Pico board and ported uPy to it (STM32F401CD with 384k ROM and 96k RAM).  Works like a charm!  I have the code sitting in a branch that's based upon a chain of private branches (that support F411 and F401), so will need some extra work to extract only the relevant commits.  This issue is more of an FYI so others don't duplicate these efforts.

**Comment by danicampora** [comment]
Cool, thanks for the info!!

**Comment by dpgeorge** [comment]
Done in 90e6d0c2ac3dcda46d93b061802692444bd931a4.
