### ISSUE TITLE
Sponsorships: payment method

### ISSUE THREAD

**Issue by massimosala** [micropython/micropython#11855]
Hi

I want to contribute but here
https://github.com/sponsors/micropython/sponsorships
the only payment method available is credit card.

Sorry, but I stopped typing my credit card into websites for several years now.

I think it is deterrent for other people as well.
Can you add Paypal?

Massimo

**Comment by dlech** [comment]
For reference:

GitHub stopped supporting Paypal as a payment option in February. https://github.blog/changelog/2023-01-23-github-sponsors-will-stop-supporting-paypal/

It is possible to add buttons for other platforms: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

**Comment by massimosala** [comment]
Mmh I see ... but .. are we forced to pay on github?

If Damien is registered on Paypal (he can always do it), then publish the email with which he registered - or contact me privately - and I can proceed with the monthly donation.

**Comment by massimosala** [comment]
up
@dpgeorge

**Comment by massimosala** [comment]
The parties seem not interested to receive funds with Paypal.
