### ISSUE TITLE
ESP32: network.WLAN(network.AP_IF).active(True) hangs on master branch (IDF v5)

### ISSUE THREAD

**Issue by eleroy** [micropython/micropython#11910]
Hello everyone,

Running this on ESP32 (TinyS3) runs forever.

```python
import network
network.WLAN(network.AP_IF).active(False)
network.WLAN(network.AP_IF).config(ssid="test",key="testtest")
network.WLAN(network.AP_IF).active(True)
```

Full version name : MicroPython v1.20.0-261-g813d559bc on 2023-06-30; TinyS3 with ESP32-S3-FN8

Probably an issue due to the new IDF I guess.

**Comment by glenn20** [comment]
Actually, the following code was recently added (last week) to `network_wlan.c:network_wlan_active()`:

```py
                while (wifi_sta_reconnects != 0) {
                    MICROPY_EVENT_POLL_HOOK;
                }
```

This should only be used when activating the `STA_IF` interface, but is also executed when activating the AP_IF interface. 

Until this is fixed, a work around is to set the `STA_IF` interface `active(True)` before activating the AP_IF interface. You should be able to then just disable the `STA_IF` interface.
