### ISSUE TITLE
ValueError: SPI(2) doesn't exist after build ESP32 with IDF_5.0.2 

### ISSUE THREAD

**Issue by styliter** [micropython/micropython#11919]
I build firmware.bin sucessfully for ESP32 GENERIC with IDF_5.0.2.

There is an error when use SPI:

>>> from machine import SPI
>>> spi = SPI(2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: SPI(2) doesn't exist
>>> SPI(1)
SPI(id=1, baudrate=500000, polarity=0, phase=0, bits=8, firstbit=0, sck=14, mosi=13, miso=12)

**Comment by whatdtech** [comment]
same issue here. Any solution?

**Comment by Meteors27** [comment]
same issue, waiting for solution...

**Comment by dpgeorge** [comment]
Fixed by aab8061dceb2ea4c6e87a876f48969e4a5a85c94
