### ISSUE TITLE
ValueError when connecting WiFi via BSSID on esp32

### ISSUE THREAD

**Issue by MATTYGILO** [micropython/micropython#11996]
Hi am using an esp32s3 and trying to connect to my WiFi via BSSID 

I am using this code (With my credentials):
```
import network
import enterprise
station = network.WLAN(network.STA_IF)
station.active(True)
station.connect("ssid", "password", bssid="aa:aa:aa:aa:aa:aa")
```

and getting this error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: 
```

All help would be much appreciated

**Comment by dpgeorge** [comment]
The `bssid` argument must be a 6-byte long bytes/bytearray object.  Eg something like `\xaa\xaa\xaa\xaa\xaa\xaa`.

You can do `bytes.fromhex('aabbccddeeff')` if you want to convert from hex to bytes.
