### ISSUE TITLE
PICO, PICO W - Thread and Timers can freeze the script

### ISSUE THREAD

**Issue by bgolab** [micropython/micropython#12041]
MicroPython v1.20. The following scrips hangs once started:

```python
from machine import Timer
import _thread
import time

tickCount = 0

def Tick1(timer):
  pass

def Tick200(timer):
  pass

def Tick1000(timer):
  global tickCount
  tickCount += 1

def core1_task():
    while True:
         pass

Timer(period=1,    callback=Tick1)
Timer(period=200,  callback=Tick200)
Timer(period=1000, callback=Tick1000)

_thread.start_new_thread(core1_task, ())

while True:
  print(tickCount)
  time.sleep_ms(1000)
  ```
  
  What we can see is:
  _Timer(mode=_

**Comment by bgolab** [comment]
To fix the issue (mostly works) we need to add two lines of code just before the _start.thread lines:

`time.sleep_ms(1000)
print("hi")`

**Comment by bgolab** [comment]
More detailed description is available here:
https://forums.raspberrypi.com/viewtopic.php?t=353750&sid=d4b6087d59c227b5aa416eaad0036552

**Comment by peterhinch** [comment]
Please enclose your code in treble backtick (`) characters to preserve the indentation. If you put the word `python` after the opening treble backtick you get syntax highlighting.

**Comment by bgolab** [comment]
I hope it should be fine now - I reformatted the code above.

**Comment by bgolab** [comment]
Please notice - this piece of code is very simplified to show the issue. Original code where the issue was discovered is much more complex (no simple 'pass' commands).

More insights are captured here:
https://forums.raspberrypi.com/viewtopic.php?t=353750&sid=d4b6087d59c227b5aa416eaad0036552

**Comment by Gadgetoid** [comment]
Possibly related, if I print the CPU ID within `Tick1000` it might be 0 or it might be 1 depending on which core waits and checks the timer pool first. This example will show the CPU ID (core) change for `Tick1000` when I deliberately fire up core1 after the timer has fired a couple of times:

```python
from machine import Timer
import _thread
import time

tickCount = 0

def Tick1(timer):
  pass

def Tick1000(timer):
  global tickCount
  tickCount += 1
  print(f"CPUID (Tick1000): {machine.mem32[0xd0000000]} {tickCount}")

def core1_task():
    while True:
        pass

Timer(period=1000,  callback=Tick1000)

print(f"CPUID (main): {machine.mem32[0xd0000000]}")

for x in range(2):
    print(f"Count (main): {tickCount}")
    time.sleep_ms(1000)
    
_thread.start_new_thread(core1_task, ())

while True:
  print(f"Count (main): {tickCount}")
  time.sleep_ms(1000)
```

Is it possible the problem is that both core0 and core1 try to fire the timer at the same time?

I noticed during my tests that sometimes the timer would fire for a few ticks and then stall (read: hardlock my Pico), potentially when this core clash happens.

IMO whether it's the root cause of this issue or not, the core/thread affinity for timers should be predictable- ie: guaranteed to be the same core that started the Timer. There doesn't appear to be a way to guarantee it in Pico SDK. This might be an SDK bug bubbling up to MicroPython.

Effectively timers work by using Pico SDKs timer functionality, which relies upon code sleeping and polling the timer pool (as I understand it). Once the timer is triggered, it fires an internal C callback that hands over the users callback function to the MicroPython scheduler.

**Comment by peterhinch** [comment]
I think the problem here is that there are no references to the timer objects. The following works here:
```python
from machine import Timer
import _thread
import time

tickCount = 0

def Tick1(timer):
  pass

def Tick200(timer):
  pass

def Tick1000(timer):
  global tickCount
  tickCount += 1

def core1_task():
    while True:
         pass

t1 = Timer(period=1,    callback=Tick1)  # Create references
t2 = Timer(period=200,  callback=Tick200)
t3 = Timer(period=1000, callback=Tick1000)

_thread.start_new_thread(core1_task, ())

while True:
  print(tickCount)
  time.sleep_ms(1000)
```

**Comment by bgolab** [comment]
I posted the simplified version of the code which failed. The original code there the issue was discovered looks like this (and contains the Timer references):
```python
_thread.start_new_thread(core1_task, ()) 				#hangs when timers below are enabled
tim1ms = Timer(period=1, callback=scheduler1ms)			#1ms
tim200ms = Timer(period=200, callback=scheduler200ms)	#200ms
tim1s = Timer(period=1000, callback=scheduler1s)		#1s
tim1h = Timer(period=3600000, callback=scheduler1h)		#1h
```

**Comment by peterhinch** [comment]
OK, but without a simple reproducer it's hard to say anything meaningful.

**Comment by bgolab** [comment]
The simplest code can be "fixed" many ways. All the fixes change the timing little bit. Many of us (micropython forum) who tried to understand the issue believes it is about racing.

I believe we need to find he root cause because all trial and error ways failed sooner or later once we add more code and change the timing again.

So I would stick to the code I shared at the beginning and try to investigate random cpu affinity....

**Comment by bgolab** [comment]
So if everything is fine just reject it

**Comment by bgolab** [comment]
Not considered bug.

**Comment by bgolab** [comment]
Not considered bug by micropython dev

**Comment by Gadgetoid** [comment]
This hardlocks for me as soon after the new thread is created on `v1.20.0 (2023-04-26) .uf2`, does it not for you @peterhinch?

```
from machine import Timer
import _thread
import time


def Tick1(timer):
  pass


def Tick1000(timer):
    pass


def core1_task():
    while True:
        pass


t1 = Timer(period=1000,  callback=Tick1)
t2 = Timer(period=1000,  callback=Tick1000)


for w in ("Three", "Two", "One", "Hardlock..."):
    print(w)
    time.sleep_ms(1000)

_thread.start_new_thread(core1_task, ())


while True:
  print("Hello World")
  time.sleep_ms(1000)

```

**Comment by Gadgetoid** [comment]
Also here's a minimal example that proves the timer (MicroPython) callback switches from firing on core0 to core1 when the second core is fired up:

```python
from machine import Timer
import _thread
import time

def Tick(timer):
  print(f"CPUID (Tick): {machine.mem32[0xd0000000]}")

def core1_task():
    while True:
        pass

t = Timer(period=1000,  callback=Tick)

print(f"CPUID (main): {machine.mem32[0xd0000000]}")

for x in range(2):
    time.sleep_ms(1000)

_thread.start_new_thread(core1_task, ())

while True:
  time.sleep_ms(1000)

```

The register `machine.mem32[0xd0000000]` points to the core ID. After letting the timer run for a couple of ticks - showing `core 0` it will fire up core 1 and the timer will start firing on core 1-

```
MPY: soft reboot
CPUID (main): 0
CPUID (Tick): 0
CPUID (Tick): 0
CPUID (Tick): 1
CPUID (Tick): 1
CPUID (Tick): 1
CPUID (Tick): 1
```

Now- should Core 1 ever be servicing a `Timer` created on Core 0? I'd venture not. The interrupt/C handler still fires on `core0` but it looks like - at a guess - `mp_sched_schedule` just doesn't care where the callback function runs. Note, I had to modify MicroPython to add `mp_printf(&mp_plat_print, "alarm_callback fired on core %d for alarm %d\n", core_num, id);` into `alarm_callback` to observe the core it fires upon. Giving me output like:

```
MPY: soft reboot
CPUID (main): 0
alarm_callback fired on core 0 for alarm 35854
CPUID (Tick): 0
alarm_callback fired on core 0 for alarm 35854
CPUID (Tick): 0
alarm_callback fired on core 0 for alarm 35854
CPUID (Tick): 1
alarm_callback fired on core 0 for alarm 35854
CPUID (Tick): 1
alarm_callback fired on core 0 for alarm 35854
CPUID (Tick): 1
alarm_callback fired on core 0 for alarm 35854
CPUID (Tick): 1
```

**Comment by peterhinch** [comment]
@Gadgetoid That looks like a genuine bug and I agree that a timer created on core 0 should be serviced on core 0.

Interestingly your first example runs with the following change:
```python
t1 = Timer(period=1001,  callback=Tick1)
t2 = Timer(period=1000,  callback=Tick1000)
```
i.e. it only fails if the two timers have exactly the same period. Do you think this is related?

It might be worth opening a new issue with your repro for the core issue: hopefully the maintainers will respond.

**Comment by Gadgetoid** [comment]
My gut feeling is that these two things are related somehow, but I'm not entirely sure how or why. I'll need to find some time with a debugger.

Agreed re another issue, though doing some digging into open issues reveals that this is a wider class of bug that might need a canonical solution for all cases. Of particular note is your own issue from Feb - https://github.com/micropython/micropython/issues/10690 - noting that ISRs are also prone to being erroneously served by core1. Actually even our test cases are super similar, so I think it makes sense for me to chime in there?
