### ISSUE TITLE
struct unpack() error handling

### ISSUE THREAD

**Issue by peterhinch** [micropython/micropython#1208]
The following code is accepted by MicroPython but throws an error in Cpython ("unpack requires a bytes object of length 2")

``` python
from struct import unpack
z = bytes([1])
unpack('<H',z)
```

**Comment by dpgeorge** [comment]
Well, this is a feature of it being "micro": it assumes you gave the correct sized buffer.  It would cost bytes to check and raise the appropriate error.

**Comment by peterhinch** [comment]
Fair enough.

**Comment by pfalcon** [comment]
Well, we want to know (and catalog) issues people faced, but actually fixing that will likely required django criteria per https://github.com/micropython/micropython/wiki/ContributorGuidelines .

**Comment by pfalcon** [comment]
See also #1220.

**Comment by dpgeorge** [comment]
This is now fixed, unpack will raise an exception if the buffer is too small (but not if it's too long).
