### ISSUE TITLE
Latest github release  deflate.DeflateIO.write  Method does not exist

### ISSUE THREAD

**Issue by joyanhui** [micropython/micropython#12101]
Latest github release   esp32-s2
```
    stream = io.BytesIO()
    with deflate.DeflateIO(stream, deflate.GZIP) as d:
        d.write(msgpack_data) 
```
DeflateIO.write  Method does not exist

**Comment by dpgeorge** [comment]
Compression is not enabled by default on the esp32 port.  If you can build firmware yourself then, to enable compression, you need to change the config to use:
```
#define MICROPY_CONFIG_ROM_LEVEL (MICROPY_CONFIG_ROM_LEVEL_FULL_FEATURES)
```

**Comment by joyanhui** [comment]
> Compression is not enabled by default on the esp32 port. If you can build firmware yourself then, to enable compression, you need to change the config to use:
> 
> ```
> #define MICROPY_CONFIG_ROM_LEVEL (MICROPY_CONFIG_ROM_LEVEL_FULL_FEATURES)
> ```

Thanks for your help.

**Comment by jimmo** [comment]
@joyanhui FYI this is detailed at https://docs.micropython.org/en/latest/library/deflate.html -- we're going to start doing this for all modules (and where applicable, optional methods/classes).
