### ISSUE TITLE
EXT_GPIO pins on Nano RP2040

### ISSUE THREAD

**Issue by Cognisant1** [micropython/micropython#12173]

**Comment by Cognisant1** [comment]
I can’t seem to access the EXT_GPIO pins on Nano RP2040. It says “expecting a regular GPIO Pin”. Can anyone help?

**Comment by robert-hh** [comment]
EXT_GPIO pins are only available at the RP2040 PICO_W. You can access them there through the Pin.cpu class, or as string argument to the Pin method like Pin("EXT_GPIO0"). EXT_GPIO0 can as well be addresses as "LED", e.g. Pin("LED").

**Comment by robert-hh** [comment]
b.t.w: Please delete your first post, copying Jimmo's post. It seemed to be made in error.

**Comment by jimmo** [comment]
@Cognisant1 To raise issues against MicroPython please use the [Issue Tracker](https://github.com/micropython/micropython/issues/new/choose).

As @robert-hh has explained above, EXT_GPIO pins are only on boards where additional pins are provided via some interface (such as the WiFi chip on the Pico W).

**Comment by Cognisant1** [comment]
ThanksSorry for raising an issue in the wrong place but thank you so much for responding. I thought the Arduino nano RP2040 did have these extended pins via the Nina module in the Board (see https://github.com/micropython/micropython/blob/67fac4ebc53db6337008ba06df7932faec80f57c/ports/rp2/boards/ARDUINO_NANO_RP2040_CONNECT/pins.csv?plain=1)Sent from my iPhoneOn 5 Aug 2023, at 23:37, Jim Mussared ***@***.***> wrote:﻿
Closed #12173 as completed.

**Comment by robert-hh** [comment]
Yes, indeed, I forgot that one. They are listed in pins.csv as and contained in the Pin.cpu and Pin.board classes. Same rule as for the PICO_W for using them.

**Comment by Cognisant1** [comment]
So sorry to be a bother,  but I’m using Thonny with the nightly build of .uf2 and when I try Pin(‘EXT_GPIO3’) or Pin (36) I get the response invalid pin. Don’t know why Sent from my iPadOn 6 Aug 2023, at 07:58, Robert Hammelrath ***@***.***> wrote:﻿
Yes, indeed, I forgot that one. They are listed in pins.csv as and contained in the Pin.cpu and Pin.board classes. Same rule as for the PICO_W for using them.

**Comment by robert-hh** [comment]
That may be a Thonny problem (again). I just uploaded the most recent nightly build, using the simple method by
- Downloading the file from https://micropython.org/download/ARDUINO_NANO_RP2040_CONNECT/
- Pushing reset twice.
- Waiting until the `RPI-RP2` drive appears,
- copying the .uf2 file to the device and
- Waiting until the `RPI-RP2` drive disappears.

Then I get in REPL using a simple terminal like Putty or mpremote with Ctrl-B the version prompt. And can use the ext pins.
```
MicroPython v1.20.0-327-gd14ddcbdb on 2023-07-27; Arduino Nano RP2040 Connect with RP2040
Type "help()" for more information.
>>> from machine import Pin
>>> p36=Pin('EXT_GPIO3')
>>> type(p36)
<class 'Pin'>
```

Rule of Thonny: If something fails when using Thonny, try the same NOT using Thonny.

**Comment by Cognisant1** [comment]
This is very helpful. When I try exactly what you’ve written it works fine. But when I add adc = ADC(p36) the error is ValueError: expecting a regular GOIO PinSent from my iPhoneOn 6 Aug 2023, at 09:31, Robert Hammelrath ***@***.***> wrote:﻿
That may be a Thonny problem (again). I just uploaded the most recent nightly build, using the simple method by

Downloading the file from https://micropython.org/download/ARDUINO_NANO_RP2040_CONNECT/
Pushing reset twice.
Waiting until the RPI-RP2 drive appears,
copying the .uf2 file to the device and
Waiting until the RPI-RP2 drive disappears.

Then I get in REPL using a simple terminal like Putty or mpremote with Ctrl-B the version prompt. And can use the ext pins.
MicroPython v1.20.0-327-gd14ddcbdb on 2023-07-27; Arduino Nano RP2040 Connect with RP2040
Type "help()" for more information.
>>> from machine import Pin
>>> p36=Pin('EXT_GPIO3')
>>> type(p36)
<class 'Pin'>

Rule of Thonny: If something fails when using Thonny, try the same NOT using Thonny.

**Comment by robert-hh** [comment]
The EXT_GPIOxx pins are not pins of the RP2, but pins of the NINAW10 ESP32 based WiFi module, and their operation requires communicating with the ESP32. Therefore not all functions of a RP2 pin may be available. If it rejects use for ADC, then it this is not implemented. Looking at the code, that seems indeed not to be supported. Although it could easily be implemented, since it is already supported by the NINAW10 module.

**Comment by Cognisant1** [comment]
Any way I can implement it in micropython. I don’t particularly want to go back to Arduino. I was enjoying micropython!!Sent from my iPhoneOn 6 Aug 2023, at 16:38, Robert Hammelrath ***@***.***> wrote:﻿
The EXT_GPIOxx pins are not pins of the RP2, but pins of the NINAW10 ESP32 based WiFi module, and their operation requires communicating with the ESP32. Therefore not all functions of a RP2 pin may be available. If it rejects use for ADC, then it this is not implemented. Looking at the code, that seems indeed not to be supported. Although it could easily be implemented, since it is already supported by the NINAW10 module.

**Comment by Cognisant1** [comment]
Hi RobertThis is a very valuable email conversation. I’m sorry I put it in the wrong place. But I’m fascinated to hear that the ADC on the NINAW10 module might be relatively easy to implement. Could you possibly convert my query into a request for the ADC implementation to be achieved? Best wishesAdrianSent from my iPhoneOn 6 Aug 2023, at 17:08, Adrian Eddleston ***@***.***> wrote:﻿Any way I can implement it in micropython. I don’t particularly want to go back to Arduino. I was enjoying micropython!!Sent from my iPhoneOn 6 Aug 2023, at 16:38, Robert Hammelrath ***@***.***> wrote:﻿
The EXT_GPIOxx pins are not pins of the RP2, but pins of the NINAW10 ESP32 based WiFi module, and their operation requires communicating with the ESP32. Therefore not all functions of a RP2 pin may be available. If it rejects use for ADC, then it this is not implemented. Looking at the code, that seems indeed not to be supported. Although it could easily be implemented, since it is already supported by the NINAW10 module.

**Comment by robert-hh** [comment]
>  I’m sorry I put it in the wrong place. But I’m fascinated to hear that the ADC on the NINAW10 module might be relatively easy to implement. 

ADC on the NINA module is already implemented. Only it is not used by the machine.ADC class of the RP2. That connection is missing. Maybe someone from Arduino can contribute it.
