### ISSUE TITLE
Pico W will not connect on WiFi

### ISSUE THREAD

**Issue by LordInchcape2** [micropython/micropython#12191]
I have followed several forum threads on Pico W running MicroPython not connecting on WifI without a clear resolution.
My Pico W will get the list of available networks but will not connect.
If I run the Pico W in the Arduino Gui it works perfectly. Connects every time.
So I know the problem is not my router or the hardware of the Pico W. It must be the MicroPython support.
Any help gratefully received.

**Comment by LordInchcape2** [comment]
I had something very similar. 
But I have just tried the exact code example you sent and it will still not connect.

**Comment by robert-hh** [comment]
Which Micropython version is installed?

**Comment by LordInchcape2** [comment]
MicroPython v1.20.0 on 2023-04-26   Raspberry Pi Pico W with RP2040

**Comment by robert-hh** [comment]
You could try a recent nightly build, just in case there were changes to that topic.

**Comment by LordInchcape2** [comment]
Thanks I will try that. I will also try micropython on one of my ESP32's.

**Comment by LordInchcape2** [comment]
Apologies. A major case of finger trouble!!
The password on some of my scripts had picked up a stray character.,
