### ISSUE TITLE
NotImplemented not implemented

### ISSUE THREAD

**Issue by pfalcon** [micropython/micropython#1222]
https://docs.python.org/3/library/constants.html?highlight=notimplemented#NotImplemented

>    Special value which should be returned by the binary special methods (e.g. __eq__(), __lt__(), __add__(), __rsub__(), etc.) to indicate that the operation is not implemented with respect to the other type; may be returned by the in-place binary special methods (e.g. __imul__(), __iand__(), etc.) for the same purpose. Its truth value is true.

Given that we have Ellipsis, I guess we won't get around implementing this. (Alias it to MP_OBJ_SENTINEL ?)

**Comment by pfalcon** [comment]
Proposed patch: #1223

**Comment by dpgeorge** [comment]
Ellipsis is there because it's also a token (...).

I assume you came across code that really needs to use NotImplemented.  I'm happy to just copy the Ellipsis implementation for this.

**Comment by pfalcon** [comment]
> I assume you came across code that really needs to use NotImplemented.

Actually, not. I just try to consider whether a uPy-compatible fix is mergeable upstream or not. I doubt that someone would agree to replace NotImplemented with Ellipsis name, even though the semantics is the same.

Also, reading how comparisons on user types are implemented in Python3, we *need* to support NotImplemented.

http://jcalderone.livejournal.com/32837.html , etc.

**Comment by pfalcon** [comment]
Implemented, #ifdef'able.
