### ISSUE TITLE
Passing kwargs to a method which references super() is broken

### ISSUE THREAD

**Issue by pfalcon** [micropython/micropython#1226]
Tescase:

~~~~
class A:

    def __init__(self, foo):
        #super().__init__()
        super()
        pass

A(foo=32)
~~~~

Instrumented to print a culprit "exisiting" value, the output is:

~~~~
<A object at 9c66df40>existing val: 
Traceback (most recent call last):
  File "a.py", line 9, in <module>
TypeError: function got multiple values for argument 'foo'
~~~~

I.e. where argument setup expects "foo" to be located, there's actually value for "self". Commenting out "super()" makes issues go away.

**Comment by pfalcon** [comment]
@dpgeorge , as this apparently affected by super() compiling/implementation, and I don't know much about it, could you queue up looking into this? I hit this in my own code, so can work it around, but it's pretty bleak, and in general case, it's not possible.

**Comment by dpgeorge** [comment]
ok

**Comment by dpgeorge** [comment]
It's not about super, it's about kwargs to a closed over function:
```
def f():
    x = 1
    def g(z):
        print(x, z)
    return g
f()(z=42)
```

**Comment by dpgeorge** [comment]
Fixed.

**Comment by pfalcon** [comment]
Great, thanks!
