### ISSUE TITLE
Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.

### ISSUE THREAD

**Issue by Sotung96** [micropython/micropython#12276]
Hi All,

I'm trying to delete usb phy and reinstall it but after I use esp_err_t usb_del_phy(usb_phy_handle_t handle), the system was reboot and show me the error : 0x4201069b: 0x42010698: usb_phy_ll_int_load_conf at C:/Espressif/frameworks/esp-idf-v5.1/components/hal/esp32s3/include/hal/usb_phy_ll.h:98 (inlined by) usb_del_phy at C:/Espressif/frameworks/esp-idf-v5.1/components/usb/usb_phy.c:332.

Do anyone know what happen?
Thanks.

**Comment by dpgeorge** [comment]
This doesn't look like it's related to MicroPython, so please ask the question at the ESP-IDF repository.
