### ISSUE TITLE
ESPNow for ESP32-S3 Failed 

### ISSUE THREAD

**Issue by stone1706** [micropython/micropython#12282]
I set chip target to esp32s3 , then build firmware and run it , what i found ...it does not support espnow module.
>>> import espnow
No module named "_espnow".....
.
but I changed chip target into ESP32 , and rebuild it , it work fine....no question about it .
 
so I thought there should be something wrong on esp32s3 profiles .

**Comment by robert-hh** [comment]
The nightly builds include espnow, and building a firmware with `make BOARD=GENERIC_S3` includes it as well. If you have any espnow.py in your file system, remove it.

**Comment by stone1706** [comment]
OK, I try it now...
thank you...
