### ISSUE TITLE
add documentation guidelines to code style guide

### ISSUE THREAD

**Issue by vitiral** [micropython/micropython#1235]
From @dpgeorge 

> The standard is implicit in the format of existing comments: be concise, use // prefix, no extra fluff, only write comments for things that are not obvious.

> In general I'm against lengthy and unnecessary comments, and I don't want to go down the doxygen route. Reading the code should be enough to describe what's happening, and, if it's not, then you write a comment.

> Most of the comments in this PR go against the above rules. There are some comments that you have that are worth adding but they need trimming and re-formatting.

These comments need to be formatted and put in examples in the style guide.

Also @dpgeorge, could you add me to the micropython group and set this task to me? If not, I will be completing this anyway.

**Comment by dpgeorge** [comment]
> could you add me to the micropython group and set this task to me? If not, I will be completing this anyway.

It is enough to just say that you want to do it :)
