### ISSUE TITLE
Experts: Firmware flashing from internal flash failed

### ISSUE THREAD

**Issue by xuancong84** [micropython/micropython#12364]
### Discussed in https://github.com/orgs/micropython/discussions/12336

<div type='discussions-op-text'>

<sup>Originally posted by **xuancong84** August 30, 2023</sup>
Hi @danicampora @dpgeorge @jimmo @peterhinch 
I have been trying to flashing firmware locally from image file on internal storage, but so far no success.

I am aware that 0x40200000-0x40300000 is mapped to the 1st 1MB of flash, so running any code from this region to flash firmware is going to fail because while flashing half-way, your code gets changed and will cause crash. Not only this, while flashing, any functions that you call cannot come from this memory region. Moreover, certain interrupt handlers may re-direct to this region upon handling special events, so you must disable watchdog, disable interrupt IRQ, etc. while flashing.

Taking care of all these, I have put my code in iram1 (40100000h-40108000h) using MP_FASTCODE and view disassembly to confirm that no function calls will reach 0x40200000-0x40300000. I will need to call spi_flash_erase_sector, spi_flash_read, spi_flash_write and uart_tx_one_char (for verbose), all these functions come from iram1. Even for reading the firmware image file, I digged out all the sectors and sector offsets for each fragment of the file, and did not use any filesystem function calls (which are all in 0x40200000-0x40300000).

Unfortunately, I can only flash the 1st portion (0x40200000-0x40209000) which is the boot-loader, the program hangs forever once writing into the flash region that is mapped to .irom0.text section, i.e., from 0x40209000 onwards.

Can someone explain why, is there some sort of memory protection or what? My code is at https://github.com/xuancong84/micropython/ </div>

**Comment by andrewleech** [comment]
Please don't duplicate on discussions and issues; people won't know where to respond in this case. As this is application asssistance more than core code changes I think keeping it on discussions is best.
