### ISSUE TITLE
esp8266: listen()/accept() broken?

### ISSUE THREAD

**Issue by roger-** [micropython/micropython#1237]
I'm testing the following server script:

```python
import esp

esp.connect('xxx', 'xxx')  
 
s = esp.socket()
  
def on_connect(sock):
    print(s.accept()) 
     
s.bind(('', 80))
s.onconnect(on_connect)
s.listen(5)
```

But get a  `OSError: not listening` everytime I connect. Seems like something is broken?

**Comment by atalax** [comment]
> ```python
> def on_connect(sock):
>    print(s.accept())
> ```

Actually, the child socket gets passed as the argument, so you should do
```python
def on_connect(sock):
    print(sock) 
```

Simple HTTP server:
```
import esp
import sys

def onnewclient(s):
    print("Client connected!")
    s.onrecv(onclientdata)
    s.onsent(onclientsent)

def onclientdata(s, d):
    dp = d.split()
    path = dp[1].format("ascii")
    if path == "/":
        s.send("HTTP/1.0 200 OK\r\n"
               "Server: Micropython for ESP8266\r\n"
               "Content-Type: text/html\r\n"
               "Connection: close\r\n"
               "\r\n"
               "<h1>ESP8266</h1>\r\n"
               "Micropython version " + str(sys.implementation[1]))
    else:
        s.send("HTTP/1.0 404 OK\r\n"
               "Server: Micropython for ESP8266\r\n"
               "Content-Type: text/html\r\n"
               "Connection: close\r\n"
               "\r\n"
               "<h1>:(</h1>")

def onclientsent(s):
    print("Closing...")
    s.close()

server = esp.socket()

server.onconnect(onnewclient)
server.bind(("", 80))
server.listen(5)
```

**Comment by roger-** [comment]
Cool, so we don't need to use accept/recv? Are those even useful to have then?

**Comment by deshipu** [comment]
Is this still an open issue, or should we close it?

**Comment by pfalcon** [comment]
As there's no standard test procedure for this port, it's hard to tell if it's fixed or not, and if/when it may be broken again.

**Comment by deshipu** [comment]
Maybe I'm reading this wrong, but it seems to me, that the issue itself is invalid. The attached code should never have worked, and the the code given in the comment is the valid way to do that instead, which, I can confirm, works. So the whole issue was a misunderstanding on the user side?

**Comment by roger-** [comment]
The issue was that the API was a bit confusing.

I'm still not sure what `accept()`/`recv()` are used for though.

**Comment by dhylands** [comment]
In the normal socket stack, you do a listen, and when somebody eventually connects, then the server side will get some information about the connector. If that information (typically IP address) is deemed to be acceptable then the server side would do an accept. The socket returned by listen is what's called a listening socket that's not bound to any particular remote, and when you call accept, you get a new socket which is actually bound to the remote end. That new socket from the accept is the socket that you then use for send/recv.

Normally if you're a server, you would do a recv to get the request from the remote end.

**Comment by roger-** [comment]
Doh, totally forgot this wasn't client only!

Thanks, I get it now.
