### ISSUE TITLE
nrf24l01 pico-to-pico officaltest gets me succes=0 failures=16 

### ISSUE THREAD

**Issue by Hopesforgypsy** [micropython/micropython#12384]
as ı said in the title ı am trying to use two nrf24l01 to communicate pico-to-pico with the official test but it gives me succes=0 failures=16 as seen in the picture ı use two computers each connected to one of the Picos ı will put a picture of the wiring and the screenshots of the thonny interface

![resim_2023-09-06_153626918](https://github.com/micropython/micropython/assets/59196975/45198c90-e369-413b-97b9-5ff1741d216c)

![20230906_153154](https://github.com/micropython/micropython/assets/59196975/45c4d6e6-472c-424e-82a1-a95052aaa9c5)

![20230906_153144](https://github.com/micropython/micropython/assets/59196975/89f4d13f-6131-4af2-aac1-7da1b5770f01)

**Comment by peterhinch** [comment]
We discussed this [here](https://github.com/orgs/micropython/discussions/11601) and you marked the discussion as resolved so I take it this can be closed. If you are still having problems, please raise them in the discussions thread.
