### ISSUE TITLE
NameError: name 'errno' isn't defined

### ISSUE THREAD

**Issue by knemay** [micropython/micropython#12453]
Hey, raise OSError(errno.ETIMEDOUT) is working fine when I test it in the REPL or in an .py file, but is raising that error when ran in an .mpy file. I'm using mpy-cross 1.20.0 to compile the file. What could be happening and how can I fix it?
Thanks in advance,

Please, dont close the issue as it seems to be a compiltation error. The test script is `raise OSError(errno.ETIMEDOUT)`. You can check that is working fine in .py files, then compile it and check that its failing with the error mentioned above.

Also, you can see from [this issue](https://github.com/micropython/micropython/issues/12238) that it should work

**Comment by robert-hh** [comment]
Just add `import errno` to you script.

**Comment by knemay** [comment]
Perfect, thanks

**Comment by robert-hh** [comment]
It's still a valid question why `errno` is available in an interactive session like a global, but not visible in the global symbol table. You cannot type in REPL `errno`, but e.g. `errno.ETIMEDOUT`.

**Comment by knemay** [comment]
Its also available in non interactive sessions as running a py file. Not sure why is undefined after compilation

**Comment by jimmo** [comment]
> It's still a valid question why `errno` is available in an interactive session like a global, but not visible in the global symbol table. You cannot type in REPL `errno`, but e.g. `errno.ETIMEDOUT`.

https://github.com/micropython/micropython/blob/5473200aab492d64866511d96b6f4a7d4cb41393/py/parse.c#L639

Some modules (including errno) are registered as providing constants. The `stm` module is a good example. This allows `machine.mem32[stm.X_BASE + stm.X_FOO]` to be evaluated at runtime as just `machine.mem32[const]`.
