### ISSUE TITLE
espnow: Resolve availability of aioespnow prior to v1.21 release

### ISSUE THREAD

**Issue by glenn20** [micropython/micropython#12580]
The [`aioespnow`](https://github.com/micropython/micropython-lib/blob/master/micropython/aioespnow/aioespnow.py) module is now available in `micropython-lib`. However, it is unclear how users are intended to access the `aioespnow` module once v1.21.0 is released. There are two options:

1. Uncomment `# require("aioespnow")` in `ports/esp32/boards/manifest.py` so that aioespnow.py is frozen into esp32 firmware by default (as suggested in PR #6515)
   - This should be done **after** updating the `micropython-lib` submodule reference in micropython from [c113611](https://github.com/micropython/micropython-lib/tree/c113611765278b2fc8dcf8b2f2c3513b35a69b39) and **before** releasing v1.21.0.
   - This requires no changes to the existing documentation

OR

2. Update `docs/library/espnow.html` to indicate that the `aioespnow` modules should be installed with `mip`.
    - **and** remove the commented line in `ports/esp32/boards/manifest.py`.

I am seeking guidance and will submit a PR accordingly. Without action, the documentation will be incomplete/inconsistent  with respect to use of `aioespnow` when v1.21.0 is released.

**Comment by dpgeorge** [comment]
Let's go for option 1.  `micropython-lib` will be updated here shortly.

**Comment by glenn20** [comment]
Great - thanks. I'll submit a one-liner PR (which will fail commit checks till micropython-lib is updated) - unless you prefer to handle it yourself ;).
