### ISSUE TITLE
v1.21.0 Failed to use hostname

### ISSUE THREAD

**Issue by ruihua-code** [micropython/micropython#12632]
ip can be successfully used, but hostname cannot complete the request. May I ask if my method is wrong?

```py
    # TODO: Deprecated. Use network.hostname(name) instead.
    # wlan.config(dhcp_hostname=hostname)
    network.hostname(hostname)
    wlan = network.WLAN(network.STA_IF)
    wlan.active(True)
    print("hostname:", network.hostname())
    while not wlan.active(True):
        print("wait wlan")
```

### http api

> * url: /cmd

> * method: POST

### use ip _Success_
* postman image:
![scrnli_2023_10_9 15-13-54](https://github.com/micropython/micropython/assets/15189454/c3e453a0-7d20-4f31-8c68-1c863d7f0eea)
![image](https://github.com/micropython/micropython/assets/15189454/55b3faa3-21fa-42bb-a123-8ba61c31411c)

### use hostname _Fail_
* postman image:
![scrnli_2023_10_9 15-17-40](https://github.com/micropython/micropython/assets/15189454/23e5f341-8dfc-4625-a0a8-bbbe408de4c9)
![image](https://github.com/micropython/micropython/assets/15189454/ffac52ef-b8bb-46da-bf23-34580f6ac168)

### build info

* **hostname**: wood-chip
* **ifconfig**: ('192.168.188.131', '255.255.254.0', '192.168.188.1', '114.114.114.114')
* **uname**: (sysname='esp32', nodename='esp32', release='1.21.0', version='v1.21.0-dirty on 2023-10-09', machine='Generic ESP32S3 
module with ESP32S3')
* **platform**: MicroPython-1.21.0-xtensa-IDFv5.0.4-158-g3f55377ab4-with-newlib4.1.0

**Comment by dpgeorge** [comment]
It looks like you're trying to use mDNS.  Do you have mDNS configured and working on your PC so that it can query the `wood-chip` name?  Are you able to use mDNS with a different (non-MicroPython) device?

**Comment by ruihua-code** [comment]
> It looks like you're trying to use mDNS. Do you have mDNS configured and working on your PC so that it can query the `wood-chip` name? Are you able to use mDNS with a different (non-MicroPython) device?

I use print to output ```network.hostname()``` as ```wood-chip```

Do you still need to do mDNS configuration on the PC? I don't understand this

In v1.20.0, I used it like this: ```wlan.config(dhcp_hostname="esp")```

Apis can then be requested using ```esp.local``` on phones and computers

**Comment by Seruf-Che** [comment]
Were you able to find a solution?
