### ISSUE TITLE
esp32: At ethernet links the method nic.isconnected() returns "True" even without a cable attached.

### ISSUE THREAD

**Issue by robert-hh** [micropython/micropython#12741]
nic.isconnected() behaves erratic in the current port not only with a SPI attached Ethernet, but also with as LAN8720 on-board interface, and probably others as well. With the LAN8720, it returns  `True` even without a cable attached after calling nic.active(1). nic.status() returns 1 in that state, which means `ETH_STARTED`.
The problem are the esp_idf calls  to  `xxx_w5500_update_link_duplex_speed()` via `get_link()` which are made. These functions check the status of the line, and if the status is not changed or changed to  valid state, then this function returns `ESP_OK`, which has the value of 0. But `ETH_LINK_UP` has also the value of 0. So the return value of  `get_link()` cannot tell, whether the device is connected and can operate.
So better use nic.status() to tell the state. That's reliable. nic.isconnected() should be changed accordingly.
I can make a PR to change nic.isconnected(). Only on question: should `True` be returns in the state `ETH_CONNECTED` or in the state `ETH_GOT_IP`. Only with the latter the interface is full operational.

**Comment by dpgeorge** [comment]
> Only on question: should `True` be returns in the state `ETH_CONNECTED` or in the state `ETH_GOT_IP`. Only with the latter the interface is full operational.

Using `ETH_GOT_IP` sounds good, that's how WLAN works, it uses `IP_EVENT_STA_GOT_IP` to set the `isconnected()` state to `True`.

**Comment by dpgeorge** [comment]
Fixed by 9c244134fb4db921f721737763f81cd9300c2e86
