### ISSUE TITLE
Wrong SyntaxError line number on missing ':'

### ISSUE THREAD

**Issue by MathieuNumworks** [micropython/micropython#12792]
The following code:
```
for i in range([1, 2])

     pass
```

Gives
__micropython:__ 
```
Traceback (most recent call last):
  File "./foo.py",  line 3
SyntaxError: invalid syntax
```

__CPython:__
```
Traceback (most recent call last):
  File "[...]/foo.py", line 1
    for i in range([1, 2])
                          ^
SyntaxError: expected ':'
```

This bug also occurs on the following code:

```
a =


b = 2
```

__micropython:__ 
```
Traceback (most recent call last):
  File "./foo.py",  line 4
SyntaxError: invalid syntax
```
__CPython:__ 
``` 
File "[...]/foo.py", line 2
    a =
       ^
SyntaxError: invalid syntax
```

I obtained these results when running micropython on: 
* https://micropython.org/unicorn/: MicroPython 537518d on 2022-10-31; unicorn with Cortex-M3 
* [v1.22.0-preview](https://github.com/micropython/micropython/releases/tag/v1.22.0-preview) unix port on macosx

The error is reported to the position of the newline token.
I believe the issue could be solved by considering the position of newline tokens as the end of the preceding line, rather than the beginning of the new line.

**Comment by dpgeorge** [comment]
Fixed by c85db05244ef6185fbb3c218c508ddd179830942
