### ISSUE TITLE
esp8266: import UART error

### ISSUE THREAD

**Issue by chinadsf** [micropython/micropython#1283]
I tested esp8266 by REPL:
"from pyb import UART"
return：ImportError：can not import UART
i konw REPL using UART0, but how can i use UART0 or UART1?
i tried main.py, but was not ok

**Comment by pfalcon** [comment]
Likely reason is that it's just not implemented yet. Feel free to submit patches.

**Comment by chinadsf** [comment]
Ok, thanks pfaIcon.
