### ISSUE TITLE
esp8266: SDK 1.1.0 brings backward-incompatible changes

### ISSUE THREAD

**Issue by pfalcon** [micropython/micropython#1287]
SDK 1.1.0 is finally MIT-licensed, so we should switch ASAP. It however introduces backward-incompatible changes. One I already worked around on esp-open-sdk level: https://github.com/pfalcon/esp-open-sdk/issues/53 . Another one is that chip turns out to not have GPIO pull-down support ;-) : http://bbs.espressif.com/viewtopic.php?f=7&t=494

**Comment by pfalcon** [comment]
@atalax : FYI

**Comment by dpgeorge** [comment]
Awesome.  Yes we should upgrade.
