### ISSUE TITLE
nRF52840-PCA10056 add extern flash filesystem

### ISSUE THREAD

**Issue by xinkunlong** [micropython/micropython#12890]
Can you support creating an external Flash system like STM32?

**Comment by robert-hh** [comment]
Using a SPI interface you can attach a Serial flash chip as a drive. Suitable Python code drivers are https://github.com/peterhinch/micropython_eeprom/blob/master/flash/FLASH.md or https://github.com/robert-hh/SPI_Flash. The first link's driver is more complex and supports spanning the file system over several chips. The second link's driver is small, simple and supports only a single chip.

**Comment by xinkunlong** [comment]
Ok, thank you for your answer
