### ISSUE TITLE
esp8266: can't read from sys.stdin

### ISSUE THREAD

**Issue by deshipu** [micropython/micropython#1293]
I was trying to work around the fact that the ESP8266 port doesn't have UART support on the Python side yet, and simply read/write from and to the sys.stdin and sys.stdout.

While sys.stdout works as expected, trying to read even a single character from sys.stdin hangs the REPL. I compared with other ports, and that's not the case in them -- they wait until the specified number of characters is input and then properly return those characters.

**Comment by deshipu** [comment]
Also doesn't work from main.py -- the board just hangs.

**Comment by danicampora** [comment]
Is the stdio uart in the esp8266 port interrupt driven?

**Comment by dpgeorge** [comment]
With the changes that make the REPL event driven, the function `mp_hal_stdin_rx_chr` no longer works at all (because received chars are given directly to the REPL and the uart rx buffer never gets filled).

**Comment by dpgeorge** [comment]
This has been fixed with the new ESP8266 execution model.
