### ISSUE TITLE
ESP-32 BLE w/ NimBLE does not support bonding/pairing

### ISSUE THREAD

**Issue by RaspberryPiDude314** [micropython/micropython#12958]
As of right now, bonding/pairing features with ESP-32/NimBLE Bluetooth stack for Micropython are non-functional. Any attempt to pair allows the device to temporarily pair but no interrupts are actually called. This includes the interrupts with data for password/pin bonding and passkey transfers, making a permanent (repeatable) connection with an ESP-32 impossible. [The docs do confirm](https://docs.micropython.org/en/latest/library/bluetooth.html#pairing-and-bonding) that this particular feature is non-functional on ESP-32. 
I don't believe this function would take up much additional on-board resources and would greatly improve the use of the already-existing Bluetooth library. I feel without this function many users simply would not use the entire library, as it is a fairly important part of Bluetooth and enables many very common and practical uses such as L2CAP and native use without code running client-side.

**Comment by andrewleech** [comment]
Pairing and bonding in ble is a suprisingly complicated thing to manage.
I wrote the support for this on the stm port for a project at work and it took me months to get it working properly.

So far no one has contributed a PR to add it on other ports, and I don't use esp chips at work.

I've also give that very few other projects I know of actually _want_ it at all, unless there's an important security reason with the particular device, people often prefer to not have to make users go through the hassle of the bonding process - particularly when it fails (which often happens) and users need to manually clear / forget the bonding on their phone etc.

**Comment by RaspberryPiDude314** [comment]
To be honest, I struggle to think of many situations you wouldn't want it. Bonding removes the entire hassle of connecting to the device every time it turns on, in cases where certain characteristics are security protected. My use case is a device that updates with battery percentage and syncs time from a user's device whenever it's turned on, for example. Both of these traits require (on Apple's side) "authentication" before they can be used, which just means temporarily pairing the device (clicking a message on screen) and not storing the key so this must be done every time. For something like this, it's very impractical. The same goes with many other things like HID or other Bluetooth characteristics/profiles that the device maker has decided to require authentication before use. I appreciate the feedback, however. If you could share the work you did for the STM port so I could see what's involved I would appreciate it.
Thanks!

**Comment by andrewleech** [comment]
If you take a look here https://github.com/micropython/micropython/commits/ccb33c39333511649d2671802be3385b84f49812/extmod/nimble/modbluetooth_nimble.c mostly in the `Commits on Dec 2, 2020` section, you'll see the bulk of the stm32 pairing and bonding stuff (with most of the final heavy lifting done by @jimmo as is usually the case with all the BLE work)
