### ISSUE TITLE
asyncio stream.py: Is async context manager code correct?

### ISSUE THREAD

**Issue by peterhinch** [micropython/micropython#12995]
[Link to code](https://github.com/micropython/micropython/blob/8b1980ad450ea2b34af4b831a8c655ba08dee800/extmod/asyncio/stream.py#L19C1-L24C1)
```py
    async def __aexit__(self, exc_type, exc, tb):
        await self.close()

    def close(self):
        pass
```
If used in an asynchronous context manager it seems that the socket is not closed.

[EDIT]
The CPython docs make no reference to async context managers. They do say of `StreamReader`:
> As an [asynchronous iterable](https://docs.python.org/3/glossary.html#term-asynchronous-iterable), the object supports the [async for](https://docs.python.org/3/reference/compound_stmts.html#async-for) statement.

This doesn't appear to be supported but would be useful.

Further, on `StreamWriter.close()` the docs say:
> The method closes the stream and the underlying socket.

In a microcontroller context failing to close sockets (read and write) is a regular cause of OOM errors.

**Comment by dpgeorge** [comment]
Looking in to this, it seems MicroPython's `StreamReader` and `StreamWriter` do not work as an async context manager, ie with `async with`.  It looks like they never did work and have no tests for this functionality.

Also as you mention, CPython doesn't support this.

So I think we should just delete both `__aenter__` and `__aexit__` from `Stream`.

-----

Regarding `StreamWriter.close()`: the CPython docs also say:


    The method closes the stream and the underlying socket.

    The method should be used, though not mandatory, along with the wait_closed() method:

So apparently you don't need to call `.close()`, only `.wait_closed()`?  I find that strange, but that's what the docs say.  Therefore we need to actually close the socket in `.wait_closed()` (but I guess we could also close it in `.close()`, it won't hurt to close twice).

The CPython docs also don't mention anything about `StreamReader.close()`... I wonder what's going on there.

**Comment by peterhinch** [comment]
> So I think we should just delete both __aenter__ and __aexit__ from Stream.

Agreed. Any thoughts on supporting `async for`?

**Comment by dpgeorge** [comment]
See #13234 which removes these methods.

> Any thoughts on supporting `async for`?

I guess iterating on a stream uses readline...?  We could implement this but it obviously adds code and I don't think anyone missed it yet.
