### ISSUE TITLE
cc3200 is size 0 (not built?) on http://micropython.org/resources/code-dashboard/

### ISSUE THREAD

**Issue by pfalcon** [micropython/micropython#1303]
For several last days.

@danicampora : Do you know what can be the problem?

**Comment by dpgeorge** [comment]
I think it's due to this 78744c4f7a368e74e8aff81320a8e1bb3265346e

**Comment by dpgeorge** [comment]
I fixed it and am now re-generating the missing data.  I'll commit the scripts to this repo so people can see/update them when needed.

**Comment by pfalcon** [comment]
Thanks.

**Comment by danicampora** [comment]
Sorry guys, I am very busy these days, and therefore my response times won't be spectacular as usual ;-). Thanks for fixing it!

**Comment by dpgeorge** [comment]
FYI, codestats.sh added in 0e6c89a5c8117561379dbf7388814d3bf1ed796e.
