### ISSUE TITLE
micropython/lora, RSSI for Hope Radio devices

### ISSUE THREAD

**Issue by davefes** [micropython/micropython#13036]
All the RSSI implementations I have seen modify the returned RSSI value dependent on frequency (lf or hf).   This distro appears to change it if the PA_BOOST is enabled?

```py
        # units: dBm
        rx_packet.rssi = self._reg_read(_REG_PKT_RSSI_VAL) - (157 if self._pa_boost else 164)
```
Module used RF96 (RFM96W).  If the above formulae is correct for other devices I could modify my `sx127x.py`

**Comment by projectgus** [comment]
We moved this issue over to https://github.com/micropython/micropython-lib/issues/770 as the lora driver is part of micropython-lib.
