### ISSUE TITLE
ValueError: incompatible .mpy file for armv6m 

### ISSUE THREAD

**Issue by premanandaembed** [micropython/micropython#13078]
im getting this error after use make ARCH=armv6m in ubuntu

**Comment by premanandaembed** [comment]
steps to reproduce or steps i tried:
	Microcontrol device:pico w
	IDE: Thony 4.1.3
	Ubuntu 22.04.3 LTS 
	log of sys.implementation._mpy:
		mpy version: 6
		mpy flags: -march=armv6m -mno-unicode
	Step-1: Tried to compile micropython release version 1.19 code from github. 
	Step-2: using Ubuntu 22.04.3 LTS for build as command make ARCH=armv6m and It is complied and successfully generated factorial.mpy file
	Step-2: Copied factorial.mpy file to pico w
	Step-3: created fact.py file inside pico w as below code:
			import factorial
			print(factorial.factorial(10))
![Screenshot 2023-11-29 101224](https://github.com/micropython/micropython/assets/64586165/efb4607e-372b-43bf-b2c8-c9d1c6657cd1)

	After these steps I'm getting when executing fact.py in pico w as ValueError: incompatible .mpy file

**Comment by dpgeorge** [comment]
What does `sys.version` report on the board you are using?

> Tried to compile micropython release version 1.19 code from github.

Please use the version corresponding to `sys.version` retrieved from the board (likely 1.20.0 or 1.21.0).

**Comment by premanandaembed** [comment]
thanks for reply it is 1.21.0

**Comment by dpgeorge** [comment]
Please compile the factorial program with MicroPython v1.21.0.

**Comment by premanandaembed** [comment]
great thanks it worked.
