### ISSUE TITLE
ESP32S3 I2S conflict

### ISSUE THREAD

**Issue by kdschlosser** [micropython/micropython#13104]
ESP-IDF 5.0.2
MicroPython 1.21.0
MCU ESP32

```
E (1026) i2s(legacy): CONFLICT! The new i2s driver 
can't work along with the legacy i2s driver
abort() was called at PC 0x40208f23 on core 0
```

**Comment by kdschlosser** [comment]
If I change MICROPY_PY_MACHINE_I2S from being set in mpconfigport.h it solves the crash when running MicroPython on the MCU. There is no compile time error. the error only happens once the firmware is flashed.

**Comment by sam0910** [comment]
Same in here, 
there was no compile error, but it crashes to infinite reset loop.
```E (1024) i2s(legacy): CONFLICT! The new i2s driver can't work along with the legacy i2s driver```

**Comment by AndreoBotelho** [comment]
Tested on ESP32 and ESP32-C3, build for both is fine but esp32 gets bootloop with the message:
`E (1024) i2s(legacy): CONFLICT! The new i2s driver can't work along with the legacy i2s driver`
and esp32-c3 boots fine

**Comment by kdschlosser** [comment]
any word on this?

**Comment by kdschlosser** [comment]
This problem still exists in the latest release.

**Comment by jonnor** [comment]
When does this issue trigger? It is not entirely clear what is needed to reproduce it. Is it only when initializing machine.I2S() instance?

**Comment by kdschlosser** [comment]
This issue has been resolved. I will close it.
