### ISSUE TITLE
WebAssembly/PyScript - JS floating numbers always casted as integers

### ISSUE THREAD

**Issue by WebReflection** [micropython/micropython#13125]
It looks like both statements result into an `int` in Python world:

```python
import js

print(js.Math.random()) # always 0
print(js.performance.now()) # always int, no float precision
```

I am afraid without knowing exactly where to look at, I couldn't just push a merge request, but it's clear that MicroPython in WASM with JS FFI needs some improvement.

**Comment by dpgeorge** [comment]
Thanks for the report.  You are correct that the JS FFI interface currently only supports passing through integers from JS to Python.

That's not too hard to fix, the main code would be in `convert_js_to_mp_obj_jsside()` and `convert_js_to_mp_obj_cside()`.
