### ISSUE TITLE
[IMPORTANT] Suggested easy TODOs for contributors

### ISSUE THREAD

**Issue by pfalcon** [micropython/micropython#1331]
List of useful (some also low-hanging) tasks for *MicroPython core* (no port-specific features), with which people interested in contributing can start:

- Add tests to increase coverage (see https://coveralls.io/r/micropython/micropython?branch=master) - coverage is already high but there's always something to do here
- Refactor to use more efficient API calls to decrease code size (example: fe3cc5bb53198cc1462fb6748137d57a68960933)
- Help testing upip and report bugs for it to micropython-lib.
- ~~Implement collections.deque.~~
- ~~Implement `__slots__` for classes (hint: objects with slots are a mutable counterpart of collections.namedtuple, so reference code already exists, and good implementation would reuse as much possible of it).~~ https://github.com/micropython/micropython/pull/3392
- ~~We need minimal base64 encode/decode implementation.~~ Done, thanks @galenhz !

More advanced tasks:
- Add (minimal, as usual) xmodem/ymodem/zmodem/etc implementation (discuss first!)
- ~~Add TCP/IP stack with SLIP support.~~ Done in https://github.com/micropython/micropython/pull/1517 , thanks @galenhz !
- Implement buffered streams support (BufferedWriter implemented as a first step, this task will involve a lot of refactoring).

Keywords: novice, newcomer, newbie

**Comment by mvdw73** [comment]
What about dma for the sd card on pyboard (stm)? Is anyone working on this?

**Comment by blmorris** [comment]
DMA for the sd card would be good to have, IMHO. I was going to attempt it after wrapping up my I2S work, but it's just as well if you get to it first.
I took a quick hack at it a couple months ago without success; since then the DMA support code has been refactored so it should be easier to use.

**Comment by tkschmidt** [comment]
I would like to try to contribute to this project. 
At coveralls.io I just see a percentage of test coverage. Is there also a way to see what is not covered?

**Comment by wgreybe** [comment]
Hi. I'm not at the level where I can add value, as Im just starting to learn to code, but Id like to be part of this in order to hopefully learn (assuming I can get my head around programming).

**Comment by pfalcon** [comment]
ucollections.deque is implemented in my fork: https://github.com/pfalcon/micropython/commits/pfalcon and serves as a base of uasyncio 2.0: https://forum.micropython.org/viewtopic.php?f=15&t=85&start=80#p25186

**Comment by reidwagner** [comment]
Okay. Glad I asked!

**Comment by cr0mbly** [comment]
> Refactor to use more efficient API calls to decrease code size (example: fe3cc5b)

I'm keen to do this (Python developer but wanting to learn C and this project excites me), is this just a straight find and replace of the above `nlr_raise` calls too `mp_raise_ValueError` where where a ValueError is required.

Thanks in advance!

**Comment by iggy12345** [comment]
Is anybody working on making import statements more flexible? Would it be a good idea to add relative import statements?

**Comment by peterhinch** [comment]
Perhaps you could explain what type of relative imports where you are having problems. In my experience they work. Taken from working MicroPython code:
```python
from . import local
from .check_mid import CheckMid
```

**Comment by dpgeorge** [comment]
Closing because this issue is outdated.
