### ISSUE TITLE
missing `micropython-1.22.1.zip`

### ISSUE THREAD

**Issue by chenrui333** [micropython/micropython#13484]
👋 it looks like 1.22.1 release might not get completed as `micropython-1.22.1.zip` is missing. Thanks!

**Comment by dpgeorge** [comment]
The zip file is just a zip of the repository with all submodules checked out, and is only for convenience of those who can't use `git` to fetch the submodules.

GitHub automatically creates source zip/tgz files which contain the repository, excluding the submodules.

Do you specifically need the zip with the submodules included?

**Comment by chenrui333** [comment]
> The zip file is just a zip of the repository with all submodules checked out, and is only for convenience of those who can't use `git` to fetch the submodules.
> 
> GitHub automatically creates source zip/tgz files which contain the repository, excluding the submodules.
> 
> Do you specifically need the zip with the submodules included?

Ask mostly for convenience as it was available for the previous releasees? (I still feel like it is good to also attach the release tarball to snapshot the modules) what do you think?
