### ISSUE TITLE
NimBLE fork has not been merged for two years?

### ISSUE THREAD

**Issue by RantyDave** [micropython/micropython#13566]
MicroPython v1.22.1 on 2024-01-05; Raspberry Pi Pico W with RP2040

I'm one of the people suffering from random disconnects on Pi Pico bluetooth (https://github.com/micropython/micropython-lib/issues/596) and started picking through the code to see if there's an obvious cause. I note that you build against a fork of NimBLE and that there hasn't been a merge for over two years.

https://github.com/micropython/mynewt-nimble/compare/master...apache%3Amynewt-nimble%3Amaster

Might this help some of the Bluetooth problems?

**Comment by dpgeorge** [comment]
The rp2 port (and Pico W board) use BTstack, not NimBLE.

**Comment by stephanelsmith** [comment]
Just starting looking into an occasional intermittent ble issue for esp32, is that also the case for esp32 port?
