### ISSUE TITLE
Sandboxing

### ISSUE THREAD

**Issue by grimnight** [micropython/micropython#1356]
One of the great benefits of Lua is sandboxing, is there a plan to support sandboxing in some way?
Would it be possible to provide a limited/custom environment for `eval`?

**Comment by pfalcon** [comment]
> One of the great benefits of Lua is sandboxing

Is that really the reason why people use/choose Lua? Do you have references to that, and to specific projects which use that feature?

> is there a plan to support sandboxing in some way?

So far nobody needed it.

> Would it be possible to provide a limited/custom environment for eval?

Python generally has good enough builtin sandboxing model. All needed features may not be yet implemented in uPy, but given a good usecase, patches would be accepted. Alternatively, any builtin function can be compiled out (we're not yet there, but that's the aim), including eval().

**Comment by pfalcon** [comment]
Also, https://github.com/micropython/micropython/issues/1355 appears to be related to sandboxing either. Can you please leave only one of these open?

**Comment by dpgeorge** [comment]
To what extent would you consider it to be sandboxed?  Assuming you're talking about the unix port, the only way code can "escape" outside the uPy process is by using the ffi module (and in that case it has access to pretty much anything that it can do as the executing user), or os.system, or the socket module.  
You can easily compile uPy without these modules.

**Comment by EcmaXp** [comment]
Check https://github.com/EcmaXp/micropython
You can control CPU Time and Memory (already by gc with heap, but my port can use multi state in one process)
And custom import function (by enable override bulitin module) also supported.

Just copy unix port and modify for sandboxing.

**Comment by EcmaXp** [comment]
Example is opencom port, but problem is there is no document.

**Comment by pfalcon** [comment]
Scope is not clear, no response from submitter, closing for now.
