### ISSUE TITLE
cross compiler error

### ISSUE THREAD

**Issue by micropythondevel** [micropython/micropython#13681]
*Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
CC ../py/stackctrl.c
../py/stackctrl.c: En la función ‘mp_stack_ctrl_init’:
../py/stackctrl.c:32:32: error: storing the address of local variable ‘stack_dummy’ in ‘mp_state_ctx.thread.stack_top’ [-Werror=dangling-pointer=]
   32 |     MP_STATE_THREAD(stack_top) = (char *)&stack_dummy;
../py/stackctrl.c:31:18: nota: ‘stack_dummy’ se declara aquí
   31 |     volatile int stack_dummy;
      |                  ^~~~~~~~~~~
En el fichero incluido desde ../py/runtime.h:29,
                 desde ../py/stackctrl.c:27:
../py/mpstate.h:296:23: nota: ‘mp_state_ctx’ se declara aquí
  296 | extern mp_state_ctx_t mp_state_ctx;
      |                       ^~~~~~~~~~~~
cc1: todos los avisos se tratan como errores
See https://github.com/micropython/micropython/wiki/Build-Troubleshooting
make: *** [../py/mkrules.mk:83: build/py/stackctrl.o] Error 1
make: se sale del directorio '/home/icelon/lgvl/lv_micropython/mpy-cross'

**Comment by jonnor** [comment]
This issue does not have sufficient information to reproduce or debug the problem. If this is not provided, we will have to close it.
