### ISSUE TITLE
mod_re_compile: returned value of re1_5_sizecode() is not checked

### ISSUE THREAD

**Issue by ampli** [micropython/micropython#1369]
```
STATIC mp_obj_t mod_re_compile(uint n_args, const mp_obj_t *args) {
    ...
    int size = re1_5_sizecode(re_str);
    mp_obj_re_t *o = m_new_obj_var(mp_obj_re_t, char, size);
```

However, re1_5_sizecode() can actually return -1:
` if (!*re) return -1;`

In such a case, memory allocation of "-1" would fail.

**Comment by pfalcon** [comment]
Ack, thanks. I don't jump to fixing this, postponing until it'll become clearer what other changes we may have in re1.5.

**Comment by pfalcon** [comment]
Thanks for the report and all the contributions to re1.5! I've now tagged re1.5 v0.8, imported it into micropython and fixed the issue you pointed above.
