### ISSUE TITLE
REPL interprets open brace incorrectly

### ISSUE THREAD

**Issue by kjcole** [micropython/micropython#1387]
A string containing an open brace is interpreted as unclosed in the REPL:

    PYB: sync filesystems
    PYB: soft reboot
    Micro Python v1.4.4-90-g9220dc4 on 2015-07-09; PYBv1.0 with STM32F405RG
    Type "help()" for more information.
    >>> p = "{"
    ...

**Comment by dpgeorge** [comment]
Yes, brackets, braces and parenthesis are scanned for matching pairs irrespective of whether they are inside strings or not.  This can be improved.

**Comment by dpgeorge** [comment]
Now fixed.

**Comment by robert-hh** [comment]
Thanks. Even if it did not hurt, it was unexpected, and made me scratch my head (once again), whether I was doing somthing wrong.
