### ISSUE TITLE
Device using the block protocol is unreliable

### ISSUE THREAD

**Issue by peterhinch** [micropython/micropython#1393]
I have been experiencing random behaviour including crashes when implementing a device using the block protocol. It's proved difficult to write a script to yield a repeatable failure and my best effort is unfortunately a little long. However it does produce a repeatable crash. I suspect a memory issue.

The code and test data is at [https://github.com/peterhinch/blockdevice.git]

**Comment by peterhinch** [comment]
In case anyone has already cloned this, I've now included a second test.

**Comment by dpgeorge** [comment]
I pushed a fix for this which hopefully actually fixes it!  The problem was that the structure holding the mount info was not scanned during a GC so was being reclaimed.  Please check latest code with your example.

**Comment by peterhinch** [comment]
My tests now run fine!
