### ISSUE TITLE
stmhal: make-stmconst.py doesn't parse stm32f746xx.h file

### ISSUE THREAD

**Issue by dhylands** [micropython/micropython#1400]
I was trying to add new constants for the M7 and ran across this. It seems to be tripping up here:
https://github.com/micropython/micropython/blob/master/stmhal/make-stmconst.py#L37

while trying to parse this typedef:
https://github.com/micropython/micropython/blob/master/stmhal/cmsis/devinc/stm32f746xx.h#L1078

Changing (Global) to ([A-Za-z0-9_]+) in the regexp seems to work fine. I couldn't find any references to to the global from ```P<global>```, but I figured I'd double check in case there is something a bit more subtle happening.

I was also thinking that we should probably have make-stmconst.py be part of the build. We can generate a .c file and a qstr.h file and then just add the stm_qstr.h file to QSTR_DEFS like is done for pins here:
https://github.com/micropython/micropython/blob/master/stmhal/Makefile#L16

If we call make-stmconst.py per build, then we'll get a smaller number of qstrs generated for the smaller processors which should free up a bunch of memory.

**Comment by dpgeorge** [comment]
Issue fixed, and make-stmconst.py is now run as part of the build.
