### ISSUE TITLE
Using dict.get when a value exists but is None does not return the default

### ISSUE THREAD

**Issue by desultory** [micropython/micropython#14156]
### Checks

- [X] I agree to follow the MicroPython [Code of Conduct](https://github.com/micropython/micropython/blob/master/CODEOFCONDUCT.md) to ensure a safe and respectful space for everyone.

- [X] I've searched for [existing issues](https://github.com/micropython/micropython/issues) matching this bug, and didn't find any.

### Port, board and/or hardware

RP2

### MicroPython version

MicroPython v1.22.2 on 2024-02-22; Raspberry Pi Pico with RP2040

### Reproduction

```
>>> e22.config
{'network_id': 22, 'fixed_point_transmission': False, 'air_rate': None, 'ambient_noise': None, 'channel': 66, 'subpacket_size': None, 'serial_parity': None, 'wor_transmitter': False, 'rssi': None, 'repeater_mode': None, 'monitor_before_tx': True, 'wor_cycles': None, 'tx_power': None, 'serial_rate': None, 'address': 1000}
>>> e22.config.get('subpacket_sizer',1234)
1234
>>> e22.config.get('subpacket_size',1234)
```

### Expected behaviour

```
>>> e22.config
{'network_id': 22, 'fixed_point_transmission': False, 'air_rate': None, 'ambient_noise': None, 'channel': 66, 'subpacket_size': None, 'serial_parity': None, 'wor_transmitter': False, 'rssi': None, 'repeater_mode': None, 'monitor_before_tx': True, 'wor_cycles': None, 'tx_power': None, 'serial_rate': None, 'address': 1000}
>>> e22.config.get('subpacket_sizer',1234)
1234
>>> e22.config.get('subpacket_size',1234)
1234
```

### Observed behaviour

```
>>> e22.config
{'network_id': 22, 'fixed_point_transmission': False, 'air_rate': None, 'ambient_noise': None, 'channel': 66, 'subpacket_size': None, 'serial_parity': None, 'wor_transmitter': False, 'rssi': None, 'repeater_mode': None, 'monitor_before_tx': True, 'wor_cycles': None, 'tx_power': None, 'serial_rate': None, 'address': 1000}
>>> e22.config.get('subpacket_sizer',1234)
1234
>>> e22.config.get('subpacket_size',1234)
```

### Additional Information

No, I've provided everything above.

**Comment by dlech** [comment]
The default value is only returned if the key is not in the dictionary. So this looks like it is working the same way CPython does. Since `"subpacket_size"` is in the dictionary, it returns the value of that key as expected.
