### ISSUE TITLE
esp8266: Error OSError: -40 https request

### ISSUE THREAD

**Issue by andreyu-git** [micropython/micropython#14204]
### Checks

- [X] I agree to follow the MicroPython [Code of Conduct](https://github.com/micropython/micropython/blob/master/CODEOFCONDUCT.md) to ensure a safe and respectful space for everyone.

- [X] I've searched for [existing issues](https://github.com/micropython/micropython/issues) matching this bug, and didn't find any.

### Port, board and/or hardware

esp-8266

### MicroPython version

MicroPython v1.22.2 on 2024-02-22; ESP module with ESP8266

### Reproduction
```

import esp

import network
import urequests as requests

esp.osdebug(0)

wlan = network.WLAN(network.STA_IF)
wlan.active(True)

if not wlan.isconnected():
    print('connecting to network...')
    wlan.connect('RT166', 'mypass')

    while not wlan.isconnected():
        pass

print('network config:', wlan.ifconfig()[0])

bot_token = 'mytoken'

res = requests.get(url=f'https://api.telegram.org/bot{bot_token}/sendMessage', data={
    chat_id: '000000',
    text: 'hello'
})

print(res.text)
```

### Observed behaviour

```
Traceback (most recent call last):
  File "<stdin>", line 26, in <module>
  File "requests/__init__.py", line 184, in post
  File "requests/__init__.py", line 93, in request
OSError: -40
```

### Additional Information

Hello!

I'm trying to make an http request to the telegram api and I get the OSError error: -40

I searched for information on the Internet, but I never found a solution!

Please tell me how to fix this problem!

**Comment by dpgeorge** [comment]
The site you are trying to access, `api.telegram.org`, requires the client to support a very modern TLS (https) protocols.  The protocols that the site supports are:
```
$ nmap --script ssl-enum-ciphers -p 443 api.telegram.org
...

PORT    STATE SERVICE
443/tcp open  https
| ssl-enum-ciphers: 
|   TLSv1.2: 
|     ciphers: 
|       TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (ecdh_x25519) - A
|       TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (ecdh_x25519) - A
|       TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 (ecdh_x25519) - A
|       TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 (dh 2048) - A
|       TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 (dh 2048) - A
|     compressors: 
|       NULL
|     cipher preference: server
|   TLSv1.3: 
|     ciphers: 
|       TLS_AKE_WITH_AES_256_GCM_SHA384 (ecdh_x25519) - A
|       TLS_AKE_WITH_CHACHA20_POLY1305_SHA256 (ecdh_x25519) - A
|       TLS_AKE_WITH_AES_128_GCM_SHA256 (ecdh_x25519) - A
|     cipher preference: server
|_  least strength: A
```

An esp8266 does not support these advanced protocols because it uses axtls for the SSL library.

Even ports that use mbedtls can't access this site without enabling the following options:
```
MBEDTLS_KEY_EXCHANGE_ECDHE_RSA_ENABLED
MBEDTLS_GCM_C
```


My suggestion is to either switch to an Pico W or esp32-based board, which could support these protocols, or use a different API (not telegram).

**Comment by jonnor** [comment]
Btw, another workaround for these kinds of issues is to use a proxy server with a bit older SSL ciphers.

As mentioned above it is unfortunately not realistic to support these modern ciphers on ESP8266. Proposing to close this issue.
