### ISSUE TITLE
PWM changes duty on 2 different pins when calling duty_u16 on only one of them

### ISSUE THREAD

**Issue by jmccand** [micropython/micropython#14210]
### Checks

- [X] I agree to follow the MicroPython [Code of Conduct](https://github.com/micropython/micropython/blob/master/CODEOFCONDUCT.md) to ensure a safe and respectful space for everyone.

- [X] I've searched for [existing issues](https://github.com/micropython/micropython/issues) matching this bug, and didn't find any.

### Port, board and/or hardware

rp2 port, Arduino Nano RP2040 Connect

### MicroPython version

OpenMV 331465c; MicroPython fff2e1f; Arduino Nano RP2040 Connect-RP2040

### Reproduction

Here's my code!
```
import time
import machine
from machine import Pin, PWM
import rp2

machine.freq(120000000) # set the CPU frequency to 120 MHz

m1pin1 = Pin(5)
m1pin2 = Pin(21)

m1pwm1 = PWM(m1pin1, freq=1000, duty_u16=0)
m1pwm2 = PWM(m1pin2, freq=1000, duty_u16=0)

LED = Pin(6, Pin.OUT)

max_duty = 65535 # constant

def m1Forward(dutyCycle):
    m1pwm1.duty_u16(dutyCycle)
    m1pwm2.duty_u16(0)

def m1Backward(dutyCycle):
    m1pwm1.duty_u16(0)
    m1pwm2.duty_u16(dutyCycle)

def allStop():
  # set all duty cycles to 0
  m1pwm1.duty_u16(0)
  m1pwm2.duty_u16(0)

while True:
    allStop()
    LED.off()
    time.sleep(2)
    LED.on()
    time.sleep(2)
    LED.off()
    print('turning m1 forward')
    m1Forward(max_duty)
    time.sleep_ms(2000)

    m1Forward(int(max_duty/2))
    time.sleep_ms(2000)

    m1Backward(max_duty)
    time.sleep_ms(2000)

    m1Backward(int(max_duty/2))
    time.sleep_ms(2000)
```
It tries to turn on a motor by setting a different duty cycle to pins GPIO5 and GPIO21.

### Expected behaviour

Expected to drive the motors by providing _different_ duty cycles to GPIO5 and GPIO21. A motor driver reads the difference in voltage and sends proportional power to the motors.

### Observed behaviour

My code tries to send different duty cycles to GPIO5 and GPIO21, but when I measure the signal to each with an ammeter, I get identical waveforms: 
<img width="878" alt="Screenshot 2024-03-28 at 10 32 19 PM" src="https://github.com/micropython/micropython/assets/43151496/9a45d7c3-a3ec-4aec-97d2-611f25314568">
You can see that the purple (GPIO5) matches the orange (GPIO21), so the motor is never powered.

In fact, even when I comment out all calls to m1pwm2, I still get identical waveforms:
```import time
import machine
from machine import Pin, PWM
import rp2

machine.freq(120000000) # set the CPU frequency to 120 MHz

m1pin1 = Pin(5)
# m1pin2 = Pin(21)

m1pwm1 = PWM(m1pin1, freq=1000, duty_u16=0)
# m1pwm2 = PWM(m1pin2, freq=1000, duty_u16=0)

LED = Pin(6, Pin.OUT)

max_duty = 65535 # constant

def m1Forward(dutyCycle):
    m1pwm1.duty_u16(dutyCycle)
    # m1pwm2.duty_u16(0)

def m1Backward(dutyCycle):
    m1pwm1.duty_u16(0)
    # m1pwm2.duty_u16(dutyCycle)

def allStop():
  # set all duty cycles to 0
  m1pwm1.duty_u16(0)
  # m1pwm2.duty_u16(0)

while True:
    allStop()
    LED.off()
    time.sleep(2)
    LED.on()
    time.sleep(2)
    LED.off()
    print('turning m1 forward')
    m1Forward(max_duty)
    time.sleep_ms(2000)

    m1Forward(int(max_duty/2))
    time.sleep_ms(2000)

    m1Backward(max_duty)
    time.sleep_ms(2000)

    m1Backward(int(max_duty/2))
    time.sleep_ms(2000)
```

I know that this is a software issue because when I run the following basic motor test, which uses on()/off() calls instead of PWM, the motors turn in both directions as expected.
```
import time
from machine import Pin

m1pin1 = Pin(21, Pin.OUT)
m1pin2 = Pin(5, Pin.OUT)
m2pin1 = Pin(18, Pin.OUT)
m2pin2 = Pin(17, Pin.OUT)

LED = Pin(6, Pin.OUT)

def m1Forward():
    m1pin1.on()
    m1pin2.off()

def m1Backward():
    m1pin1.off()
    m1pin2.on()

def m2Forward():
    m2pin1.on()
    m2pin2.off()

def m2Backward():
    m2pin1.off()
    m2pin2.on()

def allStop():
    m1pin1.off()
    m1pin2.off()
    m2pin1.off()
    m2pin2.off()

while True:
    allStop()
    time.sleep(2)
    m1Forward()
    time.sleep(2)
    m1Backward()
    time.sleep(2)
    m2Forward()
    time.sleep(2)
    m2Backward()
    time.sleep(2)
```

### Additional Information

I'm using the OpenMV IDE, which is why the startup message from the board looks different. If there's something else I should run on the board to check what version of MicroPython it's running, I can try that.

**Comment by robert-hh** [comment]
Pin 5 and 21 share the same PWM channel & slice. You can check that by printing mp1pwm1 and m1pwm2. Channels are assigned by pin # mod 8, and slices by the Pin number being even or odd. Pins with the same slice have the same frequency, but the channels may have different duty. So instead of choosing pins 5 and 21, which are both on slice 2, channel 1, select e.g. Pin 4 and 5, or 20 and 21 and pin pair.
See: https://docs.micropython.org/en/latest/rp2/quickref.html#pwm-pulse-width-modulation

**Comment by jmccand** [comment]
Okay I'll change the pins. Because channels are assigned by pin # mod 8, does that mean whenever I drive GPIO5, I also drive GPIO13, GPIO21 and GPIO29, even if I don't want to?
Do you suggest selecting pin pairs because two pins with the same slice must have the same frequency, which is compatible with powering a motor? If I wanted could I select pins 5 and 19, even though they have different slices?
Thanks for the help.

**Comment by robert-hh** [comment]
Sorry, the slice assignment is slice = (pin_# / 2) % 8. So Pins 0 and 1 belong to the same slice, but different channels, pins 16 and 17 belong to the same Slice/channel pair as pins 0 and 1. If you have a PWM at Pin 5, you do not have PWM enabled at Pin 21 as well. That is an additional step. Only if you do, you get the same signal as on Pin 5.
Different channels pins of a slice may have different duty and polarity.

**Comment by jmccand** [comment]
Ok, thanks for the clarification.
