### ISSUE TITLE
RPI-PICO-W (CYW43) Wi-Fi AP can only be configured when not active

### ISSUE THREAD

**Issue by IAmDazen** [micropython/micropython#14224]
### Checks

- [X] I agree to follow the MicroPython [Code of Conduct](https://github.com/micropython/micropython/blob/master/CODEOFCONDUCT.md) to ensure a safe and respectful space for everyone.

- [X] I've searched for [existing issues](https://github.com/micropython/micropython/issues) matching this bug, and didn't find any.

### Port, board and/or hardware

pico w

### MicroPython version

Micropython RP2040 Board CDC COM3

### Reproduction

my pico w's access point is locked with the wrong password, it still has a password when i remove it I CANNOT FIX THIS AND THE SSID IS WRONG IT IS SET AS PICO2F6F NOT PicoServer AS IT SHOULD AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA JUST USING ACCESS POINTS BREAK IT

### Expected behaviour

expected to create AP and create webserver from there

### Observed behaviour

no exception, just broken

### Additional Information

No, I've provided everything above.

**Comment by robert-hh** [comment]
Setting the AP name and password works for me if I do the BEFORE setting the AP active.

**Comment by jonnor** [comment]
Hi and thank you for the bug report. Can you provide a minimal code example which demonstrates this problem? And which version of MicroPython are you using?

**Comment by projectgus** [comment]
Can confirm this behaviour - the PICO-W requires you to set `active(False)` *before* configuring the AP config or it doesn't change the actual Wi-Fi behaviour. Whereas the docs say to set `active(True)` before configuring, and the esp8266 and esp32 ports require that.

Fix incoming.
