### ISSUE TITLE
bytearray slice assignment from generator produces error

### ISSUE THREAD

**Issue by peterhinch** [micropython/micropython#1424]
Is this an intentional "micro" difference from Cpython or an oversight? This works in Cpython but produces a "Not implemented" error in MicroPython (on Pyboard).

``` python
b = bytearray(20)
b[2:7] = (1 for x in range(5))
```

While the following workround is trivial I thought it worth flagging up:

``` python
b[2:7] = bytes(1 for x in range(5))
```

**Comment by dpgeorge** [comment]
I think it's subconsciously intentionally "micro", ie, there was no need at the time to implement it and since it's not been requested until now it's probably something that can stay as unimplemented.

**Comment by dpgeorge** [comment]
Closing due to lack of interest.
