### ISSUE TITLE
ValueError: SPI(0) doesn't exist on Nucleo F767ZI

### ISSUE THREAD

**Issue by luca827** [micropython/micropython#14388]
### Checks

- [X] I agree to follow the MicroPython [Code of Conduct](https://github.com/micropython/micropython/blob/master/CODEOFCONDUCT.md) to ensure a safe and respectful space for everyone.

- [X] I've searched for [existing issues](https://github.com/micropython/micropython/issues) matching this bug, and didn't find any.

### Port, board and/or hardware

Nucleo F767ZI

### MicroPython version

MicroPython v1.22.2

### Reproduction

from machine import SPI

spi = SPI(0, sck='D13', miso='D12', mosi='D11')

### Observed behaviour

Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
ValueError: SPI(0) doesn't exist

### Additional Information

No, I've provided everything above.

**Comment by dpgeorge** [comment]
SPI indices start at 1 on STM32 boards.  There is no `SPI(0)`.

**Comment by andrewleech** [comment]
Check the pins your specifying are correct for the SPI channel you're trying to use, stm chips generally only have 1 or 2 pins that can work for each SPI channel.

**Comment by dpgeorge** [comment]
> Where can I find the documentation which indices should work?

Each board has a configuration that specifies which UART/SPI/etc are defined.  For the Nucleo F767ZI see here: https://github.com/micropython/micropython/blob/master/ports/stm32/boards/NUCLEO_F767ZI/mpconfigboard.h#L52-L56

Only SPI(3) is defined, on pins PB3, PB4, PB5.

**Comment by andrewleech** [comment]
You should be able to use the other SPI channels too by specifying the pins in the unit call like on your original example.

The supported pins for each peripheral on this chip can be found in https://github.com/micropython/micropython/blob/master/ports/stm32/boards/stm32f767_af.csv

**Comment by jonnor** [comment]
The way to resolve this (and similar issues) seems to have been provided above. Proposing to close this issue.
