### ISSUE TITLE
docs: MicroPython Internals / Optimizations Typo

### ISSUE THREAD

**Issue by newcomb-luke** [micropython/micropython#14391]
### Checks

- [X] I agree to follow the MicroPython [Code of Conduct](https://github.com/micropython/micropython/blob/master/CODEOFCONDUCT.md) to ensure a safe and respectful space for everyone.

- [X] I've searched for [existing issues](https://github.com/micropython/micropython/issues) and didn't find any that matched.

### Documentation URL

https://docs.micropython.org/en/latest/develop/optimizations.html#variables

### Description

Extremely minor typo that anyone who modifies the docs for a real reason can fix.

Under the Variables section it says "Local variables on the other hand are are stored on the Python value stack..."

**Comment by mattytrentini** [comment]
Thanks @newcomb-luke! I've read the paragraph at least a dozen times and never noticed. :)

It would have been fine to submit a PR yourself by the way; it could be merged on it's own or integrated into a bigger merge..

**Comment by dpgeorge** [comment]
Fixed by b1ac266bb5cd0fcfa53539cb3230e7b3f323a09b
