### ISSUE TITLE
[webassembly] element.onclick = async fn fails

### ISSUE THREAD

**Issue by WebReflection** [micropython/micropython#14400]
### Checks

- [X] I agree to follow the MicroPython [Code of Conduct](https://github.com/micropython/micropython/blob/master/CODEOFCONDUCT.md) to ensure a safe and respectful space for everyone.

- [X] I've searched for [existing issues](https://github.com/micropython/micropython/issues) matching this bug, and didn't find any.

### Port, board and/or hardware

webassembly PyScript port

### MicroPython version

latest

### Reproduction

```python
async def thing(event):
    print(event)

element.onclick = thing
```

There's no way to have an async listener.

### Expected behaviour

in *JS* and other runtimes, `element.onclick = async_ref` works, in MicroPython nothing happens ... `async def():` are all ignored when assigned, either via `run` or `runAsync` utilities.

### Observed behaviour

in *JS* and other runtimes, `element.onclick = async_ref` works, in MicroPython nothing happens ... `async def():` are all ignored when assigned, either via `run` or `runAsync` utilities.

### Additional Information

No, I've provided everything above.

**Comment by dpgeorge** [comment]
I can't reproduce the problem.  Assigning async functions to onclick works for me.  Eg with the following code:
```
py.runPython(`
    import js

    async def thing(event):
        print(event)

    element = js.document.getElementById("test-button")
    element.onclick = thing
`);
```
If there's a `<button>` with "test-button" id then clicking that button prints the event to the JS console.

What is the exact version of the webassembly port that you are using?  Print the value of `sys.version` to find out.

**Comment by WebReflection** [comment]
@dpgeorge I am deeply sorry I was indeed on an previous version and with latest everything looks fine. Apologies for any inconvenience.
