### ISSUE TITLE
nrf24l01 driver SPI problem

### ISSUE THREAD

**Issue by peterhinch** [micropython/micropython#1466]
This driver initialises the SPI bus with polarity=0, phase=1. This produces the following waveform (red SCK, yellow MOSI)
![phase1](https://cloud.githubusercontent.com/assets/8437477/9956976/96bff49e-5df4-11e5-85db-abff230eb270.png)
This contradicts the datasheet which shows MOSI changing on the clock negative edge, and being read on the positive edge.
![screenshot - 180915 - 11 08 04](https://cloud.githubusercontent.com/assets/8437477/9957138/abf59caa-5df5-11e5-9fc2-944dc7eda8f0.png)
Setting phase=0 produces the correct waveform, and results in more reliable SPI communication.
![phase0](https://cloud.githubusercontent.com/assets/8437477/9957095/52a6a82e-5df5-11e5-9857-c41de22e3706.png)

**Comment by dpgeorge** [comment]
Yes I think you're right, it should be phase=0.

This error is unfortunately a recurring theme: a while back 480a7ce58f6e5dc6179373f1f8b69d6a5434b2d4 the phase convention was changed from 1/2 to 0/1 to match industry standard (see #936).  The existing drivers (like nrf24) were not updated with the change.

**Comment by dpgeorge** [comment]
Fixed in b0c08c8c173cbfe66ad78af55f4025543bbdbd9b.
