### ISSUE TITLE
Prepare to 1.4.6 release?

### ISSUE THREAD

**Issue by pfalcon** [micropython/micropython#1475]
There're changes like #1470 which noticeably change build process. Should we tag 1.4.6 (>170 commits since 1.4.5), to let more time for changes like above to be testes, stabilize, documented, etc.?

**Comment by dpgeorge** [comment]
Yes I agree go to 1.4.6 before #1470 is merged.

What about the new hardware API #1430... and shipping of WiPy?  @danicampora how about we tag 1.4.6 before shipping, is that possible or not anymore?

**Comment by danicampora** [comment]
@dpgeorge yes, it is possible, please go ahead. We still have a few days work before shipping can start.

**Comment by dpgeorge** [comment]
Ok.  Please list anything that wants in before 1.4.6 and then it'll be tagged within the next 24 hours.

**Comment by danicampora** [comment]
Nothing from my side.

**Comment by pfalcon** [comment]
Nothing specific from me too.

**Comment by dpgeorge** [comment]
Done in 5572f735b65cb4704725966d5437564501ceb673.
