### ISSUE TITLE
FYI + fix ESP8266 will crash if TCP connection fails and espconn_regist_reconcb is not set up.

### ISSUE THREAD

**Issue by mianos** [micropython/micropython#1486]
There is an additional callback for the tcp connection API ```espconn_regist_reconcb(..``` that is called when the connection fails (initially or later, a badly named API for sure).
If a handler is not registered, when you fail to connect to the remote port the ESP firmware will crash.
I implemented this additional callback for micropython in:
https://github.com/mianos/micropython/commit/ac1f123df71e9c56e6a263bbc594781f1d9ceab7

Once this is implemented (and my other changes) you can re-enable the watchdog and this board seems to be 100% stable. Totally awesome.

**Comment by dpgeorge** [comment]
Good to hear the progress!  Hopefully we can merge these fixes into the repo soon.
