### ISSUE TITLE
Documentation of pyb.standby() appears incorrect

### ISSUE THREAD

**Issue by peterhinch** [micropython/micropython#1489]
The docs state:
"pyb.standby()
Put the pyboard into a “deep sleep” state.
This reduces power consumption to less than 50 uA. To wake from this sleep state requires an external interrupt or a real-time-clock event. Upon waking the system undergoes a hard reset."

The reference manual (RM0090) Table 23 (Section 5.3 - Low Power Modes on page 126) seems to indicate that EXTI can only wake the processor up when it's in stop mode, and not when its in standby mode.

My reading of the manual indicates that the only external interrupt capable of being supported by the Pyboard is a tamper interrupt on pin X18.

**Comment by dpgeorge** [comment]
I agree.  Can only be woken by 2 pins: WKUP (PA0=X1) or TAMP1 (PC13=X18).

**Comment by dpgeorge** [comment]
Fixed in 845b5a2a582023caf484f87e6f12abc715f6b922.
