### ISSUE TITLE
wipy: Doc still shows "import pyb" instead of "import machine"

### ISSUE THREAD

**Issue by Bittencourt** [micropython/micropython#1498]
Hi Guys,

I`m new here, so sorry if this issue is already being addressed or I`m simply looking at the wrong site for the docs of the cc3200 version (http://micropython.org/resources/docs/en/latest/wipy/index.html).
but the "pyb" lib was changed in the code to "machine" but not in docs.

**Comment by danicampora** [comment]
You are completely right, docs are outdated, we'll update them once done with shipping!

**Comment by Bittencourt** [comment]
Thank you for the quick answer.

Once I become more used to the code I will be glad to help on those minor fixes.

**Comment by danicampora** [comment]
That would be awesome! Thanks :-).

**Comment by pfalcon** [comment]
@danicampora : I believe I read changelog that this was fixed?

**Comment by danicampora** [comment]
Yes, it is fixed now, thanks.

**Comment by dpgeorge** [comment]
Docs have been re-generated from source so looks like it's now fixed.
