### ISSUE TITLE
REPL don't start via UART on CC3200 version

### ISSUE THREAD

**Issue by Bittencourt** [micropython/micropython#1499]
Hi,

I had a small issue using the REPL terminal via UART on version 1.0. After successfully flashing (verified by accessing the REPL via telnet) the uart 0 is mute. By the documentation i considered that the terminal would be accessible by uart0 on boot.

I'm using a CC3200 launchpad board. If there is config I should enable for that may be a good idea to put on the readme file on the cc3200 folder of the project.

Thank you,

**Comment by danicampora** [comment]
With the CC3200 there's only one official REPL, which is the telnet one. If you one terminal duplication on the UART do:

```python
from machine import UART
import os
uart = UART(0, 115200)
os.dupterm(uart)
```

But yes, you are right, this should be documented, any help is welcome ;-)

Cheers,
Daniel

**Comment by Bittencourt** [comment]
Thank you, worked fine. 

I will try to add this to readme file, but I think it will be necessary a pull request.
And I'll be glad to help.

**Comment by danicampora** [comment]
Yes, a pull request is the way to go, thanks.
