### ISSUE TITLE
Please add 'v1.24.0-preview' Git tag for mpy-cross headers generating properly

### ISSUE THREAD

**Issue by Plaque-fcc** [micropython/micropython#15174]
### Checks

- [X] I agree to follow the MicroPython [Code of Conduct](https://github.com/micropython/micropython/blob/master/CODEOFCONDUCT.md) to ensure a safe and respectful space for everyone.

- [X] I've searched for [existing issues](https://github.com/micropython/micropython/issues) matching this bug, and didn't find any.

### Port, board and/or hardware

any

### MicroPython version

v1.24.0-preview.4.g3613ad962

### Reproduction

( on current branch master — 3613ad96244ecaa67e8d45b637dc6b24fd2942be )
cd mpy-cross && make clean && make && grep -i 'git' build/genhdr/mpversion.h

You get:
#define MICROPY_GIT_TAG "v1.23.0-5.g3613ad962"
#define MICROPY_GIT_HASH "3613ad962"

### Expected behaviour

Expected this header file to contain tag name which reflects current version, like so:

#define MICROPY_GIT_TAG "v1.24.0-preview.4.g3613ad962"
#define MICROPY_GIT_HASH "3613ad962"

### Observed behaviour

MICROPY_GIT_TAG variable mentions tag `v1.23.0`, because there's no specific preview tag for v1.24.0 yet.

### Additional Information

If you simply add `v1.24.0-preview` tag after v1.23.0, it will fix this header file. Thanks in advance.

**Comment by dpgeorge** [comment]
Now done.
