### ISSUE TITLE
asm: inline assembler: directive "data" for all the micros

### ISSUE THREAD

**Issue by massimosala** [micropython/micropython#15248]
### Description

Form the thumb2 micros, in the _inline assembler_ it is available the directive _data_
https://docs.micropython.org/en/latest/reference/asm_thumb2_directives.html

A clever usage of _data_ is to make assembler instructions available to python.
Examples:
```
@micropython.asm_thumb
def rbit(r0):
    data(2, 0xfa90, 0xf0a0)

@micropython.asm_thumb
def clz(r0):
    data(2, 0xfab0, 0xf080)
```

Note: these are only examples, I am NOT talking about to implement bit reversal and counting leading zeroes.

I think it is nice to have the _data_ directive available for all the supported architectures: armv6m, xtensa, xtensawin, riscv
also where _inline assembler_ isn't (still) implemented. 

### Code Size

I don't know

### Implementation

I would like to sponsor development of this feature

### Code of Conduct

Yes, I agree

**Comment by dpgeorge** [comment]
> I think it is nice to have the _data_ directive available for all the supported architectures: armv6m, xtensa, xtensawin, riscv

MicroPython currently only supports two inline-asm decorators: `@micropython.asm_thumb` and `@micropython.asm_xtensa`.  And for both of these the `data()` directive is available.

Actually, the `data()` and `align()` and `label()` directives are all handled in the same way for all inline-asm architectures in the common compile code.  So whenever a new arch is added it will support these directive automatically.
