### ISSUE TITLE
Build errors when building RPI_PICO for debug

### ISSUE THREAD

**Issue by peterharperuk** [micropython/micropython#15276]
### Port, board and/or hardware

RPI_PICO

### MicroPython version

v1.24.0-preview.36.gd7d77d91b.dirty

### Reproduction

cd ports/rp2
make -j8 DEBUG=1 -k

### Expected behaviour

Should build ok

### Observed behaviour

In file included from /home/peterh/source/pico/micropython_latest/lib/pico-sdk/src/common/pico_base/include/pico/assert.h:18,
                 from /home/peterh/source/pico/micropython_latest/lib/pico-sdk/src/common/pico_base/include/pico/types.h:12,
                 from /home/peterh/source/pico/micropython_latest/lib/pico-sdk/src/common/pico_base/include/pico.h:24,
                 from /home/peterh/source/pico/micropython_latest/lib/pico-sdk/src/common/pico_sync/include/pico/lock_core.h:10,
                 from /home/peterh/source/pico/micropython_latest/lib/pico-sdk/src/common/pico_sync/include/pico/mutex.h:10,
                 from /home/peterh/source/pico/micropython_latest/ports/rp2/pendsv.c:28:
/home/peterh/source/pico/micropython_latest/ports/rp2/pendsv.c: In function 'PendSV_Handler':
/home/peterh/source/pico/micropython_latest/ports/rp2/pendsv.c:87:12: error: 'pensv_mutex' undeclared (first use in this function); did you mean 'pendsv_mutex'?
   87 |     assert(pensv_mutex.enter_count == 1);
      |            ^~~~~~~~~~~
/home/peterh/source/pico/micropython_latest/ports/rp2/pendsv.c:87:12: note: each undeclared identifier is reported only once for each function it appears in
make[3]: *** [CMakeFiles/firmware.dir/build.make:3355: CMakeFiles/firmware.dir/pendsv.c.obj] Error 1
In file included from /home/peterh/source/pico/micropython_latest/py/nlr.h:33,
                 from /home/peterh/source/pico/micropython_latest/py/mpstate.h:34,
                 from /home/peterh/source/pico/micropython_latest/py/runtime.h:29,
                 from /home/peterh/source/pico/micropython_latest/shared/tinyusb/mp_usbd.h:36,
                 from /home/peterh/source/pico/micropython_latest/shared/tinyusb/mp_usbd_runtime.c:29:
/home/peterh/source/pico/micropython_latest/shared/tinyusb/mp_usbd_runtime.c: In function '_runtime_dev_count_itfs':
/home/peterh/source/pico/micropython_latest/shared/tinyusb/mp_usbd_runtime.c:199:19: error: comparison of distinct pointer types lacks a cast [-Werror]
  199 |     assert(p_desc <= itf_desc && itf_desc < p_end);
      |                   ^~
/home/peterh/source/pico/micropython_latest/shared/tinyusb/mp_usbd_runtime.c:199:43: error: comparison of distinct pointer types lacks a cast [-Werror]
  199 |     assert(p_desc <= itf_desc && itf_desc < p_end);
      |                                           ^
cc1: all warnings being treated as errors

### Additional Information

No, I've provided everything above.

### Code of Conduct

Yes, I agree

**Comment by dpgeorge** [comment]
Fixed by e35f13a22df63cfa165a5fac7f8236a0d0711e77 and 9111fa58312440fbddb4e67e9966386b3890d8d6
