### ISSUE TITLE
stmhal: USB_VCP.recv(N) return garbage data in case of timeout

### ISSUE THREAD

**Issue by pfalcon** [micropython/micropython#1529]
With `u = pyb.USB_VCP()` run:

`u.recv(5, timeout=1000)`, and quickly type 5 keys, result: `b'12345'`
`u.recv(5, timeout=1000)`, and  type 2 keys, result: `b'12\x00\x00,'`
`u.recv(5, timeout=1000)`, don't type any keys, result: `b'3\x01\x00\x00,'`

I don't think this can be expected, expected result is that only valid received data should be returned (or empty bytes).

(latest master)

**Comment by dpgeorge** [comment]
Fixed, see above commit.

In next version of API I suspect that the send/recv methods will go (just use write/read).  Send/recv are useful in that they allow to specify a timeout, but stream methods can support that using some ioctl call or other config method.
