### ISSUE TITLE
Add micropython welcome messages basic  and  on unix-based systems

### ISSUE THREAD

**Issue by torwag** [micropython/micropython#154]
Hi, 

I would like to add a welcome message to micropythons shell at least on unix based systems (same as what Cpython versions print during start). Ideally, it should work on uC too, but we should be able to enable or disable it (during runtime by a command in the config file).
Being able to disable it might be important, since parsing the output of a uC received via USB (serial) might take an extra burden, if one has to make sure to get rid of the welcome message first. E.g. after each reset, the buffer is spammed with the welcome message before measurement data is send to the buffer.
On the other hand it is a nice first I'm alive signal, helpful for debugging.

Esp. since we work on a dev-branch it would be nice to get some initial feedback which version one is using.

Taken the actual python welcome message as an example I would like to add

MicroPython X.XX
[GCC 4.8.2] on linux  [1]
See www.micropython.org for more information.
The MIT License (MIT) (c) 2013 Damien P. George
>>>

[1] this line might change respectively: e.g. 
* [GCC ARM] on 32 bit ARM Cortex M4 CPU (STM32F405RGSTM)

or a customized line via config to identify which board is in use
e.g.

*  Myproject-Servo-controller V1.2

Guess at this point is is not necessary to add additional help, license or credit commands as CPython does.

**Comment by dpgeorge** [comment]
Closing because there is no real need for printing a custom banner, and unix prints the same-format banner as all other ports.
