### ISSUE TITLE
cc3200: When initialising pin for the first time as output, value=1 does not work

### ISSUE THREAD

**Issue by dpgeorge** [micropython/micropython#1542]
To reproduce, reset the board and run:
```python
>>> p = Pin('GP0', Pin.OUT, value=1)
>>> p()
0
```
Creating the pin a second time works, so I suspect that setting the output value before the GPIO is fully configured does not work.

**Comment by danicampora** [comment]
Interesting, does this mean that you received your WiPy's today :-) ?

**Comment by danicampora** [comment]
Thanks Damien. Fixed in https://github.com/micropython/micropython/commit/19502957357aadf04015fd55272ae051d9fb0f23
