### ISSUE TITLE
examples/network/https_client.py + cloudflare.com = OSError: 97

### ISSUE THREAD

**Issue by CardealRusso** [micropython/micropython#15580]
### Port, board and/or hardware

Unix

### Reproduction

https://raw.githubusercontent.com/micropython/micropython/master/examples/network/https_client.py

If i use cloudflare.com in place of google.com o get OSError: 97 Any tips?

**Comment by dpgeorge** [comment]
It's because the `getaddrinfo()` is returning an IPv6 address as the first one.

To force IPv4 use:
```
ai = socket.getaddrinfo("cloudflare.com", 443, socket.AF_INET)
```

**Comment by CardealRusso** [comment]
thanks

**Comment by dpgeorge** [comment]
I've improved the examples in #15588, so they work with both IPv4 and IPv6.
