### ISSUE TITLE
stmhal: Improve RTC startup

### ISSUE THREAD

**Issue by dpgeorge** [micropython/micropython#1559]
We can improve the way stmhal starts up and initialises the RTC.  This is tied into the way that the device resets, either by power up, hard reset, soft reset, or exiting standby mode.  Some desired features:
1. Detect exactly when RTC initialisation is needed, and when calendar reset is need.  This may already be solved but needs to be tidied up.
2. Support LSE/LSI detection on startup, see #1546.
3. Perform LSE startup "in the background" while booting, because currently it can take up to 500ms.
4. Provide a way to indicate to the user what the reset cause was.  machine.reset_cause() and machine.wake_reason() are used for this.
5. It would be good to set the CPU clock to it's previous value when exiting standby mode, since in low power applications you wan't a slower clock and having it 168MHz on boot (even for a few ms) wastes power.  This is not really RTC related, but is related to detecting what kind of reset occurred.

**Comment by chuckbook** [comment]
Just completed a patch that includes the LSE/LSI handling with initial fallback on faulty LSE.
I'm not sure if "background startup" makes sense.
If we agree upon a dedicated memory location in the backup area, we have a solution:
valid LSE/LSI --> valid (freq-)backup --> defined frequency

**Comment by TDAbboud** [comment]
I am currently working on implementing bullets 1 and 4, but I have a question regarding the reset states. What is the difference between the power-up and hard reset? I am under the impression that a power-up reset is a type of hard reset, but a hard reset does not necessarily have to be a power-up reset. How else can you perform a hard reset?

**Comment by dhylands** [comment]
pyb.hard_reset() or machine.reset()

**Comment by peterhinch** [comment]
@TDAbboud A few thoughts regarding bullet 4. The Pyboard can be woken from deep sleep by interrupts on the Tamper and WKUP pins (X18 and X1 respectively) in addition to an RTC wakeup event. This is how I distinguish them
```python
def why():
# after detecting and returning power up status
    rtc_isr = stm.mem32[stm.RTC + stm.RTC_ISR]
    if rtc_isr & 0x2000 == 0x2000:
        return 'TAMPER'
    if rtc_isr & 0x400 == 0x400:
        return 'WAKEUP'
    return 'X1'
```
I haven't found a way properly to detect WKUP events on X1 - so currently it's assumed in the absence of any other cause. Perhaps you know the answer to this?

**Comment by dpgeorge** [comment]
I think point 1 is being solved by #1571.

**Comment by TDAbboud** [comment]
@dpgeorge I didn't see that, so I will just continue with point 4 then.

After doing some testing on the reset states I have found that a Power-on hard reset differs slightly than the hard reset done through machine.reset(). The machine.reset sets the software reset (SFTRST) flag, which is not currently checked in the rtc code.

@peterhinch I have to do some more reading in the datasheet, but from what I have read you should be able to check the WUF (wakeup) flag which is bit 0 of the PWR_CSR register. There is also the WKUPINT in the USB_OTG registers

**Comment by dhylands** [comment]
We need to code a reset_cause function which sounds like it could be shared with/used by this code.

**Comment by peterhinch** [comment]
It would be good if reset_cause returned the pin which caused a pin wakeup. Perhaps by means which can be generalised for other platforms. This would save ``stm.mem32()`` hacks.

**Comment by dpgeorge** [comment]
RTC startup was improved long ago, and feature to restore PLL values to previous state was also added.  reset_cause() method was added to machine module (but see #2500 for further improvements to that).
