### ISSUE TITLE
Global variables do not work with native emitter across module imports

### ISSUE THREAD

**Issue by HenrikSolver** [micropython/micropython#1573]
Crate a file called nativebug.py with the following content.

```
K = 10

@micropython.native
def foo(a):
    b = K*a
    return b
```

Import the file and call foo.

```
import nativebug
nativebug.foo(4)
```

with the native decorator the result will be 

```
NameError: name 'K' is not defined
```

Without the decorator the function will work as expected

Reference to discussion in the forum.
http://forum.micropython.org/viewtopic.php?f=2&t=1078&start=0

**Comment by dpgeorge** [comment]
This should be fixed by 4f3d9429b54ccc2d36123c861cd916b1ee15c640
