### ISSUE TITLE
docs: esptool in makefile invocation is pointing to py file instead of tool 

### ISSUE THREAD

**Issue by uid89626** [micropython/micropython#15790]
### Description

diff --git a/ports/esp8266/Makefile b/ports/esp8266/Makefile
index cd94a38a7..8e603b086 100644
--- a/ports/esp8266/Makefile
+++ b/ports/esp8266/Makefile
@@ -193,11 +193,11 @@ FROZEN_EXTRA_DEPS = $(CONFVARS_FILE)
 
 deploy: $(FWBIN)
        $(ECHO) "Writing $< to the board"
-       $(Q)esptool.py --port $(PORT) --baud $(BAUD) write_flash --verify --flash_size=$(FLASH_SIZE) --flash_mode=$(FLASH_MODE) 0 $<
+       $(Q)esptool --port $(PORT) --baud $(BAUD) write_flash --verify --flash_size=$(FLASH_SIZE) --flash_mode=$(FLASH_MODE) 0 $<
 
 erase:
        $(ECHO) "Erase flash"
-       $(Q)esptool.py --port $(PORT) --baud $(BAUD) erase_flash
+       $(Q)esptool --port $(PORT) --baud $(BAUD) erase_flash
 
this is a syntax error because you are invoking a py file like an executable.

### Code of Conduct

Yes, I agree

**Comment by dpgeorge** [comment]
> this is a syntax error because you are invoking a py file like an executable

No, it is correct as it is.

You can execute a file such as `esptool.py`.  It just needs to be executable and have the correct `#!...` line at the start.
