### ISSUE TITLE
Files on SD card overwritten by large files 

### ISSUE THREAD

**Issue by njberland** [micropython/micropython#1584]
I have had an issue with logging data to a file on the SD card.
It worked fine for a period - but now after a while other files on the SD card were corrupted with content from the logging.

**Comment by dhylands** [comment]
This can happen if you use the USB Mass Storage feature (i.e. CDC+MSC or VCP+MSC)

**Comment by njberland** [comment]
If I use it without plugging it into a Linux computer it works fine! Thanks!

**Comment by turbinenreiter** [comment]
see https://github.com/micropython/micropython/tree/master/examples/SDdatalogger
especially look at boot.py

**Comment by dpgeorge** [comment]
I guess this can be closed.

**Comment by njberland** [comment]
Indeed!
