### ISSUE TITLE
PIO mov instruction does not have operation functions

### ISSUE THREAD

**Issue by sk8board** [micropython/micropython#15858]
### Port, board and/or hardware

rp2, Raspberry Pi Pico

### MicroPython version

MicroPython v1.23.0 on 2024-06-02; Raspberry Pi Pico with RP2040

### Problem Statement

The PIO mov instruction does not have operation functions

### Documentation

Raspberry Pi RP2040 datasheet shows the mov instruction accepts three inputs: destination, operation, and source.

![image](https://github.com/user-attachments/assets/9a073cbe-630f-42fa-8e5c-4246759b42c5)

MicroPython only accepts two inputs and omits operation, as shown here:

https://github.com/micropython/micropython/blob/master/ports/rp2/modules/rp2.py#L165C9-L165C16

![image](https://github.com/user-attachments/assets/beb46fc1-f6cd-4a74-873c-2a68e32ceabc)

This means the important operations of the move instruction, like invert and reverse are not available in MicroPython.

Invert and reverse are key operations of PIO. 

### Expected behaviour

The expectation is for invert and reverse operations of the mov instruction within PIO to operate as designed by Raspberry Pi.

### Observed behaviour

Invert and reverse operations of the mov instruction within PIO are not available.

### Additional Information

No, I've provided everything above.

### Code of Conduct

Yes, I agree

**Comment by rkompass** [comment]
It should have it.
It's documented: [here](https://docs.micropython.org/en/latest/library/rp2.html)
And iirc, I already had used it successfully.

The thing seems to be that `invert()` or `reverse()` are processed separately before going into the` mov() `processing.

**Comment by sk8board** [comment]
Thank you for your reply. This is very helpful.

I would like to make a suggestion to help ensure others do not make this same mistake. The screenshots below show that finding this information is not intuitive. Maybe a large hyperlink could be implemented that is obvious to help enforce that additional PIO information is available at the hyperlink?

![image](https://github.com/user-attachments/assets/27376f26-4a4e-4bf2-a40f-aa085f6ce5b2)

![image](https://github.com/user-attachments/assets/b6294c4a-b3c5-4670-b919-7372b4c769c8)
