### ISSUE TITLE
A suggestion to add the modbus library in the micropython's .uf2

### ISSUE THREAD

**Issue by Omid888** [micropython/micropython#15865]
### Description

Since there is a sophisticated Modbus library for micropython, ([https://github.com/brainelectronics/micropython-modbus]()), I suggest adding the library to the micropython's libraries like the CAN-BUS library that is built-in.

**Comment by tstenvold** [comment]
There is no reason you cannot already do this by installing it via mip or mpremote, or setting it in the manifest during the build process. Adding a third-party library by default into a specific port (boards that support uf2) is not an ideal solution.

**Comment by Omid888** [comment]
> Adding a third-party library by default into a specific port (boards that support uf2) is not an ideal solution.

Of course, you're right, I asked the wrong question.
another question: Is this library specific to uf2 supporting boards or it can be used on all micropython supported microcontrollers?

P.S: many third party libraries are in the micropython base (i.e ds1820 library), and I think it's not a bad idea necessarily.

**Comment by sosi-deadeye** [comment]
The biggest reason not to include everything is limited flash size. The other reason is, that someone has to maintain it.

**Comment by felixdoerre** [comment]
> many third party libraries are in the micropython base (i.e ds1820 library), and I think it's not a bad idea necessarily.

This is not true. Firstly, `ds18x20` is not a third party library, but a library maintained by micropython (https://github.com/micropython/micropython-lib/tree/master/micropython/drivers/sensor/ds18x20), and secondly it are not "many" libraries,
that are by default included. For example on the rp2-pico, they are (apart from networking for pico_w) exactly 4: https://github.com/micropython/micropython/blob/master/ports/rp2/boards/manifest.py#L3.

And, compared to those 4 libraries, the `umodbus` you linked is huge. Just for rough estimation: `ds18x20` has 52 lines, and `umodbus` has multiple files with 400+ lines, so they don't really compare in impact.

**Comment by Omid888** [comment]
1) Right, ds18x20 is not a third-party library. But adding third party libraries is not a wrong thing to do (if all conditions are met).

2) I think the point about the "modbus library size compared to the flash size" makes sense. Therefor I thank you both for your information and close the issue.
