### ISSUE TITLE
stmhal: Allocate sd_handle and dma objects dynamically

### ISSUE THREAD

**Issue by dhylands** [micropython/micropython#1609]
Currently, there is an sd_handle object and a couple of dma objects.

If we allocate them dynamically instead of statically, then we can save about 260 bytes of RAM when not using an sdcard.

**Comment by dpgeorge** [comment]
The DMA state was moved from the BSS to the stack in c26516d40fc8bda4e083e3f8c222fccd358a957a, saving about 180 bytes.   And there is a TODO in the code about dynamically allocating `sd_handle`, so I'll close this issue.
