### ISSUE TITLE
wifi channel selection in access point mode is ignored

### ISSUE THREAD

**Issue by stanelie** [micropython/micropython#16165]
### Port, board and/or hardware

Waveshare ESP32-S3-ZERO

### MicroPython version

MicroPython v1.24.0 on 2024-10-25; Generic ESP32S3 module with ESP32S3

### Reproduction

Here is the code I use to test : 
```
import network

wlan = network.WLAN(network.AP_IF)
wlan.active(True)
wlan.config(ssid='potato',password='password',channel=6)

while True
    print(wlan.config('channel'))
```

### Expected behaviour

I expect this code to create an access point that will be on channel 6.

### Observed behaviour

The returned print command indicates the channel is "1", and a wifi scanner also confirms the access point is being broadcasted on channel 1.

### Code of Conduct

Yes, I agree

**Comment by mdaeron** [comment]
Same here with micropython v1.25.0-preview.24.g5dfbd4371.dirty on a Lolin S2 mini board. Any idea when this bug appeared?

**Comment by stanelie** [comment]
Hi @mdaeron. Does your comment imply that this used to work in the past?

**Comment by mdaeron** [comment]
> Hi @mdaeron. Does your comment imply that this used to work in the past?

Yes, definitely. But that was perhaps a couple of years ago (micropython 1.18 or 1.19). I'm currently testing to see which combination of micropython + esp-idf versions restores this functionality. Will report here if I get somewhere.

**Comment by dpgeorge** [comment]
Related to #8991
