### ISSUE TITLE
docs: MicroPython port to the ESP32

### ISSUE THREAD

**Issue by littlegreenbean33** [micropython/micropython#16195]
### Documentation URL

https://github.com/micropython/micropython/tree/master/ports/esp32

### Description

In section 
Setting up ESP-IDF and the build environment

Mentions that 

_The ESP-IDF changes quickly and MicroPython only supports certain versions. Currently MicroPython supports v5.0.4, v5.0.5, v5.1.2, v5.2.0, v5.2.2._

However
` git clone -b v5.2.0 --recursive https://github.com/espressif/esp-idf.git
Cloning into 'esp-idf'...
fatal: Remote branch v5.2.0 not found in upstream origin
`

Maybe a not supported version any more?

### Code of Conduct

Yes, I agree

**Comment by dpgeorge** [comment]
It's actually `v5.2` not `v5.2.0`.

Will be fixed by #16128.
