### ISSUE TITLE
Default args not handled for lambda's

### ISSUE THREAD

**Issue by pfalcon** [micropython/micropython#1628]
Python's bound-by-reference variables in closures are pretty broken from functional point of view. The way to get around that and proper functional (by value) binding is to use default args:

~~~~
# x & y will be bound by value
lambda z, x=x, y=y: f(x, y, z)
~~~~

And default args for lambdas is exactly what doesn't work in uPy:

~~~
>>> f = lambda x=y: x
# No error
>>> f = lambda x=1: x
>>> f()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: <lambda>() takes 1 positional arguments but 0 were given
~~~

**Comment by dpgeorge** [comment]
Implemented in 2c838942574a4970c922d1550f04e4b7b4d865a6.
