### ISSUE TITLE
Some header-source types not equal

### ISSUE THREAD

**Issue by pohmelie** [micropython/micropython#1647]
https://github.com/micropython/micropython/blob/master/py/asmx86.c#L308
https://github.com/micropython/micropython/blob/master/py/asmx86.h#L92

https://github.com/micropython/micropython/blob/master/py/mphal.h#L46
https://github.com/micropython/micropython/blob/master/unix/unix_mphal.c#L108

https://github.com/micropython/micropython/blob/master/py/mphal.h#L50
https://github.com/micropython/micropython/blob/master/unix/unix_mphal.c#L114

**Comment by dpgeorge** [comment]
Fixed in 7a5a4fe271d87c8331356673bf91416092f1edc2 and 0786716c5a9b352f24bb3e3386515ae3298942e7.
