### ISSUE TITLE
python compatibility IOError not defined

### ISSUE THREAD

**Issue by PeterKenyon** [micropython/micropython#1659]
import os
raise IOError

fails with NameError: name 'IOError' is not defined

**Comment by pfalcon** [comment]
Yes, that's by design - IOError is deprecated. If you need it, it's as simple as:

~~~
IOError = OSError
~~~

**Comment by PeterKenyon** [comment]
OK sorry for false alarm, no don't need it just trying to get existing working python 2.7 code running using micropython
