### ISSUE TITLE
unix: Passing in an invalid heap_size suffix is ignored

### ISSUE THREAD

**Issue by dhylands** [micropython/micropython#1671]
If you call the unix version of micropython with an invalid suffix then it segfaults.

```
527 >./micropython -X heapsize=1G
Segmentation fault (core dumped)
```

The fundamental problem is that that unrecognized option is ignored and it proceeds to allocate a 1 byte heap.

One potential solution was provided in #1656 but @pfalcon didn't like it and said he would simplify it, so I'm raising this issue so it doesn't get forgotten.

**Comment by dpgeorge** [comment]
This was fixed by 0e5e14fe7cd97fa83e822c1e105cf498dbb4d276
