### ISSUE TITLE
unix: passing in a negative heap size causes a segfault

### ISSUE THREAD

**Issue by dhylands** [micropython/micropython#1672]
If you call the unix version of micropython with a negative heapsize, then it segfaults:

```
532 >./micropython -X heapsize=-1M
Segmentation fault (core dumped)
```

The fundamental problem is that the heapsize parsing code considers negative heapsizes to be valid and will attempt to malloc a negative number of bytes for the heap.

**Comment by dpgeorge** [comment]
This was fixed by c1e0eb7afe2109a81f6e3ec28f9d01705010500c
