### ISSUE TITLE
unix: passing in too small of a heap cause micropython to report a cryptic error or segfault.

### ISSUE THREAD

**Issue by dhylands** [micropython/micropython#1673]
If you call micropython with a heap size which is of an insufficient size to perform the intiaiizations, then it either produces on of the two following errors:

```
534 >./micropython -X heapsize=400
FATAL: uncaught NLR 0x656610
```

or

```
539 >./micropython -X heapsize=15
Segmentation fault (core dumped)
```

The fundamental cause is that all of the initialization code is run outside of a try catch handler, so that the memory error which is thrown turns into a uncaught NLR error.

One potential solution was provided in #1656 but @pfalcon didn't like it and said he would simplify it, so I'm raising this issue so it doesn't get forgotten.

**Comment by dpgeorge** [comment]
A check for too small of a heap was added in c1e0eb7afe2109a81f6e3ec28f9d01705010500c
