### ISSUE TITLE
unix: make minimal

### ISSUE THREAD

**Issue by pohmelie** [micropython/micropython#1688]
Normal `make` is ok, but minimal:
``` bash
$ make minimal
...
CC ../py/objattrtuple.c
In file included from ../py/objtuple.h:29:0,
                 from ../py/objattrtuple.c:27:
../py/obj.h:440:57: error: unknown type name ‘uintptr_t’
     mp_uint_t (*ioctl)(mp_obj_t obj, mp_uint_t request, uintptr_t arg, int *errcode);
                                                         ^
make[1]: *** [build-minimal/py/objattrtuple.o] Error 1
make[1]: Leaving directory `'
make: *** [minimal] Error 2
```

**Comment by pfalcon** [comment]
@dpgeorge : So, here it comes again: normal unix build (and coverage) is ok, but minimal is suddenly broken.

**Comment by dpgeorge** [comment]
Ok.  So we should add it to the Travis build?

We need a proper solution to this.  We need to automatically build a lot more configurations (eg nan boxing) as well.  There are critical builds (unix, stmhal, cc3200) and the rest are less critical, but still important.  If we build the less-critical ones separately to the Travis run then people are not going to see errors until after the commit goes in, and then there will be some amount of "patching commits".

**Comment by dpgeorge** [comment]
But, regarding the issue of building minimal right now: I'd suggest putting #include <stdint.h> in py/misc.h.  stdint.h is C99 so we should have no problem.

**Comment by pfalcon** [comment]
@dpgeorge : Sounds good, I wanted to propose similar fix, but decided to ping you, because the main problem is that I don't understand how normal build can be ok, but minimal is broken. General fix works though ;-).

**Comment by pfalcon** [comment]
Fixed.

**Comment by dpgeorge** [comment]
> because the main problem is that I don't understand how normal build can be ok, but minimal is broken

It stumped me too, but I think it's due to this: https://github.com/micropython/micropython/blob/master/py/misc.h#L110 ; so stdint.h is included if unicode is enabled.

**Comment by pfalcon** [comment]
Indeed! ;-) Fixed.
