### ISSUE TITLE
Fate of unix "_os" module

### ISSUE THREAD

**Issue by pfalcon** [micropython/micropython#1702]
We by now have almost universal convention that builtin "subset" modules have "u" prefix, e.g. "uos". Apparently the only exception is that unix' module is still named "_os". I almost sure it should be renamed to uos. Any concerns?

**Comment by stinos** [comment]
On the contrary: better sooner than later I guess.

**Comment by dpgeorge** [comment]
Renaming to uos sounds good.

**Comment by pfalcon** [comment]
Renamed in 5eadb1d406fe2f3374a078592b669b75fc57e06d.
