### ISSUE TITLE
list slicing issue on reversed slicing

### ISSUE THREAD

**Issue by mbuesch** [micropython/micropython#1711]
Reversed list slicing doesn't work correctly, if indices are specified.

Micropython:

```
>>> [1,2,3,4,5][:0:-1]
[]
>>> [1,2,3,4,5][:1:-1]
[1]
>>> [1,2,3,4,5][:2:-1]
[2, 1]

>>> [1,2,3,4,5][0::-1]
[5, 4, 3, 2, 1]
>>> [1,2,3,4,5][1::-1]
[5, 4, 3, 2]
>>> [1,2,3,4,5][2::-1]
[5, 4, 3]
```

CPython 3.4:

```
>>> [1,2,3,4,5][:0:-1]
[5, 4, 3, 2]
>>> [1,2,3,4,5][:1:-1]                                                                                        
[5, 4, 3]
>>> [1,2,3,4,5][:2:-1]                                                                                        
[5, 4]

>>> [1,2,3,4,5][0::-1]
[1]
>>> [1,2,3,4,5][1::-1]
[2, 1]
>>> [1,2,3,4,5][2::-1]
[3, 2, 1]
```

**Comment by pfalcon** [comment]
@mbuesch: As you can see, unlike other issues you reported, hat didn't catch immediate attention from other developers, so please take an invitation/encouragement to look into this yourself, if you're interested. This should be right good task for initial acquaintance with codebase. Actually, you may start with looking at #1481.

**Comment by pfalcon** [comment]
https://github.com/micropython/micropython/issues/2577 claims to have fixed these issues.
