### ISSUE TITLE
esp8266: Lockup when using proprietary vendor socket API 

### ISSUE THREAD

**Issue by lamazavr** [micropython/micropython#1734]
Hi, I am trying to implement NTP request via esp sockets.
So, I connect to Wifi and do:

>>> s = esp.socket()
>>> def socket_printer(socket, data):
...     print(data)
>>> s.onrecv(socket_printer)
>>> NTP_QUERY = b'\x1b' + 47 * '\0'
>>> s.connect(('88.147.254.235', 123))
>>> s.send(NTP_QUERY)
48
>>> 

After this I can`t type any symbol. 
Maybe I do something wrong?

**Comment by dpgeorge** [comment]
> After this I can`t type any symbol.
> Maybe I do something wrong?

You might need to wait for `s.connect` to suceed before doing `s.send`.  You can set a callback using `s.onconnect`.

This callback event model is not very fun to use.

**Comment by dpgeorge** [comment]
This should be fixed when #1806 is closed.

**Comment by pfalcon** [comment]
esp8266 switched to lwIP sockets.
