### ISSUE TITLE
uctypes: segfaults with an array of structs?

### ISSUE THREAD

**Issue by dhylands** [micropython/micropython#1761]
I ran into this just before I went to bed, so I haven't had a chance to look into it yet. I created the following simplfied file:

``` python
import uctypes

desc = {
    'f1': (uctypes.ARRAY | 0, 8, {
        'b1': uctypes.UINT8 | 0,
        'b2': uctypes.UINT8 | 1,
    })
}

buf = bytearray(b'0123456789ABCDEF')

S = uctypes.struct(uctypes.addressof(buf), desc, uctypes.LITTLE_ENDIAN)

for i in range(4):
    print('f1[%d].b1 =' % i, hex(S.f1[i].b1));
    print('f1[%d].b2 =' % i, hex(S.f1[i].b2));
```

and it segfaults using unix micropython.

If I change LITTLE_ENDIAN to NATIVE then it seems to work fine.

**Comment by dhylands** [comment]
Although even with NATIVE, I get a segfault if I use bitfields:
```python
import uctypes

desc = {
    'f2': (uctypes.ARRAY | 4, 8, {
        'b1': uctypes.UINT8 | 0 | 4 << uctypes.BF_POS | 4 << uctypes.BF_LEN,
        'b2': uctypes.UINT8 | 0 | 0 << uctypes.BF_POS | 4 << uctypes.BF_LEN,
    })
}

buf = bytearray(b'0123456789ABCDEF')

S = uctypes.struct(uctypes.addressof(buf), desc, uctypes.NATIVE)

for i in range(4):
    print('f2[%d].b1 =' % i, hex(S.f2[i].b1));
    print('f2[%d].b2 =' % i, hex(S.f2[i].b2));
```

**Comment by pfalcon** [comment]
Well, running it thru debugger should show what's wrong.

**Comment by pfalcon** [comment]
Note that https://github.com/micropython/micropython/pull/1754 was merged in the meantime, so should be retested.

**Comment by dhylands** [comment]
#1754 had no change in behaviour.
#1762 fixes one of the 2 issues that I was running into.

The second issue was at least partly user error.

I used UINT8 instead of BFUINT8. The segfault was caused by trying use the extremely large offset which goes way beyond the end of the provided buffer.

I don't know if trying to access beyond the end of the buffer should raise an error in uPy or not. If it's supposed to catch it, then this issue can remain open (albeit at a low priority).

If having a segfault due to a typo is condiered fine, then we can close this.

**Comment by dpgeorge** [comment]
`uctypes` is an advanced module and you can easily segfault the hardware if you pass in bad values.  I don't think it's reasonable for this module to do sanity checking on all input because there are some invalid cases it can never catch.
