### ISSUE TITLE
Printing of doubles with exponent greater than 99 fails

### ISSUE THREAD

**Issue by dpgeorge** [micropython/micropython#1772]
The exponent of a double doesn't print properly when above 99, eg:
```python
>>> 2.**500
3.273390607896142e+?0
```

**Comment by pfalcon** [comment]
Yes, there's issue that only 2 digits of exponent is handled, overflow from 2nd digit isn't handled.

**Comment by dpgeorge** [comment]
Fixed.  See link above.
