### ISSUE TITLE
STM32F439 "bare-bones" Port

### ISSUE THREAD

**Issue by ryannathans** [micropython/micropython#1793]
I've made considerable changes to the STM32F429-DISCO to support the STM32F439, which is identical to the 429 except it has hardware accelerated hashing/crypto. My changes are for the LQFP100 pin STM32F439, the STM32F429-DISCO is based on the LQFP144.

The STM32F439 is mainly different to the STM32F405 in that:
* 439 can have 2MB flash (divided in to two banks allowing read while write)
* 64KB more RAM
* Hardware accelerated crypto/hashing
* Higher core clock speed
* More peripherals
* Smallest chip is LQFP100 instead of LQFP64

As the DISCO is significantly different to the "bare" 429/439 I think these changes should eventually be merged.

My modifications so far compared to STM32F429-DISCO:
* Changed linker to support correct memory ranges (DISCO has 8MB SDRAM)
* Added CCM to linker
* Increased heap size
* Increased core clock to 192MHz (12MHz overclock to support USB, instead of 12MHz underclock seen in DISCO)
* Added some (not all) missing pins/peripherals to pins_af, removed a few invalid entries
* Edited storage.c to use significantly more flash for the filesystem

Items on the TODO:
* Write crypto and hashing interface #1789

**Comment by david-jimenez** [comment]
@ryannathans Looks like the linker file that you modified this from has been changed from the default one. Your declaration of FLASH_TEXT doesn't match that of the comment accompanying it, you're grabbing an additional 32K of the next sector alongside it

**Comment by ryannathans** [comment]
@david-jimenez will fix, must have been a typo in the DISCO linker

**Comment by ryannathans** [comment]
#1857
