### ISSUE TITLE
docs: pyboard online docs missing some content

### ISSUE THREAD

**Issue by peterhinch** [micropython/micropython#1809]
If I build the docs locally the outcome is correct. However the online docs omit some recently added detail for example the ``ADCAll`` documentation in library/pyb.ADC.rst [here](http://docs.micropython.org/en/latest/library/pyb.ADC.html) and the line regarding the firmware build in library/network.rst [here](http://docs.micropython.org/en/latest/library/network.html)

**Comment by pfalcon** [comment]
@peterhinch : ReadTheDocs doesn't build docs automatically. @dpgeorge build new version after release. But you should be able to trigger build of "latest" docs yourself (I can). On http://docs.micropython.org/ , lick ReadTheDocs at bottom right, in sliding menu select "Build", should be clear from there. I rebuild docs, and see both additions (shift+reload in browser if in doubt!)

Thanks for docs contributions!

**Comment by peterhinch** [comment]
I appreciate there's a delay before online docs are updated. In this instance there has been a regression. The online docs were updated - now some (not all) of the changes are lost. Work has been done in the interim to better support multiple boards and I suspect an error here has resulted in this knock-on effect.

**Comment by pfalcon** [comment]
@peterhinch : I'm not sure what you mean, can you elaborate which changes are lost and what knock-on effect do you mean?

**Comment by peterhinch** [comment]
This problem has either been fixed, or has gone away: the pages now display correctly here. Possibly some local internet issue?
