### ISSUE TITLE
Assertion failed when trying to access non-exsiting attributes

### ISSUE THREAD

**Issue by stinos** [micropython/micropython#1812]
Instead of using hasattr I somewhere ended up with code similar to

```
for objName, objId in locals().items():
  try:
    myAttr = objId.SomeAttribute
    # use myAttr 
  except:
    continue
````

This results in

```micropython: ../py/vm.c:1071: mp_execute_bytecode: Assertion `exc_sp == exc_stack - 1' failed.
Aborted (core dumped)```

**Comment by pfalcon** [comment]
I'd suspect that continue in except, all wrapped in for may be an issue here. Can you try to separate that from locals() and AttributeError?

**Comment by stinos** [comment]
Indeed changing ```continue``` to ```pass``` gets rid of the assert. Using a 'normal' dictionary instead of locals doesn't change anything, nor does catching AttributeError. So for reference, this works as expected:
```
someDict = { 'a': 0 }
for _, objId in someDict.items():
  try:
    myAttr = objId.someAttr
  except AttributeError:
    pass
```

but this has the assertion failing:
```
someDict = { 'a': 0 }
for _, objId in someDict.items():
  try:
    myAttr = objId.someAttr
  except AttributeError:
    continue
```

**Comment by dpgeorge** [comment]
Fixed, see above.  @stinos please verify and close this issue :)

**Comment by stinos** [comment]
Verified, thanks!
