### ISSUE TITLE
I2C3_SDA is initialized to wrong AF on PYBLITEV10

### ISSUE THREAD

**Issue by dhylands** [micropython/micropython#1822]
I wrote up an analysis over here: http://forum.micropython.org/viewtopic.php?f=6&t=1363

I don't have a pyblite board, so I wouldn't be able to test this.

I can see 2 potential solutions:

1 - Add a new config option to allow the AF to be specified
2 - call pin_find_af(pin, AF_FN_I2C, 3) and use the af index in the af object returned.

**Comment by dhylands** [comment]
I see the Nucleo 401 board has the same issue, and I have one of those, so I can put together a patch and test it.

**Comment by dpgeorge** [comment]
Thanks @dhylands.  Although option 2 is a runtime/dynamic solution, I think it's neater and more robust.

**Comment by dhylands** [comment]
Fixed by #1833
