### ISSUE TITLE
GPIO_ hal functions seem to be badly named

### ISSUE THREAD

**Issue by dhylands** [micropython/micropython#1827]
I just noticed this, so I thought I'd throw it out for comment.

In mphalport.h (I'm looking at the stmhal version), it has the functions GPIO_read_pin and GPIO_read_output_pin which both take a port and a pin number.

However, GPIO_set_pin and GPIO_clear_pin take a port and a pin_mask (i.e. 1 << pin number)

I'd like to propose one of 2 things:
1 - Rename GPIO_set_pin and GPIO_clear_pin to be GPIO_set_pin_mask and GPIO_clear_pin_mask
2 - Make GPIO_set_pin and GPIO_clear_pin take a pin number rather than a pin mask.

**Comment by dpgeorge** [comment]
This has now been cleaned up (at least for stmhal) and the functions/macros are all named mp_hal_pin_XXX and take a pin object instead of port and pin number/mask.
