### ISSUE TITLE
GitHub Repository base could need a link to the MicroPython project

### ISSUE THREAD

**Issue by kfricke** [micropython/micropython#1834]
While navigating the different MicroPython pages I did stumble upon the fact that the main page of the GitHub MicroPython repository could need a link to the [MicroPython project page](http://www.micropython.org). Not only for convenience, but to tie these pages together and to make it easier for others to associate these two websites.

**Comment by dpgeorge** [comment]
Yes, good point!

**Comment by dpgeorge** [comment]
Addressed by 53fec1ef482b9e914565531885ace46f5b9bba92.
