### ISSUE TITLE
stmhal: stm.mem32 won't accept long in data

### ISSUE THREAD

**Issue by peterhinch** [micropython/micropython#1835]
I was under the impression this was fixed in #1649 - or am I missing something?
```python
>>> stm.mem32[stm.RTC_ALRMAR] = 0x80000000
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: overflow converting long int to machine word
```
The issue is the data not the address: assigning 0 works fine.

**Comment by dpgeorge** [comment]
Since that fix modstm.c functionality is now replaced by the generic one in extmod/machine_mem.c  So that latter file needs fixing.

**Comment by dpgeorge** [comment]
Fixed, see link above.
