### ISSUE TITLE
should there be a "shutdown.py"

### ISSUE THREAD

**Issue by hoihu** [micropython/micropython#1848]
or similar? To shutdown/close initalized peripherals/connections gracefully after REPL ends?

There was a discussion in #733 with the temporary outcome that the timer callbacks are deinit. However it seems that also #1796 is affected by this (USB VCP handling of CTRLC). 

Anyway, just thought a "shutdown.py" might be a solution for that. If present it would be executed if CTRLD was pressed. Would be kind of an analogy to "boot.py"...

**Comment by hoihu** [comment]
based on the feedback probably not ;)

I'm closing this now.

**Comment by dpgeorge** [comment]
The REPL is really only used for debugging and prototyping, so providing a shutdown mechanism isn't really necessary.  Shutdown should be handled by your "main.py" when it's about to finish/reset.  "boot.py" can also handle shutdown by working out what the reset cause was.

**Comment by hoihu** [comment]
I use CTRLDs to import the changes that i've uploaded to the board... Correct me but  main.py has no means to detect CTRLD (in Python), so it is not possible to handle that there? 

boot.py seems like the better option, but is there a way to evaluate the reset cause (e.g. ctrld?).

**Comment by hoihu** [comment]
since the machine module supports now the read out of the reset cause, I think this PR can be closed.

To summarize:
- Repl is not intended to handle shutdown mechanism. 
- Use main.py for shutdown procedures or read out reset cause at startup to init/deinit peripherals
