### ISSUE TITLE
Question about Timer at ESP8266

### ISSUE THREAD

**Issue by iitzex** [micropython/micropython#1886]
```python
from time import sleep_us, sleep_ms
from machine import Timer

def count():
    for i in range(5):
        print(i)
        sleep_ms(500)

tim = Timer(0)
tim.init(period=5000, mode=Timer.PERIODIC, callback=lambda t:count())
```
Why system got reset if I using sleep or delay?

```html
• Using non-OS SDK which is single-threaded, the CPU should not take long to execute
tasks:
- If a task occupies the CPU too long, ESP8266 can't feed the watchdog, it will cause a watchdog reset;
- If interrupt is disabled, CPU can only be occupied in us range and the time should not be more than 10 us; 
if interrupt is not disabled, it is suggested that CPU should not be occupied more than 500 ms.
• We suggest using a timer to check periodically, if users need to call os_delay_us or function while, or function for in timer callback, 
please do not occupy CPU more than 15 ms.
```
If I need delay, does it have any method avoid reseting?

**Comment by dhylands** [comment]
Set the timer to run every 500 msec, and have it count to 10, but only print something if the counter is less than 5.

Here's an example for the pyboard which does something similar:
https://github.com/dhylands/upy-examples/blob/master/heartbeat_irq.py

**Comment by iitzex** [comment]
Thank you for the example, and I try to know more.
In just normal case, what will cause wdt reset?
15ms or 500ms

**Comment by dhylands** [comment]
I'm not sure. Sleeping (for any amount of time) from within an ISR is generally a bad idea because often times the sleep function require other ISR functions which may be disabled because you're within an ISR.

**Comment by iitzex** [comment]
I try to put some delay in the blinky example, but it seems cause wdt reset. I want to know what interval of delay will make it reset. Some examples suggest using timer. That's why I write the code above to figure it out, but I'm still not know detail reason of wdt reset. Thanks for the suggestion.
