### ISSUE TITLE
Wxtra keyword arguments for I2C init in quickstart

### ISSUE THREAD

**Issue by deshipu** [micropython/micropython#1887]
I just received the mp-esp8266-firmware-v01.bin firmware via e-mail, and started to test it. When trying the I²C example from http://micropython.org/resources/docs/en/latest/esp8266/esp8266/quickref.html I got this error:

```
>>> from machine import Pin, I2C
>>> i2c = I2C(frequency=100000, scl=Pin(5), sda=Pin(4))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: extra keyword arguments given
```

**Comment by deshipu** [comment]
Skipping the "frequency" argument makes it work.

**Comment by dpgeorge** [comment]
It should be spelled "freq"; now fixed in the docs.

**Comment by deshipu** [comment]
Thank you!
