### ISSUE TITLE
Standalone binary?

### ISSUE THREAD

**Issue by VanushVaswani** [micropython/micropython#1892]
Is it possible to create a standalone executable of a Python script using MicroPython as a "backend", similar to the Nuitka project?

**Comment by dpgeorge** [comment]
No, it's not currently possible to do this, although we are very close.  Please continue the discussion in #1295.

**Comment by VanushVaswani** [comment]
Thanks. 

I actually think frozen bytecode in #1811 will achieve what I'm after. Since my platform has no REPL or file system, is there a way to run the static bytecode, i.e `run_bytecode`?

**Comment by dpgeorge** [comment]
> Since my platform has no REPL or file system, is there a way to run the static bytecode, i.e run_bytecode?

Yes, `pyexec_frozen_module()`.  That PR comes with an example that works on pyboard.
