### ISSUE TITLE
closures: confusing error message on incorrect argument count

### ISSUE THREAD

**Issue by peterhinch** [micropython/micropython#1893]
Consider this function

``` python
def foo():
    x, y, z = 0, 0, 0
    def bar(rats):
        print(x, y, z, rats)
    return bar
```

With the following (incorrect) usage at the REPL

```
>>> a = foo()
>>> a()
```

cPython issues:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: bar() missing 1 required positional argument: 'rats'
```

MicroPython seems to include nonlocal variables in the argument count:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: function takes 4 positional arguments but 3 were given
```

**Comment by dpgeorge** [comment]
Yes, it is confusing.  But hard to fix without adding a lot of extra code (the part of the code that does the arg checking doesn't know that the function is a closure, it thinks it's a normal function with extra args).
