### ISSUE TITLE
Byte array filled with garbage when extending unconventionally

### ISSUE THREAD

**Issue by ryannathans** [micropython/micropython#1898]
'''
ocean = bytearray(1000)
ocean[:-1] = b'\x00' * 10000
'''

Fills ocean with junk, although length is correct. 

Perhaps it's extending memory but not setting it to zero?

Sometimes it appears with an error saying byte code not implemented, usually it does not. If it appears, the printing of this error does not stop or change anything.

**Comment by dpgeorge** [comment]
Should be fixed by commit referenced above.  Can you please verify?

**Comment by ryannathans** [comment]
Fixed, good work damien
