### ISSUE TITLE
uzlib: support streaming

### ISSUE THREAD

**Issue by prusnak** [micropython/micropython#1910]
It would be nice if uzlib module supported streamed decompression. 

**Usecase:** Suppose I have a gzipped image file (PPM.GZ) stored on Flash/SD card. This file can be a few kilobytes big and I want to decompress its contents and dump into the LCD driver. Currently I cannot do this, because I have to decompress the whole file into main memory (using `zlib.decompress`), which is bad, because this data are often bigger than the whole RAM.

Or am I missing something?

I guess ideally there could be a function that gets file object (I think `read(size)` method could be enough) as a parameter and returns another file object.

**Comment by pfalcon** [comment]
If this is a uzlib issue, why is it submitted against micropython? And yes, this is the main technical challenge towards implementing "upip on esp8266" stretch goal.

**Comment by prusnak** [comment]
It is a missing feature of micropython. I don't know if uzlib supports this functionality and it is not exported via the module (maybe because it wants to copy API of zlib module from Python3) or it does not support it at all. That's why I am raising the point here.

**Comment by peterhinch** [comment]
zlib does support it via zlib.decompressobj(wbits=15[, zdict]) see [Python docs](https://docs.python.org/3.5/library/zlib.html). The means of support is specifically designed for streams. This differs from the idea suggested by @prusnak - I have doubts about the feasibility of returning another file object. Random access to such an object would present challenges.

**Comment by prusnak** [comment]
Yes, decompressobj is exactly what I meant.
 
-- 
Best Regards / S pozdravom,
 
Pavol Rusnak <stick@gk2.sk>
 
 
On Fri, Mar 18, 2016, at 06:31 AM, Peter Hinch wrote:
> zlib does support it via zlib.decompressobj(wbits=15[, zdict]) see
> Python docs[1]. The means of support is specifically designed for
> streams. This differs from the idea suggested by @prusnak[2] - I have
> doubts about the feasibility of returning another file object. Random
> access to such an object would present challenges.
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub[3]
>
 

Links:

  1. https://docs.python.org/3.5/library/zlib.html
  2. https://github.com/prusnak
  3. https://github.com/micropython/micropython/issues/1910#issuecomment-198215259

**Comment by prusnak** [comment]
Moved to https://github.com/pfalcon/uzlib/issues/2
