### ISSUE TITLE
make: *** [build/genhdr/qstrdefs.generated.h] Error 1

### ISSUE THREAD

**Issue by bisguzar** [micropython/micropython#1911]
when i did make in micropython/esp8266 folder i see an error.

`bisguzar@ubuntu-1gb-ams3-01:~/micropython/esp8266$ make

Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
make: xtensa-lx106-elf-gcc: Command not found

GEN build/genhdr/qstrdefs.generated.h
/bin/sh: 1: xtensa-lx106-elf-gcc: not found
ERROR: Empty preprocessor output - check for errors above
make: *** [build/genhdr/qstrdefs.generated.h] Error 1
make: *** Deleting file build/genhdr/qstrdefs.generated.h
`

**Comment by dpgeorge** [comment]
You need to install esp-open-sdk and make sure the xtensa-gcc binary is in your path.  Please use https://forum.micropython.org for these kinds of problems (search there first and you'll likely find answers to your questions).
