### ISSUE TITLE
ExtInt as decorators

### ISSUE THREAD

**Issue by nasryn** [micropython/micropython#1930]
Perhaps make a decorator for external interrupts instead of or in addition to callbacks? Something like:

    def external_interrupt(func):
        def wrap(*args, **kwargs):
            ext = ExtInt(*args, **kwargs, func)
            return ext
    return func

I think it would be pretty useful due to the nature of interrupts in general.

**Comment by pfalcon** [comment]
You're welcome to make such a module, advertize it to MicroPython community via forum (http://forum.micropython.org/) and maintain it. (MicroPython works in the same way as Python does - majority of modules aren't written by Python author(s), but by the community).
