### ISSUE TITLE
Should script main.py be named boot.py ?

### ISSUE THREAD

**Issue by krystian-wojtas** [micropython/micropython#1933]
There is a file micropython/esp8266/scripts/main.py. It's purpose is to load this script on each boot as described in one tutorial https://learn.adafruit.com/building-and-running-micropython-on-the-esp8266/micropython-usage

But it does not work as expected. If it is renamed 'boot.py', then it works fine.

Also after renaming, one warning message from serial port is gone. Take a look on the first line of output after reset
```
          b�xbc`����could not find module 'boot'

>>> 
MicroPython v1.6-282-g91031a7-dirty on 2016-03-25; ESP module with ESP8266
Type "help()" for more information.
>>> #4 ets_task(401004fc, 2, 3fff9048, 16)
```

**Comment by pfalcon** [comment]
See #1955.
