### ISSUE TITLE
esp8266 network run wlan.connect  esp8266 restart !

### ISSUE THREAD

**Issue by skylin008** [micropython/micropython#1942]
The firmware version for:MicroPython v1.6-312-gb4070ee-dirty on 2016-03-29; ESP module with ESP8266

when I run follow code,esp8266-12f  restart.
import network
wlan = network.WLAN(network.STA_IF)
wlan.active(True)
wlan.isconnected()
False
wlan.connect('essid', 'password')   #essid and password from router distribution
the esp8266-12f restart every time.
How to fix this issue?Tks!

**Comment by pfalcon** [comment]
Ack, we'll be looking what went wrong.

**Comment by pfalcon** [comment]
Ok, this was worked around in master. We'll approach fixing it better soon.
