### ISSUE TITLE
esp8266 main.py does not run on boot

### ISSUE THREAD

**Issue by ceremcem** [micropython/micropython#1964]
Hi, 

I followed [this](https://micropython.org/doc/tut-script) documentation to load a script that I want it to be run on power up of esp8266 but there is no success yet. 

Is there anyway to debug this issue (such as dumping main.py contents from REPL console)?

**Comment by hoh** [comment]
The email linking to ESP8266 firmware v02 tells us to use `boot.py`, have you tried using that filename ?
> - Filesystem support is now enabled by default (and there is no way to disable it!).  Your ESP8266 device must have at least 1MB of flash for this to work, so please don't use the firmware if it doesn't.  If you create a file "boot.py" in the filesystem then this "boot.py" file will be executed on start-up.

**Comment by hoh** [comment]
Related: https://github.com/micropython/micropython/pull/1936

**Comment by ceremcem** [comment]
Because of [this](https://github.com/micropython/micropython/issues/1946) issue, I have to use the latest checkout as of writing.

**Comment by dpgeorge** [comment]
The documentation you link to is for the pyboard, not the esp8266.

To run boot.py you need to have the filesystem mounted.  At the REPL, if you do import os, then os.listdir() it should list boot.py and/or main.py.

**Comment by pfalcon** [comment]
https://github.com/micropython/micropython/commit/6e87aeb8419e8c5fe009577a3b1bb18254a35b79 implements new bootstrapping sequence.
