### ISSUE TITLE
Build failure - extmod/modure.c

### ISSUE THREAD

**Issue by tomsparks** [micropython/micropython#1972]
I'm building on FreeBSD-11 with GCC 4.8.5 and gnu make (gmake).

CC ../py/../extmod/modure.c
../py/../extmod/modure.c:95:17: error: conflicting types for 're_exec'
 STATIC mp_obj_t re_exec(bool is_anchored, uint n_args, const mp_obj_t *args) {
                 ^
In file included from ./mpconfigport.h:235:0,
                 from ../py/mpconfig.h:45,
                 from ../py/nlr.h:36,
                 from ../py/../extmod/modure.c:31:
/usr/local/lib/gcc48/gcc/x86_64-portbld-freebsd11.0/4.8.5/include-fixed/unistd.h:557:6: note: previous declaration of 're_exec' was here
 int  re_exec(const char *);
      ^
../py/mkrules.mk:47: recipe for target 'build/py/../extmod/modure.o' failed
gmake: *** [build/py/../extmod/modure.o] Error 1

Not sure what the deal is with this.

**Comment by vfl68** [comment]
For which hardware are you trying to build ?

**Comment by tomsparks** [comment]
The "unix" version, I was going to go for the ESP8266 version afterwards.

**Comment by vfl68** [comment]
As I can read here http://www.unix.com/man-page/freebsd/3/re_exec/
the function re_exec exist in the freebsd unistd.h file ... and the same function is redefined in micropython. This function isn't defined in the linux unistd.h file.

re_exec doesn't seem to be used outside of modure.c, try to rename every re_exec in the file to something like re_exec_mpy and try to build

**Comment by tomsparks** [comment]
ok, I did that, tested, works. I'll submit a pull request.

**Comment by pfalcon** [comment]
Fixed in master. @tomsparks : A small hint: you could add your commit email to github account (invisible to others) to better associate ones to another.
