### ISSUE TITLE
ESP8266/  Build stopped working  on OS X ,  issues with liblwip

### ISSUE THREAD

**Issue by tritip** [micropython/micropython#1974]
Built from scratch, made clean, compiled all source, tried to build by  hand, started to patch the code.  There 's some commented out business in the Makefile  pertaining to using the local lwip library over the sdk version;  perhaps this has not been fully resolved yet. 
** Was able to build in Linux under Vagrant **

**Comment by dpgeorge** [comment]
Did you do `git submodule update --init`?  Please provide the specific error message from the non-working compile.

**Comment by tritip** [comment]
Yes, did the git submodule update --init.   Compile bombed out on the LINK build/firmware.elf  numerous undefined references.  Here is a link to a pastebin with the transcript:   http://pastebin.com/DdKpN6MW

Thanks Damien!

**Comment by yjroot** [comment]
I had the same problem as you and I got it fixed.
Try to checkout this for your [esp-open-sdk](https://github.com/pfalcon/esp-open-sdk) submodule and rebuild it.
https://github.com/yjroot/esp-open-lwip/commit/e424e026c901d91bce054f908feec5041f30f0d4

**Comment by pfalcon** [comment]
This should be fixed. See also http://forum.micropython.org/viewtopic.php?f=16&t=1689 for comments on build tips and tricks.
