### ISSUE TITLE
Move to next version, v1.7?

### ISSUE THREAD

**Issue by dpgeorge** [micropython/micropython#1979]
It's been over 2 months since the last version, v1.6 (31st Jan 2016) with 388 commits, so time for the next one!

There have been a lot of changes, most notably to the esp8266 port.  I suggest going straight to v1.7 for this.

Any objections?  Anything to merge before tagging v1.7?

**Comment by pfalcon** [comment]
+1 for 1.7

**Comment by inaugurator** [comment]
Sounds good!

**Comment by dpgeorge** [comment]
v1.7 will be tagged imminently.  No pushing until it's done!

**Comment by dpgeorge** [comment]
Last minute tests show PYBv1.0 failing on basics/int_big_{div,mul}.py.  Need to investigate....

**Comment by dpgeorge** [comment]
Failing int_big_div/mul are very difficult to reproduce.  Seems to be related to a USB serial problem because there are seven 0's that are not printed in one place but are printed in another.  Will probably defer fix to a later date.

**Comment by pfalcon** [comment]
So, is fix for nt_big_div/mul is deferred or 1.7 deferred? If it can't be tagged immediately, I propose to postpone it until esp8266 port release.

**Comment by dpgeorge** [comment]
v1.7 has been tagged at 9b0a150bd69f9c62a14045b4a2ecfaaf7523f542.
