### ISSUE TITLE
missing definition in stmhal/i2c.h for I2C3

### ISSUE THREAD

**Issue by rolandvs** [micropython/micropython#1980]
I have added `extern I2C_HandleTypeDef I2CHandle3;` to the `i2c.h` as this is missing (also in older versions). (I have put it in my fork of mpy)

**Comment by dpgeorge** [comment]
Why do you need this definition to be exposed in the header?

**Comment by rolandvs** [comment]
Currently I use all three possible I2C ports. I'm integrating part of the code in mpy itself for various reasons. The external for I2C1 is needed by mpy - accel.c and for that matter the reference to I2C2 could be omitted. So for consistency I would prefer to have all three mentioned. :-)

**Comment by dpgeorge** [comment]
Fixed, see 1e388079f9ff7e24adb4592b3c81aed314f86827.
