### ISSUE TITLE
make error in Unix

### ISSUE THREAD

**Issue by 1983FFly** [micropython/micropython#1991]
$ cd unix
$ make

modffi.c:32:17: fatal error: ffi.h: No such file or directory
 #include <ffi.h>
                 ^
compilation terminated.
make: *** [build/modffi.o] Error 1

**Comment by dhylands** [comment]
Either install libffi-dev or build with MICROPY_PY_FFI=0 (on the make command line) to disable ffi support.

**Comment by 1983FFly** [comment]
Thank you！It works！
