### ISSUE TITLE
pyb.CAN reinitialises when fetching object

### ISSUE THREAD

**Issue by ryannathans** [micropython/micropython#2001]
When working with SPI or UART the following applies - note how the peripheral remains initialized when I fetch that object later.

```
>>> pyb.SPI(2, baudrate=100000, mode=pyb.SPI.MASTER)
SPI(2, SPI.MASTER, baudrate=187500, prescaler=256, polarity=1, phase=0, bits=8)
>>> pyb.SPI(2)
SPI(2, SPI.MASTER, baudrate=187500, prescaler=256, polarity=1, phase=0, bits=8)
```

When working with CAN, the behavior is different. Fetching the object with the port reinitialises the object with no parameters. See below

```
>>> pyb.CAN(2, mode=pyb.CAN.NORMAL)
CAN(2, CAN.NORMAL, extframe=False)
>>> pyb.CAN(2)
CAN(2)
```

**Comment by dpgeorge** [comment]
Fixed by c4587e24262c943adc75ae12b68bbeafe5b67642.
