### ISSUE TITLE
Make deploy fails

### ISSUE THREAD

**Issue by HenrikSolver** [micropython/micropython#2003]
Today I updated to the latest version from master. And now make deploy in stmhal fails with:

Traceback (most recent call last):
  File "../tools/pydfu.py", line 20, in <module>
    import usb.core
ImportError: No module named usb.core
Makefile:309: recipe for target 'deploy' failed

Running ../tools/pydfu.py -u build-PYBV10/firmware.dfu works fine

Since flashing with pydfu worked for me a few days ago I went back to commit 2c72ae5c29143af7cd10e1458bfcbeafaf99b98d
And make deploy works fine again.

**Comment by dpgeorge** [comment]
Fixed by 109990fc322ebf102b6752a47d908cc82a4d3ff7.
