### ISSUE TITLE
BSSIDs scrambled on scan()

### ISSUE THREAD

**Issue by capaulson** [micropython/micropython#2009]
I've noticed that the scan call in network on the ESP8266 returns scrambled hex strings, for example: 
b'\x23\x17{\x332H'. Any ideas on cause, or on a solution?

**Comment by dpgeorge** [comment]
That output seems correct.  It's a raw bytes object.  To get a human-readable form use binascii.hexlify:
```
>>> import ubinascii
>>> ubinascii.hexlify(b'\x23\x17{\x332H', ':')
b'23:17:7b:33:32:48'
```

**Comment by capaulson** [comment]
Ah got it. Thanks.

**Comment by pfalcon** [comment]
Now explicitly mentioned in docs: https://github.com/micropython/micropython/commit/650df97c063a7af47c2d70a2b0c1fe7da3da5a0e
