### ISSUE TITLE
[esp8266] Socket.read example doesnt work

### ISSUE THREAD

**Issue by dmarkey** [micropython/micropython#2025]
>>> s = socket.socket()
>>> s.connect(socket.getaddrinfo('www.micropython.org', 80)[0][4])
>>> s.read(128)
b''
>>> socket.getaddrinfo('www.micropython.org', 80)
[(2, 1, 0, '', ('176.58.119.26', 80))]
>>>

**Comment by dpgeorge** [comment]
This is actually working: there will be no data to read if you don't send a request (eg HTTP GET) first.

Where did you get this example?

**Comment by dmarkey** [comment]
Sorry this was problem in chair not in computer. Closing out. It works fine when sending the actual HTTP GET request first :)
