### ISSUE TITLE
Default password of AP

### ISSUE THREAD

**Issue by Jugulaire** [micropython/micropython#2027]
I got a fresh build of micropython on my nodeMCU devboard. 
But it's impossible to connect to the AP called "MicroPython-xxxxx" because i don't have any password.
I don't have set any password and no default password was indicated. 

Can anybody help me ?

**Comment by dpgeorge** [comment]
Please see here: http://docs.micropython.org/en/latest/esp8266/esp8266/tutorial/intro.html#wifi

**Comment by pfalcon** [comment]
@dpgeorge : Good that you have it covered. Btw, esptool lately available form PyPI (via pip), maybe add that to tutorial too.

**Comment by dpgeorge** [comment]
> Btw, esptool lately available form PyPI (via pip), maybe add that to tutorial too.

Done.

**Comment by urayfajar** [comment]
pass : micropythoN
