### ISSUE TITLE
REPL input from code

### ISSUE THREAD

**Issue by Ivoah** [micropython/micropython#2037]
Is there a way to send a string to the REPL through code? Like nodemcu's [`node.input()`](http://nodemcu.readthedocs.io/en/dev/en/modules/node/#nodeinput) function? It would be useful for making a REPL available over telnet or something.

**Comment by dhylands** [comment]
If you running on pyboard A and you want to take some python text and execute it on pyboard A you can use eval, which is essentially what the REPL does.

**Comment by Ivoah** [comment]
I'm thinking of using it on the ESP8266. Also, eval doesn't support multi-line expressions, like the REPL does. `node.input()` does support multi-line expressions
> Submits a string to the Lua interpreter. Similar to pcall(loadstring(str)), but without the single-line limitation.

**Comment by dhylands** [comment]
Perhaps exec then? Putting this into a file and running it (with the unix version):
```
exec("""def foo():
    for i in range(5):
        print(i)
foo()
""")
```
produces the expected output of:
```
0
1
2
3
4
```

**Comment by Ivoah** [comment]
That still requires all of the input to be in one string. I believe with `node.input()` it is possible to do something like this:
```lua
node.input("function foo()")
node.input("for i=0, 5 do")
node.input("print(i)")
node.input("end")
node.input("end")
node.input("foo()")
```
It would be possible to make a pure python solution using `exec()` though, just have to check if the expression is finished before sending it to `exec()`

**Comment by dhylands** [comment]
The repl code (written in C) is written in a way that it can be called a character at a time. So I guess it should be possible to make a python callable function which passes a character at a time to a repl object. I don't think that anybody has done this yet though.

**Comment by Ivoah** [comment]
Okay, great! I'll poke around and see what I can do.

**Comment by Ivoah** [comment]
So after some initial poking around, it looks like ['int readline_process_char(int c)'](https://github.com/micropython/micropython/blob/b8945517723efaafa63df9ce52bb9d3fa3fceda5/lib/mp-readline/readline.c#L101) is what I want to hook into.

**Comment by pfalcon** [comment]
REPL is already available over WebREPL. Similar mechanism can be used for anything.

**Comment by Ivoah** [comment]
> REPL is already available over WebREPL. Similar mechanism can be used for anything.
after looking at the webrepl source, it seems like `uos.dupterm` is what I'm looking for

**Comment by dragon788** [comment]
I just ran across this today, but the microPython interactive REPL has "paste mode" Ctrl+E and "raw mode" Ctrl+A which allows you to paste in a string and only run it after hitting Ctrl+D. Perhaps this could be hooked in a similar manner?
