### ISSUE TITLE
Status of 512MB ESP8266 support

### ISSUE THREAD

**Issue by Ivoah** [micropython/micropython#2043]
I know that the 512MB ESP8266 chips don't have a filesystem, but would it be possible for them to have a single-file filesystem? Like only make boot.py available, so that it's still possible to put permanent code on them

**Comment by pfalcon** [comment]
I'm afraid no, we feature-pack esp8266 build so the actual code takes close to 512K. However, if for some reason you're interested in that, you can: 1) figure out what's the minimum filesystem size with 4K sectors (current limit enforced is based on 512K sectors); 2) try to prune port config to free up that much of flash.

Another approach would be to integrate another filesystem (but the above is much more low-hanging fruit).

**Comment by dpgeorge** [comment]
Support for 512k modules is added via "make 512k" target.  More recent issue discussing this is #2557.
