### ISSUE TITLE
WebREPL on 512MB ESP8266

### ISSUE THREAD

**Issue by Ivoah** [micropython/micropython#2045]
Currently the WebREPL doesn't work on the 512MB ESP8266 chips, as it has to write a config file. Would it be possible to give the 512MB chips a default password (or none at all)?

EDIT: Or have webrepl.start take a password argument.
EDIT 2: I got it working for now with
```python
import webrepl
webrepl._webrepl.password("<password>")
webrepl.setup_conn(8266, webrepl.accept_conn)
```

**Comment by pfalcon** [comment]
Let's handle this in #2043.
