### ISSUE TITLE
esp8266: enable/disable_irq() missing?

### ISSUE THREAD

**Issue by roger-** [micropython/micropython#2050]
I see references to them when I search the documentation, but they seem to be missing.

Are they not yet supported?

**Comment by pfalcon** [comment]
Yes. Do you need them? What for?

**Comment by roger-** [comment]
I wanted to do some pulse timing and I assume they were slowing things down. I started another issue on this in #2052.

**Comment by roger-** [comment]
Also I don't know how this is done on other target platforms, but it would be really handy if there was also an interrupt context manager. So something like this could be done:

```python
with interrupts_enabled(False):
   # do something 
```

**Comment by dpgeorge** [comment]
Machine disable/enable irq now implemented.
