### ISSUE TITLE
Subclassing list fails when __init__ has *args and/or **kwargs

### ISSUE THREAD

**Issue by hauptmech** [micropython/micropython#2071]
This may be one of the corner cases mentioned in #401.

When using *args and/or **kwargs in a subclass of list, it errors with:
`TypeError: function expected at most 1 arguments, got 3` or
`TypeError: function does not take keyword arguments` respectively.

For example, the following fails.
```python
class A(list):
    def __init__(self,*args,**kwargs):
        for a in args:
            print(a)
        for k,v in kwargs.items():
            print(k,v)

#a = A(a=1,b=2,c=3)
a = A(1,2,3)
```

I'm using an object like this underneath a lot others to avoid recreating the list behaviour (__getitem__, etc), but I can do so if there is not an easy fix for the above, or if it's undesireable for some reason.

**Comment by pfalcon** [comment]
Yes, we recommend against subclassing builtin types in MicroPython and partial support for that exists only to be able specific cases from CPython standard library. If it (partial support) doesn't work for you, well, see above.
