### ISSUE TITLE
building today

### ISSUE THREAD

**Issue by fork04** [micropython/micropython#2083]
In file included from ../lib/axtls/ssl/ssl.h:75:0,
                 from ../py/../extmod/modussl.c:37:
../lib/axtls/ssl/tls1.h:43:21: fatal error: version.h: No such file or directory
 #include "version.h"
                     ^
compilation terminated.
make: *** [build/genhdr/qstr.i.last] Error 1

**Comment by dpgeorge** [comment]
Did you follow the instructions and do `git submodule update --init`, `make axtls` then `make`?

**Comment by shifaz** [comment]
executing `make axtls` before `make` resolved this issue. thanks
