### ISSUE TITLE
cd unix; make fails - missing axtls

### ISSUE THREAD

**Issue by hauptmech** [micropython/micropython#2119]
I needed to add the following to build a fresh clone

```
git submodule update --init -- lib/axtls
cd unix
make axtls
make
```

(libffi is already on my system, so `make deplibs` and initializing all the submodules is overkill)

**Comment by peterhinch** [comment]
I hit this too.README.md could do with updating

**Comment by pfalcon** [comment]
> I needed

Yes, just as README describes.

**Comment by pfalcon** [comment]
Both README and Makefile had changes to re-optimize for "not reading instructions in full" situation. More changes may follow, though it's hard to optimize it beyond what it is - remove something, and important information will be missing, add something - and even less people will read it in full, move something - and more people will miss the important bits than on average now.

**Comment by hauptmech** [comment]
Seems good
