### ISSUE TITLE
ESP8266 Analogic Channel Randonly Reading without any command Given

### ISSUE THREAD

**Issue by vmesel** [micropython/micropython#2127]
Hey MicroPythoners, I just got an ESP8266 with micropython and when I import the math module, i get this output:

```
>>> import math
>>> chg_A3:-180
chg_A1:-140
chg_A1:-100
chg_A1:-60
chg_A1:-20
```

**Comment by dpgeorge** [comment]
This is the same problem as #2005.

Disable the messages using:
```
import esp
esp.osdebug(None)
```
