### ISSUE TITLE
esp8266: open('file.bin', 'rb').readline() returns str not bytes

### ISSUE THREAD

**Issue by MarkR42** [micropython/micropython#2128]
Steps to reproduce

1. Create a file file.bin

2. open('file.bin', 'rb').readline()

Expected result (as per Cpython 3.4.3):

```
>>> open('file.bin','rb').readline()
b'hi\n'

```

Actual result
```

>>> open('test.bin', 'rb').readline()
'hellohello2\n'

```

**Comment by pfalcon** [comment]
Can't reproduce.

**Comment by dpgeorge** [comment]
Confirmed on esp8266 port.  It needs to define MICROPY_PY_IO_FILEIO to get binary file support.

**Comment by MarkR42** [comment]
Yes, I meant on esp8266. Sorry to miss that off the report.

**Comment by pfalcon** [comment]
Fixed.
