### ISSUE TITLE
Prepare to 1.8.1 release

### ISSUE THREAD

**Issue by pfalcon** [micropython/micropython#2131]
Ticket to handle preparation to 1.8.1 release (updated inline).

Nice to resolve before the release:

* ~~https://github.com/micropython/micropython/pull/2102 - blocker~~
* ~~https://github.com/micropython/micropython/issues/2128~~
* ~~https://github.com/micropython/micropython/issues/2124 - suggested fix: decouple ets_poll_iter enable/disable from CPU interrup level.~~
* ~~https://github.com/micropython/micropython/pull/2091~~ - suggested fix: generalize and put implementation to extmod/
* ~~os.stat()~~

Not fitting:
* ~~https://github.com/micropython/micropython/pull/2107 - IMHO not ready to be merged as is, and should be postponed.~~

**Comment by robert-hh** [comment]
I'll go for uos.stat(), since I have the code already.

**Comment by dpgeorge** [comment]
Done, see 9b39263b118a4be65c58bf9c396203fa535bebe1.
