### ISSUE TITLE
Clear the MicroPython Screen

### ISSUE THREAD

**Issue by vmesel** [micropython/micropython#2142]
There is already a code for cleaning the screen, but it's not available natively in MicroPython. How about implementing it?

```
def clear():
    print("\x1B\x5B2J", end="")
    print("\x1B\x5BH", end="")
```

**Comment by peterhinch** [comment]
Users connect to boards running MicroPython with assorted terminal programs and with rshell. Does the above code assume a particular terminal emulation?

**Comment by vmesel** [comment]
Nope! like when I'm in my MacBook pro or in Windows, I use respectively, Terminal and PuTTY and both of them need some kind of code to clean the terminal!

**Comment by dpgeorge** [comment]
It could be part of upysh (see eg https://github.com/micropython/micropython-lib/pull/75).

**Comment by vmesel** [comment]
I'm going to make a FORK of the micropython-lib so I can work on this and than I will make a Pull Request!

**Comment by dpgeorge** [comment]
It looks like someone beat you to it: https://github.com/micropython/micropython-lib/pull/76

**Comment by vmesel** [comment]
LOL... Thats ok! It's for the community!

**Comment by Jibun-no-Kage** [comment]
The above codes are just classic ascii escape sequence codes by the way. 2J is clear screen, H is return cursor to home.  Need both since 2J does not change the cursor position.
