### ISSUE TITLE
Early Release Access

### ISSUE THREAD

**Issue by vmesel** [micropython/micropython#2151]
Hey guys, I'm working on some codes for the ESP8266 version of the MicroPython and I would like to receive the early releases of the code, so I can test it down and write some piece of code.

Is there any needs of payment to get the early release access?

Tnx!

**Comment by deshipu** [comment]
No, right now all the latest source code is in this github repository.

**Comment by pfalcon** [comment]
To clarify even more, "early access releases" were limited-time offer for certain categories of Kickstarter project backers. They are no longer relevant since the general access release was made.
