### ISSUE TITLE
esp8266: wifi scan ssid wrong length (especially if 32 bytes)

### ISSUE THREAD

**Issue by MarkR42** [micropython/micropython#2157]
The length of the ssid is computed using strlen(), which sometimes gets it wrong and risks buffer overrun. I've committed a fix on my branch.

Steps to reproduce:

1. Set up a wifi accesspoint within range with a ssid of exactly 32 bytes (the maximum)

2. 

```
import network
sta_if = network.WLAN(network.STA_IF);
sta_if.scan()
```

Expected result: ssid is shown correctly in the scan() result.

Actual result: often, some garbage bytes at the end of the ssid, maybe occasionally, a crash.

**Comment by pfalcon** [comment]
Fixed by linked PullReq.
