### ISSUE TITLE
Clear boot screen garbage with print(chr(27) + "[2J")

### ISSUE THREAD

**Issue by Tooblippe** [micropython/micropython#2169]
if you can put the following in the boot.py at the top it will clear most of the boot rubbish
    print(chr(27) + "[2J")

just an idea.

**Comment by pfalcon** [comment]
What's rubbish for you, is important diagnostics information for others. The tip is interesting though, and some users may find it useful. Please be sure to share it at http://forum.micropython.org/viewforum.php?f=16
