### ISSUE TITLE
stmhal frozen bytecode: problem with complex values

### ISSUE THREAD

**Issue by peterhinch** [micropython/micropython#2173]
Code containing a line of the form
```python
v = 1 + 0j
```
results in working code when cross-compiled but the module cannot be frozen, producing the outcome
```
error while freezing qstr(str='plot.py', qstr_esc='plot_dot_py', qstr_id='MP_QSTR_plot_dot_py'): freezing of object 0j is not implemented
```
Using
```python
v = complex(1)
```
is successful.

**Comment by dpgeorge** [comment]
Should be fixed by c51c883cc84bb680dcc810a81e81dd1df879a07c, sorry for slow response :)
