### ISSUE TITLE
Expose the font from extmod/modframebuf.c to python programs

### ISSUE THREAD

**Issue by deshipu** [micropython/micropython#2177]
I wonder if it would be possible to have the font that is compiled into the framebuf module exposed to the python code somehow, so that it could be used by drivers that don't use a 1-but framebuffer -- like the drivers for color displays. For instance, a function that takes a character and returns a memory view with the relevant font data? Not sure how feasible or hard it would be to do, and if there would be an additional cost involved with that, but it seems to me a waste when each driver includes their own font and struggles to fit it in RAM.

**Comment by deshipu** [comment]
Right now I do it with a dirty hack -- I create a 8x8 framebuffer, print the character to it, and then copy the character data -- but I think this could be done nicer?

https://bitbucket.org/thesheep/micropython-ili9341/src/4fe3cd28006e171eec16aff9e7cbae8ed394f88d/ili9341.py?fileviewer=file-view-default#ili9341.py-142:157

**Comment by mcauser** [comment]
The framebuffer font is located at /stmhal/font_petme128_8x8.h
Each byte is represents a column, left to right, with the msb at the bottom.

Sharing the font data with other display libraries sounds beneficial.
A function on the framebuf module for returning a byte array representing the supplied character(s).

**Comment by pfalcon** [comment]
So, exposing it pretty easy from technical point, but no so easy from API design point of view. The only option I see for now is to expose it as a private, undocumented function, likely to be gone later.

**Comment by deshipu** [comment]
What would it be replaced with?

**Comment by pfalcon** [comment]
By a text() function which just works.

**Comment by deshipu** [comment]
How would that work? I'm eager to to try and write that, but my limited imagination doesn't let me think about something that would work in all possible cases with all possible third party drivers and libraries.
