### ISSUE TITLE
dupterm should use readinto() method, not read()

### ISSUE THREAD

**Issue by pfalcon** [micropython/micropython#2208]
Otherwise it requires allocating (bytes) object again and again, leading to excessive memory traffic and fragmentation. I'm going to change esp8266 port to readinto().

**Comment by dpgeorge** [comment]
Yes that makes sense.  Eg block device protocol uses in-place reading method.

**Comment by pfalcon** [comment]
Required changes landed in the master, ending with https://github.com/micropython/micropython/commit/a4c8a1ffe86ace0b4394d751a2d3716f7d865ba6 . They're partly generic, partly esp8266 specific. Other ports are advised to make a similar API change.
