### ISSUE TITLE
unix: main_ uses 4K of stack unnecesarily

### ISSUE THREAD

**Issue by dhylands** [micropython/micropython#2222]
main_ allocates a temporary buffer on the stack using CHECKBUF:
https://github.com/micropython/micropython/blob/master/unix/main.c#L439
This winds up staying on the stack (I tested DEBUG and non-DEBUG builds using gcc 4.8.4) and basically causes that 4K of space to never be freed until exiting micropython.

I think that it should use either the regular heap or the mpy heap so that the memory can be released.

**Comment by pfalcon** [comment]
Even I find that too perfectionist, but fixed in 520f35632d78e1b73f647d993205aade0de8b1ce.
