### ISSUE TITLE
esp8266 webREPL sends old file data: unexpected UI behaviour.

### ISSUE THREAD

**Issue by peterhinch** [micropython/micropython#2242]
Usage: send a program to the esp8266, run it then modify the source. Use webREPL to re-send the updated source. The UI still shows the name of the file, and pressing 'Send to device' apparently works. However it behaves as if the old file were buffered re-sending the old data. It seems to be necessary to browse for the file again to force it to load the new version.

While not a major issue it is likely to confuse newcomers.

**Comment by pfalcon** [comment]
WebREPL project is hosted at https://github.com/micropython/webrepl

**Comment by peterhinch** [comment]
Apologies. I've raised the issue there.
