### ISSUE TITLE
Performance of yield from and async/await

### ISSUE THREAD

**Issue by jpochyla** [micropython/micropython#2277]
Hi! During a refactoring of a streaming parser to async methods, i've run a little bit of benchmarking (to take a look how big slowdown it would be to simply make most parsing methods `async def`). Benchmark code is [in a Gist here](https://gist.github.com/jpochyla/ddfc7fd7e7bb215945cd74bedc1b8acc).

What surprised me is the big difference between CPython and micropython:

```
$ python3 test.py
binary_yieldfrom(19) * 10: total 5.52s
binary_async(19) * 10: total 5.65s
binary_sync(19) * 10: total 2.29s
$ ./vendor/micropython/unix/micropython test.py
binary_yieldfrom(19) * 10: total 166s
binary_async(19) * 10: total 169s
binary_sync(19) * 10: total 2.66s
```

Is there any reason for this difference? What kind of crazy magic does CPython do to make it so fast? And can it be possibly replicated in micropython?

Thank you!

**Comment by pfalcon** [comment]
> Is there any reason for this difference?

The generic reason for any difference is that CPython and MicroPython are completely independently developed codebases (with different requirements).

> What kind of crazy magic does CPython do to make it so fast?

Well, you constructed an artificial testcase "against MicroPython" ;-). Try to run it with values like "d, r = 5, 100000" and you'll see that uPy actually beats CPy in coroutine call performance with reasonable call depth. However, CPy likely maintains a stack of enclosed coroutines running, which allows it to call in the most enclosed (currently running) coroutine directly, while uPy lacks such extra structure, so on each .send() it starts executing outermost coroutine and then passes a value down by interpreting the bytecode. With big call depth, this leads to exponential slowdown which you can see.

> And can it be possibly replicated in micropython?

Yes, patches welcome.
