### ISSUE TITLE
Site down?

### ISSUE THREAD

**Issue by mcauser** [micropython/micropython#2288]
I am unable to reach the MicroPython site or forum.
https://micropython.org
https://forum.micropython.org

http://www.downforeveryoneorjustme.com/micropython.org
http://www.downforeveryoneorjustme.com/forum.micropython.org

Responding to pings though.
```
Mikes-iMac:~ mike$ ping micropython.org
PING micropython.org (176.58.119.26): 56 data bytes
64 bytes from 176.58.119.26: icmp_seq=0 ttl=55 time=308.465 ms
64 bytes from 176.58.119.26: icmp_seq=1 ttl=55 time=285.738 ms
64 bytes from 176.58.119.26: icmp_seq=2 ttl=55 time=280.610 ms
```

**Comment by mnelsoneorm** [comment]
Same here.....and for some reason my local webrepl is problematic today too :(

**Comment by mcauser** [comment]
@dpgeorge http://dpgeorge.net/ is also down

**Comment by dpgeorge** [comment]
Thanks for the report.  I'm on it.

**Comment by dpgeorge** [comment]
Ok, everything should be back to normal.

**Comment by dothacker495** [comment]
Oh Great, Big thanks. It's like the micropython docs is life itself. It is hard to find other references

**Comment by pfalcon** [comment]
@dothacker495 : You can download PDF docs to use locally. And you can build HTML docs yourself too.
