### ISSUE TITLE
Error in Docs - Pin.OUT should be Pin.IN

### ISSUE THREAD

**Issue by cefn** [micropython/micropython#2308]
At http://docs.micropython.org/en/latest/esp8266/esp8266/tutorial/pins.html

```
To make an input pin use:
>>> pin = machine.Pin(0, machine.Pin.OUT, machine.Pin.PULL_UP)
```

...though it's correct in http://docs.micropython.org/en/latest/esp8266/library/machine.Pin.html

**Comment by pfalcon** [comment]
Fixed, thanks.
