### ISSUE TITLE
WeMos D1 Mini os.mkfs() fails to execute

### ISSUE THREAD

**Issue by cpranzl** [micropython/micropython#2314]
No success in executing os.mkfs()
Version: Micropython 1.8.2-9-g805c2b9 on 2016-07-10; ESP module with ESP8266

Repro:
```
>>> import os
>>> os.mkfs()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'mkfs'
```

**Comment by deshipu** [comment]
What makes you think there should be such a function? I didn't find any mention of it in the documentation.

**Comment by cpranzl** [comment]
Statet in issue #2044 

> 
> 
> You need to pass the block device and a mount point:
> 
> os.mkfs(blockdevice, '/mnt')
> 
> In the case of the internal flash the block device is pyb.Flash() and you can format it using:
> 
> flash = pyb.Flash()
> os.umount('/flash') # unmount first
> os.mkfs(flash, '/flash')
> os.mount(flash, '/flash') # mount newly formatted filesystem

```
>>> flash = pyb.Flash()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'pyb' is not defined
```

**Comment by deshipu** [comment]
That issue is about the PyBoard, not the ESP8266 port.

**Comment by cpranzl** [comment]
So 
```
>>> import os
>>> os.listdir()
['boot.py']
```
is the correct behavior?

**Comment by deshipu** [comment]
Yes.
