### ISSUE TITLE
Esp8266: can't get the __neg__ operator to work

### ISSUE THREAD

**Issue by rguillon** [micropython/micropython#2317]
The following code works on the linux port but not on the esp8266: 

```
class a():
    def __init__(self, val):
        self.val = val
    def __neg__(self):
        return a(-self.val)

a1 = a(5)
a2 = -a1
print(a2.val)
```

On my esp8266 I've got a ```TypeError: unsupported type for : 'a'````

Did i missed something?

**Comment by deshipu** [comment]
Yes. For performance reasons, MicroPython doesn't let you redefine operators.

**Comment by rguillon** [comment]
I see, however __add__ and __sub__ seems to work fine.

**Comment by pfalcon** [comment]
> The following code works on the linux port but not on the esp8266:

Should be fixed by 9cf29493569d6292fc672e757b2aa96b42f1fe1d

**Comment by rguillon** [comment]
It works, that was fast!

Thanks.

**Comment by deshipu** [comment]
I'm sorry for speaking too soon, I really thought it's completely unsupported. Is there a list somewhere of which operators are supported?

**Comment by pfalcon** [comment]
We support "all", except possibly for the esoteric ones, like matrix mul. There may be also some differences in semantics. A unit test for this functionality would a definitive reference of what's supported.
