### ISSUE TITLE
WebREPL not running

### ISSUE THREAD

**Issue by mleonard87** [micropython/micropython#2336]
On the WebREPL docs for the ESP8266 ([here](http://docs.micropython.org/en/latest/esp8266/esp8266/tutorial/repl.html#webrepl-a-prompt-over-wifi)) it mentions connecting to the chips WiFi access point and then going to the WebREPL webpage.

I found that the WebREPL wasn't actually started on my board and the documentation didn't seem to indicate how to start it. This should be added to the documentation to avoid confusion.

**Comment by pfalcon** [comment]
Please see http://docs.micropython.org/en/latest/esp8266/esp8266/quickref.html#webrepl-web-browser-interactive-prompt .
