### ISSUE TITLE
Port to the FRDM-KL25Z

### ISSUE THREAD

**Issue by kerbingamer376** [micropython/micropython#2356]
Hi,
would it be possible to port micropython to the NXP/Freescale KL25Z? It's capable of running micropython, and is an ARM device so porting wouldn't be too hard. Asking here because I have no knowledge of the toolchain at all (I've been using automagic makefiles).

**Comment by dpgeorge** [comment]
That board/MCU only has 128k flash and that's a bit tight for uPy (but still doable if you disable most of the Python features).

Otherwise, please ask such questions on the forum: https://forum.micropython.org .  Thanks!
