### ISSUE TITLE
pinout scheme is outdated in docs

### ISSUE THREAD

**Issue by kamikaze** [micropython/micropython#2371]
There is a 1.0 version of pyBoard pinout image while in some places I've found v1.1

**Comment by dpgeorge** [comment]
There are many PYBv1.0 boards out there so we still need the pinout for it.  In 5c3a2f162ec08aa2df900f25e87abb5d74e39c7c I've added extra links to the other pyboard variants in the quickref.

**Comment by mcauser** [comment]
I also added them here: https://github.com/micropython/pyboard/pull/12

**Comment by dpgeorge** [comment]
PYBv1.1 pinout was made the default in the quickref in ea95bdc1ca24e3006ef78a723e0740128ae4b0d9
