### ISSUE TITLE
undefined reference to `mp_hal_stdout_tx_strn_cooked'

### ISSUE THREAD

**Issue by benalb** [micropython/micropython#2390]
benalb@intruder  ~/tmp/micropython  
make -C mpy-cross
make: Entering directory '/home/benalb/tmp/micropython/mpy-cross'
Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
LINK mpy-cross
build/py/../lib/utils/printf.o: In function `putchar':
printf.c:(.text.putchar+0x13): undefined reference to `mp_hal_stdout_tx_strn_cooked'
build/py/../lib/utils/printf.o: In function `puts':
printf.c:(.text.puts+0x19): undefined reference to `mp_hal_stdout_tx_strn_cooked'
printf.c:(.text.puts+0x2a): undefined reference to `mp_hal_stdout_tx_strn_cooked'
collect2: error: ld returned 1 exit status
../py/mkrules.mk:109: recipe for target 'mpy-cross' failed
make: *** [mpy-cross] Error 1
make: Leaving directory '/home/benalb/tmp/micropython/mpy-cross'

 benalb@intruder  ~/tmp/micropython  
uname -a
Linux intruder 3.16.0-4-686-pae #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) i686 GNU/Linux

**Comment by dpgeorge** [comment]
Thanks for the report, fixed in 2b882e9acaecd92cf3107a597c9aba99f23b794e.
