### ISSUE TITLE
esp8266 uart 2 not available

### ISSUE THREAD

**Issue by MartijnBraam** [micropython/micropython#2391]
I've flashed micropython to my esp8266 but cannot get the third uart working.

According to this image: https://bennthomsen.files.wordpress.com/2015/12/nodemcu_pinout_700-2.png

There is UART 0 that is connected to the usb-serial converter and runs the repl.
There is UART 1 that only has a TX pin so I cannot receive data.

```python
OSError: UART(1) can't read
```

There is UART 2 that doesn't seem to exist in micropython.

```python
ValueError: UART(2) does not exist
```

Is there any way I can get UART 2 working?

**Comment by dpgeorge** [comment]
There are only 2 UARTs.  Please see this issue for explanation about the NodeMCU pinout: https://github.com/esp8266/Arduino/issues/482
