### ISSUE TITLE
[HELP] How to Login Web Site

### ISSUE THREAD

**Issue by MeantCoder** [micropython/micropython#2400]
Hello guys,

I'm making basic notifier

I want login fb/twitter/gmail etc. with nodemcu module( with uPython) but i can't imported mechanize or bs4.
how to login fb/twitter/gmail etc. ? thanks

**Comment by deshipu** [comment]
I think this is something more suited for the forum than the bug tracker. Please keep the issue tracker for actual bugs you find.
