### ISSUE TITLE
Automated builds

### ISSUE THREAD

**Issue by iBobik** [micropython/micropython#2426]
How about to build firmwares automatically in CI?

I am going to make builder as a Docker image, you can then use it as a base.

Do you prefer some CI solution for Github?

**Comment by dpgeorge** [comment]
We already use Travis CI to do automated builds on every push and PR.  And official firmware images are available at https://micropython.org/download/

What exactly are you suggesting?

**Comment by iBobik** [comment]
Aha, I did but found daily builds and did not saw it in pull requests. (So everybody can see if it is building without errors.)

My mistake.

Jan Pobořil
http://honza.poboril.cz/

18. 9. 2016 v 5:27, Damien George <notifications@github.com>:
