### ISSUE TITLE
Can not initialize WDT on esp8266

### ISSUE THREAD

**Issue by muhlpachr** [micropython/micropython#2430]
```
>>> from machine import WDT
>>> wdt = WDT(timeout=2000)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: function does not take keyword arguments
```

**Comment by muhlpachr** [comment]
```
>>> wdt = WDT(2000)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError:
```

**Comment by dpgeorge** [comment]
Please use `WDT()`  to create the default WDT.  At the moment it doesn't support setting the timeout.

**Comment by muhlpachr** [comment]
What is timeout of default WDT pelase ?
Will wdt.feed() work as expected  ?
Documentation describe planned implementation or is it copy&paste mistake from other port please ?
http://docs.micropython.org/en/latest/esp8266/library/machine.WDT.html
Thank you.

**Comment by pfalcon** [comment]
@muhlpachr : Please see https://github.com/micropython/micropython/issues/2154

**Comment by pfalcon** [comment]
> Documentation describe planned implementation or is it copy&paste mistake from other port please ?

Please see first section of the standard library description:
http://docs.micropython.org/en/latest/esp8266/library/index.html
