### ISSUE TITLE
Throw exception when using incompatible frozen mpy files

### ISSUE THREAD

**Issue by ryannathans** [micropython/micropython#2447]
Is it realistic to have some exception or error thrown when a module was frozen with an incompatible version of mpy-cross? Would it be possible to detect when this event occurs or would 'versioning' need to be added?

Idea is to prevent things like #2446 happening in the future

**Comment by dpgeorge** [comment]
There is already a version number in mpy files (and a check which raises if it doesn't match), but it didn't cross my mind to bump that version when I made the recent change to remove some bytecodes...
