### ISSUE TITLE
zlib: Segfault on zlib.DecompIO() on unix

### ISSUE THREAD

**Issue by hosaka** [micropython/micropython#2468]
I was playing with the zlib on unix port today, trying to improve the test coverage and came across a problem that I don't really understand. The code is a slight cut down version of tests/extmod/uzlib_decompio_gz.py
```python
import uzlib as zlib
import uio as io
v = b'x\x9c=\xca\xb9\x11\x00 \x0c\x04\xb1\x96\xbc\x9c?zs\xf1\x100(\x16R\xd1\x88\xb0A\x95\x1et)\x87/\x86%\x8f\xac\xde\xc6=m\xcf\x01\x84V\x0c\xde'

# the data encoded is 
# bytearray(b'13371813150|13764518736|11111111115|12345678901|13800000000')

# segfault
buf = io.BytesIO(v)
inp = zlib.DecompIO(buf, -8)
inp.read()
```

**Comment by dpgeorge** [comment]
The test above gives `OSError: EINVAL` for me (not a segfault).  Removing the "-8" arg to DecompIO constructor makes it work correctly.

**Comment by hosaka** [comment]
I've just tried to reproduce on my home pc to no success. Please ignore this for the time being, if I manage to figure out what I did that caused the segfault, I will update you.

**Comment by pfalcon** [comment]
@hosaka : First of all, thanks much for your work on improving test coverage - that's both important on its own, and just the right thing to do at the current stage of the development, so double-hit, kudos. 

Regarding this bug - I recently pushed https://github.com/micropython/micropython/commit/39968aaaff575800218b47488f85eed7081cd0cb which fixes an issue of compression/decompression dictionary size mismatch. Surprisingly, I didn't see it leading to crash, instead to data corruption. Well, now it's properly caught.

The testcase you give above unlikely to be affected by that issue though, as data set (and thus dictionary) is small anyway.

**Comment by hosaka** [comment]
@pfalcon Thanks Paul. I am hoping to progress a little more on the test coverage when I get some free time.

I didn't try to reproduce this again, but this could well be related to the commit you've linked. I'll stick it on my todo list and will test again with the new change. I will close this for the time being as I think we've exhausted the topic for now. Thanks again for the praise!
