### ISSUE TITLE
esp8266/moduos.c: Inconsistencs with respect to MICROPY_VFS_FAT 

### ISSUE THREAD

**Issue by robert-hh** [micropython/micropython#2470]
The code section for the stat() method (line 150..158) are outside the #if MICROPY_VFS_FAT bracket, leading to compile errors when MICROPY_VFS_FAT is set to 0 in mpconfigport.h.

**Comment by hosaka** [comment]
You're right. They need to be moved up above the MICROPY_VFS_FAT #endif.

**Comment by dpgeorge** [comment]
Yes.  I'll fix it.

**Comment by dpgeorge** [comment]
Fixed in bd8737520273fc07bec1ec3487c92eb11609f1da.

**Comment by robert-hh** [comment]
Wow! That's fast. Thanks
