### ISSUE TITLE
machine.time_pulse_us not included even when built with MICROPY_PY_MACHINE_PULSE

### ISSUE THREAD

**Issue by kmilner** [micropython/micropython#2480]
The documentation references the time_pulse_us function in the machine module here: https://micropython.org/resources/docs/en/latest/wipy/library/machine.html#miscellaneous-functions however it does not exist when building for the pyboard, even when adding the MICROPY_PY_MACHINE_PULSE option referenced in the changelog. 

This seems to be because stmhal/modmachine.c does not include it in the module globals table.

**Comment by dpgeorge** [comment]
Thanks for the report.  machine.time_pulse_us has now been added in 0bb3c7d3b7b8e670fd92c114b07fed1235c0d1ab.
