### ISSUE TITLE
stmhal: SD Clock Always Clocking

### ISSUE THREAD

**Issue by ryannathans** [micropython/micropython#2487]
During EM compliance testing it was found that the SD Card Clock is always clocking at 24MHz, even whilst just idling on the REPL. 

Radiation peak was at 264Mhz (11th harmonic) on the board I'm working with.

Problem originally occurred on STM32F439 but after testing it seems to also occur on the PYBLITEV1.0 and I suspect all chips covered by stmhal.

Working around it for now by changing the mode of the clock pin before and after SD access.

**Comment by dpgeorge** [comment]
Is this only when an SD card is actually inserted?

**Comment by ryannathans** [comment]
@dpgeorge apologies for the ambiguity, the line is at 24MHz continuously when SD is inserted prior to powering the device on and after removal of SD whilst device is running. If the device boots with no SD then the clock will sit at 400KHz instead of 24MHz but it still continuously clocks

**Comment by ryannathans** [comment]
stmhal/hal/f4/inc/stm32f4xx_ll_sdmmc.h

Line 75

```
  uint32_t ClockPowerSave;       /*!< Specifies whether SDIO Clock output is enabled or
                                      disabled when the bus is idle.
                                      This parameter can be a value of @ref SDIO_Clock_Power_Save           */
```

Line 580

```
/* SDIO Intialization Frequency (400KHz max) */
#define SDIO_INIT_CLK_DIV ((uint8_t)0x76)

/* SDIO Data Transfer Frequency (25MHz max) */
#define SDIO_TRANSFER_CLK_DIV ((uint8_t)0x0)
```

**Comment by ryannathans** [comment]
stmhal/hal/f4/inc/stm32f4xx_ll_sdmmc.h

Line 75

```
  uint32_t ClockPowerSave;       /*!< Specifies whether SDIO Clock output is enabled or
                                      disabled when the bus is idle.
                                      This parameter can be a value of @ref SDIO_Clock_Power_Save           */
```

Line 580

```
/* SDIO Intialization Frequency (400KHz max) */
#define SDIO_INIT_CLK_DIV ((uint8_t)0x76)

/* SDIO Data Transfer Frequency (25MHz max) */
#define SDIO_TRANSFER_CLK_DIV ((uint8_t)0x0)
```

**Comment by ryannathans** [comment]
stmhal/hal/f4/inc/stm32f4xx_ll_sdmmc.h

Line 75

```
  uint32_t ClockPowerSave;       /*!< Specifies whether SDIO Clock output is enabled or
                                      disabled when the bus is idle.
                                      This parameter can be a value of @ref SDIO_Clock_Power_Save           */
```

Line 580

```
/* SDIO Intialization Frequency (400KHz max) */
#define SDIO_INIT_CLK_DIV ((uint8_t)0x76)

/* SDIO Data Transfer Frequency (25MHz max) */
#define SDIO_TRANSFER_CLK_DIV ((uint8_t)0x0)
```

**Comment by ryannathans** [comment]
A combination of increasing SDIO_TRANSFER_CLK_DIV and enabling SDIO_CLOCK_POWER_SAVE_ENABLE resolved my issue, I've created a PR for disabling the SD clock when SD isn't in use as a result of my findings.

**Comment by dpgeorge** [comment]
Fixed by above patch.
