### ISSUE TITLE
stmhal: import os throws exception after failed mkfs

### ISSUE THREAD

**Issue by ryannathans** [micropython/micropython#2505]
import os fails with the same error as previously thrown. Probably due to misuse of mkfs but this shouldn't be occurring even so.

Possible relation to: #2044 

My misuse of mkfs due to lack of documentation (function missing from docs) http://docs.micropython.org/en/latest/pyboard/library/uos.html

```
>>> import os
>>> os.umount('/sd')
>>> os.mkfs(pyb.SDCard, '/sd')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: argument has wrong type
>>> import os
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: argument has wrong type
```

Additionally, what is the correct usage of mkfs for the SD card? I've tried the below which seems to follow the suggested usage (for flash at least) in #2044 

```
>>> import os
>>> sd = pyb.SDCard()
>>> os.umount('/sd')
>>> os.mkfs(sd, '/sd')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: can't mkfs
```

**Comment by dpgeorge** [comment]
I can't reproduce this issue with "import os" raising an exception after a failed mkfs.

os.mkfs() is now removed, use instead os.VfsFat.mkfs(bdev).

> what is the correct usage of mkfs for the SD card?

mkfs doesn't work on an SD card that has a partition table.  To format a device with a partition table you'll either need to do it on a host PC, or create a (sub)block device which exposes just the partition in the SD card that you want to format, then pass this (sub)block device to mkfs.
