### ISSUE TITLE
micropython current_gesture 3g 6g 8g not happenning

### ISSUE THREAD

**Issue by catchpolej** [micropython/micropython#2512]
However violently I shake the microbit I only get HAPPY/SAD image with this script.
It seems that current_gesture 3g,6g,8g never happens?

# 
# 'g' max sensing
#
from microbit import *

Three = Image("66666:"
              "00006:"
              "66666:"
              "00006:"
              "66666")
Six = Image("70000:"
            "70000:"
            "77777:"
            "70007:"
            "77777")
Eight = Image("99999:"
              "90009:"
              "99999:"
              "90009:"
              "99999")

while (button_b.was_pressed() != True):
    if(button_a.was_pressed() == True):
        
        for i in range(0,1000):
                sleep(1)
                display.show(Image.HAPPY)
                gesture = accelerometer.current_gesture()
                if (gesture=="3g"):
                    display.show(Three)
                    break
                if (gesture=="6g"):
                    display.show(Six)
                    break
                if (gesture=="8g"):
                    display.show(Eight)
                    break
                sleep(1)
                display.show(Image.SAD)
display.scroll("XXXXXX")

**Comment by dpgeorge** [comment]
Please repost this issue at the microbit-specific repo: https://github.com/bbcmicrobit/micropython/
