### ISSUE TITLE
stmhal: SD Card does not work on OLIMEX_407 board

### ISSUE THREAD

**Issue by BrendanSimon** [micropython/micropython#2521]
The SD card is not intialised on the OLIMEX_407 board.  The reason is that it has no SD Card Detect pin and the sdcard module only initialises a card if it is detected as being present.

**Comment by BrendanSimon** [comment]
I modified the sdcard module so that if the SD Card Detect pin is not defined in the board config file, then it will not initialise such a pin, and the SD Card Detect function will always return true, and it now works :)

Could someone please integrate into master (pull request coming).

**Comment by dpgeorge** [comment]
There was a PR for this: #2522 and discussion continued there (although it was closed without merging).
