### ISSUE TITLE
Should we add rng, sdcard, and DAC to machine HW API?

### ISSUE THREAD

**Issue by dhylands** [micropython/micropython#2524]
So, 2 modules which seem to missing from the machine HW API are rng and sdcard.

I'd like to propose that we add them. For sdcard, we could go with the API currently being used by stmhal here:
https://github.com/micropython/micropython/blob/master/stmhal/sdcard.c#L422-L432
minus the read and write routine. We may want to add an optional id parameter for the day when there is a processor with multiple SDIO interfaces (the i.MX6 has 4).

Many newer chips have a hardware random number generator, so adding that also makes sense, although perhaps with an API something like this:

```
rng = RNG()
rand_small_int = rng.random()
```

just to be more consistent with everything else. The Teensy 3.5 & 3.6 MCUs also have hardware random number generators.

I'm also assuming that DAC functionality would also belong in machine, even though it hasn't currently been mentioned.

**Comment by jonnor** [comment]
I believe that the current version of the `random` module uses the hardware RNG on most ports. 

SDCard functionality based on SPI can be found in https://github.com/micropython/micropython-lib/blob/master/micropython/drivers/storage/sdcard/sdcard.py

DAC is now defined in machine, and implemented on STM32, ESP32 ports, etc.

So I believe his issue can be closed as fixed :) Please open specific issues for any remaining functionality/bugs
