### ISSUE TITLE
esp8266: esp.esf_free_bufs(5) causes an immediate reboot

### ISSUE THREAD

**Issue by robert-hh** [micropython/micropython#2525]
Other values tried just return 0.
Yes I know: one simply should not set the argument value to 5
MicroPython v1.8.4-207-g799ccdc-dirty on 2016-10-16; ESP module with ESP8266
Empty boot.py and main.py, Wemos D1

**Comment by pfalcon** [comment]
esp.esf_free_bufs() is an internal undocumented function with undefined behavior. Do not use if in doubt.
