### ISSUE TITLE
Hard to find the appropriate source code for documentation

### ISSUE THREAD

**Issue by kamikaze** [micropython/micropython#2526]
As an example: there is an [outdated SPI documentation](http://docs.micropython.org/en/latest/pyboard/library/machine.SPI.html) and turns out that is an outdated WiPi doc. Isn't it a better idea to provide a link to the source code file/files right in documentation? There are at least two pros:

1. even if a document is "wrong" - you can figure out this by opening a wrong source code for a wrong port.

2. you can find a right source code fast, find a difference and update documentation also fast.

I'm working on SSD1322 driver right now. Found a broken SPI documentation and failed to find a right source code.

**Comment by deshipu** [comment]
You have a "View page source" link in the top right corner of every page.

**Comment by kamikaze** [comment]
this is about PAGE source, but I'm talking about SOURCE code )

**Comment by deshipu** [comment]
There is no 1-1 correspondence between the source code and the documentation.

**Comment by kamikaze** [comment]
ok, but at least if there is a class name in documentation - isn't it possible to link it to the correct source file?

**Comment by deshipu** [comment]
This is the class definition for SPI: https://github.com/micropython/micropython/blob/master/stmhal/spi.c#L1125-L1132

Not very helpful, I'm afraid.

**Comment by deshipu** [comment]
By the way, I created a number of display drivers for MicroPython, perhaps my code will be useful for you: https://bitbucket.org/thesheep/micropython-display/src

**Comment by kamikaze** [comment]
wow, that's a lot :) don't you want to make a fork and place them into drivers directory and then ask for PR? :)

**Comment by deshipu** [comment]
No, I don't.

**Comment by pfalcon** [comment]
> As an example: there is an outdated SPI documentation

What's exactly outdated? If you'd like to assist with it being fixed, please submit a separate ticket with exact and objective information about it. (Some background information on effective bug reporting: http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

For general discussions and opinion exchanges, we have a forum instead: http://forum.micropython.org

**Comment by kamikaze** [comment]
That is what exactly outdated: http://forum.micropython.org/viewtopic.php?p=14826#p14826

**Comment by pfalcon** [comment]
Ok, that at least partially addressed by https://github.com/micropython/micropython/commit/a0b2f48c2f501fb60ec312756fe4b17e81f94cc5 . It will be on docs.micropython.org tomorrow.
