### ISSUE TITLE
extmod/vfs_fat: FileIO and TextIO make_new is unreachable.

### ISSUE THREAD

**Issue by hosaka** [micropython/micropython#2533]
file_obj_make_new [vfs_fat_file.c#L229-L233](https://github.com/micropython/micropython/blob/master/extmod/vfs_fat_file.c#L229-L233) is not reachable since neither FileIO, nor TextIO are exposed to the user through the dict tables and can not be created directly. Can the function be removed or commented out?

**Comment by dpgeorge** [comment]
It is actually reachable if you get the type of an existing file (which returns FileIO).  A test for this is added in 6194336d81e73e74eb7e0f26501966082ce4d411.
