### ISSUE TITLE
Error when importing .mpy module

### ISSUE THREAD

**Issue by djolez** [micropython/micropython#2540]
Hi, 
I flashed **_v1.8.5 stable_** to my ESP8266 and tried to use .mpy modules but I get `ValueError: incompatible .mpy file`, I looked at the source code but couldn't understand what could be the reason for this error.

**Comment by dpgeorge** [comment]
Please try recompiling mpy-cross, then recompiling your .mpy files using the new mpy-cross.  That should fix it.

**Comment by djolez** [comment]
Yeah it worked, thanks.
