### ISSUE TITLE
esp8266: error in building image

### ISSUE THREAD

**Issue by robert-hh** [micropython/micropython#2575]
When trying to run make with the most recent statem I get an error:
```
CC modutime.c
modutime.c:122:5: error: initialization discards 'const' qualifier from pointer target type [-Werror]
     { MP_ROM_QSTR(MP_QSTR_ticks_add), MP_ROM_PTR(&mp_utime_ticks_add_obj) },
     ^
cc1: all warnings being treated as errors
../py/mkrules.mk:47: recipe for target 'build/modutime.o' failed
```
It looks as if line 122 should read instead:
`    { MP_OBJ_NEW_QSTR(MP_QSTR_ticks_add), (mp_obj_t)(&mp_utime_ticks_add_obj) },
`

**Comment by pfalcon** [comment]
This should be fixed in the current master.

**Comment by robert-hh** [comment]
Indeed. I'm just puzzled, because I'm almost sure I did a 'git pull' before the 'make' (and a make in open-esp-sdk, make clean, ....) before I confirmed wrote my note about it.
