### ISSUE TITLE
Line discipline settings in putty for NodeMCU v2

### ISSUE THREAD

**Issue by NoPinky** [micropython/micropython#2581]
I'm new to micropython and the ESP8266 and using putty to connect to a newly flashed, untouched esp8266-20161017-v1.8.5.bin on a NodeMCU v2 board. I always use putty to connect to various machines and hardware via SSH and serial connection. But on the NodeMCU board the Line disciple options can't auto detect the right settings that would make sense for a comfortable use. I have to enforce 'local echo' and 'local line editing' to see what I'm typing and prevent characters beeing displayed twice. This never happened to me before on any other device.
Is this an issue with the way the serial connection of ESP8266 MCU is setup or do the settings of the micropython firmware create this issue?

**Comment by robert-hh** [comment]
Hello @NoPinky. My guess is that it is more related to the USB/UART converter on the board. I never have seen comparable issues. Set Putty to: no handshake, no local echo, no local editing, baud rate 115200, 8 bit, no parity = plain vanilla.
Besides that: you should better place this question in the forum, section ESO8266: https://forum.micropython.org/
