### ISSUE TITLE
webrepl error form esp8266

### ISSUE THREAD

**Issue by skylin008** [micropython/micropython#2590]
Hello,
    when I use chrome and firefox web browser ,but error information show as below:

# First-time WebREPL connection has been received. WebREPL initial setup
will now start over this connection. During setup, UART REPL will be
non-responsive. After setup finishes, the board will be rebooted. In
case of error during setup, current session will continue.

If you receive this message unexpectedly, it may mean that your WebREPL
connection is being hacked (power off board if unsure).

How to slove this issue.Thanks!

**Comment by dpgeorge** [comment]
This is normal operation if starting the board for the first time after flashing with MicroPython.  You should enter a password in the WebREPL interface in your browser.  Then it should boot normally the next time.
