### ISSUE TITLE
FatFs's os.rename() is not POSIX compliant

### ISSUE THREAD

**Issue by pfalcon** [micropython/micropython#2598]
Trying to do os.rename("old", "new") with FatFs fails if "new" already exists with `OSError: [Errno 17] EEXIST`. This is not POSIX compliant:

> If newpath already exists it will be atomically replaced (subject to a few conditions; see ERRORS below), so that there is no       point at which another process attempting to access newpath will find it missing.

(from man 2 rename)

https://docs.python.org/3/library/os.html#os.rename says on this:

> Rename the file or directory src to dst. On Unix, if dst exists and is a file, it will be replaced silently if the user has permission. On Windows, if dst already exists, OSError will be raised even if it is a file.

So, we could leave it raising OSError, but that would be emulating Windows, and we should emulate POSIX apparently.

**Comment by hosaka** [comment]
I think adhere to posix is the best option. I remember noticing this not long ago, but forgot to mention this.

**Comment by pfalcon** [comment]
I think the same - like, VFS interface should adhere to POSIX definition of operations, and each particular FS should implement it.

**Comment by dpgeorge** [comment]
+1 for POSIX behaviour.

**Comment by robert-hh** [comment]
In principle I am in favour of a POSIX compliance, although  I do not like the idea of a silent replace.

**Comment by deshipu** [comment]
The Windows way makes it very hard to update file's contents atomically -- which may become problematic on systems that have threads or other ways of doing concurrency.

**Comment by robert-hh** [comment]
After writing, I considered the use cases. A typical application which uses the os.rename() call would/could check anyhow beforehand if the target exists, and act accordingly. Given that, the POSIX behaviour is fine.

**Comment by dpgeorge** [comment]
POSIX behaviour for rename() was implemented in b7df3e541a49a1cb72862c4015b6a883a63e1e29.

Small caveat: renaming a directory to an existing file will give an error for POSIX but will succeed for the vfs fatfs implementation.  It would require an additional stat (of the old directory) to fix this and I don't think it's worth it.
