### ISSUE TITLE
Need to work out license of STM libraries

### ISSUE THREAD

**Issue by dpgeorge** [micropython/micropython#26]
The code in stm/lib comes from the STM32F4xx standard peripheral library, v1.1.0.  I'm not sure about the license for this, and whether or not we can have it in the repo.  Need to work out the situation, and how to deal with this.

**Comment by jonnor** [comment]
Is this still an issue? There seems to be pretty clear copyright/license headers for STMicroelectronics in the relevant parts of the code in the MicroPython repository?

**Comment by dpgeorge** [comment]
> There seems to be pretty clear copyright/license headers for STMicroelectronics in the relevant parts of the code in the MicroPython repository?

Yes you're right.  And we now have the non-MIT licenses of all third party code listed in the top-level LICENSE file as a notice for all users.
