### ISSUE TITLE
Using an alternate interface for HID ?

### ISSUE THREAD

**Issue by iabdalkader** [micropython/micropython#260]
I needed a third (4th?) interface for my project, but there not enough endpoints for that, so I used an alternate vendor-specific interface with MSC, just got this working, and I thought we could use the same technique for MSC/HID ? this way you won't need to recompile to switch HID... I can send a patch if you like..

**Comment by bowman85** [comment]
Could you, please, share a project CDC+HID mode?

**Comment by dpgeorge** [comment]
This can be closed: stmhal supports dynamic selection (in boot.py) of VCP+MSC, VCP+HID or VCP only.
