### ISSUE TITLE
esp8266 build error

### ISSUE THREAD

**Issue by skylin008** [micropython/micropython#2606]
Today I build the esp8266 latest version firmware,but something error shows as below:

    skylin008@skylin008:/opt/micropython/esp8266$ make
Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
make: *** No rule to make target `lib/berkeley-db-1.xx/btree/bt_close.c', needed by `build/genhdr/qstr.i.last'.  Stop.

How to solve this issue ,Thank you very much!

**Comment by dpgeorge** [comment]
Usual things to try are: 1) run "make clean" first; 2) make sure you have latest version of esp-open-sdk; 3) make sure you did "git submodule update --init" recently.

**Comment by skylin008** [comment]
@dpeorge Thanks ，I will be check it out !
