### ISSUE TITLE
Too broad package reference in ImportError on importing submodule

### ISSUE THREAD

**Issue by markshannon** [micropython/micropython#2609]
The error message when importing a submodule that does not exist, incorrectly states that the containing package does not exist.

On the BBC micro:bit
```python
>>> import microbit
>>> microbit
<module 'microbit'>
>>> import microbit.lemon.jelly
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: no module named 'microbit'
```
Original issue:
https://github.com/bbcmicrobit/micropython/issues/290

**Comment by dpgeorge** [comment]
It looks like this was improved (fixed?) in a7fa18c203a241f670f12ab507aa8b349fcd45a1.

Eg you now get:
```python
$ micropython
MicroPython v1.19.1 on 2022-06-17; linux [GCC 11.2.0] version
Use Ctrl-D to exit, Ctrl-E for paste mode
>>> import sys
>>> import sys.lemon
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: no module named 'sys.lemon'
```
I think that's a good enough error message for MicroPython.
