### ISSUE TITLE
docs: Restructure TOC and review article links.

### ISSUE THREAD

**Issue by hosaka** [micropython/micropython#2619]
It would be a good opportunity with the current docs work, to review the structure of table of contents. It has been noted that the nav bar contains duplicates (https://github.com/micropython/micropython/issues/2578#issuecomment-259054477), hard to read/navigate, with some pages being difficult to find:

![capture](https://cloud.githubusercontent.com/assets/171876/20214143/2849c76e-a804-11e6-9c4a-d736831d8a6a.PNG)

I propose having the top level looking something along the lines of:

- Quick Reference
- General Information
- Tutorials
- Libraries
- Hardware
- Datasheets
- License
- Contents

Menu items themselves do not need to add pyboard/esp8266/etc into the menus or article titles. The "Ports and Versions" menu is a good indicator of what's currently being viewed.

**Comment by pfalcon** [comment]
https://github.com/micropython/micropython/issues/2578 contains more comments on this issue.

**Comment by pfalcon** [comment]
This should be fixed by now. If there're more issues/idea, please open separate ticket(s). (Like e.g. https://github.com/micropython/micropython/issues/3188)
