### ISSUE TITLE
add an attribute machine.device to identify device type

### ISSUE THREAD

**Issue by nupha** [micropython/micropython#2636]
Suppose to add an attribute machine.device to identify device type. For example, mp compiled for esp8266 would have a string of "esp8266", pyboard may be "payboard", "" for unkown device. So it's possible to write code like this:

if machine.device=="esp8266":
    # import some thing, do something
elif machine.device=="pyboard":
    # import some thing else, do something else

**Comment by dhylands** [comment]
You can use os.uname().sysname as well as some other stuff in os.uname().

**Comment by dpgeorge** [comment]
Yes, this feature is already available via os.uname(), and also sys.platform.
