### ISSUE TITLE
Docs do not list the set_pull methods

### ISSUE THREAD

**Issue by whaleygeek** [micropython/micropython#2671]
The docs here: 

https://microbit-micropython.readthedocs.io/en/latest/pin.html#pin-functions 

do not list the set_pull() method.

From python-microbit mailing list...

Hi David,

Looking at the code the default pull states seem to be:

read_analog: configured by mbed analogin_init() function, looks like
there is no pull
read_digital: PULL_DOWN
is_touched: PULL_UP

To change the value, use: pin.set_pull(pin.PULL_UP), or PULL_DOWN or NO_PULL.

**Comment by dpgeorge** [comment]
Wrong repo!  I reposted this issue at the correct one: https://github.com/bbcmicrobit/micropython/issues/381
