### ISSUE TITLE
MPY version of __init__.py in a package doesn't make its globals available on import

### ISSUE THREAD

**Issue by tdicola** [micropython/micropython#2680]
I noticed an odd thing when making a package and trying to optimize it with .mpy versions of the source.  It appears if a package's \_\_init\_\_.py is turned into an \_\_init\_\_.mpy the package 'works' and lets you reference submodules, but none of the globals in the \_\_init\_\_.mpy are available when importing the top level package.

This is in contrast to leaving \_\_init\_\_.py as pure python source code where the package import has all the expected globals.  

Not sure this is really supported right now but wanted to check since the behavior is inconsistent.

Here's a toy example, create these files:
- /foo
- /foo/\_\_init\_\_.py with:
  ```
  from foo.bar import bar
  FOO = 'foo'
  ```
- /foo/bar.py with:
  ```
  def bar():
      print('bar')
  ```

Use mpy-cross to turn both \_\_init\_\_.py and bar.py into .mpy files and put them in the same structure (remove the .py files of course).  Then try the following:
```
>>> import foo
>>> dir(foo)
['__name__', '__path__']
>>> 
```
Notice FOO and bar are not in the foo package namespace that was imported.

Now change \_\_init\_\_.mpy back to its \_\_init\_\_.py source (you can leave bar.mpy alone) and try the same code:
```
>>> import foo
>>> dir(foo)
['__path__', 'bar', '__name__', 'FOO']
>>> 
```
Notice FOO and bar are in the foo package namespace as expected.

**Comment by dpgeorge** [comment]
Thanks for the report!  Should be fixed by d9047d3c8a99603884db25076c37778f50633ca6.
