### ISSUE TITLE
Hi I am using Micro python to OTA updates on cc3200 device i am getting error at telnet login

### ISSUE THREAD

**Issue by theja0473** [micropython/micropython#2698]
![screenshot from 2016-12-19 12-13-07](https://cloud.githubusercontent.com/assets/15976291/21303492/c373720a-c5e4-11e6-8a34-52e311c9ba68.png)
![screenshot from 2016-12-16 17-44-22](https://cloud.githubusercontent.com/assets/15976291/21303493/c3759c10-c5e4-11e6-83cb-87d5281be630.png)

What might be the error shows did any one got this kind of error.

**Comment by dpgeorge** [comment]
Using `make deploy` in the cc3200 directory requires Python 3.4 or greater.  If you have python3 installed then change line 1 of cc3200/tools/update-wipy.py to have `python3` at the end of the line instead of `python`.

**Comment by pfalcon** [comment]
Hopefully the above cleared the matter. If not, please reopen, providing detailed info about your environment.
