### ISSUE TITLE
esp8266: Remove code for flash size fix up from flashbdev.py

### ISSUE THREAD

**Issue by pfalcon** [micropython/micropython#2743]
Since previous release, the flash size in firmware header must be already set right on the first flash, and it no longer makes sense to fix up it afterwards. So, corresponding code should be removed from flashbdev.py.

@dpgeorge , let me know if we should do that for https://github.com/micropython/micropython/issues/2735

**Comment by dpgeorge** [comment]
> let me know if we should do that for #2735

Yes, please.  Makes sense.

**Comment by pfalcon** [comment]
Done in 4a72294d7d494ae3231e7bad74f57baaa4da088c.
