### ISSUE TITLE
UNIX build on RPi3:  'ASM_ARM_PASS_EMIT' undeclared 

### ISSUE THREAD

**Issue by chipcad** [micropython/micropython#2748]
Building UNIX version on RPi3 I get this error:

../py/asmarm.c:42:26: error: 'ASM_ARM_PASS_EMIT' undeclared (first use in this function)

Béla

**Comment by dpgeorge** [comment]
Thanks for the report, it's been fixed in 3f9c45efd126810cb30986cc4a4f49c2baa62caf.
