### ISSUE TITLE
ESP8266: Socket usage

### ISSUE THREAD

**Issue by ThomasRgbg** [micropython/micropython#2754]
Hi, 

is it possible after a socket.connect() to detect, if the connection was successful ? 

Kind regards, Thomas

**Comment by robert-hh** [comment]
Hello @ThomasRgbg, this is a good question asked in the forum http://forum.micropython.org/. 
Besides that, if socket.connect() returns, the connection is made and the socket object is updated accordingly. In case of timeout or interrupt, an exception is raised (see https://docs.python.org/3/library/socket.html#socket.socket.connect).

**Comment by ThomasRgbg** [comment]
Ok, thanks!
