### ISSUE TITLE
py: object base class doesn't implement __setattr__ and __delattr__

### ISSUE THREAD

**Issue by dmazzella** [micropython/micropython#2755]
I'm working on implementing object .__ setattr__ and object .__ delattr__ with this modification:

```
diff --git "a/C:\\Users\\DMAZZE~1\\AppData\\Local\\Temp\\TortoiseGit\\objA8D6.tmp\\objobject-3f5a5e5-left.c" "b/C:\\msys64_micropython\\home\\dmazzella\\micropython_dmazzella\\py\\objobject.c"
index b33dc49..48d4919 100644
--- "a/C:\\Users\\DMAZZE~1\\AppData\\Local\\Temp\\TortoiseGit\\objA8D6.tmp\\objobject-3f5a5e5-left.c"
+++ "b/C:\\msys64_micropython\\home\\dmazzella\\micropython_dmazzella\\py\\objobject.c"
@@ -59,13 +59,47 @@ STATIC mp_obj_t object___new__(mp_obj_t cls) {
 STATIC MP_DEFINE_CONST_FUN_OBJ_1(object___new___fun_obj, object___new__);
 STATIC MP_DEFINE_CONST_STATICMETHOD_OBJ(object___new___obj, MP_ROM_PTR(&object___new___fun_obj));
 
+#if MICROPY_PY_OBJECT_METHODS_DELATTRS_SETATTRS
+STATIC mp_obj_t object___setattr__(mp_obj_t self_in, mp_obj_t attr_in, mp_obj_t value) {
+    mp_obj_instance_t *self = MP_OBJ_TO_PTR(self_in);
+    mp_map_lookup(&self->members, MP_OBJ_NEW_QSTR(mp_obj_str_get_qstr(attr_in)), MP_MAP_LOOKUP_ADD_IF_NOT_FOUND)->value = value;
+    return mp_const_none;
+}
+MP_DEFINE_CONST_FUN_OBJ_3(object___setattr___obj, object___setattr__);
+
+STATIC mp_obj_t object___getattribute__(mp_obj_t self_in, mp_obj_t attr_in) {
+    mp_obj_instance_t *self = MP_OBJ_TO_PTR(self_in);
+    qstr attr = mp_obj_str_get_qstr(attr_in);
+    // check if exists into locals_dict and return its value
+    // if this fails to load the requested attr, we raise attribute error
+    mp_map_elem_t *elem = mp_map_lookup(&self->members, MP_OBJ_NEW_QSTR(attr), MP_MAP_LOOKUP);
+    if (elem == NULL) {
+        nlr_raise(mp_obj_new_exception_msg_varg(&mp_type_AttributeError,
+            "'%s' object has no attribute '%q'",
+            mp_obj_get_type_str(self_in), attr));
+    }
+    return elem->value;
+}
+MP_DEFINE_CONST_FUN_OBJ_2(object___getattribute___obj, object___getattribute__);
+
+STATIC mp_obj_t object___delattr__(mp_obj_t self_in, mp_obj_t attr_in) {
+    mp_obj_instance_t *self = MP_OBJ_TO_PTR(self_in);
+    mp_map_lookup(&self->members, MP_OBJ_NEW_QSTR(mp_obj_str_get_qstr(attr_in)), MP_MAP_LOOKUP_REMOVE_IF_FOUND);
+    return mp_const_none;
+}
+MP_DEFINE_CONST_FUN_OBJ_2(object___delattr___obj, object___delattr__);
+#endif
+
 STATIC const mp_rom_map_elem_t object_locals_dict_table[] = {
     #if MICROPY_CPYTHON_COMPAT
     { MP_ROM_QSTR(MP_QSTR___init__), MP_ROM_PTR(&object___init___obj) },
-    #endif
-    #if MICROPY_CPYTHON_COMPAT
     { MP_ROM_QSTR(MP_QSTR___new__), MP_ROM_PTR(&object___new___obj) },
     #endif
+    #if (MICROPY_CPYTHON_COMPAT && MICROPY_PY_OBJECT_METHODS_DELATTRS_SETATTRS)
+    { MP_ROM_QSTR(MP_QSTR___delattr__), MP_ROM_PTR(&object___delattr___obj) },
+    { MP_ROM_QSTR(MP_QSTR___getattribute__), MP_ROM_PTR(&object___getattribute___obj) },
+    { MP_ROM_QSTR(MP_QSTR___setattr__), MP_ROM_PTR(&object___setattr___obj) },
+    #endif
 };
 
 STATIC MP_DEFINE_CONST_DICT(object_locals_dict, object_locals_dict_table);
```

and a new macro `#define MICROPY_PY_OBJECT_METHODS_DELATTRS_SETATTRS (1)` into unix/mpconfigport.h

using this code:

```
class DER(object):

    def __init__(self, typeid=0, classid=0, indefinite=0, value=b''):
        object.__setattr__(self, "_value", value)

der = DER()
der.c = 2
print(der.c)
```

i have this results:

```
dma@dma-pc MSYS ~/micropython/unix
$ ./micropython ../tests/basics/object__setattr__.py
Traceback (most recent call last):
  File "../tests/basics/object__setattr__.py", line 12, in <module>
  File "../tests/basics/object__setattr__.py", line 6, in __init__
TypeError: argument should be a 'object' not a 'DER'

dma@dma-pc MSYS ~/micropython/unix
$ python3 -B ../tests/basics/object__setattr__.py
2
```

the problem is into [runtime.c](https://github.com/micropython/micropython/blob/master/py/runtime.c#L935
), the solution can be add this check:

```
if (arg0_type != self->type
            #if MICROPY_PY_OBJECT_METHODS_DELATTRS_SETATTRS
            && !mp_obj_is_subclass_fast(MP_OBJ_FROM_PTR(arg0_type), MP_OBJ_FROM_PTR(&mp_type_object))
            #endif
            ) { ...
```

is the correct solution for this?

**Comment by pfalcon** [comment]
Which leads to a question - what's the purpose of all these changes? https://github.com/micropython/micropython/pull/2753, this, and more, because it won't stop here of course. Is it to make MicroPython better, or to run that funkily implemented "DER" class?

At the same time, this situation was well described couple of years ago in https://github.com/micropython/micropython/wiki/ContributorGuidelines#django-criteria . Let me quote it for you:

> If you port existing code, you'll likely find out that a lot of features missing, so adding all of them will be a lot of work, and will bloat MicroPython, and adding just one of few won't make a big difference. (So, just keep porting, by patching existing code to use facilities MicroPython already provides.)

@dmazzella , can you please explain why instead of following that advice, you choose to patch MicroPython?

**Comment by dmazzella** [comment]
the purpose of all these changes is split #2689

**Comment by dmazzella** [comment]
if i add this check to [runtime.c](https://github.com/micropython/micropython/blob/master/py/runtime.c#L935):

```
if (arg0_type != self->type
            #if MICROPY_PY_OBJECT_METHODS_DELATTRS_SETATTRS
            && !mp_obj_is_subclass_fast(MP_OBJ_FROM_PTR(arg0_type), MP_OBJ_FROM_PTR(&mp_type_object))
            #endif
            ) { ...
```

but not directly subclass "object":

```
>>> class A:
...     pass
...
...
...
>>> a = A()
>>> object.__setattr__(a, "a", 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: argument should be a 'object' not a 'A'
>>>
```

with subclass:

```
>>> class A(object):
...     pass
...
...
...
>>> a = A()
>>> object.__setattr__(a, "a", 1)
1
>>>
```

Any reason for this?

**Comment by dmazzella** [comment]
if i add this check to [objtype.c](https://github.com/micropython/micropython/blob/master/py/objtype.c#L901):

```
    #if MICROPY_PY_OBJECT_METHODS_DELATTRS_SETATTRS
    if (len == 0) {
        // if it does not inherit from any type, replace 'bases_tuple' 
        // with a tuple containing one element of type 'object'
        STATIC const mp_rom_obj_tuple_t type_base_tuple = {{&mp_type_tuple}, 1, {MP_ROM_PTR(&mp_type_object)}};
        bases_tuple = MP_OBJ_FROM_PTR(&type_base_tuple);
    }
    #endif
```

and add this to [runtime.c](https://github.com/micropython/micropython/blob/master/py/runtime.c#L935
):

```
    if (arg0_type != self->type
        #if MICROPY_PY_OBJECT_METHODS_DELATTRS_SETATTRS
        && !mp_obj_is_subclass_fast(MP_OBJ_FROM_PTR(arg0_type), MP_OBJ_FROM_PTR(&mp_type_object))
        #endif
        ) { ...
```

the result are:

for cPy

```
>>> class A:
...     pass
...
>>> a = A()
>>> object.__setattr__(a, "a", 1)
>>> a.a
1
>>>
```

for uPy

```
>>> class A:
...     pass
...
...
...
>>> a = A()
>>> object.__setattr__(a, "a", 1)
>>> a.a
1
>>>
```

This solution may be acceptable?

**Comment by dmazzella** [comment]
@dpgeorge any hints?

**Comment by dpgeorge** [comment]
> any hints?

No, not at this time.  This stuff is low priority, sorry.

**Comment by pfalcon** [comment]
Should this ticket still be open? "DER" type the title refers to is not part of MicroPython. Please update the title to describe the real problem if this ticket should be open.

**Comment by dpgeorge** [comment]
`__delattr__` and `__setattr__` were implemented for user defined classes in 18e65691661ef8e83060d0e72d66b16cc918c8b4.  The first script posted in this issue with the "DER" class now raises the error `AttributeError: type object 'object' has no attribute '__setattr__'` which shows the actual issue, that the base-class object doesn't support `__setattr__` (or the other related ones).

I don't know what the original intent of @dmazzella is with needing support for `object.__setattr__` but it may be that it can be achieved simply with the built-in `setattr`, like `setattr(self, "_value", value)`

**Comment by dmazzella** [comment]
> I don't know what the original intent of @dmazzella is with needing support for object.__setattr__ but it may be that it can be achieved simply with the built-in setattr, like setattr(self, "_value", value)

My initial need was support object.__setattr__

**Comment by dpgeorge** [comment]
> My initial need was support object.setattr

Ok, but is that supporting it just so it's there, or was there some code you tried that needed it, or did you write some code expecting it to be there?

**Comment by pfalcon** [comment]
Well, the original title tells the story: @dmazzella took highly bloated, unportable to MicroPython, CPython code and decided to port it. It didn't work, but instead of the usual hint to patch the Python code he started to patch MicroPython. Let me tell that again: there's no, absolutely no, need to use `__setattr__` to implement DER encoding https://en.wikipedia.org/wiki/X.690 . If some code used it for that, it's a problem of that code and not of MicroPython.

**Comment by dmazzella** [comment]
Ok, il no needs about object.__XXXattr__ i close it.

**Comment by NuclearManD** [comment]
Not sure if this is useful to anyone other than me, but I found a workaround and I thought it might as well go here since I never found the answer I needed here (or anywhere else).

A simple example to illustrate the premise:
```
>>> class test_class:
...     def __getattr__(self, n):
...         return "No, I'm here :wink:"
...         
...         
... 
>>> tst = test_class()
>>> tst.some_nonexistent_attribute
"No, I'm here :wink:"
```

I found that creating a __getattr__() function actually allows this to be done if one is clever.  I plan on using a dictionary in the object to store custom attributes that are created in __init__.  They cannot be predicted before that point, unfortunately.  I also found that setattr() does not work unless the attribute exists, so I needed this workaround.

**Comment by cdwilson** [comment]
FYI, for those coming across this in the future, this forum discussion has some ideas for working around missing `object.__setattr__` https://forum.micropython.org/viewtopic.php?f=2&t=7028

If other folks have worked around this or there are examples of better patterns to use, feel free to add to the forum discussion (I'd be interested in learning about them).
