### ISSUE TITLE
Installing external python modules 

### ISSUE THREAD

**Issue by elcapwne** [micropython/micropython#2772]
Hello everyone!

Is it possible to install external modules (other than the ones micropython supports)? i.e scapy for packet crafting.

Thank you.

**Comment by peterhinch** [comment]
This is a FAQ and should be raised in the forum rather than in the bug tracker. I suggest you read [this](https://github.com/micropython/micropython/wiki/Differences).

**Comment by pfalcon** [comment]
Another good response would be: if you're interested whether module X works with MicroPython, please ask authors/maintainers of that module, and let them know that you'd like it to run on MicroPython.

For example I, as the author of https://github.com/pfalcon/picotui module can say: yes, it works with MicroPython!
