### ISSUE TITLE
Wiki Update: Multi-threading now supported

### ISSUE THREAD

**Issue by Bucknalla** [micropython/micropython#2777]
The wiki currently states that MicroPython does **not support** multi-threading (https://github.com/micropython/micropython/wiki/Tips-and-Tricks). This is no longer corrected since PR [#2165](https://github.com/micropython/micropython/pull/2165) and the merging of the threading branch.

**Comment by pfalcon** [comment]
Removed, thanks. That's the good example why there should be less wiki rather than more wiki.
