### ISSUE TITLE
Should there be machine.bootloader() ?

### ISSUE THREAD

**Issue by pfalcon** [micropython/micropython#2779]
My current connection can't even load https://github.com/micropython/micropython/issues/1430 , so opening separate ticket. I see that machine module docs don't describe `machine.bootloader()` (as evolution of `pyb.bootloader()`). Should it be there or do we want to implement it adhoc from port to port?

**Comment by robert-hh** [comment]
For devices like the huzzah feather, where esptool switches to boot-loader state  by flipping DTR and RTS, this seems not to be urgently needed. For other devices it's helpful.

**Comment by dpgeorge** [comment]
I find it very useful for stmhal-based boards.  I use it all the time and only revert to using the BOOT0 pin if there's a problem with the firmware and I can't use machine.bootloader().

On some boards there is no bootloader (eg microbit, where an external chip is responsible for flashing the firmware) but on boards where there is one it seems like machine.bootloader() is a sensible thing to have.  It's similar to having machine.reset().

**Comment by dpgeorge** [comment]
Docs for this added in dd5c831a0b0c960b638109f1886edc10178f51a1
