### ISSUE TITLE
Coveralls problems

### ISSUE THREAD

**Issue by pfalcon** [micropython/micropython#2803]
https://coveralls.io/micropython/micropython says that is doesn't exist, and Travis is broken trying to post to it.

**Comment by dpgeorge** [comment]
I re-auth'd the github coveralls ap.  And it looks like the URL changed to: https://coveralls.io/github/micropython/micropython

**Comment by dpgeorge** [comment]
Coveralls seems to be ok now, recent PRs have been successful.
