### ISSUE TITLE
[feature] request missing readinto on socket

### ISSUE THREAD

**Issue by mhoffma** [micropython/micropython#2811]
can someone please add this feature into the system, it allows more efficient socket handling.  And it enables plain old telnet to work with dupterm.

Thanks!
 
diff --git a/extmod/modlwip.c b/extmod/modlwip.
index 62699bd..5b95d6b 100644
--- a/extmod/modlwip.c
+++ b/extmod/modlwip.c
@@ -1174,6 +1174,8 @@ STATIC const mp_map_elem_t lwip_socket_locals_dict_table[] = {
     { MP_OBJ_NEW_QSTR(MP_QSTR_read), (mp_obj_t)&mp_stream_read_obj },
     { MP_OBJ_NEW_QSTR(MP_QSTR_readline), (mp_obj_t)&mp_stream_unbuffered_readline_obj},
     { MP_OBJ_NEW_QSTR(MP_QSTR_write), (mp_obj_t)&mp_stream_write_obj },
+    { MP_OBJ_NEW_QSTR(MP_QSTR_readinto), (mp_obj_t)(&mp_stream_readinto_obj) },
+
 };
 STATIC MP_DEFINE_CONST_DICT(lwip_socket_locals_dict, lwip_socket_locals_dict_table);

**Comment by dpgeorge** [comment]
Good idea.  Added in f488fa29e485964d15f9f9dbfad5180c580e4b24.
