### ISSUE TITLE
ESP8266 - pin.irq().disable() is not available?

### ISSUE THREAD

**Issue by larsks** [micropython/micropython#2847]
The documentation suggests that one can disable an interrupt handler on a pin like this:

    mypin.irq().disable()

But at least using `v1.8.7-200-g21f0852` this method isn't available:

```
>>> p.irq().disable()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'IRQ' object has no attribute 'disable'
```

**Comment by larsks** [comment]
Apparently, I was looking at the documentation for the wipy board, rather than for the esp8266 (and the latter does not describe a `.disable` method).  Sorry for the noise.

**Comment by dpgeorge** [comment]
These inconsistencies will be cleaned up, hopefully sooner rather than later :)

**Comment by borut** [comment]
p = Pin(14, Pin.IN, Pin.PULL_UP,value=1)
p.irq(trigger=Pin.IRQ_FALLING,handler=callback)

p.Pin(14,Pin.IN)  # disables irq

**Comment by Arduous** [comment]
I am using micropython 1.9.3 on a nodemcu v3.The solution proposed by @borut did not disable the interrupts in my case
p.irq(trigger=0,handler=callback) seems to properly disable the interruptions

**Comment by rigrace** [comment]
This seems to work best so far:
Narrative:
- Initially set trigger to falling
- 'Press the button'
- IRQ fires with falling flag condition
- Within the logic for the falling flag condition AND pin.value() == 0
  - Clear the current (falling) IRQ
  - Start 'button press' stuff here
  - Sleep for XX ms
  - Set the IRQ for the opposite falling flag to be caught
  
       ...all quiet until the rising flag condition is met

- 'Release the button'
- IRQ fires with falling flag condition
- Within the logic for the falling flag condition AND pin.value() == 1
  - Clear the current (rising) IRQ
  - Start 'button release' stuff here
  - Sleep for XX ms
  - Set the IRQ for the opposite rising flag to be caught 
```
import time
from machine import Pin

class A:
    def __init__(self, _gpNum = 0, _bounceGuardMs = 100):
        print("init")
        self.gpNum = _gpNum
        self.bounceGuardMs = _bounceGuardMs
        self.button = Pin("GP{}".format(self.gpNum), mode = Pin.IN, pull = Pin.PULL_UP, value = 0)
        self.button.irq(handler = lambda pin : self.funct(self.button), trigger = Pin.IRQ_FALLING)
        self.startTimeMs = None
        self.endTimeMs = None
        print("gpNum: {}, bounceGuardMs: {}".format(self.gpNum, self.bounceGuardMs))
        
    def funct(self, pin):
        flags = pin.irq().flags()
        #print("pin: {}, pinFlags: {}".format(pin, flags))
        
        
        
        #print("Flags: {}, falling: {}, rising : {}, value: {}".format(flags, Pin.IRQ_FALLING, Pin.IRQ_RISING, pin.value()))
        if ((flags & Pin.IRQ_FALLING) and (pin.value() == 0)):
            self.button.irq(handler = None)
            print("Start fall")
            #print("Flags: {}, falling: {}, rising : {}".format(flags, Pin.IRQ_FALLING, Pin.IRQ_RISING))
                        
            time.sleep_ms(self.bounceGuardMs)
            self.button.irq(handler = lambda pin : self.funct(self.button), trigger = Pin.IRQ_RISING)
            
            print("End fall")
        elif ((flags & Pin.IRQ_RISING) and (pin.value() == 1)):
            print("Start rise")
            #print("Flags: {}, falling: {}, rising : {}".format(flags, Pin.IRQ_FALLING, Pin.IRQ_RISING))
            self.button.irq(None)
            
            time.sleep_ms(self.bounceGuardMs)
            self.button.irq(handler = lambda pin : self.funct(self.button), trigger = Pin.IRQ_FALLING)
            
            print("End rise")
        #else:
        #    print("neither fall nor rising")
        
gpNum = 0
bounceMs = 50
a = A(gpNum, bounceMs)



```
