### ISSUE TITLE
stmhal: os.stat('/') now fails with EPERM

### ISSUE THREAD

**Issue by dhylands** [micropython/micropython#2861]
Prior to 84c614e os.stat('/') returned a tuple:
```
>>> import os
>>> os.stat('/')
(16384, 0, 0, 0, 0, 0, 0, -621302400, -621302400, -621302400)
>>>
```
since 84c614e it now fails:
```
>>> import os
>>> os.stat('/')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 1] EPERM
>>> 
```

I ran into this with rshell (my automated tests fail). If failing with EPERM is the expected new behavior then I'll code around it.

**Comment by dpgeorge** [comment]
Fixed in 3625afa17362e8a2f873edeaa0856ae852c19beb, by allowing to stat the root directory.

My aim is not to break any existing behaviour on pyboard, if possible.  And it make sense to be able to stat the root dir.
