### ISSUE TITLE
ADC documentation voltage warning incorrect 

### ISSUE THREAD

**Issue by ryannathans** [micropython/micropython#2867]
On the documentation page for "class ADC" for the pyboard there is a warning that says not to exceed 1.4V where 1.8V is the absolute maximum. I cannot find any reference for this and after reviewing pyboard schematics can see the analog reference voltage is 3.3v. As a result I believe this message to be erroneous. 

Please point me to documentation explaining why using my board to measure 3v signals is damaging, my interpretation of the datasheet is that it's safe up to approximately the reference voltage.

**Comment by dpgeorge** [comment]
You're reading the docs for WiPy (and machine.ADC).  In 0c821f7def92a2f461a440c210cd5944707d4244 I made a "fix" so that the WiPy docs for machine.ADC (and machine.SD) are not included in the other ports' documentation.
