### ISSUE TITLE
Add github tags for micropython/* projects

### ISSUE THREAD

**Issue by pfalcon** [micropython/micropython#2871]
Github recently introduced "tags" for projects. It would be nice to add them to projects of micropython organization. Example of tags is https://github.com/pfalcon/picoweb , a line below project description. @dpgeorge , if you go to https://github.com/micropython/micropython or similar, you'll see "Manage topics" link. Please add at least following topics:

* for micropython/micropython - "micropython", "python", "embedded".
* micropython/micropython-lib - "micropython"

It should not take more than 30s per project. Thanks. My concern is that list https://github.com/search?q=topic%3Amicropython&type=Repositories started with the right projects.

**Comment by kamikaze** [comment]
noooo, my repo is the last one :( :D

**Comment by kfricke** [comment]
How about a snychronized tag for contributed device "drivers"?

**Comment by dpgeorge** [comment]
Ok, topics are now added.

> How about a snychronized tag for contributed device "drivers"?

Using "micropython" topic should be enough, but feel free to use "micropython-driver" if you like.
