### ISSUE TITLE
LCD160CR driver, save_to_flash malformed parameter

### ISSUE THREAD

**Issue by chuckbook** [micropython/micropython#2901]
In lcd160cr.py line:
`self._fcmd2('<BBB', 0x66, 'n')`
should read:
`self._fcmd2('<BBB', 0x66, 0x6e)`
or
`self._send(b'\x02fn')`

**Comment by dpgeorge** [comment]
Thanks, fixed in 8400d0461d3bb444f10242c82c5c44d4d7cbef16
