### ISSUE TITLE
How to update dfu firmware not short connect the boot1

### ISSUE THREAD

**Issue by skylin008** [micropython/micropython#2912]
Hello, every one ! How to update the dfu firmware not via the shot connect boot1 ,but from press user key!Thanks !

**Comment by dhylands** [comment]
This is more appropriate as a question on the forum.

There are only 2 ways to get into DFU mode (I'm assuming that you're talking about an STM32 board)
1 - issue pyb.bootloader() command
2 - Connect DFU pin (BOOT0) to 3.3v and RESET.

**Comment by dpgeorge** [comment]
As @dhylands says, the only way to do it without using BOOT0 is to call pyb.bootloader().  If you wanted to add a user switch yourself that enters DFU then you can write a small bit of Python to execute pyb.bootloader() when the button is pressed.
