### ISSUE TITLE
mpy-cross link error on macOS

### ISSUE THREAD

**Issue by BrendanSimon** [micropython/micropython#2941]
Got the following linker error on macOS building `mpy-cross` with commit `[96aa3a31]`

```
$ make -C mpy-cross
Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
LINK mpy-cross
Undefined symbols for architecture x86_64:
  "nlr_push_tail", referenced from:
      _nlr_push in nlrx64.o
     (maybe you meant: _nlr_push_tail)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [mpy-cross] Error 1
```

**Comment by dpgeorge** [comment]
Thanks for the report.  @BrendanSimon can you please check if #2943 fixes the problem?

**Comment by BrendanSimon** [comment]
Seems to have fixed the cross-compiler link issue, but building for the STM32F4Discovery board fails.

```
CC ../py/../lib/utils/printf.c
MPY modules/lcd160cr.py
make: *** [build-STM32F4DISC/frozen_mpy/lcd160cr.mpy] Segmentation fault: 11
```

**Comment by mcauser** [comment]
Also experiencing this on OSX 10.11.6 El Capitan.
Confirmed fixed in: https://github.com/micropython/micropython/pull/2943

**Comment by dpgeorge** [comment]
@BrendanSimon @mcauser can one (or both, for better stats) of you please post somewhere the disassembly of the mpy-cross/build/py/nlrx64.o file, using `objdump -xd <file>`?  I assume you both use 64-bit Mac.

**Comment by mcauser** [comment]
@dpgeorge I don't have objdump, but I do have gobjdump.

Using head from master branch:
https://gist.github.com/mcauser/10e5a47f516deda75c6776990fe58c24

**Comment by dpgeorge** [comment]
@mcauser thanks!  I just changed #2943 to make further fixes for Mac.  Can you please try it again?  (I push forced so you'll need to remove that branch and repull it.)

**Comment by pfalcon** [comment]
>  (I push forced so you'll need to remove that branch and repull it.)

... just to use "git pull --rebase", which should be the default command to pull anyway.

**Comment by mcauser** [comment]
https://gist.github.com/mcauser/8312a86491bddcaa262b978d632a1ecd

`./mpy-cross -v ../drivers/display/lcd160cr.py` no longer throws seg fault 11

I'll try building my stmhal board.
`make BOARD=VCC_GND_F407`
Success!

**Comment by dpgeorge** [comment]
@BrendanSimon can you please also check the latest code in #2943?

**Comment by BrendanSimon** [comment]
Yep.  The STM32F4DISCO all builds ok for me too (using arm-none-eabi-gcc v5.4.1).

**Comment by dpgeorge** [comment]
The fix has been merged to master.  Thanks guys for testing.
