### ISSUE TITLE
network configuration bug in "esp8266-20170108-v1.8.7.bin"

### ISSUE THREAD

**Issue by anpaul0615** [micropython/micropython#2944]
I found a bug about network configuration in "esp8266-20170108-v1.8.7.bin".
Please read below code.

```python
import network
softap = network.WLAN(network.AP_IF)

softap.active(True)  // I can't connect this ap 'MicroPython-xxxxxx'

softap.config('password')  //error

softap.config(password='123456789')  //now I can connect this ap
```

What is wrong?  just firmware bug?

**Comment by dpgeorge** [comment]
> softap.config('password') //error

This is supposed to raise an exception.  You can't get the password, you can only set it.

What exactly is the issue that you are reporting?

**Comment by anpaul0615** [comment]
nothing.
thank you for your help.
