### ISSUE TITLE
how  compile source code by keil,mdk or iar

### ISSUE THREAD

**Issue by fkeujjpdc** [micropython/micropython#2951]
this project is very greate,my project want use python,but my project compile by mdk,i add py floder into my project,there are many error ,such as inline,for(unsigned int i=0;   eth;
can i compile py core output lib by gcc and add the lib into mdk?
if the source code compile by mdk is perfect

**Comment by pfalcon** [comment]
The officially supported compiler is gcc. You may want to discuss portability to other compilers at the MicroPython forum, https://forum.micropython.org/viewforum.php?f=3 .
