### ISSUE TITLE
Unix string modulus operator produces incorrect result with zero argument

### ISSUE THREAD

**Issue by peterhinch** [micropython/micropython#2955]
From [this forum post](http://forum.micropython.org/viewtopic.php?f=3&t=3146)
MicroPython v1.8.1-1435-g528aeb3-dirty on 2017-02-27; linux version:
```
>>> '%+02d' % 0
'00'
>>> '%+02d' % 0
'00'
```
cPython
```
>>> '%+02d' % 0
'+0'
>>> '{:+02d}'.format(0)
'+0'
```

**Comment by dpgeorge** [comment]
Thanks for the report.  Fixed by d65371538d8ecdc64691f1c522b5b9ecc1299c7f
