### ISSUE TITLE
Confusing error message for implicit str to bytes conversion

### ISSUE THREAD

**Issue by stinos** [micropython/micropython#2957]
For example:
```
>>>b'abc'.replace('a', '')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can't convert 'str' object to str implicitly
```

**Comment by dpgeorge** [comment]
Yes, the way it's handled is that there's a generic message to say it can't convert X to a str.  In this case it's trying to convert 'a' to bytes implicitly, which can't be done, and uses the generic str error mesage for that.

**Comment by stinos** [comment]
Ok, just wanted to doublecheck the 'to str' part is by design even though it's converting to bytes

**Comment by pfalcon** [comment]
Well, let's try to look into doing something about this before closing.

**Comment by dpgeorge** [comment]
Fixed.
