### ISSUE TITLE
esp8266: soft reboot is unreliable if there are timers and interrupts at play

### ISSUE THREAD

**Issue by jcea** [micropython/micropython#2976]
Frequently when I do a soft reboot (control+d or via software "sys.exit()") of my ESP8266, if there are timers at play, the reboot if started but the ESP hangs. For Instance:

```
PYB: soft reboot
#6 ets_task(40100164, 3, 3fff8398, 4)
Traceback (most recent call last):
  File "<stdin>", line 72, in 
(the device hangs)
...
(watchdog reset after some time, ~8 seconds)
```

I think that trusting the watchdog to cover this is risky and inappropriate. Watchdog should be the last line of defense.

I think that the first step of the soft reboot should be to disable timers and ISR's.

**Comment by dpgeorge** [comment]
> I think that the first step of the soft reboot should be to disable timers and ISR's.

Yes, that will certainly help, and it would be good to make the esp8266 able to soft-reboot more reliably than it currently does.  But it may not be possible to do it in a completely clean way because of the wifi stack, which is difficult to clean up correctly.

**Comment by pfalcon** [comment]
See also https://github.com/micropython/micropython/issues/1896

**Comment by dpgeorge** [comment]
esp8266 soft-reset has improved a lot over the years, especially due to b2fa1b50edaea43007d692d24391c6f3aa4d15ca.  So I'll close this issue for now.
