### ISSUE TITLE
CI status, etc. badges in README broken

### ISSUE THREAD

**Issue by pfalcon** [micropython/micropython#2978]
I noticed that for a few days, image badges at the top of README.md are being rendered as a text. Does anybody know what's up? Did github changed their markdown syntax?

**Comment by turbinenreiter** [comment]
They are using a new implementation and it breaks some stuff apearantly.
https://github.com/blog/2333-a-formal-spec-for-github-flavored-markdown

**Comment by dpgeorge** [comment]
Should be fixed by fb139a4ba65e663aba195c4acaebe31673152dac

**Comment by pfalcon** [comment]
Thanks!
