### ISSUE TITLE
compile examples\embedding  error by cygwin 

### ISSUE THREAD

**Issue by fkeujjpdc** [micropython/micropython#2981]
make -f Makefile.upylib V=1 occur this error:
./mpconfigport.h:1:21: error：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attrib
ute__’ before ‘.’ token
 mpconfigport_minimal.h

i modify mpconfigport.h file:
`mpconfigport_minimal.h`
to
`#include"mpconfigport_minimal.h"`
then i compile success

**Comment by dpgeorge** [comment]
This is a problem with symlinks not working on cygwin, a duplicate of #2961.
