### ISSUE TITLE
wipy: i2c "readmem_into" function fault handling ignored

### ISSUE THREAD

**Issue by hoihu** [micropython/micropython#2984]
I believe I've stumbled across an issue in the I2C readmem_into implementation on the Wipy 1.

Here:
https://github.com/micropython/micropython/blob/master/cc3200/mods/pybi2c.c#L276-L281

the return value of ```pyb_i2c_mem_addr_write``` call is not handled. 

Hence, if an attached slave fails to ack in https://github.com/micropython/micropython/blob/master/cc3200/mods/pybi2c.c#L177, then the caller thinks everything is ok and the return values in the array are all zeros. 

I would expect an OSError (```mp_raise_OSError(MP_EIO)```) to be raised.

**Comment by dpgeorge** [comment]
Should be fixed by 6bfb344a808081aaaf883b7576699e05d9a86882

**Comment by hoihu** [comment]
thanks!
