### ISSUE TITLE
Having issues sending a float to and getting a float from a custom module. 

### ISSUE THREAD

**Issue by cody-hanks** [micropython/micropython#3001]
This is just a random function to make sure that I understand the process of exposing a function to the python code. 

my function is 
```
STATIC float addten(float val){
    return (float)(val +10.0);
}
STATIC MP_DEFINE_CONST_FUN_OBJ_0(addten_obj,addten);
STATIC const mp_map_elem_t globals_table[]={
     {MP_OBJ_NEW_QSTR(MP_QSTR_addten),(mp_obj_t)&addten_obj },
};
```

The error message I am seeing is, 
     ***.c:21:1: error: initialization from incompatible pointer type

I have tried with the float32_t, float, and mp_float_t for return type .... 

Any chance some one can send me in the right direction ?
If this is the wrong place to ask please let me know and I can move this somewhere else. 

Specifics, STM32F4 processor with
#include "arm_math.h"
#include "arm_const_structs.h" 
  
Eventually I would like to expose the FFT function to python using the floating point unit in the processor.

**Comment by dpgeorge** [comment]
The correct thing to do is
```c
STATIC float addten(mp_obj_t val_in){
    float val = mp_obj_float_get(val_in);
    return mp_obj_new_float(val + 10.0);
}
STATIC MP_DEFINE_CONST_FUN_OBJ_1(addten_obj,addten);
STATIC const mp_map_elem_t globals_table[]={
     {MP_OBJ_NEW_QSTR(MP_QSTR_addten),(mp_obj_t)&addten_obj },
};
```

> If this is the wrong place to ask please let me know and I can move this somewhere else.

For this kind of question, in the future please use https://forum.micropython.org

**Comment by peterhinch** [comment]
@cody-hanks For FFT you might be interested in [this](https://github.com/peterhinch/micropython-fourier).
