### ISSUE TITLE
int.from_bytes() resulting in TypeError on "esp8266-20170108-v1.8.7.bin"

### ISSUE THREAD

**Issue by DonRichie** [micropython/micropython#3008]
Hi, I am using "esp8266-20170108-v1.8.7.bin" micropython firmware on my ESP8266 12-F and trying to write code for using the bme280 sensor from Bosch.

While I tried I encountered the following behavior when I copy and try out the example for the int.from_bytes function:

```
>>> int.from_bytes(b'\xfc\x00', byteorder='big')                                                                   
Traceback (most recent call last):                                                                                 
  File "<stdin>", line 1, in <module>                                                                              
TypeError: function does not take keyword arguments  
```

I refer to the example code snippets here: 
[https://docs.python.org/3/library/stdtypes.html](https://docs.python.org/3/library/stdtypes.html)

Does somebody has an idea what I did wrong?

**Comment by dpgeorge** [comment]
You can't use the "byteorder" keyword.

To stay micro, MicroPython doesn't accept keyword arguments for the majority of the built in functions/methods.  Just using positional arguments is supported by both MicroPython and CPython, so if you do `int.from_bytes(b'\xfc\x00', 'big')` that will work with both.

For more info about differences see http://docs.micropython.org/en/latest/pyboard/genrst/index.html
