### ISSUE TITLE
call _thread.allocate_lock().release() before acquire() will make pyboard reboot

### ISSUE THREAD

**Issue by LiWeiwei-GitHub** [micropython/micropython#3045]
```
MicroPython v1.8.7 on 2017-04-26; PYBv1.0 with STM32F405RG
Type "help()" for more information.
>>> import _thread
>>> lock = _thread.allocate_lock()
>>> lock.release()
>>> lock.acquire()
```

Normal python, "lock.release()" will throw "RuntimeError" exception.

MicroPython, "lock.release()" return immediately.Then, "lock.acquire()" make pyboard reboot.

**Comment by dpgeorge** [comment]
Thanks for the report and sorry for the long delay in responding.  This is now fixed by e374cfff80c37b96b03d4438e475e405b03e6d61
