### ISSUE TITLE
there are some errors when I build it,the older version was ok.

### ISSUE THREAD

**Issue by DengQilong** [micropython/micropython#3051]
the errors are  below,I don't know why,who can help me,my email is 1303428517@qq.com.

CC ../py/../lib/utils/printf.c
MPY modules/lcd160cr.py
make: ../mpy-cross/mpy-cross: Command not found
../py/mkrules.mk:111: recipe for target 'build-NUCLEO_F767ZI/frozen_mpy/lcd160cr.mpy' failed
make: *** [build-NUCLEO_F767ZI/frozen_mpy/lcd160cr.mpy] Error 127

**Comment by dmazzella** [comment]
`
make: ../mpy-cross/mpy-cross: Command not found
`
Have you successfully build mpy-cross ?

**Comment by pfalcon** [comment]
As pointed above, you need to build mpy-cross.
