### ISSUE TITLE
tests/cpydiff/core_class_superaslocal.py no longer shows differences

### ISSUE THREAD

**Issue by pfalcon** [micropython/micropython#3059]
As can be seen at http://docs.micropython.org/en/latest/pyboard/genrst/core_language.html (grep for "when using “super” as a local"). @dpgeorge , perhaps this was fixed with super() optimization you made, or test case should be made more differentiating?

**Comment by dpgeorge** [comment]
Yes this was fixed accidentally by 5335942b599d85263d3c18eb99ff5ebd04a8bc98.

**Comment by dpgeorge** [comment]
Ok, in 084824f866af4cda42a41a16d844fa47ba3b8938 I moved the cpydiff test to the main, basics/ test dir because this feature (using super as a local) is now supported.
