### ISSUE TITLE
HTTPS request returns ssl_handshake_status -261

### ISSUE THREAD

**Issue by Kwbmm** [micropython/micropython#3070]
I'm having a bit of troubles performing a proper HTTPS GET request. I'm trying to contact a Telegram Bot through the provided APIs and I'm using [urequest.py](https://github.com/micropython/micropython-lib/blob/master/urllib.urequest/urllib/urequest.py). It looks like the issue lies at [this](https://github.com/micropython/micropython-lib/blob/master/urllib.urequest/urllib/urequest.py#L28) line of `urlopen()` function.

Code I'm using is very simple:
```python
import urequest
bot_id = "<bot_id>"
chat_id = <chat_id>

message = "This is a message".strip().replace(" ", "%20")
content = "chat_id=" + str(chat_id) + "&text=" + message
data = urequest.urlopen("https://api.telegram.org/bot" +
                        bot_id +
                        "/sendMessage",
                        content)
```
This issue may be related to micropython/micropython-lib#95 and just as @mleonard87 the [http_client_ssl - example](https://github.com/micropython/micropython/blob/master/examples/network/http_client_ssl.py) is working just fine.

**Comment by pfalcon** [comment]
Please try with the updated ussl module: https://github.com/micropython/micropython/issues/3140 . Reopen with additional details if needed.
