### ISSUE TITLE
Stale content on docs.micropython.org

### ISSUE THREAD

**Issue by riegaz** [micropython/micropython#3095]
Old and new is mixed here:

http://docs.micropython.org/en/latest/wipy/library/time.html#time.ticks_diff

**Comment by pfalcon** [comment]
@dpgeorge, please clean up dir for generated docs, page above describes itself as v.1.7.

**Comment by dpgeorge** [comment]
Ok, stale content was removed, and the docs build script that generates these pages was updated to always remove the old content before generating the new.

@riegaz where did you get that link from?  That link is no longer valid and it might be that there are some stale links out there as well.

**Comment by riegaz** [comment]
@dpgeorge It is the first result from Google when searching for "micropython time"

**Comment by dpgeorge** [comment]
Ok, thanks, hopefully their cache is updated soon.
