### ISSUE TITLE
Implementation of non-blocking I/O for modussl_mbedtls?

### ISSUE THREAD

**Issue by MrSurly** [micropython/micropython#3107]
I'm having this problem: [umqtt.simple using ssl: check_msg() throws NotImplementedError](https://github.com/micropython/micropython-lib/issues/168), which led to discovering that mbed_tls [supports non-blocking](https://tls.mbed.org/discussions/feature-request/non-blocking-calls-to-transport-layer-i-o), at least for the version included with the ESP32 IDF.

The issue seems to be that the `ussl` module is using the wrapped socket as a streaming object.  This doesn't allow the proper capture of the `EWOULDBLOCK` signal necessary to generate the `MBEDTLS_ERR_SSL_WANT_READ` and `MBEDTLS_ERR_SSL_WANT_WRITE` codes required by mbed_tls.

Proposed:
1. Extending the `stream` protocol to support timeout / blocking functions -- though this doesn't make much sense, frankly.
2. Creating a new 'socket' protocol that could be sensed by the `ussl` module, thus allowing a call to `setblocking` or `settimeout` to work correctly.  

Are the `ussl` modules intended to wrap things other than sockets?  Could they be more closely coupled if the answer is "no"?

Also: Would a PR for this be welcome if it proves feasible?

-----

####  EDIT:

I think something as simple as always returning the error code could do it.  Socket wrappers would preset `errcode` to 0; if the return value was 0 _and_ `errcode` was `EWOULDBLOCK`, then it could properly return the values expected by mbed_tls.

Old code (only showing read, write would be similar):
```c
STATIC mp_uint_t socket_stream_read(mp_obj_t self_in, void *buf, mp_uint_t size, int *errcode) {
    socket_obj_t *sock = self_in;

    // XXX Would be nicer to use RTC to handle timeouts
    for (int i=0; i<=sock->retries; i++) {
        MP_THREAD_GIL_EXIT();
        int x = lwip_recvfrom_r(sock->fd, buf, size, 0, NULL, NULL);
        MP_THREAD_GIL_ENTER();
        if (x >= 0) return x;
        if (x < 0 && errno != EWOULDBLOCK) { *errcode = errno; return MP_STREAM_ERROR; }
        check_for_exceptions();
    }
    return 0;  // causes a timeout error to be raised.
}
```

New code:

```c

STATIC mp_uint_t socket_stream_read(mp_obj_t self_in, void *buf, mp_uint_t size, int *errcode) {
    socket_obj_t *sock = self_in;

    // XXX Would be nicer to use RTC to handle timeouts
    for (int i=0; i<=sock->retries; i++) {
        MP_THREAD_GIL_EXIT();
        int x = lwip_recvfrom_r(sock->fd, buf, size, 0, NULL, NULL);
        MP_THREAD_GIL_ENTER();
        if (x >= 0) return x;

        *errcode = errno;
        if (errno != EWOULDBLOCK) {
            return MP_STREAM_ERROR;
        }
        check_for_exceptions();
    }
    return 0;  // causes a timeout error to be raised.
}
```

**Comment by dpgeorge** [comment]
The axtls implementation of ussl currently only supports blocking mode, and see #2631 for a PR that (attempts to) add non-blocking support.  You may find some ideas in that PR.

**Comment by MrSurly** [comment]
My focus is for the ESP32, which uses mbedtls. mbedtls _does_ support blocking. 

I have this working (and using in real code), but it relies on https://github.com/micropython/micropython-esp32/pull/105.

**Comment by pfalcon** [comment]
Can this be closed now? Were tests added for the implemented functionality?

**Comment by MrSurly** [comment]
>Can this be closed now?

Yes, Closing.

>Were tests added for the implemented functionality?

No.
