### ISSUE TITLE
VFS: open() does not accept encoding argument

### ISSUE THREAD

**Issue by diginfo** [micropython/micropython#3117]
This code runs under 1.8.7 but not under 1.9:

      with open('somefile.txt', 'w', encoding='utf-8') as f:
        f.write('sometext')
      
      "extra keyword arguments given"

If I remove the encoding variable then there's no error.

**Comment by dpgeorge** [comment]
Thanks for the report, this is indeed a regression with v1.9.  Note that in v1.8.7 the "encoding" arg was just ignored, so removing it won't make any difference to the behaviour of your code.  I'd recommend doing that.

**Comment by dpgeorge** [comment]
Fixed by 7ecfbb8267c050ba5bd5bdf7becfb055f53a4f80.  "encoding" still doesn't do anything but it is allowed as a kwarg.
