### ISSUE TITLE
stmhal: USB device product description is not displayed on windows

### ISSUE THREAD

**Issue by Arrowana** [micropython/micropython#3132]
The USB product description doesn't show up in windows 10.
It is currently hard to build automation because there is no way to recognise a specific pyboard without engaging any serial communication.

The functionality is present in usbd_desc.c however for some reason it does not work on windows.

The following screenshot shows that an Arduino can transmit his product description properly while the STM running micropython can't.

COM31 is a STM32F439 running micropython
![image](https://cloud.githubusercontent.com/assets/8245419/26807976/3c2d96ca-4a9d-11e7-8b39-dc0250acf2dc.png)

**Comment by dpgeorge** [comment]
This is most like because the VID/PID are not registered with the USB group, and so Windows doesn't have the VID/PID in it's database.  If you are building a product and want to have your device show up with its name then you'll need to purchase a VID and use that one.

**Comment by stinos** [comment]
I think http://pid.codes/ still has codes left, maybe get one there?

**Comment by jonnor** [comment]
MicroPython now runs on many ST devices, not just pyboard. Proposing to close this as not planned.
