### ISSUE TITLE
esp8266: Crash on ussl.wrap_socket(None)

### ISSUE THREAD

**Issue by alex-robbins** [micropython/micropython#3145]
```python
import ussl
ussl.wrap_socket(None)
```
causes a reset. Of course, callers probably shouldn't pass None here, but I assume that it isn't supposed to be possible to crash the interpreter like this (and a TypeError should be thrown instead).

On unix, the same code causes a segfault.

**Comment by dpgeorge** [comment]
Thanks for the report.  This is the same issue as #1596, that stream objects are not checked for in some places.  So we can use that issue to track it.
