### ISSUE TITLE
ussl on unix: ssl_handshake_status: -40

### ISSUE THREAD

**Issue by annejan** [micropython/micropython#3149]
I have changed my `upip` variant to take into account `server_hostname` for SNI.
`s = ussl.wrap_socket(s, server_hostname=host)`

This works perfectly on the ESP32, however on the unix variant I get `ssl_handshake_status: -40`

I have tried cleaning `axtls` and even a brand new checkout . . 

PS: I have tried the same with a host with SNI fallback to the same (sub) domain, and that works, so I'm pretty sure it could be an SNI issue.

Related to: #3140

**Comment by dpgeorge** [comment]
> This works perfectly on the ESP32

Note that ESP32 uses mbedtls, not axtls.

**Comment by annejan** [comment]
Correct . . hence me thinking it has something to do with axtls . .

The server I'm trying to connect to is badge.sha2017.org it is behind a loadbalancer and the non-SNI fallback cert is different from the requested (*.sha2017.org) wildcard . .

**Comment by pfalcon** [comment]
@annejan: Unless you have proofs that SNI is not working, it would be fair to name ticket "ussl on unix: ssl_handshake_status: -40, suspected SNI not working".

**Comment by annejan** [comment]
Working on those proofs . . 
It's unfortunately kind of hard to check deeper down currently (lots of reading up to do) . .

**Comment by pfalcon** [comment]
See https://github.com/micropython/micropython/pull/3150

**Comment by pfalcon** [comment]
> It's unfortunately kind of hard to check deeper down currently (lots of reading up to do) . .

Ack, and it's the same for everyone.

**Comment by annejan** [comment]
After attempting a long list of SNI and other domains with test script from https://github.com/micropython/micropython/pull/3150 I have come to the conclusion it's not SNI and probably something todo with the load balancer of the domain.

Closing issue. . sorry for the inconvenience!

**Comment by annejan** [comment]
Found the issue to be that `axtls` only supports TLS_RSA
<img width="525" alt="screen shot 2017-06-15 at 21 49 16" src="https://user-images.githubusercontent.com/294470/27199090-140e5d44-5215-11e7-9f9f-dba0432d00d6.png"> server only supports DHE and ECDHE

**Comment by annejan** [comment]
Unfortunately this is an issue with axtls . .
http://axtls.sourceforge.net/specifications.htm
Unsupported: Anonymous or Ephemeral DH.
