### ISSUE TITLE
esp8266 wiznet driver!

### ISSUE THREAD

**Issue by tusharvb19** [micropython/micropython#3159]
In network the wiznet driver is not present!
I want to interface wiznet5100 i.e. arduino Ethernet shield with nodemcu using micropython.
Please help me.
I have to compile the firmware with enabling the hardware???
If so what are the steps?
TIA.

**Comment by dpgeorge** [comment]
It's certainly possible to integrate the Wiznet driver into the esp8266 build, but this is out of scope of the current work that is being done.  If you want to try, have a look how it's done in stmhal and copy as much of that as possible.

I'm going to close this because it's really out of scope.
