### ISSUE TITLE
trouble building on arm-androideabi with clang

### ISSUE THREAD

**Issue by enedil** [micropython/micropython#3163]
Hello. I'm trying to get micropython runnung on Android. I have toolchain installed, clang version 4.0. However, make step fails, as shown in the log.

Here is the log

https://gist.github.com/enedil/294989beecc738868ecc480cc45526db

Sorry for not inlining it, but my terminal on this device has terrible copy/paste support.

**Comment by dpgeorge** [comment]
You should be able to just remove the offending file (nlrthumb.c) from the build, from py/py.mk.

**Comment by pfalcon** [comment]
Hopefully, the above suggestion help. Otherwise, feel free to use gcc.
