### ISSUE TITLE
Update docs markups to the latest, CPython-compatible conventions

### ISSUE THREAD

**Issue by pfalcon** [micropython/micropython#3172]
Per e92602ba27915041ecb321b770bec9a37610201c . Number of docs are already converted (7f2bc83dbc8542e75280e2eb6a918387c459ec2f, 7c0e1f1a08949920ede272ae4ac7120ee8a77bc6, etc.)

**Comment by pfalcon** [comment]
This in WIP and I'm on it.

**Comment by dpgeorge** [comment]
Most of the docs now use the latest markup, and the CODECONVENTIONS.md file describes the conventions to use.
