### ISSUE TITLE
"CPython diffs" docs is not generated properly on docs.micropython.org 

### ISSUE THREAD

**Issue by pfalcon** [micropython/micropython#3191]
See e.g. http://docs.micropython.org/en/latest/esp8266/genrst/modules.html#deque :
~~~
/bin/sh: ../unix/micropython: No such file or directory
~~~

**Comment by dpgeorge** [comment]
Now fixed.  The problem was a stale version of libaxtls.a, not being rebuilt even after "git submodule update" and an explicit "make axtls".  This dependency stuff really needs fixing.
