### ISSUE TITLE
Cannot change GPIO value

### ISSUE THREAD

**Issue by capriele** [micropython/micropython#3194]
Hi,
I'd like to change the value of a GPIO pin (on NUCLEO_F429ZI) connected to a led. I've tried different method on different pins. In particular the following code is working
`pyb.Pin(pyb.Pin.cpu.B0,pyb.Pin.OUT).on()`
istead this one is NOT working
`pyb.Pin(pyb.Pin.cpu.B14,pyb.Pin.OUT).on()`

Is this problem related to the fact that the UART_REPL is equal to PYB_UART_3? (On this board PB14 has the function of USART3_RTS). However if I write a simple program using mbed this led (LED3) is fully working.

When I start the board the P_B14 has this value:
`>>> pyb.Pin.cpu.B14`
`Pin(Pin.cpu.B14, mode=Pin.ALT, af=12)`

Thanks to all!

**Comment by dpgeorge** [comment]
af=12 means that the pin is configured for USB D-.  I'm not familiar with this particular NUCLEO board but perhaps it has 2 USB connectors, and it looks like the HS one is configured to have serial IO on it.

**Comment by capriele** [comment]
Ok is there a way to change this configuration?

**Comment by capriele** [comment]
I've fixed this behaviour in this way: 

- I've commented out `//#define USE_USB_HS` and `//#define USE_USB_HS_IN_FS`
- I've defined `#define USE_USB_FS`
inside `stm32f4xx_hal_conf.h`

**Comment by dpgeorge** [comment]
Ok, it looks like this dev board only has the USB connector on the FS peripheral, so I changed it's config in d5ec46ace4bdd0fa3b2ca45371f537259f07a6f2
