### ISSUE TITLE
mpy-cross build error with macos 10.12.5 & clang 802.0.42

### ISSUE THREAD

**Issue by ashareye** [micropython/micropython#3196]
I got error messages when building mpy-cross with macos 10.12.5 & clang 802.0.42

Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
Traceback (most recent call last):
  File "../py/makeversionhdr.py", line 107, in <module>
    make_version_header(sys.argv[1])
  File "../py/makeversionhdr.py", line 77, in make_version_header
    git_tag, git_hash, ver = info
TypeError: 'NoneType' object is not iterable
make: *** [build/genhdr/mpversion.h] Error 1

**Comment by ashareye** [comment]
I tried using "make V = 1", but still the same result

**Comment by dpgeorge** [comment]
Thanks for the report, should be fixed by b51919f5b757ee6409f97b93c0f0a8bec84f55ad

**Comment by ashareye** [comment]
ths for the quick reply & fixing, its ok now!
