### ISSUE TITLE
HID on ESP8266 please?

### ISSUE THREAD

**Issue by idesignstuff** [micropython/micropython#3251]
How hard is it to port the PYB HID module for ESP8266 boards?

I'm using Wemos D1 Mini, and Micropython has been fun to start learning on.

I'd really like to be able to plug my Wemos into a Win/Mac/Linux usb port, and send keystrokes and/or mouse inputs via HID. Mass storage would be nice as well.
 Then the wifi can be where I go to configure what the functions will be for each physical button wired up to the Wemos board...

**Comment by peterhinch** [comment]
This is really a topic for the [forum](https://forum.micropython.org/) rather than the bug tracker. Mass storage can be done via the official `sdcard.py` module (in the source tree under drivers/sdcard).

**Comment by idesignstuff** [comment]
Ok thanks.

**Comment by mattytrentini** [comment]
As discussed in the [HID library/module for ESP8266](https://forum.micropython.org/viewtopic.php?f=16&t=3640) forum post, porting the PyBoard's HID to the ESP8266 isn't possible without extra hardware (or, while _technically possible_ it's not a great idea!).  

Suggest closing this issue?

**Comment by idesignstuff** [comment]
Yes. Fair enough.



Christian

**Comment by mattytrentini** [comment]
Thanks @idesignstuff.
