### ISSUE TITLE
Q: How to use the pyboard bitmask constants module?

### ISSUE THREAD

**Issue by franzhollerer** [micropython/micropython#3261]
I would like to use the following constants in a python script:

http://wiki.micropython.org/platforms/boards/pyboard/stm-opmasks-rcc

Which module need I to import? Can please someone provide an example

**Comment by franzhollerer** [comment]
supplement. I would like to use this constants to reset the SPI1 peripheral device.

**Comment by dpgeorge** [comment]
> Which module need I to import?

You can use the stm module: `import stm` and then something like `stm.mem32[stm.RCC + stm.RCC_AHB1RSTR] |= 0x10` (that's a dummy example).

In general these kinds of questions are best asked at the https://forum.micropython.org

**Comment by franzhollerer** [comment]
@dpgeorge I have seen that. My question is how to use the constants defined here:

http://wiki.micropython.org/platforms/boards/pyboard/stm-opmasks-rcc

What I would like to do is something like this:

stm.mem32[stm.RCC + stm.RCC_APB2RSTR] |= stm.RCC_APB2RSTR_SPI1RST

But I failed to fiugre out how to access RCC_APB2RSTR_SPI1RST.

**Comment by franzhollerer** [comment]
> In general these kinds of questions are best asked at the https://forum.micropython.org

Sorry, I have overlooked this forum. Will use it next time.

**Comment by dpgeorge** [comment]
> But I failed to fiugre out how to access RCC_APB2RSTR_SPI1RST.

I see.  Those bit-level constants are not provided in the MicroPython build, mainly because there are so many of them.  If you need them then please either define them in your script, or just use the raw values in the code.
