### ISSUE TITLE
wget on macOS is broken for upip_bootstrap.sh script

### ISSUE THREAD

**Issue by boneskull** [micropython/micropython#3263]
`wget` (on macOS, installed via Homebrew) doesn't want to grab the tarball off of pypi.

I don't quite understand the necessity of downloading the tarball when the upip scripts are actually in the `tools/` dir... perhaps it should be removed?

**Comment by pfalcon** [comment]
Update the title to correspond to the bug report content.

**Comment by pfalcon** [comment]
@dpgeorge : What's your stance on tools/upip_bootstrap.sh script? On one hand, we now ship upip builtin, so could remove that bootstrap script. On the other hand, builtin upip is just one possible configuration (even if one that was made default). So, there's nothing wrong with building upy without frozen upip, and then bootstrapping it separately (and the script serves as a good executable documentation).

**Comment by boneskull** [comment]
my 2c: pick one way and go with it, because it's kind of confusing otherwise

**Comment by pfalcon** [comment]
The "one way" is described in the README, so there's little chance to be confused. And developer tools are developers tools, and serve their own purpose.

**Comment by boneskull** [comment]
if there was little chance to be confused I wouldn't have posted the issue 😐

**Comment by dpgeorge** [comment]
> What's your stance on tools/upip_bootstrap.sh script?

As @boneskull points out, the upip code is available in tools/ so a much simpler bootstrapping would be to just copy out those files to the relevant installation directory.  And such a bootstrapping is even relevant to bare-metal, by installing to the device.

So I'd have slight preference to remove bootstrap_upip.sh.

**Comment by dpgeorge** [comment]
`bootstrap_upip.sh` was removed in c2b5bfcc0c6648f549af215f3d2f47302e962c96
