### ISSUE TITLE
Prepare for release v1.9.2

### ISSUE THREAD

**Issue by pfalcon** [micropython/micropython#3270]
A couple of months went past the 1.9.1, there're few useful changes and bugfixes accumulated, the season change is ahead, so I guess it would be a good idea to release what we have.

**Comment by pfalcon** [comment]
Sounds good, thanks!

**Comment by dpgeorge** [comment]
Tagged in 1f78e7a43130acfa4bedf16c1007a1b0f37c75c3, and esp-extra-scripts branch updated (and force pushed).
