### ISSUE TITLE
cut & paste into repl swallows '-'

### ISSUE THREAD

**Issue by fluffymcpuffin** [micropython/micropython#3278]
MicroPython v1.9.1-399-g40ae6724 running on an ESP32
when i cut 10/5 - 20/10 from my editor and paste it into repl all is good.
but when i cut (x/5) – (y/10) and paste it into repl the minus sign has dissapeared.
all works well under python3 in terminal mode.

MicroPython v1.9.1-399-g40ae6724 on 2017-08-15; ESP32 module with ESP32
>>> x,y = 10,20
>>> 10/5 - 20/10
0.0
>>> (x/5)  (y/10)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'float' object is not callable
>>>

**Comment by pfalcon** [comment]
> but when i cut (x/5) – (y/10) 

This isn't a minus sign, but some other, non-ascii character.

**Comment by robert-hh** [comment]
And Python3 in terminal mode complains too:
```
  File "<stdin>", line 1
    (x/5) – (y/10)
          ^
SyntaxError: invalid syntax
```

**Comment by fluffymcpuffin** [comment]
hi robert,

you are absolutely right, thanks for you response....
you guys are great,
so long
juergen
