### ISSUE TITLE
We're very happy to use MicroPython!

### ISSUE THREAD

**Issue by Ecco** [micropython/micropython#3288]
Hi everyone,

We just wanted to let you know we've built a new graphing calculator called [NumWorks](https://www.numworks.com/), and it embeds MicroPython!

If you're curious (and I'm sure you guys are), we've put online a page that gives a lot of [internal details](https://www.numworks.com/resources/engineering/).

Thanks a lot for building such a nice engine!

**Comment by dpgeorge** [comment]
@Ecco thanks very much, and good to hear what you are using MicroPython for!

If you like, please post about the calculator at https://forum.micropython.org
