### ISSUE TITLE
BrainPad micropython PWM

### ISSUE THREAD

**Issue by VictorDuma** [micropython/micropython#3303]
Hi, everyone! I am a newer with micropython and need help now. My board is BrainPad from GHI electronics. When I try run machine.PWM, according to micropython manual it raises exception File "", line 1, in 
AttributeError: 'module' object has no attribute 'PWM'. Who is familiar with that or have an idea, please, help me!

**Comment by peterhinch** [comment]
I see your question has been resolved on the forum, which is the best place to raise such queries.
