### ISSUE TITLE
how to use Pin.init

### ISSUE THREAD

**Issue by L-eeX** [micropython/micropython#3315]
Pin.init（mode = -1，pull = -1，*，value，drive，alt ）
how I can understand the Third parameter,about the '*'?

**Comment by LiWeiwei-GitHub** [comment]
This may be what you need: http://docs.micropython.org/en/latest/pyboard/library/pyb.Pin.html.

**Comment by dpgeorge** [comment]
> how I can understand the Third parameter,about the '<star>'?

The star in the parameter list is used to indicate that all following parameters can only be specified via a keyword.  Eg: `pin.init(pin.OUT, value=1)`.  It's standard Python as explained for example here: https://www.safaribooksonline.com/library/view/python-cookbook-3rd/9781449357337/ch07s02.html
