### ISSUE TITLE
Add EINTR to uerrno module?

### ISSUE THREAD

**Issue by dlech** [micropython/micropython#3327]
This error is common on Unix platforms. Just wanted to ask if it would be worth adding to the uerrno module before submitting a pull request. `EINTR` already is available via the errno module in micropython-lib.

**Comment by pfalcon** [comment]
There're ~200 errors common on Unix platforms. Please read https://github.com/micropython/micropython/wiki/ContributorGuidelines and feel free to provide arguments why EINTR is unavoidable useful (especially that in upstream Python 3.6 users would never see it).

**Comment by dlech** [comment]
Since pretty much all system calls can be interrupted by a signal which results in this error, it seems more common than the others. Since I can use errno micropython-lib, this isn't a blocker for me, but I just wanted to through it out there to see if anyone else had a need too. If I'm the only one, then there isn't really a compelling reason to add it.

**Comment by pfalcon** [comment]
> Since I can use errno micropython-lib

That's the recommended way indeed.

**Comment by dpgeorge** [comment]
Ideally EINTR wouldn't filter through because of PEP 475 (which isn't yet implemented in uPy).  See #1329 and #3268 for further reading.

**Comment by dlech** [comment]
Thanks. In that case, I'm closing in favor of #3268 / PEP 475.

**Comment by dlech** [comment]
PEP 475 implemented in #5723
