### ISSUE TITLE
esp.socket not found

### ISSUE THREAD

**Issue by ashareye** [micropython/micropython#3337]
hi

I found the using of esp.socket as web server in [issue 1237](https://github.com/micropython/micropython/issues/1237) & [this article](https://learn.adafruit.com/building-and-running-micropython-on-the-esp8266/micropython-usage), but when I import esp with esp8266, I could not find esp.socket. I know usocket and socket, but the network example is in blocking mode, how can I use non-blocking mode and callback like what esp.socket does with "onconnect" or "onrecv" callback?

thank you

**Comment by pfalcon** [comment]
There's no esp.socket(). You may want to contact author(s) of the article above to let them know that their article contains outdated information. For up to date information, check http://docs.micropython.org/en/latest/esp8266/ regularly.
