### ISSUE TITLE
upip broken by str.rstrip() fix

### ISSUE THREAD

**Issue by pierredaye** [micropython/micropython#3339]
Hello,

I work a lot with regular full python and I decided a couple of weeks ago to by a wipy-2.0 board. For my project, I want to port an existing python library to micropython (SoCo). Therefore, I cloned the master branch more than a month ago, compiled and started to work on the project. I finally got time to come back to this project. As usual, I did a git pull origin master to get any changes on the repo. From there, I can not use upip anymore.
I cloned the master branch of micropython today (09/29/2017), I could compile it without any issue but when I try to install any lib, I have the following error:
> ./micropython -m upip install micropython-urequests
Installing to: /home/______/.micropython/lib/
Warning: pypi.python.org SSL certificate is not validated
Installing micropython-urequests 0.5 from https://pypi.python.org/packages/86/e3/20181791776d0735c5b0de4bd1b91091f224af00726f1baf555f69f5bc61/micropython-urequests-0.5.tar.gz
Error installing 'micropython-urequests': invalid syntax for integer with base 8: '00000001155\x00', packages may be partially installed

I thought that the error could be related to the update of the repo and some files not being correctly updated, so I create a new clone but the same error occurred. Finally, as I am on Fedora 26 and gcc 7, I thought that it could be related to that, so I install gcc53 on my Fedora, I compiled micropython with it but there is still this error...

What should I do?
Thanks,

**Comment by pfalcon** [comment]
Fixed by 2f7827ba8f8e31eda0e15f3d51073329cf606323.
