### ISSUE TITLE
ESP32 bluetooth support?

### ISSUE THREAD

**Issue by white-gecko** [micropython/micropython#3388]
Is there any plan to support the Bluetooth/BluetoothLE of the ESP32 board? Or is this something that can only come with MicroPython 2.0 (https://github.com/micropython/micropython/issues/2486)?

**Comment by dpgeorge** [comment]
BLE on esp32 has some initial support via a separate branch, see: https://github.com/micropython/micropython-esp32/pull/86

(In the future, please direct all esp32-related reports to the repo linked above.)

**Comment by panhuaguo** [comment]
ESP32 bluetooth support?

**Comment by aykevl** [comment]
See #4589.
