### ISSUE TITLE
Why the module is called _thread instead of uthread?

### ISSUE THREAD

**Issue by pfalcon** [micropython/micropython#3399]
We don't have the module documented, and it before doing that (even if listing it to acknowledge its existence, until we ourselves forgot what' there), would be nice to rethink subj.

To remind, we settled on the idea that all our builtin modules are targeted for direct use, so they should have "u" prefix instead of "_". That's how _socket was renamed to usocket for example.

**Comment by dpgeorge** [comment]
There is no `thread` module in CPython so `uthread` doesn't make sense.  CPython has `threading` and so uPy would have `uthreading`.  `_thread` is like `sys` and `gc`: it's a tightly integrated module that's part of the core.

**Comment by pfalcon** [comment]
Ok, sounds good.

**Comment by pfalcon** [comment]
Docs placeholder added in 579b86451dba202d573c4c22790ebe3d8ddac060.
