### ISSUE TITLE
Better Flash management ?

### ISSUE THREAD

**Issue by iabdalkader** [micropython/micropython#341]
Hi, I have a couple of suggestions for flash management, and I would really appreciate your feedback on this, even if there's no plan/need to implement them in the near future..

First one, instead of caching entire sectors, we cache blocks in a simple hash (mp_map ?) each time there's a cache miss, alloc a new 512 bytes and add it to the map, if it runs out the memory (the CCM not main ram), or the sector is changed, the cache is flushed, this will handle the 16KB and 64KB sectors as usual (with a one erase cycle per sector change) but it will also allow us to use the 128KB blocks with worst case two erase cycles.

Second one is based on how NAND controllers handle this issue, first we'll keep a mapping between logical block address (LBA) and physical block address (PBA), assuming a 512KB flash area (say the last 4 128KB sectors) that's 1024 blocks we'll need 4KBs for the map (it doesn't have to be all in memory at once could be cached) 
The first block of each sector will be reserved to identify erased blocks, (1== fresh block 0==erased/deleted) 512 bytes is twice as much as need for a 128KB sector.

When a write is requested, do a lookup in the mapping and find the physical block (initially LBA==PBA) on the second write, the block will be remapped, this will be implemented by going through all reserved blocks (master blocks?) and looking for the first free block, when found, the old block will be marked as deleted, and so on, reading will be done directly from flash.

If no free block is found, find the sector with the most deleted blocks, copy that to a swap sector, erase it and copy back.

This approach will minimize erase cycles (less power), expand the flash size, free the 64KB CCM for other uses etc..

There's one problem, where to store the mapping ? there's no NVRAM in STM32F4 other than the backup SRAM which needs VBAT connected to a battery, one thought, is to store it in flash, but this means each time a block is remapped it will need to be sync'd at some point, another idea is to use an I2C EEPROM maybe ?

**Comment by dpgeorge** [comment]
Flash use in stmhal still uses the original algorithm with a large buffer in RAM to support large sector erase size, and this is not likely to change.
