### ISSUE TITLE
gccollect.c:148:5: error: implicit declaration of function 'mp_unix_mark_exec' [-Werror=implicit-function-declaration]

### ISSUE THREAD

**Issue by adritium** [micropython/micropython#3419]
https://github.com/micropython/micropython/blob/99bf5448bd02f9b97f55025725e7d2d4ba9aced8/mpy-cross/gccollect.c#L147

In unix/gccollect.c, https://github.com/micropython/micropython/commit/d95b519aa1160960d4473d1db34bacfcc46a94d6 there was a **#ifndef _WIN32** placed around this call; should the same be placed in mpy-cross/gccollect()?

**Comment by dpgeorge** [comment]
> In unix/gccollect.c, d95b519 there was a #ifndef _WIN32 placed around this call

This was then changed in 3926c72dd2c6c9bfc4840f914be5a55258d3a248

I cannot reproduce any "implicit declaration" error when compiling mpy-cross.
