### ISSUE TITLE
Cannot upload files with ampy when changing default baud rate esp8266 to 9600

### ISSUE THREAD

**Issue by WhitleyStriber** [micropython/micropython#3425]
I'm attempting to lower the baud rate for the ESP12F module. When I change the baud rate, recompile the firmware, and upload it to the board, the ampy utility seems to hang when uploading it. I tried changing the baud rate for ampy and it doesn't work.

How can I upload files to the board using a different baud rate?

**Comment by pfalcon** [comment]
If you have a problem with ampy, please report issues to its project.

If you have problems with esp8266, and can provide reproducible steps proving that (without referring to ampy and other adhoc tools), feel free to provide these steps and reopen this issue.
