### ISSUE TITLE
NUCLEO_F429ZI USB Incorrectly configured

### ISSUE THREAD

**Issue by SytechDesigns** [micropython/micropython#3438]
The 'mpconfigboard.h' file for this board is setting the stm pll clocks incorrectly for USB, so usb is not functioning for this board port.
The following PLL settings fix the problem:
 
 //HSE is 8MHz
//HSE is 8 Mhz so pllm = 8, plln = 336 and pllp = 2 gives hclk of 168Mz
// USB cllk needs to be 48Mhz and is derived from plln clk ( 336Mhz) 
// so pllq needs to be 7 making usb clk 336Mhz /7 = 48Mhz
#define MICROPY_HW_CLK_PLLM (8)
#define MICROPY_HW_CLK_PLLN (336)
#define MICROPY_HW_CLK_PLLP (RCC_PLLP_DIV2)      
#define MICROPY_HW_CLK_PLLQ (7)

**Comment by dpgeorge** [comment]
Thanks, what you say seems correct.  I'm not sure why the CPU freq was configured to 90MHz to begin with, possibly it was trying to be 180MHz (the max for the F429) but even that frequency won't allow a 48MHz USB clock.

Fixed in 2cafef857e357bbfcf3bb3c6d10e62b778642695
