### ISSUE TITLE
Port MicroPython to Emscripten

### ISSUE THREAD

**Issue by paladin-t** [micropython/micropython#3444]
Is it possible to compile MicroPython with [Emscripten](https://github.com/kripken/emscripten)? It would be nice to have Python in browser.

**Comment by dpgeorge** [comment]
Yes it is possible and it does work but there's not yet any official code in this repository to do it.  For discussion around this please see: #1561, #2618 and #3313.

**Comment by paladin-t** [comment]
Great, I'll follow those threads. Thanks.
