### ISSUE TITLE
replace all instances of "genhdr" in #include "genhdr/<item.h>" with a MACRO in mpconfigport.h

### ISSUE THREAD

**Issue by adritium** [micropython/micropython#3447]
I had to port the build to another build system and another build-output directory scheme and it'd be nice, and trivial to implement, to be able to specify the "genhdr" directory.

**Comment by dpgeorge** [comment]
Can you please provide a pull request (or at least a patch) which does this and which works for your situation?  That way it is easier to discuss the merits/drawbacks of the idea.
