### ISSUE TITLE
MicroPython and emscripten

### ISSUE THREAD

**Issue by LeaNumworks** [micropython/micropython#3474]
Hi,
I work on a graphic calculator for the company [Numworks](https://github.com/numworks/epsilon). We have a Python app that uses MicroPython. We fixed some issues when using uPY on emscripten and successfully [got it running](https://www.numworks.com/simulator/).

Among the issues we found and fixed:
- MicroPython assumes the [stack is descending](https://github.com/micropython/micropython/blob/3990a52c0f071a7a48cc276f30785930f31eed39/py/stackctrl.c#L40), which is not the case on emscripten.
- We had trouble with garbage collection as explained in emscripten’s [portability guidelines](http://kripken.github.io/emscripten-site/docs/porting/guidelines/portability_guidelines.html).

Would you be interested in some PRs to get a working Emscripten build?

(By the way, this could be interesting for issues #3313, #2618 , #1561, #888)

**Comment by dpgeorge** [comment]
Hi @LeaNumworks, nice work with your simulator!

> MicroPython assumes the stack is descending, which is not the case on emscripten.
> We had trouble with garbage collection as explained in emscripten’s portability guidelines.

Myself and a colleague have also lately been working on an Emscripten port and came across these two issues as well.  The first is easy to fix and we can provide a compile-time option in uPy to select the stack direction.

We could not fix the second issue yet, with the GC.  We have a build of uPy that runs under node (eg `node micropython.js <script.py>`) and running this on the uPy test-suite leads to a fair few failures which are due to the GC not being able to trace root pointers.  Even compiling with -O0 does not fix the issue.  What was your approach to dealing with this problem?

> Would you be interested in some PRs to get a working Emscripten build?

I'm definitely interested in having an Emscripten port, but the GC issue is a real show stopper at this point.

**Comment by LeaNumworks** [comment]
I agree that having a working GC is a priority.

We only really did three things:

- Fix the stack direction
- Get the root pointers in [gc_collect](https://github.com/numworks/epsilon/blob/1da26f4f65a69075dab2ba9c5ff1d12d5936ae6c/python/port/port.cpp#L116) using setjmp
- Compile uPy with -O0

We did not run the uPY test-suite on our port so we may indeed be missing something. That being said, it does a great job for our use-case and the few scripts we tried this on did not seem to be leaking memory.

**Comment by kkimdev** [comment]
@LeaNumworks Would you mind sharing your branch?

In case fixing the garbage collector properly is a huge headache, how about having a naive implementation of https://github.com/micropython/micropython/blob/master/py/gc.c for Emscripten port for now and migrating to https://github.com/WebAssembly/design/issues/1079 in the future when it's ready?

**Comment by kkimdev** [comment]
@LeaNumworks Oh, I guess it's https://github.com/numworks/epsilon/tree/master/python nvm

**Comment by alanjds** [comment]
Nice!

I had put a bounty on https://github.com/micropython/micropython/issues/888#issuecomment-234735603 to get something like this done. Not that $100 USD could possibly cover the costs, but is more about an incentive to get it rolling.

Thanks very much for your effort.

**Comment by kkimdev** [comment]
nvm I took some time to read the source code and have a better understanding of the structure now.  I'll ask if I have any further question thanks!

**Comment by kkimdev** [comment]
You can try @LeaNumworks 's stand-alone micropython here https://kkimdev.github.io/epsilon/index.html

repo: https://github.com/kkimdev/epsilon
I just stripped off non-micropython dependencies from https://github.com/numworks/epsilon/tree/master/python , it didn't require much work actually.

**Comment by alanjds** [comment]
181 KB download / 665 KB unpacked !

This is nice!

**Comment by dpgeorge** [comment]
A port to javascript was added in 7d675f3a17b435c4dc7880ff597ab81274721ae9

**Comment by geowor01** [comment]
@LeaNumworks I am currently working on running MicroPython for the micro:bit with emscripten and emterpretify. I have applied your GC fixes, i.e. the descending stack, using setjmp, and I know that optimisations are not applied. Despite this, the GC still sweeps what it shouldn't, specifically, the local code_state pointer in fun_bc_call appears to not be stored in the stack but stored somewhere in emterpreter's local javascript heaps.

Am I right in thinking that you also use emterpretify?
If so, is there any reason you can think of that this might happen for me but not for the Numworks simulator?
i.e. How do you handle emterpretify storing pointers in heaps?
Is that the same issue you are trying to prevent with -O0?

**Comment by dpgeorge** [comment]
@geowor01 you may want to test with #4723 to see if it helps your case

**Comment by geowor01** [comment]
Thanks @dpgeorge! That does appear to fix the problem.

**Comment by jonnor** [comment]
This issue can probably be closed now? The JavaScript port mentioned above has been renamed to WebAssembly, and should be generally functional. Any problems with it should probably be handled in specific issues?

**Comment by mattytrentini** [comment]
Appears resolved.
