### ISSUE TITLE
Porting Micropython to Tricore Architecture

### ISSUE THREAD

**Issue by SUBBU3881** [micropython/micropython#3499]
Hello,
        I working on infineon's tricore controller using AUTOSAR. Now I need to port Micropython interpreter onto tricore controller.

1. What are the adoptable ways to port micropython onto tricore.?
2. Is it need to cross-build micropython for tricore.? if yes, where from I get cross compiler for tricore controller.?

Please respond as soon as possible.

Thanks and Regards,
Siva Prakash Reddy

**Comment by dpgeorge** [comment]
This issue was also asked https://github.com/micropython/micropython-infineon/issues/1 which is a better place for it.
