### ISSUE TITLE
.seek(offset, SEEK_CUR) not supported

### ISSUE THREAD

**Issue by dhalbert** [micropython/micropython#3517]
Seeking to a position in a file relative to the current offset is not supported. `somefile.seek(offset, SEEK_CUR)` returns `MP_ENOTSUPP`.

https://github.com/micropython/micropython/blob/5de064fbd056944e393be9355855eee6562fecdb/extmod/vfs_fat_file.c#L136

Since `f_tell()` is implemented (and used in that routine), it seems to me the code could call `f_tell()` and then call `f_lseek()` adding the offset to `f_tell()` value. Is there some reason I'm missing that it's not supported?

(Noticed by a CircuitPython user: https://github.com/adafruit/circuitpython/issues/501).

**Comment by dhalbert** [comment]
And see this PR, which implements `SEEK_CUR`:  https://github.com/micropython/micropython/pull/3494

**Comment by dpgeorge** [comment]
This is now fixed by 7642785881550bd71815623c4f93e0516217429c
