### ISSUE TITLE
How to connect to an ESP32 from a mobile application?

### ISSUE THREAD

**Issue by ShrikantKumbhar** [micropython/micropython#3518]
I want to communicate ESP32 with my mobile app. I done micopython coding as follows :

import network
ap = network.WLAN(network.AP_IF)
ap.active(True)
ap.config(essid='ESP32')
ap.config(authmode=3, password='123456789')

In this code Access point is created and it is visible in my android mobile. 
But when i connect my mobile to access point it is showing “saved” message instead of “connected” even though i have entered correct password. 
I followed same procedure using arduino code then i am able to connect my mobile with access point created by esp32. Any help is highly appreciable .

**Comment by robert-hh** [comment]
I have no issues with your script example. I can connect with an android tablet and exchange data.

**Comment by dpgeorge** [comment]
AP mode on the esp32 should be working, so I'll close this issue.
