### ISSUE TITLE
round(x, -1) is not implemented for integers, whereas it is in CPython

### ISSUE THREAD

**Issue by stroobandt** [micropython/micropython#3538]
`round(x, -1)` is not implemented for integers, whereas it is both in CPython and for floats in MicroPython.
```
MicroPython v1.9.2-87-gda8c4c26 on 2017-09-13; PYBv1.1 with STM32F405RG
>>> x = 98836
>>> round(x, -1)
98836
>>> x = 98836.
>>> round(x, -1)
98840.0
```
In CPython:
```
In [1]: x = 98836
In [2]: round(x, -2)
Out[2]: 98800
```
Some more information: https://stackoverflow.com/a/3349102/2192488

**Comment by dpgeorge** [comment]
This is now implemented by b318ebf1015ced6354f8bbaf035308214b3f5c5d
