### ISSUE TITLE
Nothing happends after flashing the new Sonoff TH10

### ISSUE THREAD

**Issue by zokri** [micropython/micropython#3540]
i flashed successfully the Sonoff TH10 with couple of micropython images, using esptool.

but after flashing nothing happends, i can't see serial output, can see wifi.
just nothing.

https://imgur.com/a/pfLUD

the Sonoff is V2.1 2017-6-8

i have older Sonoff TH10, that works fine, only this Sonoff having this problam.

Tnx

**Comment by peterhinch** [comment]
I suggest you raise this on [the forum](https://forum.micropython.org/) where it will receive a wider audience. This is a bug tracker for MicroPython.

**Comment by dpgeorge** [comment]
I assume this issue was resolved.
