### ISSUE TITLE
Data gets assigned to subclass even though no data is sent to super().__init__()

### ISSUE THREAD

**Issue by tulians** [micropython/micropython#3554]
Hello all. I'm working with a data structure which inherits from `list`, and could see that even though `data` is not sent as a parameter of `__init__` it still gets assigned to the `Buffer` object. The code for the data structure is

    class Buffer(list):
        def __init__(self, data=None):
            super().__init__()
            ...

and the specific example to replicate the issue would be:

    >>> from <filename.py> import Buffer
    >>> b = Buffer([1,2,3])
    >>> b
    [1,2,3]

When using the same code on `python3`, I get the expected empty list result, as no data is sent to the list class to initialize itself:

    >>> from <filename.py> import Buffer
    >>> b = Buffer([1,2,3])
    >>> b
    []

Is there any know issue related to this fact? If it is of use, I'm using [mpfshell](https://github.com/wendlers/mpfshell) to upload and test the code, making sure to always use the most recent version of my code and not cached ones.

**Comment by peterhinch** [comment]
Inheriting from built-in classes is not fully supported. See [differences](https://github.com/micropython/micropython/wiki/Differences).
