### ISSUE TITLE
Include obj.h in pyexec.h to resolve undefined MACRO

### ISSUE THREAD

**Issue by adritium** [micropython/micropython#3563]
https://github.com/micropython/micropython/blob/a275cb0f487cd6517760271dc01d369c32600c63/lib/utils/pyexec.h#L52

This macro is defined in `obj.h` but used in `pyexec.h` so `pyexec.h` should include `obj.h`

**Comment by dpgeorge** [comment]
Thanks for the report, fixed in 925c5b1da2fed80774dd393d597392a2c254effa
