### ISSUE TITLE
Simple HTTP Server crash with nmap -sV

### ISSUE THREAD

**Issue by ds2k5** [micropython/micropython#3582]
Hi,
got a ESP8266 Board.
Flashed the Firmware: esp8266-20171101-v1.9.3.bin

Add the Code from simple HTTP Server from http://docs.micropython.org/en/v1.9.3/esp8266/esp8266/tutorial/network_tcp.html
to boot.py an Upload it to the Board with [ampy](https://github.com/adafruit/ampy) 

If I start a **nmap -sV** an scan the IP of ESP8266 the Sever crash.

**sudo minicom -b 115200 -D /dev/ttyUSB0**

------------
>>> Network configuration: ('192.168.0.194', '255.255.255.0', '192.168.0.1', '9.9.9.10')
listening on ('0.0.0.0', 80)

client connected from ('192.168.0.11', 32878)
Traceback (most recent call last):
  File "boot.py", line 55, in <module>
OSError: [Errno 104] ECONNRESET
OSError: [Errno 2] ENOENT

MicroPython v1.9.3-8-g63826ac5c on 2017-11-01; ESP module with ESP8266
Type "help()" for more information.

<code>
import sys

print(sys.version)
</code>

Python Version is 3.4.0

------------
Code snip
<code>

    51      cl, addr = s.accept()
    52      print('client connected from', addr)
    53      cl_file = cl.makefile('rwb', 0)
    54      while True:
    55          line = cl_file.readline()
    56          if not line or line == b'\r\n':
    57              break
    58      rows = ['<tr><td>%s</td><td>%d</td></tr>' % (str(p), p.value()) for p in pins]

</code>

------------

Access with Browser works, also if i do mutilble page reload

**Comment by dpgeorge** [comment]
I tested this on a recent version (v1.11-663-gccae80c43) on esp8266 and it works ok.  The simple HTTP server example in the network tutorial does not crash, it responds to about 40 requests, and the nmap scan prints at the end:
```
Nmap done: 1 IP address (1 host up) scanned in 160.60 seconds
```
