### ISSUE TITLE
lcd160 won't run

### ISSUE THREAD

**Issue by Pedotech** [micropython/micropython#3584]
test_all('X')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'test_all' is not defined

**Comment by robert-hh** [comment]
You might need to add a little bit more of what you have done before you wrote the line test_all('X').  The proper command sequence should be:
```
from lcd160cr_test import *
test_all('X')
```

**Comment by Pedotech** [comment]
Hi Robert
Thank you so much! With your instructions it’s OK.
Great demo!
Thanks
Pedro

**Comment by robert-hh** [comment]
Your welcome. Please close the issue, if it's OK. May I also direct you to the forum at forum.micropython.org with a vivid community of people and a lot of information and help to get.
