### ISSUE TITLE
I2C can not read

### ISSUE THREAD

**Issue by Meekdai** [micropython/micropython#3587]
Hi everyone,
I use pyboard to read an I2C device, I only connect one device, but can scan to a lot of.
Here my code on the REPL

```python
MicroPython v1.9.3 on 2017-11-01; PYBv1.0 with STM32F405RG
Type "help()" for more information.
>>>from machine import Pin, I2C
>>>i2c = I2C(scl=Pin('Y9'), sda=Pin('Y10'), freq=400000)
>>>i2c.scan()
[112, 113, 114, 115, 116, 117, 118, 119]
>>>i2c.readfrom_mem(112, 0x02, 2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 19] ENODEV
```

**Comment by peterhinch** [comment]
This question should be raised in [the forum](https://forum.micropython.org/). This is the MicroPython bug tracker. I suggest you offer more information, notably details of the device you're trying to access.
