### ISSUE TITLE
MP_STATE_VM(repl_line) does not exist

### ISSUE THREAD

**Issue by adritium** [micropython/micropython#3596]
```
MP_STATE_VM(repl_line) = vstr_new(32);
#define MP_STATE_VM(x) (mp_state_ctx.vm.x)
mp_state_vm_t vm;
```

https://github.com/micropython/micropython/blob/cc92c0572e2b6dba3c5897d5778704aaccbb567e/py/mpstate.h#L108-L210

Where in `mp_state_vm_t` do I add `vstr_t* repl_line`?
https://github.com/micropython/micropython/blob/cc92c0572e2b6dba3c5897d5778704aaccbb567e/lib/utils/pyexec.c#L156-L163

**Comment by dpgeorge** [comment]
Yes it's missing.  In #3575 it has been added back, see https://github.com/micropython/micropython/pull/3575/commits/3e1f10ffc09399bf9df11500e4a4209fd1d94ebb .  When that PR is merged the problem will be fixed.

**Comment by dpgeorge** [comment]
Ok, #3575 is stalled so in 9d8347a9aac40f8cc168b0226c2e74f776a7d4bf I added back the `repl_line` pointer to the state.
