### ISSUE TITLE
Trouble compiling for esp8266 port (make step); bunch of 'xyz.h' files not found (#include xyz.h not found, starting with 'osapi.h')

### ISSUE THREAD

**Issue by soocki** [micropython/micropython#3613]
Compiler throws out errors, it cannot locate the '.h' files, the first one it complains about is 'osapi.h'.
FYI: I followed the instructions in ports/esp8266/README.md, it mentions 'cd esp8266' but it should be 'cd ports/esp8266' instead. The first two 'make' commands ('make -C mpy-cross' & 'make axtls') executed fine, the final 'make' doesn't seem to like me.
Help is very much appreciated.

**Comment by pmp-p** [comment]
hi, osapi.h is in the sysroot of esp sdk 
cf: https://github.com/micropython/micropython/issues/3605

Maybe some one should make a front page big red warning about the fact that esp build uses cross-compilation.

**Comment by soocki** [comment]
I have it in my path if that's what you are implying. At least I think that is what you are saying since you refernced that issue. Other than that I do not understand how is that supposed to help me. If I don't understand you correctly: my apologies since you are my only hope so far. I am not being ignorant, perhapsAnyway about the sdk-toolchain: I have compiled it in

**Comment by pmp-p** [comment]
i did not test non-standalone mode and it is not the default so i guess your sysroot is not set.
you should retry with defautl standalone mode to see if include files are automatically found.

**Comment by soocki** [comment]
Rebuilded the esp-open-sdk in standalone mode, it works. Appreciate the help. Ps. Do you think it is worth taking a note in 'ports/esp8266/README.md' about *NOT* building it in non-standalone mode for other doofuses like me?
