### ISSUE TITLE
No dhcp_hostname parameter in ESP32 STA_config

### ISSUE THREAD

**Issue by Sunrise17** [micropython/micropython#3616]
In `modnetwork.c` of ESP32, there is no dhcp_hostname parameter described, but it consists in ESP8266. In due to this reason, i have received `ValueError: unknown config param` while using sta_if.config(dhcp_hostname=DEVICE_NAME) method.

ESP32 Version;
![ekran resmi 2018-02-14 23 07 12](https://user-images.githubusercontent.com/26038249/36225505-edcf014c-11db-11e8-967d-e78978e155b7.png)

ESP8266 Version;
![ekran resmi 2018-02-14 23 07 20](https://user-images.githubusercontent.com/26038249/36225508-f148621e-11db-11e8-91f7-070d937949a2.png)

**Comment by dpgeorge** [comment]
Thanks for the report, the `dhcp_hostname` option is indeed missing in the esp32 port.  I think implementing it would be as simple as calling `tcpip_adapter_set_hostname(self->if_id, hostname)`.

**Comment by dpgeorge** [comment]
The 'dhcp_hostname' config option is now implemented by 27fa9881a9294c6a6875856c44101e5b33d27a3b
