### ISSUE TITLE
ESP32 Wi-Fi in AP mode does not allow listing of stations

### ISSUE THREAD

**Issue by pocus01** [micropython/micropython#3625]
Is there a way to get a list of connected stations when the ESP32 is operating in AP mode? The ESP-IDF SDK provides a 'esp_wifi_ap_get_sta_list' function. Could this be used to provide such a function?

**Comment by pocus01** [comment]
I can have a go at implementing it. :)

**Comment by pocus01** [comment]
@dpgeorge Just did a quick implementation of this... is there something I need to do before I can push the changes to this repo?

**Comment by dpgeorge** [comment]
This is now implemented.
