### ISSUE TITLE
ESP8266 : PWM glitches from full pwm to any value (only if 1 channel active)

### ISSUE THREAD

**Issue by EddieParis** [micropython/micropython#3631]
The PWM at full value is not considered as an "active" channel so if no other channel is used the timer used to mange pwm is not started. So when another duty value is set the pwm timer restarts and there is a visible glitch when driving leds.

Edit: Root cause is obvious but solution is not. I have to do more tests and measures.

**Comment by dpgeorge** [comment]
Please do submit a patch when you have something working.

**Comment by EddieParis** [comment]
@dpgeorge Patch submitted

**Comment by dpgeorge** [comment]
Thanks @EddieParis for the patch.  I confirm the glitch and that this fixes it.  Merged in b691aa0aaeb9f55f96d9ed39f214f0a9e555c94d
