### ISSUE TITLE
periodic timer blocked while waiting socket read() 

### ISSUE THREAD

**Issue by gdallaire** [micropython/micropython#3636]
Hello,

the same code (see below) running on ESP8266 and ESP32 produces different results.

This code creates a periodic timer calling a simple print() at 5 sec intervals, opens a socket, sends some bytes and then waits for a reply.

Under ESP8266, the timer continues to run while the read() is blocking.

Under ESP32, the timer is "paused" while the read() is blocking :(

any idea ?

```
import socket
import network
from machine import Timer

sta_if = network.WLAN(network.STA_IF)
sta_if.active(True)
sta_if.connect('xxxx', 'xxxxx')

t = Timer(3)
t.init(period=5000, mode=Timer.PERIODIC, callback=lambda t:print("hello"))

def connect():
    addr = socket.getaddrinfo('192.168.0.40', 4242)[0][-1]
    s = socket.socket()
    s.connect(addr)
    s.send(bytes('.....\n', 'utf8'))
    s.read()
    s.close()
```
OUTPUT:

ESP8266:
```

hello
hello
>>> connect()
hello
hello
```

ESP32:
```

hello
hello
>>> connect()

```

**Comment by dpgeorge** [comment]
Thanks for the report.  It seems that the issue was that the esp32 did not check for pending events during socket operations.  That should now be fixed by 12a3fccc7e07124afd8634353baa2a2a32a04c8d
