### ISSUE TITLE
mp_obj_bool_t is not public so cannot decode mp_type_bool

### ISSUE THREAD

**Issue by adritium** [micropython/micropython#3641]
```
typedef struct _mp_obj_bool_t {
    mp_obj_base_t base;
    bool value;
} mp_obj_bool_t;
```

is defined in `objbool.c`, not in a header.

I'm creating new boolean objects using `obj.h`
`static inline mp_obj_t mp_obj_new_bool(mp_int_t x) { return x ? mp_const_true : mp_const_false; }`

But then how do I decode when `MP_OBJ_IS_TYPE(o, &mp_type_bool) == true`?

I cannot follow the standard way
```
STATIC void bool_print(const mp_print_t *print, mp_obj_t self_in, mp_print_kind_t kind) {
    mp_obj_bool_t *self = MP_OBJ_TO_PTR(self_in);
...
```

because `mp_obj_bool_t` is private to `objbool.c`

**Comment by dpgeorge** [comment]
> But then how do I decode when MP_OBJ_IS_TYPE(o, &mp_type_bool) == true?

In general the way to decide truthness is to use `mp_obj_is_true(o)`.  This will cover all cases in Python where you are allowed to use an object in place of a bool (eg if you pass 0 or 1).

There's also `mp_obj_is_integer(o)` which can be used to tell if an object is an integer or bool.

If it's really important to distinguish `False` and `True` from 0 and 1 then use the expression: `(MP_OBJ_TO_PTR(o) == mp_const_true)`.
