### ISSUE TITLE
dir(complex_instance) is null

### ISSUE THREAD

**Issue by adritium** [micropython/micropython#3648]
In CPython (Pycharm)

```
a = complex(1, 1)
dir(a)
# ['__abs__', '__add__', '__bool__', '__class__', '__delattr__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__int__', '__le__', '__lt__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__pos__', '__pow__', '__radd__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmod__', '__rmul__', '__rpow__', '__rsub__', '__rtruediv__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', 'conjugate', 'imag', 'real']
```

In uPy
```
a = complex(1, 1)
dir(a)
# []
```

With regards to the uPy C-code, I know the reason this is null is because of two reasons:

1. `dir()`: whether you pass in a `type` or `type_instance`, it will always print what's in `type.locals_dict`
2.  type `complex` has no `.locals_dict` entry so `dir(complex)` and `dir(complex_instance)` will always return NULL.

_This is not intuitive_ 

You can get the `real` part by typing `a.real` and `a.imag`  . . . so the user should be able to see these fields by typing `dir(a)`.

Also, `complex_attr()` prevents you from assigning a value to the `real`/`imag` individually; why?

**My real-world usage**

For my use, I created a type `can_message` and I want users to be able to do the following

```
dir(can_message)
# id, data

a = can_message()
dir(a)
# id, data
a.id = 55
a.data = [1, 4, 3, 1]

print(a)
# id = 55
# data = [1, 4, 3, 1]

type(a.id)
# class <int>

type(a.data)
# class <list>
```

To implement the `dir()`, I would add a `.locals_dict` to `can_message` like so

```
STATIC const mp_rom_map_elem_t can_message_type_locals_dict_table[] =
{
		{MP_ROM_QSTR(MP_QSTR_id), MP_ROM_PTR(&id_type)},
		{MP_ROM_QSTR(MP_QSTR_data), MP_ROM_PTR(&list_type)},
};

// id_type, list_type: 
//   I need `type(a.id)` to be `class <int>` and `type(a.data)` to be `class <list>`
//   It's hacky but I this is how to do it
                             
const mp_obj_type_t id_type= {
    { &mp_type_int},
    .name = MP_QSTR_id,
};

const mp_obj_type_t list_type= {
    { &mp_type_list },
    .name = MP_QSTR_data,
};

STATIC MP_DEFINE_CONST_DICT(can_message_type_locals_dict, can_message_type_locals_dict_table);

const mp_obj_type_t can_message_type =
{
	{&mp_type_type},
	.name = MP_QSTR_message,
	.print = can_message_obj_print,
	.make_new = can_message_make_new,
	.locals_dict = (mp_obj_t)&can_message_type_locals_dict,
	.attr = can_message_attr
};
```

Implementing `a.id = 123`, I need a `.attr` function that checks that the `qstr` argument is present in `can_message_type_locals_dict_table`

**Conclusion**

This part of the API needs to be reworked so it's not so awkward to add struct-like fields.

**Comment by stinos** [comment]
>  I need a .attr function that checks that the qstr argument is present in can_message_type_locals_dict_table

No, you don't need to do it like that. You can check the qstrs without them having an antry in locals_dict. For the x-th time: forget about locals_dict unless you have functions (or constants). You already asked this on the forum, even again on Stackoverflow, got answers, which you don't seem to like, but trying again here isn't going to change the answers so you better just accept them and try to understand them. Instead of asking for an API change. An API which all others who have used it so far do not have such problems with.

Anyway consider it like this as well: dir(myType) isn't going to return those attributes, but that is totally fine because users of your class are also MicroPython users and MicroPython users know if they want dir() to return something sensible it should be ran on an instance, not a type. So your class just behaves like all others. Consistency is good. Actually even if you would go through hoops to make dir(myType) return something, that efforrt would be pretty useless since MicroPython users typically wouldn't even try to run dir on a type. Actually from a 'don't confuse the users' point of view what you are doing now is very confusing since you're essentially lying to the users bu saing 'id is <class int>' while in reality it is not.

**Comment by adritium** [comment]
> No, you don't need to do it like that. You can check the qstrs without them having an antry in locals_dict

And how is the user supposed to know which attributes they can access?
Probably by doing `dir(type)` just like in normal Python.

> dir(myType) isn't going to return those attributes, but that is totally fine 

It is totally NOT fine. If they create an object of type `can_message`, they should be able to do `dir(obj_can_message)` and find out which functions/attributes/fields exist without having to go to some other documentation.
This is the behavior in CPython; why can't it be the behavior in uPy?

> because users of your class are also MicroPython users and MicroPython users know

Again, no. The point of my feature is for people who know Python to be able to use the API. 
In Python, `dir(can_message)` and `dir(obj_can_message)` return the list of functions and attributes that belong to the object or type.

> know if they want dir() to return something sensible it should be ran on an instance, not a type.

In Python, `dir(can_message)` and `dir(obj_can_message)` return the list of functions and attributes that belong to the object or type. 

> Instead of asking for an API change. An API which all others who have used it so far do not have such problems with

Then I guess we'll stop improving uPy; better tell the C++ people that they really didn't need C++11, C++14, C++17 and they should just stick with C++03.

**Comment by stinos** [comment]
> they should be able to do dir(obj_can_message) and find out which functions/attributes/fields exist without having to go to some other documentation.
This is the behavior in CPython; why can't it be the behavior in uPy?

But it *is* the behaviour in uPy, that's exactly what e.g. Damien's comment is about.

**Comment by adritium** [comment]
> But it is the behaviour in uPy, that's exactly what e.g. Damien's comment is about.

Clarify: are you saying it's normal for `dir(type)` to be different or same behavior from CPython?

**Comment by dpgeorge** [comment]
@adritium I'm not sure what the issue is that's reported in this ticket.  Please try to separate any issues there might be with `dir()` (and how it may or may not differ to CPython) from issues with creating custom types that have attributes.

**Comment by adritium** [comment]
@dpgeorge what is the intended uPy behavior for these two cases:

`dir(any_type)` vs `dir(any_type_obj)`

**Comment by dpgeorge** [comment]
> what is the intended uPy behavior for these two cases:
> 
> dir(any_type) vs dir(any_type_obj)

@adritium The intention is for `dir()` to behave as similar as possible to CPython.  In CPython we have `dir(1)` the same as `dir(int)`, and in uPy they are almost the same as well in this case (only difference is some special method).  For a user class (`eg class A: ...`) the dir of the object instance will include the methods of the type as well as any instance members.
