### ISSUE TITLE
Float type causes memory problem

### ISSUE THREAD

**Issue by Jomsanchez-gmv** [micropython/micropython#3675]
Using floats consumes memory without the GC releasing it.
In the following script, a float variable is incremented and the current state of the memory is shown and the free memory decreases.
```
import micropython

a = 1.1

while True:
	a = a + 1.1
	print(micropython.mem_info(1))
```
![floatmem](https://user-images.githubusercontent.com/10668867/37655514-7d1d48c4-2c3d-11e8-8ae9-feeb0f4a4ac9.PNG)

This **same script made with an int** variable and the sum of an int value. It does not cause these problems as seen in the following figure.
```
import micropython

a = 1

while True:
	a = a + 1
	print(micropython.mem_info(1))
```
![integermemory](https://user-images.githubusercontent.com/10668867/37655513-7d001f1a-2c3d-11e8-82bb-b557954e02b6.PNG)

This problem causes a MemoryException when the memory reaches zero, as seen in the following figure (a port with less available memory)
![floatrtems](https://user-images.githubusercontent.com/10668867/37655512-7cd21e6c-2c3d-11e8-88fc-cc7b55e1cdeb.PNG)

**Comment by peterhinch** [comment]
I think your measurement technique is the issue here. Each pass of the loop will allocate RAM, however this will be released when a garbage collection (GC) is performed. To check for memory leaks you need to do a GC before the test starts, and again after it completes:
```python
import micropython, gc
gc.collect()
micropython.mem_info(1)
a = 1
while a < 1000000:
    a += 1.1
gc.collect()
micropython.mem_info(1)
```
Outcome: uses ~48 bytes.
(Takes ~ 12s on Pyboard V1.1)

**Comment by Jomsanchez-gmv** [comment]
Thanks for your answer, I tested your script (unix port) and woks fine. My main problen was that I was using a port with MICROPY_ENABLE_IMMORTAL_GC option enabled and gc.collect() didn´t work.
I think that this "issue" is closed.
