### ISSUE TITLE
I2C slave device on ESP32

### ISSUE THREAD

**Issue by v-gridnevsky** [micropython/micropython#3680]
Hello. Could I make ESP32 function in I2C slave mode using the recent version of MicroPython and its machine library?

**Comment by tuupola** [comment]
Vanilla MicroPython currently supports only I2C masters. However you could check [Loboris fork](https://github.com/loboris/MicroPython_ESP32_psRAM_LoBo/wiki/i2c) which has I2C slave support.

**Comment by v-gridnevsky** [comment]
Thanks, I'll look at it!

**Comment by jonnor** [comment]
I think we could close this in favor of https://github.com/micropython/micropython/issues/3935
