### ISSUE TITLE
Undefined real_main building zephyr port

### ISSUE THREAD

**Issue by phaethon** [micropython/micropython#3685]
Hello!

I was trying to build micropython Zephyr port on MacOS. My target is arduino_due. I can build Zephyr sample applications, upload them to the device and run. Thus I assume build configuration for Zephyr shall be usable. Zephyr src version is git clone from last Friday (commit 20cd4b551b938e83d8de250ebf810455a2a8a35f). cmake version is 3.10.3

When I try to build zephyr port with `make BOARD=arduino_due` I get:
 
micropython/ports/zephyr/src/zephyr_start.c:38: undefined reference to `real_main'
collect2: error: ld returned 1 exit status

I get the same if I do make_minimal instead of make.

**Comment by phaethon** [comment]
This seems to be related:
https://stackoverflow.com/questions/9537964/ranlib-warning-for-library

I created 2 softlinks in /usr/local/bin for ar and ranlib pointing to corresponding arm-none-eabi-* tools and now it compiles.

Though I must admit it still does not work on the device, but that could be another issue.

**Comment by dpgeorge** [comment]
Hi @phaethon.  I was able to build the Zephyr port just now with `make BOARD=arduino_due` and it compiles cleanly (I don't have a board so can't actually test the firmware).  I use Arch Linux with the latest Zephyr SDK 0.9.2 for Linux installed locally.  I used a very recent version of Zephyr, f77469a3bbb61c58b52a5c2e5592803dd67d1d08.  So it's most likely an issue with the SDK running on your OS.
