### ISSUE TITLE
Rework of stm32/main.c:init_flash_fs() for more flexibility

### ISSUE THREAD

**Issue by peter-conalgo** [micropython/micropython#3688]
I'd like to change the function `init_flash_fs` found in `stm32/main.c` as follows:

- make it weak linkage
- move the constant strings into that function, which define the file contents for `main.py`, `boot.py`, `readme.txt` and `pybcdc.inf`

Then, my board port can completely override the contents of those files to suit my needs. I can also set the filesystem volume name to my taste (solves #2655) and generally precisely control the contents of the filesystem at boot time.

Any feedback before I make a PR for this?

**Comment by dpgeorge** [comment]
Factory files can now be overridden by a board by defining `factory_reset_make_files()`, see 97753a1bbc5a20003bcf2a7f90cff2ca5c81ee92
