### ISSUE TITLE
Need mp_const_stop_iteration variant which can hold an argument value

### ISSUE THREAD

**Issue by pfalcon** [micropython/micropython#369]
StopIteration(val) has important meaning for generators. To optimize exception handling (not allocate big exception objects and nlr_buf_t stack frames), we need special sentinel value like mp_const_stop_iteration, but which can hold an mp_obj_t (arg of StopIteration). The idea is to convert exception as generated by bytecode to a sentinel value which can be just returned instead of being thrown. Of course, such value will need to be dynamically allocated, but again, we'll save a lot of stack on nlr_push'ed to catch StopIteration's after they are thrown.

**Comment by dpgeorge** [comment]
Optimised `MP_OBJ_STOP_ITERATION` can now take an argument, see bb00125aaac8376b8cc4c8f3da2423fcf6dae496
