### ISSUE TITLE
Is it possible to connect two ESP32 boards with MicroPython using SPI?

### ISSUE THREAD

**Issue by v-gridnevsky** [micropython/micropython#3700]
I think I'm stuck: I've found code example [here](https://github.com/micropython/micropython-esp32/issues/225), tried to send data from one board to another, but I'm only receiving rows of values like `\xff` and `\x00` instead of data, while reading input like this:
    
    from machine import SPI, Pin
    import time
    spi=SPI(1, baudrate=1000000, mosi=Pin(23, Pin.OUT), sck=Pin(18, Pin.OUT), miso=Pin(19, Pin.IN))
    while True:
        time.sleep(0.2)
        print(spi.read(8))

**Comment by martijnvandijk** [comment]
Besides @dpgeorge's suggestion, you could implement a bitbanged spi slave mode if you really want to use SPI. Using UART would be way easier though.

**Comment by Dippermmc** [comment]
> The machine.SPI class only support _master_ mode and you can't have 2 masters on the same SPI bus (because they both try and drive the SCK line). It's much easier to use UART for this kind of board-to-board communication.

Can microbit micropython support SPI slave mode?

**Comment by dpgeorge** [comment]
> Can microbit micropython support SPI slave mode?

No.
