### ISSUE TITLE
Use of const() leads to SyntaxError

### ISSUE THREAD

**Issue by doc-hex** [micropython/micropython#3702]
The last line in this example causes a SyntaxError in Micropython v1.9.3:

```python
test = const(34)

def bar(**kw):
    print(kw)

# SyntaxError: LHS of keyword arg must be an id
bar(test=test)
```

If `const()` isn't used and `test=34` then it works as expected. Strangely, if the first line is pasted/entered by itself, separate from the rest of the file, it works fine. You might need to put the above into a single file and import it to see the issue.

I don't know if this should be considered a micropython quirk, limitation or a bug.

**Comment by dpgeorge** [comment]
> I don't know if this should be considered a micropython quirk, limitation or a bug.

This is a limitation of the parser/compiler: when parsing `bar(test=test)` it's not possible to know if the first `test` is an expression (which should be replaced with 34) or a keyword (which shouldn't be replaced) until the `=` is encountered.  So it's optimistically considered an expression and substituted.

In real code one shouldn't come across this limitation much, if at all.  Constants should be written using upper case and argument names should be lower (or camel) case.

**Comment by dpgeorge** [comment]
There have been no further reports of/issues with this limitation, so I'd say it's safe to leave the behaviour as-is (`const` is local to a .py file so you just need to choose constant names that are unique to that file).
