### ISSUE TITLE
mp_load_method_maybe - finaliser - change order of check for "attr" and "locals_dict"

### ISSUE THREAD

**Issue by adritium** [micropython/micropython#3720]
I have created a type `can_message_type`

```
STATIC const mp_rom_map_elem_t can_message_type_locals_dict_table[] =
{
		{MP_ROM_QSTR(MP_QSTR_id), MP_ROM_PTR(&id_type)},
		{MP_ROM_QSTR(MP_QSTR_data), MP_ROM_PTR(&list_type)},
		{MP_ROM_QSTR(MP_QSTR_flags), MP_ROM_PTR(&mp_type_dict)},
};
STATIC MP_DEFINE_CONST_DICT(can_message_type_locals_dict, can_message_type_locals_dict_table);

const mp_obj_type_t can_message_type =
{
	{&mp_type_type},
	.name = MP_QSTR_message,
	.print = can_message_obj_print,
	.make_new = can_message_make_new,
	.locals_dict = (mp_obj_t)&can_message_type_locals_dict,
	.attr = can_message_attr
};
```

Because I want the user to be able to access the fields directly, I had to add the `.attr` function

```
msg1 = message()
# The following requires the existance of the `.attr` function
msg1.data = [1, 3, 5, 4]

```

I had to also add `.locals_dict` because I want the user to be able to do `dir(msg1)` or `dir(message)` and get a list of the attributes.

When the finaliser is called in `void gc_sweep()`, `mp_load_method_maybe` first checks and calls `.attr` and if it doesn't exist, looks up `MP_QSTR___del__` in `.locals_dict`.

Under this order, I'd have to return the `__del__` method from `.attr` when I could just put it in `.locals_dict`

**REQUEST**

Unless there's a reason for `type->attr` being called before `type->locals_dict`, I'd like the order of those two to be swapped.

**Comment by stinos** [comment]
> Under this order, I'd have to return the __del__ method from .attr when I could just put it in .locals_dict

Are you sure? All my types have .attr and .locals_dict and assigned yet their `__del__` function is in locals_dict?

> Unless there's a reason for type->attr being called before type->locals_dict

mp_load_method_maybe is used all over the place so changing order could potentially affect performance in a lot of places; moreover it might be desired that attr has priority over locals_dict, not sure
