### ISSUE TITLE
Support for python 3.6 syntax (Static Type Checking)

### ISSUE THREAD

**Issue by przemekgalazka** [micropython/micropython#3727]
Would be super cool to use Static Type Checking from the beginning as this may help a lot

https://medium.com/@ageitgey/learn-how-to-use-static-type-checking-in-python-3-6-in-10-minutes-12c86d72677b

**Comment by jpochyla** [comment]
MicroPython does support type hints for the function arguments, for variables and instance properties you can use the comment syntax: `# type: ...`.

As for possible run-time costs of `import typing` and such, I've ended up wrapping it in `if __debug__:` clauses.

**Comment by dpgeorge** [comment]
> Is it hint or compile time error?

The compiler itself doesn't care about these type hints.  You need to run an external tool (eg mypy) to find the type errors.

The addition of this particular syntax feature (PEP 526 - Syntax for Variable Annotations) is discussed in #2415, which also discusses other 3.6 changes.  I'll close this issue for now.
