### ISSUE TITLE
upip broken

### ISSUE THREAD

**Issue by misjob** [micropython/micropython#3733]
The "url_open" function in "upip.py" does not handle the "301 Moved Permanently" HTTP code correctly when connecting to https://pypi.python.org/.

It works fine with the new url: https://pypi.org/

**Comment by peterhinch** [comment]
See https://github.com/micropython/micropython-lib/pull/275

**Comment by dpgeorge** [comment]
This is now fixed by f7be5f9bfa61a07a8256aaae8f22d151f6b8ad81

**Comment by aenertia** [comment]
Hrm - I'm pulling but getting up to date messages ; i'll reclone. Something is obviously broken in my local repository
