### ISSUE TITLE
WDT Default Timeout for 8266

### ISSUE THREAD

**Issue by pushkarprasad007** [micropython/micropython#3735]
I'm trying to ensure that WDT does not reboot while my application While Loop is running. Using

`wdt = WDT()`

Inside while loop(periodically):
`wdt.feed()`

But for the above to work, I need to be aware how frequently the feed() has to be called, i.e, what is the default WDT timeout.

Can some one please let me know what it is for latest micropython firmware (1.9.3) for ESP8266?

**Comment by dpgeorge** [comment]
The WDT on the esp8266 is not currently functioning.  This is because, as long as your script is executing (even in an infinite loop), the underlying system (wifi etc) is still running and feeding the watchdog.
