### ISSUE TITLE
ustruct add support for 'x' pad byte

### ISSUE THREAD

**Issue by goatchurchprime** [micropython/micropython#3736]
Documented here:  https://docs.python.org/3.5/library/struct.html#format-characters  
(It looks to me like a lower case 'x')

I think the code implement it is in py/binary.c

I'm surprised by the omission as this is an easy one.  It's a good way to efficiently knock out unnecessary conversions of values you don't happen to need out of your byte string.

**Comment by dpgeorge** [comment]
Yes this does look like a sensible thing to implement, but more so for unpack than pack.  Do you have a (strong) use-case for it?

**Comment by goatchurchprime** [comment]
I don't know if this is a strong use-case, but the place I wanted it was for decoding the string of data from a SHT31D humidity sensor where, according to p10 of the datasheet, it inserts these unwanted CRC bytes:
https://cdn-shop.adafruit.com/product-files/2857/Sensirion_Humidity_SHT3x_Datasheet_digital-767294.pdf

My code for unpacking the values had to be (with these 2 unwanted bytes):
> rawtemp, b1, rawhumid, b2 = ustruct.unpack(">HbHb", k)

https://github.com/goatchurchprime/jupyter_micropython_developer_notebooks/blob/master/Sensor_Kennel/SHT31D_funcs.py#L32

But in general it seems this would be a useful thing for efficiently unpacking specific values from a binary C-struct while (a) ignoring the bytes you don't want and (b) not having to do slices of the byte string first.

**Comment by hardkrash** [comment]
I stumbled across needing this today,  my workaround is:
```python
a, _, b = strut.unpack('<BbB', b'\x00\x12\x34')
```
I would have preferred to have` '<BxB'` as my format and not have the` _` in the tuple unpack.

For consistency, following the `x` packs as a `b'\x00'` allows for symmetric pack and unpack (lossy in the pack as it will always be a `\x00`, but that's what pad bytes are for.

**Comment by dpgeorge** [comment]
Support for the "x" character in struct pack/unpack was added in d1f288c041c85793de17da9f8b38ff20af2a6f1d

**Comment by mattytrentini** [comment]
Looks like the [ustruct documentation](https://docs.micropython.org/en/v1.9.3/pyboard/library/ustruct.html#module-ustruct) needs to be updated?

**Comment by dpgeorge** [comment]
Yes, Jim is on top of the documentation updates: https://github.com/micropython/micropython/pull/12059#issuecomment-1722081391
