### ISSUE TITLE
ESP8266 port's upip not working

### ISSUE THREAD

**Issue by osamarais** [micropython/micropython#3743]
I guess the PyPI url was recently changed or something.
upip is working totally fine on the unix port of micropython.
However when I try to install the same package on the ESP8266 using it's own upip it's not working.
I get an error that the package is not found.

**Comment by dpgeorge** [comment]
The change in PyPI URL was recently fixed, see #3733.  Did you use the very latest nightly build of the ESP8266 firmware?

**Comment by osamarais** [comment]
Nope, using the latest stable one.

**Comment by peterhinch** [comment]
You need to flash the latest nightly build.
