### ISSUE TITLE
Failed to boot with error message - Image contains multiple IROM segments(On ESP32 chip)

### ISSUE THREAD

**Issue by eminarcissus** [micropython/micropython#3756]
Hmm.
Another weird problem here,
I'm using the latest master, and added some bluetooth logics into the firmware, and it compiles correctly(which as expected with the old micropython firmware I use), but it won't start with the latest firmware anymore.(Firmware runs if it compiles directly with master commit).

This is the boot log.

> ets Jun  8 2016 00:22:57
> 
> rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
> configsip: 0, SPIWP:0xee
> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
> mode:DIO, clock div:2
> load:0x3fff0018,len:4
> load:0x3fff001c,len:4436
> load:0x40078000,len:0
> load:0x40078000,len:11816
> entry 0x4007a9fc
> E (514) boot: Image contains multiple IROM segments. Only the last one will be mapped.
> 
> 

This is the build log for firmware

> LINK build/application.elf
>    text	   data	    bss	    dec	    hex	filename
>  957334	 295205	  99152	1351691	 14a00b	build/application.elf
> Create build/application.bin
> esptool.py v2.2.1
> Create build/firmware.bin
> bootloader     16352
> partitions      3072
> application  1363664
> total        1429200

partition_mpy.csv

> # Name,   Type, SubType, Offset,  Size, Flags
> # Note: if you change the phy_init or app partition offset, make sure to change the offset in Kconfig.projbuild
> nvs,      data, nvs,     0x9000,  0x6000,
> phy_init, data, phy,     0xf000,  0x1000,
> factory,  app,  factory, 0x10000, 0x180000,

I'm searched both in ESP_IDF and micropython for the error message, but none of them gave me any hints on where the problem roots. Looks like a partition error?

Also in partition_mpy.csv, nvs,phy and factory have a offset of 0x9000,0xf000 and 0x10000
but in mkimage.py, I can see it have a such layout

> OFFSET_BOOTLOADER = 0x1000
> OFFSET_PARTITIONS = 0x8000
> OFFSET_APPLICATION = 0x10000
> 

so what's indeed the logics behind the scene of partition here?

**Comment by dpgeorge** [comment]
Sorry, can't help here.  This is not really a bug/issue with MicroPython, you'll need to understand how the ESP IDF works to fix it.

**Comment by eminarcissus** [comment]
Got it, will get to ESP IDF to see the reason here, I've checked IDF's document for quite a lot of times but didn't get any insights about this problem. Thx very much for the help
