### ISSUE TITLE
add support to split heap in multiple ranges

### ISSUE THREAD

**Issue by adritium** [micropython/micropython#3758]
In current `gc` initialization, it is only possible to provide one range for the heap.

https://github.com/micropython/micropython/blob/12a3fccc7e07124afd8634353baa2a2a32a04c8d/py/gc.c#L108-L120

However, all the RAM available on a micro-controller might not be in a contiguous range because there might be different types of RAM: SRAM, SDRAM, SPI-RAM, peripheral-dedicated RAM etc.

In my particular case, there is 4K of RAM that is used by a certain peripheral but only if it's enabled but otherwise, it's free for general-purpose use. 
Unfortunately, 4K is too small for (most of) my uses as a heap by itself but if I could append it to my main heap, I wouldn't be letting 4K of RAM go to waste.

What do you think?

**Comment by dpgeorge** [comment]
Please see PR #3580 which proposes exactly this.
