### ISSUE TITLE
ESP8266 SPI slave mode

### ISSUE THREAD

**Issue by Fef0** [micropython/micropython#3759]
Hi, I'm new to the micropython world and I'm actually working with an ESP8266 which has to act as a SPI bridge between two SPI devices, is there any way to use the Slave mode on it? I tried with the library which is included with micropython but I can't see any slave mode.
Any ideas?

**Comment by peterhinch** [comment]
Slave mode is currently unsupported. An implementation on the ESP8266 capable of any reasonable speed would probably be difficult because of latency issues.

**Comment by Fef0** [comment]
My system should communicate at 9600 Thanks for lbaud, so not a big deal.. What about the ESP32? Is it supported?

**Comment by peterhinch** [comment]
The same observation applies: ESP32 and ESP8266 both have an underlying RTOS. Slave mode with reasonable performance is probably impracticable except on bare-metal ports such as the Pyboard. The problem is that the interface assumes a fast realtime response from the slave.

**Comment by Fef0** [comment]
Okay thanks for the clarification Peter!

**Comment by Fef0** [comment]
@dpgeorge Thanks for the clarification, I was thinking to use two ESP8266: one as slave (to receive data from the original master) and one as master (to control the original slave with the edited data), both connected with serial or I2C to exchange data. I could use an Arduino, but I need a fast computation on the bridge node, so an ESP8266 at 160MHz would be perfect. I read that the ESP8266 has a hardware SPI port, but I couldn't understand why micropython exposes just the master mode. I also have a ESP32 which should have 2 SPI port, one called HSPI and another called VSPI, so the slave-master nodes would be condensed in a single node

**Comment by mattytrentini** [comment]
Issue appears resolved, at least until an SPI Slave implementation is more widely available.
