### ISSUE TITLE
esp8266: remove print statement in ntptime

### ISSUE THREAD

**Issue by triplepoint** [micropython/micropython#3766]
There's a print statement here on line 36:
https://github.com/micropython/micropython/blob/master/ports/esp8266/modules/ntptime.py#L36

which it is not possible to avoid.  I think we could just remove it, but at the very least we should replace that line with 
```
return utime.localtime()
```
And let the calling code decide if they want to print it or not.

**Comment by dpgeorge** [comment]
> And let the calling code decide if they want to print it or not.

Yes, I agree.  But let's wait until after v1.9.4 is released.

**Comment by dpgeorge** [comment]
Fixed by aace60a75e5afedadfc30d33e91ef7c6fa312405

**Comment by triplepoint** [comment]
Awesome, thanks.
