### ISSUE TITLE
 ESP32 : please impelent UART sendbreak

### ISSUE THREAD

**Issue by nyuszis** [micropython/micropython#3785]
Due to DMX support please implement sendbreak on ESP32.

int uart_write_bytes_with_break(uart_port_tuart_num, const char *src, size_t size, int brk_len)
If size is 0 only send break on ESP32.

**Comment by dpgeorge** [comment]
> If size is 0 only send break on ESP32.

Unfortunately you can't put size=0 in this function.  So the way to implement uart.sendbreak() would be to switch parity to even and send 0x00, then switch parity back to what it was.

**Comment by dpgeorge** [comment]
This was implemented in 87623082e331b9fdbac198b287ffac6ac4953bd3

**Comment by nyuszis** [comment]
thank you
