### ISSUE TITLE
esp32: Implementation of bluetooth?

### ISSUE THREAD

**Issue by pedrofelipest** [micropython/micropython#3809]
Hello guys.

Is it possible to use esp32's BLE via micropython?

**Comment by dpgeorge** [comment]
No, BLE on ESP32 is not yet implemented.

**Comment by bmeisels** [comment]
For refrence : 
micropython/micropython-esp32#222

Considering the nrf port has been merged and includes a Bluetooth implementation (ubluepy + ble_drv),
I think it would be best to make ubluepy shared between ports and implement ble_drv for esp32.

 I have looked over the ubluepy code and it seems that the interface is generic but some of the implementation is specific (event codes and maybe more).
The ble_drv.h file uses the BLUETOOTH_SD macro but this can easily be generalized for all ports.

@aykevl @MrSurly @dpgeorge what are your thoughts?

**Comment by aykevl** [comment]
@bmeisels 
The intention is to define a new cross-platform API suitable for MicroPython that works on both the esp32 and nrf, instead of porting the ubluepy support to the esp32.

**Comment by MrSurly** [comment]
I think it makes sense to keep the interface as consistent as possible across ports.

**Comment by aykevl** [comment]
I've started writing a cross-port BLE module here: https://github.com/micropython/micropython/compare/master...aykevl:bluetooth

It currently works on both the esp32 and the nrf. Currently it only support advertisement (and only a local name):

```py
import bluetooth
bt = bluetooth.Bluetooth()               # singleton
bt.active(True)                          # activate BT stack
bt.advertise(100, 'hello MicroPython!')  # start advertisement (interval=100ms, name=..., connectable=True)
# [...]
bt.advertise(0)                          # stop advertisement (interval=0)
```

You can connect, inspect the default services, and disconnect again (restarting advertisement).

**Comment by Davidus55** [comment]
Hello guys,

I am trying to test the bluetooth on a ESP32 board with Atom IDE on Windows 10.
When I run exemples with "import bluetooth" I have an error message : "ImportError : no module named 'bluetooth'.

On atom when I ask the python version:

import sys
print("Version Python ",sys.version)

I receive :

Version Python 3.4.0

When I test with Anaconda or Pycharm (python --version):
Python 3.6.5 :: Anaconda, Inc.

My problem is that I don't understand how use the ESP32 with bluetooth without Atom or how configure Atom for used bluetooth library.

For information, It's my first projet with bluetooth, python and ESP32.

Thank you for your help.

**Comment by aykevl** [comment]
What firmware did you flash?
I did a bit of work as can be seen in the comment above. But you'd have to build and flash that specific branch or it won't work. And even then it doesn't really implement anything useful.

**Comment by Davidus55** [comment]
I used this firmware for the ESP32 : esp32-20180816-v1.9.4-465-g056e0b629.bin

I tried to use this branch with these steps on Anaconda:

(base) C:\Users\me> pip install --upgrade setuptools
(base) C:\Users\me> git clone https://github.com/micropython/micropython
(base) C:\Users\me> cd micropython
(base) C:\Users\me\micropython> conda create -n micropython python==3.6
(base) C:\Users\me\micropython> activate micropython

But after that I don't know what I need to do:
(micropython) C:\Users\me\micropython> ????

For the bluetooth I just want to send and receive some data.

**Comment by aykevl** [comment]
This is not yet implemented. I'm afraid you have to wait until the work is done.

Also, I don't know what Anaconda is supposed to be but why not just run `make deploy` inside ports/esp32?

**Comment by peterhinch** [comment]
**make** is an executable. Under Linux it's in **/usr/local/bin/**. I don't know Windows but it would seem to be missing from your system.

**Comment by robert-hh** [comment]
make and similar tools come with the MINGW package. In my installation, its in mingw32\msys\1.0.\bin. At you system, the place may be different. You may have to include the proper path into yout Windows PATH variable.

**Comment by stinos** [comment]
If you use msys2 then make isn't included by default, you have to install it using for example `pacman -S make`. In any case, you likely shouldn't be modifying the global PATH variable but rather the path of the (unix-like) shell you're running in: that is less drastic and more future proof, easier to test multiple versions of e.g. gcc and so on.

**Comment by lbandeira** [comment]
Hi guys,
It's my first project on ESP32 using micropython and I'm testing to use BLE with uPycraft V1.1 IDE. 
Reading this thread, I don't undestand one thing:
How can I build this branch `(https://github.com/micropython/micropython/compare/master...aykevl:bluetooth)` on my board ?

IDE: uPycraft V1.1 
Firmware: esp32-20181101-v1.9.4-683-gd94aa577a
Board: DOIT ESP32 - ESP-WROOM-32 - WiFi / Bluetooth

**Comment by maxwacker** [comment]
> How can I build this branch `(https://github.com/micropython/micropython/compare/master...aykevl:bluetooth)` on my board ?

The branch is here
https://github.com/aykevl/micropython/tree/bluetooth

By the way I report I succeeded to build&run this branch and was able to advertise and see the ESP32 device from another BLE device.

**Comment by aykevl** [comment]
You are right, I re-started work on it. Here is a draft PR: https://github.com/micropython/micropython/pull/4589

**Comment by dpgeorge** [comment]
Bluetooth (at least BLE) is now available on the esp32.

**Comment by def-py02** [comment]
@dpgeorge separate library?

**Comment by dpgeorge** [comment]
@def-py02 I don't understand your question.  Can you please explain what you mean by "separate library"?
