### ISSUE TITLE
ESP32: Kernel panic caused by machine.reset()

### ISSUE THREAD

**Issue by robert-hh** [micropython/micropython#3810]
Version:
(sysname='esp32', nodename='esp32', release='1.9.4', version='v1.9.4-84-g18e63584-dirty on 2018-05-22', machine='ESP32 module with ESP32')

Board: sparkfun ESP32 and Wemos LOLIN32

The commands to cause that are:
```
from machine import reset
reset()
```

**Comment by dpgeorge** [comment]
Thanks for the report.  I have come across this problem before but never looked into it, so I did just now and fixed it in df9b7e8f24384df446c98c10b28f4fb143d66d61

**Comment by robert-hh** [comment]
Agree. Because it finally performed a reset, it made not really a difference.
