### ISSUE TITLE
stm32: cannot compile due to missing lwip sources

### ISSUE THREAD

**Issue by rolandvs** [micropython/micropython#3819]
Just updated my fork and after make it ends up in:

```
make: *** No rule to make target `lib/lwip/src/core/inet_chksum.c', needed by `build-PYBV10/genhdr/qstr.i.last'.  Stop.
```

**Comment by dpgeorge** [comment]
You probably need to run a `git submodule update --init`

**Comment by rolandvs** [comment]
That doesn't seem to work :-(

`py.mk`  has `core/ipv4/inet_chksum.c` and directory contains the file...

**Comment by peterhinch** [comment]
I can't replicate this. The build scripts I use may be found [here](https://github.com/peterhinch/micropython-samples.git) `buildnew` followed by `buildpyb`.

**Comment by dpgeorge** [comment]
@rolandvs did you solve this problem?

**Comment by robert-hh** [comment]
I had this problem too, but "git submodule upate --init" solved that. I regularly forget that command.

**Comment by rolandvs** [comment]
I tried the above, but no succes. However due to time constraints I skipped this and used a fresh copy. That works fine. So I probably dit something wrong while updating from git. If it surfaces again I will make an effort to track it down.

**Comment by dpgeorge** [comment]
> So I probably dit something wrong while updating from git

Ok, so I'll close the issue then.  Feel free to reopen if neede.
