### ISSUE TITLE
ESP32 could not change the CPU freq

### ISSUE THREAD

**Issue by EliSu** [micropython/micropython#3832]
hi :
i use the MicroPython v1.9.4-25-ge6b66f10 on 2018-05-15, and i found that the CUP freq could not change with machine.freq(), is this cmd could not used in ESP32? or it is a bug?
here is the test results:

>>> import machine as m
>>> m.freq()
240000000
>>> m.freq(120000000)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: frequency can only be either 80Mhz, 160MHz or 240MHz
>>> m.freq(80000000)
>>> m.freq()
240000000
>>> m.freq(160000000)
>>> m.freq()
240000000
>>>

**Comment by danicampora** [comment]
You need to pass the frequency value in MHz, so either 80, 160 or 240. For instance:

```python
m.freq(120)     # change frequency to 120 MHz
```

**Comment by EliSu** [comment]
@danicampora

it still could not work, and the output is like below:

>>> m.freq()
240000000
>>> m.freq(80)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: frequency can only be either 80Mhz, 160MHz or 240MHz
>>> m.freq(160)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: frequency can only be either 80Mhz, 160MHz or 240MHz
>>> m.freq(240)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: frequency can only be either 80Mhz, 160MHz or 240MHz
>>>

**Comment by robert-hh** [comment]
There was and maybe still is a bug in the espressif library. The function is not supported yet, and the call to the library functions is commented out (.../ports/esp32/modmachine.c, line 71).

**Comment by dpgeorge** [comment]
> The function is not supported yet, and the call to the library functions is commented out

Yes, as far as I know it's not possible to change the EPS32 frequency on the fly (maybe someone can correcty me here?).  So it would be a good idea to raise an exception in machine.freq(freq) when trying to set it.

**Comment by EliSu** [comment]
@robert-hh  but i found the loboris/MicroPython_ESP32_psRAM_LoBo ESP32 dev, the machine.freq() could work, Is it because loboris changed the ESP-IF code to compile it instead of using the official ESP-IF?

**Comment by robert-hh** [comment]
Looking at the respective chapter in the ESP32 guide, it does not look easy (http://esp-idf.readthedocs.io/en/latest/api-reference/system/power_management.html#). And I did not check, whether the frequency check of the loboris port works.

**Comment by walterheisenberg** [comment]
Any news on this? Stil not working in v1.10
CPUfreq of 80MHz would be good for battery powered ESP32 to save energy.
Don't know, if Loboris code works, but it looks like it is here:
https://github.com/loboris/MicroPython_ESP32_psRAM_LoBo/blob/fff2e193d064effe36a7d456050faa78fe6280a8/MicroPython_BUILD/components/micropython/esp32/modmachine.c#L323

**Comment by dpgeorge** [comment]
Implemented in c33f53806630fcfa471dfc2c8338f79b5d820708
