### ISSUE TITLE
Pyboard - CC3200 WIFI 

### ISSUE THREAD

**Issue by diginfo** [micropython/micropython#3841]
Hi;

I am looking at enabling WIFI on the pyboard, specifically with CC3200 Module, but before I go ahead and order a bunch of them, can you confirm the required pins ?

I see that clk, cs, miso and mosi are GPIO14 - 17, but what about VBEN and IRQ ??

![screen shot 2018-06-05 at 12 12 53 pm](https://user-images.githubusercontent.com/6010010/40954995-01b6a572-68ba-11e8-9fff-7ff5d4408e5a.png)

Also, is the 3200 compatible with the 3000 ?

**Comment by dpgeorge** [comment]
> is the 3200 compatible with the 3000

No, it definitely isn't!  And I wouldn't recommend using the CC3000.  There is some support for the CC3100 module as external WiFi support but it's not in mainline (see eg https://github.com/emfcamp/micropython but that fork is quite old now).

**Comment by diginfo** [comment]
Damien, is there any current / proven support for a wlan connection on the pyboard ?

**Comment by diginfo** [comment]
I have succeeded in connecting a (firmware restored) 8266 using the code from here: http://www.tinyosshop.com/download/PYWIFI.zip - but how could this be integrated to work with nthe networking / wlan modules ?

**Comment by untitledlt** [comment]
is there any progress on this?

**Comment by dpgeorge** [comment]
There is no plan to support CC3200 as an external WiFi chip.  Support for CC3000 was removed in 1855df6361ad4ade62aa46ad08f3202a6a5b1bd1

There are many other options for WiFi, eg PYBD boards, Pico W, or using an esp32 as a coprocessor (Ublox Nina).
