### ISSUE TITLE
oofatfs‘s ftime no working?

### ISSUE THREAD

**Issue by junhuanchen** [micropython/micropython#3859]
f_write and `f_close` d'ont lead to `ftime` changed in my `esp32`.

i can get `ftime` in `oofatfs’f_stat`, but it not exist set `ftime` in ` f_wrtie`.

i need the value, how to changed code ?

**Comment by dpgeorge** [comment]
Thanks for the report, should be fixed by cf1509c911a1e1f983538105592575a8a520341f

**Comment by junhuanchen** [comment]
Great.
