### ISSUE TITLE
implement sys.settrace (or its subset)

### ISSUE THREAD

**Issue by prusnak** [micropython/micropython#3864]
We are thinking about implementing [`sys.settrace`](https://docs.python.org/3/library/sys.html#sys.settrace) or its subset. Currently, the most wanted is the `'line'` event (we are trying to create a very simple code-coverage tool using that). I think this feature should be an optional, enabled during the build-time via the compilation flag.

This feature is the first necessary step and can be later expanded to implement https://github.com/micropython/micropython/issues/3009 fully.

Do you have any pointers how to do that or has anyone done any experiments in that area?

// cc @matejcik @jpochyla

**Comment by dpgeorge** [comment]
`sys.settrace` is now implemented, see #5026
