### ISSUE TITLE
Cannot run "make" cammand

### ISSUE THREAD

**Issue by ziadelmolla** [micropython/micropython#3868]
Hello,
When in run the following command : 
make BOARD=NUCLEO_F429ZI
i get the following message : 
make: *** No rule to make target 'lib/lwip/src/core/def.c', needed by 'build-NUCLEO_F429ZI/genhdr/qstr.i.last'.  Stop.
Although i used the same command before and it worked perfectly fine.
Thanks in advance.

**Comment by dmazzella** [comment]
See #3819

**Comment by ziadelmolla** [comment]
Thank you for your help.
I cloned the repository with --recursive and the problem was solved.
