### ISSUE TITLE
Code cleanup - remove magic number for typecode references

### ISSUE THREAD

**Issue by adritium** [micropython/micropython#3873]
Replace magic number `0x80` with a macro everywhere `typecode` is used.

https://github.com/micropython/micropython/blob/564abb01a5526bd2d981791401e28774c7dcfe4c/py/objarray.c#L224-L226

**Comment by dpgeorge** [comment]
Thanks for the idea, done in c00ee200accb0f79fc2a7829ebe4567258ed40c0
