### ISSUE TITLE
stm32: improve timer dead-time and break configurability

### ISSUE THREAD

**Issue by dpgeorge** [micropython/micropython#3875]
Split off from #3869:

A nice feature of TIM1 is the TIM1_BKIN input to kill the PWM when something is wrong. The dead-time setup in timer.c takes a few parameters like enabling the BKIN and invert polarity. Now I made quick fix by changing the assigned values, however it would be nice if the dead-time configuration can be extended and also be set not only at the initialisation of the timer.

See timer.c at line 431, `STATIC void config_deadtime(...).`

**Comment by rolandvs** [comment]
@dpgeorge - this is "solved" in #3965

**Comment by dpgeorge** [comment]
Feature was implemented in edd0e0f93d180e79c1422d1eb7a9ec1954bb6d03
