### ISSUE TITLE
mp_type_StopAsyncIteration not implemented

### ISSUE THREAD

**Issue by adritium** [micropython/micropython#3898]
[Searching for mp_type_StopAsyncIteration](https://github.com/micropython/micropython/search?q=mp_type_StopAsyncIteration&unscoped_q=mp_type_StopAsyncIteration) indicates it's not implemented.

Is this correct current status or did someone forget to commit something?

If you [search for MICROPY_PY_ASYNC_AWAIT](https://github.com/micropython/micropython/search?q=MICROPY_PY_ASYNC_AWAIT&unscoped_q=MICROPY_PY_ASYNC_AWAIT), it's present in a bunch of places.

**Comment by dpgeorge** [comment]
It is implemented in py/objexcept.c, along with all the other exception types: https://github.com/micropython/micropython/blob/master/py/objexcept.c#L227
