### ISSUE TITLE
py/obj.h broken if floats disabled and MICROPY_OBJ_REPR_C used

### ISSUE THREAD

**Issue by nickovs** [micropython/micropython#3914]
The current code in the path through `py/obj.h` used when the object representation is `MICROPY_OBJ_REPR_C` is missing a test for the presence of floating point support around the bits that define floating point objects.

https://github.com/micropython/micropython/blob/b488a4a8480533a6a3c9468c2f8bd359c94d4d02/py/obj.h#L134-L168

**Comment by dpgeorge** [comment]
Fixed by d66c33cbd6bd144565c6cf24cebf711ee03704c2
