### ISSUE TITLE
[NUCLEO_F091RC] pyb.ADCAll(12,mask) some mask values freeze system

### ISSUE THREAD

**Issue by rolandvs** [micropython/micropython#3919]
Maybe related to #3917, also when using `pyb.ADCAll(12,MASK)` some masks will freeze micropython (at least REPL does not respond anymore and reset is the only thing to get out of it).

Instances that will freeze the system: `pyb.ADCAll(12)` and a mask value between `0x7FFF4` and `0x7FFFF`.

**Comment by dpgeorge** [comment]
> also when using pyb.ADCAll(12,MASK) some masks will freeze micropython

I think that's just because it disables the UART on PA2/PA3.

**Comment by rolandvs** [comment]
Aha that seems logical. Should there be a check for this?

**Comment by dpgeorge** [comment]
> Should there be a check for this?

It's not easy to do it in a smart way... and maybe the user does actually want to turn all pins to ADC.  Probably it's best to address this in the docs for ADCAll.

**Comment by rolandvs** [comment]
Documenting is one thing, but would it be wise to set the default mask not to (-1) but to the 0x700000 value for the internal sensors. In most other cases one would assign the analog channels per channel and not all of them at once.

**Comment by dpgeorge** [comment]
> but would it be wise to set the default mask not to (-1) but to the 0x700000 value for the internal sensors

That would be wise, but here we are trying to maintain existing behaviour, which for `ADCAll` was to put *all* pins in to ADC mode.

I'd like to revamp the `ADC` class in general, make it more consistent across ports, and also introduce something like `ADCBlock` which would allow to control an ADC peripheral block in a more user-friendly way, rather than the ad-hoc methods in `pyb.ADCAll`.

**Comment by rolandvs** [comment]
Ok, I cannot image why you would enable all adc channels at once as its use is in most cases very specific. Also earlier documentation imho showed that the example that fiddles directly with the registers was favoured as it did not have the side effects of ADCAll :-). I will use the mask and will PR the doc...

**Comment by rolandvs** [comment]
With the exception of disabling the UART when all GPIO is set to analog input it is well documented.
