### ISSUE TITLE
bug - type_attr doesn't check for .map.is_fixed == 1

### ISSUE THREAD

**Issue by adritium** [micropython/micropython#3921]
When `.py` code attempts to modify or delete a type's dictionary, the operation is _attempted_ even if `.map.is_fixed == 1`; this is incorrect behavior.

If the application _knows_ a `map` is fixed, why would it attempt to modify it?
If a type's `.locals_dict` is defined with `MP_DEFINE_CONST_DICT`, it could be placed in ROM and writing to ROM may lead to a processor exception which will NOT be caught with `nlr_t` mechanism.

https://github.com/micropython/micropython/blob/bccf9d3dcfd000b81b89b9ef862f9bc6104df99d/py/objtype.c#L1028-L1052

**Comment by dpgeorge** [comment]
> When .py code attempts to modify or delete a type's dictionary, the operation is attempted even if .map.is_fixed == 1; this is incorrect behavior.

Did you see b45c8c17f0f295e919a90659d4c1880a47b228c1 ?  That adds a check for this.
