### ISSUE TITLE
ESP32 BLE : Separate c task  to handle BLE actions

### ISSUE THREAD

**Issue by sanu-krishnan** [micropython/micropython#3974]
Hi,
Is there any stable implementation available to use BLE in esp32 micro-python?

If no, is it possible to use a separate c task `(defined in ports/esp32/main.c)` to take care of BLE actions? 
Can message queues/mailboxes be used to communicate between this ask and MP task?
Will stack sizes be a limiting factor?

It will be very helpful if anybody can give good suggestions.

**Comment by dpgeorge** [comment]
Please see #4589 for initial BLE support on the esp32.
