### ISSUE TITLE
cannot create an array of fixed size

### ISSUE THREAD

**Issue by adritium** [micropython/micropython#3981]
I need to create an array that can never be allowed to increase or decrease in size.

Without creating a new type, this cannot be done.

**Comment by dmazzella** [comment]
you can use a deque:

```
from ucollections import deque
d = deque((), 2)
```

**Comment by adritium** [comment]
That's a max size of 2, not a fixed size.

**Comment by dhalbert** [comment]
If you are storing numbers, you could use `array.array`. You could also create a class that implements `__getitem__` and __setitem__` so you could use `[]` subscripts, but there would be no other operations that could change the size

**Comment by dpgeorge** [comment]
A `memoryview` has a fixed size.

**Comment by adritium** [comment]
@dpgeorge 

Thanks that'll work.

@dhalbert I know I could create a new type but I feel like I've been doing that too much.
