### ISSUE TITLE
tests/extmod/ujson_dump_iobase.py always fails when MICROPY_STREAMS_NON_BLOCK  is disabled

### ISSUE THREAD

**Issue by boochow** [micropython/micropython#3990]
In `tests/extmod/ujson_dump_iobase.py`, `S.write()` does not return the number of bytes written.
`S.write()` returns always None so it causes always `EAGAIN` error.

In the case `MICROPY_STREAMS_NON_BLOCK` is enabled, `EAGAIN` would be ignored thanks to `mp_is_nonblocking_error(err)` defined in `py/stream.h` and `write()` does its task anyway successfully, the result of the test is correct.

However, in my thought the last line of `write()` should be `return len(buf)` because it should return None only when writing to stream is impossible for some reason.

**Comment by dpgeorge** [comment]
> However, in my thought the last line of write() should be return len(buf) because it should return None only when writing to stream is impossible for some reason.

Yes that's right, thanks for reporting!  Should be fixed by 571295d090d1eec40b45a88c2c5f54ceaf3c4e15
