### ISSUE TITLE
Crash in mp_obj_class_lookup when DEBUG_PRINT is active

### ISSUE THREAD

**Issue by BramEPC** [micropython/micropython#3999]
objtype.c/mp_obj_class_lookup contains the following (verison  1.9.4):

`#if DEBUG_PRINT`
`                printf("mp_obj_class_lookup: Returning: ");`
`                mp_obj_print(lookup->dest[0], PRINT_REPR); printf(" ");`
`                // Don't try to repr() lookup->dest[1], as we can be called recursively`
`                printf("<%s @%p>\n", mp_obj_get_type_str(lookup->dest[1]), lookup->dest[1]);`
`#endif`

mp_obj_get_type_str(lookup->dest[1]) crashes the system if dest[1] is not filled in by mp_convert_member_lookup (and remains null)  which is perfectly possible for a lot of cases...

**Comment by dpgeorge** [comment]
Thanks for the report, should now be fixed by b630dfcc1dc027bd049b4af9d25180f82c4051d9
