### ISSUE TITLE
Why qstr is passed by handle (instead of pointer)?

### ISSUE THREAD

**Issue by pfalcon** [micropython/micropython#4]
Is there any special design decisions why qstr's are referenced by index in a table, instead of direct pointers? Having extra indirection of course affects performance, especially for cached archs.

My first thought was about limiting value domain, but "qstr" type is still defined as uint, so generally takes same size as a pointer. Though I found that qstr's are stored in parse nodes as MP_PARSE_NODE_LEAF_ARG(pn), which takes 4 bits for kind. But for pointer that would mean that qstr should be 16-byte aligned. Probably too harsh for strings in constrained environment indeed. But on the other hand, if this is only required for parsing source code...

So, I wonder is there're more tricks/optimizations which assume that qstr's have limited value domain, of that's the only one?

**Comment by dpgeorge** [comment]
I don't see a reason to keep this open anymore.  Having small bytecode size (and hence compressed/indexed qstrs) is much more important than optimising for speed.  And there are places now in the code which assume only 16-bit of storage for qstrs (especially when persistent bytecode is enabled).

**Comment by pfalcon** [comment]
Ack. I try to to old ticket cleanup myself from time to time, and wanted to close these my "green naive" tickets too, but wanted to re-read them first to see what direction we went since then, but that doesn't happen for months, so just closing them sounds good.
