### ISSUE TITLE
Threading using _thread causes  segmentation fault, AttributeError:

### ISSUE THREAD

**Issue by mzakharocsc** [micropython/micropython#4008]
My micropython [program](https://pastebin.com/PTD0qE8U) is using queues and _thread API to schedule processing across multiple cores. It crashes with segfaults, or error messages like these:

> AttributeError: 'Bar' object has no attribute 'lock'
> Segmentation fault (core dumped)

or this:
> ../../py/gc.c:575: gc_free: Assertion `ATB_GET_KIND(block) == AT_HEAD' failed.

or  this:
> ../../py/gc.c:673: gc_realloc: Assertion `ATB_GET_KIND(block) == AT_HEAD' failed.

It sometimes takes hours, and sometimes minutes to run the program and experience a crash. Errors are not consistent, switching between AttributeError, gc_free Assertion, or a quiet segfault. Any suggestions on how to attempt to resolve this would be much appreciated. 

Micropython version: 1.9.4. Target: unix  (8-core x86-64 and 4-core ARM).  My ARM setup seems to reproduce this more often than x86. Also, compiling with DEBUG=1 increases the probability of occurrence

**Comment by aykevl** [comment]
I can imagine two possible causes:
* The memory allocator (py/gc.c) doesn't do proper locking.
* There is a memory corruption issue somewhere else.

See:
https://github.com/micropython/micropython/blob/master/py/gc.c#L99

**Comment by dpgeorge** [comment]
Is the GIL enabled or disabled in your case?  If you are using the standard unix configuration then the answer would be that the GIL is disabled.

**Comment by jonnor** [comment]
Information is missing to reproduce/debug the issue. Please provide the requested details, or we will have to close the issue.
