### ISSUE TITLE
RFC: Implementing generic generator protocol

### ISSUE THREAD

**Issue by pfalcon** [micropython/micropython#402]
So, we now have complete implementation of generator protocol - but for generators themselves. Here's proposal how to extend it to other compatible objects.

So, let there be 

```
mp_vm_return_kind_t mp_resume(mp_obj_t self_in,
mp_obj_t send_value, mp_obj_t throw_value, mp_obj_t *ret_val)
```

function which dispatch to mp_obj_gen_resume() if object is generator, to mp_iternext() if object supports C-level iterator protocol, and otherwise assume that it's ducktype generator and use dynamic method lookup.

Note that generator protocol is superset of iterator protocol, so the 2nd part of the proposal is to move ducktyping implementation from mp_iternext() to mp_resume(), and use the latter consistently in the interpreter.

**Comment by dpgeorge** [comment]
Generic iterators for user types have been available for some time now.  See eg `tests/basics/gen_yield_from_ducktype.py`
