### ISSUE TITLE
[BUG] Compile error: MICROPY_PY_BUILTINS_BYTEARRAY == 0 && MICROPY_PY_ARRAY == 1

### ISSUE THREAD

**Issue by adritium** [micropython/micropython#4048]
> undefined reference to `mp_type_bytearray'

When `bytearray` is disabled so is `mp_type_bytearray` but it's still used

https://github.com/micropython/micropython/blob/cbec17f2cd2712772bc57f3530d6d16f8552e155/py/objarray.c#L272-L280

**Comment by dpgeorge** [comment]
Thanks for the report, should be fixed by a785a3dbfb02f5df901e78dfc63cf31502677d82
