### ISSUE TITLE
STM32F439 random crashes (memory management/gc bug?)

### ISSUE THREAD

**Issue by ryannathans** [micropython/micropython#4077]
```
a = 1
while True:
	a *= 1.1
```

running 1.9.4 with double precision
stm32 appears to reset when executed

my understanding is that after a relatively small number of iterations the value of 'a' will become 'inf' and any further multiplication should result in 'inf' - as occurs manually e.g.

```
>>> a = 1
>>> a *= 1e+50
>>> a *= 1e+50
>>> a *= 1e+50
>>> a *= 1e+50
>>> a *= 1e+50
>>> a *= 1e+50
>>> a *= 1e+50
>>> a
inf
```

**Comment by peterhinch** [comment]
I can't replicate this on a Pyboard V1.1. The Pyboard, the Unix build and CPython 3.4.3 behave identically. The loop runs forever. If interrupted with ctrl-C, the value of `a` is `inf`.

```shell
/home/adminpete> repl
Entering REPL. Use Control-X to exit.
>
MicroPython v1.9.4-479-g828f771 on 2018-08-22; PYBv1.1 with STM32F405RG
Type "help()" for more information.
>>> 
>>> a = 1
>>> while True:
...     a *= 1.1
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
KeyboardInterrupt: 
>>> a
inf
>>> 
```

**Comment by ryannathans** [comment]
@peterhinch  are you compiling with double precision?

**Comment by peterhinch** [comment]
No.

**Comment by adritium** [comment]
> are you compiling with double precision?

@ryannathans there's two flags you need to set for double.

1. `MICROPY_FLOAT_IMPL`
2. the compiler's float flag i.e. [`-mfloat-abi=`](https://gcc.gnu.org/onlinedocs/gcc/ARM-Options.html#ARM-Options)

State your configuration for both of these

**Comment by ryannathans** [comment]
I just pass MICROPY_FLOAT_IMPL=double in when running make, the compiler float flag is handled by the make file

**Comment by adritium** [comment]
The flag is not correct

#define MICROPY_FLOAT_IMPL_NONE (0)
#define MICROPY_FLOAT_IMPL_FLOAT (1)
#define MICROPY_FLOAT_IMPL_DOUBLE (2)

**Comment by ryannathans** [comment]
the flag is checked here, what are you trying to say?

https://github.com/micropython/micropython/blob/master/ports/stm32/Makefile#L83

**Comment by ryannathans** [comment]
Not currently, I'm hoping someone else can reproduce the same issue when compiling with double precision

**Comment by dpgeorge** [comment]
@ryannathans I can't reproduce this problem.  I tried with single precision hardware on PYBv1.0, double precision software on PYBv1.0, and double precision hardware floating point on an F767.  All worked fine.

Please describe your complete set-up: hardware, software, compiler flags, compiler version, etc, so your issue can be reproduced.

**Comment by ryannathans** [comment]
@dpgeorge 

I'm running on a STM32F439VIT6 with 4MHz HSE
Compiling on Windows 10 Enterprise but in Windows Subsystem for Linux - Ubuntu 18.04.1
gcc --version is 7.3.0
arm-none-eabi-gcc --version is 6.3.1 20170620
using ''make -j12 BOARD=STM32F439 MICROPY_FLOAT_IMPL=double -C ports/stm32"

I'll try compiling for my PYBLITE V1.0 to see if I can reproduce on that

**Comment by adritium** [comment]
Can you put “print” statements so the loop index and value of `a` can be displayed?

And does it still crash?

**Comment by dpgeorge** [comment]
> I'm running on a STM32F439VIT6

It looks like that MCU has HW single precision, so I guess you use SW double precision (at least, that is how the Makefile will configure it).

You can use the `pyb.fault_debug(True)` function to help with debugging.

**Comment by ryannathans** [comment]
@dpgeorge cheers, I've only got a few more minutes spare. If I don't come to any conclusions I'll resume debugging later on today

@adritium let's find out.. will test now

**Comment by ryannathans** [comment]
Upon further debugging, I have discovered the problem does not occur unless main.py is deleted from the filesystem. Running my normal firmware, pushing control+c and then typing in the test does not cause the device to crash.

**Comment by ryannathans** [comment]
```
>>> pyb.fault_debug(True)
>>> a = 1
>>> while True:
...     a *= 1.1
...

```

the device just locks up instead of resetting

**Comment by ryannathans** [comment]
```
>>> a = 1
>>> while True:
...     a *= 1.1
...     print(a)
...

```

runs down until 


6.755260947508678e+283
7.430787042259546e+283
8.173865746485502e+283
8.991252321134054e+283
9.890377553247461e+283
1.08794153085722e+284
1.196735683942943e+284


Before crashing the same way

**Comment by dpgeorge** [comment]
> runs down until 1.196735683942943e+284

It sounds like it might be a memory/GC issue then.

> the device just locks up for a long time and eventually the COM port disappears and shows USB device not recognised instead of instantly resetting

That's because it's waiting forever in the hard fault routine.  If you attach a UART REPL  with `pyb.repl_uart(...)` then it will print the value of the registers at the point of failure, then you can see where it crashed.

**Comment by ryannathans** [comment]
And why does it work fine when I run my main.py

**Comment by dpgeorge** [comment]
> Why would it be a memory issue?
...
> And why does it work fine when I run my main.py

It's just my suspicion that it's a memory issue, based on the fact that the loop crashes before it gets to "inf", and that the same arithmetic operation outside the loop succeeds.  When main.py is/isn't loaded then the heap profile will be different when the loop runs, hence different outcome.

**Comment by adritium** [comment]
Do you have garbage collection turned on?

**Comment by ryannathans** [comment]
160576

**Comment by ryannathans** [comment]
that seems like too much, should only have 128k (or 192k including CCM)

**Comment by adritium** [comment]
I meant inside the loop we can see if memory is running out

**Comment by ryannathans** [comment]
Fixed!

added gc.threshold(10000) before running the loop

I think micropython is trying to use RAM that doesn't exist when it exceeds 128k. My firmware sets gc.threshold(10000) and that must be why it works when I run main.py

**Comment by adritium** [comment]
What board are you using ?

**Comment by ryannathans** [comment]
STM32F439VIT6 MCU on a custom PCB

**Comment by ryannathans** [comment]
Sorry, should be 192kB of SRAM (256kB including CCM)

**Comment by adritium** [comment]
Keep increasing the threshold until it fails

**Comment by ryannathans** [comment]
I believe this is the same bug that's occurring in an RTOS I've written when a certain number of tasks are loaded. Simply removing any one task results in stability. I'm printing out memory after each task and this is the last one I get.

I will shortly resume debugging this - I'll try to hook up to a UART and grab the debug info and collect as much information about this as I can using both the original example and this RTOS one.

```
stack: 972 out of 4294917120
GC: total: 161024, used: 85120, free: 75904
 No. of 1-blocks: 1690, 2-blocks: 304, max blk sz: 554, max free sz: 3360
GC memory layout; from 20004b00:
00000: MDhhhhMDMDMDhhhDDBBADh=MDDBBBSSh=Sh==Sh=Sh=BBBBBBhhSh=======hhSh
00400: h==Dh=h===h==h=Dhh========DhBh====hhhhh=========================
00800: ================================================================
00c00: ================================================================
01000: ================================================================
01400: ================================================================
01800: ================================================================
01c00: ================================================================
02000: ================================================================
02400: ================================================================
02800: ================Bhh=hhhhh======Dh======h===h=h====hhh==D.h=====h
02c00: ======================h=hhh=====h====hhh=Mhh=.DDMDh==.DhMDMDBh==
03000: DhhBhh==h=Dhh=h===BDhhhh=DBLhB.hhhhh========hBhh==DhBShhh===LhBB
03400: hh====h=======h=======================================BBBh.DDDh=
03800: ===h===hBLhBBhBBBh.hhh=======================h===.D.h=h====BL.BD
03c00: Bh==h===h===h===h=hDhDhhhhhTDhDh=DhTh=======DhTDhTDhDhDhTDhTDhhh
04000: Dh==DhDhhhhDh=DhDhhhDh=Dh=TDhhT===DhDhDhhhDh=Dh=Dh=Dh=Dh=Dh=Dh=D
04400: hLh=DhDhDhDhSh=MD..MhDBBBhBBBDBh===h====BDB.B=B.Bh==h===hB.LhLSh
04800: =h=======h..Dh=.hLh.hDhLhhhh=.hh=h.h=======DhLhhhh=Lh..DhLhhhh=.
04c00: h.hh.DhLSh==hhhh=LhhDShDhLhhhh=.hLhDDDhLhhhh=hhLhh=Dh=.hLh..DhLh
05000: hhh=.hLh..DhLhhhh=.h..h.DhLSh=hhhh=Lhh=Sh=DhLhhhh=.hD.h.DhLhhhh=
05400: Lhh=DhLhhhh=LhhLhhDhLhhhh=L.hhDhLhhhh=Sh====.DhLDhLhhhh=hLhhDhLh
05800: hhh=LhhLDhLhhhh=Lh=hDh=======hhLhhhh=LhhLhh=h=DhLh=hhhh=LhLhh.Dh
05c00: Lhhhh=hhh====h=============================h====h======h==h=====
06000: ===h==========hh====hh==hh====hh==hh==========hh============hh==
06400: ============================================================Lh..
06800: DhLhhhh=.hLhD.DhLhhhh=h===MDD.MB.B=BhBBhDBhh===h===h==B..DMDBBB.
06c00: Bh==h===DBBBhBBh.BhBh.BB=hh====h===h==DD.DDhMDMDD.DD.h==========
07000: =======TDhTDhTDhTDhTDhTDhTDhTDhTDhTDhTDhTDhTDhTDhTDhTDhTDhTDhTDh
07400: TDhTDhTDhTDhTDhTDhTDhTDhTDhTDhTDhTDhTDhTDhTDhTDhTh=hDhDhDhMMDBh=
07800: =h==BhhBBBBBB.B=.B=Bhh===h==h========h.DhDh==.DhBh=h===DhBBhh=hT
07c00: h===hDDhBBhBhhBhBhBBhBhBhhBh..Dh=====h===hBBhhBhh==.h===.DhhBDhB
08000: hhBhh==hh===.DhBBhhBhBhh==h===h=h=BhBhhBhThDBhh===h===hBBh..hBhh
08400: ==h===h====h==.h===========DhLSSh===h=====h====Dh==h=BBLBBhBBhBh
08800: hB=Bh=D..Lh===B.h.hSh=Bh==h==h==Sh=ShShShShShShh===..DDSSh==ShSh
08c00: Shh========h=h===D.BhhBh=h===h=====BhBBBBBBBBDh===.hBBh=.h======
09000: ==h=h=h=====.Dh====.MD...h=hDhMDD.MDh=BBBDh=DBBBBBBBhB=Bh===hDh=
09400: ====BBDBBhBhBhBhBhBhhBBBBh===h==h========hBBhhBBhh==h===h..hBhhB
09800: hh==Dh===hDBh=hh==h===h====MDMh===DDhD.hhShDBDhTTBhBhDDB=h===h==
09c00: =hBhhB=BhB=BDB=.Lh=====h===DhBBhhhhhB=h==h===BBhBDB=hh==B=h==h==
0a000: =Dh.B=h=h===h===hDh==BBh=DhhBBh===h===BDhBBhDB=BBBh...h====h===h
0a400: ====.MDh===MhD.Dh====h==MD...DB.B=h=.DDh=======.DBh=B=BhBDB.DhD.
0a800: ..B=h==h===.B=h=h===.DDBB.B=BhB..B=hhB=h====h===DhBD.B=hh=.B=h==
0ac00: B=h===h===========hB...B=B=hh===h===B=DhDh=.B=hBhBB=B=.B=Bhh===h
0b000: =====.DhDBBhB=BhBB.B=BhhB=hh.h===DB=h========LDDhhBhhh=h===.DBhB
0b400: BhhB=hDB=..DBhB=h====h===hhh==h===hDBDB=DB=hB=.B=hhB=hB=h=B=B=h.
0b800: DBB=h========h===h==B=B=B=DB=h=B=Dh===B=h=====hDBh=B=h=DhB=h===h
0bc00: ===Bh==B=B=B=hB=h=B=Bh===B=h=====.DBhB=hB=B=B=DB=h=B=h====h===.D
0c000: Bh=DB=B=B=.B=D.B=.B=h=B=B=.B=.B=h========h===hDBh==B=...DhB=h===
0c400: h===Bh===DB=B=h===h===Bh===DB=B=h===h===Bh=h=DB=B=h===h===Bh=h==
0c800: h===.DB..h==h===B=B=B=h=B=h===BB=h=====DBh=hB=B=B=h===Bh===hDBh=
0cc00: ==DB=B=h===h===B....DB=B=h===h===Bhh==DB=B=h===h===BD.h==B=h===.
0d000: DB..h==B=h===.DB..h==h===DB....DB=B=h===h===Bh===DB=B=h===h===B.
0d400: ...DB=B=h===h===B.Dh==B=h===h==================DB..h==B=h===LDBh
0d800: ThTDB=B=h===h===hBBhLB=hhB=h===hh===hDhBBhTB=hTB=.....B=h====h==
0dc00: =Thhh=h=h=====h====h=........TTh=======.h...hh.Lh..TTD....h==.TT
0e000: h=====h=h=============h=hLh===Thh.h=..h==h=T===h==hhBBhBhBBhBBBh
0e400: BhhBhBBhBhBBBh.h===h===h===========D....h===..SSMDh=h===========
0e800: =========================.hh=hh.....Fh==.h===============h=====S
0ec00: ....h===..Sh..........h==...........h...LAhh=====h....h=.hDDh=h.
0f000: .LhLhh===============================h=.Fh=..h..hhh=h=Dh=Th=...D
0f400: hh=======........h..h...h..h=...hD...h=hh=====..h=.h=AhDhh=h=.h.
0f800: .Ah=D.h=T=h========................................F..h.........
0fc00: ........h........hh=============================================
10000: ===================..................h=..L.......h..h===........
       (10 lines all free)
12c00: ......................................................DhhDDBBhhB
13000: B.BhB=hBBBBBhBhBhBhB.h===...h===========h===.MDh===M.D..D.Sh.Mhh
13400: ==DhBD.hMD..DhBhA.BhBBhBhhBh===.B=h=h===h=h=h===BBBhBBBhBB.h===h
13800: h=====h.....h=h===MD....DhBBh===hBBBhBBhBBBhBh.h===h...h========
13c00: .MD..Dhh====BBBhBh=====BBhBhBhBhBhBBBBhBh.h===h.hBh===========.h
14000: DA..MB.h..........................hBL...............h.....D.....
14400: ....h=...................................h=h=DM.DB..............
14800: ..h==================.....MD.BB.................................
14c00: .............................BBBBB........................h...D.
15000: ......DhB.DDh========h==========================================
15400: ================================================================
15800: =====================h=====h..hLh=BBBBhBBBhBBBB.h===hBh========h
15c00: ==BBhB.DhBBhBhBhBhBBBB.DBBB.Bh==Dh..Dh.Bhh=h===h===Bhh=h===.Dh.B
16000: hh=h===.DhBBhBhhBh..DBhh===h===BhBhBBBBBBBBhBBB.B=BBBBBh===Bh===
16400: =BBB.h===h=====hBBhBBhBh=======================h.h..hh====h===h=
16800: ===MDM.BD..D.DhBhh=..BBBBBBBBBB.B=BBB.h===h===h====h===BhBh=====
16c00: =========BBBBBBhBBhBhBh.h===hDh==h===========TTTTT....B.Th======
17000: ==h=======================h===...h====h===.MD...Dh==============
17400: ================================================================
17800: ===============h====h=BLhh=h.h===h..Mh==DM.D....DMD.hBh..D.B.BB=
17c00: .B=BBhB=h===h====h=======Dh===h===BhBhBBhBDDh=BLh=============Dh
18000: =Dh=Dh=Dh=Dh=Dh=Dh=Dh=Dh=Dh=Dh=Dh=Dh=Dh=Dh=Dh=Dh=Dh=Dh=Dh=Dh=Dh=
18400: Dh=Dh=Dh=Dh=Dh=Dh=Dh=Dh=Lh=======BBBBBhh=========BhBhBhBhBBhBh.B
18800: =hBBBhhBhBh.B=hBBhBhBhh==================h========.h===.DhBBhBBh
18c00: Bh.h.hh===h===h====.MD..h====DhBBh.hhBhh==h===A..MD.T===========
19000: =====================================================BhBhBhBhBhB
19400: BBBBBhBh=h=====.h==============h================================
19800: ================================================================
19c00: ================================================================
1a000: ===========================D.Bhh=h===h===h...h==................
       (52 lines all free)
27400: ................
```

**Comment by ryannathans** [comment]
@dpgeorge  @adritium 

Results from varying the threshold number:
```
>>> import gc
>>> gc.threshold(110800)
>>> a = 1
>>> while True:
...     a *= 1.1
...
```

less than 110842: stable maybe indefinitely
110842: MemoryError: memory allocation failed, allocating 16 bytes
110843: MemoryError: memory allocation failed, allocating 16 bytes
...
110847: after maybe 1 minute device crashes
110848: Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
MemoryError: memory allocation failed, allocating 16 bytes
110849: MemoryError: memory allocation failed, allocating 16 bytes
110850: MemoryError: memory allocation failed, allocating 16 bytes
110851: wtf?
```

>>> import gc
>>> gc.threshold(110851)
>>> a = 1
>>> while True:
...     a *= 1.1
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
TypeError: ▒▒ import gcwhi

```

110852: MemoryError: memory allocation failed, allocating 16 bytes
110853: MemoryError: memory allocation failed, allocating 16 bytes
...
110880: crash straight away
110881: MemoryError: memory allocation failed, allocating 16 bytes
greater than 110881: crash straight away


results of micropython.mem_info(True) after MemoryError: memory allocation failed, allocating 16 bytes
```

>>> import gc
>>> gc.threshold(110842)
>>> a = 1
>>> while True:
...     a *= 1.1
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
MemoryError: memory allocation failed, allocating 16 bytes
>>> import micropython
>>> micropython.mem_info(True)
stack: 500 out of 4294917120
GC: total: 161024, used: 688, free: 160336
 No. of 1-blocks: 21, 2-blocks: 8, max blk sz: 3, max free sz: 6849
GC memory layout; from 20004b00:
00000: h=hhhhSh==hhhhh=Th=hh=hBhh=B..hh==Fh=.B......h=...h=h...........
00400: ......................................F.........................
       (106 lines all free)
1b000: ........................................h.......................
       (48 lines all free)
27400: ................
```

**Comment by ryannathans** [comment]
It's incredible that we **can't allocate 16 bytes when there's 160k free ram**

**Comment by dpgeorge** [comment]
@ryannathans without this problem being reproducible on a stardard/official build it's hard to debug it.

Note that something is wrong with the stack limit because it reports 4294917120 bytes total stack.

Did you run all tests in the MicroPython test suite, including the stress tests?  They can help to show where errors are.

**Comment by ryannathans** [comment]
The problem ended up being two problems

1. A single faulty STM32F439VIT6 causing random crashes/resets when running code (but strangely not when idling on the REPL)
2. A bad linker change I had in a branch I was working on (I had RAM length incorrectly set)

When testing v1.9.4 tag without any custom changes, the crashes were from the bad STM32 (which is now fully dead - drawing far too much current and letting the magic smoke out). 

Today I found that v1.9.4 did not crash on other STM32F439VIT6 devices.

v1.9.4 with my linker file (to work with our bootloader) incorrectly set RAM length to 128k instead of 192k - this caused crashes and memory allocation exceptions.

Thanks for the assistance debugging - noticing the stack limit pointed me in the right direction.
