### ISSUE TITLE
Missing docs for machine.PWM for esp8266

### ISSUE THREAD

**Issue by brhumphe** [micropython/micropython#4079]
The docs for the [machine module](http://docs.micropython.org/en/latest/esp8266/library/machine.html#module-machine) do not include the `PWM` class, but the tutorial [does cover how to use `PWM`](http://docs.micropython.org/en/latest/esp8266/esp8266/tutorial/pwm.html) and it is in the quick reference.

**Comment by jonnor** [comment]
There appears to be documentation both at https://docs.micropython.org/en/latest/esp8266/quickref.html#pwm-pulse-width-modulation and the portable/generic https://docs.micropython.org/en/latest/library/machine.PWM.html
So I think this issue can be closed?
