### ISSUE TITLE
Zero-out heap in gc_init()

### ISSUE THREAD

**Issue by adritium** [micropython/micropython#4086]
In `gc_init()`, only the "accounting" blocks are reset.

https://github.com/micropython/micropython/blob/828f771e327b932afc4865dbec53ce567dce45f5/py/gc.c#L140-L147

Therefore, when a soft-reset occurs, objects may still be in memory if the code before uPy does not reset the RAM.

**Comment by aykevl** [comment]
In what way is this a problem?
Memory is uninitialized at (soft) reset, so it could contain anything (including data from before the reset). The GC zeroes memory before giving it out so the rest of MicroPython never sees uninitialized memory.

Zeroing memory at reset has a cost in startup time (I don't know how big) for no real benefit.

**Comment by adritium** [comment]
Oops. Yes it does zero-out the new memory.
