### ISSUE TITLE
undefined reference to `strtod'  undefined reference to `strtol'

### ISSUE THREAD

**Issue by Aslm** [micropython/micropython#4099]
Hello, I want to compile my own package into micropython, but I am getting an error when compiling. The error message is:
undefined reference to `strtod'
undefined reference to `strtol'
How can I do? thank you.

**Comment by adritium** [comment]
This question belongs in the forum

https://forum.micropython.org/index.php

**Comment by adritium** [comment]
Please close this issue since you migrated it to the forum.
