### ISSUE TITLE
When calling MICROPY_PORT_DEINIT_FUNC, tests for MICROPY_PORT_INIT_FUNC instead

### ISSUE THREAD

**Issue by pfalcon** [micropython/micropython#4112]
@stinos this line https://github.com/micropython/micropython/commit/5ed284a15e028e0435f3b6e0773e14225d8f165d#diff-1c5b9ab6f204d3f8724a0168cc50b868R96 in 5ed284a15e : As you can see, it tests for **INIT** when calling **DEINIT**. That's either typo or thinko. It's confusing, and why require a port to define INIT if it just wants to have DEINIT? Can you please take care of that?

**Comment by stinos** [comment]
Good find, definitely a copy-paste error..

**Comment by dpgeorge** [comment]
Fixed by 89516b2b62faa1a75f4f6ff0fa1ab362aa193013
