### ISSUE TITLE
objarray: ->free counter is not properly maintained

### ISSUE THREAD

**Issue by pfalcon** [micropython/micropython#4127]
As reported by @jpochyla here https://github.com/micropython/micropython/issues/4087#issuecomment-418625185 . ->free is not maintained properly across different array operations. As nobody reported segfaults, it's probably safe in that respect, but memory allocation doesn't work as expected, so it should be fixed.

**Comment by pfalcon** [comment]
And before going for that, the fact that ->free is used for completely different purpose in case an objarray encodes a memoryview, should be addressed. I.e. an alias introduced and used in appropriate places.

**Comment by dpgeorge** [comment]
Fixed by acfbb9febd024475bdcb4ebbe2ec8c0e9a652275
