### ISSUE TITLE
bug: lex->source_name used after lex is freed

### ISSUE THREAD

**Issue by adritium** [micropython/micropython#4128]
https://github.com/micropython/micropython/blob/b9ec6037edf5e6ff6f8f400d70f7351d1b0af67d/examples/embedding/hello-embed.c#L43

[From forum](https://forum.micropython.org/viewtopic.php?f=3&t=5251)

> Since mp_parse will free the lexer at the end, the lex->source_name argument of mp_compile is using memory that is not valid anymore.

**Comment by dhylands** [comment]
Should be addressed by #4129 (if that gets nerged)

**Comment by dpgeorge** [comment]
Fixed by 1a2c511e5d0841a25c5e86f41dbfc50d94a18b50
