### ISSUE TITLE
RFC: PyPI packaging guidelines

### ISSUE THREAD

**Issue by pfalcon** [micropython/micropython#413]
Let's discuss conventions and guidelines when publishing modules on PyPI - for "stdlib" (#405, https://github.com/micropython/micropython-lib), and in general.

Terminology: https://docs.python.org/3.3/distutils/introduction.html#distutils-specific-terminology

Proposal: if distribution wants to show strong affinity for being used with MicroPython (that's in particular 100% the case for micropython-lib), it's name should start with a standard prefix. Given our existing choices for long, fully explicit names, the prefix almost certainly should be "micropython-". That's long, but fully self-describing. So, last chance for a big crowd to shout "It's too long" and propose something shorter.

**Comment by cloudformdesign** [comment]
I don't understand how "upy"  is not descriptive.  What else is called upy?

**Comment by PakchoiFood** [comment]
What would you do if you wanted to use SQLite3 on pyboard to indicate the absence of the "import ffi" module?

**Comment by dpgeorge** [comment]
@PakchoiFood your comment doesn't make sense for this issue, did you post in error?

**Comment by dpgeorge** [comment]
uPy-specific packages have been published using the `micropython-` prefix for the package name, and upip has been working well for quite some time on unix and (wifi-enabled) baremetal ports.  So closing this issue.

**Comment by pfalcon** [comment]
Yeah, but this ticket was supposed to be open, so people were able to find it and learn how to make a uPy-compatible package.

**Comment by dpgeorge** [comment]
> people were able to find it and learn how to make a uPy-compatible package.

IMO that's more suitable for documentation.

**Comment by pfalcon** [comment]
But we don't have such documentation, and this ticket is all we have.

**Comment by dpgeorge** [comment]
> But we don't have such documentation, and this ticket is all we have.

The README.md of the micropython-lib repo has some documentation, and points to this ticket for further reading.  I don't see the need to keep this one open (it's still searchable and commentable if necessary).  Feel free to take bits from here and add to the micropython-lib README.md if you think that's useful.
