### ISSUE TITLE
esp8266: functions, generators don't support __name__

### ISSUE THREAD

**Issue by pmp-p** [micropython/micropython#4136]
Hi while trying to pause/patch/resume coroutines indexed by their names in a live program i found a little divergence 

```
async def func():pass
print( func.__name__)
```
µpython : `AttributeError: 'generator' object has no attribute '__name__'`

cpython 3.7 : `func`

**Comment by dpgeorge** [comment]
I think this was implemented in e2e22e3d7e29985579b2c91c639c71229422f349.  Please try the latest version of MicroPython.

**Comment by pmp-p** [comment]
yeah found that both MICROPY_PY_BUILTINS_COMPILE and MICROPY_PY_FUNCTION_ATTRS are unset. So maybe activating those features is not obvious if you did not read an mpconfigport.h for a port you do not care for.

**Comment by dpgeorge** [comment]
Yes you're right, this feature is not enabled on esp8266.  So I guess this issue is about whether or not to enable it on esp8266.

**Comment by jonnor** [comment]
Proposing to not enable this on ESP8266 by default, since it is severely constrained on program space. Those that need it can use a custom board definition.

**Comment by dpgeorge** [comment]
> Proposing to not enable this on ESP8266 by default, since it is severely constrained on program space.

Yes, I agree.

And we now use ROM level features, so it's a bit easier to see what is enabled/disabled on esp8266.
