### ISSUE TITLE
Forum is down

### ISSUE THREAD

**Issue by adritium** [micropython/micropython#4138]
![image](https://user-images.githubusercontent.com/33403260/45554095-94766580-b803-11e8-880d-d761d2b39ca2.png)

**Comment by dpgeorge** [comment]
Thanks for the report.  The issue was that the MySQL process hit the 2GiB limit of the 32-bit address space (the server has plenty more RAM though).  Restart it all seems to have helped, at least for now.

**Comment by dpgeorge** [comment]
Thanks, it's been restarted again.

**Comment by dpgeorge** [comment]
The server was updated to a 64-bit machine, so hopefully this MySQL out-of-memory error doesn't happen again.  See #4403.
