### ISSUE TITLE
Update hosted STM32F4DISCOVERY Firmware

### ISSUE THREAD

**Issue by johnthagen** [micropython/micropython#4139]
#83 added support for the [STM32F4DISCOVERY](https://github.com/micropython/micropython/wiki/Board-STM32F407-Discovery), but the latest available pre-built firmware online is only 1.9 (latest is 1.9.4): https://micropython.org/download/#other

Could the latest release be posted for this board?

**Comment by dpgeorge** [comment]
Thanks for the report, now fixed.
