### ISSUE TITLE
wiki.micropython.org is down

### ISSUE THREAD

**Issue by johnthagen** [micropython/micropython#4144]
On [micropython.org](https://micropython.org/), the Wiki link at the bottom points to an invalid link: http://wiki.micropython.org/ (502 error)

Should it be https://github.com/micropython/micropython/wiki instead?

**Comment by peterhinch** [comment]
No, that is the developer wiki. The link is to the user wiki, which is currently down.

**Comment by dpgeorge** [comment]
The user wiki should be working again.

**Comment by peterhinch** [comment]
It is!

**Comment by peterhinch** [comment]
@dpgeorge It is down again.

**Comment by dpgeorge** [comment]
Thanks for the report.  It's strange that it keeps going down.  I restarted it and enabled more verbose logging to hopefully catch the issue next time.
