### ISSUE TITLE
importlib.util.find_spec missing

### ISSUE THREAD

**Issue by Hermann-SW** [micropython/micropython#4148]
Created per this forum request
[https://forum.micropython.org/viewtopic.php?f=2&t=5268#p30189](https://forum.micropython.org/viewtopic.php?f=2&t=5268#p30189)

for "How to check if a python module exists without importing it".

**Comment by adritium** [comment]
Please rename the issue to `help("modules") doesn't list the modules imported as files`

**Comment by adritium** [comment]
https://github.com/micropython/micropython/blob/4a1edd83829d6d78ca5d172ad87e1f4a3802b483/py/builtinhelp.c#L81-L98

Nowhere does it query the files on the filesystem.

**Comment by adritium** [comment]
This capability is not exposed to Python but it's trivial to implement in C and then expose to Python (if you're comfortable with C programming).

Look at function `mp_builtin___import__` . . .

https://github.com/micropython/micropython/blob/87231132d451e7413dbb97cae74d89721c41634b/py/builtinimport.c#L249

. . . and the functions `find_file`, `stat_dir_or_file`, `mp_import_stat_any`

**Comment by peterhinch** [comment]
The preferred solution would be to write a "micro" version of `importlib` and submit a PR.

While `importlib` has uses they are specialised. In the great majority of cases you'd simply try the import and trap the exception: this fits the [EAFP paradigm](https://en.wikipedia.org/wiki/Python_syntax_and_semantics#Exceptions). I'd question the statement:

> As described in that thread test importing module as below is bad at least for MicroPython because that uses memory:

I believe exception handling uses the stack rather than the heap, so the RAM is reclaimed.

**Comment by adritium** [comment]
When you import, code is compiled to bytecode and remains in RAM.

**Comment by peterhinch** [comment]
In most cases you want to use the module and take action if it is not present.

One of the use cases for `importlib` is the special case of checking the availability of a module without using it; there are other rather specialist use cases. So a "micro" version of `importlib` would be handy if someone feels like writing it.

**Comment by sylatupa** [comment]
I'm presently trying to import a module by its file name, and I'm seeing that the importlib.util would do the trick.
I vote for a micro version of importlib :+1:  :)

**Comment by sylatupa** [comment]
I was actually able to find a descent work around using __import__ to import by file name.

**Comment by pfalcon** [comment]
> I was actually able to find a descent work around using `__import__` to import by file name.

It's not a workaround, it's how it's supposed to be done in the *Python language*.

Conversely, importlib is just a CPython-specific module, 3rd or 4th they have, to add more bloat to their library.

**Comment by sylatupa** [comment]
Great! It worked like a charm. I had to add the the folder the module was in, using the sys.path append. There probably are alternatives. But thank you for the follow up.

**Comment by jonnor** [comment]
There seems to be ways to solve the concrete usecases people have raised here. Having a full (or partial) `importlib` implementation, compatible with CPython would be great. But that should probably be done in micropython-lib (or as a third party module). https://github.com/micropython/micropython-lib
So I propose to close this issue.

If there are critical functionality that must be implemented in the MicroPython VM (cannot be done in plain Python) to implement valuable importlib functionality, then specific issues can be created for that.
