### ISSUE TITLE
Invalid RST link in timer tutorial docs

### ISSUE THREAD

**Issue by johnthagen** [micropython/micropython#4154]
> see the [switch tutorial] (tut-switch) for an introduction to callback functions

This does not render correctly as a link in RST (it's a Markdown-style link): https://docs.micropython.org/en/latest/pyboard/pyboard/tutorial/switch.html

**Comment by johnthagen** [comment]
There is another mis-formatted link in the servo tutorial:

> see eg [Wikipedia] (http://en.wikipedia.org/wiki/Servo_%28radio_control%29)

https://github.com/micropython/micropython/blob/master/docs/pyboard/tutorial/servo.rst

**Comment by dpgeorge** [comment]
Thank you for the report.  Fixed by ad4fb62f13ba8c91aacb9097243180d38f941d2a
