### ISSUE TITLE
re: regex doesn't parse newline

### ISSUE THREAD

**Issue by shawwwn** [micropython/micropython#4159]
`re.sub(r'\n', 'xxx', 'aaa\n')` 
come out as:
`aaa\n`

In CPython it is:
`aaaxxx`

**Comment by adritium** [comment]
What happens if you add a `r` to the last expression like in the first one?

**Comment by dpgeorge** [comment]
This is a duplicate of #3176: the current implementation of ure doesn't support some escape characters.  The workaround for the time being is to use non-r strings, eg `re.sub('\n', 'xxx', 'aaa\n')`
