### ISSUE TITLE
http://micropython.org/live/ is frozen, add a reset mechanism

### ISSUE THREAD

**Issue by adritium** [micropython/micropython#4162]
Queue is not being emptied.

![image](https://user-images.githubusercontent.com/33403260/45707668-9155df00-bb4d-11e8-96a7-200a9aa08bc7.png)

**Comment by kamikaze** [comment]
queue should be executed, something is wrong with execution

**Comment by adritium** [comment]
What happens if someone puts infinite loop?
Is there a timeout?

**Comment by peterhinch** [comment]
Do you really think that thought never occurred to Damien? :-) Surely the first thing a budding script kiddie would try...

**Comment by mcauser** [comment]
Open source it and I'll setup another one in my office for random internet users to play with

**Comment by jonnor** [comment]
This is not online for years now... To play with MicroPython in the browser, try https://micropython.org/unicorn/
