### ISSUE TITLE
Board with the most UART at 9 bit

### ISSUE THREAD

**Issue by Craigzyc** [micropython/micropython#4165]
I'm trying to find the board with the most available UART ports with 9 bit support. 

This file seems to suggest there are 5 uarts on the NUCLEO_F429ZI but from what I can tell the chip only has 4. Is this a mistake?
https://github.com/micropython/micropython/blob/master/ports/stm32/boards/NUCLEO_F429ZI/mpconfigboard.h

Processor product page.
https://www.st.com/en/microcontrollers/stm32f429zi.html

Also the documentation for micropython has no clarification of what does and does not support 9 bit, are there any other ports other than the STM32 that has 9 bit support?

Thank you

**Comment by dpgeorge** [comment]
This is really a question for the forum: https://forum.micropython.org

An answer in short: nRF5x, esp8266 and esp32 only support up to 8 data bits.  STM32 parts support 9 bits.  The F429 has 4 USARTs and 4 UARTs, so 8 in total.
