### ISSUE TITLE
[STM32L476] return from pyb.stop() affects working of ADC

### ISSUE THREAD

**Issue by rolandvs** [micropython/micropython#4178]
It seems that when using the STM32L476 port the use of pyb.stop() and returning from it with rtc.wakeup() do not reenable all used peripherals or clocks (assumption). So even though the program continues from where it left off, some peripherals are affected.

USB is lost which is logical as the connection will be broken... so that is expected.
But see #4022 for the effect it has on the ADC and maybe some more peripherals...

**Comment by dpgeorge** [comment]
Thanks for the report.  This should be fixed by 1acf58c08f0f29408522a99cc7ef1d6270c21c09 (that commit also fixes STM32F7xx behaviour as well).

**Comment by rolandvs** [comment]
@dpgeorge thanks a lot! Did not check yet, but can we expect the same with the H743? At least another PLL is used for the USB, however did not check if it has similar behaviour yet...

**Comment by dpgeorge** [comment]
> Did not check yet, but can we expect the same with the H743

I'm not sure about the H7 for this case.  The H7 still needs a lot of features added, so that will be addressed later.
