### ISSUE TITLE
The example propgram, ubluepy_eddystone.py, does not run

### ISSUE THREAD

**Issue by rlcase** [micropython/micropython#4179]
While testing out my NRF port to the nRF52840-MDK [https://wiki.makerdiary.com/nrf52840-mdk/](https://wiki.makerdiary.com/nrf52840-mdk/), the BLE eddystone example found at
[https://github.com/micropython/micropython/blob/master/ports/nrf/examples/ubluepy_eddystone.py](https://github.com/micropython/micropython/blob/master/ports/nrf/examples/ubluepy_eddystone.py)
issues the following error:
`OSError: Can not fit data into the advertisment packet.`

I am assuming example code should work.

Rich

**Comment by aykevl** [comment]
I don't know why it doesn't work but maybe @glennrub knows more.

**Comment by glennrub** [comment]
Thanks @rlcase for raising the Issue.

I took a look at it and could reproduce it very quickly. Basically the example is ok, but the driver used wrong value for max advertisement packet size. 
I pushed what i believe is the fix in PR #4180.

**Comment by rlcase** [comment]
Wow, that was fast. Thanks.

**Comment by glennrub** [comment]
I'm closing this issue as PR#4180 has been merged and should have resolved the bug.
