### ISSUE TITLE
cc3200 upip error 

### ISSUE THREAD

**Issue by m2030** [micropython/micropython#4203]
recently i run micropython  on my simplelink CC3200 LaunchPad as steps : 
[(http://processors.wiki.ti.com/index.php/User:Dbartlett/MicroPython_CC3200)]
but i cant find upip and i have not find any way to install it on my board 
has any one find way to install?
  the error from repl as [following]
` import upip
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: module not found`

**Comment by m2030** [comment]
Thanks Mr.Peter it is done

**Comment by pfalcon** [comment]
The simple answer to this question is that upip is shipped as builtin only with unix, esp8266 (and probably esp32) ports. For all other ports, upip should be installed manually to the filesystem first.

**Comment by m2030** [comment]
Thanks for your concern
I wonder if I installed it to lib directory or other directory(sys,cert)?

**Comment by jonnor** [comment]
upip has been replaced by mip, see https://docs.micropython.org/en/latest/reference/packages.html
