### ISSUE TITLE
Is there any example code for manipulating the registers on the nRF52?

### ISSUE THREAD

**Issue by rabbithat** [micropython/micropython#4208]
Simply put, I'd like to use Nordic's so-called "proprietary" radio modes (i.e. not bluetooth _per se_), and unless there's already a micropython library which supports that (?), then I will need to manipulate the registers directly to send and receive packets.  I've done this successfully using C, but I'm completely new to micropython and therefore unsure whether micropython will allow me access the nRF52 hardware directly, and, if so, how to go about it.

Not sure if this is the right place to ask this question (?), so if not, please advise where I should post it instead.

**Comment by peterhinch** [comment]
I suggest posting in [the forum](https://forum.micropython.org/).
