### ISSUE TITLE
[STM32] stm32h743.ld has wrong flash size

### ISSUE THREAD

**Issue by rolandvs** [micropython/micropython#4240]
The `stm32h743.ld ` file on the latest version has a wrong setting for the Flash memory size:

```FLASH (rx)      : ORIGIN = 0x08000000, LENGTH = 1024K```

The size should be 2048K.

**Comment by dpgeorge** [comment]
Thanks for the report, fixed by d2c5496894b71ad868c7fd876a436410482d8c51
