### ISSUE TITLE
help with wlan driver for pyboard

### ISSUE THREAD

**Issue by diginfo** [micropython/micropython#4255]
On and off over the last 4 months I have been writing a PYBOARD socket purely in micropython which uses the esp8266 and have successfully tested it in server and client mode for things like http server, http client and with the mqtt client.

But I have had to write my own 'soft' socket class and to use it need to overwrite the built-in socket:

`import espsock as socket`

I can then do things like:

`socket.connect(addr) `

My existing code actually provides the socket class which is written from scratch, but what I am unsure about is, is this the way to do it, or should I 'somehow' interact with the default socket by creating a driver instead.

And if so, how does the built-in socket class know about my device ??

I know nothing about C or C++ and therefore only want to do this in python, so how would I go about creating a driver that the built-in socket can talk to or is my existing approach to provide my own socket class correct ?

Th examples I have found show this:

```
import network
nic = network.CC3K(pyb.SPI(2), pyb.Pin.board.Y5, pyb.Pin.board.Y4, pyb.Pin.board.Y3)
nic.connect('your-ssid', 'your-password')
while not nic.isconnected():
    pyb.delay(50)
print(nic.ifconfig())

# now use socket as usual
...
```

> now use socket as usual

What exactly does this mean ?

`import socket as s ## < built in socket`

OR

`s = nic.socket ## < use the socket provided by nic `

Thanks !

**Comment by dpgeorge** [comment]
> > now use socket as usual
> 
> What exactly does this mean ?

It means to do `import socket` and use this standard builtin class as usual for socket operations.  The nic's configured by the `network` module will hook into the builtin `socket` module.

> I know nothing about C or C++ and therefore only want to do this in python, so how would I go about creating a driver that the built-in socket can talk to or is my existing approach to provide my own socket class correct ?

If you've already implemented it in pure Python then I wouldn't change a thing, the way you have done it is correct.  There is currently no way to hook a pure Python-implemented NIC into the builtin `socket` module.

In the future these kinds of questions are best raised at the forum https://forum.micropython.org
