### ISSUE TITLE
ESP8266: UART not working

### ISSUE THREAD

**Issue by xandatspain** [micropython/micropython#4263]
I have a NodeMCU board with ESP8266.

MP version is: `MicroPython v1.9.4-272-g46091b8a on 2018-07-18; ESP module with ESP8266`

Also I have an IR controller attached to it. The problem is the UART is not working at all, not reading and I suspect no writing also. The IR controller works on RPi2 and the commands are copied as is from there.

I attach the code which is not working:

```
def test():
    import uos, machine, time, sys

    # detach repl
    uos.dupterm(None, 1)
    
    uart = machine.UART(0)
    uart.init(9600, bits=8, parity=None, stop=1)

    # do my stuff here
    #bytes_written = uart.write(bytearray(b'\xfa\xf6'))
    bytes_written = uart.write(bytes([0xfa, 0xf6]))
    time.sleep(5)
    #bytes_written = uart.write(bytearray(b'\xfa\xf2'))
    bytes_written = uart.write(bytes([0xfa, 0xf2]))
    time.sleep(5)
    
    frame = bytearray(25)
    uart.readinto(frame)
    
    # attach repl back
    uos.dupterm(machine.UART(0, 115200), 1)

    print('Written: ' + str(bytes_written))
    print('Read: ' + str(frame))
```
bytes_written = 2, but the frame is always filled with zeros. The connection to REPL is done via serial/usb.

Thanks in advance.

**Comment by peterhinch** [comment]
Please close this issue. Support queries should be directed to [the forum](https://forum.micropython.org/) rather than to this MicroPython bug tracker.
