### ISSUE TITLE
ESP32: PWM.deinit() cannot close  pwm output?

### ISSUE THREAD

**Issue by qiren123** [micropython/micropython#4273]
for example：
```
from machine import PWM,Pin
from time import sleep
def test(pin):
    pwm=PWM(Pin(pin))
    pwm.init()
    pwm.freq(500)
    sleep(2)
    pwm.deinit()
test(25)
test(32)
```
the pin25 outpus   PWM waves until the end of   'test(32)' 
pwm.deinit() couldn't finish the pwm

if we run this program again, pin25 and pin32  output PWM at the beginning of the program until the end

**Comment by dpgeorge** [comment]
Thanks for the report.  The issue was that, after deinit(), the pin was still connected to the PWM output and when the PWM was started again (even on a different pin) the old pin would still see the signal.  Should be fixed by 9c6c32cc510dd01f5e37a4e03c403718fe51c98a
