### ISSUE TITLE
NRF - Ctrl-E Fatal Exception

### ISSUE THREAD

**Issue by diginfo** [micropython/micropython#4276]
Pasting any simple multi line code appears to crash the device:

```
MicroPython v1.9.4-674-g27ca9ab-dirty on 2018-10-28; holyiot_18010 with NRF52840
Type "help()" for more information.
>>> 
paste mode; Ctrl-C to cancel, Ctrl-D to finish
=== def bytes_to_str(bytes):
=== FATAL: uncaught exception 20003dd4
MemoryError: 
```

As soon as it hits the second line, it crashes.

If I pasted these directly into the REPL without CTRL-E then there's no problem.

**UPDATE**
OK, the same thing happens in the REPL, if I paste a single line then all is good, if I paste multiple lines then it crashes.

**Comment by glennrub** [comment]
Hi @diginfo,

I believe i have seen this before, but have forgotten what triggers this. I wonder if @dpgeorge is onto something. To isolate this a bit, does this error occur bluetooth UART REPL or regular UART REPL? and if on regular UART, is flow control  on UART enabled or disabled?

**Comment by diginfo** [comment]
Thanks for helping

It is when using the uart with no flow control 

I am using holyiot 52840

**Comment by jonnor** [comment]
Does this still happen in the lastest versions of MicroPython, such as 1.23+?

**Comment by robert-hh** [comment]
Ctrl-E for paste mode works meanwhile. Tested on a NRF52840 board.
