### ISSUE TITLE
Touch Pad Error

### ISSUE THREAD

**Issue by Fuermohao** [micropython/micropython#4313]
Touch pad error
```python

>>> import machine
>>> from machine import Pin
>>> t = machine.TouchPad(Pin(32))
>>> t.read()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Touch pad error
```

_Originally posted by @Fuermohao in https://github.com/micropython/micropython/pull/3531#issuecomment-440129205_

**Comment by Fuermohao** [comment]
my board is NodeMCU-32S.
![rtc-gpio](https://user-images.githubusercontent.com/18239246/48816356-d3351880-ed7c-11e8-953e-9de5c4a6d450.png)

**Comment by nickzoic** [comment]
Thanks!  If you can please also add in details of which touch channels (all of them? only some of them?) are affected that'd help a lot.
`ports/esp32/machine_touchpad.c:mtp_read()` returns that error for any return from the ESP-IDF function `touch_pad_read` other than ESP_OK ... that might occur if the pin is not oscillating ...  Is anything else attached or is this reproducible on just the bare board?


https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/peripheral/touch_pad.html#_CPPv214touch_pad_read11touch_pad_tP8uint16_t

**Comment by Fuermohao** [comment]
@nickzoic 
> If you can please also add in details of which touch channels (all of them? only some of them?) are affected that'd help a lot.
ok, but I still need some time to figure out.

**Comment by Fuermohao** [comment]
@nickzoic 
 I only found this pin layout. As for schematic I didn't find it.

**Comment by Fuermohao** [comment]
![image](https://user-images.githubusercontent.com/18239246/48818200-15faee80-ed85-11e8-973b-83efdf9e579a.png)


@nickzoic  I tried this @MrSurly  
It seems a little different from yesterday.

Further, I found that when I touch the touchpad, an error is triggered and it will not be released.
![image](https://user-images.githubusercontent.com/18239246/48818096-81908c00-ed84-11e8-9ee4-f29e184719bd.png)

**Comment by Fuermohao** [comment]
![image](https://user-images.githubusercontent.com/18239246/48818300-a2a5ac80-ed85-11e8-9901-97dae8676dee.png)
here is my breadboard wiring diagram

**Comment by nickzoic** [comment]
Oh!  What's the little red module?
If it's one of these kind of things
https://sktechworks.ca/product/tp223-capacitive-touch-module/ you don't
actually need it, the ESP32 has that function built in ...
Try removing the module and just touching the yellow wire!

Alternatively, if you want to use the module for some other reason, you
can treat the GPIO32 as a normal logic input pin.

**Comment by Fuermohao** [comment]
oh！I got it... I am so stupid...
I removed it, now GPIO32 works fine.
So let's just shutdown this issue.

**Comment by nickzoic** [comment]
I'm glad we were able to help!
Have fun!
