### ISSUE TITLE
esp32 DAC bits 12 does not work?

### ISSUE THREAD

**Issue by Fuermohao** [micropython/micropython#4326]
I tried to set the `bits=12` when I used dac on pin 25 or 26
but `dac.write(value)  ` can not work when I set the value in range (255,4096)
```python
>>> d = DAC(Pin(25, Pin.OUT), bits=12)
>>> d.write(4000)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Value out of range
```

is this implemented?

**Comment by MrSurly** [comment]
The DAC on the ESP32 is 8 bit, thus 0-255.  This is probably a (lack of) documentation problem for the ESP32 platform.

**Comment by Fuermohao** [comment]
got it.
