### ISSUE TITLE
Can't get BTree data to persist

### ISSUE THREAD

**Issue by colin-infersens** [micropython/micropython#4327]
Hi,

I'm developing an application in MicroPython on an ESP32 where a buffer of data to be published needs to persist over power outages/reboots.

BTree seems like the obvious solution, but in my tests I can't get the data written to the BTree db to persist - in fact it doesn't seem to be written to the file at all.

Here is some sample test code; I'd be really grateful if anyone can offer any assistance, please:

```
import btree

try:
    f = open("buffer.db", "r+b")
except OSError:
    f = open("buffer.db", "w+b")
db = btree.open(f)

db[b"1"] = b"first"
db[b"2"] = b"second"
db[b"3"] = b"third"
db[b"4"] = b"fourth"
db[b"5"] = b"fifth"

db.flush()

print('The database contains the following:')

for k in db:
    key = k.decode('utf-8')
    val = db[k].decode('utf-8')
    print('Key:', key, 'Value:', val)

print('End of data.')

db.close()
f.close()
```
This all appears to work fine, with the expected output to REPL:

```
The database contains the following:
Key: 1 Value: first
Key: 2 Value: second
Key: 3 Value: third
Key: 4 Value: fourth
Key: 5 Value: fifth
End of data.
```
But if I then try the following:
```
f = open("buffer.db", "r+b")
db = btree.open(f)

print('The database contains the following:')

for k in db:
    key = k.decode('utf-8')
    val = db[k].decode('utf-8')
    print('Key:', key, 'Value:', val)

print('End of data.')

db.close()
f.close()
```
...the output to REPL is:
```
The database contains the following:
End of data.
```

On checking the db file "buffer.db", it has a size of 0 bytes.

I'm sure I'm making a schoolboy error, but I can't spot it for the life of me.

Many thanks in advance for your help.

**Comment by colin-infersens** [comment]
Further to my question, above, I've gone back to the reference docs at Micropython.org: [btree – simple BTree database]( http://docs.micropython.org/en/latest/library/btree.html ) and done a straight copy and paste of the example code, and after running it (and seeing all the expected responses printed to REPL), the file created as the underlying stream for BTree - __mydb__ - is still at 0 bytes after the example code has run.

Any help gratefully received, thanks!

**Comment by pfalcon** [comment]
Step 1: Try your code using Unix port of MicroPython. If that works, the problem is in ESP32 port and (most likely) not in the btree module.

**Comment by colin-infersens** [comment]
Hi @pfalcon 
Many thanks for the response, I'll give your suggestion a try.

**Comment by peterhinch** [comment]
I can confirm that it works fine on the ESP8266 too, the data persisting if the file is reopened after a reboot.

**Comment by colin-infersens** [comment]
OK, thank you @peterhinch , hopefully the issue can be resolved in the ESP32 port, then.

**Comment by robert-hh** [comment]
@colin-infersens  I cannot confirm your observation. The test code above runs fine on a ESP32 board.
Device: Wemos LOLIN32 Pro with 4 MB SPIRAM
Build: MicroPython v1.9.4-697-g485514f5-dirty on 2018-11-30; ESP32 module with ESP32
Type "help()" for more information.
File system; 2020k available,  1952 k free.
Maybe the file system on your device is corrupt or full.

**Comment by colin-infersens** [comment]
OK, thanks for the feedback, @robert-hh, I'll flash the device and try it again.
I am using the [loboris/MicroPython_ESP32_psRAM_LoBo](https://github.com/loboris/MicroPython_ESP32_psRAM_LoBo) flavour of MicroPython, which could be a contributing factor, but I've compared the BTree modules from both repos, and there only very few minor differences between them.

**Comment by robert-hh** [comment]
The same on a sparkfun esp32 thing without SPIRAM
Build: MicroPython v1.9.4-679-ge328a5d4-dirty on 2018-10-28; ESP32 module with ESP32
Type "help()" for more information.

**Comment by robert-hh** [comment]
On the loboris firmware the code fails. So better open your issue again in the loboris branch and close it here.

MicroPython ESP32_LoBo_v3.2.24 - 2018-09-06 on ESP32 board with ESP32
Type "help()" for more information.

**Comment by colin-infersens** [comment]
Thank you for your help with the testing of this issue, @robert-hh - I'll do as you suggest and re-open the issue in the loboris branch.
