### ISSUE TITLE
__base__ attribute for class is not implemented

### ISSUE THREAD

**Issue by nanfang2000** [micropython/micropython#4361]
I have a class Application which inherit from class View:
```
class Application(View):
    ...
```
I want to get base class (View) of the class Application by this way:
`Application.__base__`
But I got error "AttributeError: type object 'Application' has no attribute '\_\_base\_\_'"

Well this code works in CPython3

**Comment by nanfang2000** [comment]
My fix:
in line 1044, function mp_load_method_maybe(), runtime.c:
```
} else if (attr == MP_QSTR___base__) {
        mp_obj_type_t* t = MP_OBJ_TO_PTR(obj);
        if (mp_obj_is_instance_type(t))
        {
             dest[0] = MP_OBJ_FROM_PTR(t->parent);
        }
```
It seems works as expected.

**Comment by pmp-p** [comment]
could be usefull, need #include "py/objtype.h" too at the top

**Comment by pmp-p** [comment]
@nanfang2000, you can edit the file in the browser, then click pullrequest to do like that :
https://github.com/micropython/micropython/compare/master...pmp-p:patch-3

**Comment by nanfang2000** [comment]
Thanks Paul for verifying it.
Here is my pull request :
[https://github.com/micropython/micropython/pull/4368](https://github.com/micropython/micropython/pull/4368)

**Comment by jonnor** [comment]
__bases__ was implemented and can be used for this purpose, by doing __bases__[0] in the case there is a single base-class. See discussion in https://github.com/micropython/micropython/pull/4368 for why this was preferred over __base__.
