### ISSUE TITLE
Using MicroPython with another build system

### ISSUE THREAD

**Issue by embeddedt** [micropython/micropython#4362]
Is there a simple way to use the MicroPython source code without needing to integrate my project under MicroPython's build system?

I have an existing project and I would like to add Python to it.

**Comment by embeddedt** [comment]
@pmp-p It is the unix port, but my platform does not support shared libraries. I don't really want to use the port system, I want to add the core MP code to my project.

**Comment by pmp-p** [comment]
i suggest you start with embedding cpython ( there are samples ) then come back to micropython
also it could be a topic suited for forum or  irc http://webchat.freenode.net/?nick=embeddedt&channels=%23micropython ( i'm there as pmpp )

**Comment by embeddedt** [comment]
@pmp-p How much ROM/RAM will CPython require? I haven't been able to find that information.

**Comment by stinos** [comment]
You could build a static library, there are examples of how to do that either around here or in the forums, don't remember exactly. Else you need to incorporate the header/qstr generation into your own build system and add all needed sources. In any case: look into the unix makefile for inspiration.

**Comment by dpgeorge** [comment]
You can have a look at how the micro:bit port works, which uses the yotta build system and C++, and pulls in the MicroPython source with a different directory layout: https://github.com/bbcmicrobit/micropython ; in particular see this script for doing the qstr preprocessing: https://github.com/bbcmicrobit/micropython/blob/master/tools/makeqstrhdr.sh
