### ISSUE TITLE
Better and more powerful Webrepl

### ISSUE THREAD

**Issue by Fuermohao** [micropython/micropython#4366]
After a period of development, I feel that I need to share some of my work on the MicroPython development tools.
The EMP project is an acronym for Easy MicroPython. I created this project with my partner. We implemented more powerful features through the improvement of WebREPL, and called it EMP IDE.

Here are the details about EMP-IDE:
<https://github.com/Fuermohao/EMP-IDE>

I hope that I can contribute to the MicroPython community, and although this project is not perfect at the moment, I hope to develop useful tools for the community!
At the same time, I also hope to get community support and feedback.

**Comment by Fuermohao** [comment]
If 1.10 can successfully solve the problem of UART (0) and REPL, then I think EMP-IDE will soon support the way of serial port connection.

**Comment by peterhinch** [comment]
A better place to promote this is [the forum](http://forum.micropython.org/index.php) rather than this bug tracker.

It might find more acceptance if the User Guide were fully translated into English.

**Comment by Fuermohao** [comment]
@peterhinch 
> A better place to promote this is the forum 

Actually, I already posted it on forum.
<https://forum.micropython.org/viewtopic.php?f=15&t=5034&start=10>
It took a long time to review...

> rather than this bug tracker.

sorry about this ...... just turn it off.

> It might find more acceptance if the User Guide were fully translated into English.

coming soon...

**Comment by pfalcon** [comment]
> Actually, I already posted it on forum.
https://forum.micropython.org/viewtopic.php?f=15&t=5034&start=10

Cool. Released a new version? Post again. If you're serious into developing and maintaining your IDE, feel free to actually open a dedicated thread for it, and post regular updates to it (say, once a month). That's how you can promote your project.
