### ISSUE TITLE
unexpected results for esp32 http server with threads

### ISSUE THREAD

**Issue by gengshenghong** [micropython/micropython#4372]
I am trying to test threads with http server. And get below results, which I cannot understand well (not sure it is expected or not?). What is the practical code to handle this case (needs to have multiple threads except HTTP threads).

Test code: https://gist.github.com/gengshenghong/8126467672974a72379c6f1c62892609
hardware: esp32 WROOM 32D
software: latest micropython master build
http response time: use curl command to bench 100 times.

1. only http thread, run in main thread (repl thread)
```
HTTP_IN_THREAD = False
NNN = 0
THREAD_SLEEP = False
```
http response time: 54.72ms
Result is very good for a practical http server.

2. put http in a thread
```
HTTP_IN_THREAD = True
NNN = 0
THREAD_SLEEP = False
```
http response time: 857.48ms
Question: is this expected? what it slows down so much? thread priority issue?

3. put http in a thread, add 1 worker thread
```
HTTP_IN_THREAD = True
NNN = 1
THREAD_SLEEP = False
```
http response time: 1698.14ms
In my understanding, 1 busy loop worker thread is added, it will be affected more or less, but it seems affect too much again.
Question: is this affect expected?

4. put http in a thread, add 1 worker thread but sleep most of time
```
HTTP_IN_THREAD = True
NNN = 1
THREAD_SLEEP = True
```
http response time: 2115.29ms
Question: what is wrong with "utime.sleep"? In my understand, a thread sleep will give more time for other threads, and it should performs better than case 3, but it is worse here! is this expected?

5. put http in a thread, add 10 worker thread
```
HTTP_IN_THREAD = True
NNN = 10
THREAD_SLEEP = False
```
http response time: 10 + seconds
Set "THREAD_SLEEP" to true does not change here.
Question: is thread so heavy in esp32? If all these numbers expected, how should I create a simple http server with some logic in other threads?

Hope it is clear and get your help.

Thanks,
Shenghong

**Comment by dpgeorge** [comment]
Thanks for the detailed report.  I could reproduce the issue with the supplied test_http.py script.

The main issue is that the esp32 socket would yield the GIL for each read.  socket.readline() reads one character at a time so the GIL was yielded for each character.  The FreeRTOS time slice is 10ms so it was about 10ms per character per active thread, which is a lot of delay.

Adding read buffering to sockets would help a bit to improve performance, but the buffer would need to be large and there would still be issues with excessive yielding.  So instead I addressed the issue by polling the socket for readability and not yielding if there are bytes waiting on the socket (so the read should succeed immediately).  See f350b640a038477c5b00aaae7467b9485d5e9a2b

Also related is a similar improvement to REPL printing in efe0569c260677ac480d8958616f046b992ec6d8
