### ISSUE TITLE
Would a docker image for the unix port be something wanted?

### ISSUE THREAD

**Issue by SConaway** [micropython/micropython#4374]
Would a docker image be wanted? I can make it, just want to see if I'm going to waste my time.

**Comment by jhgoodwin** [comment]
@SConaway You probably would like to read this issue: https://github.com/micropython/micropython/issues/3908

**Comment by jonnor** [comment]
There is a Docker image for the Unix port available at https://hub.docker.com/r/micropython/unix - maintained by @mattytrentini 

So this issue can be closed :)

**Comment by mattytrentini** [comment]
For reference, they can be found here (both build containers and the unix port, ready-to-use):

https://hub.docker.com/u/micropython
