### ISSUE TITLE
Enhancement suggestion: NO auto-indentation REPL mode

### ISSUE THREAD

**Issue by sebastienkrut** [micropython/micropython#4375]
### Wouldn't it be handy to be able to copy/paste a few lines of code in the REPL without worrying about indentation and/or having to switch to paste mode?

This would allow to test lines easily without using a special IDE or making additional manipulations.

Copy/past currently works in the regular REPL as long as there is no indentation in the lines of code, neither tabs.

Could we create a no auto-indentation REPL mode for this purpose?
Additionally could we create a no auto-indentation mode and no tab-completion mode for people willing to paste lines with tabs?

Instead of being different modes than the regular REPL, being able to **switch on or off auto-indentation and tab-completion** would make the trick.

Any thoughts on that?
With kind regards,

**Comment by robert-hh** [comment]
So you are asking for just another paste mode?

**Comment by peterhinch** [comment]
> Copy/past currently works in the regular REPL as long as there is no indentation in the lines of code, neither tabs.

It works fine if indentation is with spaces as per PEP8.

**Comment by dhylands** [comment]
Micropython has a paste mode: https://docs.micropython.org/en/latest/esp8266/tutorial/repl.html#paste-mode

**Comment by robert-hh** [comment]
I understood your intention right from the start, but in my view that is not useful. Pasting into REPL is only useful for short trivial code, There exist many software packages for PC, Linux and Windows, both command line tools and IDEs, which do what you want in a more comfortable and reliable way. Best tested is a package called rshell by @dhylands, and if you search in the forum at forum.micropython.org for IDE, you will find many names & packages.
b.t.w.: This discussion is also better held at the forum.

**Comment by sebastienkrut** [comment]
@robert-hh: I use and I like **rshell** by @dhylands. But I doubt it's that confortable for testing a few lines in an easy way without running a whole file (maybe I missed something though). I will continue this discussion on the forum as you suggest.
