### ISSUE TITLE
esp8266: uart read a little short

### ISSUE THREAD

**Issue by hwt9520** [micropython/micropython#4402]
esp8266 mini d1
esp8266-20190108-v1.9.4-773-gafecc124e

now uart can send and receive, very good job!
but the senser do not work : 
send ：FE 03 00 00 00 02 D0 04
receive ：FE 03 04 00 15 00 FE 65 78 
00 15 ->tem, 00 FE -> hum
 I do:
`while (True):`
        `print('---------')`
        `uart0.write("FE 03 00 00 00 02 D0 04")`
        `a = uart0.read()`
        `print(a)`
        `time.sleep(5)`

machine give me:
23
b'FE 03 00 00 00 '
---------
23
b'FE 03 00 00 00 '
---------
23
b'FE 03 00 00 00 '

it is problem of send or receive?
how can i repair it?

**Comment by robert-hh** [comment]
uart.write() returns before the last byte is sent, and uart.read() reads what arrive until it is called. For verification, you can add a small delay before calling read().

**Comment by dhalbert** [comment]
I'm not sure what sensor you're using, but it looks like you are sending a string of hex digits, and you want to send actual hex values, don't you? Instead of this:
````
uart0.write("FE 03 00 00 00 02 D0 04")
```
do you want this?
```
uart0.write(b"\xFE\x03\x00\x00\x00\x02\xD0\x04")
```

**Comment by hwt9520** [comment]
> uart.write() returns before the last byte is sent, and uart.read() reads what arrive until it is called. For verification, you can add a small delay before calling read().
time.sleep(0.5)
I have tried 0.5 1 2 
the same thing happen

**Comment by hwt9520** [comment]
@dhalbert I think no but I am not sure
the book of the sensor said
FE 03 00 00 00 02 D0 04
ef -> address of sensor
03-> read register
00 00 -> address of register
00 02 -> read 2 datas
D0 04 -> check, no sense especial
FE 03 04 00 15 00 FE 65 78
fe -> address of sensor
04 -> 4 datas
0015 -> 2.1%
00FE -> 25.4℃
65 78 -> check

**Comment by hwt9520** [comment]
@robert-hh @dhalbert thank you guys helping me 👍

**Comment by dpgeorge** [comment]
By default the UART's receive buffer has enough space for 15 characters/bytes.  If the device sends more than this at once then remaining bytes will be lost.  To increase the receive buffer size use `uart.init(rxbuf=100)` or in the constructor `machine.UART(0, rxbuf=100)`.

**Comment by hwt9520** [comment]
ok working!
really good job!
thanks
