### ISSUE TITLE
MicroPython website DNS/hosting issue?

### ISSUE THREAD

**Issue by mcauser** [micropython/micropython#4403]
Getting a `ERR_CONNECTION_REFUSED` error on:
http://micropython.org/
http://forum.micropython.org/
http://docs.micropython.org/
http://georgerobotics.com/

https://downforeveryoneorjustme.com/micropython.org
> Is micropython.org down?
> It's not just you! micropython.org looks down from here.

DNS A records pointing to 176.58.119.26, which is responding to pings.

**Comment by mcauser** [comment]
Services back to normal.

**Comment by dpgeorge** [comment]
Yes, there was a brief downtime for maintenance.

**Comment by dpgeorge** [comment]
All sites are currently down for further maintenance.

**Comment by dpgeorge** [comment]
Maintenance has finished for now and most services should be back to normal, but please report any problems here.

**Comment by dpgeorge** [comment]
The wiki.micropython.org is known to be still down.

**Comment by dpgeorge** [comment]
wiki.micropython.org is back online.

**Comment by flowergrass** [comment]
http://micropython.org/unicorn/ is broken D:

**Comment by dpgeorge** [comment]
> http://micropython.org/unicorn/ is broken D:

Thanks for hint!  Serving of static .gz files was disabled with the new server.  It's now enabled and should be working again.

**Comment by mattytrentini** [comment]
All service seem to be up; can this ticket be closed now?

**Comment by dpgeorge** [comment]
There are still a few things not running, like doc rebuilding.

**Comment by dpgeorge** [comment]
Docs and firmware builds are now working again, and they should be the remaining items.
