### ISSUE TITLE
Is the website down?

### ISSUE THREAD

**Issue by ravernkoh** [micropython/micropython#4409]
Hi.

Is the website currently undergoing maintenance or is it down? Trying to access https://micropython.org/ results in an error where the TLS certificate is rejected. Proceeding anyway will result in the following screen:

<img width="1561" alt="screenshot 2019-01-13 at 9 48 00 pm" src="https://user-images.githubusercontent.com/22592318/51086082-e9f45c00-177c-11e9-95bf-2460825138ce.png">

I need to download the ESP32 firmware urgently.

**Comment by robert-hh** [comment]
I prfepared two images  firmware_esp32_no_spiram.bin and firmware_esp32_with_spiram.bin here:
https://github.com/robert-hh/Shared-Stuff

**Comment by dpgeorge** [comment]
Please see #4403.  It should be back up now.
