### ISSUE TITLE
Micropython webserver stops working when add code to read data from dht11

### ISSUE THREAD

**Issue by alessss** [micropython/micropython#4418]
I've downloaded webserver code from https://docs.micropython.org/en/v1.8/esp8266/esp8266/tutorial/network_tcp.html, it worked well. But after adding code reading dht11 values, webserver stops responding. What's wrong with my code?

```import machine
import dht
import socket
import network
sta_if = network.WLAN(network.STA_IF)
sta_if.connect(SSID, PASS)

addr = socket.getaddrinfo('0.0.0.0', 80)[0][-1]
d = dht.DHT11(machine.Pin(5))

def measure():
    d.measure()
    temp = d.temperature()
    hum = d.humidity()
    return temp

s = socket.socket()
s.bind(addr)
s.listen(1)

print('listening on', addr)

while True:
    cl, addr = s.accept()
    print('client connected from', addr)
    cl_file = cl.makefile('rwb', 0)
    while True:
        line = cl_file.readline()
        if not line or line == b'\r\n':
            break
    response = measure()
    cl.send(response)
    cl.close()

**Comment by dpgeorge** [comment]
It's best to ask these kinds of questions at https://forum.micropython.org

But to help here: when you run the code it'll give an error on the `cl.send(response)` line which will help understand the problem.  You need to convert the response (a float) to a string to send back to the client, eg like `response = b'temp=%f' % measure()`.  Also, it may need a `time.sleep(0.25)` after `d.measure()` to avoid reading the sensor too fast in a row.
