### ISSUE TITLE
esp32 OSError: [Errno 2] ENOENT

### ISSUE THREAD

**Issue by sunbearc22** [micropython/micropython#4439]
On an espressif esp32 devkit v1 board, I tried a soft reboot Ctrl+D and a hard reboot by pressing EN button. Their output are shown below.  I had accessed the repl via `picocom /dev/ttyUSB0 -b115200`. My questions are:

 1. What is `OSError: [Errno 2] ENOENT`? The closes previous issue I came across is [this](https://github.com/micropython/micropython-esp32/issues/90). After running picocom command, I did experience no respond from keyboard (as if the system hang). I pressed the EN button and the repl appeared thereafter. 
 2.  `cpu_start: Single core mode`. The esp32 has dual core. Is there a Dual core mode?

```
>>> 
PYB: soft reboot
OSError: [Errno 2] ENOENT
MicroPython v1.9.4-788-gf874e8184 on 2019-01-25; ESP32 module with ESP32
Type "help()" for more information.
>>> ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:4732
load:0x40078000,len:7496
load:0x40080400,len:5512
entry 0x4008114c
I (411) cpu_start: Pro cpu up.
I (411) cpu_start: Single core mode
I (411) heap_init: Initializing. RAM available for dynamic allocation:
I (414) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (420) heap_init: At 3FFC0E38 len 0001F1C8 (124 KiB): DRAM
I (427) heap_init: At 3FFE0440 len 00003BC0 (14 KiB): D/IRAM
I (433) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (440) heap_init: At 400915EC len 0000EA14 (58 KiB): IRAM
I (446) cpu_start: Pro cpu start user code
I (16) cpu_start: Starting scheduler on PRO CPU.
OSError: [Errno 2] ENOENT
MicroPython v1.9.4-788-gf874e8184 on 2019-01-25; ESP32 module with ESP32
Type "help()" for more information.
>>> 
```

**Comment by dpgeorge** [comment]
>  OSError: [Errno 2] ENOENT

As you found out in that link, this does mean that "main.py" was not found on the filesystem.  It's a harmless error (unless you did want it to actually execute main.py).

>   The esp32 has dual core. Is there a Dual core mode?

Dual core is not currently supported by MicroPython.
