### ISSUE TITLE
triaging : separate ideas-features-request from BUGS

### ISSUE THREAD

**Issue by pmp-p** [micropython/micropython#4444]
i'm quite sure that on ~ 500 issues not all are related to core health.

Why not a repo "micropython-ideas" sticking to last released source code where PR ( would be the staging part ) are fully useable for testing  ?

**Comment by pfalcon** [comment]
Because who's going to maintain it?

**Comment by pmp-p** [comment]
no maintenance, just sync to ervery official release. and let contributors update their PR on that if they have seen some interest on the "peer review" comments and feel like it instead of trying to infinite run behind master.

ok let's call that a big - centralized - bag of patches.

**Comment by pfalcon** [comment]
> no maintenance,

There's no such thing in real life. Everything requires effort. To give an example, the act of writing requires maintenance - pressing the Shift key at right times, putting commas at right places, not making or fixing typos, reading it before posting, etc.

**Comment by pmp-p** [comment]
i think a repo with no committers, but some members as moderators ( from what i've heard on irc there are people expecting some action ) would not be so hard to "maintain" with a big warning about unsafe code and code of conduct on readme etc ...

that's still better than patches in a mailing list, and a good place to explain people how to apply a .diff and make V=1 a test report.

also one could imagine empty PR with just a link another repo+pr  as an example :

`#4422 - quick fix for some stupid bug` 
patch to apply https://github.com/pfalcon/pycopy/commit/2e6811b67882f93ca67912dab6d8c45e6d6d729e.diff   with a note about tested/untested

**Comment by stinos** [comment]
> not all are related to core health.

That's also what labels are for, or PRs with 'RFC:' prepended to their title. Or 'triaging:' for that matter :P

> last released source code where PR ( would be the staging part ) are fully useable for testing

I don't really understand what the difference is between this (and other ideas you mention) and how it works now. Can you explain them n detail, and the advantages? And possible disadvantages?

Everyone can submit PRs here. Or else advertise commits in their own repo on the forum/irs/slack/... And every PR is just one `fetchpr` (or whatever git tool/alias you use for that) away and everyone can test/review/comment on it. Replicating that in another repository is more work and one major disadvantage I see happening easily is one big pile of outdated half-tested code samples possibly with a lack of proper explanation of what they do. Don't get me wrong, it doesn't have to be that way, but who's going to take care of that?

**Comment by pmp-p** [comment]
> labels

are usefull for people who can apply them where they can and one could say some issues may miss labels ( sorry i won't read them all to check if assertion is valid).

_Using a stable release base for PR *testing*_

i insist this is not for *merging*. it would quite easy to provide a build script testing various PR eg  ./build-test  123 456 789  and that would maybe provide valid builds for months with pre populated ports/*/modules folder with various samples or tailored testsuites which have nothing to do in mainline tree.

_You have learned all git tools ?_

Good for you, i did not and i won't i feel too old for that. i use busybox, patch ( and wget/curl when platform is friendly enough to provide name resolution)  and a folder full of diff i picked up here and here.

it not about avertising PR and even speak english in comments, `code is all what would be expected`.

> forums / slacks etc ....

 those are not about code, forums can go read-only/vanish anytime ( eg Playground.arduino.cc). 

>Everyone can submit PRs here

but not much people want to do it as merging possibility is short-lived and MIT only.

People **could** PR pointing to others people work, a way to promote shy people, or take away the burden of code sharing for people to busy to PR back,
 
_no merging until original writer fix license or decide his work is ok and/or offers merging on his own._

that would be more about sharing than merging.

>one big pile of outdated half-tested code samples

 what's wrong with that ? did you look at cpython stdlib and PyPI closely ? using github search on that pile will be probably more helpfull than swimming in ads crowded blogs clones.

> who's going to take care of that ?

maybe here would the place for people to step up.
no need to master git, just github web interface, some social skills, extreme tolerance for beginners code,  and a bit of relaxed english/C/python. more hobby spirit than "grown up committers".

**Comment by stinos** [comment]
I think I see what you want. Just a repository for code samples/ideas, no more no less? Could be useful I guess.

> what's wrong with that ?

Depends on what kind of project you want to use the code for, but if I have to use other people's code I'd rather have it been viewed by multiple eyes and tested already.

> those are not about code, forums can go read-only/vanish anytime

Sure but I only mentioned those for *advertising* code existing, not actually sharing the literal code itself.

**Comment by jonnor** [comment]
5 years later we now have over 1300 open issues :D (not just 500). And yes, for sure, many are ideas - feature requests etc. Some are questions or more general requests for information.

Most feature requests are marked with enhancement. https://github.com/micropython/micropython/issues?q=is%3Aissue+is%3Aopen+label%3Aenhancement
Issues that are likely to be actual bugs are marked with https://github.com/micropython/micropython/issues?q=is%3Aissue+is%3Aopen+label%3Abug

And since a year or so, there is also a Github Discussion attached to the project. And Github supports "convert to discussion" - which I believe can be used beneficially to move issues/enhancements that are outside the scope of "core MicroPyhon" into a discussion thread. Examples would be drivers for external peripherals, communication protocols, algorithms - or anything else that can meaningfully be done as third party modules.

Combined, I think this is a reasonable workflow for triaging. So I think we can close this issue?
