### ISSUE TITLE
[STM32F429ZI] UART 7/8 fail

### ISSUE THREAD

**Issue by schubi93** [micropython/micropython#4445]
In  [https://github.com/micropython/micropython/blob/master/ports/stm32/boards/stm32f429_af.csv#L67](url), see Column "AF8", lines 67f., 73 f. and 89 f.. There, a lower case R"x" and T"x" causes UART 7 and 8 to fail. Thanks for fixing.

**Comment by dpgeorge** [comment]
Thanks for the report!  Should be fixed by 4bed17e78615360c018103ef3c3c2e204a9c9a46
