### ISSUE TITLE
RFC: Rename "websocket" to "uwebsocket"

### ISSUE THREAD

**Issue by pfalcon** [micropython/micropython#4450]
This is similar to https://github.com/micropython/micropython/issues/4370, submitting a new ticket as that one has PR and hopefully can be closed soon.

Naming "websocket" module as such was pretty brave, as it's of course the default name for a module dealing with Websockets, and there should be tons of "websocket" modules around. MicroPython's module is pretty specific as it implements only data transfer handling, leaving handshake part to Python code.

"websocket" module was also not documented and described as highly experimental, with only intended user is webrepl subsys. So, I think here we can just rename it to "uwebsocket", without weak links, and at least include it in the list of modules in the docs, if not describe its API completely.

**Comment by dpgeorge** [comment]
Sounds good to me.

**Comment by dpgeorge** [comment]
Done in bc4f8b438b56cf1b4f6b44febcd0d83599cbbd68

**Comment by rubydesign** [comment]
I am researching websockets and google led me here

import websocket

still works.

And this was closed without actually including any docs

**Comment by dpgeorge** [comment]
> import websocket
> 
> still works.

Yes that works because weak links are enabled for all modules starting with "u", ie `import foo` will search for `ufoo` if `foo` cannot be found anywhere.

> And this was closed without actually including any docs

Yes indeed, there are no docs for `uwebsocket`.  This issue was mainly about renaming.  Feel free to submit a PR with a docs addition.

**Comment by rubydesign** [comment]
Hi @dpgeorge (Damien, right? Great work, thanks)

I would love to send a docs PR. But i have spent hours just trying to understand what is going on. I can not read the c internals (where i can even find the strings: that import magic you explained, and don't know what all the functions do. I mean i can read c, but am not a MP developer)

And i am not a websocket user. I just thought that writing my own socket code in this day and age is not the way. (It seems other googlers chose that way) 

My feeling is that a docs should exist for features that have been written 5 years ago.
(Many of the old issues and PR are just misleading now, and that is the only docs we mortals have)
Even just an example. Or a sentence about the standard conformity.

**Comment by dpgeorge** [comment]
> I would love to send a docs PR. But i have spent hours just trying to understand what is going on.
> ...
> My feeling is that a docs should exist for features that have been written 5 years ago.

As mentioned at the top of this issue, `uwebsocket` is really an internal module, used only by `webrepl`.  It's not really designed for "end users".

That said, it would be worth documenting, at least to describe this situation.  I opened #7149 for that.
