### ISSUE TITLE
 gcc -E instead of $(CPP)

### ISSUE THREAD

**Issue by pmp-p** [micropython/micropython#4453]
there https://github.com/micropython/micropython/blob/67689bfd7e28df8d4fa23c8f25065aeb0b9d9658/py/mkrules.mk#L56

also i'm not sure what CFLAGS have to do with preprocessing here, should be only include paths
https://github.com/micropython/micropython/blob/67689bfd7e28df8d4fa23c8f25065aeb0b9d9658/py/mkrules.mk#L75

also i think i saw something like 
```cat ../../py/qstrdefs.h qstrdefsport.h build/genhdr/qstrdefs.collected.h | sed 's/^Q(.*)/"&"/' | gcc -E -I. -I../.. -Ibuild -Wall -Werror -ansi -std=gnu99 <<<<INSERT_MORE_COMPILER_OPTIONS_HERE>>> -Os -DNDEBUG -DMICROPY_QSTR_EXTRA_POOL=mp_qstr_frozen_const_pool - | sed 's/^"\(Q(.*)\)"/\1/' > build/genhdr/qstrdefs.preprocessed.h```
but seems  gcc does not like COMPILER OPTIONS ...

**Comment by dhylands** [comment]
CFLAGS also includes -D options which directly affect code generation and other options (like -mthumb) which indirectly cause defines to be created which if not present would generate different pre-processed output.

**Comment by dhylands** [comment]
It seems CPP is already defined to be $(CC) -E. At least that's the default for my make (GNU make v4.1 running under ubuntu).

What is it that you're trying to do and what specific errors are you running into?

**Comment by pmp-p** [comment]
i'm cross compiling with a non standard toolchain where the prepropessor is gcc and won't accept cc specific options ( it's a python wrapper from emscripten around clang known as emcc ).

**Comment by pmp-p** [comment]
well thanks, COPT is ok to act as "C OPTIONS" :) and fixed my preprocessor problems. but a bug can hide another and in fact frozen object is twice on the final link nothing to do with CPP ( i hope ! )
