### ISSUE TITLE
stm32: I2C on NUCLEO-L476RG uses wrong pins

### ISSUE THREAD

**Issue by ckuehnel** [micropython/micropython#4476]
I tried to use I2C for NUCLEO-L476RG w/o success.
After changing mpconfigboard.h  as marked for I2C1 it works.
![mpconfigboard](https://user-images.githubusercontent.com/195788/52447819-33dd2180-2b32-11e9-8e6a-3fdd577e48bf.png)

**Comment by dpgeorge** [comment]
Thanks for the note.  This will be fixed in #4462.

**Comment by dpgeorge** [comment]
Fixed by d1acca3c71780545e067e85b444b495cc9801b2b
