### ISSUE TITLE
how to compile my C file into micropython

### ISSUE THREAD

**Issue by yellowway** [micropython/micropython#4497]
HI . I have a IC which driver is writened by C.but I don't know how to compile this file for PYBV10 board.

I prefer three Methods:

1. Add C source code directly to the project catalog and compile it into micropython after make.(the best way)

2. Compile C source code directly and generate.Py script. Then add it manually to micropython(the better way)

3. According to the micropython format, modified the C source code is  one by one.(the worst way)

can you give me some advice?

**Comment by miketeachman** [comment]
Hi, 
Sounds like a fun project you are working on.   I think you will get the best response if you ask these questions at the [MicroPython forum](https://forum.micropython.org/).  The "Development of MicroPython" topic seems like the best place to go -- it already has a few posts related to your questions on developing a C-based MicroPython module.  There are many experts who follow the Forum post and can help you.

The Issues area in this github repository is best used to report bugs or issues in the MicroPython implementation.  The Forum is the best place to get help.
