### ISSUE TITLE
STM32F429ZI: Heap size

### ISSUE THREAD

**Issue by t35tB0t** [micropython/micropython#4513]
Heap size set too small on line 29 of:  micropython/ports/stm32/boards/stm32f429.ld

line29:   `_heap_end = 0x2001c000; /* tunable */`
should be...
line29: ` _heap_end = 0x2002c000; /* tunable */`

This increases reported heap after boot by about 64K from ~74K to ~135K

**Comment by dpgeorge** [comment]
Thanks for the report!  Fixed by c65e5c88b8ec805d40a4b040a56569f8b1aa8bab
