### ISSUE TITLE
Flash tool download page for nrf segger (mac) doesn't exist anymore

### ISSUE THREAD

**Issue by rlnktt** [micropython/micropython#4517]
https://www.nordicsemi.com/eng/nordic/Products/nRF52840/nRF5x-Command-Line-Tools-OSX/58855

The above link produces 404. Could anyone please provide an alternate link for download??

Thanks

**Comment by glennrub** [comment]
Updated link in #4520.

**Comment by glennrub** [comment]
PR has been merged, closing the issue.
