### ISSUE TITLE
stm32: compile error with frozen_mpy.c

### ISSUE THREAD

**Issue by c-hamster** [micropython/micropython#4542]
Hi ,I download the source code from github,and build it as what README.md.but It doesn't work.

.....
CC ../../extmod/vfs_fat_diskio.c
CC ../../extmod/vfs_fat_file.c
CC ../../extmod/utime_mphal.c
CC ../../extmod/uos_dupterm.c
CC ../../lib/embed/abort_.c
CC ../../lib/utils/printf.c
GEN build-PYBV10/frozen_mpy.c
**usage: mpy-tool.py [-h] [-d] [-f] [-q QSTR_HEADER]**
                   **[-mlongint-impl {none,longlong,mpz}] [-mmpz-dig-size N]
                   files [files ...]
mpy-tool.py: error: the following arguments are required: files
../../py/mkrules.mk:122: recipe for target 'build-PYBV10/frozen_mpy.c' failed**
make: *** [build-PYBV10/frozen_mpy.c] Error 2
make: *** Deleting file 'build-PYBV10/frozen_mpy.c'
python@linuxpc:/mnt/hgfs/wshare/micropython/ports/stm32$ 

ps：no file I have changed.just use "make " in /ports/stm32/

**Comment by dpgeorge** [comment]
It's possible symlinks don't work on your system.  Try rebuilding (after make clean) with:
```
$ make FROZEN_MPY_DIR=
```

**Comment by dpgeorge** [comment]
I assume this was fixed by the above suggestion.  If not feel free to reopen with further details.
