### ISSUE TITLE
foo(*a,*b) is not supported

### ISSUE THREAD

**Issue by smurfix** [micropython/micropython#4543]
Python 3.x uses this construct in `functools`.
```
>>> a=(1,2)
>>> b=(3,4)
>>> print(*a,*b)
1 2 3 4
```
MicroPython:
```
>>> a=(1,2)
>>> b=(3,4)
>>> print(*a,*b)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SyntaxError: can't have multiple *x
```
Supporting this may not be particularly useful, but it should be documented.

**Comment by peterhinch** [comment]
MicroPython supports Python 3.4 syntax. I think that came in V3.5.

**Comment by dpgeorge** [comment]
> I think that came in V3.5.

Yes, please see #1329, in particular PEP 448.

**Comment by smurfix** [comment]
OK. Closing here then.
