### ISSUE TITLE
[STM32H743] machine.bootloader() function doesn't work

### ISSUE THREAD

**Issue by Meekdai** [micropython/micropython#4573]
On my NUCLEO-H743ZI board, the machine.bootloader() function doesn't work. It is the same as PR [#4413](https://github.com/micropython/micropython/pull/4413). But it doesn't solve my problem.
May I know is there anyone has met similar problem and successfully solved it?

**Comment by dpgeorge** [comment]
It doesn't work for me either.  I just use BOOT0 connected to VDD and press reset.

**Comment by Meekdai** [comment]
But I can't enter DFU mode by connecting BOOT0 to VDD and pressing the reset button. In this case, micropython is not running. Only when I connect BOOT0 to VDD and then power on and off again, I enter DFU mode.

**Comment by Meekdai** [comment]
#4862 solved
