### ISSUE TITLE
docs.micropython.org: Please update sphinx-rtd-theme

### ISSUE THREAD

**Issue by pfalcon** [micropython/micropython#4585]
There're some visual artifacts with the old sphinx-rtd-theme as used on http://docs.micropython.org , see for example line spacing in different articles in http://docs.micropython.org/en/latest/reference/glossary.html . The latest sphinx-rtd-theme should fix those.

**Comment by dpgeorge** [comment]
Thanks for the report.  Theme version was old 0.1.  Should be fixed now.
