### ISSUE TITLE
mqtt and ssl with stm32?

### ISSUE THREAD

**Issue by will-emmerson** [micropython/micropython#4602]
I flashed micropython onto a nucleo F429ZI but mqtt and ssl modules are missing, am I doing something wrong or are they just not supported yet?
When I flashed an ESP32 board recently they both worked 'out the box', I was under the impression that modules were shared by the different ports but I must be wrong?

**Comment by dpgeorge** [comment]
In 5da60ff9cba990f239bdac2cd7ecdb2f84df4d63 the ssl/ussl module was enabled for the NUCLEO-F429ZI and other stm32 boards that have networking support.

For mqtt, that can easily be added as .py files on the filesystem.
