### ISSUE TITLE
ESP32: latest prebuilt firmware is 0 bytes

### ISSUE THREAD

**Issue by BluSpanner** [micropython/micropython#4604]
Downloading http://micropython.org/resources/firmware/esp32-20190314-v1.10-213-g28c2873d9.bin results in a 0 byte file.

**Comment by dpgeorge** [comment]
That file is now replaced by the latest esp32-20190314-v1.10-221-gc9eb7eb44.bin, which has all the data there.  Perhaps you tried to download the file just at the point where it was being updated and hence deleted?

**Comment by BluSpanner** [comment]
Downloaded esp32-20190315-v1.10-221-gc9eb7eb44.bin successfully - 1130128 bytes.
