### ISSUE TITLE
how to enable MICROPY_PY_WIZNET5K

### ISSUE THREAD

**Issue by kaacill** [micropython/micropython#4613]
hello, can you tell me how to enable MICROPY_PY_WIZNET5K ? sorry I'm newbie at micropython. Thanks

**Comment by dpgeorge** [comment]
On the stm32 port, build it using:
```
$ make MICROPY_PY_WIZNET5K=W5500
```

**Comment by kaacill** [comment]
Thank you sir. I tried and succeeded

**Comment by Chirawat** [comment]
I use ESP8266, can I use the same command?

**Comment by robert-hh** [comment]
WIZNET5K support has to be compiled into the firmware. For RP2, an implementation is built at the moment. For ESP8266 it will most likely never happen.
