### ISSUE TITLE
could not import btree module in Pyboard Micropythopn 1.9.4

### ISSUE THREAD

**Issue by rlnktt** [micropython/micropython#4614]
When I try to import 'btree' module in micropython version - 1.9.4,

I get import error stating 'No Module named 'btree''

What am I missing

**Comment by dpgeorge** [comment]
The btree module is not enabled in some ports, in particular it's not enabled on the stm32 port.

**Comment by rlnktt** [comment]
Thanks @dpgeorge  for the quick reply there!!

Please advise on ow to proceed further and get this done in PyBoardv1.1

**Comment by adritium** [comment]
You enable the flag to include btree and build the firmware

**Comment by rlnktt** [comment]
Thanks @dpgeorge and @adritium. Got this module working. 

A question here. Is there any specific reason that 'btree' is not enabled by default in the firmware configuration?
