### ISSUE TITLE
docs: "Developing and building MicroPython" contains copy-paste artifact

### ISSUE THREAD

**Issue by pfalcon** [micropython/micropython#4623]
http://docs.micropython.org/en/latest/develop/index.html currently starts with:

> This chapter describes modules (function and class libraries) which are built into MicroPython. There are a few categories of such modules:

@andrewleech: Please have a look.

**Comment by dpgeorge** [comment]
Thanks for the hint, it obviously shouldn't be there.  Removed in 0fb15fc3f4b532faa3ca4fe49809f9d9e6c5cd53
