### ISSUE TITLE
mpy-cross: input_kind is not defined

### ISSUE THREAD

**Issue by adritium** [micropython/micropython#4629]
https://github.com/micropython/micropython/blob/e0c6dfe90a3e6265b06265c5b3124c24703776f1/mpy-cross/main.c#L57-L73

**_input_kind_** is not defined.

**Comment by dpgeorge** [comment]
Thanks for the report, indeed it won't compile if `MICROPY_PY___FILE__` is defined.  But, I'm pretty sure it doesn't make much sense to enable this option for mpy-cross, because it won't affect the generated .mpy file.

**Comment by dpgeorge** [comment]
Fixed by 1556af19bfde9e8f14c84e2bc6a2c3a087e18325
