### ISSUE TITLE
comments in pyboard.py give an incomplete example

### ISSUE THREAD

**Issue by rhubarbdog** [micropython/micropython#4630]
The comments on using pyboard.py as follows
```
import pyboard

pyb  = pyboard.Pyboard('/dev/ttyACM0')

# etc
```
are incomplete, the line `pyb.exec('import pyb')` is missing

**Comment by dpgeorge** [comment]
Fixed by 869a8b70ce384be7c8ab7cfbde1de683ba2fc077
