### ISSUE TITLE
Issues in mpy-tools.py after #4564

### ISSUE THREAD

**Issue by pfalcon** [micropython/micropython#4635]
After https://github.com/micropython/micropython/pull/4564, there're some bugs/issues/inconsistencies in mpy-tool.py:

* https://github.com/micropython/micropython/blob/master/tools/mpy-tool.py#L80: The argument is no longer log2 of size, but the size itself.
* https://github.com/micropython/micropython/blob/master/tools/mpy-tool.py#L636: QSTR_LAST_STATIC isn't used in this function or the script at all.

**Comment by dpgeorge** [comment]
Thanks for the report, fixed by 74ed06828f4f8d4ec5c04f5b551e90f2fccbd0f3
