### ISSUE TITLE
Does STM32F4DISC support SDCART ?

### ISSUE THREAD

**Issue by ahmdrz** [micropython/micropython#4639]
Hi,
Does STM32F407VG (discovery) support SDCart? Is it a feature that will be added in the future? If not, can I do anything to make this happen? If so, how?

**Comment by ahmdrz** [comment]
Can I use it alone? Not in discovery board. Only STM32F407VG microcontroller.

**Comment by dpgeorge** [comment]
The STM32F4DISC board doesn't have an SD card slot.  But the software does support SD card on the STM32F407 if you enable it with MICROPY_HW_HAS_SDCARD.  See boards/PYBV10/mpconfigboard.h for an example.

**Comment by ahmdrz** [comment]
So I think https://www.kaltpost.de/?p=2199 will help me with this issue. Right?

**Comment by dpgeorge** [comment]
Yes that post should help.

For these kinds of questions (that are not bugs) it's best to ask at https://forum.micropython.org
