### ISSUE TITLE
tuple creation syntax is broken

### ISSUE THREAD

**Issue by deniz195** [micropython/micropython#4648]
Running this plain piece of python code fails mistakenly
```
>>> c = (1,2,3)
>>> (*c,4)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SyntaxError: *x must be assignment target
```

this should return `(1,2,3,4)` rather than raising an exception.

Running on `Adafruit CircuitPython 3.0.3 on 2018-10-10; Adafruit Trinket M0 with samd21e18`.

**Comment by peterhinch** [comment]
MicroPython supports Python 3.4 syntax. I think this was added in version 3.5.

**Comment by deniz195** [comment]
Ok, wasn't aware of that

**Comment by dpgeorge** [comment]
Please see #1329
