### ISSUE TITLE
How to add pip modules to micropython?

### ISSUE THREAD

**Issue by Edris89** [micropython/micropython#4654]
Hi there,

I was wondering if it's possible to add installs/modules from using pip.
A example would be the pip install catt module. 

So my question is, is it possible to add modules, compile and make the bin file to flash it on the esp8266. With the extra module added.

If so could somebody point me out to the right direction?

**Comment by peterhinch** [comment]
This question should be raised in [the forum](http://forum.micropython.org/index.php) not in this MicroPython bug tracker. You might first like to read [the documentation](http://docs.micropython.org/en/latest/reference/packages.html).

**Comment by jonnor** [comment]
MicroPython has a package manager called `mpip`. Usage is described here: https://docs.micropython.org/en/latest/reference/packages.html
Proposing to close this issue.
