### ISSUE TITLE
ESP32: how to use PPP module

### ISSUE THREAD

**Issue by neoleesky** [micropython/micropython#4658]

**Comment by neoleesky** [comment]
I see there’s ppp support in 1.10, is there any example code for this new function?
How can I set won for my sim7600 module?

**Comment by dpgeorge** [comment]
> is there any example code for this new function?

Please see #3740 and #3787 for some details.  Also, this is a good thing to ask about at https://forum.micropython.org .  If you get it working, feel free to submit something for the docs.
