### ISSUE TITLE
[PYBD] source code

### ISSUE THREAD

**Issue by dmazzella** [micropython/micropython#4663]
when will the source code and board definition be available?

**Comment by ThomasChr** [comment]
You can find the schematics here: https://pybd.io/hw/pybd_sfxw.html

**Comment by dmazzella** [comment]
I meant the definition of the board for compiling the source code into `micropython/ports/stm32/boards/`

**Comment by ThomasChr** [comment]
That is missing and dpgeorge has not made any comments when the source will be available, yet...

**Comment by dpgeorge** [comment]
Please see #4669 for source code.
