### ISSUE TITLE
Unix port doesn't compile on aarch64: ‘nlr_push’ undeclared here

### ISSUE THREAD

**Issue by mbirth** [micropython/micropython#4666]
The compilation of the Unix port always aborts with this error:

```
../py/nativeglue.c:226:5: error: ‘nlr_push’ undeclared here (not in a function); did you mean ‘nlr_jump’?
     nlr_push,
     ^~~~~~~~
     nlr_jump
make[1]: *** [../py/mkrules.mk:47: build/py/nativeglue.o] Error 1
make[1]: Leaving directory '/opt/micropython/mpy-cross'
make: *** [../../py/mkrules.mk:108: ../../mpy-cross/mpy-cross] Error 2
```

Tried with v1.9.4 and with a fresh master checkout.

This is on a Raspberry Pi 3B+ with Ubuntu 18.10.

**Comment by ThomasChr** [comment]
No problems on Ubuntu 18.04.1 LTS and Raspberry Pi 2B with Rasbian 8:
```
apt-get install libffi-dev build-essential pkg-config
mkdir micropython
cd micropython
git clone https://github.com/micropython/micropython .
git submodule update --init
cd ports
cd unix
make
./micropython
```

**Comment by robert-hh** [comment]
@mbirth Did you run after cloning the command
`git submodule update --init`
in the micropython directory?

**Comment by mbirth** [comment]
@robert-hh Of course!

Here's the log: [micropython-compile-log.txt](https://github.com/micropython/micropython/files/3033964/micropython-compile-log.txt)

```
libffi-dev:
  Installed: 3.2.1-8
```

**Comment by dpgeorge** [comment]
It sounds like the compiler is not auto-detecting the NLR variant to use, and falling back to MICROPY_NLR_SETJMP.

This line here should be evaluating to true in the C preprocessor: https://github.com/micropython/micropython/blob/master/py/nlr.h#L55

**Comment by dpgeorge** [comment]
> I'm running aarch64.

The native emitter doesn't support 64-bit ARM.  Two options to get it building are:
- disable MICROPY_EMIT_ARM (I'm not even sure why this is enabled if it's aarch64)
- compile in 32-bit mode via `make MICROPY_FORCE_32BIT=1`

**Comment by mbirth** [comment]
I just compiled it successfully for ARM64 on Ubuntu 19.04.
