### ISSUE TITLE
time module Import Error

### ISSUE THREAD

**Issue by ARM93** [micropython/micropython#4672]
Hi, i have successfully compile and run the micropython source code from "https://os.mbed.com/users/infinnovation/code/micropython/#33521d742af1". but when import the time module then i faced below error.

>>> import sys                                                                         
>>> import time                                                                        
Traceback (most recent call last):                                                     
  File "<stdin>", in <module>                                                          
ImportError: module not found                                                          
>>> while :1
... print('hello')
... time.sleep_ms(2000)
... 
Traceback (most recent call last):
  File "<stdin>"
SyntaxError: invalid syntax
>>> 

kindly help to resolve this issue.

**Comment by robert-hh** [comment]
What happens if you try `import utime as time`?

**Comment by ARM93** [comment]
thanks for your response. i got below result when tried to import the utime.
>>> import utime
Traceback (most recent call last):
  File "<stdin>", in <module>
ImportError: module not found
>>>

**Comment by dhylands** [comment]
It appears that port of micropython has yet to implement the time module.

**Comment by dhylands** [comment]
It also appears that the author has abandoned the port as there hasn't been any changes in 3 years.

**Comment by ARM93** [comment]
> It also appears that the author has abandoned the port as there hasn't been any changes in 3 years.

Hi  Dhylands, Even the while also not worked.So i believe the standard c functionalities are need to implemented. 

Could you please guide me to port that repository further to implement standard c functionalities.

**Comment by dpgeorge** [comment]
> Even the while also not worked.

You have a typo there, swapped ":" and "1", it should be: `while 1:`



> Could you please guide me to port that repository further to implement standard c functionalities.

You can try https://github.com/micropython/micropython-infineon

**Comment by dpgeorge** [comment]
Sorry, that last link to micropython-infineon is not correct.  To get the source for that mbed port you can try following the .tar.gz links on the mbed users page.

I'll close this issue because it's not related to the repository here.
