### ISSUE TITLE
pyboard-D wlan.config('essid') returns the AP ID

### ISSUE THREAD

**Issue by pacmac** [micropython/micropython#4677]
On the 8266, it returns the DECODED essid of the connection:
```
wlan().config('essid')
'myssid'
```

However on the pyboard it appears to return the station ID in binary.
```
wlan().config('essid')
b'PYBD6AA0'
```

Can this be changed so that it returns the same as the esp8266 i.e. the connected ssid in a string so that the code for both devices can be the same ?

**Comment by dpgeorge** [comment]
Ok, now fixed on stm32-pybd branch, commit with title "stm32/cyw43: For sta.config('essid') return SSID of network it's on."

**Comment by diginfo** [comment]
Excellent, thanks tested and working :-)
