### ISSUE TITLE
[NUCLEO-F091RC] MSE clock cannot be set

### ISSUE THREAD

**Issue by rolandvs** [micropython/micropython#4685]
It seems that the STM32F091RC uses the internal MSI on 48MHz. Hooking up an external crystal does not help :-) it seems there no support yet in setting the HSE clock options of the STM32F0xx.

It would be nice to have this flexibility as with all other boards supported :-)

**Comment by dpgeorge** [comment]
> it seems there no support yet in setting the HSE clock options of the STM32F0xx.

Added in 11657f2f20c869212364efa8633a7870c9be0c3c

**Comment by rolandvs** [comment]
:+ :+
