### ISSUE TITLE
collections.namedtuple does not support comma in string

### ISSUE THREAD

**Issue by jacklinquan** [micropython/micropython#4687]
>>> import collections
>>> Point = collections.namedtuple('Point', 'x,y')
>>> Point(1,2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: function takes 1 positional arguments but 2 were given
>>> Point(1)
Point(x,y=1)
>>> Point = collections.namedtuple('Point', 'x, y') # A space added
>>> Point(1,2)
Point(x,=1, y=2)
>>> # Note a weird parameter name ends with a comma "x,"

**Comment by jacklinquan** [comment]
This bug is found in standard firmware for ESP32 port:
esp32-20190125-v1.10.bin

**Comment by peterhinch** [comment]
I think the answer to this is that the (u)collections module is a 'micro' implementation with stricter syntax rules than those in the CPython library. Field names must be separated by a space so in your second example the comma is interpreted literally.

**Comment by dpgeorge** [comment]
Yes, MicroPython supports only spaces between field names if you pass in a string for the element names.  But it also supports passing in an array or tuple of strings for the elements.

**Comment by jacklinquan** [comment]
@peterhinch @dpgeorge 
Thank you all for the replies!
