### ISSUE TITLE
NUCLEO L432KC: pastemode behaves oddly to say the least

### ISSUE THREAD

**Issue by mindforger** [micropython/micropython#4714]
stemming from that issue here

https://github.com/micropython/micropython/issues/4678

i am trying to load the uPyLoader files manually to the device but in paste mode there is something VERY off, it looks like the inputbuffer is heavily overflowing when pasting longer snippets

i got it working after i pasted it line by line 

but maybe there is a better way to catch this situation or maybe @BetaRavener could add a delay in raw paste mode?! 

even with the upload and download scripts loaded, uPyLoader can not transfer files ... the send and read delay option in uPyLoader did not help, they just advanced the time to error a little bit

strange enough rshell can transfer in 4 out of 5 times the file without problems the other time i get a timeout

also it looks like you can not paste more than 6 lines, seemingly independend of the number of bytes it looks it depends only on how many lines but this may jsut be a side effect

i just found that pasting more than 239bytes causes lost bytes

i just simply pasted repeated groups of 1234567890 in paste mode with and without newlines and this is the result
first a working version 11bytes per line 14 lines
>paste mode; Ctrl-C to cancel, Ctrl-D to finish
=== test=r'''
=== 1234567890
=== 1234567890
=== 1234567890
=== 1234567890
=== 1234567890
=== 1234567890
=== 1234567890
=== 1234567890
=== 1234567890
=== 1234567890
=== 1234567890
=== 1234567890
=== 1234567890
=== 1234567890
=== '''
$ test
'\n1234567890\n1234567890\n1234567890\n1234567890\n1234567890\n1234567890\n1234567890\n1234567890\n1234567890\n1234567890\n1234567890\n1234567890\n1234567890\n1234567890\n'
$

second with 15 lines
>paste mode; Ctrl-C to cancel, Ctrl-D to finish
=== test=r'''
=== 1234567890
=== 1234567890
=== 1234567890
=== 1234567890
=== 1234567890
=== 1234567890
=== 1234567890
=== 1234567890
=== 1234567890
=== 1234567890
=== 1234567890
=== 1234567890
=== 1234567890
=== 1234567890
=== 123456789'''
$ test
'\n1234567890\n1234567890\n1234567890\n1234567890\n1234567890\n1234567890\n1234567890\n1234567890\n1234567890\n1234567890\n1234567890\n1234567890\n1234567890\n1234567890\n123456789'
$

and the third one with 30 lines
>paste mode; Ctrl-C to cancel, Ctrl-D to finish
=== test=r'''
=== 1234567890
=== 1234567890
=== 1234567890
=== 1234567890
=== 1234567890
=== 1234567890
=== 1234567890
=== 1234567890
=== 1234567890
=== 1234567890
=== 1234567890
=== 1234567890
=== 1234567890
=== 1234567890
=== 1234567892456790
=== 1340
=== 234578901789
=== 1235678456890
=== 234512346789
=== 1280
=== 13456790
=== 13456234572356780
=== 1235613456890
=== '''
$ test
'\n1234567890\n1234567890\n1234567890\n1234567890\n1234567890\n1234567890\n1234567890\n1234567890\n1234567890\n1234567890\n1234567890\n1234567890\n1234567890\n1234567890\n1234567892456790\n1340\n234578901789\n1235678456890\n234512346789\n1280\n13456790\n13456234572356780\n1235613456890\n'
$

but when i put in straight numbers without newlines i get 37 valid repetitions and then the following

>123457902357892345890

it fluctuates where exaclty it breaks but not more stable than 374bytes withopout newlines or 14 newlines seem to be possible for this board to paste

with 20bytes per line it's only 10 valid lines, so "\n" has a major impact on the performance here

and most important to note here ... there never is a "~" indicating the overflow, so overflow detection seems to fail if i understand it right

**Comment by dpgeorge** [comment]
There is no flow control on the REPL UART and it's input buffer is just 64 bytes big, so it will certainly have problems with too much data coming in at once.

The input buffer can be increased by defining `MICROPY_HW_UART_REPL_RXBUF` in the mpconfigboard.h file.  Increasing it to 1024 bytes would improve the situation a lot.

Otherwise it's not really possible to fix this because if the host PC sends data faster than the board can keep up then it will inevitably lose data.

**Comment by mindforger** [comment]
I will try it out, because upyloader is very handy when one system is behind an ssl breaking firewall

**Comment by BetaRavener** [comment]
@dpgeorge Just for info so I can advance with the issue, is this 64 bytes default only related to STM32 port? I haven't heard of people having problems on ESP based boards before.

**Comment by dpgeorge** [comment]
>  is this 64 bytes default only related to STM32 port? I haven't heard of people having problems on ESP based boards before.

ESP-based boards have a buffer of 256 bytes and do run into this issue, but usually with larger amounts of input.  So, yes, the 64 bytes is only related to STM32.  Probably it makes sense to increase it from 64 to 256 to improve the pasting behaviour.

**Comment by mindforger** [comment]
Sorry, i did not come around today to work on anything

**Comment by dpgeorge** [comment]
The UART receive buffer was increased to 260 bytes in cbeac903e86bfb0c50f55960201f9eaa9d45745a, and this should improve the situation with paste.

**Comment by mindforger** [comment]
Uhhhh the word alignment would explain the pattern of the failure, didn't know this is a thing with stm
