### ISSUE TITLE
esp8266, esp.sleep()

### ISSUE THREAD

**Issue by apollo2mond** [micropython/micropython#4735]
Hi,
as documented for esp.sleep_type(), the arguments SLEEP_NONE, SLEEP_LIGHT, SLEEP_MODEM are not pre-defined .

**Comment by dpgeorge** [comment]
>  the arguments SLEEP_NONE, SLEEP_LIGHT, SLEEP_MODEM are not pre-defined .

They are in the `esp` module as `esp.SLEEP_NONE` etc.

**Comment by apollo2mond** [comment]
Got it, my fault - many thanks for the hints.
Confirmed therefore lets closed the issue.
