### ISSUE TITLE
ports/stm32: Can't change CPU frequency on NUCLEO_F401RE board

### ISSUE THREAD

**Issue by dhylands** [micropython/micropython#4737]
Trying to change the frequency using the latest master causes a FATAL ERROR.

I tested using pyb and machine modules and tried various frequencies like 42 MHz and 64 MHz).

All attempts result in this:
```
MicroPython v1.10-290-g8402c26cf-dirty on 2019-05-01; NUCLEO-F401RE with STM32F401xE
Type "help()" for more information.
>>> machine.freq(42000000)

FATAL ERROR:
can't change freq
```

Originally brought up in the forum: https://forum.micropython.org/viewtopic.php?f=12&t=6365&p=36215

**Comment by dpgeorge** [comment]
Thanks for the report.  The issue was that the NUCLEO-F401 uses HSI instead of HSE (as source for the PLL) and that didn't support changing the frequency.  Should be fixed by 3fbf32b947eb798cf4a717adc23026e677d06bf0
