### ISSUE TITLE
raspberry pi fail to build micropython

### ISSUE THREAD

**Issue by zazinio** [micropython/micropython#4755]
hi I'm noob and I'm using rspberry pi b3+ V1.3
and rasbian version
`pi@raspberrypi:~ $ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.9 (stretch)
Release:	9.9
Codename:	stretch`
when I try to install micropython build crash with error
`pi@raspberrypi:~ $ git clone https://github.com/micropython/micropython.git
Клониране и създаване на хранилище в „micropython“…
remote: Enumerating objects: 40, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 69980 (delta 17), reused 18 (delta 12), pack-reused 69940
Получаване на обекти: 100% (69980/69980), 39.39 MiB | 3.76 MiB/s, действието завърши.
Откриване на съответните разлики: 100% (50525/50525), действието завърши.
pi@raspberrypi:~ $ cd micropython
pi@raspberrypi:~/micropython $ git pull
Already up-to-date.
pi@raspberrypi:~/micropython $ cd ports
pi@raspberrypi:~/micropython/ports $ cd unix
pi@raspberrypi:~/micropython/ports/unix $ make clean
Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
rm -f micropython
rm -f micropython.map
rm -rf build 
pi@raspberrypi:~/micropython/ports/unix $ make axtls
Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
You cloned without --recursive, fetching submodules for you.
(cd ../..; git submodule update --init --recursive)
Регистриран е подмодул „lib/axtls“ (https://github.com/pfalcon/axtls) за пътя към подмодул „lib/axtls“
Регистриран е подмодул „lib/berkeley-db-1.xx“ (https://github.com/pfalcon/berkeley-db-1.xx) за пътя към подмодул „lib/berkeley-db-1.xx“
Регистриран е подмодул „lib/libffi“ (https://github.com/atgreen/libffi) за пътя към подмодул „lib/libffi“
Регистриран е подмодул „lib/lwip“ (https://git.savannah.gnu.org/r/lwip.git) за пътя към подмодул „lib/lwip“
Регистриран е подмодул „lib/nrfx“ (https://github.com/NordicSemiconductor/nrfx.git) за пътя към подмодул „lib/nrfx“
Регистриран е подмодул „lib/stm32lib“ (https://github.com/micropython/stm32lib) за пътя към подмодул „lib/stm32lib“
Клониране и създаване на хранилище в „/home/pi/micropython/lib/axtls“…
Клониране и създаване на хранилище в „/home/pi/micropython/lib/berkeley-db-1.xx“…
Клониране и създаване на хранилище в „/home/pi/micropython/lib/libffi“…
Клониране и създаване на хранилище в „/home/pi/micropython/lib/lwip“…
Клониране и създаване на хранилище в „/home/pi/micropython/lib/nrfx“…
Клониране и създаване на хранилище в „/home/pi/micropython/lib/stm32lib“…
Път към подмодул „lib/axtls“: изтеглена е версия „43a6e6bd3bbc03dc501e16b89fba0ef042ed3ea0“
Път към подмодул „lib/berkeley-db-1.xx“: изтеглена е версия „35aaec4418ad78628a3b935885dd189d41ce779b“
Път към подмодул „lib/libffi“: изтеглена е версия „e9de7e35f2339598b16cbb375f9992643ed81209“
Път към подмодул „lib/lwip“: изтеглена е версия „92f23d6ca0971a32f2085b9480e738d34174417b“
Път към подмодул „lib/nrfx“: изтеглена е версия „d4ebe15f58de1442e3eed93b40d13930e7785903“
Път към подмодул „lib/stm32lib“: изтеглена е версия „a5e93de18479879dd129cf6272cfd75e0c794bd4“
pi@raspberrypi:~/micropython/ports/unix $ make
Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
mkdir -p build/genhdr
GEN build/genhdr/mpversion.h
GEN build/genhdr/moduledefs.h
GEN build/genhdr/qstr.i.last
GEN build/genhdr/qstr.split
GEN build/genhdr/qstrdefs.collected.h
QSTR updated
GEN build/genhdr/qstrdefs.generated.h
mkdir -p build/build/
mkdir -p build/extmod/
mkdir -p build/lib/axtls/crypto/
mkdir -p build/lib/axtls/ssl/
mkdir -p build/lib/berkeley-db-1.xx/btree/
mkdir -p build/lib/berkeley-db-1.xx/mpool/
mkdir -p build/lib/embed/
mkdir -p build/lib/mp-readline/
mkdir -p build/lib/oofatfs/
mkdir -p build/lib/timeutils/
mkdir -p build/lib/utils/
mkdir -p build/py/
CC ../../py/mpstate.c
CC ../../py/nlr.c
CC ../../py/nlrx86.c
CC ../../py/nlrx64.c
CC ../../py/nlrthumb.c
CC ../../py/nlrxtensa.c
CC ../../py/nlrsetjmp.c
CC ../../py/malloc.c
CC ../../py/gc.c
CC ../../py/pystack.c
CC ../../py/qstr.c
CC ../../py/vstr.c
CC ../../py/mpprint.c
CC ../../py/unicode.c
CC ../../py/mpz.c
CC ../../py/reader.c
CC ../../py/lexer.c
CC ../../py/parse.c
CC ../../py/scope.c
CC ../../py/compile.c
CC ../../py/emitcommon.c
CC ../../py/emitbc.c
CC ../../py/asmbase.c
CC ../../py/asmx64.c
CC ../../py/emitnx64.c
CC ../../py/asmx86.c
CC ../../py/emitnx86.c
CC ../../py/asmthumb.c
CC ../../py/emitnthumb.c
CC ../../py/emitinlinethumb.c
CC ../../py/asmarm.c
CC ../../py/emitnarm.c
CC ../../py/asmxtensa.c
CC ../../py/emitnxtensa.c
CC ../../py/emitinlinextensa.c
CC ../../py/formatfloat.c
CC ../../py/parsenumbase.c
CC ../../py/parsenum.c
CC ../../py/emitglue.c
CC ../../py/persistentcode.c
CC ../../py/runtime.c
CC ../../py/runtime_utils.c
CC ../../py/scheduler.c
CC ../../py/nativeglue.c
CC ../../py/stackctrl.c
CC ../../py/argcheck.c
CC ../../py/warning.c
CC ../../py/map.c
CC ../../py/obj.c
CC ../../py/objarray.c
CC ../../py/objattrtuple.c
CC ../../py/objbool.c
CC ../../py/objboundmeth.c
CC ../../py/objcell.c
CC ../../py/objclosure.c
CC ../../py/objcomplex.c
CC ../../py/objdeque.c
CC ../../py/objdict.c
CC ../../py/objenumerate.c
CC ../../py/objexcept.c
CC ../../py/objfilter.c
CC ../../py/objfloat.c
CC ../../py/objfun.c
CC ../../py/objgenerator.c
CC ../../py/objgetitemiter.c
CC ../../py/objint.c
CC ../../py/objint_longlong.c
CC ../../py/objint_mpz.c
CC ../../py/objlist.c
CC ../../py/objmap.c
CC ../../py/objmodule.c
CC ../../py/objobject.c
CC ../../py/objpolyiter.c
CC ../../py/objproperty.c
CC ../../py/objnone.c
CC ../../py/objnamedtuple.c
CC ../../py/objrange.c
CC ../../py/objreversed.c
CC ../../py/objset.c
CC ../../py/objsingleton.c
CC ../../py/objslice.c
CC ../../py/objstr.c
CC ../../py/objstrunicode.c
CC ../../py/objstringio.c
CC ../../py/objtuple.c
CC ../../py/objtype.c
CC ../../py/objzip.c
CC ../../py/opmethods.c
CC ../../py/sequence.c
CC ../../py/stream.c
CC ../../py/binary.c
CC ../../py/builtinimport.c
CC ../../py/builtinevex.c
CC ../../py/builtinhelp.c
CC ../../py/modarray.c
CC ../../py/modbuiltins.c
CC ../../py/modcollections.c
CC ../../py/modgc.c
CC ../../py/modio.c
CC ../../py/modmath.c
CC ../../py/modcmath.c
CC ../../py/modmicropython.c
CC ../../py/modstruct.c
CC ../../py/modsys.c
CC ../../py/moduerrno.c
CC ../../py/modthread.c
CC ../../py/vm.c
CC ../../py/bc.c
CC ../../py/showbc.c
CC ../../py/repl.c
CC ../../py/smallint.c
CC ../../py/frozenmod.c
CC ../../extmod/moductypes.c
CC ../../extmod/modujson.c
CC ../../extmod/modure.c
CC ../../extmod/moduzlib.c
CC ../../extmod/moduheapq.c
CC ../../extmod/modutimeq.c
CC ../../extmod/moduhashlib.c
CC ../../extmod/moducryptolib.c
CC ../../extmod/modubinascii.c
CC ../../extmod/virtpin.c
CC ../../extmod/machine_mem.c
CC ../../extmod/machine_pinbase.c
CC ../../extmod/machine_signal.c
CC ../../extmod/machine_pulse.c
CC ../../extmod/machine_i2c.c
CC ../../extmod/machine_spi.c
CC ../../extmod/modussl_axtls.c
CC ../../extmod/modussl_mbedtls.c
CC ../../extmod/modurandom.c
CC ../../extmod/moduselect.c
CC ../../extmod/moduwebsocket.c
CC ../../extmod/modwebrepl.c
CC ../../extmod/modframebuf.c
CC ../../extmod/vfs.c
CC ../../extmod/vfs_reader.c
CC ../../extmod/vfs_posix.c
CC ../../extmod/vfs_posix_file.c
CC ../../extmod/vfs_fat.c
CC ../../extmod/vfs_fat_diskio.c
CC ../../extmod/vfs_fat_file.c
CC ../../extmod/utime_mphal.c
CC ../../extmod/uos_dupterm.c
CC ../../lib/embed/abort_.c
CC ../../lib/utils/printf.c
GEN build/frozen.c
CC build/frozen.c
make[1]: Entering directory '/home/pi/micropython/mpy-cross'
Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
mkdir -p build/genhdr
GEN build/genhdr/mpversion.h
GEN build/genhdr/moduledefs.h
GEN build/genhdr/qstr.i.last
GEN build/genhdr/qstr.split
GEN build/genhdr/qstrdefs.collected.h
QSTR updated
GEN build/genhdr/qstrdefs.generated.h
mkdir -p build/py/
CC ../py/mpstate.c
CC ../py/nlr.c
CC ../py/nlrx86.c
CC ../py/nlrx64.c
CC ../py/nlrthumb.c
CC ../py/nlrxtensa.c
CC ../py/nlrsetjmp.c
CC ../py/malloc.c
CC ../py/gc.c
CC ../py/pystack.c
CC ../py/qstr.c
CC ../py/vstr.c
CC ../py/mpprint.c
CC ../py/unicode.c
CC ../py/mpz.c
CC ../py/reader.c
CC ../py/lexer.c
CC ../py/parse.c
CC ../py/scope.c
CC ../py/compile.c
CC ../py/emitcommon.c
CC ../py/emitbc.c
CC ../py/asmbase.c
CC ../py/asmx64.c
CC ../py/emitnx64.c
CC ../py/asmx86.c
CC ../py/emitnx86.c
CC ../py/asmthumb.c
CC ../py/emitnthumb.c
CC ../py/emitinlinethumb.c
CC ../py/asmarm.c
CC ../py/emitnarm.c
CC ../py/asmxtensa.c
CC ../py/emitnxtensa.c
CC ../py/emitinlinextensa.c
CC ../py/formatfloat.c
CC ../py/parsenumbase.c
CC ../py/parsenum.c
CC ../py/emitglue.c
CC ../py/persistentcode.c
CC ../py/runtime.c
CC ../py/runtime_utils.c
CC ../py/scheduler.c
CC ../py/nativeglue.c
CC ../py/stackctrl.c
CC ../py/argcheck.c
CC ../py/warning.c
CC ../py/map.c
CC ../py/obj.c
CC ../py/objarray.c
CC ../py/objattrtuple.c
CC ../py/objbool.c
CC ../py/objboundmeth.c
CC ../py/objcell.c
CC ../py/objclosure.c
CC ../py/objcomplex.c
CC ../py/objdeque.c
CC ../py/objdict.c
CC ../py/objenumerate.c
CC ../py/objexcept.c
CC ../py/objfilter.c
CC ../py/objfloat.c
CC ../py/objfun.c
CC ../py/objgenerator.c
CC ../py/objgetitemiter.c
CC ../py/objint.c
CC ../py/objint_longlong.c
CC ../py/objint_mpz.c
CC ../py/objlist.c
CC ../py/objmap.c
CC ../py/objmodule.c
CC ../py/objobject.c
CC ../py/objpolyiter.c
CC ../py/objproperty.c
CC ../py/objnone.c
CC ../py/objnamedtuple.c
CC ../py/objrange.c
CC ../py/objreversed.c
CC ../py/objset.c
CC ../py/objsingleton.c
CC ../py/objslice.c
CC ../py/objstr.c
CC ../py/objstrunicode.c
CC ../py/objstringio.c
CC ../py/objtuple.c
CC ../py/objtype.c
CC ../py/objzip.c
CC ../py/opmethods.c
CC ../py/sequence.c
CC ../py/stream.c
CC ../py/binary.c
CC ../py/builtinimport.c
CC ../py/builtinevex.c
CC ../py/builtinhelp.c
CC ../py/modarray.c
CC ../py/modbuiltins.c
CC ../py/modcollections.c
CC ../py/modgc.c
CC ../py/modio.c
CC ../py/modmath.c
CC ../py/modcmath.c
CC ../py/modmicropython.c
CC ../py/modstruct.c
CC ../py/modsys.c
CC ../py/moduerrno.c
CC ../py/modthread.c
CC ../py/vm.c
CC ../py/bc.c
CC ../py/showbc.c
CC ../py/repl.c
CC ../py/smallint.c
CC ../py/frozenmod.c
CC main.c
CC gccollect.c
LINK mpy-cross
collect2: fatal error: ld terminated with signal 11 [Нарушение на разделянето(segfault)]
compilation terminated.
../py/mkrules.mk:132: recipe for target 'mpy-cross' failed
make[1]: *** [mpy-cross] Error 1
make[1]: *** Deleting file 'mpy-cross'
make[1]: Leaving directory '/home/pi/micropython/mpy-cross'
../../py/mkrules.mk:108: recipe for target '../../mpy-cross/mpy-cross' failed
make: *** [../../mpy-cross/mpy-cross] Error 2
pi@raspberrypi:~/micropython/ports/unix $ `

**Comment by dhylands** [comment]
This type of issue is better dicussed on the forum: https://forum.micropython.org/

I tried this and it worked fine for me. I use a 3B+ and the 2019-04-08-raspbian-stretch-lite.zip version of raspbian on an 8 Gb SDCard.

After flasing and booting up, I did the following commands:
```
sudo apt update
sudo apt upgrade
sudo apt install git
sudo apt install libffi-dev
git clone https://github.com/micropython/micropython
cd micropython/ports/unix/
git submodule update --init
make
```
And it ran:
```
pi@gateway:~/micropython/ports/unix$ ./micropython 
MicroPython v1.10-326-g089c9b71d on 2019-05-06; linux version
Use Ctrl-D to exit, Ctrl-E for paste mode
>>> 
```

How much free space do you have on your sdcard?
Do you have a good power suppply?
Perhaps try a different sdcard.

**Comment by zazinio** [comment]
Sorry if I am in the wrong place
I am noob but fixed the problem by mistake.
Did not conect to wifi and build succeeded.

"How much free space do you have on your sdcard?
Do you have a good power suppply?
Perhaps try a different sdcard." 
It's 32GB sdcard with fresh install so it has free space.
Power supply and sd card are ok
