### ISSUE TITLE
How to switch on a electric bulb with ESP8266 board?

### ISSUE THREAD

**Issue by rajarameshmamidi** [micropython/micropython#4764]
Hi Team,

I am new to Micropython and started learning from https://docs.micropython.org/en/latest/. currently i started with ESP8266 board and i am able to blink inbuilt LED's on the board. while googling i got to know we can use ESP8266 board for home automation(IOT). Now i am trying to switch on electric bulb with the help of ESP8266 board. can someone help me how to do this (or) share a link where i can find the details   

Thanks in advance,
Raja

**Comment by peterhinch** [comment]
This is best raised in [the forum](http://forum.micropython.org/index.php) rather than this MicroPython bug tracker.
