### ISSUE TITLE
Towards consistent Foreign Function/Data Interface across unix/baremetal

### ISSUE THREAD

**Issue by pfalcon** [micropython/micropython#478]
Let's first settle with terminology, this stuff is usually called FFI (Foreign Function Interface). One response can be that STM and other MCU ports don't need to call "foreign functions", but to call functions, need to deal with "foreign data", so it's closely related. Also, no need to dismiss FFI for MCU either - there's growing tendency among the vendors to include ROMs with drivers/routines in the designs (NXP and TI were spotted).

Anyway, unix port had for an "ffi" module based on libffi, and stmhal port recently got "stm" module (3f4898456bb1a451e5e6d45cb62c9c718f2b8a76). They offer (in data access category):
- ffi: ability to access variables of simple types imported from dynamic libs.
- stm: ability to read/write memory of standard sizes from (almost) arbitrary address.

Before going further with any of them, it would be nice to consider what Python offers to help with this area:
- struct module: take something having buffer interface and parse it as a structure, with various data types and alignments support.
- struct array: allocate a memory array of native types and access with sequence interface.
- int.from_bytes()/int.to_bytes(): convert between native and Python int - concisely and with builtin types only.
- memoryview: Allows to expose C-level buffer interface as bytes-like object. Alternative view is that this creates a pointer to object and allows to access underlying object via pointer.

All types but the latter are already partially implemented in uPy. Besides implementing pure memoryview object, the last big step would be to implement memoryview-alike, which would be created from arbitrary memory address. This object then can be used with with struct and from/to_bytes. And final small step is to extend array.array to be able to use memoryview as backing store instead of always allocating a new memory.

That's the idea. To clarify: I don't call for dismissal of existing ffi/stm modules - I just call not to create further adhoc extensions in them, if extended functionality can be well, consistently, and in advanced manner can be covered by native Python interfaces.

Comments?

**Comment by dpgeorge** [comment]
The `uctypes` module was implemented to give a generic interface to foreign data.
