### ISSUE TITLE
esp32: uart deinit missing

### ISSUE THREAD

**Issue by nedoskiv** [micropython/micropython#4786]
Hello,

I was trying to start internet connection using GSM module and run into some troubles. A part from network.PPP stability there is kind a device restarts when comunicating with modem over serial after network.PPP link is deactivated, [https://github.com/micropython/micropython/issues/4708](url) so I decided to deinit uart and init it again with hope it gonna solve that issue,but for my surprise uart.deinit is not available.

**Comment by dpgeorge** [comment]
UART.deinit() was implemented in 2630d3e51f3f4ac933e556bb3df2953698ac74fc

**Comment by nedoskiv** [comment]
Thank you, and if you can answer my next silly question, If I download tomorow latest binary from download page will it contain that implementation?

**Comment by dpgeorge** [comment]
It will now, it's updated every 12 hours.
