### ISSUE TITLE
VBAT_DIV wrongly defined for STM32F411xE in adc.c

### ISSUE THREAD

**Issue by AndreasBruring** [micropython/micropython#4794]
I found that the vbat readout for the Pyboard lite seems wrong.
its half the value it should be at read out in de python code

I stumbled on the root cause if this i the adc.c file.
the VBAT_DIV is wrongly defined for the STM32F411 chip is defined as 2 and needs to be 4 according to the data-sheet.

**Comment by dpgeorge** [comment]
Thanks for the report, indeed it should be 4.  Fixed by 1f63e9b701aa6398ddb2e0db5e3a0f7f5adb4fcf
