### ISSUE TITLE
bytesarray buffer  manipulation/copy fail

### ISSUE THREAD

**Issue by nedoskiv** [micropython/micropython#4810]
Hello,

I'm not a big expert at this, so I googled a little and found this topic:

[https://stackoverflow.com/questions/10633881/how-to-copy-a-python-bytearray-buffer](url)

but it do not work for me:

`c=b'\x11\x11'

a=b'\xff\xff'
a[:]=c
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'bytes' object doesn't support item assignment`

Also tried to change in lots of way value of any byte in the array it returns same error. Did I do something wrong or there is something not yet implemented?

**Comment by robert-hh** [comment]
That does not work in CPython either. A bytes object is immutable. bytearrays allow item assignment.

**Comment by nedoskiv** [comment]
Thank you
