### ISSUE TITLE
esp8266: "git submodule update --init" doesn't work

### ISSUE THREAD

**Issue by sajjad33** [micropython/micropython#4813]

**Comment by sajjad33** [comment]
git submodule update --init" doesn't work so I have some build error like:  
"compilation terminated.
In file included from ../../py/mphal.h:32:0,
                 from ../../lib/utils/pyexec.c:37:
./esp_mphal.h:69:19: fatal error: osapi.h: No such file or directory
 #include "osapi.h"
"

**Comment by dpgeorge** [comment]
The `osapi.h` file is not part of any submodule in this repository.  Instead it's part of the esp8266 SDK.  Please follow the instructions in `ports/esp8266/README.md` to get it building.
