### ISSUE TITLE
`AttributeError: 'Pin' object has no attribute 'on'`

### ISSUE THREAD

**Issue by cool-RR** [micropython/micropython#4816]
On my ESP32, this happens:

```
>>> import machine                                
>>> p = machine.Pin(2, machine.Pin.OUT)           
>>> p.on()                                        
Traceback (most recent call last):                
  File "<stdin>", line 1, in <module>             
AttributeError: 'Pin' object has no attribute 'on'
```

Even though the docs say that the `Pin.on` method works.

**Comment by robert-hh** [comment]
Maybe your firmware version is too old. Which version are you using?
Besides that, you may use p(1) and p(0) as faster method.

**Comment by cool-RR** [comment]
Is there a way to find the version from the shell by typing a command?

**Comment by robert-hh** [comment]
In REPL, Just Press Ctrl-B

**Comment by dpgeorge** [comment]
On esp32, the `on()` and `off()` methods first appeared in release v1.10.

**Comment by cool-RR** [comment]
Result: `MicroPython v1.9.4 on 2018-05-11; ESP32 module with ESP32`

**Comment by thinhx2** [comment]
> On esp32, the `on()` and `off()` methods first appeared in release v1.10.

thank
