### ISSUE TITLE
Question ESP32: UART, I2C pins

### ISSUE THREAD

**Issue by nedoskiv** [micropython/micropython#4852]
Hello,
Just a question about ESP32 pin, can I use almost any pin to open uart/i2c  communication,
I have used so far pin 23,21 to open uart comunication as they are not described as "uart" pin I assume that  can use everything, but better to ask first.

**Comment by peterhinch** [comment]
I suggest you raise this in [the forum](http://forum.micropython.org/index.php) rather than in this bug tracker.
