### ISSUE TITLE
build esp32 failed

### ISSUE THREAD

**Issue by yunling-cn** [micropython/micropython#4872]
`GEN build/esp-idf/lwip/liblwip.a.sections_info
GEN build/esp-idf/mbedtls/libmbedtls.a.sections_info
GEN build/esp-idf/wpa_supplicant/libwpa_supplicant.a.sections_info
GEN build/esp32.common.ld
LINK build/application.elf
   text	   data	    bss	    dec	    hex	filename
 845844	 223880	  27988	1097712	 10bff0	build/application.elf
Create build/application.bin
esptool.py v2.6

A fatal error occurred: Invalid segment count 25 (max 16). Usually this indicates a linker script problem.
make: *** [build/application.bin] error 2`

**Comment by dpgeorge** [comment]
Please make sure your toolchain and ESP IDF are the correct versions and follow all steps in `ports/esp32/README.md`.  If it still fails then please report the entire output of the build with `make V=1`.
