### ISSUE TITLE
makefile and Makefile for samd port

### ISSUE THREAD

**Issue by gengshenghong** [micropython/micropython#4890]
The newly added samd port has makefile and Makefile submitted, which will cause issues on systems like OSX (and windows) -> systems that has case-intensive filesystem to use any git command.

When git clone master branch on osx, we'll get below warning. And in fact, we cannot use any git command (like git checkout -b newbranch) then.
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'ports/samd/Makefile'
  'ports/samd/makefile'

**Comment by dpgeorge** [comment]
Yes, sorry, that was added by mistake.  Removed in 08075beeb9b45557f8ed6970e4e3e4a00bd26879
