### ISSUE TITLE
Use startup_stm32*.s file from stm32lib is not updated in the MBOOT makefile

### ISSUE THREAD

**Issue by TravisJoe** [micropython/micropython#4909]
It looks like in 6b6403ce76e11fd564d9bbe90f190c99fe4e4fa2 references to the STM32 libraries changed and is updated in STM32, but not in the MBOOT makefile.

**Comment by dpgeorge** [comment]
Thanks for the report.  Should be fixed by 342539bdcce5b00b53e01423bc57782d65d5ff4b
