### ISSUE TITLE
Add support for all UARTs on STM32F746 

### ISSUE THREAD

**Issue by JuanmaFerrandez** [micropython/micropython#4911]
I was wondering if it is possible to use others UARTs on the STM32F746.
At the moment, only works UART2, 3 and 6.

Thank you, best regards.

**Comment by dpgeorge** [comment]
Yes they are all supported.  It just requires adding configuration lines for the TX/RX pins to the corresponding `mpconfigboard.h` file.

**Comment by JuanmaFerrandez** [comment]
Okay, perfect.
It has been easy. I've also had to add pins to `pins.csv` file.
Thank you very much.
