### ISSUE TITLE
stm32F769 discovery: linker FLASH_APP size

### ISSUE THREAD

**Issue by hoihu** [micropython/micropython#4924]
I stumbled across this in the stm32F769 discovery board definitions:

https://github.com/micropython/micropython/blob/master/ports/stm32/boards/STM32F769DISC/f769_qspi.ld#L20

I believe this is a copy&paste error? Shouldn't it read ```length = 1920k``` since the internal FS is activated (text0 starts at 0x08020000)?

**Comment by dpgeorge** [comment]
Yes indeed it looks like a mistake.

**Comment by chrismas9** [comment]
`FLASH_APP   .isr_vector`
`FLASH_APP (rx)  : ORIGIN = 0x08020000, LENGTH = 2016K   /* sectors 1-11 3x32K 1*128K 7*256K */`

If isr is in FLASH_APP why doesn't FLASH_APP start at 0x08000000?
Also 0x08020000 is sector 4, not sector 1 as in comment.

**Comment by dpgeorge** [comment]
> If isr is in FLASH_APP why doesn't FLASH_APP start at 0x08000000?

Because this board (with this linker file) is configured to use mboot, so it's ISR table starts at 0x08020000.

> Also 0x08020000 is sector 4, not sector 1 as in comment.

Ok, that also needs fixing.

**Comment by dpgeorge** [comment]
Fixed by 02b2ad4fbdbfae3e06ee4d0c686be36509d53d7d
