### ISSUE TITLE
write_timed(..., DAC.NORMAL) not working on STM32

### ISSUE THREAD

**Issue by jimmo** [micropython/micropython#4944]
Raised in the forum https://forum.micropython.org/viewtopic.php?f=6&t=6725

Appears to be introduced by aa7b32c81136b1250d9515adf9d13eefd81e86d4 (works before, doesn't work after). Tested on PYBV11.

It looks like the first `write_timed(..., mode=DAC.NORMAL)` after hard reset works, but subsequent calls have no effect. If you `deinit` the DAC, then you get a single pulse (at full amplitude).

```
>>> import pyb
>>> d = pyb.DAC(1)
>>> b = bytearray([0,200,0,100,0])
>>> d.write_timed(b, 2000, mode=pyb.DAC.NORMAL) # Works
>>> d.write_timed(b, 2000, mode=pyb.DAC.NORMAL) # Doesn't work (no signal on X5)
>>> d.deinit()
>>> d.write_timed(b, 2000, mode=pyb.DAC.NORMAL) # Single pulse on X5
```

No issues with `mode=DAC.CIRCULAR`.

**Comment by dpgeorge** [comment]
Thanks for reporting.  The issue was with the DMA not being fully reset after the first write (for F4, F7 and H7 MCUs).  Should be fixed by b1129df4780abc5f140b473d10ebe5316793aac2
