### ISSUE TITLE
Cannot open file with 'r+' mode

### ISSUE THREAD

**Issue by EdwardTheLegend** [micropython/micropython#4945]
This is the error and the line that threw the error.

>>> file = open('test.txt','r+')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: illegal mode

**Comment by dpgeorge** [comment]
The `"r+"` is supported by most ports.  What port/board/version do you use?

**Comment by jonnor** [comment]
There is insufficient information available to understand this issue report. Proposing to close.

**Comment by robert-hh** [comment]
No response from the poster.
