### ISSUE TITLE
esp8266 AttributeError: 'module' object has no attribute 'gethostbyname'

### ISSUE THREAD

**Issue by gary094** [micropython/micropython#4948]
I try to get the ip from a domain on my esp8266 via

`ip = socket.gethostbyname("www.google.com")`

it gives me this error:

`AttributeError: 'module' object has no attribute 'gethostbyname'`

When I try to execute this on a normal python3 interpreter it works:

`Python 2.7.15+ (default, Nov 27 2018, 23:36:35)`
`[GCC 7.3.0] on linux2`
`Type "help", "copyright", "credits" or "license" for more information.`
`>>> import socket`
`>>> socket.gethostbyname("www.google.com")`
`'216.58.214.228'`
`>>>` 

What did I do wrong? Is resolving the ip from a given domain not supported by MicroPython?

**Comment by MrSurly** [comment]
Try `getaddrinfo` instead: `socket.getaddrinfo('www.google.com', 80)`
