### ISSUE TITLE
mpy could't find the variable when it use the under line prefix

### ISSUE THREAD

**Issue by PowerfulCat** [micropython/micropython#4957]
>>> _DEFAULT_ADDRESS     = const(0x7c >> 1)
>>> _DEFAULT_ADDRESS
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name '_DEFAULT_ADDRESS' is not defined
>>> DEFAULT_ADDRESS     = const(0x7c >> 1)
>>> DEFAULT_ADDRESS
62
>>>

**Comment by robert-hh** [comment]
The behavior is quite inconsistent. It works e.g.,
- when used in a function
- when _DEFAULT_ADDRESS is first assigned to another variable
- when _DEFAULT_ADRESS is not a const, but a regular value

**Comment by PowerfulCat** [comment]
thanks
