### ISSUE TITLE
Initial a WDT with timeout param, but it seem like useless?

### ISSUE THREAD

**Issue by Walkline80** [micropython/micropython#4964]
I am running some code in a new thread using While True. I feed the WDT every 2 seconds in this loop, but after the timeout period set by the WDT, the device will restart. I don't understand, I need a watch dog. But what I got is a timed restart device?

**Comment by Walkline80** [comment]
The firmware I am using is: MicroPython v1.11-115-g592f68449 on 2019-07-04; ESP32 module with ESP32

**Comment by dpgeorge** [comment]
Can you provide some minimal code which reproduces the problem?

**Comment by jimmo** [comment]
The issue seems to be that it's being fed from a different thread. Can't reproduce if I create the WDT and feed it from the REPL but if you feed it from a thread it fails:

```python
import machine
import time
import _thread

w = machine.WDT(timeout=5000)

def thread_fn():
    while True:
        time.sleep_ms(1000)
        print('feed')
        w.feed()

_thread.start_new_thread(thread_fn, ())
```

I see

```
>>> feed
feed
feed
feed
...resets
```

**Comment by jimmo** [comment]
Reading https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/system/wdts.html it sounds like this is the expected behaviour -- tasks (threads) have to feed their own watchdogs.

**Comment by dpgeorge** [comment]
Thanks for the test case.

Our machine.WDT is not really specific about whether it is a global WDT or a per-thread WDT, because this topic never came up before.

So at least it needs some clarification around that point.  And should we try to make it a global WDT instead (if that's possible)?

**Comment by Walkline80** [comment]
> The issue seems to be that it's being fed from a different thread. Can't reproduce if I create the WDT and feed it from the REPL but if you feed it from a thread it fails:
> 
> ```python
> import machine
> import time
> import _thread
> 
> w = machine.WDT(timeout=5000)
> 
> def thread_fn():
>     while True:
>         time.sleep_ms(1000)
>         print('feed')
>         w.feed()
> 
> _thread.start_new_thread(thread_fn, ())
> ```
> 
> I see
> 
> ```
> >>> feed
> feed
> feed
> feed
> ...resets
> ```

@jimmo you're right, that's the thing what I have done, but I'm using class instead.....

But there's another question, according to source code of machine.WDT, WDT's id must be 0, so we have only one WDT in every piece of board, is this right?

![TIM图片20190731155609](https://user-images.githubusercontent.com/5964879/62194158-e092b000-b3ab-11e9-8763-0bb405c45473.png)

**Comment by Walkline80** [comment]
> Thanks for the test case.
> 
> Our machine.WDT is not really specific about whether it is a global WDT or a per-thread WDT, because this topic never came up before.
> 
> So at least it needs some clarification around that point. And should we try to make it a global WDT instead (if that's possible)?

@dpgeorge see my last reply, it seems like we have only one WDT to use, so I think....a global WDT is  necessary and usefully :)

**Comment by dpgeorge** [comment]
>  it seems like we have only one WDT to use

It looks like there's one WDT for each thread.  Eg:
```python
import _thread, machine, time
def f():
    w = machine.WDT()
    while 1:
        print('feed')
        w.feed()
        time.sleep(1)
_thread.start_new_thread(f, ())
```
This won't crash.  But if the main thread starts its own WDT and doesn't feed it then it will.  So there are multiple WDT's (it's a software WDT not a hardware one).
