### ISSUE TITLE
ENODEV after flash micropython

### ISSUE THREAD

**Issue by petrkr** [micropython/micropython#5004]
When you upload fresh micropython, inisetup.setup() is performed. But if you try access to flash it will ends with error "ENODEV". Probably because mounted flash on different place.

This issue can be solved by re-run interpreter (CTRL+D) or soft-reset (machine.reset()) or with reset button)

Consider add "machine.reset()" into inisetup as we did at our fork:

https://github.com/petrkr/micropython/commit/f48eeaff36981e334c8ceac52baa00530ae8fb55

**Comment by dpgeorge** [comment]
Thanks for the report.  Should be fixed by baeebc557c3132fa17f3c902e260d5049f7c7957
