### ISSUE TITLE
network.LAN on NUCLEO_F429ZI

### ISSUE THREAD

**Issue by MichaelAkhnoukh** [micropython/micropython#5022]
i'm having the same issue presented in this thread
https://forum.micropython.org/viewtopic.php?f=12&t=6804

the REPL crashes whenever network.LAN() instance is created

**Comment by dpgeorge** [comment]
Unfortunately I don't have one of these boards to test it.  All development of the ETH driver was done an an F7xx MCU, although there were reports of it working on the F4.

Do you have an F7 Nucleo or Discovery board that you can test the same code on?

**Comment by MichaelAkhnoukh** [comment]
> Do you have an F7 Nucleo or Discovery board that you can test the same code on?

not yet

**Comment by MichaelAkhnoukh** [comment]
i've managed to fix the issue and created a pull request.

**Comment by dpgeorge** [comment]
Fixed by b1e04848ef62d20db42b0b30f24304307c4e6765

**Comment by TA1DB** [comment]
I confirm as of today network.LAN() works as expected on STM32F7DISC as well.
