### ISSUE TITLE
[STM32F0] Using legacy pyb functions (i.e. I2C) generate compile errors

### ISSUE THREAD

**Issue by rolandvs** [micropython/micropython#5052]
Running legacy code on the STM32F091 could be done by enabling the legacy flag for PYB in the mpconfigboard.h. However, it will generate a bunch of errors with pyb_i2c.c

**Comment by dpgeorge** [comment]
The old pyb_i2c.c won't be supported on newer MCUs (eg F0, L0, WB), so best to just rewrite the Python code to not rely on the legacy API functions (should not be difficult...).

**Comment by rolandvs** [comment]
So I did...
