### ISSUE TITLE
wrong MICROPY_HW_MCU_NAME

### ISSUE THREAD

**Issue by SabineTobi** [micropython/micropython#5058]
In micropython/ports/stm32/boards/NUCLEO_L073RZ/mpconfigboard.h
#define MICROPY_HW_MCU_NAME         "STM32F073RZT6"

Should'nt this be "STM32L073RZT6" ?

**Comment by dpgeorge** [comment]
Thanks for the report, fixed by 2b07f56c2b6fecb4074d461f7ec50e6e9975fcbe
