### ISSUE TITLE
Policy towards providing Python API extended from CPython's

### ISSUE THREAD

**Issue by pfalcon** [micropython/micropython#508]
I kinda touched that in #362, let me now be explicit: what is general approach about having extended API comparing to what CPython offers? Especially about pretty fringe and weird cases which border on being unPythonic - but on the other hand, which offer efficiency for MicroPython and in general not supposed to be used widely, but in special cases (like FFI interfaces).

For example, idea which crossed my mind and prompted to submit this ticket was having something like bytearray.freeze() method which would convert bytearray in-place into bytes.

**Comment by dpgeorge** [comment]
In general the policy is to try and follow CPython as closely as possible (to allow code to run easily under both MicroPython and CPython) and extensions be put into MicroPython-specific modules.  But there are lots of situations where this is not practical for MicroPython and decisions must be made on a case-by-case basis.
