### ISSUE TITLE
ESP 32 cam ,, micropython Won't deploy

### ISSUE THREAD

**Issue by Jasou** [micropython/micropython#5080]
$ make deploy
CC /home/pi/micropython/esp-idf/components/soc/esp32/rtc_clk.c
make: xtensa-esp32-elf-gcc: Command not found
make: *** [Makefile:991: build/bootloader//home/pi/micropython/esp-idf/components/soc/esp32/rtc_clk.o] Error 127

**Comment by dpgeorge** [comment]
It looks like you need to install the xtensa toolchain (compiler).  See `ports/esp32/README.md` for details.

**Comment by Jasou** [comment]
Thank you dpgeorge  but i got this error now : 
 CC /home/pi/micropython/esp-idf/components/soc/esp32/rtc_clk.c
/home/pi/micropython/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc: 1: /home/pi/micropython/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc: Syntax error: "(" unexpected
make: *** [Makefile:991: build/bootloader//home/pi/micropython/esp-idf/components/soc/esp32/rtc_clk.o] Error 2

**Comment by jonnor** [comment]
There is not information here to be able to debug this issue. The ESP32 build works in general. Proposing to close.

**Comment by robert-hh** [comment]
Most likely resolved.
