### ISSUE TITLE
mqtt iot aws - be or not to be

### ISSUE THREAD

**Issue by tcpipchip** [micropython/micropython#5097]
Hi,
Today i think to include again in the chapter book abou the AWS IOT using Micropython
My question is:
Is it implemented on ESP32 ?

=====================
See my code

import machine
from network import WLAN
import network
import time
from umqtt.simple import MQTTClient

DISCONNECTED = 0
CONNECTING = 1
CONNECTED = 2
MQTT_HOST = "XXXXXXXXX-ats.iot.us-east-1.amazonaws.com"
TOPIC = "$aws/things/lamp/shadow/update"
MQTT_CLIENT_ID = "lamp"
MQTT_PORT = 8883
state = DISCONNECTED

connection = None

wlan = network.WLAN(network.STA_IF)
wlan.active(True)
def pub_msg(msg):
        global connection
        connection.publish(topic=TOPIC, msg=msg, qos=0)
        print('Sending: ' + msg)

def run():
    global state
    global connection
    
    KEY_PATH = "/cert/dc5478fc78-private.pem"
    CERT_PATH = "/cert/dc5478fc78-certificate.pem"
    CACERT_PATH = "/cert/ca.pem" 
    with open(KEY_PATH, 'r') as f:
          key1 = f.read()
    print(key1)
    print(" ")
    with open(CACERT_PATH, 'r') as f:
          key2 = f.read()	
    print(key2)
    print(" ")
    with open(CERT_PATH, 'r') as f:
          cert1 = f.read()
    print(cert1)
    print(" ")
    
    while True:
        while state != CONNECTED:
              try:
                    state = CONNECTING
                    client = MQTTClient(client_id=MQTT_CLIENT_ID, server=MQTT_HOST, port=MQTT_PORT, keepalive=10000, ssl=True, ssl_params={"keyfile":KEY_PATH, "certfile":CERT_PATH, "ca_certs":CACERT_PATH, "server_side":False})
                    client.connect()
                    state = CONNECTED
              except:
                    print('Could not establish MQTT connection')
                    time.sleep(0.5)
                    continue
    print('MQTT LIVE!')

while state == CONNECTED:
      msg = '{"device_id":"some_id", "data":"some_data"}'
      pub_msg(msg)
      time.sleep(2.0)

while True:
      if 1==1:
          wlan.connect('Andreia e Miguel', 'XXXXX')
          while not wlan.isconnected():
                machine.idle()
          print('Connected...')
          run()
          break

**Comment by MrSurly** [comment]
`umqtt.simple` works just fine with AWS IoT (which is just MQTT under the hood), though you're required to use TLS.

Only real problem I've had is setting up the policies correctly on the AWS side.  I generally just create a "wide open" policy for development, and then lock down as necessary later.

**Comment by MrSurly** [comment]
Note that
```
ssl_params={"keyfile":KEY_PATH, "certfile":CERT_PATH, "ca_certs":CACERT_PATH, "server_side":False}
```
should be
```
ssl_params={"keyfile":key1, "certfile":cert1, server_side":False}
```

**Comment by tcpipchip** [comment]
all certificates are correct! I already sucessfully tested AWS IOT with ESP32 LUA, ESP32 AT COMMANDS, ARDUINO ESP32 and ESP-IDF. All published data!
Can you help me in private with MICROPYTHON ESP32 ? I can send you the certificates and source code for you or other friend test.

**Comment by tcpipchip** [comment]
my skype is **wisintainer**
"Miguel Alexandre Wisintainer"

**Comment by tcpipchip** [comment]
MicroPython v1.11-303-gc8c37ca40-dirty on 2019-09-11; Generic ESP32-D2WD module with ESP32-D2WD
Type "help()" for more information.
>>> MicroPython v1.11-303-gc8c37ca40-dirty on 2019-09-11; Generic ESP32-D2WD module with ESP32-D2WD

**Comment by MrSurly** [comment]
> all certificates are correct! I already sucessfully tested AWS IOT with ESP32 LUA, ESP32 AT COMMANDS, ARDUINO ESP32 and ESP-IDF. All published data!

I believe you, but your original code passed the _filename_ rather than the _contents_ of the file. Additionally, it used `keyfile` and `certfile` parameter names in `ssl_params`, where these should just be `key` and `cert`.

Here's some code that might help:

```
from umqtt.simple import MQTTClient
import sys

def getMqttClient(clientId, endpoint, cert, key):
    try:
        client = MQTTClient(
                    clientId,
                    endpoint,
                    ssl = True, 
                    ssl_params = {'key': key, 'cert': cert})
        r = client.connect()
        print('mqtt connect', ('failed' if r else 'succeeded'))
        return client
    except Exception as e:
        sys.print_exception(e)
        print('mqtt connect failed')
        return None
```

**Comment by tcpipchip** [comment]
Hi friend
I removed the CA CERTIFCATE from parameters (i dont know why) :(

client = MQTTClient(client_id="lamp", server="a1dl08fmj981lr-ats.iot.us-east-1.amazonaws.com", port=8883, keepalive=4000, ssl=True, ssl_params={ "key":key1, "cert":cert1, "server_side":False})
client.connect()

And got the following error now
Maybe this help us
assertion "ret == 0" failed: file "../../extmod/modussl_mbedtls.c", line 177, function: socket_new
abort() was called at PC 0x4014bebb on core 1

ELF file SHA256: 0000000000000000000000000000000000000000000000000000000000000000

Backtrace: 0x4008adb7:0x3ffc1d90 0x4008b0d5:0x3ffc1db0 0x4014bebb:0x3ffc1dd0 0x400eda99:0x3ffc1e00 0x400dfe71:0x3ffc1e50 0x400dbff9:0x3ffc1e80 0x400dc634:0x3ffc1ea0 0x400e94bd:0x3ffc1f00 0x400dff00:0x3ffc1fa0 0x400dbff9:0x3ffc1fd0 0x400dc061:0x3ffc1ff0 0x400e9477:0x3ffc2010 0x400dff00:0x3ffc20b0 0x400dbff9:0x3ffc20e0 0x400e93ed:0x3ffc2100 0x400dff00:0x3ffc21a0 0x400dbff9:0x3ffc2210 0x400dc026:0x3ffc2230 0x400f80d8:0x3ffc2250 0x400f833d:0x3ffc22f0 0x400f839b:0x3ffc2310 0x400f01ad:0x3ffc2330 0x40088845:0x3ffc2360

Rebooting...
ets Jun  8 2016 00:22:57

**Comment by tcpipchip** [comment]
@MrSurly Sabe error with your routine

Btw, here the code


import machine
from network import WLAN
import network
import time
from umqtt.robust import MQTTClient

DISCONNECTED = 0
CONNECTING = 1
CONNECTED = 2
MQTT_HOST = "xxxxxxxxxxxxxxxr-ats.iot.us-east-1.amazonaws.com"
TOPIC = "$aws/things/lamp/shadow/update"
MQTT_CLIENT_ID = "lamp"
MQTT_PORT = 8883
state = DISCONNECTED

connection = None

wlan = network.WLAN(network.STA_IF)
wlan.active(True)
def pub_msg(msg):
        global connection
        connection.publish(topic=TOPIC, msg=msg, qos=0)
        print('Sending: ' + msg)
        
def getMqttClient(clientId, endpoint, cert, key):
    try:
        client = MQTTClient(
                    clientId,
                    endpoint,
                    ssl = True, 
                    ssl_params = {'key': key, 'cert': cert})
        r = client.connect()
        print('mqtt connect', ('failed' if r else 'succeeded'))
        return client
    except Exception as e:
        print('mqtt connect failed')
        return None        
        
def run():
    global state
    global connection
    
    KEY_PATH = "/dc5478fc78-private.pem"
    CERT_PATH = "/dc5478fc78-certificate.pem"
    CACERT_PATH = "/ca.pem" 
    with open(KEY_PATH, 'r') as f:
          key1 = f.read()
    print(key1)
    print(" ")
    with open(CACERT_PATH, 'r') as f:
          key2 = f.read()	
    print(key2)
    print(" ")
    with open(CERT_PATH, 'r') as f:
          cert1 = f.read()
    print(cert1)
    print(" ")
    
    client = MQTTClient(client_id="lamp", server="a1dl08fmj981lr-ats.iot.us-east-1.amazonaws.com", port=8883, keepalive=4000, ssl=True, ssl_params={ "key":key1, "cert":cert1, "server_side":False})
    client.connect()
    print('MQTT LIVE!')

while state == CONNECTED:
      msg = '{"device_id":"some_id", "data":"some_data"}'
      pub_msg(msg)
      time.sleep(2.0)


while True:
      if 1==1:
          wlan.connect('Andreia e Miguel', 'xxxxxxxx')
          while not wlan.isconnected():
                machine.idle()
          print('Connected...')
          run()
          break

**Comment by tcpipchip** [comment]
that making me crazy!
https://www.dropbox.com/s/i2bl7fwsewjqdhp/testa.py?dl=0
here the code...

**Comment by tcpipchip** [comment]
got help from Eric
But, i am still having error
[0;32mI (24738) network: CONNECTED[0m
[0;32mI (26938) event: sta ip: 192.168.0.23, mask: 255.255.255.0, gw: 192.168.0.1[0m
[0;32mI (26938) network: GOT_IP[0m
assertion "ret == 0" failed: file "../../extmod/modussl_mbedtls.c", line 177, function: socket_new
abort() was called at PC 0x4014bebb on core 1

ELF file SHA256: 0000000000000000000000000000000000000000000000000000000000000000

Backtrace: 0x4008adb7:0x3ffc1c70 0x4008b0d5:0x3ffc1c90 0x4014bebb:0x3ffc1cb0 0x400eda99:0x3ffc1ce0 0x400dfe71:0x3ffc1d30 0x400dbff9:0x3ffc1d60 0x400dc634:0x3ffc1d80 0x400e94bd:0x3ffc1de0 0x400dff00:0x3ffc1e80 0x400dbff9:0x3ffc1eb0 0x400dc061:0x3ffc1ed0 0x400e9477:0x3ffc1ef0 0x400dff00:0x3ffc1f90 0x400dbff9:0x3ffc1fc0 0x400e93ed:0x3ffc1fe0 0x400dff00:0x3ffc2080 0x400dbff9:0x3ffc20f0 0x400e93ed:0x3ffc2110 0x400dff00:0x3ffc21b0 0x400dbff9:0x3ffc2210 0x400dc026:0x3ffc2230 0x400f80d8:0x3ffc2250 0x400f8324:0x3ffc22f0 0x400f01f4:0x3ffc2330 0x40088845:0x3ffc2360

Rebooting...
ets Jun  8 2016 00:22:57

Did solve that problem ?

Thanks

**Comment by tcpipchip** [comment]
Wich esp32 model are you using ? Am i having memory problem ?

**Comment by MrSurly** [comment]
@tcpipchip 

Looking at the code in `modussl_mbedtls.c`:

```        
175: // len should include terminating null
176: ret = mbedtls_pk_parse_key(&o->pkey, key, key_len + 1, NULL, 0);
177: assert(ret == 0);
```

This shows that the key is not being parsed correctly.  

Can you post your code?

**Comment by tcpipchip** [comment]
yes, of course!

import network
from umqtt.simple import MQTTClient
import sys
import time

ssid     = 'Andreia e Miguel'
pw       = 'password'
endpoint = 'a1dl08fmj981lr-ats.iot.us-east-1.amazonaws.com'
clientId = 'MeuPrimeiroDispositivo'

with open('cert.pem') as f: cert = f.read()
with open('key.pem') as f: key = f.read()

def wifiConnect(ssid, pw):
    w = network.WLAN()
    w.active(1)
    w.connect(ssid, pw)
    t = time.time() + 10

    while not w.isconnected():
        if time.time() > t: return False
        time.sleep(.25)
    return True


def getMqttClient(clientId, endpoint, cert, key):
    try:
        client = MQTTClient(
                    clientId,
                    endpoint,
                    ssl = True,
                    ssl_params = {'key': key, 'cert': cert})
        r = client.connect()
        print('mqtt connect', ('failed' if r else 'succeeded'))
        return client
    except Exception as e:
        sys.print_exception(e)
        print('mqtt connect failed')
        return None
        

def run():
    print("Running...")

    if not wifiConnect(ssid, pw):
        raise RuntimeError('Wifi could not connect')

    client = getMqttClient(clientId, endpoint, cert, key)
    if client is None:
        raise RuntimeError('Could not connect to MQTT')
    print (client)

**Comment by MrSurly** [comment]
@tcpipchip 

Can you post the output of these commands:

`with open('cert.pem') as f: print(repr(f.read()))`
`with open('key.pem') as f: print(repr(f.read()))`

**Comment by tcpipchip** [comment]
give 10 minutes 
wait

**Comment by tcpipchip** [comment]
![image](https://user-images.githubusercontent.com/11488460/64874635-d78b3480-d621-11e9-82b2-dd64c337c523.png)

maybe the problem is the BEGIN and END CERTIFICATE texts ?

**Comment by MrSurly** [comment]
That looks like it should work.

**Comment by tcpipchip** [comment]
Yes! Something very scary is happening!
I cant believe!

**Comment by tcpipchip** [comment]
aborted again MicroPython with ESP32 :(

**Comment by tcpipchip** [comment]
Someday i will ask you to access my machine! You wont believe that!

Enviado do meu iPhone

Em 13 de set de 2019, às 14:15, Eric Poulsen <notifications@github.com<mailto:notifications@github.com>> escreveu:


That looks like it should work.

**Comment by HeMan** [comment]
Not sure about ESP32, but when doing TLS connection to AWS MQTT with ESP8266 port I needed to convert the certificates to DER format.

**Comment by tcpipchip** [comment]
@HeMan 
You got the power! :)

Well, i had think about this...but...the group didnt commented about...then i believed that is not necessary

team, can confirm ?

**Comment by Klabauterman** [comment]
Any news on this? I am having the same problem, that my esp reboots on opening the connection. And I noticed that I am getting the reboot on MicroPython 1.11, on newer versions it is telling me that my key is invalid.

**Comment by tcpipchip** [comment]
Still not! I aborted micropython! O went to circuitpython! And yesterday got success on awd iot

**Comment by Klabauterman** [comment]
I got it working in v1.11. It looks like pem-keys dont work here. You need DER keys. Just convert cert and key using openssl after downloading it from aws:

`openssl x509 -in 2cert.pem.crt -outform der -out cert.der`
`openssl rsa -in 2key.pem.key -outform der -out key.der`

**Comment by tcpipchip** [comment]
can you do step by step to the team ?

**Comment by tcpipchip** [comment]
i tried to put the ESP32 WROOM and :(
rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371

**Comment by tcpipchip** [comment]
https://micropython-nina-w102.blogspot.com/2020/05/w102-comandado-via-assistente-alexa.html

Running and i did the BLOG :)

**Comment by jonnor** [comment]
Several people seem to have gotten this to work. A key part seems to be to use DER keys/certificates, ref https://github.com/micropython/micropython/issues/5097#issuecomment-629679027
Proposing to close this issue.
