### ISSUE TITLE
Special treatment of null qstr means "NULL" is not valid in mpy-cross.

### ISSUE THREAD

**Issue by nevercast** [micropython/micropython#5140]
Minimum repro:

Create a file with the contents:
```
def expode():
    return "NULL"
```

Add this as a frozen file so that it is compiled with `mpy-cross` and output in to `frozen.c`. 
`frozen.c` now conflicts with `qstr.generated.h` with a duplicate `MP_QSTR_NULL` definition.

Seems to work fine in the REPL, presumably because the string is not QSTRd (interned)

```
build-wscale/frozen_mpy.c:764:5: error: redeclaration of enumerator 'MP_QSTR_NULL'
     MP_QSTR_NULL,
     ^
In file included from ../../py/obj.h:31:0,
                 from ../../py/objint.h:30,
                 from build-wscale/frozen_mpy.c:2:
build-wscale/genhdr/qstrdefs.generated.h:3:6: note: previous definition of 'MP_QSTR_NULL' was here
 QDEF(MP_QSTR_NULL, (const byte*)"\x00\x00\x00" "")
      ^
../../py/qstr.h:41:23: note: in definition of macro 'QDEF'
 #define QDEF(id, str) id,
                       ^
../../py/mkrules.mk:47: recipe for target 'build-wscale/build-wscale/frozen_mpy.o' failed
make: *** [build-wscale/build-wscale/frozen_mpy.o] Error 1
```

**Comment by pmp-p** [comment]
nice catch

**Comment by pmp-p** [comment]
afaik the QSTR parser is run first, then mpy-cross pass is applied but i don't think there's a filter for duplicates removal on the resulting file.

**Comment by nevercast** [comment]
`MP_QSTR_NULL` is a special value, it doesn't mean "NULL" it means missing / empty value, I found this out when exploring why my code breaks. So its not really a duplicate result. I'm not sure `__COUNTER__` or `__LINE__` will help in this case as the QSTRs need to be generated across all files. However I'm not intimately familiar with the interning process.

I'll wait for Damien to provide a suggestion, if we want to more intelligently handle the empty enum value, or handle "NULL" as a special case, or just ignore it all together. Though I'd prefer that valid strings didn't break frozen code generation.

**Comment by pmp-p** [comment]
indeed i had a look it seems the only special value. ie where "NULL" is not reproductible hash of real target value. looks like a corner case.

**Comment by pmp-p** [comment]
for anyone needed a quick temporart fix :
just freeze instead:
`def expose():
    return b"NULL".decode()
`

**Comment by pmp-p** [comment]
May i suggest making a tag [breaking changes?] available note the '?' for being nice to people who may *already* use MP_QSTR_NULL in their C/C++ module so they can access information, request more, and overall some time to prepare themselves ?

**Comment by nevercast** [comment]
In general MicroPython does not have semantic versioning and does not guarentee a fixed C/C++ API. Breaking changes are to be expected.
