### ISSUE TITLE
[STM32WB] USBDONGLE_WB55: I2C 

### ISSUE THREAD

**Issue by dmazzella** [micropython/micropython#5145]
I tried to communicate with several I2C slave devices (ATECC508A and ST25DV04K) but without success.

hw:
```
>>> i2c = machine.I2C (1, freq=400000)
>>> i2c.scan()
[]
>>>
```

sw:
```
>>> i2c = machine.I2C (-1, scl=machine.Pin.cpu.B8, sda=machine.Pin.cpu.B9, freq=400000)
>>> i2c.scan()
[]
>>>
```

can anyone communicate with i2c devices with the stm32wb?

**Comment by dpgeorge** [comment]
I didn't test this feature but it's surprising that the software I2C is not working.  Do you have pull-ups on the I2C lines?  Does basic GPIO work?

**Comment by dmazzella** [comment]
> I didn't test this feature but it's surprising that the software I2C is not working. Do you have pull-ups on the I2C lines? Does basic GPIO work?

Pull-up did the tricks.
