### ISSUE TITLE
ntptime bugs (esp8266 and esp32)

### ISSUE THREAD

**Issue by gmos** [micropython/micropython#5189]
The timeout for the ntp request is set to 1, which probably makes sense.  Due to this there is a high likelihood that the request times out, raising a [Errno 110] ETIMEDOUT.  In this case the socket stays open.  If this happens a couple of times, the file table runs out, resulting to OSError: 23 until re-boot.  The function should make sure that the socket is always closed.

Furthermore when the rtc clock is set, the day-of-week is always set to zero.  Since the day-of-week is computed by localtime, it could be set to its actual value. rtc.init(tm[0:3]+(tm[6]+1,)+tm[3:6]+(0,)) would do.

**Comment by dpgeorge** [comment]
Thanks for the report!  Both items should be fixed in 79ab82ea77b0a924e96c2f6333e00c97706971ab
