### ISSUE TITLE
AttributeError: 'socket' object has no attribute 'SOL_SOCKET' (ESP8266)

### ISSUE THREAD

**Issue by troublegum** [micropython/micropython#5191]
I have error:  "object has no attribute 'SOL_SOCKET'".

MicroPython v1.11-8-g48dcbbe60 on 2019-05-29; ESP module with ESP8266

**My code example:**
`import socket`
`socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)`
`socket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)`

What did I do wrong?

**Comment by dpgeorge** [comment]
> What did I do wrong?

You used the same variable `socket` for the module and the object.  Best to use something like `sock` for the object, eg:
```python
import socket
sock = socket.socket(...)
```

**Comment by troublegum** [comment]
Ups.. Thank you! It's works!
