### ISSUE TITLE
typo in BLE doc

### ISSUE THREAD

**Issue by poesel** [micropython/micropython#5215]
in:
https://github.com/micropython/micropython/blob/master/docs/library/bluetooth.rst

       HR_UUID = bluetooth.UUID(0x180D)
        HR_CHAR = (bluetooth.UUID(0x2A37), bluetooth.FLAG_READ | bluetooth.FLAG_NOTIFY,)
        HR_SERVICE = (HR_SERVICE, (HR_CHAR,),)

should read:

       HR_UUID = bluetooth.UUID(0x180D)
        HR_CHAR = (bluetooth.UUID(0x2A37), bluetooth.FLAG_READ | bluetooth.FLAG_NOTIFY,)
        HR_SERVICE = (HR_UUID, (HR_CHAR,),)

**Comment by dpgeorge** [comment]
Thanks for the report, fixed by d1ed73ca8f5034c1128de1fd995ca15eccb05ad9
