### ISSUE TITLE
WDT erroneously enabled ?

### ISSUE THREAD

**Issue by sengpw** [micropython/micropython#5243]
When running latest version of micropython (esp32spiram-20191011-v1.11-422-g98c2eabaf.bin) on attached code I get following runtime message:

E (2120640) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (2120640) task_wdt:  - IDLE1 (CPU 1)
E (2120640) task_wdt: Tasks currently running:
E (2120640) task_wdt: CPU 0: IDLE0
E (2120640) task_wdt: CPU 1: mp_task

When running code using micropython (esp32-20190529-v1.11.bin) runtime message does not appear. Is the latest version buggy? Or do I have to feed the watchdog? How?
[main.py.zip](https://github.com/micropython/micropython/files/3753048/main.py.zip)

**Comment by jimmo** [comment]
This has already been fixed recently, but for some reason the downloads page hasn't updated for 10 days. Hopefully will be updated soon.

**Comment by dpgeorge** [comment]
> for some reason the downloads page hasn't updated for 10 days

I'm looking into this...

**Comment by dpgeorge** [comment]
Daily builds are back (it was a problem with relative paths not working in a cron script).
