### ISSUE TITLE
WBUS-DIP28 Reset pin does not work.

### ISSUE THREAD

**Issue by peterhinch** [micropython/micropython#5250]
Momentarily grounding `rst` has no effect. Tested on two samples and confirmed by @jimmo [here](https://forum.micropython.org/viewtopic.php?f=20&t=7121).

The schematics appear to show a connection to the Pyboard's `nrst` line.

**Comment by dpgeorge** [comment]
> The schematics appear to show a connection to the Pyboard's `nrst` line.

It's not actually connected through.  The schematics have the nRST on the PYBD's WBUS ending in a small circle, so that is not connected to the NRST net.

The idea here is that you can "hot plug" tiles and reset them without resetting the PYBD itself.

**Comment by peterhinch** [comment]
OK. Sorry, I missed that.

**Comment by dpgeorge** [comment]
Maybe this requires some doc improvement?
