### ISSUE TITLE
Bug with Timer.freq() reporting wrong frequency

### ISSUE THREAD

**Issue by Bockwuhrst** [micropython/micropython#5280]
First time submitting an issue, so apologies if there's anything wrong.

Setting a timer to a low frequency sets the (almost) correct prescaler and period but reports wrong frequency.

```python
from pyb import Timer
tim2 = Timer(2, freq=0.001)
print(tim2.prescaler(), tim2.period())  # prints: 999 83999991
print(tim2.freq())  # prints: 0.03506409

# period should be 83999999 but that just seems to be a problem with floating point precision
```

Reason seams to be this line in [timer.c](https://github.com/micropython/micropython/blob/master/ports/stm32/timer.c)
```c
uint32_t divide = ((prescaler + 1) * (period + 1));
```

For big prescaler and period values their multiplication doesn't fit into a uint32_t.

**Comment by dpgeorge** [comment]
Thanks for the report.  Should be fixed by 9ec73aedb4fedafce93a018c26cfbc79686be34b
