### ISSUE TITLE
File erased on abrupt power in ESP32

### ISSUE THREAD

**Issue by hetvishah08** [micropython/micropython#5337]
Hello,
I'm using ESP32 Devkit C with the latest Micropython version. On abrupt power, all the files in the filesystem like - main.py, boot.py and other files get erased on the ESP32.
 
Opening the port through UPyCraft IDE, I wasn't able to access the device folder. On using Putty to check the files using  **os.listdir()** , I get garbage values in it.
   
```

os.listdir()

['\x00\x00\x00\x00\x00\x00\x00\x00.\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00.\x0 0\x00\x00','\x00\x00\x00\x00\x00\x00\x00\x00.\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00.\x0 0\x00\x00']                                                                                   

```
Brown-out detector might be a solution to protect the ESP32 from power changes on hardware side but I would like to know the software solutions of saving the ESP32 code memory from getting erased.

**Comment by peterhinch** [comment]
This should not occur unless you're writing to the filesystem at the time the power goes down.

**Comment by robert-hh** [comment]
Since recently, the ESP32 file system also supports littlefs2, which claim to be more robust. You have to use the daily build for that. A short note on using it is here: https://github.com/micropython/micropython/commit/4be316fb072ab7c2f28da815ead970ebf705c328

**Comment by hetvishah08** [comment]
> This should not occur unless you're writing to the filesystem at the time the power goes down.

  @peterhinch  No I have uploaded the code successfully while the circuit was receiving power.After that,the code was working fine till some time. As soon as there was power change,all the files got erased.

**Comment by hetvishah08** [comment]
> Since recently, the ESP32 file system also supports littlefs2, which claim to be more robust. You have to use the daily build for that. A short note on using it is here: [4be316f](https://github.com/micropython/micropython/commit/4be316fb072ab7c2f28da815ead970ebf705c328)

@robert-hh  I'll try it out.Thank you.

**Comment by nevercast** [comment]
Interesting that the file names and extentions have been zeroed but the file counts and name lengths seem to be intact.

**Comment by hetvishah08** [comment]
> Since recently, the ESP32 file system also supports littlefs2, which claim to be more robust. You have to use the daily build for that. A short note on using it is here: [4be316f](https://github.com/micropython/micropython/commit/4be316fb072ab7c2f28da815ead970ebf705c328)

@robert-hh  It worked.Thank you
