### ISSUE TITLE
stm32 NUCLEO_L073RZ master build overflowing flash

### ISSUE THREAD

**Issue by andrewleech** [micropython/micropython#5341]
micropython @ 973f6878 compiled with official arm gcc `arm-none-eabi:8-2019q3` is too large for the L073 chip, acording to https://gitlab.com/alelec/micropython_ci/-/jobs/354449202

```
arm-none-eabi-ld: /micropython_ci/micropython_stm32_NUCLEO_L073RZ_973f6878/firmware.elf section `.text' will not fit in region `FLASH'
arm-none-eabi-ld: region `FLASH' overflowed by 668 bytes
```

Looking at the CI history, it appears to have failed on the new Soft Timer impementation, 48b25a841 and/or a5d97f1db

**Comment by dpgeorge** [comment]
Should be fixed by 11c22430d4efe7eb8c87163faaae647b1e99abf8
