### ISSUE TITLE
[nucleo_f767zi] enabling sdcard generates errors

### ISSUE THREAD

**Issue by rolandvs** [micropython/micropython#5391]
Adding the sdcard flag and card detect pin to the board config file will generate errors when compiling, whereas the Nucleo_h743zi board file With sdcard enabled has no problems at all.  It is probably something very simple I’m overlooking?!

**Comment by rolandvs** [comment]
Moved

**Comment by dpgeorge** [comment]
It looks like the SDMMC pins are not defined in `pins.csv`.  Adding them there should fix it (please post a PR if this works!).

**Comment by rolandvs** [comment]
@dpgeorge You were right! I fixed it. I'll post a PR

**Comment by rolandvs** [comment]
Resolved in PR #5403
