### ISSUE TITLE
[NUCLEO_F767ZI] Internal Flash erased after every reset

### ISSUE THREAD

**Issue by rolandvs** [micropython/micropython#5402]
When initialising the Flash drive: hold user button, press reset, wait for two LEDs on, release user button. It will generate a file system on a volume with name "PYBFLASH" and the set of default files. Then after hitting the reset button and the drive re-appears the disk has the name "NO NAME" and is empty.

**Comment by dpgeorge** [comment]
I cannot reproduce this problem.  Using Linux, following the above process, the USB MSC drive is mountable after each reset and contains the factory files.

**Comment by rolandvs** [comment]
@dpgeorge I have bought another F767 board to see if the board in question is to be replaced and buried :-)

**Comment by dpgeorge** [comment]
It may be that the flash is worn.  You could try a mass erase.

**Comment by rolandvs** [comment]
Solved: the option bits of the F767 have a flag called nDBANK that needs to be set %^&*. The 2MByte Flash was divided in two 1MByte parts.
