### ISSUE TITLE
Many exp files seem to be missing in "tests"

### ISSUE THREAD

**Issue by jfroejk** [micropython/micropython#5417]
A lot of tests that used to have `.exp` files in earlier versions don't have any in the repository. Therefore a full set of tests can't be run from the current version.

The majority of files in `tests/basics` don't have an `.exp` file. There are also many tests in `misc`, `extmod`, `stress`, and `io` that don't have an `.exp` file.

**Comment by stinos** [comment]
No .exp file means the output is compared with the CPython output of the test file (i.e. test file is first ran with MicroPython, then with CPython, then output is compared), that's intended behaviour.

**Comment by jfroejk** [comment]
Thanks for explaining and thanks for a very fast reply.
