### ISSUE TITLE
MP_QSTR__slash_lib

### ISSUE THREAD

**Issue by pulkin** [micropython/micropython#5464]
I was in the process of copy-pasting some code from esp8266 to [my port](https://github.com/pulkin/micropython/tree/master/ports/gprs_a9). I realized that this code in `main.c`:
```c
     mp_obj_list_append(mp_sys_path, MP_OBJ_NEW_QSTR(MP_QSTR_)); // current dir (or base dir of the script)
     mp_obj_list_append(mp_sys_path, MP_OBJ_NEW_QSTR(MP_QSTR__slash_lib));
     mp_obj_list_append(mp_sys_path, MP_OBJ_NEW_QSTR(MP_QSTR__slash_));
```
produces this output
```python
>>> import sys
>>> sys.path
['', '_slash_lib', '/']
```
Is it the intended behaviour or it was fixed in the upstream recently?

**Comment by jimmo** [comment]
This relies on the qstr being defined explicitly (this provision exists for qstrs that can't be expressed using the MP_QSTR_foo syntax, e.g. if they contain non alphanumeric characters).

See https://github.com/micropython/micropython/blob/master/ports/stm32/qstrdefsport.h for how these are defined.
