### ISSUE TITLE
CRC32 in ubinascii?

### ISSUE THREAD

**Issue by jeremyherbert** [micropython/micropython#5486]
Just wondering what the appetite for adding `crc32` to `ubinascii` is? I use this a fair bit in CPython code, and I'd like to be able to use the exact same code in micropython.

I'm happy to do the patch myself, just asking for opinions here.

**Comment by mikewadsten** [comment]
Looks like it's already supported, behind a feature `#define`: https://github.com/micropython/micropython/blob/b9ec6037edf5e6ff6f8f400d70f7351d1b0af67d/extmod/modubinascii.c#L220

**Comment by jeremyherbert** [comment]
Doh, clearly missed that. Thanks.
