### ISSUE TITLE
schedule user callback when receving udp packet

### ISSUE THREAD

**Issue by jbgagnon** [micropython/micropython#5505]
Like usage in tcp, schedule user callback when receving udp packet

this is not a bug but an enhancement

Sample for testing

import socket, struct, time
soc = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
soc.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
soc.setblocking(False)

def my_cb(s):
    msg, adr = s.recvfrom(1024)
    print('cb recv from:',adr, 'len:', len(msg))
    s, = struct.unpack("!L",msg[40:44])
    t = time.localtime(s - 36524 * 86400)
    print(t)
soc.setsockopt(socket.SOL_SOCKET, 20, my_cb)

aa = socket.getaddrinfo('fr.pool.ntp.org', 123, socket.AF_INET)[0][-1]
print(aa)

msg = bytearray(48)
msg[0] = 27
soc.sendto(msg, aa)

**Comment by jonnor** [comment]
Hi and thank you for reporting. This would be good to have. There is an existing issue open about it, discussion should continue there https://github.com/micropython/micropython/issues/5505
