### ISSUE TITLE
esp32: cannot set RMT idle level

### ISSUE THREAD

**Issue by jonathanhogg** [micropython/micropython#5539]
Hi there,

Any chance of getting a hook to set the idle level for an RMT object? I need to be able to generate a precisely-timed active-low output, for which an RMT would be perfect except that it is hard-wired at the moment to idle low. It looks like it'd only be a small change in `esp32_rmt_make_new`.

Jonathan

**Comment by MrSurly** [comment]
Per https://github.com/micropython/micropython/pull/5184#issuecomment-569462169, that feature is in the works.

**Comment by jonathanhogg** [comment]
@MrSurly awesome! Any idea on a timeline?

I'm attempting to setup the build environment to generate my own firmware in the meantime…

**Comment by MrSurly** [comment]
@mattytrentini is driving the RMT dev.  The branch is [here](https://github.com/mattytrentini/micropython/tree/esp32_rmt2).  I'm just watching the dev myself for possible future use.

**Comment by jonathanhogg** [comment]
Ah! Apologies to you, @MrSurly, and to @mattytrentini for confusion.

Excitingly, and in my eagerness to get this working, I have managed to get a working build environment so I've produced firmware with an `idle_level` change incorporated…

**Comment by MrSurly** [comment]
May I ask your use case?

**Comment by jonathanhogg** [comment]
@MrSurly Sure!

I'm working on directly driving some drone-motor electronic speed controllers. They use a one-wire protocol ("DSHOT") that is very similar to NeoPixels, but operates at different speeds and with the line idling high.

Documentation on these things is incredibly thin-on-the-ground, so I'm working backwards from oscilloscope traces of the outputs of a working drone flight controller.

It's actually for a crazy art installation rather than anything like a quad copter, which is why I'm not just using a standard flight controller.

**Comment by MrSurly** [comment]
Ah, okay, so a digital update to the old 1-2ms servo control.  My own interest is the RMT is also around reading and sending RC signals, though using PPM.

**Comment by jonathanhogg** [comment]
Fix for this is in PR #6274, which will perhaps one day see mainline. In the meantime I am just using my own build so this issue isn't really doing anything useful.
