### ISSUE TITLE
drives / onewire / _search_rom / Implement Alarm Search  

### ISSUE THREAD

**Issue by ioiogamboa** [micropython/micropython#5571]
Maybe you can add an argument to _search_rom in order to implement de function Alarm Search (Function Command 0xEC). I taked your code and simply replace sentence **"self.writebyte(SEARCH_ROM)"** with self.writebyte(ALARM_SEARCH), ALARM_SEARCH=0xEC** and it work. Te only difference from these two command is that only response de ROMS which alarm were triggered.
If you add additional argument indicated de type of search you will add new functionality to the library.
Thanks a Lot.

**Comment by tve** [comment]
Since you have the solution, how about preparing a pull request (with docs update)?

**Comment by ioiogamboa** [comment]
I agree with you. I'll do it.
