### ISSUE TITLE
No tell() in BytesIO

### ISSUE THREAD

**Issue by dogtopus** [micropython/micropython#5581]
Attempting to use `tell()` in `BytesIO` results in an AttributeError.

```
MicroPython v1.12-87-g96716b46e on 2020-01-23; F4DISC with STM32F407            
Type "help()" for more information.                                             
>>> import io                                                                   
>>> a=io.BytesIO()                                                              
>>> a.tell()                                                                    
Traceback (most recent call last):                                              
  File "<stdin>", line 1, in <module>                                           
AttributeError: 'BytesIO' object has no attribute 'tell'                        
>>> 
```

**Comment by robert-hh** [comment]
Instead you could use: 
a.seek(0,  1)

**Comment by dogtopus** [comment]
> Instead you could use:
> `a.seek(0, 1)`
> Funny enough, there is a tell function in stream.c, but no QSTR for the API.

Yea that could work. However I don't really like a lot of workarounds in the code. Besides that it should be easy to just add it to MicroPython. It should have the pointer for the current position already so just a simple subtraction would probably do it.

**Comment by peterhinch** [comment]
I don't think so: `seek()` returns no value.

**Comment by robert-hh** [comment]
In my tests seek did (and the code is written that way). 

N.B.: I would not have posted that without trying.

**Comment by peterhinch** [comment]
Sorry, you're right. After further digging this seems to be a behaviour which changed at some point in Python's past.

**Comment by dpgeorge** [comment]
Since file objects have `tell()` it's nice to make `StringIO` and `BytesIO` to also have that method (to make them easier to use interchangeably).  It's also a very minor addition, so done in ed93778e004a2c6c2160f54d7362f14c5797d9c6
