### ISSUE TITLE
ESP32/urequests: Can't figure out how to provide a payload

### ISSUE THREAD

**Issue by mz3-andrey** [micropython/micropython#5589]
I've been trying to use urequests to send a post request to a webpage.
After printing the received $_POST arguments with the receiving PHP code, i found out that it isnt receiving any at all.

So far i've tried:
Using a dictionary file like requests -> Found out that it needs a string
Passing my dict through a ujson.dumps -> no exceptions raised but no post arguments received on the other end.
Doing ujson.dumps(xxx).encode('utf8') -> same story
Can anyone give me a hint please?
Thanks!

**Comment by dpgeorge** [comment]
This is a good question for https://forum.micropython.org

But, you should be able to do it either with `urequests.post(url, data=b'1234')` or `urequests.post(url, json=[1, 2, 3])`.
