### ISSUE TITLE
BLE Server for ESP32

### ISSUE THREAD

**Issue by francescofact** [micropython/micropython#5600]
Hi. 
i just started with micropython. but i can't get a BLE server working on my ESP32 with micropython.
I want to connect to my esp32 via my phone with an app like "BLE IO".
I'm using ubluetooth and this is my code:

```
import bluetooth
bt = bluetooth.BLE()
bt.active(True)
bt.gap_advertise(1000)
```

but this goes into "OSError: [Errno 5] EIO". I can't understand how to do it.

i also tried to copy the example "bt_advertising", but if i edit the demo() as this:
```
def demo():
    payload = advertising_payload(name='micropython', services=[bluetooth.UUID(0x181A), bluetooth.UUID('6E400001-B5A3-F393-E0A9-E50E24DCCA9E')])
    print(payload)
    print(decode_name(payload))
    print(decode_services(payload))
    
    bt = bluetooth.BLE()
    bt.active(True)
    bt.gap_advertise(1000, adv_data=payload)
```

it always give me errorno 5

**Comment by dpgeorge** [comment]
This question is better suited to https://forum.micropython.org

In short: BLE has concepts of "central" and "peripheral", but not "server".  Examples of both are provided in `examples/bluetooth/`, `ble_temperature_central.py` and `ble_temperature.py`.

**Comment by dhalbert** [comment]
@dpgeorge I am going to be pedantic, sorry. BLE does have client and server, which are orthogonal to central and peripheral. All four terms are "official". A server provides a service; a client talks to a server, accessing its characteristics. Once a client and a peripheral connect, either one can be a server to the other.

**Comment by dpgeorge** [comment]
@dhalbert yes, of course, you are right!  I was being too simplistic and just thinking of the peripheral/central/observer/broadcaster roles, forgetting about things like GATT server/client.  Yes it's complex.
