### ISSUE TITLE
dict functions are missing from dynruntime.h

### ISSUE THREAD

**Issue by jeremyherbert** [micropython/micropython#5609]
In `dynruntime.h`, `mp_obj_new_dict` and `mp_obj_dict_store` are not defined, whereas `mp_obj_new_list` and `mp_obj_list_append` are. Was this deliberate or an oversight?

**Comment by dpgeorge** [comment]
It was mostly API functions that were needed by the examples in `examples/natmod` that were initially added.  There's no problem at all to add more API functions.

**Comment by jeremyherbert** [comment]
Ok, I will add and PR soon.

**Comment by dpgeorge** [comment]
Dict functions were added in 148d12252b54d330c66ccac4bbbe6d804a8d1e8f
