### ISSUE TITLE
SPI slave bug on SF2W

### ISSUE THREAD

**Issue by thenniges** [micropython/micropython#5616]
I am using a SF2W in slave mode. It works most of the time, but has this issue occasionally. This issue makes it impossible for me to use it as a test tool as desired.

It will send most bytes accurately, but it will occasionally(~3/1260) send incorrect bits. When it messes up, it will send bits in this pattern: a correct bit, another correct bit, then the bit that it sent before the last. For example, if you were sending 0b12345678, it might send 0b12345657.

I have updated the firmware and have looked at it with a logic analyzer and the problem still persists. I am also sure that it is not a problem with my code because the problem is intermittent and I have printed what I am sending through SPI and it matches what is expected, even when the send fails.

**Comment by mattytrentini** [comment]
This issue has become stale and we'll close it; the short response is that SPI Slave mode isn't implemented in MicroPython. Please reopen this ticket if there's additional information.
