### ISSUE TITLE
Is CAN FD fully supported on STM Nucleo H743 ?

### ISSUE THREAD

**Issue by skpang** [micropython/micropython#5621]
I have a  STM Nucleo H743 board and would like to try out CAN FD.
Looking at the fdcan.c and can.c I can see where the Nominal bitrate is set but I can't see where the Data bitrate is set.

Also in pyb_can.c the tx_msg.BitRateSwitch flag seems to be hard coded to off and tx_msg.FDFormat is set to classic CAN.

So is CAN FD fully support ?

**Comment by suzonch** [comment]
Found out the solution? Any way to enable CAN FD on that board? I have the same board.

**Comment by dpgeorge** [comment]
Fixed by ff287d085f95ab0ca3fdf67ee9d8cce6f046b01e
