### ISSUE TITLE
OSError: [Errno 19] ENODEV

### ISSUE THREAD

**Issue by bam2619** [micropython/micropython#5663]
Here is my code: 
[data2.zip](https://github.com/micropython/micropython/files/4222913/data2.zip)

This is the error I receive, the line numbers change though each time I run it. I have gotten it to output numbers before giving an error (anywhere from 1 to 10)
Traceback (most recent call last):
  File "<stdin>", line 17, in <module>
  File "<stdin>", line 14, in depth
  File "ms5803.py", line 70, in read
OSError: [Errno 19] ENODEV

**Comment by jimmo** [comment]
Hi,

This might be better discussed on the forum -- https://forum.micropython.org/  Please post there, and you can paste your code inline using the `[code]` `[/code]` blocks. (Also include more information about how things are wired up and which board/port you're using).

I'm guessing though that this is an I2C device and it's not responding to the address the driver expects. Try doing an I2C scan and see if the device appears. If not, maybe check the pull-up resistors on SDA/SCL.
