### ISSUE TITLE
bytes builtin doesn't accept encoding kwarg

### ISSUE THREAD

**Issue by lurch** [micropython/micropython#567]
Dunno if this is a known problem or has been reported before, but searching for 'bytes' obviously throws up a hell of a lot of matches! ;)

On CPython, I can do both `bytes('hello', 'ascii')` and `bytes('hello', encoding='ascii')`.
On uPy, the former works, but the latter fails with
`TypeError: wrong number of arguments`

I also just spotted that on CPython both `str(b'hello', 'ascii')` and `str(b'hello', encoding='ascii')` produce the same result, but on uPy the second version returns something quite different. (let me know if I should split that off into a separate issue)

**Comment by dpgeorge** [comment]
As mentioned above, `bytes('aoeu', encoding='ascii')` will now raise a `NotImplementedError`.  And since there's been no further need/interest/request to support these keyword args I'm going to close this issue.

**Comment by geekguy-wy** [comment]
I have an interest in this because I need the bytes() function which is used in my pack() routines to get a packet ready to send over RFM69 radio.

**Comment by peterhinch** [comment]
You can write
```python
bytes('abcd','ascii')
```
You need to pass the encoding as a positional arg, rather than as a keyword arg.
