### ISSUE TITLE
Memoryview comparison not working correctly anymore

### ISSUE THREAD

**Issue by kevinkk525** [micropython/micropython#5674]
In an older release this worked:

```
>>> memoryview(b"hi")==b"hi"
True
```

Now it doesn't:

```
>>> memoryview(b"hi")==b"hi"
False
```

This causes all kinds of problems in my code, obviously.
My guess is that this is caused by the commit about equality comparison (can't find it right now but read it today before pulling the latest changes)

**Comment by peterhinch** [comment]
Nasty. It works in CPython. A search on **is:pr equality** throws up several possible candidates.

**Comment by dpgeorge** [comment]
Thanks for the report.  IMO it's good to have all these issues exposed, it means the test suite was not testing things which were important and used in real code.
