### ISSUE TITLE
Upip does not recognise connection errror and throw index error

### ISSUE THREAD

**Issue by haixuanTao** [micropython/micropython#5685]
Hey there,

Just want to log a problem that took a bit of time to solve for me although it is pretty simple when you think about it. 

But if you're not connected, upip.install will throw the error:
``` 
Error installing 'your_module': list index out of range, packages may be partially installed
```
A better error would be:

```
Error connection failed
```

I tried to find a way to contribute but I'm really new to the package.

If you want I can look deeper to implement the change.

**Comment by jonnor** [comment]
upip has been replaced by mip in MicroPython 1.20, https://github.com/micropython/micropython/releases/tag/v1.20.0
Closing as no longer relevant.
