### ISSUE TITLE
exec bytearray CPython inconsistency

### ISSUE THREAD

**Issue by Bockwuhrst** [micropython/micropython#5704]
Just found a minor CPython inconsistency with the way exec works.

On micropython:
`exec('print(1)')  # prints 1` 
`exec(b'print(1)')  # prints 1` 
`exec(bytearray(b'print(1)'))  # raises TypeError: can't convert 'bytearray' object to str implicitly`

On CPython all versions work.

**Comment by dpgeorge** [comment]
Thanks for the report.  I've created #5709 with a simple fix for this.

**Comment by dpgeorge** [comment]
Fixed by 1993c8cf9af930cd6ff2f28390ac3a8a09d5b297
