### ISSUE TITLE
ESP32 BLE gap_advertise() param cause exception

### ISSUE THREAD

**Issue by Walkline80** [micropython/micropython#5722]
According to [BLE.gap_advertise()](http://docs.micropython.org/en/latest/library/ubluetooth.html?highlight=bluetooth#ubluetooth.BLE.gap_advertise), I'm setting up the param 'connectable' to False, then it will cause exception:

```python
import ubluetooth as bt
from ble_advertising import beacon_advertising_payload

class Beacon(object):
    def __init__(self, ble):
        self.__ble = ble

        self.__ble.active(False)
        print("activating ble...")
        self.__ble.active(True)
        print("ble activated")

        self.__adv_payload = beacon_advertising_payload("https://walkline.wang")

    def advertise(self, interval_us=50000):
        print("advertising...")
        self.__ble.gap_advertise(interval_us, adv_data=self.__adv_payload, connectable=False)


def main():
    ble = bt.BLE()
    beacon = Beacon(ble)

    beacon.advertise()
```

```docs
activating ble...
I (21110) BTDM_INIT: BT controller compile version [5aed448]
I (42562) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (42662) phy: phy_version: 4102, 2fa7a43, Jul 15 2019, 13:06:06, 0, 0
GAP procedure initiated: stop advertising.
ble activated
advertising...
GAP procedure initiated: advertise; disc_mode=2 adv_channel_map=7 own_addr_type=0 adv_filter_policy=0 adv_itvl_min=80 adv_itvl_max=80
GAP procedure initiated: advertise; disc_mode=2 adv_channel_map=7 own_addr_type=2 adv_filter_policy=0 adv_itvl_min=80 adv_itvl_max=80
Traceback (most recent call last):
  File "<stdin>", line 64, in <module>
  File "<stdin>", line 60, in main
  File "<stdin>", line 53, in advertise
OSError: [Errno 5] EIO
```
According to the system information prompt, it looks like the advertise function was executed twice automatically, but why?

**Comment by dpgeorge** [comment]
Can you provide the exact value of `self.__adv_payload` that is being used as the advertising data?

**Comment by dpgeorge** [comment]
> ```python
> interval_us=50000
> ```

It looks like this is the problem: with BLE controllers < BLE 5.0 the minimum interval is 100ms.  So try passing 100000 to this value.

**Comment by Walkline80** [comment]
> It looks like this is the problem: with BLE controllers < BLE 5.0 the minimum interval is 100ms. So try passing 100000 to this value.

@dpgeorge , that's the real problem I have made, thanks a lot~

However, the '50000' problem in my another ble_hid project, it doesn't cause any exception with default value of 'connectable', I'm just curious why this is happening?

**Comment by dpgeorge** [comment]
> However, the '50000' problem in my another ble_hid project, it doesn't cause any exception with default value of 'connectable', I'm just curious why this is happening?

For connectable devices the minimum is 20ms (I think).  I guess the reason non-connectable advertising has a minimum of 100ms is to prevent flooding of the BLE radio spectrum by unconnectable but broadcasting beacons (and because connectable devices stop advertising once they have been connected to).

**Comment by Walkline80** [comment]
@dpgeorge thanks for your reply again~
