### ISSUE TITLE
Providing support for constants in Python code

### ISSUE THREAD

**Issue by pfalcon** [micropython/micropython#573]
I told there's optimization itch... (again, or finally). So, we discussed this already, and there's support for native modules already, so can we have:

```
from micropython import const

VAL = const(100)
```

After that, VAL is subject to constant propagation per existing compiler support. Initial implementation can do just intra-module propagation.

**Comment by dpgeorge** [comment]
Reviving this issue again to discuss how to make const properly compatible with CPython.

Currently uPy recognises `<id> = const(<expr>)` in the parser as a special pattern and then replaces all occurences of `<id>` with `<expr>`, as well as doing the actual assignment.  But if `<id>` starts with an underscore then no assignment is made to the global dict.

"const" is considered a builtin in uPy which makes it incompatible with CPython (without resorting to tricks).  It's also incompatibly with uPy itself for builds that don't have const optimisation enabled.

As suggested at the very top of this issue, the right way to do it is have `from micropython import const` at the start of the script.  Then at least one can provide a dummy implementation of const in micropython.py for CPython.  And for uPy builds that don't have const optimisation, the micropython module can include a const function that is the identity (returns its argument).

But note that the parser recognises "const" only, not something like "micropython.const", or any other name.

An alternative would be to implicitly make variables const if they are all upper case and start with a double underscore.

**Comment by peterhinch** [comment]
+1 for ``from micropython import const`` It's more transparent and Pythonic in my opinion.

**Comment by tannewt** [comment]
+1 for `from micropython import const` though I wonder if it would be better to split the optimizations and decorators for micropython from the `micropython` module which can be used for `mem_info()` and stuff too.

**Comment by pfalcon** [comment]
@dpgeorge : So, do you propose to just add dummy "const" symbol to micropython module, which is definitely ok, or something beyond that, like a) modify parser so that if "from micropython import const" wasn't done, "const" wasn't treat specially, or maybe b) modify parser even further, so e.g. const subst happened only on RHS (re: issues reported previously)?

**Comment by dpgeorge** [comment]
> though I wonder if it would be better to split the optimizations and decorators for micropython from the micropython module

I think it's fair to have just one uPy-language specific module (ie should be available in all uPy ports) for language features (like const, native, viper) as well as features tightly coupled to the core (eg mem_info, heap_lock, alloc_emg_exc_buf).

> So, do you propose to just add dummy "const" symbol to micropython module,

Yes, and it'll be pointing to the identity function, which already exists (mp_identity_obj).

> modify parser so that if "from micropython import const" wasn't done, "const" wasn't treat specially

I wouldn't do that at this point, but we could in the future if there was a need.

> modify parser even further, so e.g. const subst happened only on RHS (re: issues reported previously)

Substitutions that produce `obj.42` or `42 = x` are a bug and should probably be fixed anyway.

**Comment by dpgeorge** [comment]
`micropython.const` identity function was added in 791b65f4b261a23e427664f0b86ce32b60e33cb5.

**Comment by dpgeorge** [comment]
Const substitution bug (eg obj.42) was fixed in 6d310a5552f43b3f984a5d8020b41301ab7937a4.

**Comment by dpgeorge** [comment]
Main issues of this ticked have been addressed, there can be constants in Python code and there is support for having constants from external modules via `MICROPY_PORT_CONSTANTS`.
