### ISSUE TITLE
Dicts not yet supported for str.format().

### ISSUE THREAD

**Issue by pfalcon** [micropython/micropython#574]
Following snippets not yet supported:
~~~~
"%(foo)s" % {"foo": "bar"}
"{foo:}".format(**{"foo": "bar"})
~~~~

Note that this is submitted for documentation purposes, low enough priority, and can just collect votes to be implemented so far.

**Comment by pfalcon** [comment]
Can't believe I contribute to language fragmentation by implementing superfluous features, but `"{foo}".format(**{"foo": "bar"})` implemented in https://github.com/micropython/micropython/commit/c1144966417de643d86286dae3189e8c0e09d9c2 . Blame the existing broken code which uses those features. Don't use in real life.

**Comment by dpgeorge** [comment]
At least it's neat and relatively minimal.

I would like to add a compile option to select either % or {} string formatting, for space constrained builds.

**Comment by pfalcon** [comment]
> I would like to add a compile option to select either % or {} string formatting

Yes, I'd like that too.
