### ISSUE TITLE
Wrong part_num equals in stm32

### ISSUE THREAD

**Issue by thyrrestrup** [micropython/micropython#5753]
https://github.com/micropython/micropython/blob/baf8aa286af1af2ddf0179b82b3411d45f513b23/ports/stm32/main.c#L263

Should this line `== 3` instead

**Comment by dpgeorge** [comment]
Thanks for the report.  Indeed that looks like a bug.

**Comment by dpgeorge** [comment]
Fixed by eae495a7147983267371b09ea606977efa9111a5

(The fix was tested with a PYBv1.1 and an SD card with 4 partitions.)
