### ISSUE TITLE
Undocumented parameter of ussl.wrap_socket 

### ISSUE THREAD

**Issue by czAdamV** [micropython/micropython#5761]
The function `wrap_socket` from the `ussl` module accepts positional parameter `server_hostname`, but its behaviour is undocumented. I've run into this when debugging an issue with the `urlopen` function (using this parameter) from the `urllib.urequest` module of the micropython-lib project (micropython/micropython-lib#374). I suspect the behaviour I described in the original issue might be caused by a bug in micropython or an underlying library, but I'm not sure if I can post the issue here as the code causing it is using a parameter that technically shouldn't exist.

**Comment by jonnor** [comment]
Networking across different ports was made more similar in the last yesrs. This parameter is now documented, at https://docs.micropython.org/en/latest/library/ssl.html#ssl.SSLContext.wrap_socket
