### ISSUE TITLE
machine.soft_reset not available for esp8266

### ISSUE THREAD

**Issue by antariandel** [micropython/micropython#5764]
Hi all,

This is related to https://github.com/micropython/micropython/issues/2508
Is there a limitation because of which _soft_reset_ isn't implemented for the esp8266? I'd like to have the same behaviour from code, that Ctrl+D does.

Thanks for any info!

**Comment by dpgeorge** [comment]
> Is there a limitation because of which _soft_reset_ isn't implemented for the esp8266?

No, it would work the same as other ports, and would be good to add it for consistency.

Now implemented by 8d34344dceb367844b651deccadff2b55f20c55c
