### ISSUE TITLE
How can I fix this?

### ISSUE THREAD

**Issue by DavePlayz** [micropython/micropython#5792]
#Price Comparison Machine
#Working out price for item 1 and finding mass for it aswell.
#Price
C1 = int(input('Cost of first product: $'))
#Quantity
M1 = int(input('Mass of first product (In grams): '))
set(T1 = (C1 / M1))
#Working out price for item 2 and finding mass for it aswell.
#Price
C2 = int(input('Cost of second product: $'))
#Quantity
M2 = int(input('Mass of second product (In grams): '))
set(T2 = (C2 / M2))
#Getting the numbers to compare...
#Then...
#FINAL DECISION:
#Checks if product one is better value.
if (C1 / M1) < (C2 / M2):
  print('Item 1 has better value! By' + T1 + '$/g')
#Checks if product two is better value  
if (C2 / M2) < (C1 / M1):
  print('Item 2 has better value! By' + T2 + '$/g')
#Checks if they are the same  
elif (C1 / M1) == (C2 / M2):
  print('There is no best buy, buy whatever you want.')

But whenever the code is run the the setting of the variable has a problem.
TypeError: set() does not take keyword arguments
How do I fix that?

**Comment by stinos** [comment]
`set(T2 = (C2 / M2))` is not valid Python code in any Python version. Did you mean `T2 = C2 / M2` i.e. delcaring a variable?
