### ISSUE TITLE
code-format.sh doesn't fix spaces for C-style casts

### ISSUE THREAD

**Issue by stinos** [micropython/micropython#5802]
```
        float r =  (  float  )    0.0;
        float r =   (float )    0.0;
        float r =   ( float)    0.0;
```
gets formatted into
```
        float r = (  float  )    0.0;
        float r = (float )    0.0;
        float r = ( float)    0.0;
```

**Comment by stinos** [comment]
Here's another one:
```
(( mod < zero ) != (*y < zero ))
```
doesn't remove the space before mod and after zero.
So it's not the casting, it's the braces.

**Comment by dpgeorge** [comment]
See #5804 for a fix.  Didn't try the above examples but it should hopefully address them all.

**Comment by stinos** [comment]
That fixes the last one.
With these 2
```
# Add or remove space after C/D cast, i.e. 'cast(int)a' vs. 'cast(int) a' or
# '(int)a' vs. '(int) a'.
sp_after_cast                   = remove   # ignore/add/remove/force

# Add or remove spaces inside cast parentheses.
sp_inside_paren_cast            = remove   # ignore/add/remove/force
```
the casts are fixed for me as well (assuming we do not want a space after a cast)

**Comment by dpgeorge** [comment]
> With these 2 ... the casts are fixed for me as well (assuming we do not want a space after a cast)

Ok, added those extra options to #5804
