### ISSUE TITLE
qemu-arm test failure does not give useful output

### ISSUE THREAD

**Issue by dlech** [micropython/micropython#5812]
Apparently grep thinks the .out file is binary for some reason.

see: https://travis-ci.org/github/micropython/micropython/jobs/667540522#L900-L913

**Comment by dlech** [comment]
potential fix test pending https://travis-ci.org/github/micropython/micropython/jobs/667554548

**Comment by stinos** [comment]
Would be nice to have this fixed indeed, only way to figure out qemu-arm failures now is to build locally

**Comment by dpgeorge** [comment]
Easiest way would be to cat the entire console.log file, or just use `-a` to accept binary, and `-C` to print context.

**Comment by dlech** [comment]
I already have a fix in the PR I linked. I'll break it out to a separate PR.

**Comment by dpgeorge** [comment]
Fixed by 6c77d5c7cd1ddfd35fe5932e91c09881ac49d79b
