### ISSUE TITLE
something goes wrong when i want to run micropython on my own stm32 board

### ISSUE THREAD

**Issue by CCHLENG** [micropython/micropython#5827]
Hi !
For some reason, I can't use pyboard in my application. I need to make my own stm32 board to run micropython.
Now I'm trying to download the firmware to my board. The board I use has a STM32F407VGT6, same as [STM32F4DISC](https://www.st.com/en/evaluation-tools/stm32f4discovery.html).
So I try to download `STM32F4DISC-20200328-v1.12-310-g9418611c8.dfu` to the board with `DfuSeDemo` :
- set BOOT0 = 1, BOOT1 = 0
- power on
- download the dfu file with DfuSeDemo
- power off after download
- set BOOT0 = 0, BOOT1 = 0
but nothing happens when I power on. i did't see a new USB flash drive on my PC.

![image](https://user-images.githubusercontent.com/25116183/77822188-675e7f00-712b-11ea-9fe6-d0e584755490.png)

So what can i do? is there a guide to follow if i want to run micropython on my own board?

**Comment by CCHLENG** [comment]
same way works on F407ZGT6.. so strange

**Comment by dpgeorge** [comment]
This kind of problem is best suited to discuss at https://forum.micropython.org

Here is for bug reports and feature requests.
