### ISSUE TITLE
Where does the unix port look for boot.py and is there a command line option to change it?

### ISSUE THREAD

**Issue by spierepf** [micropython/micropython#5838]
I would like to use micropython's unix port as a means of testing my code without having to upload the code to my ESP32 each time.

I've noticed that the unix port has a much different library search path than my ESP32 so I've tried adding the following code to boot.py:

```
import sys

if 'linux' == sys.platform:
  sys.path.append("./lib")
```

However, I cannot figure out how to convince the micropython executable to actually load boot.py on startup.

**Comment by tve** [comment]
http://docs.micropython.org/en/latest/unix/quickref.html#environment-variables

Please use forum.micropython.org for questions. Github is for bugs. Thanks! ;-)
