### ISSUE TITLE
How to enable CAN bus support on NUCLEO_F091RC

### ISSUE THREAD

**Issue by CCHLENG** [micropython/micropython#5845]
Hi! 
I am using NUCLEO_F091RC, deu to its flash memory and SRAM, it may not perform some complex calculations.  But it provide many interfaces at a low cost.
It has: I2C、USARTs、SPI、CAN bus. Now i can use these interfaces with micropython except CAN bus. I have tried to build the firmware by adding following codes in `mpconfigboard.h` :
```
#define MICROPY_HW_ENABLE_CAN      (1)

#define MICROPY_HW_CAN1_TX (pin_PA11)
#define MICROPY_HW_CAN1_RX (pin_PA12)
```
But I meet some error when I build the firmware : (
I think I can't simply add some `#define` to enable the CAN bus on NUCLEO_F091RC.
Is there a way to change some files to enable the CAN bus?

**Comment by jimmo** [comment]
This was already raised in the forum -- let's continue the discussion there.
