### ISSUE TITLE
[CC3200] FTP Firmware update doesn't work

### ISSUE THREAD

**Issue by SciLor** [micropython/micropython#5846]
I tried to copy over a new bootloader via ftp to /flash/sys/mcuimg.bin. But no change is visible. 
The bootloader isn't updated at all.

I am using a toniebox as board.

**Comment by Sekilsgs2** [comment]
For me updating working good.
Bootloader not updating via ftp only factimg.bin - main application

**Comment by SciLor** [comment]
I see it depends on the filename. I will have to fix that, so I can replace any file I want to. Thx for the hint.

https://github.com/micropython/micropython/blob/bd5633778f8dce0d71578338926fc6500069429e/ports/cc3200/ftp/updater.c#L44
