### ISSUE TITLE
const expression does not support power operator **

### ISSUE THREAD

**Issue by dugres** [micropython/micropython#5865]
>>> a = const(2*8)
>>> b = const(2**8)
Traceback (most recent call last):
  File "<stdin>", line 1
SyntaxError: constant must be an integer

**Comment by jimmo** [comment]
`const()` can only work on either literal integers, or expressions that can be constant-folded to literal integers.

Constant folding supports the following operators: |, &, ^, <<, >>, +, -, %, //  (and unary +, -, ~). This isn't so much a bug (there's an explicit comment `// Can't fold @ or / or **` in the code that handles this), as maybe a limitation. I don't know the exact reason, but I would imagine that the additional code to ensure that it's a case that resulted in a small int was too costly (and given that shifting is supported probably wasn't deemed necessary).

So in your case you could use `const(1 << 8)` to achive the same thing.

**Comment by dpgeorge** [comment]
That is correct, power is not supported in const expressions.  It could be but it would cost extra code, and it's likely that `<<` is enough.

**Comment by dugres** [comment]
If it's the intended behavior, it's ok, The error message is miss leading though.

**Comment by dpgeorge** [comment]
> The error message is miss leading though.

It's currently "constant must be an integer", which might be slightly clearer if changed to "bad const expression".

**Comment by dugres** [comment]
I think that "unsupported const expression" might be even clearer.

**Comment by dpgeorge** [comment]
See #5891 for a PR that implements folding of power.

**Comment by dpgeorge** [comment]
> I think that "unsupported const expression" might be even clearer.

Yes it would, but also need to think about code size, and longer messages increase code size.  But here maybe it's worth a few extra bytes.

**Comment by dpgeorge** [comment]
Power operator is now supported in const expressions (see commit above).

**Comment by louis-riviere-xyz** [comment]
Very nice.
Improving consistency is a good thing.
👍
