### ISSUE TITLE
_thread lock.acquire() timeout not implement ?

### ISSUE THREAD

**Issue by water5** [micropython/micropython#5945]
I try:
`lock.acquire(1, 3)`

but the lock is acquired unconditionally, the timeout parameter not implement currently?

test environment: ESP32, MicroPython v1.12 on 2019-12-20

**Comment by jimmo** [comment]
> the timeout parameter not implement currently?

Not currently implemented.

from `modthread.c`:

```c
    if (n_args > 1) {
        wait = mp_obj_get_int(args[1]);
        // TODO support timeout arg
    }
```

**Comment by dpgeorge** [comment]
Closing as a duplicate of #3332.
