### ISSUE TITLE
type object has no attribute __doc__

### ISSUE THREAD

**Issue by wrobell** [micropython/micropython#601]
In Python 3.4, the following script works

```
from collections import namedtuple

T = namedtuple('T', 'a b')
T.__doc__ = 'Test'
```

When running with MicroPython I am getting the error

```
Traceback (most recent call last):
  File "t-doc.py", line 4, in <module>
AttributeError: 'type' object has no attribute '__doc__'
```

Funny enough, we probably expect all documentation to be removed by MicroPython, so `T.__doc__ = 'Test'` should probably do nothing?

**Comment by dpgeorge** [comment]
Writing to custom/unimplemented attributes in an object implemented in C (in this case a namedtuple) is not supported in MicroPython.
