### ISSUE TITLE
Timing of next release?

### ISSUE THREAD

**Issue by jonsmirl** [micropython/micropython#6017]
The current release (not master) of micropython is using the commit id of the ESP32 beta 4 SDK. At the time this release was made esp32 support had compile issues. Those issues were quickly fixed in micropython master, however the release tag is in front of those fixes. lv_micropython is only ported to releases of micropython so those build issues got ported into lv_micropython.
https://forum.littlevgl.com/t/esp32-micropython-build-errors-lots/1754

These issues can be fixed with a few edits, but a new micropython release would cure the problem by moving onto the released ESP32 4 SDK.

Note: if you install the ESP compiler using the ESPIDF3 method you won't encounter this. If you install the compiler using the new install script in ESPIDF4 you'll hit it.

**Comment by dpgeorge** [comment]
We don't have a scheduled release timeline (maybe we need one...) and because everything is done on the master branch it can be hard to coordinate working towards a release and adding new features (maybe that workflow needs to change...).

Regardless, there does need to be a new release sooner rather than later.  And I'd like it to be very soon.

**Comment by tve** [comment]
IMHO it would be nice to get the various TLS and non-blocking socket fixes which culminate in adding TLS to uasyncio into MP for the next release..

**Comment by embeddedt** [comment]
Is the `master` branch considered stable enough at any point in time to work off of? Perhaps `lv_micropython` should just use that instead.

(cc @amirgon)

**Comment by dpgeorge** [comment]
> Is the `master` branch considered stable enough at any point in time to work off of?

The master branch is the development branch, so at any given commit it may have new bugs or regressions.  But the tests are extensive and get very good coverage, and the CI covers a lot, so master is usually quite stable.

**Comment by jonnor** [comment]
There has been many releases since 2020! This issue can be closed
