### ISSUE TITLE
Add proper error handling in upip for wrong json files

### ISSUE THREAD

**Issue by deimi** [micropython/micropython#6025]
Line 197 in [upip.py](https://github.com/micropython/micropython/blob/ab4e197707cd456499d680091fdc9daeff18c62a/tools/upip.py#L197) contains an assert for checking the amount of elements in the release list entry.
If the json file contains more than one element for the "release" list entry, the assert will hit and upip stops with an empty error message.
```sh
$ micropython -m upip install --debug micropython-wifimanager
Installing to: /home/deimi/snap/micropython/80/.micropython/lib/
Queue: ['micropython-wifimanager']
https://micropython.org/pi/micropython-wifimanager/json
Warning: micropython.org SSL certificate is not validated
https://pypi.org/pypi/micropython-wifimanager/json
Error installing 'micropython-wifimanager': , packages may be partially installed
```
Those kind of wrong json files can occur in pypi. See https://github.com/mitchins/micropython-wifimanager/issues/4

So in the name of easier error investigation, I suggest to replace the assert with a proper exception.

**Comment by jonnor** [comment]
Hi and thank you for reporting.

upip has been replaced by mip, a couple of releases ago. So this is no longer relevant.
