### ISSUE TITLE
Building NUCLEO_H743ZI in windows

### ISSUE THREAD

**Issue by infantasteff** [micropython/micropython#6031]
Hello,

I am currently trying to build micropython in windows 10 in atollic true studio ide for port NUCLEO_H743ZI. I got the following error. 

c:/program files (x86)/gnu tools arm embedded/9 2019-q4-major/bin/../lib/gcc/arm-none-eabi/9.2.1/thumb/v7e-m+dp/hard/libgcc.a
c:\Program Files (x86)\GNU Tools Arm Embedded\9 2019-q4-major\bin\arm-none-eabi-ld.exe: cannot find build-NUCLEO_H743ZI/lib/mbedtls/library/ssl_: No such file or directory
make: *** [Makefile:614: build-NUCLEO_H743ZI/firmware.elf] Error 1

**Comment by dpgeorge** [comment]
Did you update the submodules?  Try running `make submodules` in the `ports/stm32/` directory.

**Comment by infantasteff** [comment]
I updated the submodules again. Below is the list of submodules updated
make V=1 submodules
Updating submodules: lib/lwip lib/mbedtls lib/mynewt-nimble lib/stm32lib
git submodule update --init ../../lib/lwip ../../lib/mbedtls ../../lib/mynewt-nimble ../../lib/stm32lib

But still I receive the same error message

**Comment by dpgeorge** [comment]
Please copy here the full output of `make V=1`

**Comment by infantasteff** [comment]
I have attached the full output for make V=1
[micropython3.build.log](https://github.com/micropython/micropython/files/4620950/micropython3.build.log)

**Comment by stinos** [comment]
Command line length problem: the `srv` in `ssl_srv` starts at column 16385.
A bit strange, because the only limits I know of are around 260, 2048, 8192 and 32768 depending on how a command gets invoked. Don't think I've seen 16384 before, and I don't know which component is at fault here.

**Comment by stinos** [comment]
Workaround: change build directory to `b` instead of `build-NUCLEO_H743ZI`.

**Comment by infantasteff** [comment]
I am able to generate the binaries. 
Thank you very much
