### ISSUE TITLE
Error on nativeglue.h while trying to build new firmware

### ISSUE THREAD

**Issue by arlucio** [micropython/micropython#6032]
When I tried to make this file [Makefile](https://github.com/pulkin/micropython/blob/master/ports/gprs_a9/Makefile) to update micropython version of the related port.

In file included from ../../py/emitnx86.c:4:
../../py/nativeglue.h:138: error: expected ‘)’ before ‘->’ token
../../py/nativeglue.h:140: error: expected ‘;’ before ‘void’

Anyone knows what could it be? So I may to have a hint where to search for a solution.

**Comment by dlech** [comment]
Perhaps a macro is not properly defined? I think there is a compiler option to save the output of a file after running the preprocessor. That could be useful to debug the problem.

**Comment by dpgeorge** [comment]
It looks like it's because an entry in `mp_fun_table_t` is called `setjmp` and probably the toolchain redefines that symbol to something else.

A fix would be to rename that entry (line 138) from `setjmp` to `setjmp_`.

**Comment by arlucio** [comment]
Thanks for the quick response. After I renamed that entry the error disappeared.

I'm getting a new error now so I've opened a new issue at #6035.

**Comment by dpgeorge** [comment]
Fixed by 801f7dca78c2983a8ab96e79784d0b3c5cc9e7de
