### ISSUE TITLE
Memory leak for native machine code in mpy files

### ISSUE THREAD

**Issue by pmvr** [micropython/micropython#6045]
I noticed a memory leak in the usage of native mpy files.

Even for the simple example given in the [documentation](https://docs.micropython.org/en/latest/develop/natmod.html#natmod) the following code demonstrates the issue:

```
import factorial
from urandom import randint
import gc

for i in range(100000):
    c = factorial.factorial(randint(4, 15))
    print(gc.mem_free())
    print(i, c)

```

I tested this with
> MicroPython v1.12 on 2019-12-20; PYBD-SF2W with STM32F722IEK

on a Pyboad D-series.

**Comment by dpgeorge** [comment]
If you change `randint(4, 15)` to `randint(4, 12)` then the "memory leak" is not there.

What's happening is that for large factorials the value computed is too large to be stored in a small-int (which takes 0 heap memory) and instead a big-int is created (on the heap).  The function `mp_obj_new_int(...)` is doing the memory allocation in this case, for the large values.

And it's not a memory leak because a `gc.collect()` will reclaim it when the number is no longer referenced.

**Comment by pmvr** [comment]
Right, a `gc.collect()` reclaims the memory.

However, there still seems to be a difference:
The loop over `factorial.factorial(15)` lets the board run out of memory until it resets, the same loop over the simple python function `f(15)`
```
def f(n):
    r = 1
    for i in range(2, n+1):
        r *= i
    return r
```
lets the garbage collector release memory right before the board resets.

One further remark: `factorial.factorial(15)` in fact computes 15! % 2**32, because `factorial_helper` operates on `mp_int_t`, which is on STM32: `preprocessed.h:typedef int mp_int_t;` So, for a 31-bit integer, a big-int is created on the heap.

**Comment by pmvr** [comment]
Overall, I think, its clear enough right now. Thanks!

**Comment by dpgeorge** [comment]
> The loop over `factorial.factorial(15)` lets the board run out of memory until it resets,

Yes, I tested this and it does do a hard reset after a GC with the native code.

This is actually a bug: on stm32 the native code loaded from a .mpy file is not reachable by the GC because there is no pointer stored which points to the start of the native chunk of code.

**Comment by dpgeorge** [comment]
See #6061 for a proposed fix.

**Comment by pmvr** [comment]
Yes, I can confirm that the proposed fix lets the GC automatically release unused memory from the heap of a native mpy-module.
