### ISSUE TITLE
Need to implement proper __new__ handling for instance classes

### ISSUE THREAD

**Issue by pfalcon** [micropython/micropython#606]
Snippet from CPy stdlib urlparse.py:

```
class Quoter(collections.defaultdict):
    def __init__(self, safe):
        """safe: bytes object."""
        self.safe = _ALWAYS_SAFE.union(safe)

```

You see, it doesn't call `super().__init__()`. That's because it relies on `__new__` to initialize base class automatically. Specifically for CPy, collections.defaultdict is at all native type, and to emulate its behavior we need `__new__`.

Another testcase:

```
class Base:

    def __new__(cls):
        print("Base __new__")

class Sub(Base):
    pass


o = Sub()
```

**Comment by projectgus** [comment]
I'm going to close this as the case in the issue description works, as does the case of subclassing list. I'm honestly not sure if every permutation of inheritance works (or, more correctly, I'm sure it does not). However I think it's better tackled in a new issue with the specifics if/when someone comes across it.
