### ISSUE TITLE
os.chdir to non-existent path

### ISSUE THREAD

**Issue by jcw** [micropython/micropython#6069]
When doing `os.chdir('/blah')`, an ENODEV error is thrown, as expected.

But a subsequent `os.getcwd()` also throws this error, i.e. the directory was changed anyway.
I expected the working directory to remain as before.

My reason for trying this, is that `os.chdir('/sd'); import app` in `main.py` could be a convenient way to run application code when an SD card is present, while falling back to another file when not.

**Comment by peterhinch** [comment]
The Unix build works as expected, but I can confirm this on a Pyboard 1.0.

Re your problem, on a Pyboard **sys.path** changes depending on whether an SD card is present. If one is present it reads
`['', '/sd', '/sd/lib', '/flash', '/flash/lib']`
whereas in the absence it reads
`['', '/flash', '/flash/lib']`.
This means that if present an SD card is searched prior to flash. There are several options for using this behaviour to achieve your aim.

**Comment by robert-hh** [comment]
Which board are you using, which filesystem and which firmware version?

**Comment by jcw** [comment]
Aha, excellent, the path adjustment is indeed sufficient. Many thanks for pointing this out.
I'll leave this issue open for the "stuck in bad working dir" behaviour on PyBoard etc.

(I'm using `v1.12-464-gcae77daf0-dirty on 2020-05-23; MCUDEV STM32F407ZG` from @mcauser)

**Comment by dpgeorge** [comment]
Thanks for the report.  See #6085 for a fix.
