### ISSUE TITLE
Bytearray slice assignement throwing exception on ESP32 idf v4.

### ISSUE THREAD

**Issue by PureBasic** [micropython/micropython#6096]
Following the example in the documentation: 
https://docs.micropython.org/en/latest/genrst/builtin_types.html#bytearray
````
>>> b = bytearray(4)
>>> b[0:1] = [1, 2]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NotImplementedError: array/bytes required on right 
>>> print(b)
bytearray(b'\x00\x00\x00\x00')
````
I noticed that assigning `b'\x01\x02'` works.

**Comment by EddieParis** [comment]
I think you misread this doc. This is the intended behavior.  It works on CPython but not on micropython, hence the exception.

**Comment by PureBasic** [comment]
Indeed . Sorry for the noise.
