### ISSUE TITLE
STM32L496RE firmware for custom board

### ISSUE THREAD

**Issue by Maryem-arch** [micropython/micropython#6132]
Hello, 
I have a custom board that contains the **STM32L496RE microcontroller** I wanted to upload the micropython firmware into my board, first

- I created a folder named NEWBOARD for my board under _micropython/ports/stm32/boards_

- Copied into it the files used in the NUCLEO_L476RG (in folder NUCLEO_L476RG under _micropython/ports/stm32/boards_) since I have the Nucleo and it shares the same core with my custom board , and I changed the pins according to my custom board in the **mpconfigboard.h** under _micropython/ports/stm32/boards/NEWBOARD_ 

- Copied the ld file used for the Nucleo board **stm32l476xg.ld** found under _micropython/ports/stm32/boards_ and then I changed the memory addresses according to my board

- Changed the reference of the ld file **(line 4)** in the **mpconfigboard.mk** file located under _micropython/ports/stm32/boards/NEWBOARD_ 

- Changed line 52 in the Makefile located in _micropython/ports/stm32_ as follows:
**OPENOCD_CONFIG ?= boards/openocd_stm32l4.cfg**

Then, I ran `make BOARD=NEWBOARD` in  _micropython/ports/stm32_ 

The firmware was built and I tried to flash it into my board using `make BOARD=NEWBOARD deploy-openocd`  ,(I made sure the board was connected to the computer and it showed in the terminal) 

It didn't work so I tried it with `make BOARD=NEWBOARD deploy-stlink` , it said that the memory was successfully flashed but when I opened the serial connection using **picocom** , none of the micropython commands worked (Ex : `pyb.LED(2).on()` ) knowing that they worked fine when I flashed the **NUCLEO_L476RG**
I assumed the firmware didn't flash at all, so I moved the binary file (**firmware.bin** that was created in _micropython/ports/smt32/build-NEWBOARD_ after I built the board files) to Windows (knowing that I was using **Ubuntu**) and I flashed the board using **st-link Utility**, it worked apparently but it still didn't respond to any of the micropython commands, instead the LEDs mentioned in **mpconfigboard.h** kept blinking without any command from me, they start blinking whenever I power on the board, knowing that when I only put one pin in the mpconfigboard.h , only the LED mentioned will blink, when I put two, they both blink.

I couldn't know the reason behind the blinking, and I couldn't figure out why the firmware that I configured didn't work properly on my board.
I would appreciate it if someone could give me further explanation about how this firmware works or why am I having this issue.

- Also, are there any more configurations or files that I should modify to have a working firmware for my custom board ?

Thank you very much

**Comment by dpgeorge** [comment]
This question is better suited to https://forum.micropython.org

The best way to approach such issues is using a debugger (eg arm-none-eabi-gdb).  Also, since you have a known working board (the nucleo) work out exactly the differences between that and your board.  Probably it is to do with the amount of flash, the nucleo with an RG has 1Mbyte and your is an RE with 512kbyte.  This will affect the filesystem layout.
