### ISSUE TITLE
Mention the PyFlasher application in the "Deploying the firmware" sections

### ISSUE THREAD

**Issue by marcelstoer** [micropython/micropython#6137]
I am the author of and main contributor to https://github.com/marcelstoer/nodemcu-pyflasher/. The PyFlasher is a single-purpose GUI application around esptool that, with the help of PyInstaller, comes as a self-contained executable for Windows and Mac. It has been downloaded over 160k times in the last 3.5y.

![](https://raw.githubusercontent.com/marcelstoer/nodemcu-pyflasher/master/images/gui.png)

When I received a thank-you email by a guy who, thanks to PyFlasher, managed to install MicroPython onto an ESP8266 I went looking what you project's documented/recommended flashing options are.

Is there any interest in a PR that would list the PyPlasher as an alternative to plain `esptool` in the following two files?

http://docs.micropython.org/en/latest/esp32/tutorial/intro.html#deploying-the-firmware
http://docs.micropython.org/en/latest/esp8266/tutorial/intro.html#deploying-the-firmware

**Comment by jonnor** [comment]
The docs currently say

> Currently we only support esptool.py to copy across the firmware

esptool.py is the official from EspressIf. While your tool looks nice, we do not have the capacity to support helping people with using different tools. So I do not think we should link to anything else in the documentation. People will find alternatives online or via their IDE, if they do not like command-line :)
