### ISSUE TITLE
bluetooth advanced apis

### ISSUE THREAD

**Issue by TimonPeng** [micropython/micropython#6141]
if you want to read some device information, you must do connect first.

but in arduino, you don't need to do this, bt_irq callback better provided an object?

```C++
BLEDevice::init("");
BLEDevice::setPower(ESP_PWR_LVL_P7);
BLEScan *bleScan = BLEDevice::getScan();

bleScan->setAdvertisedDeviceCallbacks(new ScanDeviceCallback());
bleScan->setActiveScan(true);
bleScan->setInterval(100);
bleScan->setWindow(99);

BLEScanResults foundDevices = bleScan->start(scanTimeout, false);

int count = foundDevices.getCount();
for (int i = 0; i < count; i++)
{
    BLEAdvertisedDevice device = foundDevices.getDevice(i);

    String name = device.getName().c_str();
    bool uuidExist = device.haveServiceUUID();
    bool nameExist = device.haveName();
}
```

**Comment by Walkline80** [comment]
BLE broadcasting payload may include the UUID and/or device name and other information, MicroPython can read these without connect first, if you want to discover services, characteristics and descriptors then you have to connect to the device first no matter what firmware you used


兄弟，你提供的这段代码不是也只能获取uuid和设备名称吗？这些只是ble设备广播的信息

**Comment by jimmo** [comment]
Yes, it's important to clarify the distinction between the advertising payload and scan response (available to any scanner) and the GATT characteristic/descriptor data (only available after a connection).

Some GATT services allow their data to be included in the advertising payload (via 0x16 "Service Data), but this isn't as common and relatively poorly documented.

@TimonPeng if you haven't seen https://github.com/micropython/micropython/blob/master/examples/bluetooth/ble_advertising.py it provides some helpers for working with BLE advertising payloads.

**Comment by TimonPeng** [comment]
@jimmo learned! thx!
