### ISSUE TITLE
Docs: Update statement regarding u-name/non-u-name modules

### ISSUE THREAD

**Issue by schneider42** [micropython/micropython#6150]
Currently the docs state:

> On some embedded platforms, where it may be cumbersome to add Python-level
> wrapper modules to achieve naming compatibility with CPython, micro-modules
> are available both by their u-name, and also by their non-u-name.  The
> non-u-name can be overridden by a file of that name in your library path (``sys.path``).
> For example, ``import json`` will first search for a file ``json.py`` (or package
> directory ``json``) and load that module if it is found.  If nothing is found,
> it will fallback to loading the built-in ``ujson`` module.

Since MicroPython 1.12 the Unix and Windows ports also implement weak aliases. Documentation should be updated accordingly. I'm not too deep into the matter so my proposal is:

> On some platforms micro-modules
> are available both by their u-name, and also by their non-u-name.  The
> non-u-name can be overridden by a file of that name in your library path (``sys.path``).
> For example, ``import json`` will first search for a file ``json.py`` (or package
> directory ``json``) and load that module if it is found.  If nothing is found,
> it will fallback to loading the built-in ``ujson`` module.

I'm also wondering what the logic behind enabling / disabling this feature is:
 - Ports which enable it: zephyr, stm32, nrf, esp8266, windows, esp32, cc3200, unix, javascript
 - Ports which disable it: bare-arm, minimal, pic16bit, powerpc, qemu-arm, samd, teensy      

I can understand that the minimal target might not want to enable it, but why would for example the Teensy 3.1 disable it?

**Comment by jonnor** [comment]
Is this still an issue, or can it be closed? I believe there has been considerable changes here over the last 4 years.
