### ISSUE TITLE
extmod/uasyncio No StreamReader.readexactly method

### ISSUE THREAD

**Issue by peterhinch** [micropython/micropython#6156]
This method [was supported](https://github.com/micropython/micropython-lib/blob/b89114c8345e15d360c3707493450805c114bc8c/uasyncio/uasyncio/__init__.py#L113) in uasyncio V2.0.

**Comment by dpgeorge** [comment]
Yes, this should be added.

**Comment by dpgeorge** [comment]
See #6285 for an implementation of this.

**Comment by dpgeorge** [comment]
Implemented in 441460d81ff2b1faee7d044d859896f754361b93
