### ISSUE TITLE
py: semi-colon missing in big-endian mp_float_union_t

### ISSUE THREAD

**Issue by NoePeterlongo** [micropython/micropython#6161]
https://github.com/micropython/micropython/blob/cba3e25cb33007e4c0b1a0c476ecce7166fb089f/py/misc.h#L250
semi-colon missing if I'm not mistaken

**Comment by dpgeorge** [comment]
Thanks for the report!  To prevent this in the future would be good to have a CI build for big-endian machine.  Maybe a qemu-arm board...

**Comment by dpgeorge** [comment]
See #6163 for a fix.

**Comment by brettcannon** [comment]
I think this issue can be closed.
