### ISSUE TITLE
machine.SDCard freq-argument not recognized?

### ISSUE THREAD

**Issue by siochs** [micropython/micropython#6162]
The [documentation](https://docs.micropython.org/en/latest/library/machine.SDCard.html#machine.SDCard) states:
`classmachine.SDCard(slot=1, width=1, cd=None, wp=None, sck=None, miso=None, mosi=None, cs=None, freq=20000000)`

Now, what am I doing wrong?

```
>>> import machine, uos
>>> machine.SDCard(slot=2, width=1, freq=20000000)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
TypeError: extra keyword arguments given

>>> machine.SDCard(slot=2, width=1, cd=None, wp=None, sck=None, miso=None, mosi=None, cs=None, freq=20000000)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
TypeError: extra keyword arguments given

>>> machine.SDCard(2, 1, None, None, None, None, None, None, 20000000)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: extra positional arguments given
>>> machine.SDCard(2, 1, 10000000)
```
Where can I find the class definition?

Platform: ESP32 generic: esp32-idf3-20191220-v1.12.bin

**Comment by siochs** [comment]
Oh, it seems that the freq-arguments only works with the lastest unstable betas. Maybe that should be noted somewhere in the docs.

**Comment by dpgeorge** [comment]
> it seems that the freq-arguments only works with the lastest unstable betas. Maybe that should be noted somewhere in the docs.

That's right.  What the docs need is a banner at the top to note development version, rather than stable version.

**Comment by siochs** [comment]
Good for me. Issue can be closed. Thank you guys.
