### ISSUE TITLE
Can I add modules processed by TI MSP432E401Y

### ISSUE THREAD

**Issue by ZhaoSQ-CH** [micropython/micropython#6210]
On the existing processors based on MicroPython, it is difficult to expand the TI processor. At this stage, only the basic part is completed. The company has no longer invested in research and development here because of its love for open source projects and the need to improve its own capabilities. So in the next step of the planning time, I would like to ask if you can increase TI's processor?

**Comment by jonnor** [comment]
There is no MSP432 port in mainline MicroPython. There seem to have been a little bit of work back in 2017, but it seems to have stalled. https://forum.micropython.org/viewtopic.php?f=12&t=1823&sid=b44416d6db8948ea9fa3c82ea59f7d7d&start=20

Unless someone has or starts working actively to maintain a port, I do not see it relevant to keep this issue open.
