### ISSUE TITLE
Out of date/invalid source linking for documentation of `PinAF`

### ISSUE THREAD

**Issue by hlovatt** [micropython/micropython#6213]
The file [pyb.html](https://docs.micropython.org/en/latest/library/pyb.html?highlight=pinaf) lists `PinAF` as a class within `pyb` (see list of classes at end of the linked page). 

Strangely, however, if you go to view page source, top right of page, then the linked [source](https://docs.micropython.org/en/latest/_sources/library/pyb.rst.txt) file doesn't mention `PinAF`.

Therefore the linked source isn't the 'real' source of the page! 

The two should be in sync.

**Comment by dpgeorge** [comment]
The html file is automatically generated from the rst.  And that "table of contents" (it's a `toctree` list) corresponds to all of the classes that Sphinx finds in the listed rst files.  So it is in sync, and any changes to this source file, or any of the rst files linked in this `toctree` will be reflected in the generated HTML.
