### ISSUE TITLE
[ESP32] Read from ADC2 Pins

### ISSUE THREAD

**Issue by jdjjm** [micropython/micropython#6219]
Is there any way of accessing ADC2 Pins? 
Even with WiFi off you cannot set up an ADC on any of the ADC2 Pins as you get the error
`ValueError: invalid Pin for ADC`

Looking at the esp32 port for [machine_adc.c](https://github.com/micropython/micropython/blob/master/ports/esp32/machine_adc.c) it seems only adc1 pins are supported. Is there any way to use ADC2?

**Comment by peterhinch** [comment]
Please raise this in [the forum](http://forum.micropython.org/index.php) rather than in the MicroPython bug tracker.

**Comment by jdjjm** [comment]
Okay thanks

**Comment by jdjjm** [comment]
Is there a reason [machine_adc](https://github.com/micropython/micropython/blob/master/ports/esp32/machine_adc.c) only exposes ADC 1? I understand most uses case will have WiFi running however there are times when this isn't the case so what is the reason for not having them accessible? It seems a little restrictive to me.

**Comment by WayneKeenan** [comment]
FYI: There is a workaround for getting ADC2 values whilst WiFi is running. 
Also, an Espressif dev said (albeit a long time ago) "There is a fix coming for ADC2 and WiFi soon :)"

Ref:  https://github.com/espressif/arduino-esp32/issues/102#issuecomment-331360699

**Comment by dpgeorge** [comment]
This is simply not implemented (mainly because with WiFi enabled it's not possible to use ADC2).  Also there's currently no standard way to select an ADC peripheral to use for a given pin, but in this case I think it could just automatically select ADC2 if a pin was given that only supported ADC on ADC2.

Summary: it can be implemented, feel free to make a PR for it.

**Comment by dpgeorge** [comment]
Support for ADC2 was implemented in 63438a31bb6d0c8012e338433df95700f1cbca97

**Comment by MauroDiamantino** [comment]
> Support for ADC2 was implemented in [63438a3](https://github.com/micropython/micropython/commit/63438a31bb6d0c8012e338433df95700f1cbca97)

But, do I have to disable Wifi to use it?

**Comment by dpgeorge** [comment]
> But, do I have to disable Wifi to use it?

I'm not sure, you'll need to read the ESP datasheet, or just try it out.
