### ISSUE TITLE
To support multiple inheritance, should filter out "object" from base class spec and handle it as implicit fallback

### ISSUE THREAD

**Issue by pfalcon** [micropython/micropython#624]
We're not going to get proper Python MRO any time soon (#525), but to at least not break multiple inheritance (MI) in obvious way, we should at least do following:
1. Filter out "object" from any explicit base class specification. (turn `class Foo(object)` into `class Foo`).
2. Look up attributes in "object" as a fallback.

This will emulate the fact that in Python3, "object" is always the last type in MRO.

Failing to do the above may mean, that with our naive depth-first MRO, "object" ultimate base of first superclass in MI case may seize method call destined to another superclass, if "object" has such method. With #520 & #606, object now implements `__new__` and `__init__`, so any other multi-superclass will be denied construction and initialization.

**Comment by dpgeorge** [comment]
Multiple inheritance works relatively well now.  And `object` has special handling to make it the last type.
