### ISSUE TITLE
Incorrect GC collect behavior for 32bit build?

### ISSUE THREAD

**Issue by stinos** [micropython/micropython#625]
It's not entirely clear to me how the gc is supposed to work (i.e. is it supposed to garbage collect *everything* that is not in scope anymore, or can it decide at will what to collect?) but in any case I'm watching different behavior for 32bit vs 64bit builds.

Given a module ```mod``` with a type ```SomeClass``` that has a finalizer and is allocated using ```m_new_obj_with_finaliser```, and prints it's address in ```__init__``` and ```__del__```, I used this script to test behavior:

````
import mod
import gc

def CollectMe() :
  x = mod.SomeClass()

CollectMe()
x = mod.SomeClass()
gc.collect()
````
Output on unix:
```
> make clean && make
...
> ./micropython test.py
__init__: 0xaa11c0
__init__: 0xaa11e0
__del__: 0xaa11c0

> make clean && make DEBUG=1
...
CC gccollect.c
gccollect.c: In function ‘gc_helper_get_regs’:
gccollect.c:63:1: error: bp cannot be used in asm here

> make clean && make MICROPY_FORCE_32BIT=1 MICROPY_MOD_FFI=0 MICROPY_USE_READLINE=0 
...
> ./micropython test.py
__init__: 0x83f50e0
__init__: 0x83f50f0

> make clean && make MICROPY_FORCE_32BIT=1 MICROPY_MOD_FFI=0 MICROPY_USE_READLINE=0 DEBUG=1
...
> ./micropython test.py
__init__: 0x87530e0
__init__: 0x87530f0
__del__: 0x87530e0
```

The 32bit non-debug build behaves different (and the 64bit debug doesn't build)
I also tried this for the windows msvc build (tried mingw, but it doesn't have __bss_start and _end)? The inline assembly syntax is different and I never used Intel assembly but afaik this could be the equivalent for 32bit - at least it does store the values of the registers properly in arr:

```
void gc_helper_get_regs(regs_t arr) {
    register long a1;
    register long a2;
    register long a3;
    register long a4;
    __asm {
        mov a1, ebx;
        mov a2, esi;
        mov a3, edi;
        mov a4, ebp;
    }
    arr[0] = a1;
    arr[1] = a2;
    arr[2] = a3;
    arr[3] = a4;
}
```

Here the output is again different, but this behaviour is definitely wrong as it collects variables still in scope:
```
__init__: 0026DB70
__init__: 0026C0C0
__del__: 0026DB70
__del__: 0026C0C0
```

**Comment by dpgeorge** [comment]
GC has been improved since this issue was last discussed, most notably the BSS is no longer scanned, but rather the root pointers are all collected in the one location in the global state structure.

Also relevant is a the bug fix for native codegen on unix/windows port in 2127e9a844ae46cb2149e7c38eb9f4345075f6e4.

Can this issue be closed?

**Comment by stinos** [comment]
Think so yes: I tried all samples posted here again with a couple of different builds/environments and everything is correct.

**Comment by dpgeorge** [comment]
Thanks, closing then.
