### ISSUE TITLE
Provide support for ESP32-S2?

### ISSUE THREAD

**Issue by tom2855** [micropython/micropython#6262]
I have a ESP32 board and I installed Micropython on it successfully.But when I tried to do it on my ESP32-S2 board,it gave me an error.It said I used the wrong chip.So would you like to provide support for ESP32-S2?It's a board from Espressif too.Looking forward to getting your response!Thanks a lot!

**Comment by sfranzyshen** [comment]
bump

**Comment by palmtreefrb** [comment]
bump

**Comment by dpgeorge** [comment]
See #6925.

**Comment by dpgeorge** [comment]
Support for esp32s2 was added in 66a86a061530eeee51191c3c667e9bc3cfcfda40
