### ISSUE TITLE
writing is not permitted when use ble_simple_peripheral demo

### ISSUE THREAD

**Issue by pzg250** [micropython/micropython#6295]
Hi,
I am trying to use  ble_simple_peripheral.py. But when I use mobile to connect to esp32. It can connect to esp32. But cannot write value. The tool shows "writing is not permitted"Any advise ?  ( I use nRF Connect.)

Regards,
Major

![image](https://user-images.githubusercontent.com/10494153/88744283-7b69ca00-d179-11ea-9b57-db17083d9122.png)

![image](https://user-images.githubusercontent.com/10494153/88744164-2928a900-d179-11ea-8529-cd01533ddbe0.png)

**Comment by jimmo** [comment]
You should be writing to the characteristic with UUID "6E400002-B5A3-F393-E0A9-E50E24DCCA9E" -- doesn't look like you're looking at the right service in nRF Connect.

**Comment by pzg250** [comment]
> You should be writing to the characteristic with UUID "6E400002-B5A3-F393-E0A9-E50E24DCCA9E" -- doesn't look like you're looking at the right service in nRF Connect.

Hi, thank you. 
Yes, but only UUID 2902 available.

**Comment by pzg250** [comment]
Hi @jimmo , could you indicate how to do next ? Maybe need to change the demo code ? or use some some special mobile app?

**Comment by pzg250** [comment]
Anyone can help? Or is there a doable demo ? Thanks in advance.

**Comment by pzg250** [comment]
use latest master version.
