### ISSUE TITLE
bytes() creates a new object for an existing bytes object

### ISSUE THREAD

**Issue by kevinjwalters** [micropython/micropython#6320]
MicroPython will create a new object for `bytes(var)` when var is of type `bytes`. This behaviour is different to three versions of CPython that I tried and given that it's an immutable type seems unnecessary and inefficient. Example on micro:bit:

```
MicroPython v1.9.2-34-gd64154c73 on 2017-09-01; micro:bit v1.0.1 with nRF51822
Type "help()" for more information.
>>> 
>>> a = b"Original"
>>> b = a
>>> c = bytes(a)
>>> type(a)
<class 'bytes'>
>>> a is b
True
>>> a is c
False
>>> id(a)
536871968
>>> id(b)
536871968
>>> id(c)
536871840
```

Discussed on [MicroPython Forum: bytes() makes a new copy of a bytes variable](https://forum.micropython.org/viewtopic.php?f=3&t=8849).

I noticed this originally on CircuitPython 5.3.0.

**Comment by dpgeorge** [comment]
Fixed by ca017841d65b5f9da5eb4e6e3ca66b009bc54fc4
