### ISSUE TITLE
Space savings in libm

### ISSUE THREAD

**Issue by dhalbert** [micropython/micropython#6326]
You may be interested in this:

@jepler found some significant space savings (608 bytes) in `libm` with a simple change to the `two_over_pi` constant array. See https://github.com/adafruit/circuitpython/commit/a3566ad055438a9a72ccc0d3ae3feae48e4cf702, part of https://github.com/adafruit/circuitpython/pull/3236.

We're also looking at an algorithm change: https://github.com/adafruit/circuitpython/pull/3245, but it causes a loss of precision, so we are not sure about including it yet.

**Comment by dpgeorge** [comment]
Thanks!  See #6398

**Comment by dpgeorge** [comment]
Done in 38959ed8f11970d47f4e07b720a590e65e80dc35
