### ISSUE TITLE
Ampy stops the running program in esp 32 micro python

### ISSUE THREAD

**Issue by notgounded** [micropython/micropython#6338]
Not able use ampy and run python program at the same time . When  I use any ampy command it gives an error could not enter raw repl or it executives ampy command and stops the running program . How to use ampy command while program is running in esp wroom 32? Is it possible to run program on one core and use repl from other core?
Thanks in advance

**Comment by davehylands** [comment]
This question is better suited to be asked on the forum https://forum.micropython.org/

github issues are for bugs.

I'm pretty sure that the answer to your question is no.

**Comment by notgounded** [comment]
Thankyou and is there a way to use  2nd core in esp wroom 32?
Should I close this issue?

**Comment by notgounded** [comment]
> This question is better suited to be asked on the forum https://forum.micropython.org/
> 
> github issues are for bugs.
> 
> I'm pretty sure that the answer to your question is no.

Thankyou and is there a way to use 2nd core in esp wroom 32?
Should I close this issue?

**Comment by dpgeorge** [comment]
> . How to use ampy command while program is running in esp wroom 32? Is it possible to run program on one core and use repl from other core?

It's not possible to do this because MicroPython (on esp32 at least) does not have the concept of multiple interpreters running at once (one for the REPL and one for the running program).

Instead you could implement your own REPL in Python as a separate thread.
