### ISSUE TITLE
uasyncio StreamReader.read(n) CPython incompatibility

### ISSUE THREAD

**Issue by peterhinch** [micropython/micropython#6355]
MicroPython requires a value `n` while the CPython method has a default value `n=-1`. See [the docs](https://docs.python.org/3/library/asyncio-stream.html):

> coroutine read(n=-1)
    Read up to n bytes. If n is not provided, or set to -1, read until EOF and return all read bytes.
    If EOF was received and the internal buffer is empty, return an empty bytes object.

Raised [by this user](https://github.com/peterhinch/micropython-async/issues/44).

**Comment by beyonlo** [comment]
@dpgeorge 

>Another option would be to query the underlying UART to see how much data is waiting in its buffer, and then explicitly read that many bytes, eg read(uart.any()).

Was this the logical above implemented in the PR #6358?

> A simpler alternative is to request a read of a large number of bytes, eg read(1000). That will return early if there are less than that many bytes to read so will effectively wait for the UART to have at least 1 byte then read everything that's immediately available.

Right. Just a question: is this fast? I mean, if read(1000) in uasyncio v3 will be fast as the .read() from uasyncio v2. I need to send/receive many frames per second over UART and I would like do not have delay in this process of the read(1000)

> When a socket is closed then it will have EOF once all bytes are read from it. UART doesn't have the concept of closed, at least not EOF closed.
> 
> (I added a test to the PR above which tests `read(-1)` on sockets and so tests this EOF-on-close behaviour.)

Right, and about the many socket applications (like my own) that do not closed the socket? In my application (same application that I use UART), I have a persistent socket connection, it never is closed.

Thank you so much.

**Comment by dpgeorge** [comment]
> > Another option would be to query the underlying UART to see how much data is waiting in its buffer, and then explicitly read that many bytes, eg read(uart.any()).
> 
> Was this the logical above implemented in the PR #6358?

No.  `read(-1)` is implemented as "keep reading, blocking, reading, blocking, reading" until the read hits EOF, and then return the concatenated result of all reads.  That's the CPython semantics of read-all.

> Right. Just a question: is this fast? I mean, if read(1000) in uasyncio v3 will be fast as the .read() from uasyncio v2.

Yes, it will do the same thing in both v2 and v3: wait for at least one byte to become available and then read and return all bytes that are immediately available with no further blocking, up to a maximum of 1000 (or whatever you pass as the argument).

> Right, and about the many socket applications (like my own) that do not closed the socket? In my application (same application that I use UART), I have a persistent socket connection, it never is closed.

They will behave the same as the UART: a read-all (as implemented in #6358) will wait forever because the EOF will never be hit.

It really depends what you are trying to do, as to the best way to do it.  It sounds like you want to "read all available data", in which case `read(1000000)` is what you want (or a suitable size, maybe 1000 is enough depending on the expected data coming in).

**Comment by beyonlo** [comment]
Hi @dpgeorge 

> No. `read(-1)` is implemented as "keep reading, blocking, reading, blocking, reading" until the read hits EOF, and then return the concatenated result of all reads. That's the CPython semantics of read-all.

All right. Understood. So please, just to clarify, will be available on the uasyncio v3 the .read() and the .read(-1), or both will execute the same logical explained above?


> Yes, it will do the same thing in both v2 and v3: wait for at least one byte to become available and then read and return all bytes that are immediately available with no further blocking, up to a maximum of 1000 (or whatever you pass as the argument).

All right.


> They will behave the same as the UART: a read-all (as implemented in #6358) will wait forever because the EOF will never be hit.

All right.

> It really depends what you are trying to do, as to the best way to do it. It sounds like you want to "read all available data", in which case `read(1000000)` is what you want (or a suitable size, maybe 1000 is enough depending on the expected data coming in).

All right. Understood. It's just JSON-RPC over a socket. So will works fine to me with .read(1000), like as in the UART scenario :) 

Thank you so much.

**Comment by peterhinch** [comment]
@beyonlo If your socket connection is over WiFi you may want to test the behaviour of your communications through WiFi outages. [This](https://github.com/peterhinch/micropython-samples/blob/master/resilient/README.md) is my take on this issue.

**Comment by dpgeorge** [comment]
Stream `read(-1)` was implemented in db7682e02d3ffd3338f20effc9ad4735a48bf774
