### ISSUE TITLE
Can't build teensy port for Teensy 3.5

### ISSUE THREAD

**Issue by mogplus88** [micropython/micropython#6363]
Hi All,
I want to use Micropython on my Teensy 3.5, but every time I try to do a "make deploy" I get a dialog box saying micropython.hex was built for Teensy 3.2 and my board is a Teensy 3.5. I have opened Arduino and set the board to Teensy 3.5 and uploaded a blinky program to it successfully, then closed Arduino and saved the file. If I open Arduino again the board is still set to Teensy 3.5. But when I try the make deploy again I get the same dialog. Can I force it to make for a Teensy 3.5? What else can I do to get it to work on my Teensy 3.5?
Thanks.

**Comment by mogplus88** [comment]
Hi @robert-hh , I didn't realise the post was so old. Too bad, Python on the Teensy would be great. I discovered this page as well, which seems to allow a specific build for the 3.5 (or 3.1 or 3.6).
https://github.com/micropython/micropython/wiki/Board-Teensy-3.1-3.5-3.6
I tried this one as well, and the first thing it complained about was that it didn't know where arduino was. Luckily the error message gave me a clue, I had to add ARDUINO=/opt/arduino-1.8.12 to the command. Then it worked but again gave me the dialog about being compiled for Teensy 3.2. It seems no matter what you specify, you get get 3.2 (like the model T Ford, you can have any colour you like as long as it's black)
The dhylands version appears to be only for Teensy 3.1. I couldn't find anything about teensy-rtc, where would I find that? Although as you say it is probably too old to be worth looking at.
There seems to be a lot of excitement around about Python on the Teensy 4.0 and 4.1. The 4.1 is the same form factor as the 3.5, but I haven't got one and they are quite expensive. (about $AUD65 locally). Also it appears to be 10 times as powerful as the 3.5, which is already using a sledge hammer to crack a peanut for my application. But what the heck...

;-)

**Comment by robert-hh** [comment]
> The dhylands version appears to be only for Teensy 3.1. I couldn't find anything about teensy-rtc, where would I find that? Although as you say it is probably too old to be worth looking at.

In the dhylans repository you have to checkout the teensy-rtc branch with:

`git checkout teensy-rtc`

Then you can build with the BOARD=... options for the models 3.5 and 3.6 using:

`make clean`
`make BOARD=TEENSY_3.5`

**Comment by jonnor** [comment]
The Teensy port has been removed, ref https://github.com/micropython/micropython/commit/e579ebb11b199ab04210fd8a82a3af5be6e4fdc5

**Comment by robert-hh** [comment]
Thar would have been a port for the Kinetis family. Might be possible since NXP's hardware libraries provides pretty similar API's for Kinetis and MIMXRT. But there is little demand for it.
