### ISSUE TITLE
(ESP32 uPython V1.12) List of List: Bad assignement

### ISSUE THREAD

**Issue by FranklinBerger** [micropython/micropython#6368]
Hello,
I have found that bug when dealing with lists. The problem is that when you try to creat a list from multiplications, they all become linked together. I have tried to explain the bug on the most simple way via the screenshot. Hope it will result on a bug fix or something like that.
I'm on a ESP32 with Micropython esp32-idf3-20191220-v1.12
Thank you for everything!

![BugReport_List_MicropythonV1 12_ESP32](https://user-images.githubusercontent.com/63146072/91046887-80575780-e619-11ea-9c42-94f7e6069709.png)

**Comment by jcw** [comment]
See https://www.tutorialspoint.com/How-does-repetition-operator-work-on-list-in-Python

Try `a = [[0] * 5 for _ in range(3)]`

**Comment by FranklinBerger** [comment]
Oh, don't expected that but it work, thank you verry much

**Comment by davehylands** [comment]
You get the same result using CPython, so it isn't actually a bug.

**Comment by FranklinBerger** [comment]
Yes, I saw that after,
A friend sent me that post on StackOverflow witch explain everthing:

https://stackoverflow.com/questions/12791501/python-initializing-a-list-of-lists

It just seems so stange that I didn't thought it would be a normal way of working for Python / uPython.
Thank you for you'r kind responses and sorry for this "trash-issue"
