### ISSUE TITLE
`bluetooth.FLAG_INDICATE` not assigned.

### ISSUE THREAD

**Issue by cyber-murmel** [micropython/micropython#6380]
I tried to run the `examples/bluetooth/ble_temperature.py` and it failed with
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ble_temperature.py", line 23, in <module>
AttributeError: 'module' object has no attribute 'FLAG_INDICATE'
```
`FLAG_INDICATE` is not defined
```python
>> bluetooth.
__class__       __name__        BLE             FLAG_NOTIFY
FLAG_READ       FLAG_WRITE      UUID
>>> bluetooth.FLAG_NOTIFY
16
>>> bluetooth.FLAG_READ
2
>>> bluetooth.FLAG_WRITE
8
```
According to the ESP-IDF[https://github.com/espressif/esp-idf/blob/dd8db6621b930a9cbfeef14a0d4daba8c8506e74/components/bt/host/bluedroid/api/include/api/esp_gatt_defs.h#L295] it needs to be `0x20`

**Comment by dpgeorge** [comment]
This constant was added in 9d823a5d9a6730edde8e1df1e5ff4add1ad17094 , so if you update to the latest version of the firmware then it should work.

Otherwise, just define it as 0x20 in the script.
