### ISSUE TITLE
【Bug】Servo Module for pyboard v1.1 with firmware v1.13

### ISSUE THREAD

**Issue by CaptainJackey** [micropython/micropython#6403]
http://docs.micropython.org/en/latest/library/pyb.Servo.html#pyb.Servo.speed

speed is the speed to change to, between -100 and 100,  Servo.speed(-100) to Servo.speed(-50) make no sense , but the firmware v1.11 is ok!

**Comment by dpgeorge** [comment]
Thanks for the report.  I can confirm the issue, and it should now be fixed by b31cb21a3936b97af4a52b082e1f40c2061aeab7
