### ISSUE TITLE
The const-type local variables visibility.

### ISSUE THREAD

**Issue by LDmicroGitHub** [micropython/micropython#6407]
MicroPython v1.13 on 2020-09-02; ESP32 module with ESP32

```python
from micropython import const

def test1():
    x = 1
    z1 = const(2)
    print("test1", "x=", x, "z1=", z1)
    
def test2():
    x = 3
    z2 = const(4)
    print("test2", "x=", x, "z2=", z2, "z1=", z1)

def test3():
    y = const(5) 

def test4():
#    y = const(6) # uncomment to catch error
    pass
    
test1()
test2()
```

%Run -c $EDITOR_CONTENT
test1 x= 1 z1= 2
test2 x= 3 z2= 4 z1= 2

**Why z1 is visible in test2? Is z1 global?**

**When uncomment line 18, we get a SyntaxError exception:**
Run -c $EDITOR_CONTENT
Traceback (most recent call last):
  File "<stdin>", line 18, in test4
SyntaxError: can't assign to expression

**Comment by robert-hh** [comment]
assignment with const can be seen as giving a number with a symbolic name. It is not a Pyhton type assignment, but more like a #define in c. The name which then represents the number is not a Python symbol, but just a literal. Is is effective at source file level throughout the file in which is is  define on all lines following that definition. And it is limited to integers or integer expressions.

P.S.: Questions like these are better raised in the forum.

**Comment by LDmicroGitHub** [comment]
Thanks
