### ISSUE TITLE
stable version 1.13 does not include uasyncio

### ISSUE THREAD

**Issue by sjev** [micropython/micropython#6410]
I've upgraded my esp8266 board from 1.12 to 1.13 (`esp8266-20200902-v1.13.bin` )
It looks like the `uasyncio` is missing from the build.
Upgrading further to an unstable `esp8266-20200903-unstable-v1.13.bin ` solves this.

**Comment by fitzterra** [comment]
Yes, I just noticed the same thing. Thanks @sjev for the heads-up on the unstable version solving the issue. I do not normally run unstable versions, but am not in the mood to build from scratch today :-)

**Comment by dpgeorge** [comment]
Thanks for the report.  Should now be fixed, I rebuilt the v1.13 release to include uasyncio.

See #6434 which aims to fix this properly in the future.
