### ISSUE TITLE
nrf52 DK Bluetooth Support in Micropython (Zephyr Port)

### ISSUE THREAD

**Issue by mridwang** [micropython/micropython#6414]
Hi , I am getting the following error while importing Bluetooth Module in NRF52 DK in REPL. Does Micropython supports BLE module? Please advise. 
>>> import bluetooth
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: no module named 'bluetooth'

Also it is not importing Network Module.

**Comment by robert-hh** [comment]
Did you look into the nrf examples at https://github.com/micropython/micropython/tree/master/ports/nrf/examples? They import a module with the name "ubluepy".

Besides that: questions like these are better asked in the forum at https://forum.micropython.org/
This place here is the bug tracker.

**Comment by mridwang** [comment]
> Did you look into the nrf examples at https://github.com/micropython/micropython/tree/master/ports/nrf/examples? They import a module with the name "ubluepy".
> 
> Besides that: questions like these are better asked in the forum at https://forum.micropython.org/
> This place here is the bug tracker.

Thanks. I have tried to import "ubluepy" getting the same error.

**Comment by MaureenHelm** [comment]
The Bluetooth module isn't supported in the Zephyr port yet.

**Comment by jonnor** [comment]
Since April 2021 there is a bluetooth module for Zephyr. So I believe this issue can be closed.
