### ISSUE TITLE
Wiolink support

### ISSUE THREAD

**Issue by prabindh** [micropython/micropython#6421]
Using the esp8266 image flashed, I am able to read the CONFIG PIN at pin 0.

However, the digital inputs for the board that are at GPIO 12,13,14 are not getting read.

Looking at the machine_pin.c of esp8266, it is not entirely clear if some setting needs to be changed specifically for wiolink board.

Please advise what needs to be changed, or if there is an already supported image for wiolink. (https://seeeddoc.github.io/Wio_Link/)

**Comment by robert-hh** [comment]
GPIO12, 13, 14 are full supported by the machine.pin module. You should able to read the value. e.g.;
```
from machine import Pin
p12=Pin(12, Pin.IN)
print(p12.value())
```
P.S.: Questions like these are better asked in the forum at https://forum.micropython.org. There is a large support community. The place here is the bug tracker.

**Comment by prabindh** [comment]
Thanks.
