### ISSUE TITLE
Option to set SPIRAM size

### ISSUE THREAD

**Issue by imkindaprogrammermyself** [micropython/micropython#6460]
Will there be an option to set the SPIRAM size on ESP32 boards? There are boards with 8MB PSRAM. I would really like to set the RAM size.

**Comment by pumelo** [comment]
I don't think it's easy to support more than 4MB of memory.

Citing from the esp-idf docs:
> However, because the address space for external memory is limited in size, only the first 4MiB can be used as such. Access to the remaining memory is still possible, however this needs to go through a bankswitching scheme controlled by the himem API.

https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/himem.html
