### ISSUE TITLE
round(0.5) returns 0

### ISSUE THREAD

**Issue by MaxUdk** [micropython/micropython#6481]
round(0.5) should return 1. please fix

**Comment by stinos** [comment]
> round(0.5) should return 1

Depends on whom you ask; the main 'rule' for MicroPython is implementing the Python standard, which dictates round(0.5) shall be 0, not 1.

**Comment by mcauser** [comment]
"Round half to even" eg.
```python
round(0.5) == 0
round(1.5) == 2
round(2.5) == 2
round(3.5) == 4
round(4.5) == 4
round(5.5) == 6
round(6.5) == 6
round(7.5) == 8
round(8.5) == 8
```
Even numbers round down. Odd round up.
