### ISSUE TITLE
Typo in documnetation

### ISSUE THREAD

**Issue by houneie** [micropython/micropython#6485]
I was going through [Distribution packages, package management, and deploying applications](https://docs.micropython.org/en/latest/reference/packages.html) and found a typo in step 5 
![image](https://user-images.githubusercontent.com/23403229/94230065-90b16980-ff1a-11ea-9136-4e44e5dd6fe7.png)

**Comment by dpgeorge** [comment]
Fixed by ee7568ca8d4f1a5d09a123cf5f7a1e430b8f4c9d
