### ISSUE TITLE
Version info reported on boot is incorrect

### ISSUE THREAD

**Issue by peterhinch** [micropython/micropython#6499]
Current daily build as listed on website:
PYBD-SF2-20200930-unstable-v1.13-77-g0fd0eb00a.dfu (latest)

Report on boot using firmware built from today's sources.
Unix:
MicroPython v1.12-778-g0fd0eb00a-dirty on 2020-09-30; linux version
Pyboard D SF6W:
MicroPython v1.12-778-g0fd0eb00a-dirty on 2020-09-30; PYBD-SF6W with STM32F767IIK

Pyboard D SF6W REPL:
```python
>>> os.uname()
(sysname='pyboard', nodename='pyboard', release='1.13.0', version='v1.12-778-g0fd0eb00a-dirty on 2020-09-30', machine='PYBD-SF6W with STM32F767IIK')
```

**Comment by dpgeorge** [comment]
Did you `git pull --tags`?  Making a fresh clone of this repo, I get:

**Comment by peterhinch** [comment]
Thank you - that fixed it I've updated my build script accordingly.
