### ISSUE TITLE
can i use STM32 Nucleo and Discovery boards as same as pyBoard V 1.0?

### ISSUE THREAD

**Issue by Irvingao** [micropython/micropython#6514]
Where can i find the spcific docs and the IO map of STM32 Nucleo and Discovery boards?

**Comment by rolandvs** [comment]
Www.st.com

**Comment by dpgeorge** [comment]
This question is best asked at https://forum.micropython.org

(For the board you're interested in, see the `ports/stm32/boards/<BOARD_DIR>/pins.csv` file.)
