### ISSUE TITLE
mpy cross do not support Chinese encode?

### ISSUE THREAD

**Issue by ub3132003** [micropython/micropython#6537]
ex. 
It's good work in .py file.
`"固件升级".encode('gbk')   >>>b'\xb9\xcc\xbc\xfe\xc9\xfd\xbc\xb6'`

bad work in .mpy file
`"固件升级".encode('gbk')   >>>b'\xe5\x9b\xba\xe4\xbb\xb6\xe5\x8d\x87\xe7\xba\xa7'`

**Comment by dpgeorge** [comment]
MicroPython doesn't support gbk encoding, only utf8 and ascii.  So I'm not sure how the first example above worked at all?

Written as `"固件升级".encode('utf8')` it gives the same result as a .py file and a .mpy file.

**Comment by jonnor** [comment]
UTF8 or ASCII must be used.
