### ISSUE TITLE
Using OpenSSL in user C module

### ISSUE THREAD

**Issue by janoist1** [micropython/micropython#6545]
I'm working on a C module that depends on OpenSSL. It tries to import the global SSL headers `#include <openssl/ssl.h>`. I noticed that ESP-IDF does contain OpenSSL among other components. Why can't I include it in my custom C modules? Target device is ESP32. Thanks.

**Comment by jimmo** [comment]
This might be better asked on the forum (https://forum.micropython.org). Please include more information about what's not working when you ask there. I suspect you'll require additional include paths and linker dependencies configured in your module's makefile to make this work.
