### ISSUE TITLE
Replace esp32 main.py via Bluetooth

### ISSUE THREAD

**Issue by bx5974** [micropython/micropython#6547]
Hi,

I want to replace the ESP32 main.py code from another Android app (where i will type the python code) dynamically via Bluetooth, so the new code must run as main.py 

Please help me how to do that. thanks.

**Comment by jimmo** [comment]
This might be better asked on the forum. https://forum.micropython.org/

In general though, you're going to need to define a service with a characteristic that can receive data (via repeated writes from the client on the phone). The MicroPython code can then buffer these writes and when complete (and verified), it can write out the new main.py to the filesystem (using the standard filesystem functionality).
