### ISSUE TITLE
make: *** [build-NUCLEO_F412ZG/firmware.elf] Error 1

### ISSUE THREAD

**Issue by Nil0375** [micropython/micropython#6554]
CC build-NUCLEO_F412ZG/pins_NUCLEO_F412ZG.c
LINK build-NUCLEO_F412ZG/firmware.elf
arm-none-eabi-ld: build-NUCLEO_F412ZG/dma.o: in function `dma_init':
dma.c:(.text.dma_init+0x82): undefined reference to `DMA_CalcBaseAndBitshift'
make: *** [build-NUCLEO_F412ZG/firmware.elf] Error 1

**Comment by dpgeorge** [comment]
It builds ok for me, and for CI.  You may need to `git submodule update` to get the latest `stm32lib`.
