### ISSUE TITLE
mp_vprintf incorrectly implements precision-modifier for strings

### ISSUE THREAD

**Issue by jeepee** [micropython/micropython#6562]
mp_vprintf treats the precision-modifier on a string to be the exact length to print.
This can cause out-of-bound reads on strings:

    mp_printf(print, "%.100s", "abc")

    abc^@<up to 100 bytes of garbage>

The precision-modifier should be treated as a maximum-length instead.

**Comment by dpgeorge** [comment]
Fixed by 5020b14d5419065f1a5ef5aed1be7badee28c9bf
