### ISSUE TITLE
Fatal Uasyncio/Uart Stream Lifecycle Bug (STM32)

### ISSUE THREAD

**Issue by gtomassi** [micropython/micropython#6576]
When calling aclose (maps to Stream.wait_closed) on the new implementation of Stream, something goes awry in the stream read process and begins raising exceptions. This will likely have a fatal impact on any projects using UARTs with any life cycle when migrating to uasyncio v3.

**After calling aclose the following stack trace is seen:**
```python
AssertionError:
  ...
  File "uasyncio/stream.py", line 30, in read
  File "uasyncio/core.py", line 94, in queue_read
  File "uasyncio/core.py", line 82, in _enqueue
```
It keeps repeating rapidly forever..

**Steps to reproduce:**

1. Open a UART connection using the stream reader 'streamReader = asyncio.StreamReader(uart)'
2. Listen to the stream reader using streamReader.read(n)
3. Close the stream reader
4. Not sure if this is required, but open a new stream reader on the same UART again

**Notes:**
- The read is not being "released" when closing the stream reader, and thus tries to continue to read on a closed stream reader. `yield IOReadDone(self.polls)` was in the v2 implementation and no equivalent operation exists in the v3.

**Comment by gtomassi** [comment]
After further investigation, the issue appears to be because the the uart object being passed into the stream reader always has the same unique object ID (id(uart)). So when the old read never releases (and hangs forever), and a new read is requested, the _enqueue operation already has a task waiting on that stream. Thus it throws an assertion error since there shouldn't be a task that already exists for that stream. 

This may actually be a bug in the uart code rather than the new uasyncio, if uart.deinit() does not properly release a read operation.

**Comment by dpgeorge** [comment]
I could not reproduce this problem.  I used the following code on a pyboard:
```python
import machine, uasyncio as asyncio

async def main():
    uart = machine.UART('XA', 9600)
    sr = asyncio.StreamReader(uart)
    sr.write('test')
    await sr.drain()
    print('read:', await sr.read(4))
    sr.close()
    await sr.wait_closed()
    
asyncio.run(main())
```
This raises an exception, but not as described above.  Instead it gives:
```
read: b'test'
Traceback (most recent call last):
  File "<stdin>", line 12, in <module>
  File "uasyncio/core.py", line 1, in run
  File "uasyncio/core.py", line 1, in run_until_complete
  File "uasyncio/core.py", line 1, in run_until_complete
  File "<stdin>", line 10, in main
  File "uasyncio/stream.py", line 1, in wait_closed
AttributeError: 'UART' object has no attribute 'close'
```

**Comment by gtomassi** [comment]
@dpgeorge 
Doesn't seem to happen for us anymore with the latest MP (1.15). So something must've changed, not sure what. Will continue to monitor and reopen if needed.

**Comment by dpgeorge** [comment]
Great, thanks for letting us know.
