### ISSUE TITLE
machine.memX does not support slices but should we let it crash?

### ISSUE THREAD

**Issue by Arrowana** [micropython/micropython#6588]
While developing we (team) observed that the following crashes the device:

```
import machine
some_address = 0x0800... # A valid memory address
machine.mem8[some_address:some_address+10]
```

This cause a crash since machine.mem8, mem16, mem32 do not support slices as noted in the comment. 
https://github.com/micropython/micropython/blob/ed7ddd4dd436fb84e602fee4dbdc4882eca642ab/extmod/machine_mem.c#L63-L65
The snippet above was initially in a greater amount of code, a crash is never good as it requires auditing things one by one to identify where it happens.

The crash can easily be prevented, or should slices be implemented instead?

**Comment by dpgeorge** [comment]
Fixed by 922f81dfd1b94e23f23f05aac0ecafac8645ce46
