### ISSUE TITLE
Nucleo F429ZI UART

### ISSUE THREAD

**Issue by micropyt** [micropython/micropython#6590]
I need to change uart pins in firmware. After rewrite in the mpconfigboard.h, rebuild the firmware and call the uart the response is uart 2 doesn't exist. What I have to change to it works?

Thanks for your responses.

**Comment by dpgeorge** [comment]
To get help on this, please post your changes to the `NUCLEO_F429ZI` board definition, and the REPL session that shows the error.

**Comment by micropyt** [comment]
Here are the posts. The first is the original settings of mpconfigboard.h.

![original](https://user-images.githubusercontent.com/73776149/98306990-2681ef00-1fc5-11eb-93fb-aaee908bfc2d.PNG)

changed
![changed](https://user-images.githubusercontent.com/73776149/98306996-2aae0c80-1fc5-11eb-9a48-30ca76bfeaa2.PNG)

the errors
![repl](https://user-images.githubusercontent.com/73776149/98307011-2e419380-1fc5-11eb-8397-79d8c71e427e.PNG)

**Comment by micropyt** [comment]
I need to run Modbus with this shield:

https://www.waveshare.com/wiki/RS485_CAN_Shield

**Comment by micropyt** [comment]
Is possible to use the Pin alternate function on stm32?

**Comment by davehylands** [comment]
Yes.

These types of questions are best asked on the [forum](https://forum.micropython.org/). github issues are for tracking bugs.

**Comment by micropyt** [comment]
Thanks, but I have to say, that it doesn't work probably.
UART does not work on the new pins.

**Comment by dpgeorge** [comment]
The issue is that PD8/PD2 do not have alternate functions for UART2.  And PD0/PD1 do not have alternate functions for UART4.  Same for the UART5 changes.  You must select pins that support the alternate function (only certain pins support certain UARTs).
