### ISSUE TITLE
Bin release version

### ISSUE THREAD

**Issue by bg4hkq** [micropython/micropython#6591]
Can you pub a compiled binary version? I have a problem compiling
thank's

**Comment by robert-hh** [comment]
Do you look for these? http://micropython.org/download/

**Comment by peterhinch** [comment]
@bg4hkq Two comments to add to the above. Firstly this is the MicroPython bug tracker. Support queries should be raised in [the forum](http://forum.micropython.org/index.php).
Secondly, your request is impossible to meet without knowing your system architecture.
