### ISSUE TITLE
.bss corruption with native modules on ESP32

### ISSUE THREAD

**Issue by jimmo** [micropython/micropython#6592]
Modify features1.c to change `uint16_t data16[4];` to `uint16_t data16[32];`.
Compile for xtensawin
Copy over features1.mpy and test.py containing:

```py
import gc
import features1

def demo():
    print(features1.access())
    features1.access()
    features1.access()
    gc.collect()

demo()
```

Import test then run test.demo() a few times. The list printed out by `features1.access()` should be all-zero but contains modified entries.

```
>>> import test
initialising module self=3ffe5440
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
>>> test.demo()
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
>>> test.demo()
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
>>> test.demo()
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 1, 0, 3, 0, 1, 0, 7, 0, 1, 0, 3, 0, 1, 0]
>>> test.demo()
[7, 0, 1, 0, 3, 0, 1, 0, 15, 0, 1, 0, 3, 0, 1, 0, 7, 0, 1, 0, 3, 0, 1, 0, 31, 0, 1, 0, 3, 0, 1, 0]
>>> test.demo()
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 1, 0, 3, 0, 1, 0, 31, 0, 1, 0, 3, 0, 1, 0]
>>> test.demo()
[7, 0, 1, 0, 3, 0, 1, 0, 15, 0, 1, 0, 3, 0, 1, 0, 7, 0, 1, 0, 3, 0, 1, 0, 31, 0, 1, 0, 3, 0, 1, 0]
```

This happens on both spiram and non-spiram builds. Making `data16` larger (or smaller) seems to make the issue go away?

**Comment by jimmo** [comment]
Originally reported at the forum: https://forum.micropython.org/viewtopic.php?f=3&t=9243&p=52062

**Comment by dpgeorge** [comment]
Thanks for reporting.  This is most likely the same issue as #6045 : the top-level function object for a module (which executes the module's outer scope) usually has nothing pointing to it after it has executed, so can be GC'd.  For native .mpy files this top-level function object points to the bss and rodata (if they exist), so they'll get GC'd.  And this problem should manifest on all architectures.

The fix can be the same as in #6045, to maintain a list of all imported native .mpy top-level function objects, but it'd be nice to find a neater way to do it....

**Comment by agners** [comment]
@dpgeorge sounds plausible. I tried the the suggested change in https://github.com/micropython/micropython/pull/6061/files, which from what I understand does keep a global pointer for __init__ (and with that bss). With this change I can no longer reproduce the issue...

**Comment by agners** [comment]
Unfortunately, it seems not to do the trick entirely: After some hours/days of running, I get `FAT filesystem appears to be corrupted.`...
