### ISSUE TITLE
MICROPY_STACK_CHECK does not work as expected, when micropython runs alternately with other codes

### ISSUE THREAD

**Issue by hayate0106** [micropython/micropython#6593]
The original intention of **_MICROPY_STACK_CHECK_**  should be used for stack check of python. But if I execute the following code, the **_mem_in_c_** will affect the stack check. Is this under consideration for using **_MICROPY_STACK_CHECK_**?
```c

void* m_call(void* str) {
  const char* s = mp_obj_str_get_str(str);
  char mem_in_c[10240];
  do_str(s);
}

======================================================

do_str("import m\nm.call(\"print(123)\")")

```

**Comment by dpgeorge** [comment]
> The original intention of **_MICROPY_STACK_CHECK_** should be used for stack check of python.

Since the Python call frames live on the C stack (usually) this stack-check must check the depth of the C stack.  So it's working as intended.

You can look at PYSTACK, that may help here.
