### ISSUE TITLE
Can urequests use requests AuthBase classes from standard requests?

### ISSUE THREAD

**Issue by achapkowski** [micropython/micropython#6616]
Can urequests use requests AuthBase classes from standard requests?
Thank you

**Comment by jonnor** [comment]
Such questions are best investigated by checking the source code. Currently at https://github.com/micropython/micropython-lib/blob/master/python-ecosys/requests/requests/__init__.py#L36

In this case the answer is no, there is no such mechanism in the 'request' module in MicroPython. Instead you should construct and pass the relevant headers directly for each request.
