### ISSUE TITLE
MICROPY_PY_WIZNET5K=5500: `mod_network_nic_type_wiznet5k'

### ISSUE THREAD

**Issue by BNLConsultancy** [micropython/micropython#6625]
Hi i am currently having issues compiling the wiznet drivers for OPENMV4 board specifications, i am currently getting this error:

```
CC src/systick.c
/home/jack/Development/OPENMV_FIRMWARE/openmv/src/build/micropython/modnetwork.o:(.rodata.mp_module_network_globals_table+0xc): undefined reference to `mod_network_nic_type_wiznet5k'
collect2: error: ld returned 1 exit status
Makefile:682: recipe for target 'firmware' failed
make: *** [firmware] Error 1
```
Is this a known error and does anyone know how i can fix this?

**Comment by jonnor** [comment]
OpenMV is a particular downstream project of MicroPython. Issues building that must be addressed to the OpenMV team.
