### ISSUE TITLE
TypeError when calling super().init() 

### ISSUE THREAD

**Issue by stinos** [micropython/micropython#664]
Using the code from the class_super_object test:

```
class Test(object):
    def __init__(self):
        super().__init__()
```

I get a `TypeError: function takes 1 positional arguments but 0 were given` but only on the INtime patform; this might have to do with uninitialized stack memory: `mp_call_method_n_kw()` in runtime.c gets called with n_args = 0 and the line `int adjust = (args[1] == NULL) ? 0 : 1;` is used to make n_args 1 when called on an object. When testing with msvc, args[1] is 0xFDFDFDFD which are the guard bytes before and after heap alloc'ed memory (so I guess it's actually undefined behaviour to access it since it's not allocated), hence the test happens to pass and adjust becomes 1. On INtime however args[1] happens to be 0, hence the error raised.

**Comment by dpgeorge** [comment]
Now fixed!  See 5f97aaeca4dc607a2d32e758c3ef6131ffb168a6.
