### ISSUE TITLE
Bluetooth registered presence detection with esp32

### ISSUE THREAD

**Issue by kindmartin** [micropython/micropython#6640]
hi all here, hope this 2020 crazy times found you well at home like me, having time for fun coding.
I'm back to official uPy as I'm building a small alarm and I would like to disarm it if one of the owner Bluetooth devices is nearby. I was struggling last week looking /trying examples, I can get any results. 
I imagined a setup process where the owner registers his phone with the esp alarm and if after a deepsleep wake up triggered for a sensor if the devices are in a scan list results instead to proceed with the alarm task just disarms itself-

Can anyone make some hint with a close bt scan example? 

I've read about iPhones changing his MAC address randomly or the like for security reasons, so perhaps this simple idea is more complex than I supposed.

I've tried things like https://lemariva.com/blog/2020/02/tutorial-micropython-and-bluetooth-ble-m5stack or the upy  1.13 https://github.com/micropython/micropython/tree/master/examples. 
any help will be appreciated.

M

**Comment by dpgeorge** [comment]
This is best asked at https://forum.micropython.org
