### ISSUE TITLE
Updating the firmware on my "NUCLEO_F446RE"

### ISSUE THREAD

**Issue by Msadr471** [micropython/micropython#6678]
Hi Everyone,

How should I upload the  `NUCLEO_F446RE-20201205-unstable-v1.13-221-gc8b055717.dfu` on my board?

`pydfu -u NUCLEO_F446RE-20201205-unstable-v1.13-221-gc8b055717.dfu`
![image](https://user-images.githubusercontent.com/49529241/101261382-125c1980-374c-11eb-8a60-0a4fb657c729.png)

`dfu-util aaalt 0 -D NUCLEO_F446RE-20201205-unstable-v1.13-221-gc8b055717.dfu`
![image](https://user-images.githubusercontent.com/49529241/101261401-30c21500-374c-11eb-819d-f24dcb02abfc.png)

on CMD no one of those options works.
![image](https://user-images.githubusercontent.com/49529241/101261372-fb1d2c00-374b-11eb-9cf1-e8830ec245d3.png)

I know I'm wrong but I do not know where ?!
I'm not familiar with Python either!
Well, I just connected the NUCLEO F446 RE board directly to the laptop and executed this code! So I know I missed something but I do not know what it is ?!

commands on cmd: [CMD.txt](https://github.com/micropython/micropython/files/5647742/CMD.txt)

**Comment by dpgeorge** [comment]
These kinds of questions are best asked at: https://forum.micropython.org

In short, you need to install USB drivers on Windows to access the DFU device.  You can read some notes about this here: http://micropython.org/resources/Micro-Python-Windows-setup.pdf
