### ISSUE TITLE
uasyncio is lacking current_task()

### ISSUE THREAD

**Issue by tve** [micropython/micropython#6686]
I find `current_task()` useful for patterns like:
```
class Foo:
    async def run(self):
        self.task = asyncio.current_task()
        ...
    def cancel(self):
        self.task.cancel()
```
of course a real use is likely to have `try ... except CancelledError` etc.
Current work-around is:
```
def current_task():
    from uasyncio.core import cur_task
    return cur_task
```
Maybe all this is an anti-pattern and I should do something different?

**Comment by dpgeorge** [comment]
I think it's a useful function to have.  `cur_task` is already used a fair bit in the core uasyncio implementation.  In an (RT)OS it's like knowing your own thread, which seems to be quite a fundamental piece of information.  And once you have `current_task()` it's easy to pass that value to other tasks if they need to cancel you.
