### ISSUE TITLE
unsuitable german translation of "to" in change flow

### ISSUE THREAD

**Issue by heikokue** [micropython/micropython#6711]
the current german translation "bis" of the english "to" don't fits.
the german word "zu" fits better.

**Comment by heikokue** [comment]
the new change.errors.no-override should be also translated

**Comment by robert-hh** [comment]
Where did you find a German translation in this project? I doubt that Damien would do that. And what "change flow" are you looking at?

**Comment by heikokue** [comment]
oh sorry, I'am working with micropython and node-red in parallel.
this issue is adressed to node-red and I entered this issue in the wrong firefox window.
I close it

**Comment by heikokue** [comment]
oh sorry, I'am working with micropython and node-red in parallel.
this issue is adressed to node-red and I entered this issue in the wrong firefox window.
I close it
