### ISSUE TITLE
ESP32: BLE crash when trying to use an itag

### ISSUE THREAD

**Issue by aguaviva** [micropython/micropython#6730]
python version: MicroPython v1.13 on 2020-09-02; ESP32 module (spiram) with ESP32
repro code:  [itag.py.txt](https://github.com/micropython/micropython/files/5740635/itag.py.txt)
console output:

> 
> Scanning:
> 0 c1:b4:70:74:7e:d8 0 -73 TrackerPA [UUID16(0xfff0)] 03:19:c1:03:02:01:05:03:03:f0:ff:07:ff:c1:b4:70:74:7e:d8:0a:09:54:72:61:63:6b:65:72:50:41
> 0 c1:b4:70:74:7e:d8 0 -71 TrackerPA [UUID16(0xfff0)] 03:19:c1:03:02:01:05:03:03:f0:ff:07:ff:c1:b4:70:74:7e:d8:0a:09:54:72:61:63:6b:65:72:50:41
> 0 c1:b4:70:74:7e:d8 0 -70 TrackerPA [UUID16(0xfff0)] 03:19:c1:03:02:01:05:03:03:f0:ff:07:ff:c1:b4:70:74:7e:d8:0a:09:54:72:61:63:6b:65:72:50:41
> Found sensor: 0 c1:b4:70:74:7e:d8 TrackerPA
> _IRQ_PERIPHERAL_CONNECT 0 0 c1:b4:70:74:7e:d8
> _IRQ_GATTC_SERVICE_RESULT 0 1 11 UUID16(0x1800)
> _IRQ_GATTC_SERVICE_RESULT 0 12 15 UUID16(0x1801)
> _IRQ_GATTC_SERVICE_RESULT 0 16 19 UUID16(0x1804)
> _IRQ_GATTC_SERVICE_RESULT 0 20 25 UUID16(0xfff0)
> _IRQ_GATTC_SERVICE_DONE 20 25
> _IRQ_GATTC_CHARACTERISTIC_RESULT 0 21 22 18 UUID16(0xfff1)
> Connected
> Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
> Core 1 register dump:
> PC      : 0x401600a0  PS      : 0x00060c30  A0      : 0x8016a28b  A1      : 0x3ffdcc50  
> A2      : 0x3ffc52a8  A3      : 0x00000000  A4      : 0x3f42ec87  A5      : 0x3f4028a7  
> A6      : 0x3f4347a2  A7      : 0x3f434808  A8      : 0x00000000  A9      : 0x3ffdcc10  
> A10     : 0x3ffc52a8  A11     : 0x00000000  A12     : 0x00000004  A13     : 0x3ffdcc50  
> A14     : 0x00000003  A15     : 0x3ffc3454  SAR     : 0x00000010  EXCCAUSE: 0x0000001c  
> EXCVADDR: 0x00000004  LBEG    : 0x400998c0  LEND    : 0x400998ee  LCOUNT  : 0x00000000  
> 
> ELF file SHA256: 0000000000000000
> 
> Backtrace: 0x4016009d:0x3ffdcc50 0x4016a288:0x3ffdcc80 0x40169d09:0x3ffdccc0 0x40162d11:0x3ffdccf0 0x4016138d:0x3ffdcd20 0x4016139f:0x3ffdcd40 0x40168682:0x3ffdcd60 0x400f9d0a:0x3ffdcd80 0x40095ce1:0x3ffdcda0
> 
> Rebooting...
> ets Jun  8 2016 00:22:57
> 
> rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
> configsip: 0, SPIWP:0xee
> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
> mode:DIO, clock div:2
> load:0x3fff0018,len:4
> load:0x3fff001c,len:5148
> load:0x40078000,len:14040
> load:0x40080400,len:3764
> entry 0x40080630

**Comment by jonnor** [comment]
Hi @aguaviva - thank you for reporting this issue. Did you find a fix for the problem? Are you able to re-test if this happens on latest MicroPython (1.23)? There have been many upgrades to esp-idf since 1.13, which may have fixed the problem
