### ISSUE TITLE
can't find '__main__' module 

### ISSUE THREAD

**Issue by mimansamaheshwari** [micropython/micropython#6736]
I am trying to make a custom micropython firmware for ESP32 16MB board. I am facing following error in running ```make``` function ```/ports/esp32/build-venv/bin/python3: can't find '__main__' module ```. Can anyone please tell me the possible solution?
So far I have followed all the steps as stated in the Readme file.

**Comment by stinos** [comment]
Can you post the rest of the output right before this error occurs?

**Comment by dpgeorge** [comment]
The esp32 port is now built with cmake.  Please try again.  If it fails feel free to reopen this issue with details of how to reproduce the problem.
