### ISSUE TITLE
JavaScript GC has issues

### ISSUE THREAD

**Issue by embeddedt** [micropython/micropython#6738]
The JavaScript port's garbage collector may need to be revisited. I am not sure where the exact problem is, but running `import gc` followed by `gc.collect` triggers the following error:

```
RuntimeError: memory access out of bounds
    at wasm-function[35]:0x15fa
    at invoke_vii (ports/javascript/build/micropython.js:2188:25)
    at wasm-function[1387]:0xa200b
    at wasm-function[1094]:0x79b38
    at wasm-function[647]:0x4b571
    at wasm-function[426]:0x3554d
    at wasm-function[424]:0x3543c
    at invoke_iiii (ports/javascript/build/micropython.js:2133:32)
    at wasm-function[1179]:0x7f687
    at wasm-function[657]:0x4c416
```

EDIT: I should also note that this is being compiled with Emscripten 2.0.4, which uses WebAssembly instead of asm.js. However, we found that the same crash occurs in asm.js mode (though the stack trace is obviously different).

**Comment by dpgeorge** [comment]
Should be fixed by c13853f4dab9c65ee6d1af99b25f999b16ef2827
