### ISSUE TITLE
hibernation support on the esp32

### ISSUE THREAD

**Issue by keredson** [micropython/micropython#6743]
i see the esp32 deep sleep mode (10µA) is supported:
http://docs.micropython.org/en/latest/esp32/quickref.html#deep-sleep-mode

is the hibernation mode (2.5µA) supported as well?
https://lastminuteengineers.com/esp32-sleep-modes-power-consumption/

**Comment by askpatrickw** [comment]
Hey @keredson the MP crews prefers questions in the forum which you can find here https://forum.micropython.org/

**Comment by jonnor** [comment]
Hibernation mode is not supported, and I have not seen any plans to add it at this time.

Proposing to close this issue.
