### ISSUE TITLE
New Issue Template

### ISSUE THREAD

**Issue by askpatrickw** [micropython/micropython#6744]
I suggest the MP Repo add a New Issue Template which explains how Issues should be used and to direct people to the forum for questions instead of using Issues.

You can see how to set that up at the following link.

https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/configuring-issue-templates-for-your-repository

**Comment by jimmo** [comment]
Thanks for the suggestion @askpatrickw  -- I agree. Would be interested to get your feedback on https://github.com/micropython/micropython/pull/6754

**Comment by askpatrickw** [comment]
long ago fixd
