### ISSUE TITLE
MPZ arithmetic errors with DIG_SIZE == MPZ_DIG_SIZE

### ISSUE THREAD

**Issue by mipy123** [micropython/micropython#6777]
There are some (potentially dangerous) arithmetic errors often occurring with long 100% CPU delays with the Unix port defaults (cannot test other ports) when dealing with large numbers.

CPython:
`>>> (2**256 - 2**32)**2 // (2**256 - 2**32)
115792089237316195423570985008687907853269984665640564039457584007908834672640`

MicroPython 1.13 (takes approximately 1 minute):
`>>> (2**256 - 2**32)**2 // (2**256 - 2**32)
1766847064778390606685032887445983096815437806911733293014036620377194496`

MicroPython 1.13 (immediate, with DIG_SIZE = MPZ_DIG_SIZE - 1):
`>>> (2**256 - 2**32)**2 // (2**256 - 2**32)
115792089237316195423570985008687907853269984665640564039457584007908834672640`

Is it safe to change the default DIG_SIZE to MPZ_DIG_SIZE - 1?

**Comment by dpgeorge** [comment]
Thanks for the report.  I can reproduce it.  This is indeed a serious bug, which seems to be an edge case in the long division.

A simpler reproduction, which is broken on unix (64-bit) and stm32 (32-bit, on a PYBD-SF6):
```
>>> (2**48-1)**2 // (2**48-1)
65535
```
True answer is 281474976710655

**Comment by dpgeorge** [comment]
See #6844 for a fix that fixes the cases above.  The fix needs further testing.
