### ISSUE TITLE
esp32: Audio encoder FLAC/MP3 wanted

### ISSUE THREAD

**Issue by emard** [micropython/micropython#6783]
HI!

I'd like if possible the audio compression encoder in micropython.
FLAC encoder would be ideal, but MP3 is ok too.

I'd like to store audio from microphone to SD card, compressed
One example code in C is here

https://github.com/myvobot/esp32_mp3_encoder

**Comment by UnexpectedMaker** [comment]
This is a feature request not an issue. Maybe ask for this on the forums?

**Comment by jonnor** [comment]
Hi. This kind of functionality can - and should - be implemented outside of core MicroPython. For example, as user C modules or native C module. There is a discussion thread about this here: https://github.com/orgs/micropython/discussions/11307
Proposing to close this issue in favor of the discussion thread.
