### ISSUE TITLE
OSError: [Errno 2] ENOENT - Sipeed Maixduino esp32 - Audio

### ISSUE THREAD

**Issue by alan-egham** [micropython/micropython#6807]
I am using a [Sipeed Maixduino esp32 board. ](https://www.amazon.co.uk/Seeed-Studio-Sipeed-Maixduino-RISC-V/dp/B07SW9ZWQQ) I am running an example code from the [Sipeed website ](https://maixpy.sipeed.com/en/libs/Maix/audio.html?h=audio)however it does not work despite me having put the 6.wav file inside the sd card. The board is working fine with other functions but for audio it just shows:

Traceback (most recent call last):
  File "<stdin>", line 18, in <module>
OSError: [Errno 2] ENOENT
MicroPython v0.5.0-125-gd4bdb25 on 2020-08-26; Sipeed_M1 with kendryte-k210
Type "help()" for more information.

and it says there are problems with line 18 which is:

player = audio.Audio (path = "/sd/6.wav")

however, I cannot locate where it had gone wrong. I am a beginner at this, please help. Thanks!

**Comment by jonnor** [comment]
This seems to be Sispeed own distribution of MicroPython, and their example code. Please address questions about usage and bugs to them.
We can only support the upstream MicroPython, and recent versions (latest is 1.23).
