### ISSUE TITLE
PWM bias at high frequency 

### ISSUE THREAD

**Issue by oldeman** [micropython/micropython#6815]
I played today with PWM high frequencies and noticed a bias that is tiny at low frequencies but gets big at high frequency: pwm.freq(125000000) results in 62.5MHz, pwm.freq(62500000) results in 41.67MHz, pwm.freq(41666666) results in 31.25MHz, pwm.freq(31250000) results in 25MHz etc.

I think it's the line
uint32_t div16_top = 16 * source_hz / freq;
which I believe should be
uint32_t div16_top = 16 * source_hz / freq -1;

**Comment by IhorNehrutsa** [comment]
Please specify a port

**Comment by jonnor** [comment]
This issue has insufficient information needed to reproduce the problem. Proposing to close.
