### ISSUE TITLE
ST-LINK on Nucleo-144 STM32-H743ZI2 -- deactivated by MicroPython?

### ISSUE THREAD

**Issue by codedump** [micropython/micropython#6830]
First, let me be honest and state that I've posted essentially the same message on the MicroPython forum. However, as the MicroPython post apparently is moderated (and awaits moderation), and I'm assuming that the GitHub issue page has more reach, I'm posting it again here. Please advise if this is considered "bad behaviour", take my apologies if yes, and let me know if discussion is generally preferred by the community on the Forum or on GitHub in the future.

Now to my issue: I've managed to install MicroPython on the ```STM32-H743ZI2``` few weeks ago. Using the on-board STLINK-V3E requires a custom ```st-link``` version, as described [here](https://github.com/stlink-org/stlink/issues/1063), but otherwise works well. I do have a MicroPython prompt, but I didn't get into details on what exactly works and what doesn't. (I think a simple LED-test failed, but it might also have been me doing something wrong with MicroPython, I'm just beginning.)

Now I'm trying to understand the hardware better and was attaching the USB cable to ST-LINK again, only to find this output:
```
root@7597058af286:~# st-info --probe
Found 1 stlink programmers
 serial:     303032413030334633343338353130433334333133393339
 hla-serial: "\x30\x30\x32\x41\x30\x30\x33\x46\x33\x34\x33\x38\x35\x31\x30\x43\x33\x34\x33\x31\x33\x39\x33\x39" 
 flash:      0 (pagesize: 0)
 sram:       0 
 chipid:     0x0000
 descr:      unknown device   
```

This essentially means that the ST-LINK is dead in the water. It's supposed to look like this instead:
```
 ...
flash:      2097152 (pagesize: 131072)
sram:       131072
chipid:     0x0450
descr:      H742/743/753
```

Am I doing something wrong, or did MicroPython just deactivate the on-board ST-LINK?

Where should I start reading to understand more? I've combed the st.com documentation I could find on this device (they don't even state that deactivating ST-LINK should be possible), and I've read the READMEs from MicroPython, in particular the one on the STM32 ports.

Cheers & Thanks

**Comment by dpgeorge** [comment]
This question is definitely more suited to the forum.  Here is for bug reports and discussion of features.

I just approved your post.  See here for further discussion: https://forum.micropython.org/viewtopic.php?f=12&t=9709&p=54303
