### ISSUE TITLE
rp2 port no module named array

### ISSUE THREAD

**Issue by benevpi** [micropython/micropython#6837]
In the latest version of MicroPython from the getting-started page (version 1.14 dated 2nd Feb), there doesn't appear to be the array module. The following fails

```
import array
```

I *think* this also stops PIO code from running -- at least, it seems to stop mine.

**Comment by robert-hh** [comment]
There is uarray. So it's the alias which is missing. You can use

import uarray as array

**Comment by benevpi** [comment]
Just to add -- here's some code that was working until this version: https://gist.githubusercontent.com/benevpi/845e5dc432f05b6160ed56fc6f3b4032/raw/e151508ae724fcfbf0b08be33ebce554dff563c2/pwm_pio.py

**Comment by benevpi** [comment]
there's no uarray

```
MicroPython v1.14 on 2021-02-02; Raspberry Pi Pico with RP2040

Type "help()" for more information.
>>> import uarray
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: no module named 'uarray'
>>> 
```

**Comment by aallan** [comment]
I'm going to back out, and point the [Getting Started](https://www.raspberrypi.org/documentation/pico/getting-started/) page at the launch version of MicroPython (dated stamped 20210121) unless this is resolved.

**Comment by robert-hh** [comment]
The code which you are pointed at works fine. So there may by a problem in the public firmware image. I am using this one which I have build myself: https://github.com/robert-hh/micropython/blob/rp2_fat/ports/rp2/build/firmware.uf2

**Comment by benevpi** [comment]
yep, @robert-h 's firmware works fine. It's the public one with the problem

**Comment by aallan** [comment]
> The code which you are pointed at works fine. So there may by a problem in the public firmware image. I am using this one which I have build myself: https://github.com/robert-hh/micropython/blob/rp2_fat/ports/rp2/build/firmware.uf2

Could you quickly download the public binary, https://micropython.org/download/rp2-pico/rp2-pico-latest.uf2, and test?

**Comment by aallan** [comment]
Okay then. Looks like it's up to @dpgeorge.

**Comment by The-Spirit** [comment]
> I'm going to back out, and point the [Getting Started](https://www.raspberrypi.org/documentation/pico/getting-started/) page at the launch version of MicroPython (dated stamped [20210121](https://www.raspberrypi.org/documentation/pico/getting-started/static/5d8e777377e8dbe23cf36360d6efc727/pico_micropython_20210121.uf2)) unless this is resolved. @dpgeorge can you take a look?

Fixed it for me, thanks 👍 
Was thinking it was me with my inexperience.....

**Comment by dpgeorge** [comment]
Thanks for the report.  The reason the public builds don't include it is because they build the firmware in a directory that is outside the source tree, and the user-c-modules feature didn't support this.  That should be fixed by #6845.

**Comment by dpgeorge** [comment]
Hopefully fixed by 1f800cac3c4f56418486f24c3824418a890f759f.  Let's see if the daily builds have array.

**Comment by lurch** [comment]
Thanks Damien.
If the next daily-build _does_ fix this problem (which prevented PIO code from working), should we link the Getting Started page to (a copy of) that, rather than the 20210121 release (which has the GP19 and ADC temp-sense bugs)? Or should we continue linking to 20210121 until the stable v1.15 is released? ping @aallan

**Comment by The-Spirit** [comment]
> Hopefully fixed by [1f800ca](https://github.com/micropython/micropython/commit/1f800cac3c4f56418486f24c3824418a890f759f). Let's see if the daily builds have array.

Feedback: latest unstable build (rp2-pico-20210205-unstable-v1.14-8-g1f800cac3.uf2) has array's 👍

**Comment by benevpi** [comment]
Also, latest unstable rp2-pico-20210205-unstable-v1.14-8-g1f800cac3.uf2 version works with PIO again (at least in the simple version tested above)

**Comment by aallan** [comment]
Okay, I've pulled last night's unstable and the version of MicroPython you get when you click to download the UF2 from the Getting Started page is now rp2-pico-20210205-unstable-v1.14-8-g1f800cac3.uf2. I can flip the link back to the permanent URL of  https://micropython.org/download/rp2-pico/rp2-pico-latest.uf2 when V1.15 is released I guess?

**Comment by dpgeorge** [comment]
Thanks for confirming the fix.

> Okay, I've pulled last night's unstable and the version of MicroPython you get when you click to download the UF2 from the Getting Started page is now rp2-pico-20210205-unstable-v1.14-8-g1f800cac3.uf2. I can flip the link back to the permanent URL of https://micropython.org/download/rp2-pico/rp2-pico-latest.uf2 when V1.15 is released I guess?

This sounds fine.  But in the future it make come up again that we want a fix to go through to a "stable" release before a MicroPython release.  Maybe there's a better way to manage this?  I don't really have any ideas though.

**Comment by lurch** [comment]
In SemVer land you'd make a v1.14.1 release ?

**Comment by dpgeorge** [comment]
> In SemVer land you'd make a v1.14.1 release ?

Indeed.  For that we'd need to start doing branches with patch releases.  That can be done, just hasn't been done before here.

**Comment by ObeidHaidar** [comment]
Hey,

Had the same issue recently. I believe Thonny Python IDE downloads the stable uf2 file onto the pico.
Problem was fixed when downloading the unstable build https://www.raspberrypi.org/documentation/pico/getting-started/static/f70cc2e37832cde5a107f6f2af06b4bc/rp2-pico-20210205-unstable-v1.14-8-g1f800cac3.uf2

**Comment by robert-hh** [comment]
It' called daily build, not unstable build. These daily builds are typically as stable as the others.

**Comment by aallan** [comment]
> It' called daily build, not unstable build. These daily builds are typically as stable as the others.

The word "unstable" is right there in the file name.
