### ISSUE TITLE
rp2 PIO: Allow merging Tx/Rx FIFOs together

### ISSUE THREAD

**Issue by tjvr** [micropython/micropython#6854]
The PIO state machines on the RP2040 have 4 word deep TX and RX FIFOs. If you only need one direction, you can "merge" them into either a single 8 word deep TX or RX FIFO. The [uart_rx example](https://github.com/raspberrypi/pico-examples/blob/master/pio/uart_rx/uart_rx.pio) does this for example.

This merging is controlled using `sm_config_set_fifo_join`:

```c
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_RX);
```

I can't see a way to set this from MicroPython; it looks like `sm_config_set_fifo_join` is never called. Is this intentional?

Happy to try writing another PR if you agree we should add this. I'm not sure what the API would look like!

**Comment by dpgeorge** [comment]
> I can't see a way to set this from MicroPython; it looks like `sm_config_set_fifo_join` is never called. Is this intentional?

It's simply not implemented at the moment.

> Happy to try writing another PR if you agree we should add this. I'm not sure what the API would look like!

Feel free to.  I think it can just set the relevant bits in `shiftctrl` in `PIOASMEmit.__init__`, so it needs some new keyword args to that constructor.  Maybe `fifo_join=PIO.JOIN_TX`?
