### ISSUE TITLE
modbluetooth: Descriptor flag mapping

### ISSUE THREAD

**Issue by jimmo** [micropython/micropython#6864]
See https://forum.micropython.org/viewtopic.php?f=2&t=9690&p=54636

Characteristic flags (expect the BLE_GATT_CHR_F_* values) are handled differently to descriptor flags (expect the BLE_ATT_F_* values).

Because ubluetooth defines its own constants (for compatibility across multiple stacks), although it happens to match exactly the BLE_GATT_CHR_F_ values, we should explicitly do this mapping for descriptors.

**Comment by dpgeorge** [comment]
Fixed by e6de6656f4146ace63304795e24dc7aae7f4dd1c
