### ISSUE TITLE
STM32: Can't Factory Reset

### ISSUE THREAD

**Issue by braiden** [micropython/micropython#6903]
Expected Behavior:
  1. While Holding User Button
  2. Press Reset Button
  3. Release User Button after 3 flashes
  4. Devices echos back 3 flashes
  5. Files-system should be restored to default state.

?

Or am I misunderstanding how it's supposed to work?

I had to change this line:
https://github.com/micropython/micropython/blob/bffb71f523e4bcc21b913af291deeb67091bed88/ports/stm32/main.c#L534

to: `mounted_flash = init_flash_fs(state.reset_mode);`

... since https://github.com/micropython/micropython/blob/bffb71f523e4bcc21b913af291deeb67091bed88/ports/stm32/main.c#L475 only updates `state.reset_mode` not `reset_mode`.

**Comment by chrismas9** [comment]
`Release User Button after 3 flashes`

That depends on the board and how many LEDs are configured. Boards with one LED will flash it three times for FS reset. Boards with three or more LEDs (eg pyboard) count in binary on LED2 and LED3 so FS reset is when both are on. Boards with two LEDs also count in binary but you only see bit 0. When LED2 comes on count is 1. When it goes out count is 2. When it comes on again count is 3. So FS reset is second flash. Many Nucleo boards only have two LEDs.

**Comment by braiden** [comment]
My board, [WeAct_F411CE](https://github.com/WeActTC/WeAct_F41), has 1 led, active low. So three flash, reset_mode = 3 I believe, and PR should resolve.

Maybe the bug exists only for boards where `MICROPY_HW_USES_BOOTLOADER`  is false.

**Comment by dhylands** [comment]
I can confirm that using the latest master than the file system reset no longer works on my PYBV11 board.

I'm releasing when both orange and green LEDs are lit and the files listed in my filesystem before the reset are still there after the reset.

**Comment by dhylands** [comment]
I can confirm that the filesystem reset doesn't work on my PYBV11 with the latest master and that the filesystem reset works properly on my PYBV11 with PR #6904

**Comment by dpgeorge** [comment]
Thanks for the report, and sorry it took a bit of time to get to it.
