### ISSUE TITLE
unix port socket sendto - "TypeError: object with buffer protocol required"

### ISSUE THREAD

**Issue by ozimchuk** [micropython/micropython#6924]
MicroPython v1.14-68-gd4b45898f on 2021-02-18; linux version

The following code produces "TypeError: object with buffer protocol required":

> from socket import *
> s = socket(AF_INET, SOCK_DGRAM)
> s.sendto(b'\x00', ('localhost', 5000))

**Comment by dpgeorge** [comment]
The second argument to sendto must be an address as returned by getaddrinfo.  The following may work:
```
s.sendto(b'\x00', getaddrinfo('localhost', 5000)[0][-1])
```

**Comment by ozimchuk** [comment]
> The second argument to sendto must be an address as returned by getaddrinfo. The following may work:
> 
> ```
> s.sendto(b'\x00', getaddrinfo('localhost', 5000)[0][-1])
> ```

This worked for me.
Thank you!
