### ISSUE TITLE
ESP32 sys.path is _slash_lib instead of /lib

### ISSUE THREAD

**Issue by wogum** [micropython/micropython#6942]
In ESP32 builds 1.14-70 and 1.14-72 sys.path is _slash_lib instead of /lib. This issue has been persistent since the Makefile changes 6 days ago.
import sys
print(sys.path)

gives:
['','_slash_lib']

**Comment by dpgeorge** [comment]
Thanks for the report.  Should be addressed by #6944.

**Comment by dpgeorge** [comment]
Fixed by 75db0b907942f4b2e7306d2ce90d2f014cd5a414

**Comment by wogum** [comment]
Thanks for the fix and very fast response.
