### ISSUE TITLE
GB2312 and GBK encoding doesn't work on MicroPython

### ISSUE THREAD

**Issue by fred913** [micropython/micropython#6951]
### How To Reappearance: 
Platform: MicroPython v1.14 on 2021-02-02; ESP module with ESP8266
Just evaluate the following evaluation:
`"一".encode("gbk")`
The result is same as `"一".encode("utf-8")`
But as you know, UTF-8 encoding is not same as GB2312 encoding.
Does MicroPython support GB2312 encoding?

**Comment by dlech** [comment]
> Does MicroPython support GB2312 encoding?

No, it does not.
