### ISSUE TITLE
bare-arm is missing include flags for user modules

### ISSUE THREAD

**Issue by KaiJan57** [micropython/micropython#6971]
https://github.com/micropython/micropython/blob/cdaec0dcaffbfcb58e190738cf6e9d34541464f0/ports/bare-arm/Makefile#L19
When trying to compile bare-arm with user modules, include flags are missing. It took me hours to find that this line is missing `$(CFLAGS_MOD)`, so maybe add that by default? I believe that could spare others many hours of frustration!

**Comment by dpgeorge** [comment]
The bare-arm (and minimal) ports are not really intended to be built using user C modules.  And it's not enough to just add `$(CFLAGS_MOD)`, it also needs additions for `$(CFLAGS_EXTRA)`, `$(SRC_MOD)` and `$(LDFLAGS_MOD)`, as well as `$(SRC_QSTR)`.  And then more stuff for C++ support (which is needed to build the default set of user C modules in the examples/ directory).

**Comment by dpgeorge** [comment]
See 4fc2866f45692b05829d71b636724e690b786307 for improvements to the bare-arm port.
