### ISSUE TITLE
UNIX: Running MPY files - Invalid Syntax

### ISSUE THREAD

**Issue by Barak-Men** [micropython/micropython#6983]
Hi, 
im  trying to run .mpy files - that generated as a result of running `mpy-cross myscript.py` .

I want to run this files directrly from micropython, i.e, 
I need to send to my microcontroller only a `.mpy` files and to run them directly.

when i try to just run micropython on mpy files,
the error `invalid syntax is  raised due to Invalid token`

so how can i run mpy files?
thanks.

(i didnt find an option to ask questions on the forum, so im asking it here)

**Comment by bertelschmitt** [comment]
Did you run  mpy_cross with the -march=[your platform] option?

**Comment by ALEX010001** [comment]
Yes i got `.mpy` file, and I want to running it directly.
I want something like:

./micropython myscript.mpy

how can i do that?

**Comment by ALEX010001** [comment]
I need i due to lack of memory in my mcu.
I want to flash only the part that runs the bytecodes (.mpy files), and to send to my mcu only this .mpy files.

**Comment by dpgeorge** [comment]
If you want to run a .mpy locally using the unix port of MicroPython then you need to import it rather than run it directly.  Eg:
```
$ mpy-cross -mcache-lookup-bc test.py
$ micropython -m test
```

**Comment by jonnor** [comment]
I believe the above documents how to resolve the problem. Proposing to close this issue.
