### ISSUE TITLE
Extra warnings

### ISSUE THREAD

**Issue by eblot** [micropython/micropython#699]
Hi,

I've rebuilt micropython for an eCos-embedded platform, based on an old plain ARM7-TDMI (ARMv4T) SoC. We usually build all our code with many extra warnings enabled, but I had to disable many of them with micropython as they kept rising. Some warnings are harmless, but some others are likely to report real potential issues.

Here is the list of warnings that I had to shut off to build micropython:

- [ ] -Wbad-function-cast
- [x] -Wdouble-promotion
- [ ] -Wfloat-equal
- [x] -Wformat
- [x] -Wmissing-declarations
- [ ] -Wmissing-format-attribute
- [x] -Wmissing-prototypes
- [x] -Wold-style-definition
- [x] -Wpointer-arith
- [x] -Wredundant-decls
- [x] -Wshadow 
- [x] -Wsign-compare
- [x] -Wstrict-prototypes
- [ ] -Wswitch-default
- [ ] -Wswitch-enum
- [x] -Wuninitialized
- [ ] -Wunsuffixed-float-constants
- [x] -Wunused-parameter

I known that I'd better come with patches, for now I've just started playing with micropython.
It may be worth adding some/all of them to the default warning list?

Compiler: arm-eabi GCC 4.9.0 / binutils 2.24

EDIT by @dpgeorge: made warnings above checkboxes.  Once checked off, core uPy passes that warning.

**Comment by dpgeorge** [comment]
uPy now compiles with more warnings enabled (the ones checked true in the first comment of this issue).  These warnings are enabled on unix/ port.

The rest of the warnings are not going to be fixed in the foreseeable future.
