### ISSUE TITLE
machine PWM library Reference Missing From Docs

### ISSUE THREAD

**Issue by A-Krau** [micropython/micropython#7000]
No reference to machine.PWM can be found in the Libraries Reference section of http://docs.micropython.org/

Specifically interested in Raspberry Pi Pico port.

**Comment by jonnor** [comment]
Thank you for reporting!
There is now documentation for PWM at https://docs.micropython.org/en/latest/library/machine.PWM.html?highlight=pwm#machine.PWM and https://docs.micropython.org/en/latest/rp2/quickref.html#pwm-pulse-width-modulation

Proposing to close this issue.
