### ISSUE TITLE
timeout function in UART not available

### ISSUE THREAD

**Issue by nayanagg** [micropython/micropython#7001]
HI,

I want to use timeout method in UART for Pi Pico.

HELP!

**Comment by robert-hh** [comment]
There is a Pull Request open implementing that. See https://github.com/micropython/micropython/pull/6870, but also https://github.com/micropython/micropython/issues/6999 for the basic problem in the UART module.

**Comment by dpgeorge** [comment]
UART timeout support was added to the rp2 port in 8ade163fffe9cca620ebe945dec8d25c54dc877d
