### ISSUE TITLE
Interesting size savings in mp_execute_bytecode: -1500 bytes, -3.2% speed

### ISSUE THREAD

**Issue by jepler** [micropython/micropython#7004]
Over in CircuitPython, we noticed two techniques (for interpreter with MICROPY_OPT_COMPUTED_GOTO  enabled) that gave a nice flash savings but at a cost to the speed of the bytecode interpreter.  It looks like the structure is similar enough to current micropython that the same could be applied here.

https://github.com/adafruit/circuitpython/pull/4344

* a table called entry_table was reduced from being a 4-byte type to being a 2-byte type; however, a small amount of arithmetic was added to each DISPATCH(), making the size savings about half of what I'd hoped for
* Second, realizing that the code in the DISPATCH macro itself is a significant part of the overall code size of mp_execute_bytecode, consolidate all of them into a single ONE_TRUE_DISPATCH(), which the others reach by goto. This saves much more space, at the expense of one additional jump for every bytecode encountered.

Sizes and timings from a Feather M0 Adalogger and the English language build of CircuitPython:

<table>
<tr><th>Version <th>Free Flash <th>Increase <th>Benchmark Time <th>Increase
<tr><th> Original <td> 2100 bytes <td> <td> .655s <td>
<tr><th> Compress Table <td> 2332 bytes <td> +232 <td> .666s <td> +1.7%
<tr><th> One True Dispatch <td> 3600 bytes <td> +1268/+1500 <td> .676s <td> +1.7%/+3.2%
</table>

**Comment by dpgeorge** [comment]
Thanks for letting us know about this.  I did already post over at https://github.com/adafruit/circuitpython/pull/4344#issuecomment-793765741 but copying my comment here:

Did you try compiling with MICROPY_OPT_COMPUTED_GOTO disabled, ie using a big switch in the VM? I just tried this patch out here and it seems that a big switch is still smaller than what is here.

Using minimal port, cross compiled to Cortex-M4 with -Os:
```
build options                                       fw size     diff to baseline
baseline MICROPY_OPT_COMPUTED_GOTO=0                67224       +0  
MICROPY_OPT_COMPUTED_GOTO=1                         69008       +1784   
MICROPY_OPT_COMPUTED_GOTO=1 w/ compressed table:    68516       +1292   
MICROPY_OPT_COMPUTED_GOTO=1 w/ one-true-dispatch:   67844       +620    
MICROPY_OPT_COMPUTED_GOTO=1 w/ both above:          67336       +112
```

So in the end if the port/board needs to save space then it's best to just disable `MICROPY_OPT_COMPUTED_GOTO` to get the most space savings (and also performance is still very good with this option disabled).
