### ISSUE TITLE
esp32: The modified .py files can't be compile automatically.

### ISSUE THREAD

**Issue by lesson6** [micropython/micropython#7007]
when i change some python files,  and compile use command "make". Those files can't compile automatically.

**Comment by lesson6** [comment]
hi，IhorNehrutsa. Thank you for answer.Yes,I mean the files in the dirctory micropython/ports/esp32/modules.
I used the latest micropython that suport cmake.
micropython commit id is  59a129f22f096d992496111c498b3ea97e637115.
 And esp-idf commit id is dddcc2ede8601915ad134ecf46f8682e5e6de2a4 (HEAD -> release/v4.2, origin/release/v4.2).
Maybe there have some different .

for example, I changed _boot.py(just add a line to print hello), then make, it show "no work to do".
![image](https://user-images.githubusercontent.com/49231903/110571744-0771b480-8193-11eb-9d37-4df007c3a82f.png)

**Comment by lesson6** [comment]
By the way , it work well when i use makefile to compile earlier version.

**Comment by dpgeorge** [comment]
Seems to be related to #6948.

**Comment by lesson6** [comment]
Yes, It is the same reason.
