### ISSUE TITLE
f.write() prints number bytes written in nightly

### ISSUE THREAD

**Issue by jdtsmith** [micropython/micropython#7013]
Today's nightly ESP 32 non-SPIRAM build:

```
>>> with open("file.txt","w") as f: 
...    for i in range(3):
...     f.write('Testing\n'*(i+1))
... 
8
16
24
```

**Comment by dpgeorge** [comment]
That's expected behaviour.  At the REPL all results of executing a line a printed (but usually the result is `None` which is not printed).

**Comment by dpgeorge** [comment]
Just to be clear, this is CPython behaviour:
```
$ python
Python 3.9.1 (default, Dec 13 2020, 11:55:53) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> for i in range(4):
...     i
... 
0
1
2
3
>>> 
```

**Comment by jdtsmith** [comment]
Interesting.  I'm suppose I'm used to ipython behavior, which only prints the _last_ item in a multi-line block by default. Thanks!
