### ISSUE TITLE
rp2 daily builds use outdated pico-sdk

### ISSUE THREAD

**Issue by Hermann-SW** [micropython/micropython#7016]
Last weekend V1.1.0 pico-sdk was published.
Can daily rp2 builds please update lib/pico-sdk before building? 
https://forum.micropython.org/viewtopic.php?f=21&t=10016

Current:
pico-sdk @ 2d5789e
lib/pico-sdk: Update to latest version v1.0.1.
last month

V1.1.0 is fc10a97

**Comment by dpgeorge** [comment]
Yes, good idea.  See #7018.

**Comment by dpgeorge** [comment]
pico-sdk updated to 1.1.0 in a62e791978a66948637538d1a0a363fe35fa88e4
