### ISSUE TITLE
How can I get clean source code that does not depend on the platform.

### ISSUE THREAD

**Issue by china-zhangdj** [micropython/micropython#7017]
How can I get clean source code that does not depend on the platform, just like lua, which can be easily ported to any platform. When I tried to port micropython to arm9 bare metal, I encountered many errors because of source code dependency.

**Comment by dpgeorge** [comment]
There are a few places to look for examples of how to integrate MicroPython into a system:
- http://docs.micropython.org/en/latest/develop/porting.html
- `examples/embedding/`
- `ports/bare-arm/`
- `ports/minimal/`

**Comment by china-zhangdj** [comment]
alright, thank you very much.
