### ISSUE TITLE
Feature request: UART RTS/CTS hardware flow control on ESP32

### ISSUE THREAD

**Issue by Sebbb** [micropython/micropython#7023]
As the underlying esp-idf API supports RTS/CTS for serial communication, it would be good to be able to use it also from Micropython. Currently it's not implemented.

I have found #4438, but that seems to be for a more generic software approach. 

As hardware flow controls is implemented in the Development Framework, it should be rather easy to add.

https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/uart.html#_CPPv421uart_hw_flowcontrol_t

Thanks!

**Comment by dpgeorge** [comment]
Flow control is implemented in a3675294ae39a724aec6959238c45af0dea92f21
