### ISSUE TITLE
mp_ prefix collision

### ISSUE THREAD

**Issue by eblot** [micropython/micropython#704]
FWIW, there are many libraries out there that use the `mp_` prefix. For example, `ctaocrypt`, a library with big number primitives used for cryptography and SSL implementation from CyaSSL/WolfSSL dedicated to embedded targets. A quick search on Google shows that `mp_` is used in many libraries.

On embedded targets, especially with static linking, this creates name collision at link time.
Maybe it would be worth using a less common prefix, such as `mpy_`?

It is likely that micropython becomes highly popular as it deserves to. Linking with other 3rd party libraries - hence collision occurences would grow.

**Comment by dpgeorge** [comment]
Note: we should probably rename the py/ directory to match the chosen prefix.

**Comment by hauptmech** [comment]
upy_. It seems like many here use uPy to refer to the project. (upython was my first google search for this project when someone told me verbally that I should check it out.)

**Comment by jonnor** [comment]
Nearly 10 years have passed, and the practical problems from this seem to have been pretty small. Perhaps it is OK the way it is? :)
