### ISSUE TITLE
esp32-idf3-20210202-v1.14.bin Firmware Cannot Active Bluetooth

### ISSUE THREAD

**Issue by ChowSings** [micropython/micropython#7042]
CODE：
```
import bluetooth

ble = bluetooth.BLE()
print(ble.active())
ble.active(True)
print(ble.active())
```
PRINT：
bluetooth
False
Traceback (most recent call last):
  File "<stdin>", line 34, in <module>
OSError: [Errno 110] ETIMEDOUT

but esp32-idf3-20200902-v1.13.bin firmware is OK

**Comment by jonnor** [comment]
Hi. We are now using a much more recent esp-idf and many improvements. Issues like this should not occur.
Please report back if issue is still present on MicroPython 1.23 or later
