### ISSUE TITLE
Bluetooth: two exampleImportErrors: no module named 'ble_advertising' or 'bletooth_advertising'

### ISSUE THREAD

**Issue by Ce345** [micropython/micropython#7054]
This error must be earlier reported. Extensive search did not give any results. Therefor this try.
Have tried out two examples in Thonny with the ESP32 as interpreter. (ESP32 micro python tested with a py blink).

**Comment by sonnny** [comment]
Did you add this file  ble_advertising.py to your device. link here ----->   [https://github.com/micropython/micropython/blob/master/examples/bluetooth/ble_advertising.py](url)

Thanks,
Sonny

**Comment by Ce345** [comment]
thanks for your tip. the given url seems not resolvable. will try a google
search

greetings

Op vr 19 mrt. 2021 20:58 schreef sonnny ***@***.***>:

**Comment by Ce345** [comment]
You guided me to this website!!!!
