### ISSUE TITLE
urequest HTTPS get request OSError-202 

### ISSUE THREAD

**Issue by bodemax** [micropython/micropython#7061]
Hi,

I have a php file where i ping whit my esp32. It has  a interval of 10 sec. The first few minutes are running fine but after a while i got a OSErrro -202. I foud this only happens whit https and not http. but i have no other option

the request code:

` print("I wil ping to " , str(urlPing + '?mac=' + str(mac)))`
`  r = requests.get(urlPing + '?mac=' + str(mac))`
`  rText = r.text`
`  r.close()`
`  print(rText) `
the urlPing is a https://www.xxxx.xxx.php (do to sucerty reasons i cannot show the full link)
If the mac addres is valid it will respond "ok" and if it is not valid "no valid mac".

this is the error i get: 
` File "urequests.py", line 108, in get`
`  File "urequests.py", line 53, in request`
`OSError: -202`

 when the errors happens it never stop. try except, reconnect to wifi. only a hardreset

esp32 has 512 KB memory.

If you could help me I am really grateful.

Tanks in advace,
Maxim

**Comment by jimmo** [comment]
This issue is now being tracked in https://github.com/micropython/micropython/issues/8940.
