### ISSUE TITLE
Networking support on Raspberry Pi Pico

### ISSUE THREAD

**Issue by gregwa1953** [micropython/micropython#7062]
Does anyone have any idea when networking support will come to the Raspberry Pi Pico?
I know that CircuitPython has networking support, but I'd rather use MicroPython in the long haul.

**Comment by peterhinch** [comment]
The Pico has no on board networking hardware. A [forum](http://forum.micropython.org/index.php) search will yield at least two ways of overcoming this using ESP8266 boards.

**Comment by gregwa1953** [comment]
Thank you for your assistance.
