### ISSUE TITLE
esptool.py command using -z?

### ISSUE THREAD

**Issue by lumpynose** [micropython/micropython#7077]
On the github project for esptool.py I can't find anything about the -z flag.  Is that still necessary/useful?  You show it on the page on micropython.org for flashing the esp32.

**Comment by dpgeorge** [comment]
Specifying this will compress the firmware during download: https://github.com/espressif/esptool/blob/ed04f90c8ee3994bfedf90de8e2450126c69f196/esptool.py#L3801-L3802
