### ISSUE TITLE
ESP32: Unexpected high pulse on GPIO pin init

### ISSUE THREAD

**Issue by robert-hh** [micropython/micropython#7079]
This effect was mentioned by used @kotk_o on the forum. 
It is impossible to initialize a GPIO pin as low level output and keeping it's output low for the whole process. During init, there will be a high pulse of about 300µs. The reason is the call to gpio_reset_pin() during init, which sets the pin to input mode with the internal pull_up enabled.
Due to that, the GPIO settings do not allow a pin to be configured as input with high impedance. If no pull mode is specified, it stays in the reset mode, which is PULL_UP.
There was obviously a good reason to call gpio_reset_pin(), because that sets it to a known state. But the side effect is not always appropriate.

**Comment by RCS-it1** [comment]
Please, read forum page: https://forum.micropython.org/viewtopic.php?f=18&t=10112

**Comment by dpgeorge** [comment]
> There was obviously a good reason to call gpio_reset_pin(), because that sets it to a known state. But the side effect is not always appropriate.

See #5771 and commit 8a917ad2529ea3df5f47e2be5b4edf362d2d03f6 for this change.

**Comment by dpgeorge** [comment]
See #7121 for a fix.

**Comment by dpgeorge** [comment]
Should be fixed by e5d2ddde25351f1ede7d0d1b00be632301962fb0
