### ISSUE TITLE
ESP32 GPIO wrong initial configuration. Pull-up always enabled

### ISSUE THREAD

**Issue by RCS-it1** [micropython/micropython#7082]
Hello Team,

We detected a **critical error** on micropython for ESP32 (I don't know if it appears in other ports). It seems that when you configure any GPIO, the PULLUP is always enabled during 150-200us. Doesn't matter if you configure the GPIO as input or output. 

This bug is confirmed from multiple users. See this link:

https://forum.micropython.org/viewtopic.php?f=18&t=10112

**Comment by RCS-it1** [comment]
repeated topic..

**Comment by robert-hh** [comment]
My PR was initiated by your forum topic. Since you did not raise one for a few days, I did that in your favor. Your initial problem was the high level, but having no option to set the GPIO as high impedance is also disturbing.

**Comment by dpgeorge** [comment]
Duplicate of #7079.
