### ISSUE TITLE
CC3200 LAUNCHXL port upip module not found

### ISSUE THREAD

**Issue by fsam6177** [micropython/micropython#7128]
I installed micropython on CC3200 LAUNCHXL and it works fine. But when I try to import the upip module, it says module not found. I copied the upip.py and upip_utarfile.py to /flash/lib and tried importing the module. It imports the module but cannot find the attributes help() and install() (AttributeError). I also tried copying the files to /flash/src and then deleting the files from /flash/lib and I get the same error. Finally I copied the files to /flash and still no luck. 
Is there a procedure to install the library or get upip to work? 
![cc3200_flash](https://user-images.githubusercontent.com/35525068/115122493-22032e80-9f86-11eb-9f03-566a1c9dda9c.jpg)

**Comment by dpgeorge** [comment]
> But when I try to import the upip module, it says module not found.

Can you please show the exact error that it raises?  It may be that it cannot find a dependency of upip, rather than upip itself.  Also please show the output of `sys.path`.

**Comment by fsam6177** [comment]
This is what I get when I try to import upip. Also, the sys.path is not available, it is sys.__path__.
![CC3200_error_up](https://user-images.githubusercontent.com/35525068/115308920-87e3e780-a139-11eb-86b0-7cfeec0f72d4.jpg)

**Comment by jonnor** [comment]
`upip` has been replaced by `mip`. Please test and report if `mip` is missing, along with instructions how to reproduce. Proposing to close this issue.
