### ISSUE TITLE
mimxrt/machine_pin: Implement machine pin class

### ISSUE THREAD

**Issue by alphaFred** [micropython/micropython#7164]
The mimxrt port is lacking the `Pin` class of the `machine` module as well as automated generation of pin configuration using `machine-pin.py`. 

I am currently working on this and just wanted to create the issue to make you aware ☺️.

**Comment by alphaFred** [comment]
@dpgeorge

**Comment by dpgeorge** [comment]
Sounds great!

**Comment by dpgeorge** [comment]
`machine.Pin` implemented in ff5d39529c3bf331dd8171aaa24937b2650f40fd
