### ISSUE TITLE
PyCharm warning when using pin.value()

### ISSUE THREAD

**Issue by Delilovic** [micropython/micropython#7165]
PyCharm is displaying a warning when using pin.value()

Parameter 'x' undefined

![image](https://user-images.githubusercontent.com/6611242/116108493-3943c980-a6b4-11eb-93ae-1ddd638cbfad.png)

**Comment by dpgeorge** [comment]
This must be a problem with PyCharm set-up, that it doesn't know the correct signature of `Pin.value()`.  How are function signatures configured?

**Comment by mishafarms** [comment]
There is a plugin for PyCharm for micropython, You must install it and then enable it for your project. See settings/Plugins to install and settings/Languages & Frameworks/micropython.
It does not have support for esp32 just esp8266, but machine seems to be pretty well supported. The plugin source in at 
[https://github.com/vlasovskikh/intellij-micropython](url)

**Comment by dpgeorge** [comment]
Thanks @mishafarms for the info.  I think this issue can be closed now.
