### ISSUE TITLE
STM32/CYW43 driver: Allow using different UARTs for Bluetooth.

### ISSUE THREAD

**Issue by iabdalkader** [micropython/micropython#7173]
https://github.com/micropython/micropython/blob/a708848b0cb0f304f43178140d84d5535e186a38/drivers/cyw43/cywbt.c#L58
And
https://github.com/micropython/micropython/blob/a708848b0cb0f304f43178140d84d5535e186a38/drivers/cyw43/cywbt.c#L152

This driver uses a hard-coded UART6 AF which makes it impossible to use with a different UART, and it also assumes there's an RF switch... Also in uart.c some of the UARTs don't configure CTS and RTS (for some reason) for example UART7 CTS/RTS pins not set:
https://github.com/micropython/micropython/blob/a708848b0cb0f304f43178140d84d5535e186a38/ports/stm32/uart.c#L353
```c
            __HAL_RCC_UART7_CLK_ENABLE();
            #endif
            pins[0] = MICROPY_HW_UART7_TX;
            pins[1] = MICROPY_HW_UART7_RX;
            break;
```
I want to send 2 PRs to fix this (I already tested CYW43 BT with H7/UART7). Is this something that will be merged ?

Note: This is part of a larger goal to make more drivers configurable in board config files and more flexible. This is also related  #6986 (it's been pending for a while, can you please check it out ?) and also there's one more queued PR for H7 ADC.

**Comment by dpgeorge** [comment]
> I want to send 2 PRs to fix this (I already tested CYW43 BT with H7/UART7). Is this something that will be merged ?

Yes, please send them.
