### ISSUE TITLE
[ESP32]urequests, umqtt  not existed in esp32-20210418-v1.15.bin 

### ISSUE THREAD

**Issue by codemee** [micropython/micropython#7185]
The urequests module is not found in esp32-20210418-v1.15.bin firmware. 

![圖片](https://user-images.githubusercontent.com/1037913/116497111-2e1db300-a8d9-11eb-9102-c71a4dc2cd9e.png)

**Comment by mcauser** [comment]
Does this work for you?
```
import upip
upip.install('urequests')
```

**Comment by codemee** [comment]
It works. But the urequests and umqtt modules are builtin in V1.14 and previous version.

**Comment by mcauser** [comment]
Having a look at the 2x manifests:
https://github.com/micropython/micropython/blob/master/ports/esp32/boards/manifest.py
https://github.com/micropython/micropython/blob/master/ports/esp32/boards/manifest_release.py

`urequests` and `umqtt` are present in `manifest_release.py` but not `manifest.py`.

Are you getting your `esp32-20210418-v1.15.bin` from https://micropython.org/download/esp32/ ?

**Comment by codemee** [comment]
Yes, I got the file from the download page.

**Comment by snympi** [comment]
I have found the same issue moving to V1.15 from V1.14 with `umqtt` that is missing. It is missing from the official download used to flash my esp32.

**Comment by dpgeorge** [comment]
This is now fixed, the build system properly selects `manifest_release.py` (it was due to the change to cmake).
