### ISSUE TITLE
How do I read keyboard input without waiting for the user to press Enter?

### ISSUE THREAD

**Issue by nayanagg** [micropython/micropython#7210]
Hi,

I want to print character in i2c LCD display from keyboard through pi pico. But the issue is in input() character is not getting visible until ENTER button is pressed.

Kindly help...

**Comment by robert-hh** [comment]
sys.stdin.read(n), where n is the number of characters. Or sys.stdin.buffer.read(n) for raw characters w/o any translation/encoding.

P.S.: Questions like this are are better asked at the forum (forum.micropython.org).

**Comment by nayanagg** [comment]
Tried sys.stdin.read(1) but still need to press enter to get it displayed on lcd display.

**Comment by dpgeorge** [comment]
As mentioned, this is a great topic for the forum.
