### ISSUE TITLE
mimxrt: all utime.sleepxxx methods fail

### ISSUE THREAD

**Issue by robert-hh** [micropython/micropython#7234]
Calling utime.sleep(), utime.sleep_ms() or utime.sleep_us() freezes the board.

MicroPython v1.15-88-g7b923d6c7 on 2021-05-09; Teensy 4.0 with MIMXRT1062DVJ6A

**Comment by dpgeorge** [comment]
Thanks for the report.  It's because SysTick cannot wake the CPU from WFI/WFE.

I've implemented much improved timing functions in #7275.

**Comment by robert-hh** [comment]
Thanks. Yes, that #7275 is indeed much improved. I searched already in the IMXRT SDK for a class with that functions, but got lost in the sheer volume of interfaces and definitions.

**Comment by robert-hh** [comment]
So I'll close that one. Please merge #7275 soon, so we can integrate it in our PR's.
