### ISSUE TITLE
Cannot build for tinypico since commit 32ec07a3504d6dcbfc53997197a3c53e8c03497f

### ISSUE THREAD

**Issue by cgreening** [micropython/micropython#7240]
Looks like  a reference was left in with the old location:

`boards/UM_TINYPICO/mpconfigboard.cmake`

Still refers to:

```
boards/TINYPICO/sdkconfig.board
```

**Comment by dpgeorge** [comment]
Fixed by cce7096d1a031f43f72c2ea87513301c3db118dc
