### ISSUE TITLE
Pyb v1.1 doesn't work

### ISSUE THREAD

**Issue by Explo7** [micropython/micropython#7255]
Hi, i use my pyboard (with basics tools and program like usine a servomotor and supply the board in energy with à computer) and It's stop suddenly and i only see red, and blue light at their max level, and the yelow one wich is very low. I try   the factory reset but i can't do it (green and yelow light are not on).

Thank for your help

**Comment by peterhinch** [comment]
This query should be raised in [the forum](http://forum.micropython.org/index.php) and not in the MicroPython bug tracker. It will be more likely to receive a response there.

**Comment by dpgeorge** [comment]
It may be that the board has been broken by excessive voltage/current.  If it's not broken it can be recovered by entering DFU mode and reprogramming it.  The forum is the best place to ask about how to check that.
