### ISSUE TITLE
No more ESP32 pre-built 'unstable' firmware

### ISSUE THREAD

**Issue by robhamerling** [micropython/micropython#7296]
There are no more updates listed of pre-built 'unstable' firmware for the ESP32 since version 1.15-22. It was already reported in a forum item, but this hasn't had the desired effect so far.  Opening an issue might be more effective (as suggested in the forum).

**Comment by dpgeorge** [comment]
Thanks for raising this.  It's because the build system uses `MPY_LIB_DIR` in the manifest file, and that doesn't work on cmake since 21fee92be6c534d0d44518c0c76f0c7cf5f64b18 added back support for `FROZEN_MANIFEST`

Should be fixed by #7297.

**Comment by dpgeorge** [comment]
Auto builds have hopefully been fixed, should appear in the next 12 hours.
