### ISSUE TITLE
"decode" method on memoryview?

### ISSUE THREAD

**Issue by smurfix** [micropython/micropython#7347]
When I have a bytestring somewhere in an incoming protocol buffer, currently there's no good way to convert it to an UTF-8 string. Instead, I need to create an intermediate bytearray with the data so that I can call `.decode` on it.

It'd be helpful to have a `.decode` method on the memoryview itself.

**Comment by dpgeorge** [comment]
Instead of `.encode()`/`.decode()`, the recommended way to convert to/from UTF8 in MicroPython is to use:
```python
str(bytes_or_memoryview, 'utf8')
```
This is also compatible with CPython.

**Comment by smurfix** [comment]
OK, that works, thanks.
