### ISSUE TITLE
openmv port to esp32s3 block

### ISSUE THREAD

**Issue by YanMinge** [micropython/micropython#7443]
Hi,
I am creating an open source project, Part of it is to port openmv to esp32s3.
I have done most of the work, usb, camera, micropython...
But I was block here now
https://github.com/YanMinge/esp32_mpy/blob/master/project/aitest/omv/common/usbdbg.c
line 222:
```
                    usbdbg_set_irq_enabled(false);
                    // Clear interrupt traceback
                    mp_obj_exception_clear_traceback(mp_const_ide_interrupt);
                    MP_STATE_VM(mp_pending_exception) = mp_const_ide_interrupt;
                    #if MICROPY_ENABLE_SCHEDULER
                        if (MP_STATE_VM(sched_state) == MP_SCHED_IDLE) {
                            MP_STATE_VM(sched_state) = MP_SCHED_PENDING;
                    }
                    #endif
```

I want to break of repl loop or some micropython script. but the code can't achieve this purpose.

openmv do it like this
```
                    usbdbg_set_irq_enabled(false);
                    mp_obj_exception_clear_traceback(mp_const_ide_interrupt);
                    __set_BASEPRI(0);
                    pendsv_nlr_jump(mp_const_ide_interrupt);
```

**Comment by dpgeorge** [comment]
It's hard to tell why it doesn't work without further details about the symptoms (what goes wrong).

But please use the `mp_sched_exception(mp_const_ide_interrupt)` function instead of setting `MP_STATE_VM()` state directly.

**Comment by YanMinge** [comment]
thanks, I wrote the code as you suggested. Seems to be working perfectly
