### ISSUE TITLE
'module' object has no attribute 'exc_info'

### ISSUE THREAD

**Issue by majoson-chen** [micropython/micropython#7464]
`sys.exc_info` doesn't seem to be implemented yet, but `sys.print_exception` was already exist.
I think it won't be too difficult to open the `exc_info` interface based on the implementation of `sys.print_exception`, but it will be useful for logging and troubleshooting.  

some module like `traceback` and `logging` need this interface to work normally.  
Hope you can adopt my suggestion.  
Tks!

**Comment by Li-Lian1069** [comment]
i use esp32&esp8266 to develop
