### ISSUE TITLE
How to make the LPUART working on STM32 -  Nucleo WB55  ?

### ISSUE THREAD

**Issue by YannickMarietti** [micropython/micropython#7466]
Hello

I am simply struggling to understand how to initialize the newly added LPUART on the Nucleo WB55 ...
I found no example about it.
I try things like this :

`from pyb import UART`
`uart = UART(2)`
`uart.init(9600, bits=8, parity=None, stop = 1)`

But it always fail with a message like : 

_"ValueError: set baudrate XXXX is not within 5% of desired value"_

Which UART number  shall I use ?

Any help would be greatly appreciated !

Best regards

Yannick

**Comment by dpgeorge** [comment]
Try `pyb.UART('LP1')`

**Comment by YannickMarietti** [comment]
Thank you !

With 

`from pyb import UART`
`uart = UART('LP1')`
`uart.init(9600, bits=8, parity=None, stop = 1)`

The problem remains the same, I still get the following message : 

`ValueError: set baudrate 0 is not within 5% of desired value`

Sorry :(

Yannick

**Comment by dpgeorge** [comment]
What version of MicroPython are you running?  Commit 2ac09c2694f89b11544f4abf10413c64eeec2b15 did fix some issues around setting the baudrate on STM32WB55 MCUs.

**Comment by YannickMarietti** [comment]
Hello Damien

Thank you again for your support !
I use this release : 
NUCLEO_WB55-20210625-unstable-v1.16-17-gb51ae20c0.dfu

**Comment by dpgeorge** [comment]
Ok, I can confirm there is something wrong with the setting of the LPUART baudrate on the NUCLEO_WB55.

**Comment by YannickMarietti** [comment]
Thanks :)

**Comment by dpgeorge** [comment]
Should be fixed by fef21144047201d639b2692e3a55083c7180cb29
