### ISSUE TITLE
struct module: Support for half-precision floats ("e")

### ISSUE THREAD

**Issue by scy** [micropython/micropython#7467]
CPython's `struct` module supports packing and unpacking [half-precision floats](https://en.wikipedia.org/wiki/Half-precision_floating-point_format) with the format code `e` since 3.6. These are 16 bit long:

* 1 bit sign
* 5 bit exponent
* 10 bit significand

It would be awesome if MicroPython could support them too.

**Comment by dpgeorge** [comment]
Support for half-floats is now implemented.
