### ISSUE TITLE
Inline assembler movwt does not support full range of long ints

### ISSUE THREAD

**Issue by PinkInk** [micropython/micropython#750]
Example;

Micro Python v1.1.1-138-g2097c8b on 2014-07-13; PYBv1.0 with STM32F405RG
Type "help()" for more information.
>>> @micropython.asm_thumb
... def test():
...   movwt(r0,0x3fffffff+1)
...
SyntaxError: 'movwt' expects an integer
>>>
>>> @micropython.asm_thumb
... def test():
...   movwt(r0,0x3fffffff)
...
>>> test()
1073741823

**Comment by dpgeorge** [comment]
It's been 18 months, but this is now fixed in ea8be373a975356808a19a79f1dd20383bec82ba.  Reason it took so long is because there were lots of other big structural changes that were needed before this could happen.
