### ISSUE TITLE
How is the ".py" file transfer to the device which has micropython firmware?

### ISSUE THREAD

**Issue by yangwc** [micropython/micropython#7507]
I knowe, we can use Thonny, uPyCraft or MicroPython File Uploader transfer the .py file to the device. But now, I need to make a new simple tool, how can I transfer the python file to the device?

**Comment by jimmo** [comment]
Take a look at https://pypi.org/project/mpremote/ or if you want to make your own tool, you can use tools/pyboard.py (from this repository) as a library (which is what mpremote uses too).

FYI this is the bug tracker for MicroPython. This sort of question is better suited for the forum (https://forum.micropython.org)
