### ISSUE TITLE
When using the mpremote tool, must specify the port

### ISSUE THREAD

**Issue by yangwc** [micropython/micropython#7516]
When I using the mpremote tool, must specify the port number in every instruction at every time. Otherwise, it can't work. 
Only if the port number is specified, it works OK, the mpremote version is 0.0.5, python version is 3.6 
![image](https://user-images.githubusercontent.com/10265618/125024305-15890080-e0b3-11eb-86c4-4e37fed7bbbc.png)

**Comment by peterhinch** [comment]
Perhaps you could provide more details: what OS you're running and what target you are connecting to. I regularly connect to RP2, ESP32 and Pyboards under Linux with:
```bash
$ mpremote mount .
```

**Comment by dpgeorge** [comment]
`mpremote` has been updated to 0.2.0.  Please try again with the latest version, it should be working.
