### ISSUE TITLE
Missing support for seek direction in mpremote RemoteFile

### ISSUE THREAD

**Issue by maruno** [micropython/micropython#7534]
Normally one can provide an argument for the seek-direction when using a file's `seek`-method, e.g.:
```python
SEEK_END = const(2)

with open('/remote/some_file', 'rb') as f:
    f.seek(-FOOTER_SIZE, SEEK_END)
```

Unfortunately when using mpremote's mount feature this doesn't work on the `RemoteFile` objects:
```TypeError: function takes 2 positional arguments but 3 were given```

**Comment by dpgeorge** [comment]
Fixed by 7870ec03701eb0bac44edf8c98e367a669918658
