### ISSUE TITLE
How to run CPP code from micropython in ESP32 ?

### ISSUE THREAD

**Issue by Prabhuelectro** [micropython/micropython#7566]
I have some CPP code for ESP32 and need to run from micropython. like, call an external program with os. system function. Is it possible to call the binary file from micropython?

**Comment by mocleiri** [comment]
micropython is written in C so needs to call C methods but you can call C++ code from within those methods.

I suggest you read the manual page about C/C++ modules and native modules (which have linker restrictions)
https://docs.micropython.org/en/latest/develop/extendingmicropython.html

https://github.com/micropython/micropython/tree/master/examples/usercmodule/cppexample
