### ISSUE TITLE
Inline assembler: unknown problem with passed in values

### ISSUE THREAD

**Issue by PinkInk** [micropython/micropython#760]
First post of this disappeared into history with my response to closure of #753 - believe there's a problem with the wrapper around inline assembler, the following examples cause the pyboard to crash;

    @micropython.asm_thumb
    def peek(r0):
      ldr(r0, [r0, stm.GPIO_MODER])
    >>> peek(stm.GPIOA)
     ***crash***
 
    @micropython.asm_thumb
    def peek(r0, r1):
      orr(r0, r1)
      ldr(r0, [r0, 0])
    >>> peek(stm.GPIOA, stm.GPIO_MODER)
    ***crash***

(ref http://forum.micropython.org/viewtopic.php?f=2&t=216 for precursor tests that, I believe, indicate that they shouldn't).

**Comment by pfalcon** [comment]
Assuming the issue was clarified, closing. Please reopen with additional data if needed.
