### ISSUE TITLE
mpremote requires documentation

### ISSUE THREAD

**Issue by mattytrentini** [micropython/micropython#7600]
The `mpremote` tool is currently not documented in the [official MicroPython docs](https://docs.micropython.org/en/latest/). It would be helpful to many users to see this useful tool well-documented.

`docs/reference/mpremote.rst` should be created and, as a starting point, the contents of [mpremote/README.md](https://github.com/micropython/micropython/tree/master/tools/mpremote) can be used.

**Comment by dpgeorge** [comment]
Done in 135339ce3ab8a50ae5160d1d84062475baeb1798
