### ISSUE TITLE
Daily Builds stopped on July 22nd, 2021

### ISSUE THREAD

**Issue by robert-hh** [micropython/micropython#7609]
No more daily builds since then.

**Comment by pidou46** [comment]
July 22nd, I would say
At least for ESP32:
GENERIC : esp32-20210722-unstable-v1.16-121-g7649f5fbd-dirty.bin

**Comment by dpgeorge** [comment]
Thanks for the report, it's due to 0256e1ab8b8ca376a9c4da83e375ff01ce1b8af0.  Should be fixed now, next build is in progress.

**Comment by dpgeorge** [comment]
It should be fixed (again), by commit ed42002c398d00d4f3753fbeec861f1c4db9fc24
