### ISSUE TITLE
ESP32S2 Pins greater than or equal to 34 cannot be set as output

### ISSUE THREAD

**Issue by wangshujun-tj** [micropython/micropython#7631]
machine_pin_obj_init_helper Judgment is only performed for esp32, not for esp32s2

I can solve it according to the following modifications

    // configure mode
    if (args[ARG_mode].u_obj != mp_const_none) {
        mp_int_t pin_io_mode = mp_obj_get_int(args[ARG_mode].u_obj);
        
        #if CONFIG_IDF_TARGET_ESP32
        if (self->id >= 34 && (pin_io_mode & GPIO_MODE_DEF_OUTPUT)) {
        #elif CONFIG_IDF_TARGET_ESP32S2 || CONFIG_IDF_TARGET_ESP32S3
        if (self->id >= 46 && (pin_io_mode & GPIO_MODE_DEF_OUTPUT)) {
        #endif
        
            mp_raise_ValueError(MP_ERROR_TEXT("pin can only be input"));
        } else {
            gpio_set_direction(self->id, pin_io_mode);
        }

**Comment by dpgeorge** [comment]
Thanks for the report, see a fix in #7671.
