### ISSUE TITLE
[Board/Arduino Nano RP2040 Connect] Adding the first rp2 board with wifi.

### ISSUE THREAD

**Issue by Cellebyte** [micropython/micropython#7634]
Hey could someone advice me of getting this board onboarded with micropython?

I wrote me an neopixel implementation but now I am struggeling with the missing WIFI.

That's what I found in the circuitpython project. But sadly circuitpython does not support `uasyncio`.
```c
USB_VID = 0x239A
USB_PID = 0x00CF

USB_PRODUCT = "Arduino Nano RP2040 Connect"
USB_MANUFACTURER = "Arduino"

CHIP_VARIANT = RP2040
CHIP_FAMILY = rp2

EXTERNAL_FLASH_DEVICES = "AT25SF128A, IS25LP128F"

CIRCUITPY__EVE = 1
```

**Comment by dpgeorge** [comment]
This board is now supported.  Builds for it should appear in the download page https://micropython.org/download/ARDUINO_NANO_RP2040_CONNECT/ in about 10 hours.
