### ISSUE TITLE
Does pyb's PWM support center symmetry?

### ISSUE THREAD

**Issue by china-zhangdj** [micropython/micropython#7684]
Hello everyone, I tried to implement the FOC controller through micropython, but I got stuck in the SVPWM module. I need pyb's PWM output to have a symmetrical waveform to achieve seven-segment wave transmission. What should I do? .

**Comment by dpgeorge** [comment]
It should work by using the CENTER mode for counting, eg: `pyb.Timer(..., mode=pyb.Timer.CENTER, ...)`

**Comment by china-zhangdj** [comment]
https://github.com/micropython/micropython/issues/7684#issuecomment-901932432
Thank you very much.
