### ISSUE TITLE
pyboard.py only run in python3.9

### ISSUE THREAD

**Issue by iz4blue** [micropython/micropython#7700]
Hello.

https://github.com/micropython/micropython/blame/master/tools/pyboard.py#L662
This commit creates a constraint on python3.9 .

<img width="823" alt="Screen Shot 2021-08-24 at 14 13 54" src="https://user-images.githubusercontent.com/979297/130559571-6c057f8a-8304-44a1-817f-815cc7df8a19.png">

Python 3.9 is so up to date that I try to register issue.

Thank you for reading.

**Comment by jimmo** [comment]
Thanks -- created #7701 to fix.

**Comment by dpgeorge** [comment]
Fixed by 145fedef8d74a504c4b7c000e6c305602d07feff
