### ISSUE TITLE
Build for UM_FEATHERS2 fails: Missing include file from usb.c

### ISSUE THREAD

**Issue by Maddox-zephyr** [micropython/micropython#7708]
There is a missing include file that is referenced in usb.c:

        "/micropython/ports/esp32/usb.c:34:10: fatal error: tusb_cdc_acm.h: No such file or directory
         #include "tusb_cdc_acm.h"
                  ^~~~~~~~~~~~~~~~
        compilation terminated.`
        
Checking usb.c, it is indeed trying to include "tusb_cdc_acm.h"
       `#include "py/runtime.h"
	#include "py/mphal.h"
	#include "usb.h"

	#if CONFIG_USB_ENABLED

	#include "tinyusb.h"
	#include "tusb_cdc_acm.h"`

the command I used to build:  make BOARD=UM_FEATHERS2

Short term, I can stick the include file in the directory (where can I find this include file?).  Long term, it should be part of the build source.

Cheers,

Bruce

**Comment by UnexpectedMaker** [comment]
I've added a PR that adds required IDF versions for S2, C3 and S3 to the readme, so we should close this again @Maddox-zephyr 
https://github.com/micropython/micropython/pull/7822

@mcauser if you still want more info in the releases changelog, feel free to open an issue specific to that :)
