### ISSUE TITLE
AP ESP32-S2 Denied Access To Network

### ISSUE THREAD

**Issue by moefear85** [micropython/micropython#7719]
Hello,

I'm using micropython v1.16 with an esp32-s2. I'm trying to setup webrepl. For this, I'm trying to setup the esp32 as an access point. But nothing is able to connect to it. Everything is getting "Denied Access To Network", irrespective if I have a password set or using an open network. I'm using the following code in boot.py:

import network
ap = network.WLAN(network.AP_IF)
ap.config(essid="moefear85", password="********")
ap.active(True)
print(ap.ifconfig())
import webrepl
webrepl.start()

Update: I've tried setting the authmode parameter, I tried AUTH_WPA_PSK, AUTH_WPA2_PSK, and AUTH_OPEN, all with and without setting the password parameter. Nothing helps.

Moreover, when attempting to connect to my smartphone's hotspot from the esp32, using station mode, I get "OSError: Wifi Internal Error". calling "scan()" returns an empty list.

I tried a precompiled binary I found on the net, with version 1.15 for esp32s2. When attempting scan(), I get "RuntimeError: Wifi Unknown Error 0x0102".

**Comment by dpgeorge** [comment]
I looked into this and the issue seems to be that the ESP32-S2 runs out of (IDF) memory and so cannot accept any incoming WiFi connections.

I assume you're using the `GENERIC_S2` board?  On a board with external SPIRAM the AP works because there is enough memory.

To fix it requires reducing the amount of memory used by the MicroPython heap.  Reducing it by 32k seems to work, ie in `main.c`:
```
size_t mp_task_heap_size = heap_caps_get_largest_free_block(MALLOC_CAP_8BIT) - 32*1024;
```

**Comment by Wind-stormger** [comment]
Before looking for software problems, you can check for hardware problems, such as whether the wifi power supply is good.

If you have a voltmeter and know how to use it, it is recommended that you measure whether the VDD3P3 pin of the EPS32 chip has a voltage of 3.3V. 

If there is an abnormality here, this error will be reported.

Please refer to the chip data sheet for the VDD3P3 pin.

I have encountered such a problem, I hope it can provide an idea for people looking for a solution.

**Comment by moefear85** [comment]
@dpgeorge 

thx for finding the cause of the problem. Yeah I was using a GENERIC_S2 board. I guess this should be closed now.

@ Wind-stormger
No it's not a hardware problem.
