### ISSUE TITLE
ESP32-S2 + PSRAM

### ISSUE THREAD

**Issue by moefear85** [micropython/micropython#7733]
I read through the open issues.. I found alot on esp32-s2 support, some mention PSRAM, but none mention how to configure the build to get it working, or if that is necessary.

So.. I don't know where else to ask this... is it possible to compile MP for ESP32-S2 with (2MB) PSRAM enabled? If so, what is the exact command line? In the boards folder under esp32, I see "GENERIC_SPIRAM" and "GENERIC_S2", but no "GENERIC_S2_SPIRAM".

**Comment by dpgeorge** [comment]
It might be enough to include `boards/sdkconfig.spiram` in the `set(SDKCONFIG_DEFAULTS ...)` part of your `mpconfigboard.cmake` file.

**Comment by moefear85** [comment]
thx I'll give it a try... it leaves the question though, how would I know for sure after flashing that psram is enabled and being used?

currently cloning the latest master, to see if esp32s2 wifi works

**Comment by dpgeorge** [comment]
> how would I know for sure after flashing that psram is enabled and being used?

Run:
```
>>> import micropython
>>> micropython.mem_info()
```
It will tell you how big the heap is.
