### ISSUE TITLE
Serial keeps outputting after Ctrl+C

### ISSUE THREAD

**Issue by moefear85** [micropython/micropython#7734]
Sometimes I print debug info to Serial in a very tight loop, causing buffers to fill up. Thus after pressing Ctrl+C to end the running code, it can take up to even 20 seconds before the board responds. I'm not sure if micropython is simply caught up, but I assume it has long since processed and responded to the Ctrl+C and terminated the program, but continues to send all the "pent-up" data out over serial. The same might be happening on the PC side, so I'm not sure whether this should be a micropython issue or not.

But, is it possible, after micropython sees a Ctrl+C, that it immediately discard everything in the output buffer, since usually by the time someone presses Ctrl+C, they are no longer interested in the rest of the serial output.

**Comment by dpgeorge** [comment]
The serial output buffer of the device (you didn't specify which one you are using though) is probably not very large, and MicroPython will stop printing as soon as it receives ctrl-C.  So the issue is likely on the PC side.

**Comment by moefear85** [comment]
ah ok... I'll double check then thx. It happens really with any esp (8266,32,s2...).

**Comment by dpgeorge** [comment]
If you can provide instructions to reproduce the issue then we could check if it's really a problem with the board (as opposed to the PC).
