### ISSUE TITLE
pyb.usb_mode(None) It doesn't work. After the execution, the USB mode is switched from VCP+MSC to MSC. How to temporarily disable the USB function?

### ISSUE THREAD

**Issue by china-zhangdj** [micropython/micropython#7740]
pyb.usb_mode([modestr, ]port=-1, vid=0xf055, pid=-1, msc=(), hid=pyb.hid_mouse, high_speed=False)
If called with no arguments, return the current USB mode as a string.

If called with modestr provided, attempts to configure the USB mode. The following values of modestr are understood:

How to understand "attempts "?

**Comment by dpgeorge** [comment]
> How to understand "attempts "?

The configuration may fail in which case it will raise an exception.  Also, it can only switch if currently disabled, so if it's enabled you need to do:
```
pyb.usb_mode(None)
pyb.usb_mode('VCP')
```

> pyb.usb_mode(None) It doesn't work

Can you please provide more detail about why it doesn't work, what board you use, what version of the firmware, and what Python code you run.

**Comment by china-zhangdj** [comment]
I am using STM32F401CC board, compiled firmware V1.12, the code is simple

```python
import pyb
pyb.usb_mode(None)
pyb.usb_mode("VCP")
pyb.usb_mode()

Returned "MSC"
```

**Comment by dpgeorge** [comment]
It should be working... can you try the latest v1.17 MicroPython?  Then run (you'll need a UART REPL because USB will go down):
```python
import pyb
print(pyb.usb_mode())
pyb.usb_mode(None)
print(pyb.usb_mode())
pyb.usb_mode("VCP")
print(pyb.usb_mode())
```

**Comment by china-zhangdj** [comment]
Thank you very much, although the query did not become "None", it did realize the mode switching function.
```python
MicroPython v1.17 on 2021-09-06; XiangChen_Core with STM32F401VC
Type "help()" for more information.
>>> import pyb
>>> pyb.usb_mode()
'VCP+MSC'
>>> pyb.usb_mode(None)
>>> pyb.usb_mode()
'VCP+MSC'
>>>
>>>
>>> pyb.usb_mode("VCP")
>>> pyb.usb_mode()
'VCP'
>>> pyb.usb_mode(None)
>>> pyb.usb_mode("MSC")
>>>

```
