### ISSUE TITLE
WLAN.config("mac") printing MAC incorrectly

### ISSUE THREAD

**Issue by moefear85** [micropython/micropython#7745]
Hello,

I'm using an ESP32-S2-Wroom-I. When I create a station or ap using for example:

sta = network.WLAN(network.STA_IF)

and then try to read the mac address using:

sta.config("mac")

it prints b'|\xdf\xa1\x03B.' even though the mac address is:  7c:df:a1:03:42:2e. in other words, it is displaying the 2nd, 3rd, and 4th bytes as the MAC. I don't see any perspective in which this would be correct/useful. Am I missing something?

**Comment by robert-hh** [comment]
b'|\xdf\xa1\x03B.' is the proper MAC address. The ASCII code of '|' is 0x7c, 'B' is 0x42, '.' is 0x2e. That's the way Python prints byte strings. If you want a nice HEX representation, you havee to use binascii.hexlify() for converting the representation.
Note: Question like these are better asked at the MicroPython forum: https://forum.micropython.org. There, you can as well search for answers.
