### ISSUE TITLE
rp2: MICROPY_PY_UHEAPQ is missing

### ISSUE THREAD

**Issue by yjchun** [micropython/micropython#7746]
Hello..
Found heapq module was missing in rp2 port.
/ports/rp2/mpconfigport.h did not have MICROPY_PY_UHEAPQ included.
Enabling MICROPY_PY_UHEAPQ seems working fine in simple test.

I am not sure if MICROPY_PY_UHEAPQ is intentionally opted out or just not included by mistake.
Thanks.

**Comment by dpgeorge** [comment]
I think this is just a mistake.  It should be included to match esp32 and stm32.

**Comment by dpgeorge** [comment]
Fixed by bbbdef4cc1d2cb3a3f6c2d067b6988534773b2a6
