### ISSUE TITLE
mpremote cannot create subfolders in a mounted folder - Windows

### ISSUE THREAD

**Issue by Josverl** [micropython/micropython#7758]
When using mpremote on Windows it appears not to be able to create directories in a mounted folder.
Minimal repro: 
```  
(.venv) PS C:\develop\MyPython\micropython-stubber\board> 
mpremote mount . exec "import os;os.mkdir('spam')" 
Local directory . is mounted at /remote
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'RemoteFS' object has no attribute 'mkdir'
(.venv) PS C:\develop\MyPython\micropython-stubber\board> 
```
and similar issues rise when importing a module that tries to create subfolders.
looking at the [code](https://github.com/micropython/micropython/blob/226c0341ca78086b98f802d26f61220a2c19ffef/tools/mpremote/mpremote/pyboardextended.py#L221) indeed no **mkdir**  method has been implemented.
Is this intentional , or something that could be added ?

- mpremote  0.0.6
- micropython v1.17 
- OS: Windows_NT x64 10.0.22000

**Comment by dpgeorge** [comment]
`mkdir` and `rmdir` were added to `mpremote` in 7566d107d5acc82a45df0dd5c5803bf5d2564043
