### ISSUE TITLE
How to speed up the startup speed of micropython on ESP32.

### ISSUE THREAD

**Issue by china-zhangdj** [micropython/micropython#7761]
I run lv_micropython on the ESP32 for GUI development, but it takes 5 seconds or more to run the script every time I boot up, how can I start it quickly?
Thank you for your help.

**Comment by dpgeorge** [comment]
This question is better suited to https://forum.micropython.org.

Briefly: you could precompile the .py files to .mpy, or freeze the Python code into the firmware.
