### ISSUE TITLE
ESP32: make does not recompile changed files from ports/esp32/modules

### ISSUE THREAD

**Issue by IhorNehrutsa** [micropython/micropython#7815]
make (mpy-cross) does not recompile changed files from ports/esp32/modules 

It does not recompile files from ports/esp32/modules even when delete output directory
  ports/esp32/build-GENERIC/frozen_mpy/

**Comment by embeddedt** [comment]
This seems to be the same issue as #7753.

**Comment by IhorNehrutsa** [comment]
Yes, it is the same issue as #7753
