### ISSUE TITLE
V1.17 threading versions Error running reset production mode

### ISSUE THREAD

**Issue by Spring641** [micropython/micropython#7816]
In the thread version of the latest firmware V1.17, pressing the USR button to reset the system after the system starts will cause the system to crash! According to my current debugging code, I found that the execution of mp_hal_delay_ms() in the thread version code will cause the system to crash.

**Comment by CaptainJackey** [comment]
v1.16 is ok, v1.17's thread has bug. 

version : threading: v1.17-47-gb326edf68 (latest)

**Factory reset the filesystem invalid ， please cheak!**

**Comment by IlysvlVEizbr** [comment]
In v1.18 the bug is still exist.
Safe mode & Factory reset the filesystem function of pyboard cannot be used

**Comment by CaptainJackey** [comment]
> o

Yes, For the threading firmware.  Normal firmware is OK! @dpgeorge

**Comment by jimmo** [comment]
I was able to repro this -- the threading firmware seems fine and passes the unit tests, but the safe-mode boot sequence is failing.

You're right, the culprit is `mp_hal_delay_ms`. PR incoming.
