### ISSUE TITLE
Code formatters

### ISSUE THREAD

**Issue by IhorNehrutsa** [micropython/micropython#7829]
Which **C** and **Python** code formatters are used in Micropython?
If they are used, how to run them locally?

If nothing, then I suggest using
[Clang formatted for C and C++ source code](https://clang.llvm.org/docs/ClangFormat.html)
[Yapf for Python source code](https://github.com/google/yapf)

**Comment by dlech** [comment]
uncrustify and black plus some custom fixups

Use [./tools/codeformat.py](https://github.com/micropython/micropython/blob/master/tools/codeformat.py) to run locally

**Comment by IhorNehrutsa** [comment]
@dlech Thank you.
