### ISSUE TITLE
Framebuf module: Test are sloppy

### ISSUE THREAD

**Issue by volkerjaenisch** [micropython/micropython#7843]
Dear Micropython developers!

Writing tests for my new function [Framebuffer.get_rect(x,y,w,h)](https://github.com/Inqbus/micropython/blob/master/extmod/modframebuf.c) I oriented myself (as a newcomer) on existing tests: Go to Rome - behave like a Roman.

I was a bit disappointed by the tests for the framebuffer code.

Looking at 

https://github.com/micropython/micropython/blob/master/tests/extmod/framebuf1.py

```
w = 5
h = 16
size = w * h // 8
buf = bytearray(size)
maps = {
    framebuf.MONO_VLSB: "MONO_VLSB",
    framebuf.MONO_HLSB: "MONO_HLSB",
    framebuf.MONO_HMSB: "MONO_HMSB",
}
```

This code runs. But it is wrong if anybody changes the parameters w and h. It only runs correctly if h is a multiple of 8.

This is because here were tests for horizontal as well as vertical pixel orientation mixed together in one function.

For horizontal pixels it has to be
size =  w // 8 * h 
and for vertical pixels it has to be
size =  w * h //  8

And I asked myself:
- Why did anybody test a single buffer size?
- And why a buffer where one boundary is a power of 2?

Then I started to implement my tests - ongoing!
My parametrized tests have found at least six really nasty errors in my own function and in the tests. Bit banging is error prone!

Cheers,
Volker

**Comment by jonnor** [comment]
Hi and thank you for the comments.
Code contributions for improving tests, especially things that uncover and fixes bugs are welcome. Additive or minor changes are best done by just opening a merge request.
