### ISSUE TITLE
port-unix: Standard variant missing basic os functionality

### ISSUE THREAD

**Issue by mikebentley15** [micropython/micropython#7875]
The `os` module in the standard variant, commonly distributed when installing micropython through package managers such as `conda` or `pamac`, is missing key functionality.

```
>>> import os
>>> dir(os)
['__class__', '__name__', 'remove', 'errno', 'getenv', 'ilistdir', 'mkdir', 'putenv', 'rename', 'rmdir', 'stat', 'statvfs', 'system', 'unsetenv']
```

Notable omissions are `getcwd`, `chdir`, and `listdir`

I see these can be enabled by adding the following to `ports/unix/variants/standard/mpconfigvariants.h`

```
#define MICROPY_READER_VFS                      (1)
#define MICROPY_VFS                             (1)
#define MICROPY_VFS_POSIX                       (1)
#define MICROPY_PY_UOS_VFS                      (1)

#define mp_import_stat mp_vfs_import_stat
#define mp_builtin_open mp_vfs_open
#define mp_builtin_open_obj mp_vfs_open_obj
```

**Question:** is there a reason this is disabled by default?

**Comment by dpgeorge** [comment]
This has been fixed by 2b409ef8a46015f8f3bd20bc44e644637dbe9bd3 (all unix variants now use VFS).
