### ISSUE TITLE
Micropython to LOM204 (stm32L071CZ + SX1276)

### ISSUE THREAD

**Issue by tcpipchip** [micropython/micropython#7885]
Sir,
I am finishing the porting the Micropython to LOM204 LORAWAN module.
I have a first question, where is the the config file that define wich are the the TXD and RXD gpio used to make the Micropython console interface ?
Thank so so much!
Thanks!

**Comment by jonnor** [comment]
Board configuration, such as USART RX/TX can be found under ports/stm32/boards .
Which USART is used for the console is controlled by MICROPY_HW_UART_REPL
For example here is a similar chip, https://github.com/micropython/micropython/blob/master/ports/stm32/boards/B_L072Z_LRWAN1/mpconfigboard.h
