### ISSUE TITLE
RP2: time.localtime day of week is wrong

### ISSUE THREAD

**Issue by peterhinch** [micropython/micropython#7889]
This cropped up in [the forum](https://forum.micropython.org/viewtopic.php?f=21&t=11211#p61568). On CPython, the Unix build and a Pyboard the day of the week is correctly reported today as 5 (Saturday). On Pico it is 4:
```python
MicroPython v1.17 on 2021-09-07; Raspberry Pi Pico with RP2040
Type "help()" for more information.
>>> 
>>> import time
>>> time.localtime()
(2021, 10, 9, 12, 1, 33, 4, 282)
```

**Comment by scruss** [comment]
and yet the RP2040's RTC gets the day correct:

    MicroPython v1.17 on 2021-09-02; Raspberry Pi Pico with RP2040
    Type "help()" for more information.
    >>> import time
    >>> from machine import RTC
    >>> r=RTC()
    >>> time.localtime()
    (2021, 10, 30, 21, 52, 1, 4, 303)
    >>> r.datetime()
    (2021, 10, 30, 5, 21, 52, 2, 0)

**Comment by dpgeorge** [comment]
See #8250 for a fix.

**Comment by dpgeorge** [comment]
Fixed by 5679fe6aee7811447ab9dfc9b4539526b23b1d84

**Comment by mchobby** [comment]
Hi, while testing a RTC module, I discovered an inconsistancy with time.localtime().
time.localtime() doesn't place the proper "Hour" data at position 3 of returned tuple.
**Issue should be reopen**

# tested with RP2 (pico RP2040)

MicroPython v1.27.0
MicroPython v1.28.0
MicroPython v1.29.0-preview.627.g8250ff1c11 on 2026-07-26

# Example - Python vs MicroPython
Let's get this fixed value for my local time (I just grab it for comparison).

`_time = 1785291456 `

Python returns this:

```
Python 3.6.9 (default, Mar 10 2023, 16:46:00) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.4.0 -- An enhanced Interactive Python. Type '?' for help.
In [1]: _time = 1785291456                                                      
In [2]: import time                                                             
In [3]: time.localtime( _time )                                                 
Out[3]: time.struct_time(tm_year=2026, tm_mon=7, tm_mday=29, tm_hour=4, tm_min=17, tm_sec=36, tm_wday=2, tm_yday=210, tm_isdst=1)
```
Date is correct.
Time is correct, it is 17h17m36s with GMT+1, si 4PM 17m 36s is good.

Now with micropython:

```
MicroPython v1.29.0-preview.627.g8250ff1c11 on 2026-07-26; Raspberry Pi Pico with RP2040
Type "help()" for more information.
>>> _time = 1785291456
>>> import time
>>> time.localtime( _time )
(2026, 7, 29, 2, 17, 36, 2, 210)

```

Position 3 of tuple (value "2" after the "29") is not the Hours but appears to be the WeekDay (as position 6).
Position 4  & 5 looks goods (the minutes followed by the seconds).

Cheers,
Dominique

**Comment by agatti** [comment]
@mchobby isn't this already covered by #4394?

**Comment by mchobby** [comment]
@agatti, #4394 looks to be a ESP32 port. I noticed my issue in the RP2 port.
If you have a Pico/RP2040 under the hand, it would be a great to confirm the finding.

**Comment by agatti** [comment]
The implementation looks identical in those two ports, look at `ports/esp32/modtime.c` and `ports/rp2/modtime.c`.  Ultimately the change should be made in either `shared/timeutils` or in `extmod/modtime.c`, and that will impact pretty much all ports.

**Comment by scruss** [comment]
> time.localtime() doesn't place the proper "Hour" data at position 3 of returned tuple.

No, it's doing the right thing, as long as you understand that MicroPython isn't TZ-aware

Let's take a look at your chosen timestamp of 1785291456 in an unambiguous way:

```bash
LANG=en_DK.UTF-8 TZ=UTC date --date='@1785291456'
2026-07-29T02:17:36 UTC
```

In CPython:

```bash
TZ=UTC python3
Python 3.13.5 (main, Jul 15 2026, 20:25:40) [GCC 14.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> _time=1785291456
>>> import time
>>> time.localtime(_time)
time.struct_time(tm_year=2026, tm_mon=7, tm_mday=29, tm_hour=2, tm_min=17, tm_sec=36, tm_wday=2, tm_yday=210, tm_isdst=0)
```

In MicroPython on RP2350:

```
MicroPython v1.28.0 on 2026-04-06; Raspberry Pi Pico 2 W with RP2350
Type "help()" for more information.
>>> _time=1785291456
>>> import time
>>> time.localtime(_time)
(2026, 7, 29, 2, 17, 36, 2, 210)
```

The 2 we're seeing in position 4 (starting from 1) isn't _tm_wday_, it's the _tm_hour_ of 02:17 UTC.

**Comment by mchobby** [comment]
Thanks all for your answers. I finally understand what looks wrong to me (I was dealing with machine.RTC, an external PCF8523 RTC and time.localtime().

time.localtime(x) returns the following format  (Year, month, day, hour, min, sec, weekday, yearday)

whereas 

machine.RTC().datetime() returns the following format (Year, Month, Day, WeekDay, hour, min, sec, ms) also named "datetimetuple" format

This has been very confusing... but it is fine right now.
Sorry for the annoyance.
Regards,
Dominique
