### ISSUE TITLE
unix make fails

### ISSUE THREAD

**Issue by mrharmtz** [micropython/micropython#7900]
attempted to build micropython(hash: e87b2e8bfa71a09f0fe585fc0127e9fa42b68f19) for unix on virtual ubuntu 18.04.6 LTS machine
gcc: 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)
build-essential: 12.4ubuntu1.
libffi-dev: 3.2.1-8.
pkg-config: 0.29.1-0ubuntu2.
git: 12.17.1-1ubuntu0.9.
python: 3.6.9

fails on making "modbtree.c".

thank you
code below the build that fails

`gcc -I../../lib/berkeley-db-1.xx/PORT/include -I. -I../.. -Ibuild-standard -I../../shared/readline -Wall -Werror -Wextra -Wno-unused-parameter -Wpointer-arith -Wdouble-promotion -Wfloat-conversion -std=gnu99 -DUNIX -DFFCONF_H=\"lib/oofatfs/ffconf.h\" -DMICROPY_PY_USSL=1 -DMICROPY_SSL_AXTLS=1 -I../../lib/axtls/ssl -I../../lib/axtls/crypto -I../../extmod/axtls-include -DMICROPY_PY_BTREE=1 -DMICROPY_USE_READLINE=1 -DMICROPY_PY_TERMIOS=1 -DMICROPY_PY_SOCKET=1 -DMICROPY_PY_THREAD=1 -DMICROPY_PY_THREAD_GIL=0  -DMICROPY_PY_FFI=1 -Os -DNDEBUG -fdata-sections -ffunction-sections -Ivariants/standard  -g -U _FORTIFY_SOURCE -DMICROPY_QSTR_EXTRA_POOL=mp_qstr_frozen_const_pool -DMICROPY_MODULE_FROZEN_MPY -DMPZ_DIG_SIZE=16  -DMICROPY_MODULE_FROZEN_STR -D__DBINTERFACE_PRIVATE=1 -Dmpool_error=printf -Dabort=abort_ "-Dvirt_fd_t=void*"  -c -MD -o build-standard/extmod/modbtree.o ../../extmod/modbtree.c
In file included from ../../extmod/modbtree.c:37:0:
../../lib/berkeley-db-1.xx/PORT/include/db.h:1:1: error: expected identifier or ‘(’ before ‘.’ token
 ../../include/db.h
 ^
In file included from ../../extmod/modbtree.c:38:0:
../../lib/berkeley-db-1.xx/PORT/include/../../btree/btree.h:89:3: error: data definition has no type or storage class [-Werror]
 } PAGE;
   ^~~~
../../lib/berkeley-db-1.xx/PORT/include/../../btree/btree.h:89:3: error: type defaults to ‘int’ in declaration of ‘PAGE’ [-Werror=implicit-int]
../../lib/berkeley-db-1.xx/PORT/include/../../btree/btree.h:127:2: error: unknown type name ‘pgno_t’
  pgno_t pgno;   /* page number stored on */
  ^~~~~~
../../lib/berkeley-db-1.xx/PORT/include/../../btree/btree.h:157:2: error: unknown type name ‘recno_t’
  recno_t nrecs;   /* number of records */
  ^~~~~~~
../../lib/berkeley-db-1.xx/PORT/include/../../btree/btree.h:158:2: error: unknown type name ‘pgno_t’
  pgno_t pgno;   /* page number stored below */
  ^~~~~~
../../lib/berkeley-db-1.xx/PORT/include/../../btree/btree.h:247:2: error: unknown type name ‘pgno_t’
  pgno_t pgno;   /* the page number */
  ^~~~~~
../../lib/berkeley-db-1.xx/PORT/include/../../btree/btree.h:248:2: error: unknown type name ‘indx_t’
  indx_t index;   /* the index on the page */
  ^~~~~~
../../lib/berkeley-db-1.xx/PORT/include/../../btree/btree.h:252:2: error: expected specifier-qualifier-list before ‘PAGE’
  PAGE *page;   /* the (pinned) page */
  ^~~~
../../lib/berkeley-db-1.xx/PORT/include/../../btree/btree.h:282:2: error: unknown type name ‘DBT’
  DBT  key;   /* B: Saved key, or key.data == NULL. */
  ^~~
../../lib/berkeley-db-1.xx/PORT/include/../../btree/btree.h:283:2: error: unknown type name ‘recno_t’
  recno_t  rcursor;  /* R: recno cursor (1-based) */
  ^~~~~~~
../../lib/berkeley-db-1.xx/PORT/include/../../btree/btree.h:310:2: error: unknown type name ‘MPOOL’
  MPOOL  *bt_mp;  /* memory pool cookie */
  ^~~~~
../../lib/berkeley-db-1.xx/PORT/include/../../btree/btree.h:312:2: error: unknown type name ‘DB’
  DB  *bt_dbp;  /* pointer to enclosing DB */
  ^~
../../lib/berkeley-db-1.xx/PORT/include/../../btree/btree.h:315:2: error: expected specifier-qualifier-list before ‘PAGE’
  PAGE  *bt_pinned;  /* page pinned across calls */
  ^~~~
In file included from /usr/include/features.h:424:0,
                 from /usr/include/x86_64-linux-gnu/bits/libc-header-start.h:33,
                 from /usr/include/stdio.h:27,
                 from ../../extmod/modbtree.c:27:
../../lib/berkeley-db-1.xx/PORT/include/../../btree/extern.h:36:22: error: unknown type name ‘DB’
 int  __bt_close __P((DB *));
                      ^
../../lib/berkeley-db-1.xx/PORT/include/../../btree/extern.h:37:35: error: unknown type name ‘DBT’
 int  __bt_cmp __P((BTREE *, const DBT *, EPG *));
                                   ^
../../lib/berkeley-db-1.xx/PORT/include/../../btree/extern.h:39:29: error: unknown type name ‘DBT’
 int  __bt_defcmp __P((const DBT *, const DBT *));
                             ^
../../lib/berkeley-db-1.xx/PORT/include/../../btree/extern.h:39:42: error: unknown type name ‘DBT’
 int  __bt_defcmp __P((const DBT *, const DBT *));
                                          ^
../../lib/berkeley-db-1.xx/PORT/include/../../btree/extern.h:40:32: error: unknown type name ‘DBT’
 size_t  __bt_defpfx __P((const DBT *, const DBT *));
                                ^
../../lib/berkeley-db-1.xx/PORT/include/../../btree/extern.h:40:45: error: unknown type name ‘DBT’
 size_t  __bt_defpfx __P((const DBT *, const DBT *));
                                             ^
../../lib/berkeley-db-1.xx/PORT/include/../../btree/extern.h:41:29: error: unknown type name ‘DB’
 int  __bt_delete __P((const DB *, const DBT *, u_int));
                             ^
../../lib/berkeley-db-1.xx/PORT/include/../../btree/extern.h:41:41: error: unknown type name ‘DBT’
 int  __bt_delete __P((const DB *, const DBT *, u_int));
                                         ^
../../lib/berkeley-db-1.xx/PORT/include/../../btree/extern.h:42:37: error: unknown type name ‘DBT’
 int  __bt_dleaf __P((BTREE *, const DBT *, PAGE *, u_int));
                                     ^
../../lib/berkeley-db-1.xx/PORT/include/../../btree/extern.h:42:44: error: expected declaration specifiers or ‘...’ before ‘PAGE’
 int  __bt_dleaf __P((BTREE *, const DBT *, PAGE *, u_int));
                                            ^
../../lib/berkeley-db-1.xx/PORT/include/../../btree/extern.h:43:25: error: unknown type name ‘DB’
 int  __bt_fd __P((const DB *));
                         ^
../../lib/berkeley-db-1.xx/PORT/include/../../btree/extern.h:44:30: error: expected declaration specifiers or ‘...’ before ‘PAGE’
 int  __bt_free __P((BTREE *, PAGE *));
                              ^
../../lib/berkeley-db-1.xx/PORT/include/../../btree/extern.h:45:26: error: unknown type name ‘DB’
 int  __bt_get __P((const DB *, const DBT *, DBT *, u_int));
                          ^
../../lib/berkeley-db-1.xx/PORT/include/../../btree/extern.h:45:38: error: unknown type name ‘DBT’
 int  __bt_get __P((const DB *, const DBT *, DBT *, u_int));
                                      ^
../../lib/berkeley-db-1.xx/PORT/include/../../btree/extern.h:45:45: error: unknown type name ‘DBT’
 int  __bt_get __P((const DB *, const DBT *, DBT *, u_int));
                                             ^
In file included from ../../lib/berkeley-db-1.xx/PORT/include/../../btree/btree.h:388:0,
                 from ../../extmod/modbtree.c:38:
../../lib/berkeley-db-1.xx/PORT/include/../../btree/extern.h:46:1: error: unknown type name ‘PAGE’
 PAGE *__bt_new __P((BTREE *, pgno_t *));
 ^~~~
In file included from /usr/include/features.h:424:0,
                 from /usr/include/x86_64-linux-gnu/bits/libc-header-start.h:33,
                 from /usr/include/stdio.h:27,
                 from ../../extmod/modbtree.c:27:
../../lib/berkeley-db-1.xx/PORT/include/../../btree/extern.h:46:30: error: unknown type name ‘pgno_t’; did you mean ‘ino_t’?
 PAGE *__bt_new __P((BTREE *, pgno_t *));
                              ^
../../lib/berkeley-db-1.xx/PORT/include/../../btree/extern.h:47:30: error: unknown type name ‘pgno_t’; did you mean ‘ino_t’?
 void  __bt_pgin __P((void *, pgno_t, void *));
                              ^
../../lib/berkeley-db-1.xx/PORT/include/../../btree/extern.h:48:31: error: unknown type name ‘pgno_t’; did you mean ‘ino_t’?
 void  __bt_pgout __P((void *, pgno_t, void *));
                               ^
../../lib/berkeley-db-1.xx/PORT/include/../../btree/extern.h:49:30: error: unknown type name ‘pgno_t’; did you mean ‘ino_t’?
 int  __bt_push __P((BTREE *, pgno_t, int));
                              ^
../../lib/berkeley-db-1.xx/PORT/include/../../btree/extern.h:50:26: error: unknown type name ‘DB’
 int  __bt_put __P((const DB *dbp, DBT *, const DBT *, u_int));
                          ^
../../lib/berkeley-db-1.xx/PORT/include/../../btree/extern.h:50:35: error: unknown type name ‘DBT’
 int  __bt_put __P((const DB *dbp, DBT *, const DBT *, u_int));
                                   ^
../../lib/berkeley-db-1.xx/PORT/include/../../btree/extern.h:50:48: error: unknown type name ‘DBT’
 int  __bt_put __P((const DB *dbp, DBT *, const DBT *, u_int));
                                                ^
../../lib/berkeley-db-1.xx/PORT/include/../../btree/extern.h:51:36: error: unknown type name ‘DBT’
 int  __bt_ret __P((BTREE *, EPG *, DBT *, DBT *, DBT *, DBT *, int));
                                    ^
../../lib/berkeley-db-1.xx/PORT/include/../../btree/extern.h:51:43: error: unknown type name ‘DBT’
 int  __bt_ret __P((BTREE *, EPG *, DBT *, DBT *, DBT *, DBT *, int));
                                           ^
../../lib/berkeley-db-1.xx/PORT/include/../../btree/extern.h:51:50: error: unknown type name ‘DBT’
 int  __bt_ret __P((BTREE *, EPG *, DBT *, DBT *, DBT *, DBT *, int));
                                                  ^
../../lib/berkeley-db-1.xx/PORT/include/../../btree/extern.h:51:57: error: unknown type name ‘DBT’
 int  __bt_ret __P((BTREE *, EPG *, DBT *, DBT *, DBT *, DBT *, int));
                                                         ^
../../lib/berkeley-db-1.xx/PORT/include/../../btree/extern.h:52:38: error: unknown type name ‘DBT’
 EPG *__bt_search __P((BTREE *, const DBT *, int *));
                                      ^
../../lib/berkeley-db-1.xx/PORT/include/../../btree/extern.h:53:26: error: unknown type name ‘DB’
 int  __bt_seq __P((const DB *, DBT *, DBT *, u_int));
                          ^
../../lib/berkeley-db-1.xx/PORT/include/../../btree/extern.h:53:32: error: unknown type name ‘DBT’
 int  __bt_seq __P((const DB *, DBT *, DBT *, u_int));
                                ^
../../lib/berkeley-db-1.xx/PORT/include/../../btree/extern.h:53:39: error: unknown type name ‘DBT’
 int  __bt_seq __P((const DB *, DBT *, DBT *, u_int));
                                       ^
../../lib/berkeley-db-1.xx/PORT/include/../../btree/extern.h:54:33: error: unknown type name ‘pgno_t’; did you mean ‘ino_t’?
 void  __bt_setcur __P((BTREE *, pgno_t, u_int));
                                 ^
../../lib/berkeley-db-1.xx/PORT/include/../../btree/extern.h:55:31: error: expected declaration specifiers or ‘...’ before ‘PAGE’
 int  __bt_split __P((BTREE *, PAGE *,
                               ^
../../lib/berkeley-db-1.xx/PORT/include/../../btree/extern.h:56:12: error: unknown type name ‘DBT’
      const DBT *, const DBT *, int, size_t, u_int32_t));
            ^
../../lib/berkeley-db-1.xx/PORT/include/../../btree/extern.h:56:25: error: unknown type name ‘DBT’
      const DBT *, const DBT *, int, size_t, u_int32_t));
                         ^
../../lib/berkeley-db-1.xx/PORT/include/../../btree/extern.h:57:27: error: unknown type name ‘DB’
 int  __bt_sync __P((const DB *, u_int));
                           ^
../../lib/berkeley-db-1.xx/PORT/include/../../btree/extern.h:61:37: error: unknown type name ‘DBT’
 int  __ovfl_put __P((BTREE *, const DBT *, pgno_t *));
                                     ^
../../lib/berkeley-db-1.xx/PORT/include/../../btree/extern.h:61:44: error: unknown type name ‘pgno_t’; did you mean ‘ino_t’?
 int  __ovfl_put __P((BTREE *, const DBT *, pgno_t *));
                                            ^
../../extmod/modbtree.c:43:5: error: unknown type name ‘DB’
     DB *db;
     ^~
../../extmod/modbtree.c:65:16: error: unknown type name ‘DB’
 void __dbpanic(DB *db) {
                ^~
../../extmod/modbtree.c:69:34: error: unknown type name ‘DB’
 STATIC mp_obj_btree_t *btree_new(DB *db, mp_obj_t stream) {
                                  ^~
In file included from ../../py/mpstate.h:35:0,
                 from ../../py/runtime.h:29,
                 from ../../extmod/modbtree.c:32:
../../extmod/modbtree.c: In function ‘btree_close’:
../../extmod/modbtree.c:94:33: error: implicit declaration of function ‘__bt_close’; did you mean ‘__bt_delete’? [-Werror=implicit-function-declaration]
     return MP_OBJ_NEW_SMALL_INT(__bt_close(self->db));
                                 ^
../../py/obj.h:90:67: note: in definition of macro ‘MP_OBJ_NEW_SMALL_INT’
 #define MP_OBJ_NEW_SMALL_INT(small_int) ((mp_obj_t)((((mp_uint_t)(small_int)) << 1) | 1))
                                                                   ^~~~~~~~~
../../extmod/modbtree.c: In function ‘btree_put’:
../../extmod/modbtree.c:101:5: error: unknown type name ‘DBT’
     DBT key, val;
     ^~~
../../extmod/modbtree.c:102:8: error: request for member ‘data’ in something not a structure or union
     key.data = (void *)mp_obj_str_get_data(args[1], &key.size);
        ^
../../extmod/modbtree.c:102:57: error: request for member ‘size’ in something not a structure or union
     key.data = (void *)mp_obj_str_get_data(args[1], &key.size);
                                                         ^
../../extmod/modbtree.c:103:8: error: request for member ‘data’ in something not a structure or union
     val.data = (void *)mp_obj_str_get_data(args[2], &val.size);
        ^
../../extmod/modbtree.c:103:57: error: request for member ‘size’ in something not a structure or union
     val.data = (void *)mp_obj_str_get_data(args[2], &val.size);
                                                         ^
In file included from ../../py/mpstate.h:35:0,
                 from ../../py/runtime.h:29,
                 from ../../extmod/modbtree.c:32:
../../extmod/modbtree.c:104:33: error: implicit declaration of function ‘__bt_put’; did you mean ‘__bt_fd’? [-Werror=implicit-function-declaration]
     return MP_OBJ_NEW_SMALL_INT(__bt_put(self->db, &key, &val, 0));
                                 ^
../../py/obj.h:90:67: note: in definition of macro ‘MP_OBJ_NEW_SMALL_INT’
 #define MP_OBJ_NEW_SMALL_INT(small_int) ((mp_obj_t)((((mp_uint_t)(small_int)) << 1) | 1))
                                                                   ^~~~~~~~~
../../extmod/modbtree.c: In function ‘btree_get’:
../../extmod/modbtree.c:110:5: error: unknown type name ‘DBT’
     DBT key, val;
     ^~~
../../extmod/modbtree.c:111:8: error: request for member ‘data’ in something not a structure or union
     key.data = (void *)mp_obj_str_get_data(args[1], &key.size);
        ^
../../extmod/modbtree.c:111:57: error: request for member ‘size’ in something not a structure or union
     key.data = (void *)mp_obj_str_get_data(args[1], &key.size);
                                                         ^
../../extmod/modbtree.c:112:15: error: implicit declaration of function ‘__bt_get’; did you mean ‘__bt_fd’? [-Werror=implicit-function-declaration]
     int res = __bt_get(self->db, &key, &val, 0);
               ^~~~~~~~
               __bt_fd
../../extmod/modbtree.c:113:16: error: ‘RET_SPECIAL’ undeclared (first use in this function)
     if (res == RET_SPECIAL) {
                ^~~~~~~~~~~
../../extmod/modbtree.c:113:16: note: each undeclared identifier is reported only once for each function it appears in
../../extmod/modbtree.c:61:16: error: ‘RET_ERROR’ undeclared (first use in this function); did you mean ‘CHECK_ERROR’?
     if (res == RET_ERROR) { \
                ^
../../extmod/modbtree.c:120:5: note: in expansion of macro ‘CHECK_ERROR’
     CHECK_ERROR(res);
     ^~~~~~~~~~~
../../extmod/modbtree.c:121:32: error: request for member ‘data’ in something not a structure or union
     return mp_obj_new_bytes(val.data, val.size);
                                ^
../../extmod/modbtree.c:121:42: error: request for member ‘size’ in something not a structure or union
     return mp_obj_new_bytes(val.data, val.size);
                                          ^
../../extmod/modbtree.c: In function ‘btree_seq’:
../../extmod/modbtree.c:128:5: error: unknown type name ‘DBT’
     DBT key, val;
     ^~~
../../extmod/modbtree.c:130:12: error: request for member ‘data’ in something not a structure or union
         key.data = (void *)mp_obj_str_get_data(args[2], &key.size);
            ^
../../extmod/modbtree.c:130:61: error: request for member ‘size’ in something not a structure or union
         key.data = (void *)mp_obj_str_get_data(args[2], &key.size);
                                                             ^
../../extmod/modbtree.c:133:15: error: implicit declaration of function ‘__bt_seq’; did you mean ‘__bt_sync’? [-Werror=implicit-function-declaration]
     int res = __bt_seq(self->db, &key, &val, flags);
               ^~~~~~~~
               __bt_sync
../../extmod/modbtree.c:61:16: error: ‘RET_ERROR’ undeclared (first use in this function); did you mean ‘CHECK_ERROR’?
     if (res == RET_ERROR) { \
                ^
../../extmod/modbtree.c:134:5: note: in expansion of macro ‘CHECK_ERROR’
     CHECK_ERROR(res);
     ^~~~~~~~~~~
../../extmod/modbtree.c:135:16: error: ‘RET_SPECIAL’ undeclared (first use in this function)
     if (res == RET_SPECIAL) {
                ^~~~~~~~~~~
../../extmod/modbtree.c:141:42: error: request for member ‘data’ in something not a structure or union
     pair->items[0] = mp_obj_new_bytes(key.data, key.size);
                                          ^
../../extmod/modbtree.c:141:52: error: request for member ‘size’ in something not a structure or union
     pair->items[0] = mp_obj_new_bytes(key.data, key.size);
                                                    ^
../../extmod/modbtree.c:142:42: error: request for member ‘data’ in something not a structure or union
     pair->items[1] = mp_obj_new_bytes(val.data, val.size);
                                          ^
../../extmod/modbtree.c:142:52: error: request for member ‘size’ in something not a structure or union
     pair->items[1] = mp_obj_new_bytes(val.data, val.size);
                                                    ^
../../extmod/modbtree.c: In function ‘btree_iternext’:
../../extmod/modbtree.c:199:5: error: unknown type name ‘DBT’
     DBT key, val;
     ^~~
../../extmod/modbtree.c:203:21: error: ‘R_FIRST’ undeclared (first use in this function)
         int flags = R_FIRST;
                     ^~~~~~~
../../extmod/modbtree.c:205:16: error: request for member ‘data’ in something not a structure or union
             key.data = (void *)mp_obj_str_get_data(self->start_key, &key.size);
                ^
../../extmod/modbtree.c:205:73: error: request for member ‘size’ in something not a structure or union
             key.data = (void *)mp_obj_str_get_data(self->start_key, &key.size);
                                                                         ^
../../extmod/modbtree.c:206:21: error: ‘R_CURSOR’ undeclared (first use in this function); did you mean ‘CURSOR’?
             flags = R_CURSOR;
                     ^~~~~~~~
                     CURSOR
../../extmod/modbtree.c:208:21: error: ‘R_LAST’ undeclared (first use in this function); did you mean ‘R_FIRST’?
             flags = R_LAST;
                     ^~~~~~
                     R_FIRST
../../extmod/modbtree.c:213:53: error: ‘R_PREV’ undeclared (first use in this function)
         res = __bt_seq(self->db, &key, &val, desc ? R_PREV : R_NEXT);
                                                     ^~~~~~
../../extmod/modbtree.c:213:62: error: ‘R_NEXT’ undeclared (first use in this function); did you mean ‘R_LAST’?
         res = __bt_seq(self->db, &key, &val, desc ? R_PREV : R_NEXT);
                                                              ^~~~~~
                                                              R_LAST
../../extmod/modbtree.c:216:16: error: ‘RET_SPECIAL’ undeclared (first use in this function)
     if (res == RET_SPECIAL) {
                ^~~~~~~~~~~
../../extmod/modbtree.c:61:16: error: ‘RET_ERROR’ undeclared (first use in this function); did you mean ‘CHECK_ERROR’?
     if (res == RET_ERROR) { \
                ^
../../extmod/modbtree.c:219:5: note: in expansion of macro ‘CHECK_ERROR’
     CHECK_ERROR(res);
     ^~~~~~~~~~~
../../extmod/modbtree.c:222:9: error: unknown type name ‘DBT’
         DBT end_key;
         ^~~
../../extmod/modbtree.c:223:16: error: request for member ‘data’ in something not a structure or union
         end_key.data = (void *)mp_obj_str_get_data(self->end_key, &end_key.size);
                ^
../../extmod/modbtree.c:223:75: error: request for member ‘size’ in something not a structure or union
       end_key.data = (void *)mp_obj_str_get_data(self->end_key, &end_key.size);
                                                                         ^
../../extmod/modbtree.c:224:28: error: request for member ‘internal’ in something not a structure or union
         BTREE *t = self->db->internal;
                            ^~
../../extmod/modbtree.c:225:22: error: ‘BTREE {aka struct _btree}’ has no member named ‘bt_cmp’; did you mean ‘bt_mp’?
         int cmp = t->bt_cmp(&key, &end_key);
                      ^~~~~~
                      bt_mp
../../extmod/modbtree.c:240:40: error: request for member ‘data’ in something not a structure or union
             return mp_obj_new_bytes(key.data, key.size);
                                        ^
../../extmod/modbtree.c:240:50: error: request for member ‘size’ in something not a structure or union
             return mp_obj_new_bytes(key.data, key.size);
                                                  ^
../../extmod/modbtree.c:242:40: error: request for member ‘data’ in something not a structure or union
             return mp_obj_new_bytes(val.data, val.size);
                                        ^
../../extmod/modbtree.c:242:50: error: request for member ‘size’ in something not a structure or union
             return mp_obj_new_bytes(val.data, val.size);
                                                  ^
../../extmod/modbtree.c:246:50: error: request for member ‘data’ in something not a structure or union
             pair->items[0] = mp_obj_new_bytes(key.data, key.size);
                                                  ^
../../extmod/modbtree.c:246:60: error: request for member ‘size’ in something not a structure or union
             pair->items[0] = mp_obj_new_bytes(key.data, key.size);
                                                            ^
../../extmod/modbtree.c:247:50: error: request for member ‘data’ in something not a structure or union
             pair->items[1] = mp_obj_new_bytes(val.data, val.size);
                                                  ^
../../extmod/modbtree.c:247:60: error: request for member ‘size’ in something not a structure or union
             pair->items[1] = mp_obj_new_bytes(val.data, val.size);
                                                            ^
../../extmod/modbtree.c: In function ‘btree_subscr’:
../../extmod/modbtree.c:257:9: error: unknown type name ‘DBT’
         DBT key;
         ^~~
../../extmod/modbtree.c:258:12: error: request for member ‘data’ in something not a structure or union
         key.data = (void *)mp_obj_str_get_data(index, &key.size);
            ^
../../extmod/modbtree.c:258:59: error: request for member ‘size’ in something not a structure or union
         key.data = (void *)mp_obj_str_get_data(index, &key.size);
                                                           ^
../../extmod/modbtree.c:260:20: error: ‘RET_SPECIAL’ undeclared (first use in this function)
         if (res == RET_SPECIAL) {
                    ^~~~~~~~~~~
../../extmod/modbtree.c:61:16: error: ‘RET_ERROR’ undeclared (first use in this function); did you mean ‘CHECK_ERROR’?
     if (res == RET_ERROR) { \
                ^
../../extmod/modbtree.c:263:9: note: in expansion of macro ‘CHECK_ERROR’
         CHECK_ERROR(res);
         ^~~~~~~~~~~
../../extmod/modbtree.c:267:9: error: unknown type name ‘DBT’
         DBT key, val;
         ^~~
../../extmod/modbtree.c:268:12: error: request for member ‘data’ in something not a structure or union
         key.data = (void *)mp_obj_str_get_data(index, &key.size);
            ^
../../extmod/modbtree.c:268:59: error: request for member ‘size’ in something not a structure or union
         key.data = (void *)mp_obj_str_get_data(index, &key.size);
                                                           ^
../../extmod/modbtree.c:274:36: error: request for member ‘data’ in something not a structure or union
         return mp_obj_new_bytes(val.data, val.size);
                                    ^
../../extmod/modbtree.c:274:46: error: request for member ‘size’ in something not a structure or union
         return mp_obj_new_bytes(val.data, val.size);
                                              ^
../../extmod/modbtree.c:277:9: error: unknown type name ‘DBT’
         DBT key, val;
         ^~~
../../extmod/modbtree.c:278:12: error: request for member ‘data’ in something not a structure or union
         key.data = (void *)mp_obj_str_get_data(index, &key.size);
            ^
../../extmod/modbtree.c:278:59: error: request for member ‘size’ in something not a structure or union
         key.data = (void *)mp_obj_str_get_data(index, &key.size);
                                                           ^
../../extmod/modbtree.c:279:12: error: request for member ‘data’ in something not a structure or union
         val.data = (void *)mp_obj_str_get_data(value, &val.size);
            ^
../../extmod/modbtree.c:279:59: error: request for member ‘size’ in something not a structure or union
         val.data = (void *)mp_obj_str_get_data(value, &val.size);
                                                           ^
../../extmod/modbtree.c: In function ‘btree_binary_op’:
../../extmod/modbtree.c:290:13: error: unknown type name ‘DBT’
             DBT key, val;
             ^~~
../../extmod/modbtree.c:291:16: error: request for member ‘data’ in something not a structure or union
             key.data = (void *)mp_obj_str_get_data(rhs_in, &key.size);
                ^
../../extmod/modbtree.c:291:64: error: request for member ‘size’ in something not a structure or union
             key.data = (void *)mp_obj_str_get_data(rhs_in, &key.size);
                                                                ^
../../extmod/modbtree.c:61:16: error: ‘RET_ERROR’ undeclared (first use in this function); did you mean ‘CHECK_ERROR’?
     if (res == RET_ERROR) { \
                ^
../../extmod/modbtree.c:293:13: note: in expansion of macro ‘CHECK_ERROR’
             CHECK_ERROR(res);
             ^~~~~~~~~~~
../../extmod/modbtree.c:294:43: error: ‘RET_SPECIAL’ undeclared (first use in this function)
             return mp_obj_new_bool(res != RET_SPECIAL);
                                           ^~~~~~~~~~~
../../extmod/modbtree.c: At top level:
../../extmod/modbtree.c:329:14: error: unknown type name ‘FILEVTABLE’
 STATIC const FILEVTABLE btree_stream_fvtable = {
              ^~~~~~~~~~
../../extmod/modbtree.c:330:5: error: initialization makes integer from pointer without a cast [-Werror=int-conversion]
     mp_stream_posix_read,
     ^~~~~~~~~~~~~~~~~~~~
../../extmod/modbtree.c:330:5: note: (near initialization for ‘btree_stream_fvtable’)
../../extmod/modbtree.c:330:5: error: initializer element is not computable at load time
../../extmod/modbtree.c:330:5: note: (near initialization for ‘btree_stream_fvtable’)
../../extmod/modbtree.c:331:5: error: excess elements in scalar initializer [-Werror]
     mp_stream_posix_write,
     ^~~~~~~~~~~~~~~~~~~~~
../../extmod/modbtree.c:331:5: note: (near initialization for ‘btree_stream_fvtable’)
../../extmod/modbtree.c:332:5: error: excess elements in scalar initializer [-Werror]
     mp_stream_posix_lseek,
     ^~~~~~~~~~~~~~~~~~~~~
../../extmod/modbtree.c:332:5: note: (near initialization for ‘btree_stream_fvtable’)
../../extmod/modbtree.c:333:5: error: excess elements in scalar initializer [-Werror]
     mp_stream_posix_fsync
     ^~~~~~~~~~~~~~~~~~~~~
../../extmod/modbtree.c:333:5: note: (near initialization for ‘btree_stream_fvtable’)
../../extmod/modbtree.c: In function ‘mod_btree_open’:
../../extmod/modbtree.c:356:5: error: unknown type name ‘BTREEINFO’; did you mean ‘BTREE’?
     BTREEINFO openinfo = {0};
     ^~~~~~~~~
     BTREE
../../extmod/modbtree.c:357:13: error: request for member ‘flags’ in something not a structure or union
     openinfo.flags = args.flags.u_int;
             ^
../../extmod/modbtree.c:358:13: error: request for member ‘cachesize’ in something not a structure or union
     openinfo.cachesize = args.cachesize.u_int;
             ^
../../extmod/modbtree.c:359:13: error: request for member ‘psize’ in something not a structure or union
     openinfo.psize = args.pagesize.u_int;
             ^
../../extmod/modbtree.c:360:13: error: request for member ‘minkeypage’ in something not a structure or union
     openinfo.minkeypage = args.minkeypage.u_int;
             ^
../../extmod/modbtree.c:362:5: error: unknown type name ‘DB’
     DB *db = __bt_open(MP_OBJ_TO_PTR(pos_args[0]), &btree_stream_fvtable, &openinfo, /*dflags*/ 0);
     ^~
../../extmod/modbtree.c:362:14: error: implicit declaration of function ‘__bt_open’; did you mean ‘__bt_sync’? [-Werror=implicit-function-declaration]
     DB *db = __bt_open(MP_OBJ_TO_PTR(pos_args[0]), &btree_stream_fvtable, &openinfo, /*dflags*/ 0);
              ^~~~~~~~~
              __bt_sync
../../extmod/modbtree.c:362:14: error: initialization makes pointer from integer without a cast [-Werror=int-conversion]
In file included from ../../py/mpstate.h:35:0,
                 from ../../py/runtime.h:29,
                 from ../../extmod/modbtree.c:32:
../../extmod/modbtree.c:366:28: error: implicit declaration of function ‘btree_new’; did you mean ‘btree_seq’? [-Werror=implicit-function-declaration]
     return MP_OBJ_FROM_PTR(btree_new(db, pos_args[0]));
                            ^
../../py/obj.h:282:39: note: in definition of macro ‘MP_OBJ_FROM_PTR’
 #define MP_OBJ_FROM_PTR(p) ((mp_obj_t)p)
                                       ^
../../py/obj.h:282:29: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
 #define MP_OBJ_FROM_PTR(p) ((mp_obj_t)p)
                             ^
../../extmod/modbtree.c:366:12: note: in expansion of macro ‘MP_OBJ_FROM_PTR’
     return MP_OBJ_FROM_PTR(btree_new(db, pos_args[0]));
            ^~~~~~~~~~~~~~~
At top level:
../../extmod/modbtree.c:316:28: error: ‘btree_type’ defined but not used [-Werror=unused-const-variable=]
 STATIC const mp_obj_type_t btree_type = {
                            ^~~~~~~~~~
cc1: all warnings being treated as errors
../../py/mkrules.mk:77: recipe for target 'build-standard/extmod/modbtree.o' failed
make: *** [build-standard/extmod/modbtree.o] Error 1
`

**Comment by oopsmonk** [comment]
@mrharmtz I got the same error earlier and fixed it by enabling symlinks in git configuration.
https://git-scm.com/docs/git-config#Documentation/git-config.txt-coresymlinks
make sure symlinks is set to true
```
$ git config -l
...
core.symlinks=true
...
```

**Comment by mrharmtz** [comment]
> That file is a symlink. So something went wrong cloning the repository. Maybe the Ubuntu is backed by a Windows filesystem?

yeah you are correct, thanks, I simply moved it out of the shared folder between windows and the guest ubuntu.

> @mrharmtz I got the same error earlier and fixed it by enabling symlinks in git configuration. https://git-scm.com/docs/git-config#Documentation/git-config.txt-coresymlinks make sure symlinks is set to true
> 
> ```
> $ git config -l
> ...
> core.symlinks=true
> ...
> ```
 I did try this but it didn't work. I will try again later, thanks
