### ISSUE TITLE
Allow qstrs to be defined per file rather than in one huge header

### ISSUE THREAD

**Issue by dhylands** [micropython/micropython#791]
Currently, we have one huge qstrdefsport.h file which has all of the qstrs (minus the py ones) for a given port.

I think that it would be fairly straight forward to allow each source file to have a qstr file which describes the qstrs it needs.

So something like modpyb.c could have modpyb.qstr that contains the qstrs that modpyb needs. We would still have all of the generated qstrs go into one big file like it does now.

This would make things easier when a port (like teensy) winds up grabbing source files from the stmhal tree. It would automatically grab the corresponding qstr file as well. The way I'm thinking of implementing this would allow for mixing the 2 systems so you don't need to switch all of the files at once.

I thought I'd propose this before making any changes.

**Comment by dpgeorge** [comment]
qstrs are now automatically generated.
