### ISSUE TITLE
Regex results different from CPython

### ISSUE THREAD

**Issue by stinos** [micropython/micropython#7920]
```
import re
m = re.match("([^\s]+)\s*([^\s]+)", "5 1000")
print("g1", m.group(1), "g2", m.group(2))
```

CPython (tried with 3.7 and 3.8, windows and linux): `g1 5 g2 1000` which is correct as far as I can tell
MicroPython v1.17-92-gf4c1389fb (msvc and linux ports): `g1 5 100 g2 0` which looks like a bug?

**Comment by dpgeorge** [comment]
Fixed by 64193c7de9f53e01dca447a4a902398fe85b9c06
