### ISSUE TITLE
Autoindent is confusing and unnecessary, can we remove/disable it or have a workaround?

### ISSUE THREAD

**Issue by pdg137** [micropython/micropython#7925]
As a new micropython user, I'm thrown off by the automatic indentation feature for several reasons, and think it should be removed or at least made optional. I don't expect this to be very likely to happen, but I didn't see any other issue requesting its removal, so I thought it would be a useful to write down my thoughts here. Note that the original feature request is [here](https://github.com/micropython/micropython/issues/1368) for reference.

My main objection is that micropython is used in educational contexts, where we put a lot of effort into teaching students that they need four spaces to indent a block. In the REPL, however, the lesson becomes strangely inverted: you need to delete four spaces to exit a block and get your code to run.

In the simplest cases it doesn't even save keystrokes, either. Consider input like this:

```python
if True:
    print("true!")
```

The trade-off is between typing space-space-space-space before `print`, or backspace-backspace-backspace-backspace at the end.

Another big problem is that it causes constant problems with copy and paste: #4375 and #4621, for example. Some editors work around this, but it's still broken, for example, in Microbit's web editor (possible fix [here](https://github.com/microbit-foundation/python-editor-next/issues/277)), or for anyone who connects with a normal serial terminal. Wouldn't it be simpler and safer for the micropython-specific editors to implement the auto-indent themselves?

It's also worth noting that auto-indent is *not* a feature of the Python REPL. So by having it in our REPL, we're choosing to make our software different from the standard software, negating some of the educational benefit of learning micropython. It *is* a feature of the popular iPython interface, but they somehow implemented it in a way that allows pasted code to work automatically in a normal terminal. (If ours worked like that, maybe it would be fine.)

As I said at the beginning, it seems unlikely that this feature will get removed at this point.  But maybe there could be a compromise. For example, allow it to be disabled with a configuration option of some sort. Or perhaps we could allow a raw LF/Ctrl+J character (which apparently does nothing right now) to insert a line break without auto-indentation, as it does in Emacs?

**Comment by joewez** [comment]
Honestly, I like the auto-indent and think it would be a horrible mistake to remove it, and even to make it _optional_ would be worse.

I think it serves an important (yet gentle) reminder that INDENTATION is a defining and essential part of the language that should be one of the first things you learn.  You could haggle over 4 backspaces versus one keystroke, but it's all kind of pointless until the student learns that indention and consistency are what defines CODE BLOCKS in MicroPython.

Also, making something optional always seems like a nice compromise, but my experience has shown me there are hidden costs.  More code, more documentation, and you will **still** have instances where people will be "thrown off".

**Comment by mattytrentini** [comment]
Can this issue be closed now?

**Comment by dpgeorge** [comment]
I think there's still a discussion to be had here.  The main point is that MicroPython's REPL is different to CPython's (and we otherwise try very hard to be the same as CPython).  See eg #8145 which shows that auto-indent is a stumbling block.

Maybe the following could work: if a space or tab is entered at the start of the first line that is auto-indented then the auto-indent on that line is deleted and the space/tab inserted, and auto-indent is turned off for the rest of the continued input.

That would allow auto-indent to continue to work and be convenient, but also automatically disable itself if there is any pasted code, or if the user does (by habit) enter spaces/tabs to manually indent.

**Comment by dpgeorge** [comment]
See #8391 for an implementation of the above idea about disabling auto-indent automatically.

**Comment by dpgeorge** [comment]
Fixed by 6d401be4dd0164cb197a05c7419f7b6ef5bbdf51, auto-indent is now disabled when pasting code at the REPL.
