### ISSUE TITLE
The ports/esp32/machine_pin.c does not contain gpio47&gpio48 used by esp32s3

### ISSUE THREAD

**Issue by Wind-stormger** [micropython/micropython#7928]
Referring to the datasheet of esp32s3, I confirm that it has gpio47 and gpio48.

May I ask if there is any reason I have missed, which makes it impossible to join these two gpios here?

**Comment by UnexpectedMaker** [comment]
I'm working on the S3 port and well, your are way too early to be expecting everything in mainline :) Production S3 silicon wont even be available until early next year (doesn't even go into production until December). Current silicon on the DevKit boards are still pre-production.

IO47 and 48 are problematic - They are new types of functionality (External SPI Clock), and the IO is used in some of the planned S3 variants and are not available to the user. I've solved this (just for use as GPIO) in my local changes in the port work I am doing, but I'm a long way away from having this ready for a PR, sorry. 

That said, you are always free to fork MP, and make your own changes and build your own firmware :)

**Comment by Wind-stormger** [comment]
> just for use as GPIO
Thank you. That's exactly what I did， just for use as GPIO is enough for current needs .

**Comment by UnexpectedMaker** [comment]
> just for use as GPIO
> Thank you. That's exactly what I did， just for use as GPIO is enough for current needs .

nps! Can you close this issue now?

**Comment by street-grease-coder** [comment]
according to the esp-idf v4.4 the board that is shipped now as dev board is not the 'beta' version anymore. simply enabling the pins 46 to 48 and using the neopixel guide grants full control over the onboard RGB LED. Is there really an issue with a two line pull-request in this regard?

**Comment by UnexpectedMaker** [comment]
I’ll try to get a PR ready with my latest S3 work in the next day or 2.

**Comment by street-grease-coder** [comment]
thanks! otherwise I'll figure out how to make that 2-liner pull request... =) on another, tangentially related note: noticed bluetooth is completely disabled and won't compile with the esp32s3 build, guessing that's because of ble 5.0 and the idf being implemented differently, not sure where to start to look into this - guessing that it requires writing some wrapper functions for the C code provided in the esp-idf, wondering if it's enough to change some naming schemes... In any case, super excited for your PR and thanks for sharing!

**Comment by Wind-stormger** [comment]
I tried to add new code after line 200 of this file：

https://github.com/micropython/micropython/blob/3745c393c82050a64445dbdf4c34836fa8664ce0/ports/esp32/machine_pin.c#L199-L203

``` c
    {{&machine_pin_type}, GPIO_NUM_45},
    {{&machine_pin_type}, GPIO_NUM_46},
    
    #if CONFIG_IDF_TARGET_ESP32S3
    {{&machine_pin_type}, GPIO_NUM_47},
    {{&machine_pin_type}, GPIO_NUM_48},
    #endif

    #endif
 }; 
```

Now it does not affect the compilation of esp32s2. After a simple test, gpio48 can be successfully driven on esp32s3.

But,when I saw the code from 502 lines to 636 lines, I was confused. I didn't understand what a "pin IRQ object" was. I didn't know that gpio45 ended here, so I didn't try to add it rashly.

**Comment by UnexpectedMaker** [comment]
I have a PR (https://github.com/micropython/micropython/pull/7988) that has all of this plus more in it.  Just wait for that to get merged.
