### ISSUE TITLE
The latest threading firmware of pyboard v1.1 has bug with Boot mode. 

### ISSUE THREAD

**Issue by CaptainJackey** [micropython/micropython#7935]
Since v1.7 , something wrong with threading firmware, when burning the threading firmware, pyBoard's boot modes (two keys) function can not be used. please check it, thanks! @jimmo @dpgeorge 

https://docs.micropython.org/en/latest/pyboard/general.html#boot-modes

![1](https://user-images.githubusercontent.com/42539086/138856269-86a57fad-9006-438f-997d-fa1db6d99354.png)

**Comment by jimmo** [comment]
Duplicate of #7816
