### ISSUE TITLE
It seems impossible to edit the wiki

### ISSUE THREAD

**Issue by peterhinch** [micropython/micropython#7961]
Until August I was able to edit [the wiki](https://wiki.micropython.org/Home) using GitHub authentication. Now this fails. @dhylands has confirmed this, and a similar problem with the GitHub wiki, in [this forum thread](https://forum.micropython.org/viewtopic.php?f=15&t=11365&p=62159#p62108).

**Comment by dpgeorge** [comment]
The wiki here is now read-only.  Please use wiki.micropython.org for everything wiki-related.
