### ISSUE TITLE
ESP32: Micropython allocated heap is reduced for IDF >= 4.2.2.

### ISSUE THREAD

**Issue by glenn20** [micropython/micropython#7962]
Micropython allocates a heap size of only 65536 bytes on the ESP32 for later versions of the ESP IDF (>= 4.2.2) instead of the actually available 110536 bytes.

Since the implementationof a new allocator in the IDF (October 2020), **heap_cap_get_largest_block()** returns the size of the largest allocatable block rounded down to the nearest power of 2 (in contradiction with the [documentation](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/mem_alloc.html#_CPPv432heap_caps_get_largest_free_block8uint32_t).

I have filed an issue against the IDF at <https://github.com/espressif/esp-idf/issues/7808>.

The follwing patch provides an ugly work around:

```diff
diff --git a/ports/esp32/main.c b/ports/esp32/main.c
index 2ba613668..dce82b7fb 100644
--- a/ports/esp32/main.c
+++ b/ports/esp32/main.c
@@ -131,7 +131,20 @@ void mp_task(void *pvParameter) {
     #else
     // Allocate the uPy heap using malloc and get the largest available region
     size_t mp_task_heap_size = heap_caps_get_largest_free_block(MALLOC_CAP_8BIT);
-    void *mp_task_heap = malloc(mp_task_heap_size);
+    void *mp_task_heap;
+    for (size_t incr = mp_task_heap_size >> 1;
+         incr > 4;
+         incr >>= 1)
+    {
+        mp_task_heap_size += incr;
+        mp_task_heap = heap_caps_malloc(mp_task_heap_size, MALLOC_CAP_8BIT);
+        if (mp_task_heap == NULL) {
+            mp_task_heap_size -= incr;
+        }
+        heap_caps_free(mp_task_heap);
+        printf("HeapSize=0x%x  %d\n", mp_task_heap_size, mp_task_heap_size);
+    }
+    mp_task_heap = malloc(mp_task_heap_size);
     #endif
 
 soft_reset:
```

**Comment by IhorNehrutsa** [comment]
Correspond to **ESP32: RAM leak in ESP-IDF v4.3** #7813
