### ISSUE TITLE
FW: The firmware download page looks wonderful now.

### ISSUE THREAD

**Issue by robert-hh** [micropython/micropython#7966]
Quite an impressive select of boards. And easy to use. The json files need more tags, but that can be added easily now that the structure is set up.

**Comment by jimmo** [comment]
Thank you @robert-hh !! Sorry it's been a long time coming, working away at it in small chunks this year.

Shout out to @mcauser and @UnexpectedMaker for providing board images and additional metadata!! Thanks!!

We will do more with the features & filtering at some stage. Many boards do not currently offer firmware but the plan (I think) is to turn on automatic building of every board for all ports.

**Comment by dpgeorge** [comment]
For automatic building of mimxrt, rp2 and samd ports see #7972.
