### ISSUE TITLE
uasyncio ThreadSafeFlag re-entry

### ISSUE THREAD

**Issue by oclyke** [micropython/micropython#7978]
Please see my post on the forums:
https://forum.micropython.org/viewtopic.php?f=2&t=11393

I think I've found a bug in the behavior of uasyncio's ThreadSafeFlag which causes program execution to stop if a thread safe flag gets set more than once without being waited upon first

port: ESP32
uasyncio: v3 (using built-in from upy commit f4c1389fb)

**Comment by peterhinch** [comment]
The bug was in the user code and not in ThreadSafeFlag. See forum thread.
