### ISSUE TITLE
Downloads: Wrong file types for mimxrt build.

### ISSUE THREAD

**Issue by robert-hh** [micropython/micropython#8015]
The file types built for the mimxrt port are a little bit inconsistent. The Teensy boards require .hex files, the MIMXRT1xxx and Seed boards require .bin files. The files on the download page do not meet always and every day this rule. Is there any way to specify, which file type shall be created, like a tag in the json file?

**Comment by dpgeorge** [comment]
> Is there any way to specify, which file type shall be created, like a tag in the json file?

The extensions are specified in `tools/autobuild/build-boards.sh`:
```
function build_mimxrt_boards {
    build_boards $1 $2 modmimxrt.c bin hex
}
```
Looking at the downloads page for Teensy https://micropython.org/download/TEENSY40/ it is inconsistent, and the sorting/order of releases seems wrong:
![teensydl](https://user-images.githubusercontent.com/6187689/142694216-b36330e1-8546-473a-b0be-380eef19a3ca.png)

**Comment by robert-hh** [comment]
That's what puzzled me. And for some m in mimxrt boards there is not .bin file at all.

**Comment by dpgeorge** [comment]
Should be fixed.

**Comment by robert-hh** [comment]
Thank you. All file types are visible now. The only slightly irritiating is, that for the mimxrt the .hex files are shown first, which is a little bit misleading, at least at the moment. @alphaFred will make a PR shortly with a generic bootloader for all mimxrt boards, which uses dfu-util for upload and accepts .hex files as well. That bootloader also does not erase the file system on firmware upload for Teensy boards. We are currently testing the bootloader to make sure, that it works well on all supported boards. The bootloader is bundled with the firmware, such that there is only one file type per device to take care of and chance are a little bit less to confuse users.

**Comment by dpgeorge** [comment]
> he only slightly irritiating is, that for the mimxrt the .hex files are shown first, which is a little bit misleading, at least at the moment.

If that order needs changing, ie put .bin before .hex, then it requires a new entry in `board.json` which specifies the default extension (also possible the list of extensions that should be built and shown).

**Comment by robert-hh** [comment]
> If that order needs changing, ie put .bin before .hex, then it requires a new entry in board.json which specifies the default extension (also possible the list of extensions that should be built and shown).

Does that entry already exist? Probably not.
