### ISSUE TITLE
how can code "know" is it running on ESP32 or ESP32-S2

### ISSUE THREAD

**Issue by emard** [micropython/micropython#8036]
I have small problem
on ESP32 I should use SPI(id=2, baudrate=...)
on ESP32-S2 I should use SPI(baudrate=...)

to write compatible code, how can it tell is it
running on ESP32 classic or ESP32-S2, with
minimum memory footprint for this decision.

or how can code tell does SPI() support "id="
argument or not?

**Comment by UnexpectedMaker** [comment]
SPI(baudrate=...) is SoftwareSPI not not HW SPI. You always need to pass the SPI channel as the first parameter to use HW SPI.

You can import name from machine and check `uname().machine` to see what ESP32 chip the firmware is built for.

**Comment by emard** [comment]
ok uname()
