### ISSUE TITLE
stm32 NUCLEO WB55 : issue on embedded user LEDs numbers

### ISSUE THREAD

**Issue by YannickMarietti** [micropython/micropython#8054]
Hello

On firmware 1.17 with board NUCLEO-WB55 (stm32), the numbers attributed to the 3 embedded LEDs are inverted versus PCB printings:

**User LED** => **Printing on board PCB** => **Example µPython call**
Blue LED (right) => LED1 => pyb.LED(3).toggle()
Green LED (center) => LED2 => pyb.LED(2).toggle()  _(matching for this one !)_
Red LED (left) =>LED3 => pyb.LED(1).toggle()

**Is it possible to get Blue LED referenced as LED(1) and red LED referenced as LED(3) on future firmwares ?**
 
Best regards

Yannick

**Comment by jimmo** [comment]
Thanks -- just checked and you're right. It's confusing that it's RGB from left to right, but the labelling is 3 2 1. See #8055 for a fix.

**Comment by YannickMarietti** [comment]
Thanks Jiimmo :)

**Comment by dpgeorge** [comment]
Fixed by 92f54fe8d9618dd5e6101ac5c5f83ffc53b1bc57

**Comment by YannickMarietti** [comment]
Thanks !
