### ISSUE TITLE
 ImportError: can't import name Servo

### ISSUE THREAD

**Issue by iwordly** [micropython/micropython#8059]
`from pyb import Servo
`
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: can't import name Servo`
using STM32F4DISC file but it can't import Servo ,PWM……
Even your have this issue?
I want get a answer and thinks you support.

**Comment by dpgeorge** [comment]
`pyb.Servo` is not enabled on the STM32F4DISC board, although I guess it could be.  You can try building with:
```
make BOARD=STM32F4DISC CFLAG_EXTRA=-DMICROPY_HW_ENABLE_SERVO=1
```

**Comment by iwordly** [comment]
Thank your answer, unfortunately, it has the mistakes aslo.

**Comment by dpgeorge** [comment]
`pyb.Servo` has been enabled on various STM32F4/F7 boards in 0892ebe09105185a2e9bc97a7047187b4d141270

**Comment by iwordly** [comment]
Thank you for your patience to answer, adding this line of code, `#define MICROPY_HW_ENABLE_SERVO     (1)`
there is no error, if I want to add the encoder device, can I also join it?

**Comment by dpgeorge** [comment]
> if I want to add the encoder device, can I also join it?

There is no encoder.  But you can use `pyb.Timer`.

**Comment by iwordly** [comment]
okay thanks you support!



---Original---
From: "Damien ***@***.***&gt;
Date: Wed, Dec 15, 2021 07:57 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [micropython/micropython]  ImportError: can't import name Servo(Issue #8059)




  
if I want to add the encoder device, can I also join it?
  
There is no encoder.  But you can use pyb.Timer.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by robert-hh** [comment]
There are two implementations for an encoder/counter class in progress. One by @IhorNehrutsa for ESP32, and one by me for MIMXRT. There also a PR from @jonathanhogg for a slightly different implementation. We three had a discussion phase to get a common basic API for the class, taking into account on how a implementation for STM32 could look like.

**Comment by iwordly** [comment]
okay thanks.
I will join it later.



---Original---
From: "Robert ***@***.***&gt;
Date: Wed, Dec 15, 2021 15:59 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [micropython/micropython]  ImportError: can't import name Servo (Issue #8059)




 
There are two implementations for an encoder/counter class in progress. One by @IhorNehrutsa for ESP32, and one by me for MIMXRT. There also a PR from @jonathanhogg for a slightly different implementation. We three had a discussion phase to get a common basic API for the class, taking into account on how a implementation for STM32 could look like.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
