### ISSUE TITLE
Sometimes the sdcard is recognized, but the internal drive is what's shared

### ISSUE THREAD

**Issue by dhylands** [micropython/micropython#806]
I often do copy a file from mv linux host to the internal flash drive. Then go to the terminal and do a Control-D.

I have an sdcard plugged in, but sometimes it isn't recognized, and occaisonally when I do the Control-D the sdcard will be recognized.

The internal drive is what's being shared with the PC, but the sdcard is what's current as far as micropython is concerned (i.e. os.getcwd() returns '/sd')

So it may not be a real issue, but it is a bit disconcerting.

I think that this arises because the internal drive is what's being shared and doing the Control-D leaves that connection up.

So the question becomes, if the internal flash is what's being shared, should we make it be the current directory regardless of whether the sdcard was recognize or not?

**Comment by dpgeorge** [comment]
This should now be resolved by the changes made in d39c7aa517b722161a7dd792fafc5096d58beec8 (see main.c).
