### ISSUE TITLE
build system: New code formatting errors flagged in old code.

### ISSUE THREAD

**Issue by robert-hh** [micropython/micropython#8070]
One of my latest update to a PR caused code formatting error in files not in any way related to that PR and files, being unchanged since quite a while. These files are:

extmod/uasyncio/event.py
ports/stm32/make-stmconst.py
tests/extmod/utimeq1.py
tools/pydfu.py

The flagged errors are in all cases obsolete empty lines. Was something changed in the build system?

**Comment by dlech** [comment]
See https://github.com/micropython/micropython/pull/8067

**Comment by robert-hh** [comment]
Thanks. Did not notice that.
