### ISSUE TITLE
esp32c3 Flash Instructions Documented Incorrectly

### ISSUE THREAD

**Issue by hansonap** [micropython/micropython#8100]
The MicroPython.org [esp32c3](https://micropython.org/download/esp32c3/) and [esp32c3-usb](https://micropython.org/download/esp32c3-usb/) download pages appear to have incorrect instructions.

# Necessary changes
- The `--chip` flag should have a value of `esp32c3`.
- The  flash offset should be `0x0`.
- The bin file name should be updated to include `c3` after esp32, for completeness.

# Discussion
The symptom of the wrong flash offset was that after flashing, which appeared to be successful, I could not connect to the board with ampy, mpfshell, or rshell. I stumbled across [this](https://forum.micropython.org/viewtopic.php?f=18&t=10104&start=10) forum which had the answer. And indeed the [bootloader](https://docs.espressif.com/projects/esp-idf/en/latest/esp32c3/api-guides/bootloader.html?highlight=0x0) documentation for the esp32c3 states that it should be `0x0`.

Most people who use MicroPython on an esp32, if like myself, only use esptool to flash MicroPython have no concept of flash offsets and how to choose them so it would be good to fix this and maybe add a page to the MicroPython docs.

I would be happy to make these changes / pull request but did not see the website source in this repository.

**Comment by dpgeorge** [comment]
Fixed by ea5744fd8decb1161a2bd212813a275e2705fd89
