### ISSUE TITLE
PWM, Modes, and channels issue

### ISSUE THREAD

**Issue by kthod861** [micropython/micropython#8108]
Hello,

While trying to get the same behavior as "ledc"+"ledcWriteTone" using micropython, i ended up stuck with no solution to get the 8 PWM output with different frequencies .

Goal: get 8 frequencies outputs (fixed duty) that can be modified using python as the ESP32 is able to provide this ( tested using ledc on a bare new ESP32 board).
But i probably have missed something here.

For example, using "esp32-20210902-v1.17.bin", and by default testing the example provided here is a fail:
- https://docs.micropython.org/en/latest/esp32/tutorial/pwm.html

i say fail as the output of it i absolutly not :

- `PWM(Pin(15), freq=100, duty=64, resolution=10, mode=0, channel=0, timer=0)`

but rather:

- `PWM(Pin(15), freq=100, duty=64 )`

Did also a ton of test by myself without understanding the logic behind mode and channel selection when creating a PWM object.
It sounds like it dynamically choose timers depending on init frequency but i'm really not sure about that.

Any help is welcome

**Comment by robert-hh** [comment]
PWM has been changed to support different frequencies. Try the latest daily build.

**Comment by kthod861** [comment]
Awesome ! , using latest nightly solved it.
Thanks a lot

**Comment by IhorNehrutsa** [comment]
@kthod861 please close the issue if all right
