### ISSUE TITLE
ESP32 round(99.00001, 0) = 99.00001

### ISSUE THREAD

**Issue by PsuFan** [micropython/micropython#8117]
Can someone explain why round(99.00001, 0) = 99.00001 on ESP32? Floor will remove it but some instances I need round places...

**Comment by peterhinch** [comment]
See https://github.com/micropython/micropython/issues/5284, https://github.com/micropython/micropython/issues/4212 etc.

**Comment by PsuFan** [comment]
Sorry I did do a search! But there were tons of results..
