### ISSUE TITLE
Raspberry Pi Pico - Not showing in Windows Explorer

### ISSUE THREAD

**Issue by ninjaWolf8724** [micropython/micropython#8118]
I have flashed MicroPython to a Raspberry Pi Pico. I am am able to complete the flash process fine, but the device won't show in Windows Explorer, and I want to install modules, as well as a new code.py. But it shows up in Thonny just fine.
I am using MicroPython 1.17 and my host OS is Windows 11 Pro 64-bit

**Comment by robert-hh** [comment]
That is the intended behavior. It only shows a drive on the PC for the firmware update. During regilart operation you have to use tools like Thonny or mpremote to transfer files between the PC and the RPi Pico.

**Comment by Kyuchumimo** [comment]
This is normal behavior, it also happens in Linux. Using MicroPython firmware the board uses FS mode.
Using Adafruit CircuitPython firmware you can see the board as a mass storage device.

**Comment by pavelrevak** [comment]
MicroPython support mass storage only with STM microcontrollers
for RP there is circuitpython with mass storage support.

**Comment by davehylands** [comment]
> MicroPython support mass storage only with STM microcontrollers
> for RP there is circuitpython with mass storage support.

See this thread for more details: https://forum.micropython.org/viewtopic.php?f=21&t=11054&p=60773

**Comment by domdfcoding** [comment]
Is there a plan to support mass storage? I noticed that Anvil's Pico W firmware (available [here](https://github.com/anvil-works/anvil-pico/releases)) enables USB mass storage (see [this Tom's Hardware guide](https://www.tomshardware.com/how-to/build-raspberry-pi-pico-w-web-app)), but I'm not sure how they achieve that.

**Comment by jimmo** [comment]
> Is there a plan to support mass storage? I noticed that Anvil's Pico W firmware (available [here](https://github.com/anvil-works/anvil-pico/releases)) enables USB mass storage (see [this Tom's Hardware guide](https://www.tomshardware.com/how-to/build-raspberry-pi-pico-w-web-app)), but I'm not sure how they achieve that.

Mass storage can be enabled by setting the `MICROPY_HW_USB_MSC` build option. The Arduino Nano RP2040 Connect board does this for example: https://github.com/micropython/micropython/blob/master/ports/rp2/boards/ARDUINO_NANO_RP2040_CONNECT/mpconfigboard.h#L14

Mass storage requires that we use the FAT filesystem (rather than LittleFS) which is significantly worse for performance and reliability.

More background here https://github.com/micropython/micropython/pull/7402#issuecomment-1048777491
