### ISSUE TITLE
Duplicated tab while pasting code

### ISSUE THREAD

**Issue by keelung-yang** [micropython/micropython#8145]
Hi,
I got duplicated tab both in screen and minicom on Ubuntu 18.04.6 (all packages are up-to-date)
And I also tried pyb_v1.1 firmware with version 1.17 and pybv11-20220107-unstable-v1.17-316-gb96318ab6.dfu
```python3
def f():
    pass #1
    pass #2
    pass #3
```
![mp_past](https://user-images.githubusercontent.com/20385450/148487322-a2b7e688-06fb-4a45-8ecb-798990ceb382.png)

**Comment by dpgeorge** [comment]
Use ctrl-E to enter paste mode, then it should work.

See related discussion in #7925.
