### ISSUE TITLE
CAN FD not working with STM32 H7

### ISSUE THREAD

**Issue by suzonch** [micropython/micropython#8169]
I have Nucleo H743ZI, according to https://github.com/micropython/micropython/issues/4774 CAN FD is implemented then why long message isn't working? 
![image](https://user-images.githubusercontent.com/26577218/149325633-1add373c-b881-44c0-bbc9-8ce8e2520a22.png)

**Comment by suzonch** [comment]
Any suggestion @iabdalkader

**Comment by iabdalkader** [comment]
I think I can fix this, but will need you to test it, let me know if you're willing to test it and I'll have a look. Note there's also an open PR to improve and fix some issues with the FDCAN driver.

**Comment by suzonch** [comment]
Hi,

I'm totally ready to test it anytime. That'd be really great if it can be fixed. I'm messing around a bit with my limited experience in C.

I'm keeping an eye on that PR too.

Best regards
Md Abu Daud Chowdhury
________________________________

**Comment by suzonch** [comment]
Hi,
I'm totally ready to test it anytime. That'd be really great if it can be fixed. I'm messing around a bit with my limited experience in C.

**Comment by iabdalkader** [comment]
I'll let you know when it's done. I got it working, but still need to reconfigure the shared RAM.

**Comment by suzonch** [comment]
That's great, so you'll create a new PR with this fix?

**Comment by iabdalkader** [comment]
#8185

**Comment by suzonch** [comment]
I'll confirm if it works once I get the FD CAN converter working, from logic analyzer it seems to be working(analyzer can't decode CAN FD but only CAN)

**Comment by dpgeorge** [comment]
Fixed by ff287d085f95ab0ca3fdf67ee9d8cce6f046b01e
