### ISSUE TITLE
esp32s3/clk.h missing on build

### ISSUE THREAD

**Issue by DaniDD** [micropython/micropython#8181]
Hello,
I cant build the image to flash on ESP32-S3. Branch is master, from esp-idf too.
modmachine.c will include "esp32s3/clk.h" and other files will include soc/cpu.h
I dont have this files.
I try it with GENERIC without S3. There is the same error. 
Wah can I do?
Thx

**Comment by dpgeorge** [comment]
You can see that the CI builds OK.  It uses IDF commit 142bb32c50fa9875b8b69fa539a2d59559460d72

**Comment by DaniDD** [comment]
Thank you, with this IDF I can build it.
