### ISSUE TITLE
esp-idf v5 maintenance

### ISSUE THREAD

**Issue by oclyke** [micropython/micropython#8182]
I've upgraded my dev machine to an M1 based mac. The ESP-IDF now supports the arm64 architecture, but these versions of the IDF have some refactoring that breaks the ESP32 micropython build.

**Comment by jonnor** [comment]
MicroPython builds and works with ESP-IDF 5.x for well over 1 year now. If you are having problems, please open a new issue with more details such as exactly how you are building, which versions of esp-idf is used, and the complete build log. Also remember to update submodules, as per the build instructions in the README.
