### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by Github73840134** [micropython/micropython#8201]
Hi there, I am a big fan of the mp project. But I have few questions...
- How do you make your own network interface to put in `network.Driver()`?
- What are the required functions and values for the network interface class?
- Can you change the board name while executing?
- Can you disable safe/recovery mode from being accessed?
- Can you kill specific threads with _thread?
- Is there any tips for signals that require specific timing (i.e. VGA,Composite video)?

I am a python programmer, so I like micro python a lot, it just raises a lot of questions.

Thanks to any who can answer!

**Comment by peterhinch** [comment]
Your query is more likely to be answered if you post it in [the forum](http://forum.micropython.org/index.php) rather than in this bug tracker.
