### ISSUE TITLE
1.18dev/esp32: confusing method name ADC.read_uv()

### ISSUE THREAD

**Issue by jacklinquan** [micropython/micropython#8203]
The name "uv" normally refers to "micro volt".
This method actually returns value in "milli volt".
I suppose this method should be renamed to ADC.read_mv() instead.

**Comment by dpgeorge** [comment]
It is supposed to return a value in microvolts, that's what the documentation says.  So maybe the function is implemented incorrectly?

**Comment by jacklinquan** [comment]
@dpgeorge ,
Sorry that I'm wrong.
It does return a value in microvolts, just the resolution is in millivolt level.
I'll close this issue.
