### ISSUE TITLE
is there something between mpy-cross and a frozen module?

### ISSUE THREAD

**Issue by keredson** [micropython/micropython#8216]
I've used both cross-compiled modules (which consume ram for the resulting code, even if you save the compiling ram) and frozen modules (which do not, but require re-flashing the device).  Is there a way to generate a frozen module but load it from the filesystem?  (Where they would be easier to update, but run straight from flash and not consume ram?)

**Comment by dpgeorge** [comment]
Yes, this feature is currently work-in-progress, see #8191.

**Comment by keredson** [comment]
heck yeah, awesome work @dpgeorge!
