### ISSUE TITLE
Source code of BLE.gattc_write()? - Exception thrown

### ISSUE THREAD

**Issue by nickagian** [micropython/micropython#8227]
It's a bit embarrassing, but it seems I'm unable to find the source code of the BLE.gattc_write() function. The reason I'm looking for it is to understand why I get an exception each time I call it in my application.

**Comment by dpgeorge** [comment]
- Python wrapper: https://github.com/micropython/micropython/blob/master/extmod/modbluetooth.c#L839-L852
- implementation (for NimBLE based ports): https://github.com/micropython/micropython/blob/master/extmod/nimble/modbluetooth_nimble.c#L1396-L1410

**Comment by jonnor** [comment]
Question seems to be answered.
