### ISSUE TITLE
Feature request: native code emitter for generators

### ISSUE THREAD

**Issue by peterhinch** [micropython/micropython#823]
Given the use of generators to implement threaded code there might be substantial performance benefits if the enhanced code emitters worked with generators. As far as I can see this is currently unsupported: the following issues a "TypeError: 'NoneType' object is not an iterator" on the print line unless I comment out the decorator. Other custom decorators work fine.

@micropython.native
def myfunc():
    for x in range(10):
        yield 2*x

gen = myfunc()
while True:
    try:
        print(next(gen))
    except StopIteration:
        break

**Comment by pfalcon** [comment]
Tracked by https://github.com/micropython/micropython/issues/1041 .
