### ISSUE TITLE
Teensy 4.1 with micropython and C++ modules

### ISSUE THREAD

**Issue by Friday8229** [micropython/micropython#8243]
Hi i want to use the Teensy 4.1 with micropython. I found [this](https://micropython.org/download/TEENSY41/) website that lets you flash the micropython environment. So i want to know is there any possibility I'll be able to compile custom C++ modules in the micropython environment like i do with other boards such as Esp32 if so can you guide me to a tutorial on how to do it?

**Comment by dpgeorge** [comment]
The same approach for esp32 should work for the mimxrt port (Teensy 4.1).  See http://docs.micropython.org/en/latest/develop/cmodules.html

Questions like these are better suited for https://forum.micropython.org
