### ISSUE TITLE
Build error with ESP-IDF v4.4

### ISSUE THREAD

**Issue by water5** [micropython/micropython#8282]
ESP-IDF v4.4 (github `master` branch)
ESP-32
```python
make BOARD=GENERIC
```

>[ 78%] Building C object esp-idf/wifi_provisioning/CMakeFiles/__idf_wifi_provisioning.dir/src/scheme_ble.c.obj
>[ 78%] Generating ../../genhdr/qstr.i.last
>[ 78%] Linking C static library libesp_local_ctrl.a
>[ 78%] Linking C static library libasio.a
>make[3]: Leaving directory '/home/mc3/micropython/ports/esp32/build-GENERIC'
>[ 78%] Built target __idf_esp_local_ctrl
>make[3]: Leaving directory '/home/mc3/micropython/ports/esp32/build-GENERIC'
>[ 78%] Built target __idf_asio
>/home/mc3/micropython/ports/esp32/gccollect.c:37:10: fatal error: soc/cpu.h: No such file or directory
> #include "soc/cpu.h"
          ^~~~~~~~~~~
>compilation terminated.
>[ 78%] Linking C static library libwifi_provisioning.a
>make[3]: Leaving directory '/home/mc3/micropython/ports/esp32/build-GENERIC'
>[ 78%] Built target __idf_wifi_provisioning
In file included from /home/mc3/micropython/ports/esp32/machine_timer.c:38:
/home/mc3/esp-idf/components/driver/deprecated/driver/timer.h:16:2: warning: #warning "legacy timer group driver is deprecated, please migrate to driver/gptimer.h" [-Wcpp]
 #warning "legacy timer group driver is deprecated, please migrate to driver/gptimer.h"
  ^~~~~~~
>/home/mc3/micropython/ports/esp32/machine_timer.c:217:13: warning: 'TIMER_BASE_CLK' macro is deprecated
         self->period = (uint64_t)(TIMER_SCALE / mp_obj_get_float(args[ARG_freq].u_obj));
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>/home/mc3/micropython/ports/esp32/machine_timer.c:225:13: warning: 'TIMER_BASE_CLK' macro is deprecated
         self->period = (((uint64_t)args[ARG_period].u_int) * TIMER_SCALE) / args[ARG_tick_hz].u_int;
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>/home/mc3/micropython/ports/esp32/main.c:38:10: fatal error: soc/cpu.h: No such file or directory
 #include "soc/cpu.h"
          ^~~~~~~~~~~
>compilation terminated.
>/home/mc3/micropython/ports/esp32/modmachine.c:40:10: fatal error: esp32/clk.h: No such file or directory
 #include "esp32/clk.h"
          ^~~~~~~~~~~~~
>compilation terminated.

**Comment by nccwarp9** [comment]
how was this solved?
