### ISSUE TITLE
esp32: After hard reset PWM always has a duty of 512 of frequencies < 611Hz.

### ISSUE THREAD

**Issue by robert-hh** [micropython/micropython#8306]
This is another variant of the <611Hz issue. After hard reset, for the first PWM object the duty rate is always 50% for frequencies < 611Hz, regardless of what has been set in the constructor. Setting the duty rate in a second command works. Further new instantiated PWM objects have the right duty rate. For frequencies >=611 it works well.

**Comment by dpgeorge** [comment]
Fixed by 55a0125a154a9c13363d900e0caccd218bce0a54
