### ISSUE TITLE
Neopixel appears broken in v1.18 on esp32-c3

### ISSUE THREAD

**Issue by jcksnvllxr80** [micropython/micropython#8346]
I was running micropython v1.17 and neopixel was working perfect to control the onboard LED using pin 8.
I upgraded to v1.18 and all of a sudden, the write() function on NeoPixel doesn't even seem to work using the example code in the docs. (granted I am using the onboard LED instead of external neopixels). Anyone know whats going on here? Error shown below.

```
from machine import Pin
from neopixel import NeoPixel
pin = Pin(8, Pin.OUT)
np = NeoPixel(pin, 1)
np[0] = (255, 255, 255)

np.write()
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "neopixel.py", line 1, in write
  OSError: (-258, 'ESP_ERR_INVALID_ARG')
```

**Comment by dpgeorge** [comment]
Please see related #8198.

I think the bug here was fixed by 1f04a9a1fcd4172f7c721e05a4515c9c8bb0e8c9

**Comment by jcksnvllxr80** [comment]
I would like to fix this issue by using the latest nightly build [here](https://micropython.org/resources/firmware/esp32c3-20220224-unstable-v1.18-149-g64bfaae7a.bin) but in its name it says "unstable". I am not exactly sure that means what I think it means. Does it mean, "do not install this because it is doomed to break"?

**Comment by dpgeorge** [comment]
Nightly/unstable builds are relatively OK.  They already pass a lot of tests to get to that stage.  But don't use it in mission critical things!

**Comment by jcksnvllxr80** [comment]
Yes, the latest nightly build fixed the issue. Thank you
