### ISSUE TITLE
mpy_cross version 6? ValueError: incompatible .mpy file

### ISSUE THREAD

**Issue by duder1966** [micropython/micropython#8369]
I have pulled, built, installed the latest ESP32 version and it runs fine. However, when I try to load and run .mpy file I get the `ValueError: incompatible .mpy file` error. 

My local version of mpy_cross: MicroPython v1.18 on 2022-01-22; mpy-cross emitting mpy v5

However, on the ESP32, the mpy_cross version says 6.

Any ideas on how to resolve this? Is another version of mpy_cross coming to pypi soon?

Thanks.

**Comment by dlech** [comment]
The mpy-cross PyPI package repository is here: https://gitlab.com/alelec/mpy_cross. There should be CI builds of the package you can download from there.

**Comment by dpgeorge** [comment]
In the meantime you can build mpy-cross yourself and use that to recompile the .mpy files.

**Comment by duder1966** [comment]
Okay. That works (i.e. using the same mpy-cross as used for the build). Problem solved for the interim. Thanks.
