### ISSUE TITLE
AttributeError: 'module' object has no attribute 'argv'

### ISSUE THREAD

**Issue by Kakcalu13** [micropython/micropython#8422]
I was following the doc with every single steps:

Here is what I did:
1. git clone git@github.com:micropython/micropython.git
2. cd micropython
3. cd mpy-cross
4. make
5. It went OK.
6. cd ..
7. cd ports/unix
8. make submodules
9. it went OK
10. make
11. it went OK
12. able to run `./micropython`
13. make test
14. it went OK
15. ran `./micropython -m upip install micropython-pystone`
16. error

Full error:
```
bwuk@robots:~/micropython/ports/unix$ ./micropython -m upip install micropython-pystone
Traceback (most recent call last):
  File "upip.py", line 351, in <module>
  File "upip.py", line 301, in main
AttributeError: 'module' object has no attribute 'argv'
bwuk@robots:~/micropython/ports/unix$ 
```

OS: Ubuntu 20.04
Python: Python 3.8.10
git status:
![image](https://user-images.githubusercontent.com/65916520/158824895-5a80333a-3070-4f76-86ab-fccb8cd3aca0.png)

What did I do wrong? I admit, I'm not expert in python yet. I wanted to start this with micro:bit outside of their editor. It's using `import machine` which comes from this repo. Pypi doesn't work too. :sweat:

**Comment by dpgeorge** [comment]
Do you have any files in `$HOME/.micropython/lib`?  If there is a `sys.py` there then try deleting it.

**Comment by BenjaminEHowe** [comment]
I'm getting the same issue using [the official docker image](https://hub.docker.com/r/micropython/unix).

**Comment by dpgeorge** [comment]
`upip` is now deprecated.  Please use `mip` instead: http://docs.micropython.org/en/latest/reference/packages.html

**Comment by Kakcalu13** [comment]
Thanks, guys! I had no idea how I missed this in first place. I was actually planning to resume on Microbit this weekend. This is perfect timing! I will resume and if I managed to get it working, I will provide each details what I did. 

Thanks for the link!

**Comment by BenjaminEHowe** [comment]
`mip` doesn't seem to work on [the official docker image](https://hub.docker.com/r/micropython/unix) (1.19.1). Based on [the docs](https://docs.micropython.org/en/latest/reference/packages.html#using-mip-on-the-unix-port) I think I should be able to run (e.g.) `micropython-dev -m mip install urequests`, however I get error `ImportError: no module named 'mip'`.

Any ideas? I can't see any instructions for how to install `mip`. Happy to open a fresh issue given this isn't really the same as the OP's issue.

**Comment by peterhinch** [comment]
`mip` is part of the MP build. The doc reference posted by @dpgeorge explains how to use it.

**Comment by jonnor** [comment]
upip has been replaced by mip in MicroPython 1.20, https://github.com/micropython/micropython/releases/tag/v1.20.0
Closing as no longer relevant.
