### ISSUE TITLE
f-string feature missing on esp8266 with 1MiB flash port, throws SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Kyuchumimo** [micropython/micropython#8450]
Code example:
```
string = "F-STRING"

print(f"{string} OK")
```

see: https://github.com/micropython/micropython/releases/tag/v1.18
...

_esp8266 port:_

- _boards/GENERIC: enable f-strings_
...

...

**Comment by dpgeorge** [comment]
The 1MB board uses the `GENERIC_1M` board definition and this does not enable f-strings, because it does not have enough space.

Only the `GENERIC` board has f-strings enabled.
