### ISSUE TITLE
codecov does not run reports if any test fails

### ISSUE THREAD

**Issue by dlech** [micropython/micropython#8464]
As documented in https://docs.codecov.com/docs/ci-service-relationship#section-checking-ci-status, codecov doesn't run reports if any CI test fails. However, it is quite common for the code size test to fail when adding new features and this is when code coverage reports are arguably the most useful.

I suggest that we change the code size test to never fail and make it always add a pull request comment with the report instead.

**Comment by dpgeorge** [comment]
> I suggest that we change the code size test to never fail and make it always add a pull request comment with the report instead.

Yes, I like this idea.  I'm just not sure how to do it!
