### ISSUE TITLE
ESP32 related issue

### ISSUE THREAD

**Issue by GanerCodes** [micropython/micropython#8465]
I'm at a loss here, I can't seem to figure this out. I have this extremely odd issue where an LED controller I have will become laggy over the peirod of several days. This wouldn't be a problem if the issue didn't continue even after running machine.reset(). If I physically press the reset button on my esp32 (or unplug and replug) it fixes it. If anyone has any suggestions I'll be happy to hear them as I've been pondering this for months

**Comment by peterhinch** [comment]
I suggest you post this query, with a minimal code sample which displays the problem, in [the forum](http://[forum](http://forum.micropython.org/index.php).micropython.org/index.php).

**Comment by GanerCodes** [comment]
> Memory leak?

perhaps, but shouldn't machine.reset() reset the memory?

**Comment by GanerCodes** [comment]
Is there any way to trigger a hardware reset? what all needs to be reset?

Could the line `(time.time_ns() / 1_000_000) % (2 ** 32)` have anything to do with it? Does it become inaccurate after time, even after machine reset?

**Comment by jej** [comment]
Be sure to use `ticks_diff` in case (https://docs.micropython.org/en/latest/library/time.html#time.ticks_diff)

**Comment by GanerCodes** [comment]
time wrap around doesn't have any effect on my code so I don't think that would do anything

**Comment by GanerCodes** [comment]
im so stupid i needed integer division not normal division

implicit float casting is ruining my sanity
