### ISSUE TITLE
ESP32-S2 Error running .mpy files

### ISSUE THREAD

**Issue by peterhinch** [micropython/micropython#8469]
If this is cross compiled
```python
def foo():
    print('foo')
foo()
```
the resultant `.mpy` file runs on Pyboard, RP2 and ESP32 (all running firmware V1.18 or subsequent). On two separate ESP32-S2 boards the outcome is as follows:
```python
MicroPython v1.18-221-g94a9b5066-dirty on 2022-03-17; ESP32S2 module with ESP32S2
Type "help()" for more information.
>>> import rats1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: incompatible .mpy file
```
Cross compiler:
```
$ ./mpy-cross --version
MicroPython v1.18-141-gff9c70850-dirty on 2022-02-19; mpy-cross emitting mpy v5
```

**Comment by dlech** [comment]
The mpy version changed from v5 to v6 in https://github.com/micropython/micropython/commit/f2040bfc7ee033e48acef9f289790f3b4e6b74e5 (`v1.18-150-gf2040bfc7`). `v1.18-141-gff9c70850-dirty` is from before this change and `v1.18-221-g94a9b5066-dirty` is from after this change. So it is working as expected. A firmware that uses mpy v6 cannot run a file created with mpy-cross that emits v5.

**Comment by dpgeorge** [comment]
You can check the mpy version on the target by `sys.implementation.mpy & 0xf`.
