### ISSUE TITLE
[suggestion] make generic_spiram easier to compile

### ISSUE THREAD

**Issue by street-grease-coder** [micropython/micropython#8482]
I tried to compile for generic_spiram and 16mb partition table but needed to follow the following guides/posts to make it work. This seems to be a problem that came up on some occasions in the past https://github.com/micropython/micropython/issues/6950

This post is merely to ask if it's easy for an expert to incorporate these changes when partitionsizes of 8 or 16mb are detected - to help noobs compile for the spiram board (which I would assume is typically bundled with larger partition sizes). 

This is the guides & changes I followed:
https://github.com/micropython/micropython/issues/8202
https://github.com/russhughes/st7789_mpy/issues/56
https://forum.micropython.org/viewtopic.php?f=18&t=9768&start=10

To make it work for 16MB do I do the following correctly?
1. adjusted the partitions.csv file and made sure that the factory line in partitions.csv read `factory, app, factory, 0x10000, 0x1f0000,` 
2. added these three lines in `sdkconfig.spiram`: 
`CONFIG_COMPILER_OPTIMIZATION_SIZE=y
CONFIG_COMPILER_OPTIMIZATION_PERF=n
CONFIG_ESPTOOLPY_FLASHSIZE_16MB=y`
3. used make ` make FLASH_SIZE?=16MB BOARD=GENERIC_SPIRAM`

If this doesn't make sense in bigger context, please close

**Comment by dpgeorge** [comment]
> 2\. added these three lines in `sdkconfig.spiram`:
>         `CONFIG_COMPILER_OPTIMIZATION_SIZE=y`

See #8525, which should add this.

Providing builds for all possible flash sizes would really increase the number of boards.  Maybe instead it's possible to auto detect the available flash at runtime?
