### ISSUE TITLE
Viper code emitter produces unexpected error messages

### ISSUE THREAD

**Issue by peterhinch** [micropython/micropython#854]
Code which runs under standard and native emitters produces error messages if a comparison is performed between floats and integers: f < 1 has to be rewritten as f < 1.0 if f is a float. This tends to produce reams of error messages from working code.

**Comment by dpgeorge** [comment]
Viper now gives much better error messages.  Rules about irq handlers are documented in docs.  Unimplemented language features are fewer now, and partially documented in the wiki.
