### ISSUE TITLE
ESP32 port - configuring MICROPY_PY_NETWORK_WLAN to 0 causes linking issue

### ISSUE THREAD

**Issue by geza-pycom** [micropython/micropython#8541]
Hello,

Using the esp32 port, MICROPY_PY_NETWORK_WLAN cannot be set to 0 to disable the WLAN module because _network_wlan_event_handler()_ API is expected to exist in _modnetwork.c_ therefore linking issue happens.

The issue was discovered on this commit: https://github.com/micropython/micropython/commit/d242a9b

**Comment by dpgeorge** [comment]
Yes you are correct.

See #8544 for a fix.  Does that work for your case?

**Comment by geza-pycom** [comment]
Yes, it works. Thanks.

**Comment by dpgeorge** [comment]
Thanks for confirming.

Fixed by eb9674822b4d3be308beae2fa238ad85de9f09fa
