### ISSUE TITLE
Linker Error  FAILED: zephyr/zephyr_pre0.elf zephyr/zephyr_pre0.map

### ISSUE THREAD

**Issue by KarthikeyanM-eaton** [micropython/micropython#8556]
I am doing zephyr setup using west tool. I have tried to build the samples (nucleo_f767zi samples\basic\blinky) which is available zephyrproject\zephyr\samples, but it is failing and getting linker error (FAILED: zephyr/zephyr_pre0.elf zephyr/zephyr_pre0.map). Kindly anyone suggest me. For reference shared build error screenshot.
![image](https://user-images.githubusercontent.com/96125299/163763799-3217cf94-da94-4340-b6f1-548d6bcb12d5.png)

**Comment by dpgeorge** [comment]
It looks like you are trying to build a Zephyr example, not MicroPython.  MicroPython builds OK with Zephyr 3.0.0.  You can follow the instructions in the `ports/zephyr/README.md` file.
