### ISSUE TITLE
How can I turn off the machine.Pin  irq event ?

### ISSUE THREAD

**Issue by MarchAwake** [micropython/micropython#8559]
import machine
import time

def machine_pin_irq_handler(machine_pin):
    print("{} irq trigger".format(machine_pin))

def machine_pin_irq_on(machine_pin):
    machine_pin.irq(trigger=machine.Pin.IRQ_RISING, handler=machine_pin_irq_handler)
    print("Trun on {} irq".format(machine_pin))
  
machine_pin = machine.Pin(18, mode=machine.Pin.IN, pull=machine.Pin.PULL_DOWN)
machine_pin_irq_on(machine_pin)

**Comment by robert-hh** [comment]
If you call machine_pin.irq() again with handler=None, the irq is switched off.

**Comment by MarchAwake** [comment]
@robert-hh thanks a lot.
