### ISSUE TITLE
In RP2, Under what circumstances will the watchdog be triggered to restart the machine.

### ISSUE THREAD

**Issue by MarchAwake** [micropython/micropython#8618]

**Comment by dpgeorge** [comment]
I think this is question that can be answered by the rp2040 datasheet.

The intention of a watchdog is to trigger (reset the device) if it is not fed by the timeout.

**Comment by MarchAwake** [comment]
In RP2, When an exception occurs in my program, I use a try except and the WDT fires @dpgeorge

**Comment by dpgeorge** [comment]
If you think there is a problem with how MicroPython uses the WDT then please provide a description of the problem and how others can reproduce it.

**Comment by MarchAwake** [comment]
I am very sorry, but I found that the problem was caused by improper use of coroutines @dpgeorge
