### ISSUE TITLE
ussl within urequests causes memory problems

### ISSUE THREAD

**Issue by MATTYGILO** [micropython/micropython#8662]
I am running a program on an esp32.

I run a https request early on in the code, then later run some resource intensive neural networks.

I get this error

`Guru Meditation Error: Core  1 panic'ed (InstrFetchProhibited). Exception was unhandled.`

I first mentioned this problem in these questions:
[https://github.com/mocleiri/tensorflow-micropython-examples/issues/84](url)
[https://github.com/espressif/esp-idf/issues/8856](url)

> I have since found the root of the problem, but do not know how to fix it

When I comment out all the lines of code including ussl within the urequests file

[https://github.com/micropython/micropython-lib/blob/master/python-ecosys/urequests/urequests.py](url)

`s = ussl.wrap_socket(s, server_hostname=host)`
etc.

The program doesn't crash. However, I require https requests. All help is much appreciated.

**Comment by jimmo** [comment]
This issue is now being tracked in https://github.com/micropython/micropython/issues/8940.
