### ISSUE TITLE
Store mem_info in a .txt file

### ISSUE THREAD

**Issue by MATTYGILO** [micropython/micropython#8675]
Hi I was wondering whether it is possible to store the mem_info in a txt file

**Comment by jimmo** [comment]
This is Micropython's issue tracker. Your question might be better suited to the forum https://forum.micropython.org/

I'm not sure if you mean text file on the device filesystem, or as a text file on your host PC. The latter seems more useful, and it's easy to do with either pyboard.py or mpremote.

https://docs.micropython.org/en/latest/reference/pyboard.py.html
https://docs.micropython.org/en/latest/reference/mpremote.html

e.g.

```
$ pyboard.py --device /dev/ttyACM0 -c 'import micropython; micropython.mem_info(1)' > /tmp/mem_info
$ cat /tmp/mem_info
stack: 508 out of 15360
GC: total: 103168, used: 1488, free: 101680
 No. of 1-blocks: 16, 2-blocks: 6, max blk sz: 40, max free sz: 6343
GC memory layout; from 20002cf0:
00000: h=hhhh=======================================hhhShShh==h=======h
00400: ==========Bh=hh=hhB..h..h==h=......h=..h=.......................
       (98 lines all free)
19000: ................................................
```

If you want to have the device write it to a file on the device filesystem, then the easiest way to do this is to temporarily capture stdout via dupterm into a BytesIO, then write that to a file.

```
import micropython
import io
import os

s = io.BytesIO()
dup_prev = os.dupterm(s)
micropython.mem_info(1)
os.dupterm(dup_prev)

# Now you can write s.getvalue() to a file
```
