### ISSUE TITLE
How to package the python program into a UF2 file with MicroPython

### ISSUE THREAD

**Issue by marchawake** [micropython/micropython#8676]
How to package the python program into a UF2 file with MicroPython?

**Comment by MarchAwake** [comment]
Thanks a lot @jimmo

**Comment by MarchAwake** [comment]
freezing can create main.py in the filesystem

**Comment by jimmo** [comment]
> freezing can create main.py in the filesystem

Not exactly, frozen files are not in the filesystem. However, you can freeze main.py and use it instead of the filesystem version. This was discussed recently in #8660

**Comment by MarchAwake** [comment]
I start the service in boot.py. What negative impact does this have on MicroPython?

**Comment by robert-hh** [comment]
None. boot.py and main.py are executed one after the other and run in the same context.

**Comment by jimmo** [comment]
> None. boot.py and main.py are executed one after the other and run in the same context.

On ESP32 this is true (there isn't really a lot of point to boot.py on ESP32). However, on STM32, boot.py runs before network and USB init. boot.py should technically only be used for configuring usb, network, (and filesystems to find main.py if necessary).

**Comment by mattytrentini** [comment]
If this is clear now @MarchAwake can you please close this ticket? Thanks!

**Comment by jonnor** [comment]
Clarifications have been provided and no response indicating this did not resolve the issue in 2 years.
