### ISSUE TITLE
win10 cygwin64 stm32 port compile error

### ISSUE THREAD

**Issue by venjani** [micropython/micropython#8703]
I try compile make BOARD=NUCLEO_F401RE V=1 
/bin/sh: -c: line 0: syntax error near unexpected token "("
/bin/sh: -c: line 0: `python3 ../../py/makeqstrdefs.py
make: *** [../../py/mkrules.mk:105: build-NUCLEO_F401RE/genhdr/qstr.i.last] Error 1

**Comment by stinos** [comment]
Can you post the complete output, starting with `make clean`? What GCC toolchain version are you using, what Python version?

**Comment by venjani** [comment]
The GCC Toolchain was C:\Promgram Files(86)... path
I move C:\Arm... path and now ok

**Comment by venjani** [comment]
The problem solved
