### ISSUE TITLE
Build for Pi Pico fails

### ISSUE THREAD

**Issue by dopeyhex** [micropython/micropython#8715]
In micropython/lib/pico-sdk/src/rp2_common/pico_bootrom/include/pico/bootrom.h:120:59: error: array subscript 0 is outside array bounds of «uint16_t[0]» {aka «short unsigned int[]»} [-Werror=array-bounds]

Compiler: g++-11

**Comment by robert-hh** [comment]
That's a bug in the compiler. Use v10.3.1.
