### ISSUE TITLE
uzipfile functionality

### ISSUE THREAD

**Issue by rohan-ahluwalia** [micropython/micropython#8757]
I was curious if micropython had uzipfile functionality. I know that there is uzlib functionality but was attempting to figure out a way to look into zipped files and extract data? If someone knows if this is possible with uzlib or if there is another way to implement this let me know!

**Comment by jonnor** [comment]
I accidentally a zipfile module here, based on CPython - https://github.com/jonnor/micropython-zipfile
There is also a much more minimalistic implementation here, https://github.com/maruno/mpy-blox/blob/master/mpy_blox/zipfile.py
So I think we can close this now :)
