### ISSUE TITLE
SOS!

### ISSUE THREAD

**Issue by QiaoTuCodes** [micropython/micropython#8786]
how can i  make firmware file with stm32f410c8 ?

**Comment by jimmo** [comment]
This is the MicroPython bug tracker. Please try and keep this for reporting bugs, feature requests, or issues with the documentation.

The stm32f410c8 has 64kiB flash and 32kiB ram and is on the small end of what MicroPython can support. You will have to disable most features (e.g. MICROPY_CONFIG_ROM_LEVEL_MINIMUM) to get it to work (and likely you will need to disable the compiler and just use frozen code -- the minimal feature set with the compiler disabled is about 45kiB).

You need to define a board definition (copy one of the existing ones and modify as appropriate, e.g. https://github.com/micropython/micropython/tree/master/ports/stm32/boards/NUCLEO_F411RE). And see ports/minimal/mpconfigport for the minimal configuration (turn off MICROPY_ENABLE_COMPILER).
