### ISSUE TITLE
1.19.1 add ulab fail

### ISSUE THREAD

**Issue by wangshujun-tj** [micropython/micropython#8802]
[ 81%] Generating ../../genhdr/qstrdefs.generated.h
ERROR: Call to MP_REGISTER_MODULE(MP_QSTR_ulab, ulab_user_cmodule, MODULE_ULAB_ENABLED) should be MP_REGISTER_MODULE(MP_QSTR_ulab, ulab_user_cmodule)

make[3]: *** [esp-idf/main/CMakeFiles/__idf_main.dir/build.make:71：genhdr/moduledefs.h] 错误 1
make[3]: *** 正在删除文件“genhdr/moduledefs.h”

make code
export USER_C_MODULES=~/myesp32build/ulab/code/micropython.cmake

**Comment by dlech** [comment]
The error message explains how to fix the problem. Change `MP_REGISTER_MODULE(MP_QSTR_ulab, ulab_user_cmodule, MODULE_ULAB_ENABLED)` to `MP_REGISTER_MODULE(MP_QSTR_ulab, ulab_user_cmodule)`.
