### ISSUE TITLE
every port folder come with a script so it clones only the submodules it requires and nothing else

### ISSUE THREAD

**Issue by aguaviva** [micropython/micropython#8825]
My plan it to build the ESP32 port, however when I update the submodules I am getting libs for the pico, smt32 and other bits I won't need.

Could every port folder come with a script so it clones only the submodules it requires and nothing else?

Thanks

**Comment by dpgeorge** [comment]
If you run `make submodules` in a port directory it will init only the required submodules.  You can use `make BOARD=xxx submodules` as well.

**Comment by raulamd** [comment]
Much appreciated the quick response, I just found this is documented in the main readme.md
