### ISSUE TITLE
ESP8266, How to change the gblic version of micropython ?

### ISSUE THREAD

**Issue by MarchAwake** [micropython/micropython#8826]
ubuntu@ubuntu-22:~/下载/micropython-1.18/ports/esp8266$ docker run --rm -v $HOME:$HOME -u $UID -w $PWD larsks/esp-open-sdk make -j16
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
CC machine_bitstream.c
CC machine_pin.c
CC machine_rtc.c
CC machine_adc.c
CC machine_uart.c
CC machine_wdt.c
CC machine_hspi.c
CC modesp.c
CC modnetwork.c
CC modutime.c
CC moduos.c
CC ets_alt_task.c
CC fatfs_port.c
CC posix_helpers.c
CC hspi.c
/home/ubuntu/下载/micropython-1.18/mpy-cross/mpy-cross: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /home/ubuntu/下载/micropython-1.18/mpy-cross/mpy-cross)
/home/ubuntu/下载/micropython-1.18/mpy-cross/mpy-cross: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /home/ubuntu/下载/micropython-1.18/mpy-cross/mpy-cross)
MPY flashbdev.py
error compiling /home/ubuntu/下载/micropython-1.18/ports/esp8266/modules/flashbdev.py:
CC ../../lib/oofatfs/ff.c
CC ../../lib/oofatfs/ffunicode.c
make: *** [../../py/mkrules.mk:156: build-GENERIC/frozen_content.c] Error 1
make: *** Waiting for unfinished jobs....

ubuntu@ubuntu-22:~/下载/micropython-1.18/ports/esp8266$ ldd --version
ldd (Ubuntu GLIBC 2.35-0ubuntu3) 2.35
Copyright (C) 2022 自由软件基金会。
这是一个自由软件；请见源代码的授权条款。本软件不含任何没有担保；甚至不保证适销性
或者适合某些特殊目的。
由 Roland McGrath 和 Ulrich Drepper 编写。

**Comment by jimmo** [comment]
I think this means that mpy-cross was compiled on the host, and then you're using it inside the docker container. You need to build mpy-cross inside the container first (and `make clean` it first to force it to rebuild if you've already built it).

See https://github.com/micropython/micropython/tree/master/ports/esp8266#build-instructions for more information.

FYI this is MicroPython's issue tracker. As per the template text, "how to" questions are better suited to the forum.
