### ISSUE TITLE
Drop Python 2 support in build scripts?

### ISSUE THREAD

**Issue by dlech** [micropython/micropython#8850]
I see we still have one CI build that is using Python 2. Python 2 has been out of support since Jan. 1, 2020. Do we really need to keep supporting it? (I'm starting to forget how to write code that is compatible with both 2 and 3 since I haven't had to do that for years now.)

**Comment by dpgeorge** [comment]
I think we should keep Python 2 support for a while longer.  There are lots of old systems out there that still use it and are hard to upgrade.  I don't think it's that hard to support for just the core build scripts.  CI will catch any issues here.

**Comment by dlech** [comment]
ok
