### ISSUE TITLE
Pypi mpy-cross returns zero when it encounters IndentationError.

### ISSUE THREAD

**Issue by RSC-Games** [micropython/micropython#8851]
I was writing a toolchain in CPython to compile a lot of MicroPython code. I noticed that while compiling, when an IndentationError occurred, mpy-cross returned zero exit status, so my toolchain continued compiling the code even though there were errors. This does not happen with other errors (like SyntaxError).

Minimal Example (hello_world.py):
```
def hello_world():
	print("Hello World (Tab indent.)")

	# Print another hello world.
    if True:
   		print("Hello World (4 spaces indent)")

if __name__ == "__main__":
  hello_world()
```

bash:
```
$ pip install mpy-cross-1.19.1
~snip~
$ python
>>> import os
>>> print(os.system("mpy-cross hello_world.py"))
Traceback (Most recent call last):
  File "hello_world.py", line 4
IndentationError: unindent does not match any outer indent level
0
>>>

```

Captured Logs from my toolchain:
```
INFO: mpy-cross: Starting cross compiler.
INFO: mpy-cross: Capabilities of the compiler:
MicroPython v1.19.1 on 2022-06-18; mpy-cross emitting mpy v6
INFO: mpy-cross: Start compilation

INFO: mpy-cross: Compiling file task_manager.py
INFO: spc-fw: Exit status of mpy-cross thread: 0
INFO: mpy-cross: Compiling file __init__.py
Traceback (most recent call last):
  File "firmware_build/bin/Util/task_manager.py", line 157
IndentationError: unindent doesn't match any outer indent level

INFO: mpy-cross: Compiling file settings.py
INFO: spc-fw: Exit status of mpy-cross thread: 0
INFO: mpy-cross: Compiling file constants.py
Traceback (most recent call last):
  File "firmware_build/bin/Iface_Gen_1/settings.py", line 99
IndentationError: unexpected indent
INFO: spc-fw: Exit status of mpy-cross thread: 0
INFO: mpy-cross: Compiling file storage.py
INFO: spc-fw: Exit status of mpy-cross thread: 0
INFO: mpy-cross: Compiling file CONFIG_REV1.py
Traceback (most recent call last):
  File "firmware_build/bin/Iface_Gen_1/storage.py", line 63
IndentationError: unindent doesn't match any outer indent level
INFO: spc-fw: Exit status of mpy-cross thread: 0

INFO: mpy-cross: Source compilation finished.

... and build completes successfully.
```

[EDIT]: Minimal example is broken. Trying to find a working one.

If possible, could you guys backport the fix to mpy-cross 1.18 because some of my devices are running 1.18 and I do not have access to my micropython development machine right now. If not, then I can just find the time to rebuild my custom micropython
firmware.

**Comment by dlech** [comment]
The Python package you are using is probably https://gitlab.com/alelec/mpy_cross, so bugs with that package should be reported there.

Also, it has a Python API, so if you are using it from Python, then you shouldn't call it with `os.system()`, just use the Python API directly.

**Comment by dpgeorge** [comment]
Running plain `./mpy-cross` on a file with indentation error does return an error code (value 1) to the shell.  So the problem is not in this repository.

**Comment by RSC-Games** [comment]
I only encountered this issue with my implementation on replit.com. When I downloaded the files and ran them on my Windows PC the code worked perfectly.
