### ISSUE TITLE
urequests Module missing when building for Pico-W myself

### ISSUE THREAD

**Issue by WaGi-Coding** [micropython/micropython#8852]
Hey i just tried to build the firmware for the PICO_W from current source on Ubuntu. Everything works fine, it shows as Pico W board etc.

However, i cannot use urequests like i can in the official Pico W Build. I followed the Readme files. Did i might missed something?

Greetings

**Comment by WaGi-Coding** [comment]
I saw it's part of the micropython-lib repo. But i just wonder how i can include it with the firmware like the official PicoW MP firmware does

**Comment by daviesian** [comment]
I had this issue today too, and resolved it as follows: 

You need to clone the `micropython-lib` repo next to the `micropython` repo. So, if you have something like `~/dev/micropython`, you should also have `~/dev/micropython-lib`. Then delete, recreate and reinitialise your build directory and rebuild the firmware from scratch, and the `urequests` package [should be included](https://github.com/micropython/micropython/blob/master/ports/rp2/boards/PICO_W/manifest.py#L7). That worked for me!

**Comment by WaGi-Coding** [comment]
> I had this issue today too, and resolved it as follows:
> 
> You need to clone the `micropython-lib` repo next to the `micropython` repo. So, if you have something like `~/dev/micropython`, you should also have `~/dev/micropython-lib`. Then delete, recreate and reinitialise your build directory and rebuild the firmware from scratch, and the `urequests` package [should be included](https://github.com/micropython/micropython/blob/master/ports/rp2/boards/PICO_W/manifest.py#L7). That worked for me!

This did the trick. Many many thanks
