### ISSUE TITLE
DS3231 reset issue

### ISSUE THREAD

**Issue by garudaonekh** [micropython/micropython#8886]
Hi,
I have no idea why my DS3231 reset to year 1900 after a few uses and a few case it goes to 2100 or something. The battery is new and the voltage to the DS3231 is 5v.
This happen after a few code update or debug. My board is A9 Gprs.

**Comment by dpgeorge** [comment]
This doesn't sound like a problem with MicroPython.  If you think it is, please reopen the issue with details on the code you are running and MicroPython version.
