### ISSUE TITLE
Feature request SSL/ussl Arduino Nano RP2040 (rp2)

### ISSUE THREAD

**Issue by covidium** [micropython/micropython#8898]
It seems that the current build for Arduino Nano RP2040 (rp2) doesn't have ussl/SSL enabled during the build making it useless if one would like to contact a web server over HTTPS.
I was able to c/p the usocket.py file available in the micropython-lib repo, but this one will automatically try to load the ussl/ssl module for creating the requests over TLS.

Is it possible to recompile or enable the ussl/ssl module for a new build? 
Thanks

**Comment by dpgeorge** [comment]
Fixed by c5563aa024c60c6da1ebe79e97f2307b49999499
