### ISSUE TITLE
ESP32-S3 FREERTOS DUAL CORE USE

### ISSUE THREAD

**Issue by TGiles1998** [micropython/micropython#8927]
Hi,

I have been trying to enable the use of both cores for micropython on the ESP32-S3. I have read:

https://github.com/micropython/micropython/issues/4611
https://github.com/micropython/micropython/issues/4895
https://github.com/micropython/micropython/issues/8197
https://github.com/micropython/micropython/pull/7258

Is there a simple flag that I can place in the sdkconfig file to re-enable the use of both cores. I understand that I have to be careful about global variables and if both cores try to access the same one, issues are caused but it would be very useful to run simultaneous tasks on both cores at the same time.

Searching through the files I know that the I2S non blocking uses freertos to assign to a different core but I'm also not sure how this would be implemented. 

Many thanks,

Thomas

**Comment by jimmo** [comment]
> Is there a simple flag that I can place in the sdkconfig file to re-enable the use of both cores.

Unfortunately there is not a simple flag.

> I understand that I have to be careful about global variables and if both cores try to access the same one, issues are caused but it would be very useful to run simultaneous tasks on both cores at the same time.

The issue isn't about Python-level synchronisation as the GIL takes care of that, it's about how tasks are scheduled and interrupted by ISRs.

It would be good to solve this, and https://github.com/micropython/micropython/issues/4895#issuecomment-513615788 (and other discussion in that thread) is still useful to understand the problem.
