### ISSUE TITLE
docs: I don't see machine.SDCard in Micropython 1.19.1 although documented

### ISSUE THREAD

**Issue by zachmoshe** [micropython/micropython#8942]
This page suggests to use `machine.SDCard`, but when I tried a fresh installation of Micropython for rpi pico (from https://micropython.org/resources/firmware/rp2-pico-20220618-v1.19.1.uf2), I don't seem to have an SDCard in the machine module.

>>> import machine
>>> machine.SDCard
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'SDCard'

I found however a driver called sdcard.py under the drivers folder and it seems to work. Did we move sdcard support from `machine` to a dedicated driver? If so - documentation is a bit misleading.

**Comment by robert-hh** [comment]
Not every port and board has the machine.sdcard module. It is only present if the port & board support it. Otherwise sdcard.py can be used, like you did.
Note: Questions like this one are better asked in the forum.

**Comment by sgbaird** [comment]
`sdcard.py` [not on master](https://github.com/micropython/micropython/blob/master/drivers/sdcard/sdcard.py) (as of 2022-11-02). See https://github.com/micropython/micropython/blob/v1.19.1/drivers/sdcard/sdcard.py

**Comment by jonnor** [comment]
The question seems to have been answered. machine.sdcard is available on some ports, https://github.com/micropython/micropython-lib/blob/master/micropython/drivers/storage/sdcard/sdcard.py can be used on other (using SPI peripheral).
