### ISSUE TITLE
Incorrect thousands separator formatting with mpz

### ISSUE THREAD

**Issue by matejcik** [micropython/micropython#8984]
When formatting a mpz number with the built-in thousands separator format specifier `{:,}`, _and_ the first group of digits is 3 long, there is a leading `,` in the result.

Reproducer says it all:
```
>>> number = 123_456_789_123_456_789_123_456_789
>>> "{:,}".format(number)
',123,456,789,123,456,789,123,456,789'
```

Non-mpz numbers do not suffer from the problem.

To fix, move the comma-adding logic before the done-checking loop.
https://github.com/micropython/micropython/blob/963e599ec0d253534eb835ade7020e8ac3d7919b/py/mpz.c#L1714

**Comment by dpgeorge** [comment]
Thanks for the report.  Should now be fixed.
