### ISSUE TITLE
Re-Flash .frozen content without firmware upgrade

### ISSUE THREAD

**Issue by omogenot** [micropython/micropython#9022]
When writing a MicroPython application for a device, in order to a) save as much RAM as possible for its execution, b) possibly "protect" application content, it is a usual practice (I guess) to move most of the application program parts into the .frozen section of the device MicroPython firmware as .mpy files that will be executed on site. And this possibility is brilliant.
However, in order to, eventually, enable the devices to perform a "Over-The-Air" type of upgrade, it would be great to be able, from the application, to re-flash the content of the pseudo-directory .frozen to upgrade this user-defined part of the firmware without having to re-flash the whole firmware. A kind of patch of the flash content.
In essence, it would be to be able to load the content of the `frozen_content.c.obj` file to a specific location to replace the previous one.
I know that it is not as simple as that, but it's the global idea. I don't have enough knowledge on the internals of MicroPython to start this, but I am definitely willing to help if I can.

**Comment by dlech** [comment]
You may also be interested in #8381.

**Comment by dpgeorge** [comment]
This feature has been requested quite a bit and #8381 is the solution that will be adopted.  It's not exactly the same as replacing `frozen_content.c.obj` but it's close enough and has other nice properties (one being that you can update the application and the mapfs filesystem doesn't need to change).
