### ISSUE TITLE
ESP32 can't set AP ssid

### ISSUE THREAD

**Issue by liangfyx** [micropython/micropython#9079]
Board: ESP32
Firmware: esp32-20220618-v1.19.1.bin
Issue: I refer to the official documentation to enable AP mode, but I cannot set ssid.
Detail:
![image](https://user-images.githubusercontent.com/20663717/185793049-0e7f369a-fe77-4930-a7ce-f781670543e3.png)
![image](https://user-images.githubusercontent.com/20663717/185793054-fd6cc3b8-cfcc-478e-8601-c7df1f672d3f.png)

**Comment by marcidy** [comment]
use `essid` instead of `ssid`

```
ap.config(essid='ESP-AP')
```

this is a real issue as the docs are out of line with the code, might just be a doc issue though

**Comment by liangfyx** [comment]
Thank you, I tested it and it works fine~
