### ISSUE TITLE
Multiple i2c.init calls can hang the bus

### ISSUE THREAD

**Issue by dhylands** [micropython/micropython#908]
Link from forum: http://forum.micropython.org/viewtopic.php?f=5&t=231&start=20#p1768

It seems that calling i2c.init multiple times when there are multiple devices on the bus can cause the bus to hang.

I'd like to propose that initializing the bus as MASTER a second time should either fail, or detect that it's already initialized and not reinitialize the HW.

**Comment by dpgeorge** [comment]
I2C has error handling and initialisation has been significantly improved sinc this issue was opened.  In particular, doing i2c.init() multiple times is now ok.  See 74fb5d6932c835f92c6985799e30ea28b6449705.
