### ISSUE TITLE
Create a gc function to return the largest allocatable memory

### ISSUE THREAD

**Issue by dhylands** [micropython/micropython#910]
I think that, in addition to mem_free and mem_alloc, that we should have a function like mem_contig which returns the largest amount of contiguous memory (i.e. size of the largest object which could be allocated).

**Comment by cloudformdesign** [comment]
In the memory manager I'm developing I was planning on adding something like this. It was going to be tm_between(least,  most) where it returns a pointer between least and most. 

I can also implement tm_contig if you would like

**Comment by pfalcon** [comment]
Not a separate function, but since https://github.com/micropython/micropython/commit/749cbaca7f5406e23bbf0009477c73e14fa8a9ff , micropython.mem_info() reports this value.

**Comment by dmartauz** [comment]
It might be useful to have an option to return values currently printed by micropython.mem_info() on 3rd row - e.g. as a tuple of ints. These values could be reported to a backend server and used for heap fragmentation analysis of long-running managed devices running MicroPython.

**Comment by dhylands** [comment]
I think it would be better to have separate functions. If you return a tuple then you need to allocate memory for the tuple.

**Comment by dmartauz** [comment]
That's good point. However having separate but similar functions would increase code size. Another idea is to return the tuple only with a specific argument, e.g. micropython.mem_info(2). What do you think about it?

**Comment by dhylands** [comment]
Increasing the code size in flash wasn't as much of a concern as causing memory to be allocated by calling a function to query about memory.
