### ISSUE TITLE
Issues Reading Files between 7/20 build & 8/30

### ISSUE THREAD

**Issue by michaeka79** [micropython/micropython#9197]
I am trying to do a very simple open a file and read it process. I have a private key from Amazon that was originally encoded as a PEM key but I converted it into a DER key.  with v1.19.1-192 built on 7/20/2022, I am able to open this DER file and read the key into a variable. Starting with the build on 8/30/2022 v1.19.1-345 I get a UnicodeError when I try to read the files.  I have a PEM file for Amazon's CA that reads without an issue it is just the DER key files that appear to now be broken. I'll gladly call myself a noob in this area, but it doesn't seem like anything changed in the coding of Micropython since then that would have caused this kind of issue.  But I'm totally stumped! 

The read I am trying to do is as follows:

keyfile = "PicoTestBed01.private.key.der"
    with open(keyfile, 'r') as f:
        key = f.read()

**Comment by dlech** [comment]
If this is a binary file, open it with `'rb'` instead of `'r'`. If this is a text file, it contains invalid unicode characters.

**Comment by dlech** [comment]
FWIW, the change that triggered this is #9083 .

**Comment by michaeka79** [comment]
I'll gladly accept my noob badge for this one. Thank you! Weird you'd want to be using safe Unicode characters ;)

**Comment by jimmo** [comment]
Thanks @dlech !
