### ISSUE TITLE
ESP32 Slow flash access when PPP active

### ISSUE THREAD

**Issue by ThinkTransit** [micropython/micropython#9266]
When a ppp network link is active on an ESP32 device, writing files to external flash is 40 times slower than when the ppp link is not active.

Tested on ESP32-S3 WROOM modules, ESP32-S3-WROOM-2-N32R8V and ESP32-S3-WROOM-1-N16R8CT

Can be reproduced with the following code.

``` python
from utils import timed_function

f = open("test.txt",'wb+')
 
@timed_function
def file_write_seq_access(blocksize):
    chunk = b'\xff'4000
    for i in range(blocksize//4000):
        f.write(chunk)

file_write_seq_access(512000)

Function file_write_seq_access Time = 9395.923ms
```

Approximately 9 seconds to run after flash erase and mp install

Initiate pp connection
``` python
import network
import time

qw = network.PPP(self.uart)
qw.active(True)
time.sleep(0.5)
qw.connect(authmode=qw.AUTH_PAP, username="", password="")

count = 0
while qw.isconnected == False:
    await asyncio.sleep(1)
    count += 1
    if count > 5:
        raise
logger.debug(f'PPP connected')

```

After ppp link is established perform the same file write test.

``` python
from utils import timed_function

f = open("test.txt",'wb+')
 
@timed_function
def file_write_seq_access(blocksize):
    chunk = b'\xff'4000
    for i in range(blocksize//4000):
        f.write(chunk)

file_write_seq_access(512000)

Function file_write_seq_access Time = 368099.125ms

```
Flash write now takes 368 seconds.

**Comment by Tangerino** [comment]
You are a lucky guy, I never make PPP to work :(

**Comment by ThinkTransit** [comment]
Yes it works but it slows down the esp32 system, I have no idea why, it's very strange.

If you have network connectivity ppp should be easy to connect. On the modem I'm using (ublox sara-r5) it's just one command:

```
'ATD*99***1#\r\n'
```

**Comment by ThinkTransit** [comment]
Can't reproduce anymore on latest versions of IDF, closing as possibly fixed.
