### ISSUE TITLE
Performance regressions since v1.0

### ISSUE THREAD

**Issue by pfalcon** [micropython/micropython#941]
@dpgeorge writes in https://github.com/micropython/micropython/pull/933#issuecomment-60535680:

> Surprisingly, uPy v1.0 is nearly 2 times faster than uPy master.

Other comments there provide more information.

**Comment by dpgeorge** [comment]
@pfalcon do we need this to remain open?

**Comment by danicampora** [comment]
@dpgeorge Any chance you can generate some graphs showing how performance has improved over the last 5 months?

**Comment by dpgeorge** [comment]
Just found this "git build dashboard" for Espruino: http://www.espruino.com/binaries/git/stats.html .

**Comment by pfalcon** [comment]
> @pfalcon do we need this to remain open?

Sorry, missed to reply - I'd consider the info in this ticket too precious to just close it. At the very least it can be moved to a wiki (but then just keep this ticket open sounds good too), and better to somehow be able to automate and re-run such analysis from time to time.

**Comment by dpgeorge** [comment]
> and better to somehow be able to automate and re-run such analysis from time to time.

My plan is to automatically generate the above plots and have them served at micropython.org.  I will (slowly) work on that.

**Comment by dpgeorge** [comment]
Latest data for binary size and pystones from v1.0 to v1.4.2:

![out](https://cloud.githubusercontent.com/assets/6187689/7586054/d31f496c-f8a0-11e4-9be7-77b010ec9eab.png)

**Comment by dpgeorge** [comment]
Data now available in a fancy interactive D3 graph here: http://micropython.org/resources/code-dashboard/

It doesn't yet update automatically.  That's the next thing to do.

Also the dates are wrong.

**Comment by dhylands** [comment]
Very cool

**Comment by pfalcon** [comment]
Looks nice indeed. Can there perhaps be legend that unix/minimal are compiled for arch X? (And the I suggest x86_32, and maybe even arm for minimal ;-) ).

**Comment by dpgeorge** [comment]
Code dashboard updated to include complete data (every revision is now there) and some notes about the details of its generation.

It also updates automatically each day.

Final remaining thing: should I make the scripts and www files available in this or another repo?

**Comment by pfalcon** [comment]
Great work, thanks! Well, it's usually helpful if stuff is open-source, if you consider it's suitable for that. But then there's usually extra work to decide/cleanup/put together, and I imagine that it already took quite a while of your time, so putting it in backlog to come back later may make sense ;-).

**Comment by dpgeorge** [comment]
I can put the "gitstats.sh" script in the tools/ directory; it does all the work of collecting the statistics.  The rest is the www page, which you can actually download yourself by inspecting the html/js/css source.

**Comment by pfalcon** [comment]
Sound good. (I actually regularly find myself scratching my head re: where that adhoc script I used to do <something>, so having it there is less headache ;-) ).

**Comment by danicampora** [comment]
Awesome! Great job Damien!

**Comment by dpgeorge** [comment]
Script to generate the statistics now available in tools/codestats.sh.
