### ISSUE TITLE
esp32s2 usb hang up after machine.lightsleep(xx)

### ISSUE THREAD

**Issue by shaoziyang** [micropython/micropython#9414]
After machine.lightsleep(xx) is called, USB function is suspended without response.

Test board: LOLIN S2 Mini

![图片](https://user-images.githubusercontent.com/1037534/192146808-493d814d-859c-4d9d-a94d-f22b42b890be.png)

**Comment by puppet13th** [comment]
look like same issue as lolin c3 mini.it hang because it uses chip builtin usb otg as uart.

**Comment by jimmo** [comment]
That is to be expected.
