### ISSUE TITLE
Cannot compile CModules into ESP32 firmware

### ISSUE THREAD

**Issue by Nyan256** [micropython/micropython#9468]
I am having an issue compiling CModules into the Micropython ESP32 firmware, or it is compiled but inaccessible somehow
I have the same issue with two external CModules:
```
bitstruct-micropython: https://github.com/peterzuger/bitstruct-micropython
hydrogen-micropython: https://github.com/peterzuger/hydrogen-micropython
```

Because of this I am suspecting the issue may be with Micropython.

The device is a Lilygo LORA32

**The problem:**
After following the process when I console into the ESP32 and try to import the modules, they are not found

```
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 188777542, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:4540
ho 0 tail 12 room 4
load:0x40078000,len:12344
ho 0 tail 12 room 4
load:0x40080400,len:4124
entry 0x40080680
MicroPython v1.19.1 on 2022-09-29; ESP32 module with ESP32
Type "help()" for more information.
>>> 
>>> import hydrogen
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: no module named 'hydrogen'
>>> import bitstruct
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: no module named 'bitstruct'
 ```

**Expectation:**
Expecting to be able to import the modules

**Interestingly during compilation the following lines are shown:**
```
Including User C Module(s) from ../../../../modules/micropython.cmake
Found User C Module(s): usermod_bitstruct, usermod_hydrogen
```

**ESP-IDF specifics:**

```
kirsa@enki ~/Hax/Projects/micropython $ idf.py --version
ESP-IDF v4.2.2

kirsa@enki ~/Hax/Projects/micropython $ printenv | grep IDF
IDF_PYTHON_ENV_PATH=/home/kirsa/.espressif/python_env/idf4.2_py3.9_env
IDF_PATH=/home/kirsa/.esp/esp-idf
IDF_TOOLS_EXPORT_CMD=/home/kirsa/.esp/esp-idf/export.sh
IDF_TOOLS_INSTALL_CMD=/home/kirsa/.esp/esp-idf/install.sh
```

**Directory structure:**
```
Projects/
├── modules/
│   ├── bitstruct-micropython/
│   │   ├── bitstruct/
│   │   │    ├── bitstream.c
│   │   │    ├── bitstream.h
│   │   │    └── bitstruct.c
│   │   ├── micropython.mk
│   │   ├── micropython.cmake
│   │    ...
│   ├── hydrogen-micropython/
│   │   ├── Particle.h
│   │   ├── hydrogen.c
│   │   ├── micropython.mk
│   │   ├── micropython.cmake
│   │    ...
│   └── micropython.cmake
└── micropython/
    ├──ports/
   ... ├──esp32/
      ...
```

**cmake files:**
```
kirsa@enki ~/Hax/Projects/modules $ cat micropython.cmake 
include(${CMAKE_CURRENT_LIST_DIR}/bitstruct-micropython/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/hydrogen-micropython/micropython.cmake)
```
```
kirsa@enki ~/Hax/Projects/modules/bitstruct-micropython $ cat micropython.cmake
add_library(usermod_bitstruct INTERFACE)

target_sources(usermod_bitstruct INTERFACE
    ${CMAKE_CURRENT_LIST_DIR}/bitstruct/bitstruct.c
    ${CMAKE_CURRENT_LIST_DIR}/bitstruct/bitstream.c
)

target_include_directories(usermod_bitstruct INTERFACE
    ${CMAKE_CURRENT_LIST_DIR}/bitstruct/
)

target_link_libraries(usermod INTERFACE usermod_bitstruct)
```
```
kirsa@enki ~/Hax/Projects/modules/hydrogen-micropython $ cat micropython.cmake 
add_library(usermod_hydrogen INTERFACE)

target_sources(usermod_hydrogen INTERFACE
    ${CMAKE_CURRENT_LIST_DIR}/hydrogen.c
)

target_include_directories(usermod_hydrogen INTERFACE
    ${CMAKE_CURRENT_LIST_DIR}
)

target_link_libraries(usermod INTERFACE usermod_hydrogen)
```

**Compile commands tried:**
(between each I did a make clean in ports/esp32/)
```
kirsa@enki ~/Hax/Projects/micropython $ make -C ports/esp32/ USER_C_MODULES=../../../../modules/micropython.cmake
```
```
kirsa@enki ~/Hax/Projects/micropython $ make -C ports/esp32/ USER_C_MODULES=../../../../modules/micropython.cmake CFLAGS_EXTRA=-DMODULE_BITSTRUCT_ENABLED=1
```
```
kirsa@enki ~/Hax/Projects/micropython $ make -C ports/esp32/ USER_C_MODULES=../../../../modules/micropython.cmake CFLAGS_EXTRA=-DMODULE_HYDROGEN_ENABLED=1
```
```
kirsa@enki ~/Hax/Projects/micropython $ make -C ports/esp32/ USER_C_MODULES=../../../../modules/micropython.cmake CFLAGS_EXTRA=-DMODULE_BITSTRUCT_ENABLED=1,-DMODULE_HYDROGEN_ENABLED=1
```

**Steps to replicate:**
```~/Hax/Projects $ git clone --branch v1.19.1 https://github.com/micropython/micropython.git```
```~/Hax/Projects $ cd micropython/mpy-cross```
```~/Hax/Projects/micropython/mpy-cross $ make```
```~/Hax/Projects/micropython/mpy-cross $ cd ../ports/esp32/```
```~/Hax/Projects/micropython/ports/esp32 $ make submodules```
```~/Hax/Projects/micropython/ports/esp32 $ cd ../../```
```~/Hax/Projects/micropython $ make -C ports/esp32/ USER_C_MODULES=../../../../modules/micropython.cmake```
```~/Hax/Projects/micropython $ esptool.py -p /dev/ttyACM0 erase_flash```
```~/Hax/Projects/micropython $ esptool.py -p /dev/ttyACM0 -b 460800 --before default_reset --after hard_reset --chip esp32  write_flash --flash_mode dio --flash_size detect --flash_freq 40m 0x1000 ports/esp32/build-GENERIC/firmware.bin```

**Here is the full log of my build process:**
[log.txt](https://github.com/micropython/micropython/files/9675762/log.txt)

Many thanks for your time and let me know if there is anything I am doing wrong, or anything else I can try to support troubleshooting.

-Kirsa

**Comment by jimmo** [comment]
Thanks for the detailed report @Nyan256   Can confirm this is not an issue in MicroPython though.

I was able to make this work on the Unix port and ESP32, but note four things:
 - You must enable the modules with the `-DMODULE_BITSTRUCT_ENABLED=1` flags. They are not enabled by default.
 - Rather than comma separating, they should be space-separated. e.g. `"CFLAGS_EXTRA=-DMODULE_BITSTRUCT_ENABLED=1 -DMODULE_HYDROGEN_ENABLED=1"`.
 - `CFLAGS_EXTRA` won't do anything on esp32, because our Make wrapper won't pass this to the IDF build. You should instead set these variables in your `micropython.cmake`.
 - The current latest version of both of these libraries will only work against the latest micropython (mostly due to the recent object type definition changes). If you want to compile against v1.19.1 you'll need an older version of the modules.

Here's what I had in micropython.cmake that worked for esp32 on latest micropython:

```
include(${CMAKE_CURRENT_LIST_DIR}/../../src/github.com/peterzuger/bitstruct-micropython/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/../../src/github.com/peterzuger/hydrogen-micropython/micropython.cmake)

target_compile_definitions(usermod_bitstruct INTERFACE
    MODULE_BITSTRUCT_ENABLED=1
)

target_compile_definitions(usermod_hydrogen INTERFACE
    MODULE_HYDROGEN_ENABLED=1
)

set(MICROPY_CPP_FLAGS_EXTRA "-DMODULE_BITSTRUCT_ENABLED=1" "-DMODULE_HYDROGEN_ENABLED=1")
```

I wasn't initially able to get libhydrogen to compile on esp32 though -- I'm not sure the fix in https://github.com/peterzuger/hydrogen-micropython/commit/1a70f5fab190f9d08af05204c036d2aa7f2c6cf7 works.
(I got it to build by modifying `random.h` to force `#define ESP32` (to make the QSTR build work) and then `random/esp32.h` to use `mp_hal_delay_ms`).

@peterzuger From looking at your two repos it seems that ESP32 is supposed to be supported, so perhaps I've missed something obvious.

(This is actually the second time today we've had someone run into issues with the make wrapper not passing variables through... see #9459. For at least CFLAGS_EXTRA, we could probably make this work in ports/esp32/Makefile ?)

**Comment by jimmo** [comment]
Thanks @peterzuger -- can confirm this now works with the latest version of your repos on an ESP32.

```
$ mpr
MicroPython v1.19.1-458-g65ab0ec91 on 2022-09-30; ESP32 module with ESP32
Type "help()" for more information.
>>> import hydrogen
>>> import bitstruct
>>> 
```

**Comment by Nyan256** [comment]
Thanks @jimmo & @peterzuger! bitstruct-micropython is now working for me :-D
(do not need hydrogen right now, just was using it for troubleshooting)
I would most likely not figured it out on my own, so glad for the assistance so that I can do bit-manipulation way easier.

```
MicroPython v1.19.1 on 2022-09-30; ESP32 module with ESP32
Type "help()" for more information.
>>> 
>>> from bitstruct import *
>>> pack('u1u3u4s16', 1, 2, 3, -4)
b'\xa3\xff\xfc'
>>> unpack('u1u3u4s16', b'\xa3\xff\xfc')
(1, 2, 3, -4)
>>> calcsize('u1u3u4s16')
24
>>> 
```
