### ISSUE TITLE
How to compile files in addition to .py files into the micropython firmware?For example, I need to compile the Pi16x16 .raw file into the firmware.

### ISSUE THREAD

**Issue by iBoundary** [micropython/micropython#9588]
How to compile files in addition to .py files into the micropython firmware?For example, I need to compile the Pi16x16 .raw file into the firmware.

**Comment by jimmo** [comment]
@iBoundary Please see my reply here https://github.com/orgs/micropython/discussions/9587  (and no need to raise an issue when you've already raised a discussion post).
