### ISSUE TITLE
Pseudo-random number generator

### ISSUE THREAD

**Issue by pfalcon** [micropython/micropython#965]
It's nice that stmhal port has hw random generator, but we really should implement port-independent reproducible PRNG. I can think of following choices:

1. Implement exact same algo as in CPython. This will help achieve 100% reproducibility for testing, etc.
2. Implement the smallest (by code size) reasonable PRNG.
3. Implement cryptographically-secure PRNG.

**Comment by dpgeorge** [comment]
Point 2 above (Implement the smallest (by code size) reasonable PRNG) was implemened in a58a91eb04c50daafb31228a79f6752374338c5e using Yasmarang generator.
