### ISSUE TITLE
docs: Pin.toggle() method is not documented

### ISSUE THREAD

**Issue by millosolomillo** [micropython/micropython#9652]
`Pin.toggle()` method works (at least for RP2040 platform) but it is not documented here: 

https://docs.micropython.org/en/latest/library/machine.Pin.html#methods

**Comment by robert-hh** [comment]
It's available only at the rp2 and samd port, as you know.

**Comment by millosolomillo** [comment]
Already opened a PR at #9653, sorry :sweat_smile:

**Comment by uPesy** [comment]
I really think board ports should be more harmonized for basic fonctions, otherwise we lost the theorical advantage of uPython : one code that works on different hardware ...

**Comment by jonnor** [comment]
I do not consider toggle to be core. It is trivial to use `pin.value(not pin.value())`. Proposing to close.

**Comment by projectgus** [comment]
> I do not consider toggle to be core. It is trivial to use `pin.value(not pin.value())`. Proposing to close.

I agree, but I think we at least should document it on the ports where it's already implemented.
