### ISSUE TITLE
UDP socket send with cc3000 module locks up when done CPU bound

### ISSUE THREAD

**Issue by cpwolff** [micropython/micropython#973]
Hello,

below code causes a hang with one or two udp messages being sent:

```
wifi = network.CC3k(pyb.SPI(1), pyb.Pin('X5'), pyb.Pin('X4'), pyb.Pin('X3'))
wifi.connect('TS-OO', '****')
time.sleep(4)
s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
s.connect(('10.170.241.6', 2222))

while True:
  s.send("some text")
  #time.sleep(0.001)
```

If the time.sleep is enabled then there is no hang and udp messages are sent continuously. 
The way `SpiResumeSpi()` is handled may be the cause in function `hci_unsolicited_event_handler` in file evnt_handler.c 

`HostFlowControlConsumeBuff()` in socket.c shows that all 6 buffers are consumed and that `tSLInformation.usNumberOfFreeBuffers` is not increased because the SPI interface seems to be disabled.

Best regards
Carl.

**Comment by dpgeorge** [comment]
There has not been any progress on this issue and likely won't be since the CC3000 is quite outdated.  Any users encountering this issue can use the work-around of adding a small delay in the loop.
