### ISSUE TITLE
Need a way to mark differences from CPython in docs

### ISSUE THREAD

**Issue by pfalcon** [micropython/micropython#983]
Subj. This would apply to discrepancies, extensions, etc. Need just some markup pattern, ideally simple, but which would render visibly to a user.

And this probably should go hand in hand to providing link to upstream CPython documentation for a function (which should save us a lot of typing - if we really want to have all functions documented).

**Comment by dpgeorge** [comment]
As discussed above, differences use the "adminition" tag combined with a "class", and this is used in the docs.
