### ISSUE TITLE
nrf: download_ble_stack.sh failing to download SD binaries.

### ISSUE THREAD

**Issue by jimmo** [micropython/micropython#9866]
Something has changed in `https://www.nordicsemi.com/api/sitecore/Products/MedialibraryZipDownload2` that now returns a 403 page with  "www.nordicsemi.com needs to review the security of your connection before proceeding".

The URLs are still correct and they work in the browser, but I guess something is triggering abuse protection. Not sure exactly, when I copy the successful requests from Chrome devtools as curl commands, they fail in curl.

This is causing the nRF build to fail in CI.

@glennrub Do you have any idea what might have changed or how we can work around this? Thanks

**Comment by glennrub** [comment]
@jimmo 
I tried to run the script myself, and it works for me (wget version 1.19.4). However, I'll check a bit if it is possible do download using an alternate method.

**Comment by dpgeorge** [comment]
The nrf CI of recent PRs seem to work again...

**Comment by jimmo** [comment]
OK thanks @glennrub -- looks like this was just a temporary thing. Sorry for the noise!
