### ISSUE TITLE
ESP8266 port needs wifi

### ISSUE THREAD

**Issue by dpgeorge** [micropython/micropython#992]
The ESP8266 port gives a Python REPL over UART, but there is currently no interface to the wifi capabilities of the chip.  This issue is intended to point potential contibutors in the right direction for implementing wifi.

Wifi bindings will be most useful if they fit in the standard POSIX mould of socket, connect, accept, bind listen, send, recv, etc.  These functions can then be made available in the standard Python socket library.

Configuration functions, like list-access-points, and set-wpa-password, need to go in a dedicated ESP wifi driver, which is available to Python scripts from the network module.

Before any Python bindings are made, there are 2 main categories of C functions that need to be written:

1. Functions to configure the wifi, set IP, etc.

2. Functions to mimic the POSIX socket, connect, accept, bind, listen, send, recv functions.

Once these C functions exist, bindings to Python scripts is straight forward (and can be copied from stmhal port).

Usage of the wifi within a script will then look something like:
```python
import network
wifi = network.ESP8266() # create wifi driver
wifi.listap() # list access points
wifi.connect('ssid', 'password') # connect to an access point

import socket
s = socket.socket()
s.connect(('192.168.0.1', 8080))
s.send('some data')
```
See issue #876 for background on this scheme.

**Comment by pfalcon** [comment]
> The ESP runs a very limited OS, which schedules tasks in a cooperative, event-triggered/callback fashion. This means that any code you want to run can only run for a short time and must then return complete control to the OS, so that other tasks can be called.

Ok, telling that, listening to it, and knowing it theoretically is apparently not enough to grasp the depth of it. Because everything, everything is even-driven. Starting from user_init() - it's not a funky name for main(), it's a callback user may use to initialize his stuff - even before system is fully initialized, like wifi subsystem, for example call to wifi_station_scan() fails. Ok, there's workaround to get control after wifi is initialized - system_init_done_cb(). From its callback, wifi_station_scan()  can be called, but again, it's just a callback and should return quickly. Staying in system_init_done_cb()'s callback causes havoc, for example, wifi_station_scan()'s callback locks up.

So, next step would be to make repl a coroutine - instead of calling stdin_rx_chr() in a loop, it will be fed character by character from external event loop.

**Comment by ARMWorks** [comment]
A couple knowledgeable folks have told me the 8266 lacks some features
(security?) needed for good wifi, as in industrial apps. I had asked how TI
will keep selling 3100/3200 parts at $9 a chip.

Any info about this?

**Comment by dpgeorge** [comment]
> apparently not enough to grasp the depth of it. Because everything, everything is even-driven.
> ...
> Staying in system_init_done_cb()'s callback causes havoc

Yep, the ESP8266 is pretty deeply set in its ways.  Yes, I tried using system_init_done_cb but, as you point out, it doesn't work either.

> So, next step would be to make repl a coroutine - instead of calling stdin_rx_chr() in a loop, it will be fed character by character from external event loop.

Yes, that's the thought I had and where I stopped to move on to other things :)

Seriously, is it worth doing this?  Alternatives: 1) use RTOS version of SDK; 2) abandon it in favour of a better wifi solution.

**Comment by danicampora** [comment]
I vote for option number 2 ;-). The CC3200 port is almost ready to go live, the FTP server is already working super solid.

**Comment by dpgeorge** [comment]
> I had asked how TI will keep selling 3100/3200 parts at $9 a chip. Any info about this?

I don't know much about TI's retail activities.  The CC3200 is getting support from @danicampora which will hopefully make it into this repo soon.  Following that, CC3100 should be relatively easy to support.  Do you know of good CC3100 modules out there that are cheap and small (like the Adafruit CC3000 breakout)?

**Comment by pfalcon** [comment]
> Seriously, is it worth doing this?

Refactoring one function? Why not? ;-) Though I dunno who/when would do it. But it's interesting exercise in program control flow transformation ;-).

> Alternatives: 1) use RTOS version of SDK;

As you point yourself, that may solve some problems, but bring other. Also, it's unclear how tested and stable it is, how well supported, etc.

> 2) abandon it in favour of a better wifi solution.

Well, I didn't start esp8266 port ;-). I treat it as a testing ground for uPy portability and scalability (just as many other ports). As for better wifi, ah, they all the same...

**Comment by danicampora** [comment]
The CC3100 modules are not yet available, but they should be soon. Remember that both chips (CC3200 and CC3100) are quite new and productions quality samples were made available only 3 months ago.

**Comment by ARMWorks** [comment]
I saw TI CC3100 dev boards yesterday for about $45 listed from TI. I didn't
check costs in distribution - the ad caught be on FaceBook and I'll check
it again.

No stock
http://www.ti.com/tool/tidc-cc3100modboost?keyMatch=cc3100%20modules&tisearch=Search-EN

Modules not available
http://www.ti.com/tool/cc3100boost?keyMatch=cc3100%20modules&tisearch=Search-EN

Oh well.

**Comment by blmorris** [comment]
@danicampora, @ARMWorks -
> The CC3100 modules are not yet available, but they should be soon. Remember that both chips (CC3200 and CC3100) are quite new and productions quality samples were made available only 3 months ago.

Strange, I have two of the CC3100BOOST modules which I purchased from Digikey about two months ago. I even managed to test them with the pyboard thanks to some code provided by user nelfata from the micropython forum: http://forum.micropython.org/viewtopic.php?f=2&t=401

He ask me to post it to github for him: https://github.com/blmorris/micropython-cc3100

Unfortunately it is a bit beyond me to extend it, so I have moved on for now. The boards belong to my employer but I might be able to pass them along to someone better able than me to develop the micropython drivers for them.
-Bryan

**Comment by danicampora** [comment]
Yes the CC3100 BOOST is available since a while ago, but I think that @dpgeorge was talking about something like the adafruit module, which could be used for production. The CC3100 BOOST is more like a development board.

But yes, that CC3100 board is one of the options available now.

**Comment by danicampora** [comment]
> He ask me to post it to github for him: https://github.com/blmorris/micropython-cc3100

Cool, that can be combined with what I have done for the CC3200.

**Comment by blmorris** [comment]
@danicampora 
> Cool, that can be combined with what I have done for the CC3200.

Great, I hope it helps. Nadim will be happy to know his code is getting used. And as I suggested to him, I can compile and test code for the CC3100, and even tweak things a bit for debugging, though my C coding skills are not very strong.

At risk of straying even further off the original topic of the thread, I wonder if there is a reason that CC3100 dev boards have been slow in coming. The Adafruit board uses the CC3000 module from TI rather than the chip itself, it seems like it would be a minor design change to the CC3000 breakout board to adapt it to the CC3100 module. 
Mouser even has CC3100MOD and CC3200MOD parts in stock, although that may be very new: 
http://www.mouser.com/ProductDetail/Texas-Instruments/CC3100MODR11MAMOBT/?qs=sGAEpiMZZMsRr7brxAGoXU2q05xFRfh6eOuPsiHRKqpryzsOv9jNCA%3d%3d

Maybe the hobby hardware developers have just been waiting for the modules to reach the market to develop their breakout boards. If I had known two months ago that this would be the situation I might have adapted the Adafruit design for the CC3100MOD and built up a few myself. I suppose I could just ask them directly…
-Bryan

**Comment by igrr** [comment]
Regarding task switching with the ESP SDK: I have implemented something similar in my Arduino port for esp8266 to support blocking reads and writes. I'm not familiar with python internals (I.e. REPL) but I have a feeling that this approach should work here as well. Basically I save registers and move the stack pointer on entry/exit to the user task. This way it is possible to yield(); to the OS at any point in the code.

**Comment by pfalcon** [comment]
@dpgeorge: Another issue with ESP port is that vendor SDK tries to define its own versions of C99 types. I see that in uart.c, you avoid that by not mixing uPy and esp8266 sdk includes. But following this route further may be cumbersome. Would you prefer me to patch vendor includes in esp-open-sdk (one drawback of that is it will complicate vendor sdk version upgrades a bit - btw, I've set 0.9.4 as current in esp-open-sdk, now that I see basic wifi functionality working when built against it).

**Comment by igrr** [comment]
@pfalcon Something along these lines should do the trick: https://github.com/igrr/atproto/blob/master/target/esp8266/c_types.h.diff

**Comment by pfalcon** [comment]
@igrr: Sure. The question whether/how to do it.

**Comment by dpgeorge** [comment]
> Basically I save registers and move the stack pointer on entry/exit to the user task. This way it is possible to yield(); to the OS at any point in the code.

Yes, this is certainly do-able.  You are implementing your own task-switching code.

> Another issue with ESP port is that vendor SDK tries to define its own versions of C99 types.

Yeah, it's a right pain that!

> Would you prefer me to patch vendor includes in esp-open-sdk

There is no elegant solution to this, so, yes, if you are willing to maintain this patch then please go ahead and do this.  It would certainly help a lot interfacing to their library code.

**Comment by pfalcon** [comment]
Ok, so esp8266 port now has basic facilities to properly integrate into module OS cooperative multitasking. Further steps required:

* Start implementing [network](http://docs.micropython.org/en/latest/library/network.html#module-network) module.
* esp8266 SDK callbacks don't support passing "user data" to callbacks, so we need to support generating trampolines to pass such data as needed to implement callbacks in Python.

**Comment by pfalcon** [comment]
>>    Isn't this the same as what I suggested above: saving the entire C stack at points where we need to return control to the OS, and then restoring the stack when we get called again? Whatever this implementation is called, it needs a fair bit of RAM for the stack.
> I cannot assess details now, but generally, Python coroutines are analogs of callbacks, where control flow destination is just implicit instead of explicit. CPython's asyncio implementation is layered exactly that way: on event loop level, there're only callbacks, coroutine support is encapsulated in Task object, which would work with any compliant implementation of event loop.

Ok, this is important topic which I didn't want to discuss without ability to test actual usecases. Well, now there's something to play it. Unfortunately, my results are less inspiring than I wanted. As this ticket is already overloaded, and because any solution to the issue appears to require extensions to Python, I posted it here: http://forum.micropython.org/viewtopic.php?f=3&t=501

**Comment by pfalcon** [comment]
> Another issue with ESP port is that vendor SDK tries to define its own versions of C99 types.

Patch to fix that pushed to esp-open-sdk.

**Comment by pfalcon** [comment]
Btw, I've got an idea how to support normal POSIX sockets w/o RTOS and bloat like that: just implement no-blocking mode. That's part of the API, so who would dare to say that's not real sockets? ;-)

**Comment by dpgeorge** [comment]
Fair enough!

**Comment by roger-** [comment]
@pfalcon

That sounds good, but it would also be nice to have callbacks.

**Comment by roger-** [comment]
@dpgeorge:

Heads up that [Arduino now has ESP8266 support](https://github.com/esp8266/Arduino), including WiFi.

**Comment by pfalcon** [comment]
ESP8266 SDK 1.1.0 was (re)released under MIT license today: http://bbs.espressif.com/viewtopic.php?f=5&t=481 .

**Comment by pfalcon** [comment]
@dpgeorge, @atalax: I'm again hit by an issue when esp8266 serial programming speed is awful. I'd appreciate if you could post your figures at https://github.com/themadinventor/esptool/issues/44

**Comment by dpgeorge** [comment]
ESP8266 port now has proper wifi.
